### ISSUE TITLE
Add Unicode/utf-8 support for codenames

### ISSUE THREAD

**Issue by toholdaquill** [freedomofpress/securedrop#1000]
In order to make issue #999 solvable, SecureDrop would first need to implement support for Unicode/utf-8 codenames.

It may (or may not) make sense to do this in conjunction with issue #997, depending on the amount of work involved.

**Comment by eloquence** [comment]
As far as we know, now that we're on Python 3, there are no restrictions that would prevent us from supporting UTF-8 codenames other than the issue identified in #1001. If we discover other issues in resolving #999, we can address as part of that. Closing.
