### ISSUE TITLE
File and directory permissions should be declared consistently

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1006]
There are a few tasks where the Ansible config is explicitly declaring permissions that don't match up on the host. The serverspec tests in #1002 caught a few of these, such as:

```
- name: ensure send_encrypted_alarm script is present
  template:
    src: send_encrypted_alarm.sh
    dest: /var/ossec/send_encrypted_alarm.sh
    mode: 775
    owner: ossec
    group: root
  tags:
    - procmail
    - permissions
```

At a glance, it looks like that tasks ensures sets permissions on `/var/ossec/send_encrypted_alarm.sh` to `0775`. Not so:

```
root@mon-staging:~# stat -c %a /var/ossec/send_encrypted_alarm.sh
1407
```

The culprit is how Python, and therefore Ansible, handles decimal versus octal numbers. In Python 2.7, preceding a decimal number with a zero will ensure it's interpreted as an octal number. 
### Options for formatting file permissions

All of the options below, when fed to the `mode:` parameter in an Ansible task, will result in the same permissions, i.e. `0755`:
- `"775"`
- `"0775"`
- `0775`
- `00775`
- `0o775`
- `0o0775`

Of those options, I consider `00775` the best format, since it's both readable and unambiguous. It's worth noting that `0o0775` works with both Python 2.6 and Python 3.x, and is actually required from 3.x onwards. Despite the [looming deprecation of Python 2](https://lists.debian.org/debian-devel-announce/2015/04/msg00005.html), Ansible [isn't planning to port to Python 3 anytime soon](http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine). Even if Ansible does move, updating our configs to use the `0o` prefix rather than `0` would be trivial.
### One-liner syntax

When using the `key=value` syntax in Ansible tasks, [integer values are coerced to strings](https://github.com/ansible/ansible/issues/9196), and passed to Python's `os.chmod` accordingly, meaning that `mode=775` works exactly the same as `mode: "755"`. With the exception of extremely terse tasks, multiline format should be preferred over the one-liner syntax, since it makes diffs in version control much more readable. (I'll submit a PR soon that adjusts most of our config to multiline syntax, so upcoming changes are clearer for review.)
### Files affected

Running `grep -ri "mode: [^\'\"]"` in the `install_files/ansible-base` directory shows these files which warrant further inspection:
- [x] roles/ossec-server/tasks/mon_install_postfix.yml:    mode: 0400
- [x] roles/ossec-server/tasks/mon_configure_ossec_gpg_alerts.yml:    mode: 775
- [x] roles/ossec-server/tasks/mon_configure_ossec_gpg_alerts.yml:    mode: 660
- [x] roles/common/tasks/create_users.yml:    mode: 0644
- [x] roles/restrict-direct-access/tasks/iptables.yml:    mode: 0700
- [x] roles/app/tasks/initialize_securedrop_app.yml:    mode: 0600
- [x] roles/app/tasks/initialize_securedrop_app.yml:    mode: 400
- [x] roles/app/tasks/configure_securedrop_worker.yml:    mode: 0644
- [x] roles/app/tasks/configure_securedrop_worker.yml:    mode: 0644
- [x] roles/app/tasks/create_app_dirs.yml:    mode: 0700
- [x] roles/app/tasks/create_app_dirs.yml:    mode: 0700
- [x] roles/app/tasks/create_app_dirs.yml:    mode: 0700
- [x] roles/app/tasks/create_app_dirs.yml:    mode: 0700
- [x] roles/app/tasks/create_app_dirs.yml:    mode: 0700

Changes to the above Ansible tasks should be accompanied by corresponding spectests, once #1002 is merged.

**Comment by garrettr** [comment]
@dolanjs @conorsch What else from this issue do we want to include in release/0.3.4? We already have the tor directory permissions changes included from #1052.

**Comment by conorsch** [comment]
@garrettr I haven't written these changes yet, so they won't make 0.3.4. Changing the file permissions will safely will require a better testbed than we have widely available right now. It'd be best to implement these changes on top of other diff-munging changes, such as #1004, which is currently tagged for 0.4.

**Comment by conorsch** [comment]
Nearing the finish line on this. #1214 includes major changes to the Ansible roles, as will the solution for #1023, so blocking here until those are both resolved. Once they are, updating each `mode:` paramter and its corresponding Serverspec test will be a cinch.

**Comment by conorsch** [comment]
Will need to take another pass through the `develop` branch to confirm, but the concerns outlined here should be largely addressed there. Leaving the 0.4 milestone in place, pending confirmation.

**Comment by conorsch** [comment]
Several of the OSSEC config tasks set permissions that are subsequently overridden by the postinst hooks in the FPF-maintained OSSEC packages; we should set the permissions once, correctly, and update the config tests to track regressions. Discovered this during QA of #1464.
