### ISSUE TITLE
Inconsistent directory path

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#1017]
If you go command by command in the install.md the [directory path](https://github.com/freedomofpress/securedrop/blob/develop/docs/install.md#install-securedrop) is incorrect. In the [Download the SecureDrop repository](https://github.com/freedomofpress/securedrop/blob/develop/docs/install.md#download-the-securedrop-repository) section the admin is instructed to cd into the securedrop repo directory. A few sections later in the [Install SecureDrop](https://github.com/freedomofpress/securedrop/blob/develop/docs/install.md#install-securedrop) section the admin is instructed to `cd securedrop/install_files/ansible-base` which is the wrong path. It should just be `cd install_files/ansible-base`

**Comment by dolanjs** [comment]
@ageis pointed out the directions say to open a new terminal in between the two sections mentioned previously the [set up the servers](https://github.com/freedomofpress/securedrop/blob/develop/docs/install.md#set-up-the-servers) section instructs the admin to open a new terminal. Which would mean the the correct path would be `cd Persistent/securedrop/install_files/ansible-base`

**Comment by garrettr** [comment]
> open a new terminal in between the two sections mentioned 

Is this necessary? I'd rather they use the same terminal consistently, since there's no good reason to create a new Terminal between the two sections, and doing so will clutter up their screen and could confuse them.

**Comment by garrettr** [comment]
This was closed by #1019.
