### ISSUE TITLE
Network Firewall doc needs correcting

### ISSUE THREAD

**Issue by harlo** [freedomofpress/securedrop#1025]
References to "Connection Information" should be replaced with "Edit Connections...".  Replace corresponding screencap, too.

See:

https://github.com/freedomofpress/securedrop/blob/0.3.3/docs/network_firewall.md#disable-dhcp-on-the-lan

**Comment by harlo** [comment]
Another thing: clarify CIDR allocation for OPT1 and LAN (24)
Because pfsense will "guess" for you, sometimes it guesses 32, which is wrong.

**Comment by harlo** [comment]
Another thing: specify that username + pwd have to be the same for both app and mon.

**Comment by harlo** [comment]
Another thing: admin ssh key should be passwordless (prefered) or diceword-generated.  this is because pinentry doesn't let you copy/paste.

**Comment by conorsch** [comment]
Reformatting for clarity:

### Things to change
* [ ] Replace `Connection Information` with `Edit Connections`
* [ ] Replace screenshot that mentions `Edit Connections`
* [ ] Clarify CIDR allocation for OPT1 and LAN on /24

**Comment by harlo** [comment]
Turns out, only item #3 (the CIDR mapping bit) is relevant.  Items 1 + 2 are fine the way they are.

**Comment by garrettr** [comment]
This was merged for release/0.3.4 in #1060. Taking this off of the 0.3.4 milestone as using #1060 as the marker there instead, since this will also need to be resolved for the develop branch.

**Comment by garrettr** [comment]
These changes were merged into develop in #1075.
