### ISSUE TITLE
Second file path option for OSSEC public key is wrong

### ISSUE THREAD

**Issue by harlo** [freedomofpress/securedrop#1028]
In the instructions for prod-specific.yml, we give users the choice on putting their public key for ossec notifications at 2 locations.  The longer of the two should be changed to `install_files/ansible-base/roles/ossec_server/files`, which is where ansible is actually looking for it.

**Comment by harlo** [comment]
@dolanjs suggests removing the option altogether; just dropping all such files in `install_files/ansible-base`

**Comment by dolanjs** [comment]
This will require modifying the prod-specific.yml file which needs to be handled carefully to avoid merge conflicts for the admin during the update process. Moving to 0.4 milestone to align with other ansible re-orgs that will address some of these issues.

**Comment by conorsch** [comment]
The new validation logic presented in #1782 now explicitly states that the OSSEC pubkey file should be placed in the `install_files/ansible-base/` directory, to eliminate ambiguity. If the OSSEC pubkey file cannot be found by Ansible, an informative error message will be displayed to the Admin _before_ the prod playbook contacts the servers.
