### ISSUE TITLE
Playbook should fail if user creation fails

### ISSUE THREAD

**Issue by harlo** [freedomofpress/securedrop#1029]
If the user specified in `ssh_user` directive fails, the playbook should fail out.

**Comment by conorsch** [comment]
Steps to reproduce? We expect admins to hardcode the username in the `prod-specific.yml` file, and also provide the same username via the `-u` option when running the playbook interactively. Was the problem you saw caused by different values in the vars file and the command line?

**Comment by dolanjs** [comment]
The problem we faced is in the `prod-specific.yml` we put the tails username `amnesia` instead of the admin username from the app/mon servers. The ansible playbook created the user and kept running the playbook.

**Comment by conorsch** [comment]
OK, we can rework how the `validate` role vets usernames in the prod playbook. At the very least we can check against a blacklist of common disallowed usernames, e.g. amnesia/vagrant. More importantly the `validate` role should assert that the `ssh_user` var == `ansible_ssh_user`.

**Comment by conorsch** [comment]
Related problem: the `validate` role doesn't check for uninitialized variables, but it should. Currently, if an admin doesn't fill out a required variable in the `prod-specific.yml` file, the `validate` role blithely disregards the empty string and only fails when trying to run the associated task. Example:

```
- debug: msg="verifying ssh_users is not set to vagrant"
  failed_when: ssh_users == "vagrant"
```

Since the `prod-specific.yml` file uses an empty string by default:

```
$ grep ssh_users prod-specific.yml
ssh_users: ""
```

the `validate` role should check for empty vars as part of its sanity checking.

**Comment by conorsch** [comment]
The `validate` role should also check the GPG fingerprints specified in `prod-specific.yml`. If an Admin makes a typo on a fingerprint, debugging it can be a painful process. Might as well provide a custom filter for verifying the structure of the fingerprint.

**Comment by conorsch** [comment]
Sticking to the original scope of this issue, username validation should include:

* != "vagrant"
* != "amnesia"
* in `ssh_users`
* ansible username matches `ssh_users` (or is included within it, if a list)

**Comment by conorsch** [comment]
See also #749, which includes verifying that `ssh_user` is not set to `root`.

**Comment by conorsch** [comment]
Validating the SSH username against all possible blacklisted vars (e.g. "root", "amnesia", etc.) is simple enough, but adding config tests to ensure failure is slightly more complicated. Working on that now—it might require triggering an Ansible provisioning run with `--extra-args ssh_users=amnesia` and confirming the playbook fails.
