### ISSUE TITLE
Clarify that user doesn't need to manually add torrc directives

### ISSUE THREAD

**Issue by harlo** [freedomofpress/securedrop#1030]
The lines after successful installation kind of imply user should manually add the contents of the *-aths to torrc.  But there's a script that already does that.  Pls reword.

See https://github.com/freedomofpress/securedrop/blob/0.3.3/docs/install.md#install-securedrop

**Comment by harlo** [comment]
this one's taken care of. closing.

**Comment by garrettr** [comment]
The changes from #1034 also need to be merged into release/0.3.4, since this issue has the release/0.3.4 milestone assigned.

**Comment by garrettr** [comment]
@harlo I'll take care of this one since it's just a cherry-pick of doc changes.

**Comment by garrettr** [comment]
I cherry-picked the sole commit from #1034 onto the release/0.3.4 branch in 60eb86cb7eb0e6d98076bb42852cc584891eb695.
