### ISSUE TITLE
Fix install_local_pkgs role

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1040]
The Ansible role `install_local_pkgs` is broken, and should be removed. It's currently being skipped in the Vagrantfile by default for for the `*-staging` hosts, as well as in the online integration tests (still under development) via environment variables, and yet the role is explicitly included in the `securedrop-staging.yml` playbook. 

At a later date, if necessary, we can reimplement the role dynamically, so it doesn't need to be manually excluded all over the place. Doing so will be simpler after some reorganizing of the Ansible layout. 

The rewritten role should provide the following functionality:
- [x] automatically rebuild the app-code deb package as part of the staging playbook
- [x] ensure presence of build vm (otherwise build steps are skipped without error, by default)
- [x] add tags to target rebuilding-and-reinstalling
- [x] provide helpful error messages to developers if packages are missing
- [x] works in digitalocean and virtualbox

**Comment by conorsch** [comment]
See #1058 for recent example of how this role is applied. Having this role around is useful for testing new .deb packages with staging hosts. In its current form, it's painful to use, since several files must be manually edited in order to configure it for a successful Ansible run.

If the role is removed during the reorg, consider adding docs on manual installation of the .deb packages for testing new versions. The build process in the `build` VM is sufficiently automated that generating the .debs for testing is convenient.

**Comment by dolanjs** [comment]
@conorsch An issue to keep in mind while addressing this during the ansible re-org is that the vagrant shared folder is not currently accessible in the app or mon staging and prod VMs. Currently the install_local_pkgs role just uses ansible to copy the deb packages to the VM and then uses dpkg to install what was copied over. The built in ansible apt module was not used to install the deb packages because it kept throwing an error when trying to install multiple deb packages including the grsec deb package.

**Comment by conorsch** [comment]
Working on this now. Rather than including the `install_local_pkgs` role in the staging playbook and skipping it by default via `--skip-tags`, its inclusion can be toggled via a top-level variable `install_local_packages` which defaults to `false`. With this setup, the role will be skipped by default in all environments and platforms, and will require an explicit override to add it.

**Comment by garrettr** [comment]
@conorsch Explicit is better than implicit :+1:

**Comment by conorsch** [comment]
This role works "well enough" now that we should include it by default for testing with the staging role. The current implementation isn't smart enough to skip installing debs from the apt repo under staging, but a future fix can address that. In order to enable the role by default, we should simply remove this L83 from the Vagrantfile:

```
       ansible.skip_tags = ENV['SECUREDROP_STAGING_SKIP_TAGS'] || 'install_local_pkgs'
```

The major side-effect to removing the line is that folks would need to create and provision the `build` VM when testing under staging, but that's actually what I want contributors to do.

**Comment by conorsch** [comment]
The `staging` machines should default to installing from local Debian packages, rather than pulling down the debs from the FPF apt repository. We can automate most of this, but the OSSEC debs are built in a [separate repo](https://github.com/freedomofpress/ossec). So we'll need documentation to fill in the gap about building those debs and copying them into the SecureDrop repo.

**Comment by conorsch** [comment]
Got chained deb package building working as an automatic include in the staging playbook. Also supports _just_ rebuilding and reinstalling the deb packages (takes less than a minute!) via a special command:

```
ANSIBLE_ARGS="--tags rebuild" vagrant provision /staging/
```

Will submit a PR after #1196 is reviewed and merged.

**Comment by conorsch** [comment]
New role works like a charm in VirtualBox, will need to do some additional testing to get it working just as well in DigitalOcean. Working on that now.
