### ISSUE TITLE
Audit vagrant plugins

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1045]
The docs mention several Vagrant plugins, most of which are not necessary. Identify unnecessary plugins and remove them from the Vagrantfile and the docs. If any plugins are required or recommended, list them as such in `develop.md`. 

For example, the `Vagrantfile` includes this line:

`staging.hostmanager.aliases = %w(securedrop-monitor-server-alias)`

The Ansible config already handles writing to `/etc/hosts`, so the `vagrant-hostmanager` plugin isn't useful. Since mention of the plugin is buried down at the bottom of `develop.md`, trying to run the VMs on a pristine clone of the git repo will cause failure if the user doesn't have the plugin installed locally. This is a frustration for new contributors.

`vagrant-cachier` was disabled half a year ago (8745bd81) and [nothing has changed](https://github.com/fgrehm/vagrant-cachier/issues/128) that would allow us to re-enable it, so get rid of it.

The `vagrant-digitalocean` plugin is useful but should not be required. Make sure it's not required before moving it to a **Recommended** section. Consider recommending `vagrant-vbox-snapshot` as well.

**Comment by conorsch** [comment]
Consider recommending:
* vagrant-digitalocean
* vagrant-pristine (convenient when destroying and recreating VMs)
* vagrant-vbox-snapshot

Consider removing:
* vagrant-cachier
* vagrant-hostmanager

**Comment by conorsch** [comment]
Error showing up infrequently in Snap:

```
+ [[ -f /var/go/vagrant_1.7.2_x86_64.rpm ]]
+ [[ -x /usr/bin/vagrant ]]
+ vagrant plugin install vagrant-digitalocean
Installing the 'vagrant-digitalocean' plugin. This can take a few minutes...
Installed the plugin 'vagrant-digitalocean (0.7.4)'!
+ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Net::HTTPNotFound: No gems found matching "vagrant-vmware-fusion" "3.2.9" nil
Command ./snap_ci/pinned.sh failed with status 1. Took 25.62 seconds.
```

I've only ever seen it on `vagrant-hostmanager` specifically, which is interesting. Just another reason to remove unnecessary dependencies.

**Comment by garrettr** [comment]
FWIW, `vagrant-pristine` is now [deprecated](https://github.com/fgrehm/vagrant-pristine/commit/6d044265db17451c606f000bf43437e95a742bb4) and that functionality is expected to be included in a future version of Vagrant (perhaps as soon as [1.8](https://github.com/mitchellh/vagrant/pull/5613#issuecomment-120142019)).

**Comment by conorsch** [comment]
`pristine` didn't land in 1.8, but `snapshot` did. Our docs can recommend `vagrant-digitalocean`, and mention of all other plugins can be removed.

**Comment by garrettr** [comment]
@flamsmark just ran into an issue related to the Vagrant plugins while trying to `vagrant up /staging$/`. In `Vagrantfile` under the definition of `mon-staging`, there is the line:

```
    staging.hostmanager.aliases = %w(securedrop-monitor-server-alias)
```

Which only works if you have vagrant-hostmanager installed. AFAICT we are not using vagrant-hostmanager anymore, so this line was probably left in by mistake and should be removed.

This issue is present on both develop and 0.3.6.

**Comment by conorsch** [comment]
Opened #1311 to address the `vagrant-hostmanager` problem. There's simply no reason to require that plugin any longer—if it's installed, you don't notice the problem, but I've been bitten by it several times recently while switching machines, and it's quite irritating.

Another point raised by this issue was whether the DigitalOcean integration would require configuration for new devs. I'm pleased to report that the `vagrant-digitalocean` plugin is _not_ a hard requirement, and is only necessary to test on DigitalOcean when explicitly stating `--provider=digitalocean`. There's still legacy mention of `vagrant-cachier` in the Vagrantfile warning against its use, and I'm happy leaving that for now. #1208 tracks improvements to the dev docs, so I'm comfortable closing this after #1311 is merged.

**Comment by conorsch** [comment]
Updated #1208 to include mention of `vagrant-digitalocean` plugin, so closing this issue.
