### ISSUE TITLE
Support concurrent VirtualBox instances of same VM

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1069]
The `virtualbox.name` declarations in the Vagrantfile prevent multiple instances of the same VM on a single host machine. This restriction causes problems for running multiple differently configured SecureDrop environments, for example while using `git-new-workdir` to test feature branches while continuing development on a separate branch.

Having a manually specified `name` attribute for a vbox host admittedly makes for a pleasant listing in the VirtualBox GUI:

![vbox_static_names2](https://cloud.githubusercontent.com/assets/657862/8506161/cb30f752-21bb-11e5-98ad-b52c3504b65b.png)

However, attempting to `up` the same VM elsewhere—an operation fully supported by Vagrant's philosophy of machine isolation—results in an error message:

```
Bringing machine 'mon-staging' up with 'virtualbox' provider...
Bringing machine 'app-staging' up with 'virtualbox' provider...
A VirtualBox machine with the name 'mon-staging' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```

Enabling concurrent VMs causes automatic generation of a unique `name` for the machine, so you can have as many copies as you want:

![vbox_dynamic_names_many_vms](https://cloud.githubusercontent.com/assets/657862/8506162/d1c67f6a-21bb-11e5-8f25-ec617386948e.png)
## Changes necessary

The current config poses a few problems for supporting multiple boxes, mostly due to the networking setup. The following items in the `Vagrantfile` will need to be changed:
- Convert static IP addresses for private networking to DHCP addresses, via the [Vagrant `:dhcp` private network type](https://docs.vagrantup.com/v2/networking/private_network.html).
- Enable automatic correction of port forward collisions for `development` and `/staging/` hosts.
- Remove `virtualbox.name` declarations from all hosts.

**Comment by garrettr** [comment]
Agreed that this is a good change to make, this problem has annoyed me numerous times in the past.

**Comment by conorsch** [comment]
Glad to know I'm not alone. I've got a few feature branches lying around with various implementations of this, and right now I think it'd be simplest to remove just the `v.name` declarations from the Vagrantfile, and require manual changes to the internal networking IPs. Will try to strike a balance between convenience and reliability.

**Comment by conorsch** [comment]
Just got bitten by this again. Will get a PR up momentarily.
