### ISSUE TITLE
Prevent reboots during cron-apt upgrade

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1071]
### Background
We use cron-apt, rather than unattended-upgrades, to manage overnight updates for the app and mon servers. When run via cron, cron-apt fuzzes the reboot logic by 0-60 minutes after invocation. The logic is on L318 in `/usr/sbin/cron-apt`:

```
        TIME=$(($RANDOM % $RUNSLEEP))
        sleep $TIME
        echo "CRON-APT SLEEP: $TIME, $(date)" >> "$INITLOG
```
The `RUNSLEEP` env var defaults to 3600 (see L244), thus the 0-60 minute delay. The SecureDrop Ansible playbooks configure cron-apt to run at 4AM local time, which means upgrades actually start anywhere between 4:00 and 5:00 local time. The Ansible playbooks also mandate a reboot at 5:00 local time, in order to clear memory (see #805). 

### The problem
If cron-apt runs at 4:59, and updates are available, then the upgrade will almost certainly be interrupted the 5:00 scheduled reboot. Such an interruption could leave apt or dpkg in a broken state (see possibly related #1032). The two cronjobs for cron-apt and reboot were originally set an hour apart to ensure the execution windows for the tasks did not overlap. It's easy to overlook the time-fuzzing logic, because if you run `cron-apt` from the command-line, it skips the fuzzing altogether:

```
if [ -t 0 ]; then
    RUNIMMEDIATELY="yes"
fi
if test "$RUNIMMEDIATELY" = "yes"; then
    RUNSLEEP=
fi
```

In short: if STDIN is a terminal, then we're running interactively, so don't bother sleeping. The reboot cronjob used to check for the presence of `/var/run/reboot-required`, as well, which *should* have ignored a reboot if cron-apt is still running, depending on when exactly the `/var/run/reboot-required` file is written by apt.

### Mitigations
There are a few ways to solve:
* Append the reboot task to the cron-apt task on the same cron line, so cron-apt blocks and the reboot runs after. (Choose wisely between `&&` and `;`.)
* Leave the cron-apt task on a separate line, and have it check for a running cron-apt process, sleep until cron-apt exits, then reboot.
* Move the cron-apt task up by an hour, to 3:00 local time, effectively creating a minimum window of 60 minutes between cron-apt starting and the reboot command. Technically this doesn't ensure the tasks won't overlap, but it would be a better implementation of the current config. 

The first option seems simplest and most reliable. The reboot task should be chained with `;`, rather than `&&`, to ensure that the server reboots even if cron-apt fails.

Thanks for pointing this out, @dolanjs.

**Comment by garrettr** [comment]
@conorsch @dolanjs Should we nominate this for 0.3.5?

**Comment by dolanjs** [comment]
@garrettr I think that would be a good idea.

**Comment by garrettr** [comment]
> The reboot task should be chained with ;, rather than &&, to ensure that the server reboots even if cron-apt fails.

@conorsch Are you sure? When does cron-apt fail? Might it be better not to reboot, in case the failure occurred during, say, a kernel upgrade, in which case rebooting might leave the system in a broken state requiring physical recovery?

**Comment by conorsch** [comment]
Chaining the reboot with `;` rather than `&&` is a better implementation of the current config. Currently, the server will reboot exactly at 5:00 local time _no matter what_. Since the nightly reboot was added to ensure purging of memory, changing the reboot to be conditional on a successful cron-apt run could have the side-effect that a server doesn't reboot for days or weeks in the event of a failing cron-apt task.

Other than purging memory, I don't see a compelling reason to force the reboots—but we are doing it now, and it was deemed necessary in #805.

**Comment by garrettr** [comment]
If `cron-apt` exits with an error, then something went wrong and it probably requires an admin's attention to resolve. Such an error would be written to the cron-apt error log (I checked this in the source), which should be monitored by OSSEC (need to verify this). If so, the admin will be notified when a cron-apt occurs, and should be able to take prompt action to resolve it.

I'm thinking it might be better to rely on admins to fix the systems in the event that cron-apt is broken and avoid the potential for the automatic reboot to break the system in a difficult-to-recover manner, even if that means the system might go a few days without an automatic reboot to clear the memory.

@dolanjs What do you think?

**Comment by garrettr** [comment]
FWIW in #853 we added a custom decoder to ensure that OSSEC will send alerts for cron-apt warnings/errors.

**Comment by dolanjs** [comment]
@garrettr The admin will get an alert for an error in the cron-apt logs which will need to get addressed either way. So I think requiring cron-apt to finish without errors for the reboot to happen is fine and will cover that edge case of preventing an unresponsive system.

**Comment by conorsch** [comment]
Sounds good to me. Target of 0.3.5 is realistic for this, I'll submit a PR shortly.

**Comment by garrettr** [comment]
@dolanjs Agreed, thanks for weighing in. @conorsch Sounds good! I can also write the PR if you have other things you're working on right now. Should be pretty easy :grin:

**Comment by garrettr** [comment]
Cherry-picked 654e19762568804685f0bd7137b0ba33795da0d9 to the release/0.3.5 branch in 0483ce3d93b935c1e8e0269a861fbd288fbe42dd.
