### ISSUE TITLE
Replace connect-proxy with netcat

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1087]
During the development of #1070, we realized that `netcat` can be used as a SOCKS proxy for various applications. In `develop.md`, we currently recommend using `connect-proxy` when a SOCKS proxy for Tor is needed on Ubuntu. However, `netcat` has some advantages over `connect-proxy`:
1. It is installed on Ubuntu (and Mac OS X, and most Unix-y systems) by default
2. It is more actively maintained than connect-proxy (at least on Ubuntu, where the last update for netcat was in [2012](http://changelogs.ubuntu.com/changelogs/pool/universe/n/netcat/netcat_1.10-40/changelog), whereas the last update for connect-proxy was in [2009](http://changelogs.ubuntu.com/changelogs/pool/universe/c/connect-proxy/connect-proxy_1.101-1/changelog)).

In my opinion, we should just replace all references to connect-proxy with netcat.

The main thing we should test is that netcat **does not leak DNS lookups**. `connect-proxy` has a flag `-R remote` that explicitly requires it to do DNS resolution remotely (through the proxy), which is safe. Netcat does not have a comparable flag (although it does have `-n`, which might be useful -- needs investigation). However, it defaults to SOCKS5 by default, which supports [remote DNS resolution](https://www.inet.no/dante/doc/1.3.x/config/socks.html), so I think it probably does the right thing. From my [limited testing](https://github.com/freedomofpress/securedrop/pull/1070#issuecomment-123109555), `nc` on Mac OS X 10.10 does remote DNS resolution by default (or it wouldn't have been able to resolve the `.onion` addresses I was trying to SSH to).

**Comment by conorsch** [comment]
For what it's worth, I uninstalled `connect-proxy` when you opened this issue, and I haven't noticed any incompatibility with our config. As for guarding against DNS leakage, the defaults of `VerifyHostKeyDNS=no` for `ssh` and `-X 5` for `netcat` should be confirmed, and maybe hardcoded in our SSH proxy commands out of caution. The `-n` option for `netcat` does look interesting as well, but I haven't tested it yet.

**Comment by conorsch** [comment]
This was already handled by 6cced9dcb16e0fd15841bf0aec75fa15fe64a847 in #1441, but there's a dangling reference in a comment in the Vagrantfile that should be cleaned up as well.
