### ISSUE TITLE
Log statistics about javascript support of whistleblowers submitting information

### ISSUE THREAD

**Issue by fpietrosanti** [freedomofpress/securedrop#109]
Following the Javascript/Non-Javascript discussion i think that we need to move out from the "subjective and philosophical point of view" and move to an "objective and analytical approach".

I am in favor of extensive use of Javascript due to that capability it does provide for security and usability.

I think, but that's a subjective point of view, that 99.99% of whistleblowers submitting information to a SecureDrop platform use the stock Tor Browser Bundle with Javascript enabled.

If 99.99% of users approaching a SecureDrop installation have Javascript turned on, i think it would be a reasonable understanding, that it's not required to have a Javascript-free submission interface, with all the limits that it provide.

The experience we had with 32 media on GlobaLeaks is that not a single user even blamed for the system being based on Javascript, but it's possible that who was working with javascript disabled, just enabled it. So it's not a valuable statistics.

This ticket is to propose the server-side logging of statistics of access by the whistleblowers, to detect how many users have Javascript turned on and how many users have javascript turned off.

Those kind of statistics should be exposed with a public OpenData feed (just writing to a .csv file) aggregated data, updated on a daily or weekly basis (to prevent time pattern correlation on the amount of submission).

Given that statistics the SecureDrop project would have a set of data to be analyzed to objectively evaluate if the denial of use of Javascript is reasonable or not.

**Comment by garrettr** [comment]
Leaving this open. We should consider performing user research on the effectiveness of our "disable javascript" UX. I still believe that it is important to disable Javascript and do not anticipate reversing our stance on avoiding the use of Javascript in the source interface.

**Comment by justintroutman** [comment]
@garrettr Have you considered hosting a small "UX onboarding" demo, where invitees run through the SecureDrop process and provide feedback? That can be an easy way to reach a consensual view on what the real bottlenecks are, including the JavaScript disabling issue.

**Comment by garrettr** [comment]
@justintroutman I think that's a great idea! I've never done anything like before. Might you be interested in advising or helping out? :smile:

**Comment by justintroutman** [comment]
@garrettr It would be my pleasure to both advise and help out! Let's connect on this soon.

**Comment by eloquence** [comment]
We discussed this on our old issue review today. We're closing this for now as the original issue (logging of JS usage) is not something we anticipate doing -- both due the perceived/actual sensitivity of logging, and the relatively low utility of the information for development purposes. We'll certainly want to investigate the UX and security aspects of JS usage further, and may create separate issues for that.
