### ISSUE TITLE
Document credential recovery scenarios

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#1091]
Often get questions about how to recover if the only admin or journalist gets a new phone, forgets their keepass manager master password or has tails usb failure. Should document the typical processes as part of the docs.
### Scenarios

Journalist
- Recovering access to the Document Interface

Admin
- Recovering console access (password + google-authenticator)

SVS
- Recovering access to the airgapped tails usb (we can't... but should go over what needs to be done to move past this... generating a new airgapped svs tails usb, application gpg keypair...)

**Comment by flamsmark** [comment]
Recovering the airgapped Tails disk should just be a matter of backing it up appropriately?

**Comment by garrettr** [comment]
> Recovering the airgapped Tails disk should just be a matter of backing it up appropriately?

That's correct. You only _need_ to back up the application GPG private key. We generally recommend cloning the airgapped Tails disk (hereafter, "SVS Tails USB") to 1 or 2 additional USB sticks, since they serve as _bootable_ backups.

**Comment by KwadroNaut** [comment]
@flamsmark  correct, but backing up nor cloning is documented, and Tails doesn't come with a nice interface to take care of that.

**Comment by eloquence** [comment]
Recovering admin access is documented in https://docs.securedrop.org/en/master/rebuild_admin.html

Rotating the submission key is documented in https://docs.securedrop.org/en/master/offboarding.html#rotate-the-submission-key

Managing one's 2FA credentials is documented in https://docs.securedrop.org/en/master/journalist.html#reset-passphrase-or-two-factor-authentication-credentials

Managing another user's credentials as an admin is documented in https://docs.securedrop.org/en/latest/admin.html#passphrases-and-two-factor-resets (merge into a release pending)

I'm therefore closing this old tracking issue in favor of additional specific follow-up improvements.
