### ISSUE TITLE
Delete confirmation can be triggered accidentally

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1110]
The new confirmations in #1105 work by adding hidden links that have their `display:` property toggled via CSS pseudo-selectors. However, even when they are hidden they are still clickable. For example, on the source's `/lookup` page:

![hidden delete button for replies](https://cloud.githubusercontent.com/assets/407302/9888716/7319fa3a-5bab-11e5-8abc-10cf444996cf.png)

As you can see, when you mouse over the area where the delete button is "hidden" (not yet activated by clicking the visible "Delete" button with the trashcan icon), the cursor turns into a pointer, indicating a clickable element. Clicking in this apparently empty space causes the reply to be deleted.

All of the confirmation buttons in #1105 should not be clickable unless they are visible. This is probably achievable in all of the browsers we care about via CSS' [pointer-events](http://stackoverflow.com/a/10276157/1093000).

**Comment by taravancil** [comment]
This only happens in the source interface since `opacity` is used to toggle visibility rather than the `display` property. It should be fixed now!
