### ISSUE TITLE
Support secondary DNS server(s) in Ansible playbooks

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1114]
The Ansible configuration currently supports only a single string for a DNS server. Instead, the `dns_server` variable should be a list, and all IP addresses in it should be allowed out when writing the iptables rules.

The Network Firewall docs already recommend using two DNS servers (giving `8.8.8.8` and `8.8.4.4` as examples), but given the firewall rules, `8.8.4.4` will not be reachable by the servers. We should also update the Server Config docs with examples that include typing both DNS servers. Currently the docs only recommend setting `8.8.8.8`.

Changing the format of any variables in `prod-specific.yml` is likely to cause a merge conflict for admins when they pull down a new version from the git repo. Look into intelligent handling of the value to check whether it's iterable or a string, to retain backwards compatibility for admins with only a single value set.

**Comment by eloquence** [comment]
This was fully realized via #5288. :)
