### ISSUE TITLE
Update hardware recommendation for SVS

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1115]
We currently recommend the Intel NUC model D54250WYK for use with SecureDrop, as App, Mon, and SVS. However, the D54250WYK has recently been [EOL'ed by Intel](http://ark.intel.com/products/series/70407/Intel-NUC-Boards-and-Kits), so we need a replacement. Unfortunately, the new iteration of NUCs (NUC5i5RYK and NUC5i5RYH) come with onboard wifi and bluetooth, and therefore are not suitable for use with the airgapped Secure Viewing Station.

A suitable replacement 
- **must not** include integrated wireless hardware, and 
- **must** have x86/_64 architecture ([Tails does not support ARM](https://tails.boum.org/support/faq/index.en.html#index7h2))

Newer hardware increasingly ships with wifi capability out of the box. We've got an odd use case not wanting it. In #1112 we added a warning about the EOL for the D54250WYK, but we still need to identify a replacement.

**Comment by flamsmark** [comment]
The hardware recommendations are are also rather difficult to parse, because of the way that the document is laid out. Improving the quality of the documentation should probably go hand-in-hand with improving the content.

**Comment by KwadroNaut** [comment]
NUC5i3MYHE and NUC5i3MYHE come with wireless antennas pre-assembled (like the others), but it's m.2 wifi slot is *not* filled. That would be similar with many re-purposed thinkpads where a card is removed, but the antenna behind the monitor remains there.

**Comment by justintroutman** [comment]
Intel's direct recommendations, per our requirements, were exactly the [NUC5i5MYHE ](http://ark.intel.com/products/84861/Intel-NUC-Kit-NUC5i5MYHE) and [NUC5i3MYHE](http://ark.intel.com/products/84860/Intel-NUC-Kit-NUC5i3MYHE) models, as noted by @KwadroNaut's comment.
