### ISSUE TITLE
Encrypted transfer device

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1119]
Current recommendations leave the transfer device unencrypted. This just makes me feel bad. In my recent setup, I encrypted the transfer device using a diceware passphrase which I saved in the keyrings of the SVS, admin workstation, and journalist workstations. With the keyring system, there's nothing extra to remember during everyday use of the transfer device, and it's not much additional setup load.

**Comment by conorsch** [comment]
Thanks for testing the keyring integration in Tails! If the passphrase for decrypting the transfer device can be stored in Tails persistence, I don't see any reason not to recommend encryption here.

We recommend and expect that only encrypted files will be written to the transfer device, but encrypting it fully provides additional protection against mistakes. Definitely in favor of a docs update.

**Comment by conorsch** [comment]
Tested this again, and quite happy with the behavior. This will become SOP for new installs, so let's definitely update the docs to include the recommendation.

**Comment by harlo** [comment]
+1 on encrypting the transfer device. We've started training people on this
workflow and it works quite well.

**Comment by conorsch** [comment]
We now recommend encrypted the Transfer Device [in the official docs](https://docs.securedrop.org/en/stable/set_up_dtd.html). Thanks for the recommendation and testing here, @flamsmark!
