### ISSUE TITLE
Document the importance of labeling all devices

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1120]
Current install docs make some mention of labeling disks. Labeling is important. With SecureDrop, labels are a UX issue that impinges on user behavior that could compromise the security model. The setup documentation should always instruct the admin to label a disk that they've just made *immediately*.

This is particularly important for (say) the SVS and admin workstation, but becomes even more important in a multi-admin setup or when provisioning many journalist workstations at once, and so on.

**Comment by conorsch** [comment]
Agreed. The [current phrasing](https://github.com/freedomofpress/securedrop/blob/develop/docs/install.md) in the docs is rather offhand:

> One thing to consider is that you are going to have *a lot* of USB drives to keep track of, so you should consider how you will label or identify them and buy drives accordingly. Drives that are physically larger are often easier to label (e.g. with tape or a label from a labelmaker).

[and](https://github.com/freedomofpress/securedrop/blob/develop/docs/install.md):

>It's a good idea to label or color-code these in order to tell them apart.

We should provide much firmer recommendations about good labeling practices. When running tests on hardware and assisting with on-site installs, we're pretty aggressive about accurate labeling, and the docs should reflect that stance.

**Comment by conorsch** [comment]
Thanks to @flamsmark, the docs now strongly encourage sound labeling practices, e.g.
* ./set_up_tails.rst:As soon as you create a new Tails drive, *label it immediately*.
* ./set_up_svs.rst:Station”. If it's not labeled, label it right now, then boot it on the
* ./set_up_dtd.rst:If you haven't already, make sure to label it.

Most of these changes were pulled in via #1153, and later reorganized as part of #1158.
