### ISSUE TITLE
U2F

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1121]
SecureDrop currently uses Yubikeys in HOTP mode. This is not terrible, but it's not great. U2F is an objectively superior technology which should be used instead. Fully switching over relies on Fireox implementing U2F support and that support being carried over into Tor Browser.

**Comment by redshiftzero** [comment]
It sounds like Firefox U2F support is probably not going to happen in the near to medium term future... closing for now. Someone can re-open if the situation changes.
