### ISSUE TITLE
Firewall template config

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1122]
The firewall setup instructions are monotonous and fiddly and an easy place to make mistakes. Although FPF can't offer template configs for every firewall out there, since you already recommend pfsense and have pfsense-specific documentation with pfsense screenshots, why not just include a pfsense config file that an admin can edit/upload, saving a whole load of fiddly web-interface-clicking.

Better yet — using a config file might mean that the firewall can be configured over SSH, removing the need for a password and allowing the option of turning off the firewall's web interface altogether. Since the firewall can be physically reset in-person without trouble, this shouldn't represent a huge usability/lockout hurdle.

**Comment by conorsch** [comment]
As of `0.3.5`, we do indeed ship a (redacted) template, which should make the firewall config less of a mouse-hunt. See 16a2118, which made it in via #1113 for details.

As for automatic configuration of the firewall, first we need to virtualize the firewall to improve the testing environment. Eager to get to that, but it depends on a docs overhaul—currently underway, with much help from you—and refactoring the Ansible config to make adding new hosts more manageable.

**Comment by conorsch** [comment]
We should generate an updated template with default local IPv4 addresses and instruct Admins to apply that. During initial installs, the manual configuration of the firewall causes a lot of frustration, typically for nuances like TCP versus UDP for NTP and DNS. If we generate the config that we want, with predictable IP addresses, then we have a sane default convention, and experienced Admins can still adjust values such as local IPv4 addresses to their liking.

Generating the first-run template is worthwhile even if we still require the Admin to log in via the web interface and apply the config that way (versus SSH).
