### ISSUE TITLE
Refactor `roles.md`

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1132]
`roles.md` was broken out of the end of `terminology.md` and should be checked and revisited after reviewing the installation docs.

**Comment by redshiftzero** [comment]
Am I correct that this no longer exists?

**Comment by redshiftzero** [comment]
OK I'm not sure what the history is here, but I'm going to close this ticket as I no longer see this file or its rst equivalent in the docs directory.
