### ISSUE TITLE
Checklist for setting up a journalist with everything they need to use SecureDrop

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1135]
Currently, setting up a single journalist's accounts &c. is mentioned in `install.md` — and spread over several places. Hopefully, a newsroom doesn't need to **install** SecureDrop all that often. But they will need to set up accounts for several people, and potentially set up new accounts periodically as part of their new-staff onboarding process. These steps should live in their own document for easy reference.

**Comment by flamsmark** [comment]
This should probably be the place to talk about the different needs for large and small organizations, the possibility of having multiple *Secure Viewing Stations* if there are multiple offices, large-team training and deployment plans, and long-term SecureDrop lifecycle management.

**Comment by harlo** [comment]
It would be helpful to mention that only Tails drives created via the Tails Installer can enable persistence.  I usually suggest having an unused Tails USB around for doing just that, or creating them from the Admin's Tails USB (without having them log in to their own persistence).

**Comment by garrettr** [comment]
@harlo Good point! @flamsmark mentions that in the PR which he will be submitting soon.

**Comment by redshiftzero** [comment]
Resolved in #1953
