### ISSUE TITLE
Style guide for docs

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1137]
SecureDrop has a bunch of terms of art. What's the correct way to refer to the “application server”? Should it be capitalized, abbreviated, italicized? I'm not super-invested in the answers here, but they should be written down among the developer docs so that any future user-facing documentation can be consistent. I'm sure that *I*'ve been inconsistent in my proposed edits — once the style is agreed, I can go through and make everything follow it.

**Comment by conorsch** [comment]
* Capitalized: Always, throughout the docs
* Italicized: When introduced, but not throughout
* Abbreviated: Never in the user-facing docs. In the developer docs, abbreviation is acceptable.

**Comment by conorsch** [comment]
In the case of the *Secure Viewing Station*, it's tempting to abbreviate as SVS. Let's try *not* to do that in the user-facing docs, but allow it in the developer docs, and see how that reads.

**Comment by garrettr** [comment]
I've started a style guide for the docs in `docs/development/documentation.rst` ([rendered](https://docs.securedrop.org/en/latest/development/documentation.html#style-guide)), but this issue shouldn't be closed yet since it's still a work in progress.

**Comment by garrettr** [comment]
Another issue that should be addressed in the docs is mundane: ReST authoring guidelines, specifically around stuff like tabs vs. space, hard vs. soft line wrapping, maximum line lengths, etc. Something like [Qubes' Guidelines for Documentation Contributors](https://www.qubes-os.org/doc/doc-guidelines/).

**Comment by conorsch** [comment]
Honestly the [existing style guide](http://securedrop.readthedocs.io/en/latest/development/documentation.html) satisfies me for the time being, and therefore I vote for closing this. We can always revisit later as we continue to improve the dev docs. @garrettr, thoughts?

**Comment by garrettr** [comment]
@conorsch I agree, the current documentation style guide is a good start. I think the most efficient way to improve it would be to do so incrementally, as questions about style conventions come up - like we just did in #1295.
