### ISSUE TITLE
Organize documentation images

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1140]
The docs `images` folder has a bunch of images together in a folder. I'd like to separate them out a little by putting them into folders like `screenshots` and `icons`. To avoid breakage, they should be temporarily replaced with symlinks.

**Comment by conorsch** [comment]
:+1: Breaking up the images is a fine idea. For future-compatibility, let's move everything under `images/`, like so:

* `images/icons/`
* `images/screenshots/`
* `images/photos/` (unimplemented, but possible)

That should cover just about everything.

**Comment by conorsch** [comment]
Halfway done here. The docs now have well organized subdirectories:

* `images/firewall`
* `images/icons`
* `images/install`
* `images/manual`
* `images/printer_setup_guide`
* `images/screenshots`

but there are other screenshots lying in the base that could still be cleaned up. Also, a few images are unnecessarily marked executable; `find images/ -type f -perm /a+x` will list them. Keeping this issue open until that's resolved.

**Comment by freddymartinez9** [comment]
The ones marked executable seem to be in the directories i.e. `firewall/`. I can clean this up.

**Comment by freddymartinez9** [comment]
opened #1498 for this

**Comment by redshiftzero** [comment]
After merge of #1498, I think we're good to close this now.
