### ISSUE TITLE
Compile all the download/verify steps at the start of `install.md`

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1143]
There's a fair bit of stuff to download, verify, and `dd` to thumb drives at the start of the SecureDrop installation process. This material should all be clustered together towards the start. Perhaps in a section which reminds prospective admins to collect all their thumb drives and hardware and so on the day before their install, then leave downloads overnight and verify and flash them all first thing on install-day.

**Comment by conorsch** [comment]
The [Before You Begin](http://securedrop.readthedocs.io/en/latest/before_you_begin.html) section handles this nicely, and also links out to [Hardware](http://securedrop.readthedocs.io/en/latest/hardware.html) for a more explicit take. @flamsmark If you have further ideas on how to improve the docs for first-time admins, I'm happy to make changes.
