### ISSUE TITLE
Remove old apt config

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1145]
The current Ansible config adds the Freedom of Press apt repository to `/etc/apt/sources.list.d/apt_freedom_press.list`, with a repo URL of `https://apt.freedom.press trusty main`. That works great. 

However, long-running instances of SecureDrop may still have the old repo URL specified in a different file: `/etc/apt/sources.list.d/apt_pressfreedomfoundation_org.list`, with repo URL `https://apt.pressfreedomfoundation.org`. We changed the apt repo URL in November 2014 (see 97fefe45f4240d36d4d2162d7844cfa05f70ca8a), but the config does not ensure that the old repo is removed.

The discrepancy may cause problems during upgrades for long-running instances. After we update the Ansible playbooks, admin intervention will be necessary to fix the issue.

**Comment by conorsch** [comment]
As with #2725, handling via `securedrop-keyring` sounds reasonable, so we're not dependent on Admin intervention. This is a cleanup task, only observed on rare occasions, so not critical to resolve.

**Comment by eloquence** [comment]
We made it over the Ubuntu 14.04>16.04 without issues since this was discovered, and the number of instances that could be impacted by this is tiny. Curious if a cleanup task is still required here? If so, we may want to get it out before #4768 (Bionic/Focal).

**Comment by eloquence** [comment]
We'll resolve this as part of #4768.

**Comment by eloquence** [comment]
As far as I can tell, this file is [not included in backups](https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/backup/files/backup.py), so with the current reinstall -> restore path for moving to Ubuntu 20.04, the issue would be resolved implicitly as part of the upgrade. Please let me know if I'm wrong about that. 

I'll leave it open in case we do revisit the question of in-place upgrades.

**Comment by eloquence** [comment]
The only officially supported migration path to Ubuntu 20.04 was a reinstall from a backup (which does not include this old file), so this should be fully resolved. Closing.
