### ISSUE TITLE
L10n — source interface

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1168]
During intro/testing at CPJ today, one of the concerns was l10n. The Source Interface appears to be available only in English. It should be translated into other languages and made available. CPJ may be able to assist with initial strings for some common languages like Russian and Arabic.

**Comment by toholdaquill** [comment]
On Mon, Nov 02, 2015 at 11:54:11AM -0800, Tom Lowenthal wrote:
> During intro/testing at CPJ today, one of the concerns was l10n. The Source Interface appears to be available only in English. It should be translated into other languages and made available. CPJ may be able to assist with initial strings for some common languages like Russian and Arabic.

See also issues 753, 999, 1001, and 1103.

**Comment by garrettr** [comment]
This is one of our priorities for the 0.4 release. We've been reviewing the extant pull requests that help address this concern. We completely agree that l10n is a priority; unfortunately, internationalizing software and designing useful workflows for localization is a significant amount of work. We are planning this stuff now and work on surfacing our plan and a way to monitor our progress publicly by the end of this week.

**Comment by ehartsuyker** [comment]
@garrettr I have too much time on my hands, so if you need someone to help out with that, I can be that guy.

**Comment by yuvadm** [comment]
Tracking + can help with RTL considerations for Arabic/Farsi/Hebrew

**Comment by heartsucker** [comment]
Note: `gettext` for the strings is resolved via #2308.
