### ISSUE TITLE
Download all submissions

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1171]
If there are multiple sources, their submissions must be downloaded individually. When there are lots of submissions, that can be quite laborious.

**Comment by garrettr** [comment]
This is also easy to implement. I think we should add all of the following:

1. A "Download all" button on each source's page, and/or a "download all" button in the entry for each source on the main Document Interface page
2. A "Download all unread" button on the main page, which is a one-click download of _unread_ submissions from _all_ sources.
3. A "Download all" button on the main page, which is a one-click download of _all_ submissions from _all_ sources.
    * This button should have a warning dialog that tells you how big this download is going to be, and gives you the option to continue or cancel it. This could easily grow to GBs after running a public instance for a few weeks or months, and it there are issues with downloading that much data on the Journalist Workstation because:
        1. It's over Tor, so it could take a _very_ long time (hours or days).
        2. The Journalist Workstation uses Tails, which writes to a ramdisk by default - so the maximum file you can download is the amount of RAM on your workstation (minus the amount needed to run Tails and its applications). This could easily be exceeded by downloading all submissions from a long-running SeucreDrop.

            I'm not sure what happens when you try to download a file that's too large to fit in memory on Tails. It's probably not good. You could potentially also write to the Persistent volume of the Journalist Workstation device, but that would require a manual decision from the user (Tor Browser defaults to downloading files to `~/Tor Browser`, and you have to manually switch it to `~/Persistent/Tor Browser` in the file picker). Even in that case, the Journalist Workstation is usually a smallish USB (32-64 GB), so even then you might not have enough space.

4. We could also consider offering "Download unread from selected sources" and "Download all from selected sources" to the main page (similar to the "Delete selected", "Star selected", and "Unstar selected" options that are currently present).

**Comment by pwplus** [comment]
I would like to work on this. I'll try to finish it by the end of Saturday which would correspond with the hackathon.

**Comment by garrettr** [comment]
@pwplus That's great! I'll add a card to the hackathon Trello board noting that you're working on this. If you want to work with us on Gitter/Trello, check out the info in this Trello card: https://trello.com/c/MACCDJXy/1-getting-started :smile:

**Comment by garrettr** [comment]
@pwplus Also, feel free to submit your work in smaller, modular PR's for each of the 4 types of "multiple download" buttons I described in https://github.com/freedomofpress/securedrop/issues/1171#issuecomment-153827721 if you think that makes sense.

**Comment by pwplus** [comment]
I've got the first button working. I'll make a PR.

**Comment by conorsch** [comment]
Resolved via #1467 and #1486. Will ship in 0.4.
