### ISSUE TITLE
Make wordlist usable for diceware

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1172]
The SecureDrop wordlist is carefully curated to avoid all sorts of pitfalls. It would make a great diceware wordlist. It'd be great to have an easy way of building it as a printable diceware list, or using it on a small script on the Admin Workstation to generate passphrases on the fly, or as an appendix to the installation docs that can be easily printed.

**Comment by harlo** [comment]
:+1:  great idea!

**Comment by garrettr** [comment]
I agree! However, I would say that we shouldn't necessarily use the list as-is. While it's been improved significantly over the canonical Diceware list, these improvements were done in an incremental and ad-hoc manner. I think a concentrated review of the word list could lead to further improvements.

**Comment by conorsch** [comment]
See also #1235.

**Comment by heartsucker** [comment]
I made a new diceware list (mostly by hand). This might be relevant here.
https://github.com/heartsucker/diceware

**Comment by heartsucker** [comment]
Closing this as 1) my wordlist was implemented and then 2) the EFF's was implemented.
