### ISSUE TITLE
Version Update Guide for <0.3.6

### ISSUE THREAD

**Issue by SteveNor** [freedomofpress/securedrop#1173]
Hello there,
sorry it's maybe a dumb question, but i can't find any documentation how to update to a current release, just for an pre03 Version upgrade.
It would be great to see which actions have to be considered and how to perform an update from 0.3.x to the latest release.
update_version.sh looks promising, but i cant figure out if there are some other steps suggested  to perform.
I think this should just be listed in the documentation. (Even if the only thing to do is to run the script)
Thanks in advance!

**Comment by conorsch** [comment]
@SteveNor Yes, upgrade procedures should be in the [new docs](https://docs.securedrop.org/en/latest/), but we haven't added them yet. In the meantime, drop a line to securedrop@freedom.press and I can walk you through the steps. If possible, please encrypt your message—you can find the info on the GPG key for that address [on our website](https://securedrop.org/help).

**Comment by conorsch** [comment]
Closed via #1179.
