### ISSUE TITLE
Journalist workstation template creation

### ISSUE THREAD

**Issue by tomlowenthal** [freedomofpress/securedrop#1176]
When training multiple journalists at the same time, it becomes useful to create a template image for the journalist workstation Tails drive, then replicate it. Journalists must then individually edit passphrases and so on. This should go in a training manual.

**Comment by eloquence** [comment]
We have docs now for backing up journalist workstations:
https://docs.securedrop.org/en/stable/backup_workstations.html

We're also investigating ways to simplify the build story for Journalist Workstations, e.g., #5297. In the long run, we are hoping to migrate more users to the new SecureDrop Workstation based on Qubes: https://github.com/freedomofpress/securedrop-workstation/

Closing accordingly.
