### ISSUE TITLE
Provisioning utility for journalists & Journalist Workstations

### ISSUE THREAD

**Issue by tomlowenthal** [freedomofpress/securedrop#1177]
It can be a lot of work to set up a journalist with a Journalist Workstation, either manually configuring a Tails drive from scratch, or flashing an image, then having to change passwords for Tails' persistence, and KeepassX, and setting up Yubikeys, and configuring their account on the Document interface, and giving them their passwords.

There can be a better way. Imagine a utility run by an administrator on the admin workstation. A journalist enters their desired Tails persistence passphrase, then the utility customizes a template image for a Journalist Workstation with that passphrase, configures a Yubikey, creates an account via the document interface (or similar API) with a randomly-generate passphrase which is then stored in the KeepassX database for that Tails image, a passphrase is generated for a transfer device, automatically loaded into the keyring, and then those disks are flashed and can be given to the journalist.

**Comment by zenmonkeykstop** [comment]
Closing - this a good idea, but the SecureDrop Workstation is going to reduce or eliminate the requirement to set up Journalist Workstations in the future, so any work here would be short-lived.
