### ISSUE TITLE
Handle Submissions with no Sources in currently running instances.

### ISSUE THREAD

**Issue by pwplus** [freedomofpress/securedrop#1189]
We need to handle submissions database entries in currently running instances that have no Source. This is a follow up issue to https://github.com/freedomofpress/securedrop/issues/1188.

**Comment by pwplus** [comment]
@garrettr Can you add this as a milestone? Thanks!

**Comment by fowlslegs** [comment]
X-link: https://github.com/freedomofpress/securedrop/issues/1419.

**Comment by redshiftzero** [comment]
note: the correct place to address this ticket now is in an alembic revision (with no `downgrade` implemented as this is a destructive action)

**Comment by eloquence** [comment]
We have privately received a patch for this that we'll consider, therefore moving to near-term backlog for inclusion in a future sprint.
