### ISSUE TITLE
Mitigate weak DH attack on Tor hidden services

### ISSUE THREAD

**Issue by jacksingleton** [freedomofpress/securedrop#1191]
At least for 0.2.5 and 0.2.6 (the versions included in Jessie and the Tor Debian repo respectively) tor by default uses 1024 bit DH groups from apache2 (embedded in the source, https://github.com/torproject/tor/blob/maint-0.2.6/src/common/crypto.c#L2023).   

BUT, it looks like there is an infrequently used config parameter called DynamicDHGroups. There's not a lot of documentation on this, but despite being originally implemented only for bridge servers (https://trac.torproject.org/projects/tor/ticket/4548) I _think_ it also applies to hidden services as described in the ticket above and indicated in the code (https://github.com/torproject/tor/blob/maint-0.2.6/src/or/config.c#L1507) **can someone more familiar with tor verify this?** 

Interestingly, this functionality was removed from 2.7 earlier this year: https://github.com/torproject/tor/commit/511ca9b91cec03f4ef6f23adccd5cdd47a245e5f

We should check that DynamicDHGroups applies to hidden services, and if so, add `DynamicDHGroups 1` to https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/common-app/files/torrc-app

**Comment by jacksingleton** [comment]
I asked around on Tor IRC and it seems like Tor "server_mode" does not include running hidden services, meaning that DynamicDHGroups will not apply.

DynamicDHGroups was removed in the 2.7 branch because they are moving towards ECDH. But Tor does still use DH as part of the hidden service protocol.

**Comment by flamsmark** [comment]
I don't think that SecureDrop should use a custom setup for Tor onion services. I think that it makes much more sense to let Tor fix these issues upstream.

**Comment by conorsch** [comment]
We've since added support for v3 onion services https://github.com/freedomofpress/securedrop/issues/4724, which don't have this issue. Although some orgs are still using v2, we plan to mandate use of v3 starting with the next OS migration ~2021-04 https://github.com/freedomofpress/securedrop/issues/4768#issuecomment-595981497
