### ISSUE TITLE
Remove sneakernets and separate USB keys from architecture overview diagram

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1203]
As much as I love the term sneakernet, it is not an idea we teach in trainings AFAIK. Also, there is now a singular transfer device, as opposed to USB keys A and B. We should change the architecture overview diagram to reflect this. Cross-reference #976.

**Comment by flamsmark** [comment]
How do you explain moving files to and from an airgapped machine without including the concept of a sneakernet, even if you don't use that word?

At my org, we *don't* use the same device for moving things between journalist workstations and the viewing station as we use for moving files from the viewing station to a regular computer. I agree that these labels could use updating, but I don't concur with your overall description of the process.

**Comment by fowlslegs** [comment]
@flamsmark I was mostly going off the documentation. The separation of transfer devices you describe is not explained there.

The main thing I would like to see is consistency between the diagram, the rest of the documentation, and our trainings.

@harlo maybe you have some input here.

**Comment by garrettr** [comment]
@flamsmark 

> As much as I love the term sneakernet, it is not an idea we teach in trainings AFAIK.

I don't understand this criticism. We _require_ all SecureDrop instances to manually transfer encrypted submissions from the Journalist Workstation to the Secure Viewing Station on removable media (DVD/CD-R or USB), which is the very definition of _sneakernet_.

Perhaps we don't always use this exact term, and should be more consistent, or we should define it in the documentation?

> Also, there is now a singular transfer device, as opposed to USB keys A and B.

This is true, and the diagram should be updated.

**Comment by garrettr** [comment]
@flamsmark 

> At my org, we don't use the same device for moving things between journalist workstations and the viewing station as we use for moving files from the viewing station to a regular computer.

If you are using USB to transfer to and from the Secure Viewing Station, I don't see a meaningful security benefit for using separate USB keys for these different tasks. However, I do see a potential compatibility benefit, in that (per our documentation) you are using a Linux-compatible encrypted LUKS device to transfer between the Journalist Workstation and the Secure Viewing Station, which are both running Tails, but when you transfer from SVS to a "regular computer", the "regular computer" may not be running Tails and so you might need to use a differently formatted USB stick.

**Comment by fowlslegs** [comment]
@garrettr Sorry I can't remember who I brought the term sneakernet up to in person, but someone told we don't really use that term anymore. We at least don't use it in the docs, except for the diagram and a passing mention in the terminology page--not in the actual instructions on moving files to/ from the airgap. We can just make it a single sneakernet (as opposed to A and B) if we want to keep the term. I'm all for that.

> I don't see a meaningful security benefit for using separate USB keys for these different tasks

I agree.

>, I do see a potential compatibility benefit, in that (per our documentation) you are using a Linux-compatible encrypted LUKS device to transfer between the Journalist Workstation and the Secure Viewing Station, which are both running Tails, but when you transfer from SVS to a "regular computer", the "regular computer" may not be running Tails and so you might need to use a differently formatted USB stick.

Handling this could be another issue.

**Comment by flamsmark** [comment]
Yes @garrettr, that's exactly right. Our **Transfer Device**s — for moving submissions from a **Journalist Workstation** to a **Secure Viewing Station** are all ext4+LUKS. For moving files from a **Secure Viewing Station** to another computer, we use a regular/unrelated FAT thumb drive or a DVD.

**Comment by mark-in** [comment]
There is no extra `sneakernet` word in the diagram anymore (#1211) because transfering over a sneakernet is explained via media between `Areas` (like Tor).

**Comment by conorsch** [comment]
Closed via #1211. Thank you for your excellent contributions, @mark-in!
