### ISSUE TITLE
Improve developer docs

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1208]
The new docs format is a joy. The recent hackathon shed light on a few aspects of our setup that cause problems for first-time contributors. 

### Documentation expansion
- [x] explanation of the automated tests (both travis and snap)
- [x] useful commands for rebuilding packages
- [ ] ~document need to build ossec packages for staging~ (no longer necessary; see #1668)
- [x] useful commands for running tests locally
- [x] clearer descriptions of the staging environments
- [ ] ~explain use of `vagrant-digitalocean` plugin for remote testing~ (no longer necessary; see #1666)
- [x] document management scripts for `pip` requirements (see https://github.com/freedomofpress/securedrop/pull/1348#issuecomment-240582768)
- [x] explicit version recommendations for:
  - [x] vagrant
  - [x] ansible
  - [x] virtualbox
- [x] document CI pipeline (especially any manual actions required by FPF staff)

### Documentation reformatting
- [x] breakout the environment descriptions into separate page
- [x] clean up .travis.yml file (linting only)
- [x] consistently make `code` blocks copypastable (no prefixed `$`)
- [x] update "copyright" year in docs
- [x] add SD logo to navbar

Right now much of the developer docs are folded into a **Getting Started** section. Breaking out the environment descriptions to a dedicated page would make the docs easier to navigate.

**Comment by conorsch** [comment]
#1381 shows a clear need for explicit versioning in VirtualBox. Do the same for Ansible (related: #1146).

**Comment by conorsch** [comment]
#1306 and #1379 changed the workflow for updating Python dependencies via the `pip_update.sh` script. [From a comment in](https://github.com/freedomofpress/securedrop/pull/1385#issuecomment-242007476) #1385:

> That should not be necessary with the current pip-compile-based workflow. The idea is that the requirements/*.in files list direct dependencies of SecureDrop, and we use pip-compile to generate the requirements/*.txt files from the *.in files, which contain all of the dependencies (including dependencies of dependencies, and so on, for SecureDrop).

> Whenever the *.in files are updated, pip_update.sh should be run to update the *.txt files in tandem. This has been the practice for all of the pull requests related to updating the Python dependencies so far (see #1306 and #1379 for examples).

That's very important to document clearly for devs.

**Comment by fowlslegs** [comment]
We could actually pin a version of Ansible in a top-level requirements directory similar to how I've done in [FingerprintSecureDrop](https://github.com/freedomofpress/FingerprintSecureDrop/tree/master/requirements). Also see [relevant README section instructions](https://github.com/freedomofpress/FingerprintSecureDrop#getting-started). Note, these requirements are totally separate from the [application requirements](https://github.com/freedomofpress/FingerprintSecureDrop/tree/master/fpsd/requirements) which are installed by Ansible during provisioning of the crawler role.

**Comment by conorsch** [comment]
Working on updating the docs now, in preparation for this weekend's hackathon.

**Comment by conorsch** [comment]
Now that #1666 is merged, we should have all the functionality we need to document merged into `develop`; will get some changes rolling here shortly.

**Comment by conorsch** [comment]
For codeblocks, I'll make them all copy/pasteable by removing the `$` shell prompt indicator. In the few cases where we use a codeblock to record a terminal session, meaning both typed commands and text printed to stdout, I'll preserve the `$` shell indicators on the lines for typed commands.
