### ISSUE TITLE
Publish non-binary source of the static images (like logo)

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#1217]
There is a need to adapt the logo for demonstration/presentation/keynote purposes. Unfortunately there are no source files (vector graphics) for all binary PNGs in the repo. Could someone upload them to the repo? @micahflee?
[Maybe we need a separate repo for SecureDrop-related media like logos/slides/etc ?]

**Comment by eloquence** [comment]
Since this issue was filed, we've published logo assets & sources here:
https://github.com/freedomofpress/securedrop-ux/tree/main/SD%20Branding

Closing.
