### ISSUE TITLE
Document google-authenticator setup for login via tty

### ISSUE THREAD

**Issue by neo-luddite** [freedomofpress/securedrop#1219]
I had he problem that after the playbooks ran through smoothly I wasn't able 
to access mon and app via the .onion adresses. I tried logging in via tty   
and failed. I figured out that google-authenticator needs to be configured to
be able to log in via tty (which is supposed to happen after logging in via .onion for the first time ). maybe mentioning this as a note in the admin guide would be good for future references. tnx

**Comment by neo-luddite** [comment]
btw: I'd suggest to recommend "free otp" to be used as OTP-app for android and not the "google authenticator app". "free otp" is open source, available on google play and fdroid (on the later as a reproducible build). At leastor list it as an alternative. tnx!

**Comment by conorsch** [comment]
The docs for the OTP 2FA are here: https://docs.securedrop.org/en/latest/google_authenticator.html, under **Topic Guides**, but that page isn't referenced by Admin Guide or the Install Guide. A logical place for cross-linking would be at the end of the **Install SecureDrop** page: https://docs.securedrop.org/en/latest/install.html, with explicit mention of physical logins.

**Comment by neo-luddite** [comment]
it's also mentioned in 
https://docs.securedrop.org/en/latest/configure_admin_workstation_post_install.html 

at the bottom of the page.

**Comment by conorsch** [comment]
Yes, that's probably the best place for the updated instructions to go. I've updated PR #1237 to implement the changes. If you have any concerns about clarity, @neo-luddite, let me know.

**Comment by flamsmark** [comment]
Why bother requiring TOTP 2FA for tty login? Anyone with local access to the machines can do whatever they want anyway. And remote access via SSH doesn't use this 2FA scheme because Ansible makes so many SSH connections that it's impractical to enter codes constantly. Why not fully deprecate the TOTP process?

**Comment by garrettr** [comment]
@flamsmark Couldn't agree with you more; my [thoughts](https://github.com/freedomofpress/securedrop/pull/1237#issuecomment-193541532) on the issue. 2FA for tty login is currently optional, and I believe we should phase it out entirely in an upcoming release.
