### ISSUE TITLE
Warn or stop a source from submitting documents with compromising metadata

### ISSUE THREAD

**Issue by bxjx** [freedomofpress/securedrop#122]
Uploading documents containing metadata may reveal information about the source. E.g. http://www.theguardian.com/world/2012/dec/04/john-mcafee-confirms-guatemala-vice

Metadata can be scrubbed by a journalist on the viewing station using the [Metadata Anonymization Toolkit](https://mat.boum.org/) (MAT), but I think it would be better if the source was prevented, or at least warned, about submitting these documents in the first place. Ideally the source would use MAT, but this might be too much to expect.

Perhaps SecureDrop could have a configuration option to prevent the upload of any document except those that could be scanned for metadata on the client side?

I've written some code that scans PDFs before they are uploaded and asks the user to confirm that none of the metadata in the document compromises their identity. The code requires javascript but does not use any extensions or server communication. It does require a modern browser. It works on the version of Firefox included in the TOR Bundle. I think I could possibly write similar code for JPGs and possibly other formats.

On a related note, it might be worth preventing/warning the upload of certain document types that may contain hidden information other than metadata. E.g. Microsoft Word Documents may contain pass edits that can be reverted and therefore retrieved.

This issue is probably also related to #101 and #119.

**Comment by fowlslegs** [comment]
Our stance on JS in the source interface has not shifted in years, so I'm going to go ahead and close this one, even though it's a cool idea.

**Comment by redshiftzero** [comment]
Does this _need_ to be done in JS? What about having this done on the server side? I realize that this is not ideal, but until we have a magical browser extension that executes signed JS, it's probably better than just having sources submit documents with all kinds of metadata they might not even realize are there. App code examines the document, returns some useful feedback to source "Hey Col Biggins you might want to remove your name from the Author field" and let them strip off the metadata they don't want the journalist to know?

**Comment by fowlslegs** [comment]
Processing documents adds greatly to the attack surface. Submissions may take hours to transfer, only to warn the source they may want to use some tool they've never heard and then re-submit. How do we distinguish useful metadata (e.g., DKIM on someone else's emails) vs harmful metadata (e.g., time data in JPG metadata in a photo taken covertly by the source)?

**Comment by redshiftzero** [comment]
The processing you just described could be done on the server side no? It seems like a good first step would be just to display to the source "Here's the metadata your file has in it". Instead of referring them to another tool, we could just ask them to check the fields they'd like to be wiped. If we worry about handling every possible type of file then this could get really unwieldy, but if we stick to the most common files, e.g. PDFs, then this could be a very nice and useful feature for sources to understand what they are actually doing and protect their identity when they are leaking documents.

**Comment by fowlslegs** [comment]
The processing I described is heavily problematic for the reasons I described. Processing of documents on the Application Server opens up a huge vector for compromise, not to mention how this may hurt UX. I think we'll just end up scaring away sources who won't be able to grasp the significance of all the metadata we display to them.
