### ISSUE TITLE
ossec emails rejected due to "@ossec.server" sender domain

### ISSUE THREAD

**Issue by neo-luddite** [freedomofpress/securedrop#1220]
ossec alerts didn't work for me out of the box because the sender
email is @ossec.server which gets rejected because the domain doesn't
exist. my workaround are postfix generic tables for manipulating the
sender domain.

**Comment by ageis** [comment]
The OSSEC alerts require some configuration. The sender e-mail should be sasl_username@sasl_domain. You are routing through another mail server, correct? Is it one you operate, or a different third party? Is this the staging or production environment?

This might be a legit issue.
Line 41 in ./group_vars/securedrop_monitor_server.yml: `postfix_hostname: ossec.server`

**Comment by garrettr** [comment]
@neo-luddite Did you configure the OSSEC alerts per our documentation? See https://docs.securedrop.org/en/latest/install.html and https://docs.securedrop.org/en/latest/ossec_alerts.html.

**Comment by neo-luddite** [comment]
I'm using one of our production mailservers as a mail relay. 
In production-specific.yml  I entered the following values accordingly to my setup:

> smtp_relay: "mail.example.net"
> smtp_relay_port: "25"
> sasl_username: "abc"
> sasl_domain: "example.net"
> sasl_password: "password"

/var/ossec/etc/ossec.conf: 
> \<email_from\>ossec@freedom.press\</email_from\>

mail.log:
> postfix/smtpd[1761]: connect from localhost[127.0.0.1]
> postfix/smtpd[1761]: 71B0DA0048: client=localhost[127.0.0.1]
> postfix/cleanup[1763]: 71B0DA0048: message->id= 20151214101336.71B0DA0048@ossec.server>
> postfix/qmgr[1555]: 71B0DA0048: from=<ossec@freedom.press>, size=612, nrcpt=1 (queue active)
> postfix/smtpd[1761]: disconnect from localhost[127.0.0.1]
> postfix/local[1764]: 71B0DA0048: to=<ossec@ossec.server>, orig_to=<root@localhost>, relay=local, delay=0.12, delays=0.08/0/0/0.04, dsn=2.0.0, status=sent (delivered to command: /usr/bin/procmail)
>postfix/qmgr[1555]: 71B0DA0048: removed
>postfix/pickup[1554]: A0A33A09A1: uid=1002 from=<ossec>
>postfix/cleanup[1763]: A0A33A09A1: message-id=<20151214101336.A0A33A09A1@ossec.server>
>postfix/qmgr[1555]: A0A33A09A1: from=<ossec@ossec.server>, size=1591, nrcpt=1 (queue active)
>postfix/smtp[1667]: A0A33A09A1: to=<XXX@XXX.XX>, relay=mail.example.net[XX.XX.XX.XX]:25, delay=0.4, delays=0.05/0/0.26/0.09, dsn=4.1.8, status=deferred (host >mail.example.net[XX.XX.XX.XX] 
said: 450 4.1.8 <ossec@ossec.server>: Sender address rejected: Domain not found (in reply to RCPT TO command))

so ossec sends from freedom.press, postfix rewrites it to ossec.server which gets rejected by the mail_relay due to beeing non-existand. this seems coherent (from my dilettante pov) with postfix main.cf:

> myhostname = ossec.server
> myorigin = $myhostname

**Comment by neo-luddite** [comment]
I had to do a fresh install for getting rid of the FDE. I changed `postfix_hostname: ossec.server` to `postfix_hostname: example.net`  (my according value), that solved the problem for me, ossec mail notifications are working. so "{{  sasl_domain }}"  in host_vars could do the trick.

**Comment by sigvei** [comment]
Fresh 0.3.9 install here. The e-mails have a From-address of ossec.server, and this fails with some mail relays. 

To fix this, I had to SSH into mon. I added to `/etc/postfix/main.cf`:

`sender_canonical_maps = hash:/etc/postfix/canonical`

And created a file `/etc/postfix/canonical`, with one line:

`@ossec.server real.email@address.com`

Then I ran `sudo postmap /etc/postfix/canonical` (and, obviously, `service posfix reload`).

I guess this will be overwritten at next ansible runthrough, but this should point to what might need to be changed in the configuration.

**Comment by sighmon** [comment]
I also had some problems when setting ```sasl_domain: ""``` empty in ```prod-specific.yml```.

Which output:

```sh
# /etc/postfix/sasl_passwd
[smtp.relay.net]:587  username@:passphrase
```

When ```sasl_domain: ""``` is left empty, could the output remove the ```@``` symbol?

**Comment by conorsch** [comment]
This was handled #1565.
