### ISSUE TITLE
docs.securedrop.org THS is not working

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1228]
Filing a separate issue, this was originally reported in a comment in https://github.com/freedomofpress/securedrop/issues/1227#issuecomment-164757438:

The Docs are not working for THS. http://docs.secrdrop5wyphb5x.onion/ redirects to https://analytics.freedom.press/ with 302 Found. Using docs.securedrop.org with CAPTCHA each page is really, really annoying (and it's unsolvable most of the time).

**Comment by ageis** [comment]
@garrettr just fixed this. @mark-in thanks for reporting.

The docs are now available on the subdomain of our Tor hidden service: http://docs.secrdrop5wyphb5x.onion/

**Comment by conorsch** [comment]
@ageis Nice! Working great over here. Unfortunately folks will still have to edit the URL manually to get to http://docs.secrdrop5wyphb5x.onion/, but at least we support it now.

**Comment by mark-in** [comment]
@ageis, thanks! Now it's usable.

btw, is it OK to have Google Analytics at http://docs.secrdrop5wyphb5x.onion/?
From the docs: *`Don’t use 3rd party analytics, tracking, or advertising`*.... :smiley:

**Comment by ageis** [comment]
@mark-in We're aware of the Google analytics, that's a feature added by Read the Docs, not us. They are hosting the documentation currently. We have an internal issue for self-hosting Read the Docs without Google analytics.
