### ISSUE TITLE
Replace confusing OS X screenshots with Tails ones in Journalist Guide

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#1231]

**Comment by conorsch** [comment]
Completely agree here. We should target the **User Guides** and replace the OS X screenshots (taken with VMs) with screenshots made in Tails on a hardware test instance. Doing so would go a long way in standardizing on Tails for the right and proper OS for accessing SecureDrop, regardless of role.

**Comment by fowlslegs** [comment]
Closing this since it's already tracked in #1544.
