### ISSUE TITLE
Rewrite static/js/source.js removing jquery requirement for source interface

### ISSUE THREAD

**Issue by evilaliv3** [freedomofpress/securedrop#1233]
It seems to me that currently on the source interface jQuery is included but required only by: https://github.com/freedomofpress/securedrop/blob/develop/securedrop/static/js/source.js

It would be valuable to rewrite such library so to remove jQuery requirement.

From a small analysis few functions would be needed:

1) a function to show/hide html elements; this is doable in standard javascript with:

``` javascript
          document.getElementById("element_id").style.display = "none";  // hide
          document.getElementById("element_id").style.display = "block"; // show
```

2) a function for adding a class to html elements; this is doable in standard javascript with:

``` javascript
          document.getElementById("element_id").className += "additional_css_class";
```

3) fading/fadout functions; not immediatly doable but can it's fancy-only stuff that can be either removed or be implemented in CSS

**Comment by redshiftzero** [comment]
Once #2405 is addressed, this can be picked back up based on the work so far in PR #1298 branch `kaizensoze-remove-jquery`
