### ISSUE TITLE
Totally unmemorizable stuff in the wordlist

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#1235]
With high probability a source get a phrase-like codename consisting of words. But sometimes one can get something like
`crest sill 86 crt plushy 13th rebut`.
Numbers are easy to forget. Words leave some trace in human memory (one can remember a word by its length/shape/etc). Numbers are not.
It's all because of [`wordlist`](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/wordlist#L6515). A possible fix is to replace all numbers with words generated additionally.

**Comment by heartsucker** [comment]
I made a new diceware list (mostly by hand). This might be relevant here.
https://github.com/heartsucker/diceware
