### ISSUE TITLE
Git clone fails journo/admin workstation

### ISSUE THREAD

**Issue by dbgdngit** [freedomofpress/securedrop#1238]
I'm trying to build a new Journo tails usb and a a new admin tails usb

With Tails 1.8.2

after cd ~/Persistent

git clone https://github.com/freedomofpress/securedrop.git fails

Error :Couldnt resolve host github.com while accessing https://github.com/freedomofpress/securedrop.git/info/refs
fatal: HTTP request failed

I can access the site fine via tor browser on same installation so resolve doesnt make sense

**Comment by dbgdngit** [comment]
ok - it works using http and not https..odd

**Comment by conorsch** [comment]
@dbgdngit Oh dear. Can you reproduce after reboots? Can you git clone _any_ HTTPS URL, or do they all fail? For instance, try:

```
git clone https://github.com/tails-developers/testing-dummy
```

via the [Tails bugtracker](git clone https://github.com/tails-developers/testing-dummy).

**Comment by dbgdngit** [comment]
git clone https://github.com/tails-developers/testing-dummy works

2 different sticks across multiple reboots didnt work with securedrop git

**Comment by redshiftzero** [comment]
Hey @dbgdngit did you find a solution to this?

**Comment by conorsch** [comment]
I'm assuming the solution here was "wait a while and then it magically worked." Wasn't able to reproduce myself at the time of first report. Given the staleness of the ticket, let's go ahead and close. Holler if you have notes to share that should be folded in project documentation, @dbgdngit!

**Comment by dbgdngit** [comment]
Yeah, happy to close. I've used several other tails installs without issue

On 6 December 2016 22:34:16 GMT+00:00, Conor <notifications@github.com> wrote:
>I'm assuming the solution here was "wait a while and then it magically
>worked." Wasn't able to reproduce myself at the time of first report.
>Given the staleness of the ticket, let's go ahead and close. Holler if
>you have notes to share that should be folded in project documentation,
>@dbgdngit!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/freedomofpress/securedrop/issues/1238#issuecomment-265294915

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
