### ISSUE TITLE
Journalists should be able to thread messages or put messages into folders

### ISSUE THREAD

**Issue by trevortimm** [freedomofpress/securedrop#125]
One of the biggest complaints from the New Yorker was that once you start getting a lot of people sending you things, the current setup gets disorganized pretty quickly. This was mentioned in the security audit too. Being able to arrange all the files and messages into folders arranged by source codename and/or being able to thread messages will alleviate this problem.

**Comment by redshiftzero** [comment]
A crack at implementing this feature exists in PR #1422, suggestions/feedback welcome

**Comment by redshiftzero** [comment]
This is something that will be tackled with the journalist client in the upcoming [SecureDrop workstation](https://github.com/freedomofpress/securedrop-workstation).

**Comment by eloquence** [comment]
Closing in favor of specific workflow improvements to the [SecureDrop Client](https://github.com/freedomofpress/securedrop-client), as we're not currently planning to revisit this in the SecureDrop Core Journalist Interface (feature parity with Client improvements will be determined on a case-by-case basis).
