### ISSUE TITLE
Backup script does not GPG encrypt zip file, does not name file correctly

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1250]
While running the `securedrop-prod.yml` playbook, the `fetch` and `srm` commands fail because the script that backs up the config files does not `gpg` encrypt the zipped file. The `stdout` from this command reflects this (it lacks the `.gpg` extension).

My env.
```
Host: Tails 2.0.1
Target: Ubuntu 14.04.3

amnesia@amnesia:~/Persistent/securedrop/install_files/ansible-base$ python --version
Python 2.7.9
amnesia@amnesia:~/Persistent/securedrop/install_files/ansible-base$ ansible --version
ansible 1.7.2
amnesia@amnesia:~/Persistent/securedrop/install_files/ansible-base$ uname -a
Linux amnesia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
```

The failures it causes.

```
TASK: [backup | fetch the created backup file back to the host machine's
ansible_base directory] ***
failed: [app] => {"failed": true, "file":
"/tmp/sd-backup-2016-03-05--18-09-03.zip.gpg"}
msg: the remote file does not exist

FATAL: all hosts have already failed -- aborting
```

```
TASK: [backup | secure delete the encrypted backup requires
secure-delete package] ***
failed: [app] => {"ansible_job_id": "984641593190.13724", "changed":
true, "cmd": ["srm", "/tmp/sd-backup-2016-03-05--18-12-39.zip.gpg"],
"delta": "0:00:00.002954", "end": "2016-03-05 18:13:02.044976",
"finished": 1, "rc": 1, "start": "2016-03-05 18:13:02.042022"}
stderr: Error: File /tmp/sd-backup-2016-03-05--18-12-39.zip.gpg - No
such file or directory
<job 984641593190.13724> FAILED on app

FATAL: all hosts have already failed -- aborting
```

The workaround for this was to remove the `.gpg` extensions from the playbook.

**Comment by conorsch** [comment]
@ehartsuyker This one has me a bit confused. Can you try executing the script that gets copied `/tmp` interactively, and check for error output? I'm concerned that there's a problem with the GPG keyring. You can also try running on just the Monitor Server with `--limit mon` and see if it fails there (the Monitor Server also has ATHS values that should be backed up to the Admin Workstation, just in case).

**Comment by ehartsuyker** [comment]
@conorsch Yeah, a keyring problem makes sense. That could also explain https://github.com/freedomofpress/securedrop/issues/1252 . I'll check when I get home tonight.

**Comment by conorsch** [comment]
Closing in favor of #1252. @heartsucker if you're still having trouble, let me know!
