### ISSUE TITLE
Unable to submit documents to source interface (SD 0.3.6)

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1252]
With a clean set of servers and a fresh, sucessful install with `ansible`, attemping to submit a doc via the `.onion` address causes an internal server error.

### Exact Steps
1. Install SD 0.3.6
2. Go to the `.onion` address
3. Click `Submit Documents`
4. Get codename, click `Continue`
5. Type `test` as a message, upload no docs
6. Click `Submit`
7. the `/submit` page says `Sorry, the website encountered an error and was unable to complete your request.`

### Logs 'n Stuff

My env:
```
root@app:/var/log# python --version
Python 2.7.6
root@app:/var/log# uname -a
Linux app 3.14.48-grsec #1 SMP Mon Jul 27 11:41:51 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
root@app:/var/log# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

Output from `securedrop_worker/err.log`
```
18:08:36 RQ worker started, version 0.4.6
18:08:36 
18:08:36 *** Listening on default...
18:20:28 RQ worker started, version 0.4.6
18:20:28 
18:20:28 *** Listening on default...
09:57:50 RQ worker started, version 0.4.6
09:57:50 
09:57:50 *** Listening on default...
```

Output from `securedrop_worker/out.log`
```
Error 101 connecting to localhost:6379. Network is unreachable.
```

And `localhost` is in `/etc/hosts`.

Output from `netstat -tupln` 
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN      1348/apache2    
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      1348/apache2    
tcp        0      0 127.0.0.1:22            0.0.0.0:*               LISTEN      1030/sshd       
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1118/redis-server 1
udp        0      0 10.20.2.2:123           0.0.0.0:*                           1282/ntpd       
udp        0      0 127.0.0.1:123           0.0.0.0:*                           1282/ntpd       
udp        0      0 0.0.0.0:123             0.0.0.0:*                           1282/ntpd       
udp6       0      0 :::123                  :::*                                1282/ntpd 
```

Redis seems happy (and the logs show no errors):
```
root@app:/var/log# redis-cli
127.0.0.1:6379> ping
PONG
```

`/var/www/securedrop/securedrop/securedrop.log` does not exist.

`/var/log/apache2/{access, document-access, error, other_vhosts_access}.log` are empty.

`/var/log/apache2/document-error.log`:
```
[Sun Mar 06 09:59:35.966087 2016] [:info] [pid 1352:tid 3402257479552] mod_wsgi (pid=1352): Attach interpreter ''.
[Sun Mar 06 09:59:35.966360 2016] [:info] [pid 1352:tid 3402257479552] mod_wsgi (pid=1352): Adding '/var/www/securedrop' to path.
[Sun Mar 06 09:59:35.966321 2016] [:info] [pid 1351:tid 3402257479552] mod_wsgi (pid=1351): Attach interpreter ''.
[Sun Mar 06 09:59:35.966567 2016] [:info] [pid 1351:tid 3402257479552] mod_wsgi (pid=1351): Adding '/var/www/securedrop' to path.
```

**Comment by garrettr** [comment]
@ehartsuyker Attempting to repro now.

**Comment by ehartsuyker** [comment]
Ok, I'm narrowing in on the problem. I had the wrong fingerprint (admin, not app) in the playbook. Fixing this allowed the app to submit documents. However, the documents were not encrypted. Or zipped. Gzip can't open the `.zip`, and it's definitely not `pgp` encrypted.

**Comment by ehartsuyker** [comment]
Further fun. If I go and download the files individually, the decrypt, but the `.zip` still is just... garbage?

So I can submit docs, download them, and decrypt them, but this still feels broken. Huh.

**Comment by conorsch** [comment]
Closing in favor of #1257, which identifies a narrow problem (i.e. lack of automatic verification of GPG fingerprints) quite well. Thanks for the verbose command examples, @heartsucker!
