### ISSUE TITLE
When refering hackpad.com, make the docs available

### ISSUE THREAD

**Issue by KwadroNaut** [freedomofpress/securedrop#1255]
Training schedule (https://github.com/freedomofpress/securedrop/blob/develop/docs/training_schedule.rst) refers to securedrop.hackpad.com, which seems to be an internal only place. Can you either open up those documents, add a little note of how to get access to them or remove that url so people don't get confused?

**Comment by conorsch** [comment]
@KwadroNaut You're completely correct. We've migrated away from Hackpad even for internal documents recently, so the best solution is just to remove mention of the Hackpad docs entirely.

While we're at it, the Training Guide would be more useful if it linked to other sections of the docs, particularly for the topic guides. @harlo Can you take a look at the [rendered Training Guide](http://securedrop.readthedocs.io/en/latest/training_schedule.html) and see if there's anything you'd like added or removed? Targeting develop for updates here would be fine.
