### ISSUE TITLE
GPG keys should be validated against fingerprints before provisioning

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1257]
The application will fail if the GPG key fingerprint is wrong.

Related: https://github.com/freedomofpress/securedrop/issues/1252

**Comment by conorsch** [comment]
Ah-ha! Glad we were able to ferret that out. What, praytell, was the exact nature of the problem? My plan at present is to beef up the validation of variables declared in the site-specific vars prior to applying the playbooks to the servers.

Was your problem mismatched whitespace? A typo? I'd like to make sure new filters address the specific problem you had, so we can confidently say it won't happen on future versions.

**Comment by ehartsuyker** [comment]
@conorsch I have an admin GPG key and an app GPG key in my keyring both under the same email, but I grabbed the wrong one. I actually assumed they were both provided so the fingerprint would validate the key (since the fingerprint can be automatically pulled from the key).

**Comment by conorsch** [comment]
@heartsucker wrote an implementation to address this problem in #1259. Rather than use a bash script, let's try the more tedious—but idempotent—approach in pure Ansible tasks.

Other improvements to the "validate" role are tracked in:
* #749 
* #858 
* #1029

**Comment by conorsch** [comment]
Related: #858.
