### ISSUE TITLE
Backup fails on app-prod VM

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1268]
Ansible 1.8.4
OSX 10.11.3
SD: commit 051ab3e
Command: `vagrant up mon-prod app-prod`

Ansible output:
```
TASK: [backup | Run the collect script to backup all the needed files to perform a restore] ***
failed: [app-prod] => {"ansible_job_id": "19696324056.3608", "changed": true, "cmd": ["/tmp/0.3_collect.py"], "delta": "0:00:00.058255", "end": "2016-03-28 08:22:37.218452", "finished": 1, "rc": 1, "start": "2016-03-28 08:22:37.160197", "warnings": []}
stderr: Traceback (most recent call last):
  File "/tmp/0.3_collect.py", line 18, in <module>
    import config
ImportError: No module named config

FATAL: all hosts have already failed -- aborting
```

This does *not* fail when running `vagrant up mon-staging app-staging`

**Comment by conorsch** [comment]
Finally able to reproduce this issue—thanks for providing the specific commit. Looks like the prod playbook is broken on develop, as the `Configure SecureDrop Application Server` play is being skipped entirely. Not sure why that is yet, likely a small typo somewhere.

The test suite for prod fails miserably, and shows that the deb packages on the App Server aren't being installed, which led me to identify the skipped play. Will continue to investigate why th eplay isn't being triggered.
