### ISSUE TITLE
Unable to remotely provision Yubikey

### ISSUE THREAD

**Issue by tomlowenthal** [freedomofpress/securedrop#1272]
As an admin, I would like to change a user's Yubikey asynchronously, and without being in the same place as them.
### Expected steps
1. initialize new Yubikey, noting HOTP key
2. send Yubikey to user
3. confirm that user has received Yubikey
4. use admin workstation to log into document interface
5. add Yubikey to account by pasting in HOTP secret
6. [at next login, user must use Yubikey]
### Problem

Adding a Yubikey to a user's account requires entering an HOTP code to confirm. There is no way around this confirmation step.
#### Unsuitable alternatives

**Change the Yubikey then send it to the user.** This approach would temporarily deny the user access to SecureDrop. One the new Yubikey was added to their account, they would no longer be able to log in with their old one. Until they received the new Yubikey, they would be unable to use SecureDrop. In addition, that active Yubikey presents something of a security concern while it's en route.

**Synchronous change-over.** It would be possible to provision the new Yubikey if the user and admin are able to speak over the phone. The user can plug in the new Yubikey and tap it to create an HOTP code which they read to the admin. However, this relies on the user and admin being available simultaneously to perform the change-over. This may be impractical due to time-zones or other logistical matters. It also presents a barrier to changing many users' Yubikeys efficiently.

**Comment by zenmonkeykstop** [comment]
Users can now update their own HOTP secret, which mitigates this somewhat. Closing, as there's no clear path to improvement.
