### ISSUE TITLE
develop: *ths files are not formatted correctly

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#1278]
In `./roles/restrict_direct_access/tasks/fetch_tor_config.yml` we are writing the Tor hidden service hostname files to the Admin Workstation. 

In each file there is supposed to be a newline after the string, but the included `\n` does not evaluate properly and is being escaped. See line 34: https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/restrict-direct-access/tasks/fetch_tor_config.yml#L34

This results in an actual `\n` string in the file, so when `tails_files` goes to write `torrc_additions` and append them together, and in turn the `securedrop_init` script uses that as an input, it writes an invalid torrc configuration. HidServAuth values after the first one are commented out and appear on one line (due to the username comment at the end of the previous line and lack of a newline), i.e.

```
HidServAuth kel7ydurccybpmza.onion AqKdqDOPgBjOtfeBry6YPh # client: admin\nHidServAuth qnfbry5cjxpqo2qr.onion 3vZDrCUJvYB8477VLPSMQR # client: admin\n
```

**Comment by garrettr** [comment]
Good find. Did this ever work? That [change](46e8c2bbfb2ac91be42820171f912ae61a2fbb99) was made recently (ish) so it's possible that it just never worked.

Is this only a problem on develop, or also on the current stable release (0.3.6)?

**Comment by ageis** [comment]
@garrettr This code is new (part of the Ansible re-org and only in develop), not an issue in the current stable release.

**Comment by conorsch** [comment]
Almost certainly due to a discrepancy in Ansible versions, since v2 changed escaping strategies for special chars in a lot of contexts. I'll test multiple versions and report back.

**Comment by garrettr** [comment]
@conorsch That makes sense to me. @ageis What version of Ansible did you test with?

**Comment by ageis** [comment]
Ah, I was running 2.0.1. Forgot I'm supposed to be using 1.9.4.

**Comment by garrettr** [comment]
This is still good to know for our upcoming move to Ansible 2.x :-)

**Comment by conorsch** [comment]
@ageis Thanks. And it's still good to track these changes so we're not surprised by them. I'm betting the breakage only occurs after v2, and it'd be best to refactor in a way that supports both styles.

**Comment by ageis** [comment]
That would explain why a few other tasks in the playbook failed and I was only able to finish the playbook by re-running it several times ;)

**Comment by conorsch** [comment]
Confirmed it's an Ansible version problem.

## 1.9.4
* files are written with newline appended correctly
* files are written to `install_files/ansible-base`

## 2.0.1
* files are written with an escaped newline inline (bad)
* files are written to repo root when run via vagrant (surprising)

Will work on a fix that handles both cases.
