### ISSUE TITLE
zlib inflate problem

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1279]
When receiving a submission through SecureDrop, I encountered an error that rendered me unable to decrypt the entire submission. This is on an SD instance where I have downloaded other documents and messages and decrypted them on the SVS no problem. I am using SecureDrop 0.3.6 and the Tails drives use Tails 2.2.1. 

As usual, I download the document (2-firstword-secondword-doc.gz.gpg) from the web interface to to the DTD, transfer it over to the SVS, copy over, and try to decrypt by manually clicking the file. Decryption begins and seems to proceed as usual, until a dialog box appears that reads "Couldn't decrypt file: 2-firstword-secondword-doc.gz.gpg No data". 
### What I checked:

1) I have verified that the file was downloaded correctly from the webapp: I downloaded the file from the web interface several times and verified that the hashes of each file were the same (perhaps some option to display a hash in the UI of the webapp may be useful?). 

2) In order to see what the issue with the decrypt was, I try to decrypt on the command line:
`gpg --decrypt 2-firstword-secondword-doc.gz.gpg > 2-firstword-secondword-doc.gz`

When I do this, the output displays that the file was indeed encrypted to the SD application public key, then I get the following error:

`gpg: fatal: zlib inflate problem: invalid block type`
`secmem usage: 2528/12768 bytes in 4/28 blocks of pool 13088/65536`

I've tried both gpg and gpg2 - which are using GnuPG 1.4.18 and GnuPG 2.0.26 respectively - and get the same `zlib inflate problem` for both. 

However, in order to view some of the documents from the submission, I did the following: 
`gunzip < 2-firstword-secondword-doc.gz > 2-firstword-secondword-doc.tar`

I open the .tar, and see an alphabetic listing of documents, all of which I can open and read no problem, up until but not including the last file (alphabetically) in the partial decrypt (presumably where the decryption failed). 

Have you encountered this error/issue before or have any thoughts? 

Thanks for your time!

**Comment by garrettr** [comment]
Thanks for reporting this! I have not encountered any issues like this while using or testing SecureDrop. I will look into further and keep an eye out for issues like it in the future.

**Comment by freddymartinez9** [comment]
Hi @garrettr @redshiftzero (also @ageis ) I was able to resolve the issue on the same archive that was having problems. I did some research on zlib and gpg and found this problem came up with "large" archives. I did some simple redirects on the CLI: 
`gpg --decrypt < 2-firstword-secondword-doc.gz.gpg > 2-firstword-secondword-doc.gz`

**It works! ** From there the GUI tools also worked as expected, no need to redirect to gunzip or create tar archives. There was also discussions online on using bzip2 instead of zlib for decryption (although I don't know if/how that would on SD).

**Comment by garrettr** [comment]
@freddymartinez9 Wow, that's really strange. Sounds like a bug in GPG. It's good you found a workaround - we might consider adding a note to the documentation about this.

I made some large submissions to SecureDrop the other week while I was testing the backup and restore processes - I can try to take a look later this week and see if any of them have this problem, which would be a helpful test case.

If you have a reproducible test case (that obviously isn't derived from an authentic submission to your SecureDrop instance), we'd be interested in taking a look at it.

**Comment by freddymartinez9** [comment]
We tried this again and I was able to decrypt it using the GUI without the use of redirect. I did note that the DTD that we used was different than @redshiftzero's.  I'm still not sure how to reproduce this.

**Comment by garrettr** [comment]
I don't think the DTD should make a difference one way or the other. The fact that you were able to successfully decrypt it by changing the invocation of `gpg` suggest to me that this is a bug in GPG. It may be something that we can avoid triggering by changing something about how we encode/encrypt archives in SecureDrop, but I would need a reproducible test case (original file along with hard-to-decrypt output from SecureDrop) in order to test this.

**Comment by smonika** [comment]
Hello Can you please let me know how you solve the problem zlib inflate problem gpg --decrypt
Really appreciate your help

**Comment by freddymartinez9** [comment]
@smonika I solved it based on my comment from April 23rd. Did that not work for you?

**Comment by smonika** [comment]
Thanks Fred for the quick response tried gpg —decrypt <  filename.txt.pgp > filename.txt but got the same inflate error

**Comment by smonika** [comment]
Hello Fred ,Just want to check if  any other command prior to gpg —decrypt < filename.txt.pgp > filename.txt 
Thanks for your time

**Comment by conorsch** [comment]
@freddymartinez9 @smonika We're still interested in more data to reproduce this problem. To be clear, we do **NOT** want actual submissions from a production instance. But any info you can provide about characteristics of a submission that would allow us to recreate, e.g. filesize, nested directories, precompressed on a certain platform, etc., would be very useful to us.

**Comment by smonika** [comment]
File size is 2.5 GB 
It is not nested 
precompressed used zlib

**Comment by garrettr** [comment]
To expand on @conorsch's comment: if possible, a reproducible test case would be ideal. That is, we need a file that, when upload to SecureDrop through the Source Interface, then downloaded through the Journalist Interface, consistently exhibits this issue. Again, **please do not** send us a submission from an anonymous source who's used a SecureDrop under your control. If you can create a test case yourself, possibly based on characteristics inferred from the file you are witnessing, that would be the most helpful thing for us to debug the issue.

**Comment by smonika** [comment]
Thanks so much for all your help client sent the file again and now it is working fine 
Regards
Monika

**Comment by conorsch** [comment]
> File size is 2.5 GB  

@smonika That shouldn't work—SecureDrop limits uploads to 500MB. Anything above that limit will show a "Connection reset" message shortly after submitting.

> Thanks so much for all your help client sent the file again and now it is working fine 

Glad to hear it's working for you now. Don't hesitate to reach out if we can provide further assistance.

**Comment by redshiftzero** [comment]
Alright I am going to close this one. Happy to re-open at a later date if someone can provide a reproducible test case that **does NOT include any submissions from a live SecureDrop instance**.
