### ISSUE TITLE
Replace use of gzip/zlib with lzma

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1282]
From `store.py`:

``` py
# We store file submissions in a .gz file for two reasons:
#
# 1. Downloading large files over Tor is very slow. If we can
# compress the file, we can speed up future downloads.
#
# 2. We want to record the original filename because it might be
# useful, either for context about the content of the submission
# or for figuring out which application should be used to open
# it. However, we'd like to encrypt that info and have the
# decrypted file automatically have the name of the original
# file. Given various usability constraints in GPG and Tails, this
# is the most user-friendly way we have found to do this.
```

The use of gzip/zlib is not particularly important, and we could achieve better compression ratio and speed by switching to lzma. The one holdup for making this transition is that the lzma module requires Python 3. In the future, we may upgrade to Python 3, and at that point it makes sense to switch to lzma.

**Comment by kaizensoze** [comment]
There's always pylzma (https://pypi.python.org/pypi/pylzma) if you don't want to wait to upgrade to Python 3.

**Comment by garrettr** [comment]
This is a minor improvement to an ugly hack. Lowest possible priority on resolving this. I think it would be better to rethink the storage layer so we can encrypt submission metadata (like the original filename) without resorting to hacks like this. This would be eminently doable if we wrote a better client for the document interface, like we have been discussing recently.

**Comment by fowlslegs** [comment]
I don't think we're ever going to upgrade to Python 3. Would be too much work considering we're going to be rearchitecting SD in the near future. Also, we're trying not to add any more 3rd-party Python package dependencies. This said, I'm closing this issue.
