### ISSUE TITLE
Refactor install.sh script for Tails configuration

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1308]
The `tails_files/install.sh` script is designed to be run after initial installation on both the Admin Workstation and the Journalist Workstation. The script handles configuring the ATHS values in the system torrc file so that the Document Interface is accessible, and for the Admin Workstation, the servers are reachable over SSH.

The strategy used to handle the ATHS configuration has changed over the past year or so, due to both upstream changes and less-than-durable implementations on our part, and the deprecated solutions must be cleaned up by subsequent versions of the script to provide a path for ensuring system state on the Admin and Journalist Workstations.

Previously we've considered `install.sh` to be a "run-once" script, that will handle initial configuration and that's it. Because we're preparing to clean up several legacy issues (e.g. #1285), we'll need to instruct Admins to run the script again—and therefore the script must be largely idempotent.

The following changes must be accommodated for in the script:

* [x] #1182 
* [x] #1198 
* [x] #1206 
* [x] #1277 
* [x] #1285 
* [x] #1287 
* [x] #1292 

In so far it is as possible, the script on second-run should not prompt for information that's already determinable. For instance, rather than interactively prompting for ATHS info for the Document Interface on the Journalist Workstation, the script should inspect common locations for that information (e.g. `/etc/tor/torrc`) and reuse it if found.

As general cleanup, the following wish-list would greatly improve maintainability for the script:

* [x] organize the disparate logic into small reusable functions
* [x] avoid using all-caps var names at the global level, to avoid clobbering env vars
* [x] use bracket-notation when interpolating vars in strings
* [x] liberal comments throughout explaining rational of each piece

Long-term, we need to rethink the use of Bash at all. In certain context of SecureDrop, we can leverage Ansible to help achieve idempotence, but that only works on the servers. For the workstations, a more durable solution than Bash is warranted.

**Comment by conorsch** [comment]
Resolved by #1309 and #1318.

**Comment by ageis** [comment]
Don't know where else to put this, but I was talking to somebody and they told me there is an automated testing framework for Bash. It's called [Bats](https://github.com/sstephenson/bats). If you were interested in having a test suite/case for this script.

**Comment by fowlslegs** [comment]
Thanks for the tip @ageis. I'm going to actually open up a new issue for that because the bash scripts we use are obvious really important to successful deployment/ instance management and have not been historically as trusty as we would like.

**Comment by conorsch** [comment]
Cross-linking discussion of testing bash scripts for posterity: https://github.com/freedomofpress/securedrop/issues/1366
