### ISSUE TITLE
Consider using include statements to DRY out docs

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1319]
In the upgrade docs for each release, we instruct Admins to pull down the latest release via git, verify the GPG signature on the tag, then checkout out the release branch and proceed with any manual intervention required by the release.

Now that we're using ReadTheDocs (since #1158), we can create a snippet of text to be included dynamically in multiple documents. Think "macro", but without nightmares. Here are some examples of repetitious docs:
- https://docs.securedrop.org/en/latest/set_up_admin_tails.html#verify-the-release-tag
- https://docs.securedrop.org/en/latest/upgrade/0.3.x-to-0.3.5.html#upgrade-procedure
- https://docs.securedrop.org/en/latest/upgrade/0.3.5-to-0.3.6.html#upgrade-procedure
- (pending release 0.3.7)

Repetition is soggy—let's _DRY it out!_ :sunglasses:

We didn't implement a reusable snippet for the 0.3.7 release, but we _did_ reconcile develop docs with master, so we're in a good position to start doing reusing snippets starting in 0.3.8. The tag verification workflow is the most obvious example of redundancy in the docs, but there may be others. Let's track any additional candidates in this issue as well.

**Comment by zmanian** [comment]
I started looking at this but I haven't been able to find any documentation on reusable text snippets in ReStructuredText/ReadTheDocs files. It would be helpful if someone could point at what feature is intended to be used.

**Comment by redshiftzero** [comment]
Sure! Check out [this blog](http://tychoish.com/posts/large-sphinx-deployments/) under "Single Source Content" regarding reStructuredText's `include` directive

**Comment by conorsch** [comment]
Originally recorded in #1208, I'm moving the following examples for places in the docs to use include statements over here:

### Consider using `include` statements to DRY out docs
- [ ] ssh connectivity test:
  - [ ] `servers.rst`
  - [ ] `test_the_installation.rst`
  - [ ] `upgrade_to_tails_2x.rst`
- [ ] ansible-playbook commands
  - [ ] `install.rst`
  - [ ] `backup_and_restore.rst`
  - [ ] `upgrade/0.3.5-to-0.3.6.rst`
  - [ ] `upgrade/0.3pre-to-0.3.x.rst`
  - [ ] `upgrade/0.3.x-to-0.3.5.rst`
- [ ] git clone tasks
  - [ ] `development/getting_started.rst`
  - [ ] `tails_guide.rst`
  - [ ] `set_up_admin_tails.rst`
  - [ ] `development/documentation_guidelines.rst`

**Comment by conorsch** [comment]
#2029 shows a good example of where DRY include statements in the docs would be useful: there we copied the same recommended list of commands in two different documents, rather than using a snippet.

**Comment by conorsch** [comment]
See also #2066.

**Comment by redshiftzero** [comment]
See #2139 for an example of using the `include` directive.

**Comment by zenmonkeykstop** [comment]
Recent experiences with new admins would seem to indicate that this would also be useful in places like `onboarding.rst`, to allow for complete instructions on a single page without repetiion (currently the doc in question throws to another page for Git instructions, and it doesn't make for a good flow). I'm going to grab this one for further investigation.

**Comment by eloquence** [comment]
This has become standard practice in work on our docs; specific portions that need to be DRY'd can be filed as separate issues.
