### ISSUE TITLE
Update Deployment Best Practices Recommendation

### ISSUE THREAD

**Issue by jmhale** [freedomofpress/securedrop#1337]
Should make the Washington Post "Whole Site" recommendation more generalized.

https://github.com/freedomofpress/securedrop/blob/develop/docs/deployment_practices.rst#whole-site-changes

The example of using `ssl.washingtonpost.com` is no longer applicable, since that domain just redirects to www now, which is being served entirely over HTTPS.

**Comment by garrettr** [comment]
Dang, you beat me to the punch on filing #1337! 😆
