### ISSUE TITLE
Move diceware wordlist into `dictionaries` directory

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1339]
Bug  #1328 is that `config.py` can't be updated without risking breaking deployments. However, since it's not updated in the git repo, we can't change the value that sets the location of the wordlist. This is a tracking issue to move the wordlist from `securedrop/wordlist` to `securedrop/dictionaries/diceware.txt`

This was temporarily fixed by #1334, but needs to be addressed when the configuration and deployment of SD is cleaned up.

**Comment by dachary** [comment]
Implemented in https://github.com/freedomofpress/securedrop/pull/2344

**Comment by redshiftzero** [comment]
Closing due to merge of #2344
