### ISSUE TITLE
Upgrade Python Dependencies for 0.3.9

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1352]
Our Python dependencies are in need of an update. See https://requires.io/github/freedomofpress/securedrop/requirements/?tag=0.3.8.

In terms of the app code, upgrades to `psutil` and `qrcode` should in general not be security critical because of how we've used them. The one function in `werkzeug` we call directly has not changed, but Flask uses much more of the package. Flask should stay on top of changes with `werkzeug`, but that's what testing is for (validation). There was also nothing security-related that would affect us in the Flask changelog.

So at this time there is nothing critical to worry about, it's just good to stay up-to-date, especially because our test suite is failing, presumably due to our out-of-date selenium no longer supporting the latest Firefox.

* For `flask` the following changes looked relevant:
    * Templates are no longer automatically reloaded outside of debug mode. This can be configured with the new TEMPLATES_AUTO_RELOAD config key.
    * Added :command:`flask` and the flask.cli module to start the local debug server through the click CLI system. This is recommended over the old flask.run() method as it works faster and more reliable due to a different design and also replaces Flask-Script.
    * Flask will now log by default even if debug is disabled. The log format is now hardcoded but the default log handling can be disabled through the LOGGER_HANDLER_POLICY configuration key.
    * flask.ext is now deprecated (pull request #1484).
* This change looks really important in `qrcode` :wink::
    * Avoid unnecessary dependency for non MS platforms, thanks to Noah Vesely.
        *...Not really, though; `pip compile` will take care of removing it for us.
* Upgrading `selenium` should fix https://github.com/freedomofpress/securedrop/issues/1351.
* Only very minor fixes in `pytest`, so again that shouldn't affect anything.
* `pbr` is a sub-dependency (of `mock`) and I don't see a changelog for it.

**Comment by garrettr** [comment]
> the changes to Werkzeug are in code we don't use (in fact, we only use one small, fully-independent function from Werkzeug that I believe we should just copy and hardcode into the SD source to simplify our dependencies, which I believe are too many)

@fowlslegs Flask depends on Werkzeug. It is not a minor dependency.

**Comment by fowlslegs** [comment]
I forgot, yes. Edited.

**Comment by ageis** [comment]
@fowlslegs @garrettr For Python dependency chain monitoring, it might be worth checking out https://requires.io/ or https://dependencyci.com/ or https://gemnasium.com/ They integrate with GitHub, do take a close look at the OAuth permissions though.

**Comment by fowlslegs** [comment]
I have been using the requires.io web interface, but did not realize it can integrate with your project as well.

>You will be asked for write permissions: this is so that we can setup web hooks to keep track of your project updates, but also to push pull-requests if you opt-in for this feature.

**Comment by garrettr** [comment]
Unless there have been security updates to Python dependencies since the initial review in the top comment, this is fairly low priority and may not be necessary for 0.3.9.

At the moment, the largest benefit appears to be that it would resolve #1351.

**Comment by garrettr** [comment]
Resolved in #1379.
