### ISSUE TITLE
Download submissions from the Sources view

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1354]
A SecureDrop user has requested that we make it possible to download submissions from the initial "Sources" view of the Document Interface. They say they would like to be able to:

> download messages straight from the main window instead of having to click through to each source - so could click several new submissions from several sources and 'download all' in one go, for example.

**Comment by mdrose** [comment]
So are they just looking to be able to download all new submissions from multiple selected sources? Maybe just add a "Download selected unread" button?

**Comment by pwplus** [comment]
I could look into updating my old PR.

**Comment by fowlslegs** [comment]
@ajvb is working on this one for the Hackathon.

**Comment by ajvb** [comment]
Working on updating https://github.com/freedomofpress/securedrop/pull/1181 and finishing out the tests.

**Comment by redshiftzero** [comment]
Implemented in #1467
