### ISSUE TITLE
Make HTML/CSS responsive

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1357]
Currently many of the elements have fixed sizes (in pixels). This led to some ugly and poorly sized containers for the German translations in #1103 because of long words. It would probably look equally bad with very short words as in Chinese.

Before piling on more features, it might make sense to refactor the HTML/CSS (or hopefully SASS #1349) to support containers that resize depending on content size (as well as possibly monitor size). As I'm not usually a frontend dev, I'd roll it all by hand and skip a framework.

Currently there are a lot of features that require front changes, so it would be good to make this change before starting any of the others:  #1356, #1355, #1354, #1353,  #1171, #1170, (plus a nasty rebase of #1103)

**Comment by heartsucker** [comment]
I can help with this, but it would be helpful if someone could merge #1349 first. We already have ugliness with the new wordlist because of the longer words.

![screenshot - 11102016 - 11 10 43 am](https://cloud.githubusercontent.com/assets/3998464/20172717/8a70ef36-a736-11e6-983b-3b608846781e.png)

**Comment by conorsch** [comment]
Sorry about the holdup on #1349, @heartsucker—those changes are in `develop` now, so have at it!

**Comment by heartsucker** [comment]
@conorsch No worries. I'm probably going to hold off on this since it looks like @ninavizz has some more major changes to the UI in the pipe, and any changes I make might conflict with that.

Also related: https://github.com/freedomofpress/securedrop/issues/1450

**Comment by heartsucker** [comment]
Work tracked in branch [`responsive-css`](https://github.com/freedomofpress/securedrop/tree/responsive-css).

**Comment by kushaldas** [comment]
@SaptakS please have a look :)

**Comment by SaptakS** [comment]
@kushaldas sure. I will try to contribute and make the pages more responsive in case they aren't. Thanks. 😃

**Comment by SaptakS** [comment]
There is one more thing that I wanted to ask. Apart from changing the fixed sizes (in pixels) to maybe percentage or `vw/vh`, one more thing that we often see is though things resize like they should with screen size, somethings appear better when done differently in mobile. 

Say, for example, in the /generate page, in wide screen, the differently sized buttons look good, but in narrower screens it looks weird:

### Wide Screen:
![screen shot 2018-01-04 at 6 12 49 pm](https://user-images.githubusercontent.com/9530293/34563985-fc704b74-f17a-11e7-81bb-00950ecf1bb9.png)

### Narrow Screen:
![screen shot 2018-01-04 at 6 13 06 pm](https://user-images.githubusercontent.com/9530293/34564364-669e33a2-f17c-11e7-8ad6-5d93c379dce3.png)

**Comment by dachary** [comment]
@SaptakS note that for this specific page we removed the **USE EXISTING CODENAME** button so this won't be an issue anymore.

**Comment by good-lly** [comment]
what is the progress, any update? I could help ...

**Comment by eloquence** [comment]
As the above comments and PRs show, a lot of work has been done on this since the issue was filed, and both JI and SI should render responsively. Additional improvements, e.g., to table rendering, can be filed as separate issues.
