### ISSUE TITLE
Consider EFF's new wordlist

### ISSUE THREAD

**Issue by byeskille** [freedomofpress/securedrop#1361]
EFF has recently published a new and improved diceware wordlist
https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases

This list might be considered for SecureDrop as it has fewer rare words, and have used data relating to how many people understand the word to select words.

**Comment by heartsucker** [comment]
@byeskille SD was just updated to a similar and longer list: https://github.com/heartsucker/diceware/blob/develop/wordlists/en_US/wordlist-8192.txt

You can find it in the `develop` branch.

**Comment by fowlslegs** [comment]
I'm actually _very_ much in favor of switching to the EFF list. If you read that blog post it's pretty impressive how much research went into that list. While it's about 500 words fewer, it seems they really chose them carefully:

> We based our list off of data collected by Ghent University's Center for Reading Research. The Ghent team has long studied word recognition; you can participate yourself in their online quiz to measure your English vocabulary. This list gives us a good idea of which words are most likely to be familiar to English speakers and eliminates most of the unusual words in the original Diceware list. This data also includes "concreteness" ratings for each words, from very concrete words (such as screwdriver) to very abstract words (such as love).

> We took all words between 3 and 9 characters from the list, prioritizing the most recognized words and then the most concrete words. We manually checked and attempted to remove as many profane, insulting, sensitive, or emotionally-charged words as possible, and also filtered based on several public lists of vulgar English words (for example this one published by Luis von Ahn). We further removed words which are difficult to spell as well as homophones (which might be confused during recall). We also ensured that no word is an exact prefix of any other word.

**Comment by redshiftzero** [comment]
Implemented by @commandnotfound in PR #1452
