### ISSUE TITLE
Write test suite for our bash scripts

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1366]
We rely on a number of bash scripts for development, deployment, package configuration, and admin maintenance. As of now, we don't have any sort of test suite for these scripts. Historically some of these scripts have not been as robust and trusty as we would like. Something I've seen recommend by @ageis and elsewhere is https://github.com/sstephenson/bats. We might want to look into alternatives as well. Creating a test suite for our bash scripts would help us ensure that changes to them do not break new or existing SD deployments/instances.

**Comment by garrettr** [comment]
In general, I would prefer for us to move away from using bash scripts as much as possible. Bash is simply an awful scripting language. Rather than invest resources in writing tests for bash scripts, I would generally prefer to rewrite them in Python wherever possible (following [Tails' example](https://tails.boum.org/blueprint/Port_shell_scripts_to_Python/)).

**Comment by fowlslegs** [comment]
100% agree @garrettr. On the note of investing resources wisely, we should probably wait to see how the deployment story changes with the rearchitecture before spending time re-writing our current bash scripts in Python.

**Comment by conorsch** [comment]
The more relevant problem here is general lack of testing for the Tails environment overall. The virtualized environments for working on SecureDrop omit Tails representation altogether, requiring manual testing on hardware as part of the release process. Virtualizing a Tails environment and forcing Admin interaction in a GUI VM may be worthwhile to help catch issues with the Tails config.

>I would prefer for us to move away from using bash scripts as much as possible

Truth. In particular it's frustrating to have Ansible for enforcing state on the SecureDrop servers, but not for configuring the Journalist Workstation. (Although we can assume Ansible is installed on the Admin Workstation, Journalists don't have it, so none of the configuration scripts use Ansible for setting up Tails.) We're going against the grain with Tails by overloading the persistence functionality to rewrite system-wide configs, so it shouldn't come as a surprise that we're getting bitten by oversights in the run-once scripts such as `tails_files/install.sh` (e.g. #1394).
