### ISSUE TITLE
Release SecureDrop 0.3.9

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1380]
This is a tracking issue for the final tasks involved in releasing SecureDrop 0.3.9. We'll use a checklist in this top comment to track the remaining work - note that it may change over time, as new items are added, removed, or split into subtasks.

# Finish release candidate (0.3.9-rc1)
- [x] Merge open pull requests from 0.3.9 milestone - @fowlslegs
- [x] Build test debs - @conorsch 
- [x] Stand up test apt server with 0.3.9-rc1 packages - @conorsch 

## Test 0.3.9-rc1
- [x] Unit tests pass on 0.3.9-rc1 staging VM - @fowlslegs
- [x] Interactive testing produces nothing funky in the logs in staging VM - @fowlslegs

# Install blocking bug forces 0.3.9-rc2
## Fixing the problem
- [x] Create a PR to fix #1394 - @conorsch
- [x] Merge @conorsch's PR after review - @fowlslegs 
- [x] Full review of the `securedrop/install.sh` script - @fowlslegs

# Make release candidate 0.3.9-rc2
- [x] Add fix to #1394 to the changelog - @fowlslegs
- [x] Upgrade version in `release/0.3.9` branch to 0.3.9-rc2 - @fowlslegs

# Test 0.3.9-rc2
- [x] Test upgrade from 0.3.8 works correctly on staging VM - @fowlslegs
- [x] Unit tests pass on 0.3.9-rc2 staging VM - @fowlslegs
- [x] Interactive testing produces produce nothing strange in logs in staging VM - @fowlslegs
- [x] Build and upload 0.3.9-rc2 debs to the test apt server - @conorsch 
- [x] Test upgrade from 0.3.8 works on prod w/ test repo debs - @conorsch 
- [x] Test install (not upgrade) of 0.3.9 works on prod w/ test repo debs - @conorsch 
- [x] Test from-scratch hardware install - @msheiny

# Release
- [x] Build final Debian packages for 0.3.9 - @garrettr 
- [x] Release 0.3.9 - @conorsch 
- [x] Publish blog post about 0.3.9 Debian package release - @garrettr 

# Post-release
- [x] Merge release changes into development branch @garrettr

**Comment by conorsch** [comment]
Testing packages are up: https://apt-test.freedom.press/ 

In order to test, you'll need to update both the apt repo URL and [GPG key](https://gist.github.com/conorsch/9a436df37aabb82efdd93b447c60ed70) in the Ansible config, from the offline master signing key. Apply [this patch](https://gist.github.com/conorsch/0121f4d045939c2f6d9a8ce6554b7257) to the `release/0.3.9` branch to incorporate the changes, then run a clean build of staging or prod.

**Comment by fowlslegs** [comment]
Looks like we're going to have to make a https://github.com/freedomofpress/securedrop/issues/1394. I've updated the task list to reflect this. Let's discuss how we want to test the fix to #1394 as well.

**Comment by fowlslegs** [comment]
I went ahead and merged #1397, but am about to do a full review of the current state of `securedrop/install.sh` to look for any other bugs that may have made it in with the rewrite (or were there before). Since we don't have a test suite or environment for this, it might be wise to try to try to test this on hardware, but that's also quite time consuming.

An idea I just had is that it might be a good idea to put manual/ hardware testing of the install aside until Mike gets here. Then his first couple of days (9/6-9/7) here can be doing the SD install that he was going to do anyway, but instead of 0.3.8, he can test on 0.3.9-rc2. In the meantime, we can complete all other testing for 0.3.9-rc2. This syncs up with when Garrett will get back, so provided everything goes well during Mike's install, we'll be able to cut this release on 9/8. It will also be helpful for Mike to see how the release process works.

**Comment by justintroutman** [comment]
I particularly like this idea because Mike is/will be remote -- the more intimate he becomes with the installation process, the better. Also, this will be a timely second run for me as I continue editing the SD docs.

**Comment by fowlslegs** [comment]
There were some vulnerabilities in `pyotp` and `Werkzeug` that have been found and fixed in newer releases since 0.3.9-rc1, so I'm doing some evaluation of the changes, but will most likely include a PR to update them before 0.3.9-rc2.

**Comment by fowlslegs** [comment]
Just an update on this--I just merged 0.3.9-rc2. Also, yesterday @justintroutman, @conorsch, and I had a meeting and decided to go ahead with having Mike do a from-scratch hardware install of 0.3.9-rc2 when he gets here. It's also important that he gets to see how the release process works, so we'll need to get to that before he leaves. Monday the 5th is labor day, if he works T-W and gets the install done we could release on Th  the 8th. If Mikes install takes longer or starts later or Th is not good, we shouldn't do a release on a Friday, so we'll wait for M the 12th or T the 13th. Mike leaves on the 14th.

**Comment by fowlslegs** [comment]
I'll have my remaining tasks finished by EOD tomorrow. @conorsch you should try to do the same so everything can be ready for @msheiny to start on the hw install by Th. @msheiny, the only modifications you should need to do to the standard install are:

(i) Checkout the `release/0.3.9` branch instead of the `0.3.8` tag (so you'll have to skip the signature verification as well since you can't sign a branch).
(ii) Apply the patch @conorsch posted above, so that you pull from the test apt repos where the `0.3.9-rc2` packages are, instead of the production repos that contain `0.3.9`.

**Comment by fowlslegs** [comment]
Let me know if I'm missing anything there @conorsch ^.

**Comment by fowlslegs** [comment]
Provided @msheiny starts on Th, and nothing goes catastrophically wrong, he should be finished on Friday or Monday. This will set things up for a Tueday, Sep 13 release, the day before @msheiny leaves, which is perfect because as noted we want familiarize him in person with the release process.

**Comment by conorsch** [comment]
@fowlslegs The custom patch process you describe for testing the rc is spot-on. We'll follow that procedure when running the pre-release hardware install in the coming days.
