### ISSUE TITLE
Proposal: Change all references of "Document Interface" to "Journalist Interface" to be consistend with code

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1384]
Document interface is ambiguous because it could mean the source interface because sources submit documents, or it could mean the the journalist interface because the journalist reads documents.

I think this is entirely a documentation issue (plus one of two lines in some `bash` script), and doesn't impact sources in any way.

**Comment by fowlslegs** [comment]
In favor.
