### ISSUE TITLE
Double submission of journalist replies

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1392]
I can't reproduce this, but when replying to a source, clicking the submit button sent two replies. When returning to the conversation page, there were two flash messages saying that my reply was went and two entries for my reply in the list. I confirmed that the `db.sqlite` has two entries.

**Comment by fowlslegs** [comment]
Going to close this one since we haven't seen it in 7 months. Re-open please if you can ever reproduce or it crops up for anyone else who sees this.
