### ISSUE TITLE
Include redmine.freedom.press as altname

### ISSUE THREAD

**Issue by KwadroNaut** [freedomofpress/securedrop#1401]
Currently redmine.freedom.press is an alias for support.freedom.press, but the cert being served doesn't include that as an altname, resulting in certificate warnings. Could be removed from DNS or the altname put in the next renewal of the certificate.

**Comment by conorsch** [comment]
Thanks for reporting this. I've removed the CNAME. The redmine.freedom.press URL isn't referenced anywhere in the [support documentation](http://securedrop-support.readthedocs.io/en/latest/), so no need to maintain it.
