### ISSUE TITLE
Update securedrop.org/faq#audits with fourth audit

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#1407]
The securedrop.org FAQ lists the first three audits, but does not mention the audit that was done in 2015. Please update the page; it's a good resource to link to when explaining to folks that yes, the system is regularly audited by independent experts.

**Comment by conorsch** [comment]
@runasand Thanks for pointing that out—I've updated the [Audits Section of the FAQ](https://securedrop.org/faq#audits) to include the newest report.
