### ISSUE TITLE
[Edited: redacted for privacy]

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#1408]
[Edited: redacted for privacy]

**Comment by garrettr** [comment]
I just tested their Source Interface at the .onion address you provided and was able to create an account and make a submission without any issues. There do not appear to be any issues with their SecureDrop installation.

Note that "the proxy server is refusing connections" suggests that there is an issue with your local proxy server. Are you using [Tor Browser](https://www.torproject.org/projects/torbrowser.html.en)? If you are, you should check to make sure that it was able to successfuly connect to the Tor network.

If you are not using Tor Browser, I strongly encourage you to do so.

Finally, if you are a potential source, please be careful when using public channels such as GitHub to discuss your activity. We cannot help you if you expose yourself in this manner. As a general rule do not encourage sources to discuss details of their activity on any public forum, including GitHub.

**Comment by Carjoy1969** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Thanks - I agree and realized my error as soon as I posted. Is there any way to delete the post?





On Tuesday, September 20, 2016, 3:19 PM, Garrett Robinson <notifications@github.com> wrote:


I just tested their Source Interface at the .onion address you provided and was able to create an account and make a submission without any issues. There do not appear to be any issues with their SecureDrop installation.

Note that "the proxy server is refusing connections" suggests that there is an issue with your local proxy server. Are you using Tor Browser? If you are, you should check to make sure that it was able to successfuly connect to the Tor network.

If you are not using Tor Browser, I strongly encourage you to do so.

Finally, if you are a potential source, please be careful when using public channels such as GitHub to discuss your activity. We cannot help you if you expose yourself in this manner. As a general rule do not encourage sources to discuss details of their activity on any public forum, including GitHub.

**Comment by garrettr** [comment]
As far as I know, GitHub does not allow issues to be deleted. I can, however, delete the content of your comments, which I will now do.

**Comment by garrettr** [comment]
I deleted everything I could delete (comments after the original issue comment, which cannot be deleted) and redacted the rest.
