### ISSUE TITLE
Internal server error while submitting

### ISSUE THREAD

**Issue by mmohsen** [freedomofpress/securedrop#141]
I have SecureDrop installed on three, freshly installed Ubuntu 12.0.4.3 64-Bit. I installed it according to the instructions step by step. When I tested submitting a few lines, I get a plain "internal server error" response from the page `***********.onion/lookup/`

**Comment by garrettr** [comment]
There was never a reply from @mmohsen and this issue refers to a very outdated version of SecureDrop.
