### ISSUE TITLE
Update landing page guide on readthedocs

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1410]
FPF has a security guide / checklist for an organization's SecureDrop landing page. This should be committed and should go into readthedocs. 

Also: a note about the implications of using CloudFlare on an organization's landing page should be added.

**Comment by garrettr** [comment]
There is some documentation about landing page best practices already in Read the Docs: https://docs.securedrop.org/en/stable/deployment_practices.html#landing-page. However, it should be reviewed as it could use some updates.

> Also: a note about the implications of using CloudFlare on an organization's landing page should be added.

👍

**Comment by ageis** [comment]
Not just CloudFlare, but Akamai, StackPath, Incapsula, Amazon CloudFront, etc.
