### ISSUE TITLE
Remove extra test wrapper

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1412]
Get rid of `test.sh` that is used to run the functional tests

**Comment by fowlslegs** [comment]
Working on this... have a question:

* There's no reason not to merge `test_{unit_journalist,journalist,_single_start}.py` into a single file, right? They are all `unittest.TestCase` objects testing the journalist module--I'd combine the imports, but they'd each stay their own class.

@garrettr

**Comment by fowlslegs** [comment]
Pending PR is https://github.com/freedomofpress/securedrop/pull/1527.
