### ISSUE TITLE
Turn off Ansible deprecation warnings or update to new syntax

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1427]
Running the development playbook (all playbooks actually) spits out a whole bunch of deprecated syntax warnings. While Ansible 1.X still cooperates with this deprecated syntax, it would be better to update all the roles to Ansible 2. In the meantime, how do you feel about setting `deprecation_warnings=False` in `ansible.cfg`?

**Comment by conorsch** [comment]
See discussion in #1146. Updating the version of Ansible running on the Admin Workstations is non-trivial.

**Comment by redshiftzero** [comment]
I'm closing this since we have #1146 coming down the pipe for SecureDrop 0.4

**Comment by dkarapanos** [comment]
- vim /etc/ansible/ansible.cfg
Line 180

- Change 
`#deprecation_warnings = True`
to
`deprecation_warnings = False`
