### ISSUE TITLE
Secure drop attempting unexplained connections

### ISSUE THREAD

**Issue by TOZALI** [freedomofpress/securedrop#1431]
Our installation of secure drop seems to be making a call to two unusual IPs. The firewall has picked it up and dropped it. Is there any reason why the secure drop server would need to contact the following IPs:

173.194.204.108 - Google
208.82.41.1 - Pulaski Electric System

OSSEC ALERT
Oct 24 04:11:23 mon kernel: [1380542.213056] Denied_TCP IN= OUT=em1 SRC=x.x.x.x DST=173.194.204.108 LEN=52 TOS=0x00 PREC=0x00 TTL=64 ID=9082 DF PROTO=TCP SPT=59038 DPT=80 WINDOW=304 RES=0x00 ACK URGP=0 OPT (0101080A148CF9BA8E0D5E95) 
Oct 24 04:11:23 mon kernel: [1380542.213056] Denied_TCP IN= OUT=em1 SRC=x.x.x.x DST=208.82.41.1 LEN=52 TOS=0x00 PREC=0x00 TTL=64 ID=9082 DF PROTO=TCP SPT=59038 DPT=80 WINDOW=304 RES=0x00 ACK URGP=0 OPT (0101080A148CF9BA8E0D5E95) 

Thank you.

**Comment by conorsch** [comment]
@TOZALI

Thanks for contacting us. You may have a misconfiguration in your vars or firewall setup, but it's hard to say more with the information provided so far. Please open ticket via our support portal, so we can discuss specifics about your instance privately. You'll need to register for the support portal if you haven't already—[instructions here](http://securedrop-support.readthedocs.io/en/latest/).

**Comment by redshiftzero** [comment]
Any further discussion of this issue can occur on the support portal. Closing!
