### ISSUE TITLE
Allow sources to provide GPG public keys

### ISSUE THREAD

**Issue by Hainish** [freedomofpress/securedrop#144]
We should allow the sources to provide their own GPG public keys for replies, rather than having them generated.  This way, a savvy source could be assured that replies were sent directly to them, decryptable using a secret key only they possess, rather than one that is stored on the source server and they supply with their codename.

If a source provides a public key, we should not generate a keypair for them.  We've been toying with how to deal with the possibility of entropy depletion in https://github.com/freedomofpress/securedrop/issues/140.  This is not meant to deal with that issue, but could provide a solution to it in the unlikely event that we decide to exclusively have sources provide their keys and not have it generated on the server.

**Comment by garrettr** [comment]
If this is ever implemented, we should hide the recipients as suggested in #13. See https://github.com/freedomofpress/securedrop/issues/13#issuecomment-86202424 for context.

**Comment by fowlslegs** [comment]
> An uploaded public key would have its own uid that would not fit this scheme. It would also potentially have privacy problems (what if a user picking a pseudonym they had used elsewhere, or just used their regular GPG key?)

> Adding a new uid to fit our existing scheme is actually impossible, since uid's need to be signed by the corresponding private key. 

The only way to ensure a source doesn't do this is to generate a keypair for them to download with a uid like "test" to try to mask the possibility this is a SD correspondence key. The private key can be removed from the server as soon as a successful download happens. This requires we TOFU the server, but we're already doing this when we download the SVS public key (I didn't actually think about that before--that's something that could be made better if we provided SVS fingerprints on our landing pages and directory).

... Actually, we could avoid the TOFU problem and possible entropy worries of generating keys by asking sources to create a new GPG key with the uid "test." On upload, the server confirms this is the uid in memory, and saves/deletes it if it is/isn't.

**Comment by eloquence** [comment]
We should IMO only do this in a manner that is accessible to users not comfortable manually using `gpg` (along the lines of the ideas for end-to-end encryption of source submissions discussed in #92), or the value is going to be marginal with high maintenance effort.

**Comment by eloquence** [comment]
(Closing this issue because we're unlikely to implement this as-described.)
