### ISSUE TITLE
Flask Testing uses one request context per TestCase method

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1444]
In normal usage, each request object is processed in it's own request context. In Flask Testing all request objects are processed in a single request context for a given TestCase method. If you're only making a single request in a test method, everything will work as expected. However, if you want to test anything more complicated (i.e., anything that involves multiple users or multiple requests from a single users), all bets are off. To illustrate the problem, I've uploaded a Gist that illustrates the problem with a very simple example, and a little further explanation in the comments: https://gist.github.com/nvesely/b6e72ae0902c97723fcf44b46160d499.

Edit: link surgery.

**Comment by fowlslegs** [comment]
I started writing a subclass of `flask_testing.TestCase` that will reset the context before any request. That way the context will be preserved after a request (until the next one) in order to take advantage of the context assertion methods and other conveniences provided by Flask Testing, while still resolving this issue.

**Comment by fowlslegs** [comment]
I made more progress on this over the weekend, but I totally screwed with my use of git and deleted that work in an unrecoverable manner :sob:

**Comment by heartsucker** [comment]
Would just like to point out that this is biting me in the ass right now and we should fix it. :(

**Comment by heartsucker** [comment]
Pointing out that this one got me again while writing tests for session expiration.

**Comment by heartsucker** [comment]
Pointing out that this is still a problem 😐 😐 😐

**Comment by legoktm** [comment]
Use of flask-testing was removed in https://github.com/freedomofpress/securedrop/pull/2948 and finally in 65f092ce1c2ce364d3d11ff54931a7ef28721819.
