### ISSUE TITLE
Recommend backing up SVS and Admin Tails sticks

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1446]
Within a week of setting of SecureDrop for the first time, my brand new Tails USB stick crapped out on me an I was unable to recover the application GPG key. To prevent lock outs from the app/mon servers, and to prevent the permanent loss of access to the encrypted documents, both the Admin and SVS USB sticks should have a dedicated USB back up.

To fix this, the install docs should recommend
- backing up the home directory of the SVS immediately after generating the GPG keys
- backing up the home directory of the Admin immediately after SD installation
- labeling the two backup USB sticks to avoid plugging the SVS back up into a non-airgapped device

**Comment by conorsch** [comment]
Ouch, sorry to hear that. Yes, the docs should do a much better job of prepping Admins for disaster recovery. Tagging a few related/duplicate issues:

* #1127 
* #1128 
* #1091 
* #606 

As you can see, this particular shortcoming of the docs has been a problem for a while. =/
