### ISSUE TITLE
Add documentation for journalists on how to strip metadata and redact documents

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1449]
Right now we provide little guidance about how to anonymize source materials on the SVS. It would be valuable to provide some more documentation on how to use MAT (or another tool?) to strip out metadata as well as on how to redact documents.

**Comment by fowlslegs** [comment]
Though there is no security benefit for this, it would be cool to add a section on how to use metadata to verify the authenticity of documents, or to gather other valuable information that might help build a story around something. The journalist must still keep in mind what they learn from this metadata may be compromising. E.g., it would be bad to include the date photos were taken in an article, even if that information might help you discover some other interesting contextual material. Keep in mind #1451.

**Comment by commandnotfound** [comment]
In what voice must this documentation be in? Should it be directed toward the journalist? Or to an administrator who would then instruct a journalist? At present, the journalist guide tends to lean toward the latter.

**Comment by conorsch** [comment]
@commandnotfound Preserve the existing third-person voice, since that's mutually applicable to both Admins (for use in future instruction) and Journalists (who are reading the guide themselves).

**Comment by KwadroNaut** [comment]
Keep in mind stuff like DSA-3708-1 as well: "did not remove metadata from images embededed in PDF
documents […] This update disables PDF support in MAT entirely." The Metadata Anonymisation Toolkit is installed on every SVS.

**Comment by fowlslegs** [comment]
X-linking https://github.com/freedomofpress/securedrop/issues/543

**Comment by eloquence** [comment]
Closing in favor of #2382.
