### ISSUE TITLE
Add journalist docs on using Tor to research SD submissions

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1451]
Currently, there are no explicit instructions on opsec when researching SecureDrop submissions. At minimum, journalists should always use Tor Browser on their work machines (not the Journalist Workstation) to research SecureDrop submissions. For extremely sensitive submissions research, it would be good to add instructions on using their Journalist Workstation to install another copy of Tails to a new USB.

**Comment by conorsch** [comment]
Good point. During on-site trainings, we discuss opsec surrounding submissions and research, but the docs don't currently reflect that. The SecureDrop docs may not be the best place for such documentation—it may be more appropriate to link out to general opsec training materials else—but as a near-term solution it's a great idea to add them. cc @harlo

**Comment by freddymartinez9** [comment]
Opened https://github.com/freedomofpress/securedrop/pull/1465
