### ISSUE TITLE
Provide a PDF of the documentation on the Journalist and Admin workstations

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1470]
I think this could be handy for journalists and admins. We'd make a desktop icon for it of course. The problem is it getting out of date, and us lacking an update mechanism.

**Comment by ajvb** [comment]
Could it be automated through the sphinx documentation using the LaTeX -> PDF generation? http://www.sphinx-doc.org/en/1.4.8/builders.html#sphinx.builders.latex.LaTeXBuilder

**Comment by fowlslegs** [comment]
Yeah, that's what I was thinking. Implementation should be easy, just want to consider whether it's okay these docs might get out of date, or whether we'd always rather have people fetch the latest via another device.

**Comment by ajvb** [comment]
That's a good question. I imagine FPF has some way to send out release notes / communicate with its users. Would a good MVP be to simply add it and notify users of big changes when they occur? Or is this too dangerous / easy to get wrong?

Sorry if my question seems silly, just have not idea what the communication looks like with the users/admins of the current installations.

**Comment by fowlslegs** [comment]
We do communicate with users via a number of channels, but the current process of setting up SD is kind of a PITA. We don't want to ask journos to clone our repo, verify the latest git tag with GPG, and run some script periodically. Normally, an admin sets up their Tails stick for them (and hopefully updates Tails regularly too--or the journo just does it themselves as there is a pretty friendly automatic update GUI in Tails). If we were to stick with Tails long-term I would say we should have a separate APT repo to provide client-side packages, but we're trying to move journos to the in-very-early-development, Qubes-based, combined-SVS-and-JW system made accessible through the reading room client. So I think it's wise to not focus much effort on the parts of the SD system subject to change in the coming year or two.

I think it's a good idea to include desktop PDF of the documentation, especially for journalists who might be less likely to seek it out on their own. We might be able to compile the PDF with a notice that informing the user that for the latest version of the docs they should visit https://docs.securedrop.org from their non-JW computer. However, now remembering that I've heard from some admins that most journos use a single machine for day-to-day work and their JW--this, IMO, makes an even better argument for why we should include it in Tails. As we add features to the journalist interface (we just renamed it from document interface btw), some of those might not be documented, but I don't think there's anything dangerous in old documentation.

**Comment by conorsch** [comment]
> The problem is it getting out of date, and us lacking an update mechanism.

These problems are severe enough that I think it's better to rely on docs.securedrop.org. Navigating the docs in a browser, even over Tor, is a more pleasant experience than opening a PDF.

**Comment by fowlslegs** [comment]
How about we ship the documentation in the securedrop-app-code package and serve it from each SD instance via the JI (basically the same suggestion @ninavizz made with regards to the SI)? This:

1. Avoids the problem of the documentation getting out of date.
2. Makes it possible to read documentation on the JI w/o connecting to any external sites (i.e., any site that's not your org's SD instance).

**Comment by redshiftzero** [comment]
Closing this in favor of #2131
