### ISSUE TITLE
Documentation and wipefs transfer device broken

### ISSUE THREAD

**Issue by KwadroNaut** [freedomofpress/securedrop#1479]
It only showed up after following exactly the documentation and not using the cli: Error wiping newly created partition /dev/sdc1: Command-line `wipefs -a "/dev/sdc1"' exited with non-zero exit status 1: wipefs: error: /dev/sdc1: probing initialization failed: No such file or directory
 (udisks-error-quark, 0)

This is a bug showing up since Wheezy, when using gnome-disk-utility, like explained on https://docs.securedrop.org/en/stable/set_up_dtd.html It can be worked around by issuing the wipefs command manually, then reopening gnome-disk-utility. It is known and now also fixed upstream: https://bugs.freedesktop.org/show_bug.cgi?id=85477

Do we want to update the documentation to mention this? It might still take a while before these upstream changes get merged back into Debian and Tails.

**Comment by fowlslegs** [comment]
Sorry, @KwadroNaut, my eyes seem to have passed over this issue until now. If you can confirm this hasn't been fixed in the latest release of Tails then, yes, we should document this workaround in the docs. PRs would be very much appreciated!

**Comment by KwadroNaut** [comment]
It still does, tested on Tails 2.10. When I or someone else manages to create a pull request, the images need to be updated as well.

**Comment by redshiftzero** [comment]
Thanks for this excellent report @KwadroNaut. I've confirmed that on Tails 2.10 that this is fixed so I think this is good to close. I've also tested this process on a beta for Tails 3.0 (required for SecureDrop 0.4) and updated all the screenshots for the DTD creation process in #1695. 

Let us know if you find any other issues!
