### ISSUE TITLE
https://freedom.press/securedrop is a 404

### ISSUE THREAD

**Issue by bjacobel** [freedomofpress/securedrop#1514]
This link appears in the Github description of the repo, and seems to have moved - maybe it should now point to https://securedrop.org.

I'd submit a PR, but only repo admins can change description and URL meta for a repo.

**Comment by conorsch** [comment]
Nice catch, @bjacobel! Fixed. Updated repo description to use https://securedrop.org, and also added a 301 on the old URL just in case anyone is still using it.
