### ISSUE TITLE
Allow the admin to configure automatic reboot time

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#1515]
The SecureDrop servers automatically reboot every 24 hours to periodically wipe memory (#805). The admin should be allowed to choose when the servers reboot; 5am is not an ideal time for everyone. I, personally, would like to be available when the servers reboot in case they don't come back up on their own.

**Comment by fowlslegs** [comment]
Related: https://github.com/freedomofpress/securedrop/issues/1414.

**Comment by alecmuffett** [comment]
This may seem similar to #1414 but it is not.  It's much simpler than that.  

Presumably the intention is that the reboots should happen in "quiet time" - but if something bad should happen and the machine needs manual intervention, the resulting outage can be several hours in length (5am->9am?) simply waiting for a human being to get to the server/datacentre. 

Some means to configure reboots to be scheduled during prime operational coverage hours, would be easy to build - it's surely just an integer cronjob? - and reduce risk to service.

**Comment by fowlslegs** [comment]
Yeah, one would just have to make a Jinja2 template of [this file](https://github.com/freedomofpress/securedrop/blob/0.3.11/install_files/ansible-base/roles/common/files/cron-apt) and set a var [here](https://github.com/freedomofpress/securedrop/blob/0.3.11/install_files/ansible-base/prod-specific.yml) to specify the reboot time. Super easy if you're familiar w/ Ansible.

**Comment by fowlslegs** [comment]
Only leaving in 0.4 because there's a pending PR and it's a small change.
