### ISSUE TITLE
Support stable ansible in playbooks

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1531]
Ansible is a fast moving target and it is not sustainable to maintain compatibility with the version that is distributed from the `Debian` repos. From a high-level I propose we do the following:

I imagine the below actions will be kicked off by a `./setup.sh` and user wont have to bother with the logic involved:
* Install virtualenv on tails (its fine if this is blown away after reboot)
* build a virtualenv environment under the persistent space, pip install ansible and any other third-party libraries we may need there
* layout wrapper scripts that users call to kick off playbook launch for all runs that make use of this virtualenv. 

Now we may want to run our own pypi mirror specifically to host these packages. That way we can tightly lock to a version of ansible that is compatible with our playbooks. Since dotfiles will be persistent as part of the tails installation process we could also layout a `.pip/pip.conf` and have those changes maintained over reboot.

**Comment by msheiny** [comment]
To be clear I'm advocating bumping ansible to latest `2.2.x` branch and maintaining close match up with latest stable in all SD releases.

**Comment by conorsch** [comment]
Lots of relevant discussion in #1146. Using a virtualenv that persist within the securedrop repository seems the best of both worlds. It will still be difficult for us to mandate version bumps, but it'll be far easier to do so than the current situation, which has us locked at Ansible v1.7.2 due to Tails's use of the Jessie stable repos.

**Comment by fowlslegs** [comment]
I vote in favor of closing this issue and merging discussion with #1146.

**Comment by msheiny** [comment]
Aggggrrrrreeeeeeeeed @fowlslegs.  I'll close this out and continue to post to the other issue.
