### ISSUE TITLE
Add `style guide` to docs/readme so new contributors can be aware of UI/design

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1537]
Basically take the notes from #1536 and other recent issues and compile them somewhere central so when forgetful people like me try to make changes 6 months from now, there will be a convenient place to look.

**Comment by fowlslegs** [comment]
I think making it into a checklist w/ sub-issues is probably the way to go.

**Comment by ninavizz** [comment]
@heartsucker I love you! A UX styleguide is a project unto itself, however. Global IxD patterns and UI styles are important to have documented. Even when done #jamecono style tho, it's a proper project. I def agree tho, we gotta start somewhere—but I'd like to chat with the team about how best to get it going. @justintroutman cc'ing you here as FYI. :)

**Comment by fowlslegs** [comment]
Digression: we love @heartsucker at FPF. Dude does so much good work; it's awesome to have him as a contributor. Deserves some public recognition.

While I'm at it, you've also been doing awesome work @ninavizz, and we're really grateful SD is getting some long overdue attention from a skilled UI/UX designer such as yourself.

**Comment by justintroutman** [comment]
@ninavizz I'm totally on board with the importance of a style guide. Let's set aside a day this week to talk more about this, and the other UX items.

**Comment by ninavizz** [comment]
Created #1552 as a stopgap interim measure.

**Comment by eloquence** [comment]
This is still relevant, but very outdated; since this issue was filed, a lot of work has gone into documenting UI assets and styles, but there is not yet a single canonical styleguide. See https://github.com/freedomofpress/securedrop-ux/wiki for current state.

**Comment by eloquence** [comment]
Upon consideration, closing in favor of more up-to-date UX tracking issue here: https://github.com/freedomofpress/securedrop-ux/issues/65
