### ISSUE TITLE
Rename URL `/lookup` to help sources understand what they are doing

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1556]
Calling it `submit` on first submit and `replies` thereafter would make the most sense. This would help sources understand what is happening if they look at the address bar while navigating. `lookup` doesn't seem to make any sense. This also mirrors the language on the page as @ninavizz mentions in #1536.

**Comment by eloquence** [comment]
Closing as specified, we may want to reconsider the path name at some point, but are probably not going to have a variable path depending on action.
