### ISSUE TITLE
Prevent admin journalists from deleting themselves

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1562]
To prevent lockouts and other forms of usability degradation, I propose one of two things:
1) a full ban on any admin from deleting themselves
2) an admin may not delete themselves if they are the last remaining admin

**Comment by fowlslegs** [comment]
There's still SSH though? Just not convinced this is really a problem that needs solving.

**Comment by conorsch** [comment]
Agreed with @fowlslegs. I've actually used the GUI to delete the last remaining Admin intentionally during on-sites, due to staffing changes, then recreated via the CLI.

**Comment by heartsucker** [comment]
Fair enough. It just seemed like a silly thing to be able to do.

**Comment by fowlslegs** [comment]
Closing as per Conor and I's comments.
