### ISSUE TITLE
Visual indicator to signify which Tails stick is inserted

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1564]
This is more of an issue with tails itself but since it is highly integrated into our workflow I wanted to start tracking it here. We also may be able to implement a work-around until tails introduces a feature we can take advantage of.

Anywhoo -- Jumping around between tails disks can be confusing for admins since there are many different types we ask them to juggle to manage securedrop. We should either work with the Tails folks to get https://labs.riseup.net/code/issues/8846 prioritized or determine some other hacky way to visually indicate to the user which stick they are currently using.

**Comment by fowlslegs** [comment]
From the docs (https://docs.securedrop.org/en/stable/set_up_tails.html#create-tails-usbs):

> As soon as you create a new Tails drive, label it immediately. USB drives all look alike and you’re going to be juggling a whole bunch of them throughout this installation. Label immediately. Always.

Anyway, think this is sufficient, so closing. Feel free to re-open if you still have concerns.

**Comment by msheiny** [comment]
I don't agree that the documentation to label the sticks is sufficient. The documentation requires way too many manual steps and introduces significant opportunity for human error in a variety of steps (and in return vulnerabilities to the system). You also have cases where you upgrade tails sticks from another tails stick so you'll have multiple labeled USB sticks hanging off a machine without knowing which one you booted from.

In general, I think the tails work-flow is hard for users but I understand it is a current necessary evil to maintain the airgap. Doing anything additional in our technical ability to make the tails workflow more accessibility is a huge security/usability win in my book.

**Comment by conorsch** [comment]
The motivation here is sound. One of the most common questions during an initial Admin training is: "Wait, which Tails device is this?" The hardware labels are a must-have to keep track of the sticks when not in use, but once they're booted up, it can be difficult to keep track, particularly if the USB ports are on the rear of a machine, and the label is not easily visible. We recommend labelling the computer hardware as well as the drives, but that's mostly sidestepping the problem of providing a clear visual indicator in the UI.

Even something as simple as color-coding, e.g. black for Admin, blue for Journalist, and red for SVS, would go a long way in helping to guide users.

**Comment by ninavizz** [comment]
If this could get a "Reading Room" label slapped on it, I'd love to have this on the table for UX chin-rubbing. It's a valid humans-being-human problem, much as I appreciate the documentation's recommendation to be sound. 

I know none of y'all read each and every one of my pink-text annotations in the wireframes I've delivered... it's good to be reminded that few humans ever read all the text they're supposed to, on things. :)

**Comment by msheiny** [comment]
> #humansgonnabehuman

preach :tada:

**Comment by fowlslegs** [comment]
We need to partner with Kanguru (in particular because they have offerings w/ physical write protect switches, which is pretty cool) to come out with a pack of joint-branded, pre-labeled, color-coded SD/Kanguru USBs.

> If this could get a "Reading Room" label slapped on it, I'd love to have this on the table for UX chin-rubbing.

The reading room is intended to be a client written for the Qubes operating system, where all user applications run in an arbitrary number of compartmentalized virtual machines. If/when that happens, we won't be booting from USBs at all (we'll be booting Qubes from a standard internal drive).

**Comment by fowlslegs** [comment]
If it wasn't clear the "We need to partner with Kanguru..." was me joking.

**Comment by eloquence** [comment]
Given our focus on the SecureDrop Workstation as an alternative to the legacy Journalist Workstation experience, closing.
