### ISSUE TITLE
All links are broken in https://securedrop.org/faq#audits

### ISSUE THREAD

**Issue by jdcc** [freedomofpress/securedrop#1568]
I was trying to look through the audit info, but all the links in that section appear to be broken.

e.g. https://freedom.press/securedrop-files/iSEC_OTF_FPF_SecureDrop_Deliverable_v1.2.pdf returns a 404.

**Comment by conorsch** [comment]
Drat, thanks for reporting this, @jdcc. This was caused by a recent website migration, and we didn't update the URLs for the audit PDFs. Will get that cleaned up shortly.

**Comment by conorsch** [comment]
All links to the the audit PDFs are now fixed: https://securedrop.org/faq Again, thanks for bringing this to our attention, @jdcc.

**Comment by jdcc** [comment]
No problem! Happy to be another set of eyes.
