### ISSUE TITLE
Change delete/download text on Journalist interface

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1571]
As per the comment from @redshiftzero here https://github.com/freedomofpress/securedrop/pull/1538#issuecomment-277539051:

Change the buttons that say `Download` and `Delete` to say say `Download Selected` and `Delete Selected` when JS is disabled. Optionally, leave as is when JS is enabled. This may be superseded by additional UI changes that I may have seen in @ninavizz's mock ups.

**Comment by fowlslegs** [comment]
Adding to 0.4 because this seems like a usability bug for non-JS users.
