### ISSUE TITLE
Change reset buttons for YubiKey/Authenticator in Journalist/Admin interface

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1572]
As per the suggestion here https://github.com/freedomofpress/securedrop/pull/1538#issuecomment-277539051:

Currently the buttons with the reset text are far too large and it is not necessarily clear what they do. Explanatory text should be added, and the buttons should be relabeled. Could use some input from @ninavizz.

**Comment by SaptakS** [comment]
@heartsucker I was thinking maybe we can add a onhover tooltip to the buttons to show additional information? What kind of information should we have in tooltip? I was thinking something like `RESET APP TOKEN` and `RESET HARDWARE TOKEN` for the button labels and explaining in the tooltip about the 2FA thing. @redshiftzero what do you think?

**Comment by redshiftzero** [comment]
I think that would be great @SaptakS - would this be CSS only?

Looking at the 2FA reset page:

<img width="776" alt="screen shot 2018-04-16 at 10 28 51 am" src="https://user-images.githubusercontent.com/7832803/38825368-2f34c18a-4161-11e8-9735-126935e4f2d7.png">

I think the text we have above the button something like e.g. "Reset 2FA for mobile apps such as FreeOTP or Google Authenticator" and "Reset 2FA for hardware tokens like Yubikey" would be nice for the tooltip.

**Comment by SaptakS** [comment]
I will try making it CSS only. I think it will be possible in principle. 😅
