### ISSUE TITLE
Update text on source codename generation page

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1573]
In this comment https://github.com/freedomofpress/securedrop/pull/1480#issuecomment-278811959 @ninavizz requests that the copy on the `/generate` page be updated.

**Comment by ninavizz** [comment]
This is only for the 0.3.11 release. 

I'm attempting my first-ever PR, right now, to do exactly this. Wish me luck!! :)

**Comment by eloquence** [comment]
This issue is outdated; discussions about revising instructions and UX on this page are still ongoing (#4096, #5239), however.
