### ISSUE TITLE
Build-In SVG Parsing

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#1576]
Hey y'all:

For the Journalist and Admin interfaces, lots of small icons will be very helpful in making otherwise busy pages & list-views easier to read. Extreme icon re-sizing is also paramount in making interfaces responsive—and, eventually, that'll be a priority for the Source interface.

I'd like to add this item to Reading Room and/or 0.4/1.0 for consideration. This is one project I just found in a quick Goog search, but I'll also leave it to the people who really know what they're doing, to figure-out how this may get done, and if it's a feasible thing to add to a list of priorities. https://github.com/memononen/nanosvg

**Comment by fowlslegs** [comment]
The reading room will probably be built with a toolkit that will support this, but I'll look into it for the JI next week.

**Comment by fowlslegs** [comment]
One problem is that some journalists do want use the JI w/ TBB SS on high. Using SVGs would not fit in well with our policy of "graceful degradation." Not sure if this is a total blocker, but it might be best to wait to support this via whatever GUI toolkit we build the reading room client with.

**Comment by fowlslegs** [comment]
Closing because we're trying to move forward with fixing this issue via the reading room client and not here.
