### ISSUE TITLE
Deprecate use of CSS `text-transform: uppercase`

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1587]
Pedantic fix to some ugliness I introduced in previous changes.

**Comment by heartsucker** [comment]
As a note, since SD is moving toward i18n, this might need to be closed and left unimplemented. I'm not sure if browsers are capitalization-aware in other languages. For example, in German there is no such thing as a capital ß, only SS. It would lead to less oddities and a more consistent user experience if the translators write the string as they would be displayed.

**Comment by heartsucker** [comment]
This should be a requirement for i18n because we don't want to break all the buttons If we ever switch cases. Also, we don't want to annoy our translators with tedious capitalization fixes.

We'd also need to confirm support for this in Tor Browser.

**Comment by heartsucker** [comment]
Depends on #2354

**Comment by eloquence** [comment]
We are using the `.upper` class that was added since this issue was filed for some strings. We may in fact want to deprecate using it. The [Mozilla localization guidelines](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices) state:

> The `text-transform` property is not reliable for some locales; for example, `text-transform: uppercase` won't work properly with languages such as Irish/Gaelic. For example, `App Size` in English may be capitalized via `text-transform: uppercase` to `APP SIZE` but in Gaelic this would change `Meud na h-aplacaid` to `MEUD NA H-APLACAID` which violates the locales orthographic rules, as it ought to be `MEUD NA hAPLACAID`. In general, localizers should make the decision about capitalization. If you want to display `WARNING`, add a string with that capitalization, and explain it in the localization note.

I've retitled the issue -- we should either deprecate the use of `text-transform: uppercase` (my recommendation based on the above) or apply it consistently.

**Comment by eloquence** [comment]
Retitled per discussion with @conorsch and @rmol, we'll resolve by fully deprecating use of `text-transform:uppercase`.

**Comment by eaon** [comment]
Stumbled on this during SI redesign work and confirmed that the only element left which uses `text-transform: uppercase` is one button in the JI:

https://github.com/freedomofpress/securedrop/blob/7b6c61a87665dce977a149cbdc81770ddcf38621/securedrop/journalist_templates/edit_account.html#L98-L101

There's a couple of languages which have `RESET PASSWORD` translated but commented out, is it reasonable to revive those or start fresh?

**Comment by cfm** [comment]
Nice catch, @eaon.  Are you referring to gettext entries like:

https://github.com/freedomofpress/securedrop/blob/22ed80b4c7e8fe416f410eb84ac9ca05739417a6/securedrop/translations/tr/LC_MESSAGES/messages.po#L1237-L1238

I believe such entries will be reactivated in Weblate as part of the regular [`i18n_tool.py` workflow](https://docs.securedrop.org/en/stable/development/i18n.html#i18n-tool-py) once that all-caps source string reappears, without our having to uncomment them manually.
