### ISSUE TITLE
Add "Delete my account" functionality to source interface

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1588]
In addition to @ninavizz's suggestions about adding cancel/back buttons to different screens, I think it might be useful to have a feature that makes it permanently impossible to log back in as a particular source. Currently they can just delete all their replies, but this leaves the possibility that they can be compromised before a source writes to them again.

This "deletion" would just be on the source interface so that logins to a particular username is no longer allowed ("user not found" type response), but the docs/messages would remain accessible on the journalist interface. Additionally, a flag would appear on the JI saying "this user has deleted their account" and prohibit them from writing responses.

This would give a few benefits:

1) Make the source feel more comfortable by letting them know they can delete even more traces of their activity
2) Make the source feel more comfortable by giving them more control over the information exchange process
3) Make the source safer by eliminating yet one more way for an adversary to learn information about them in the even of some sort of compromise

What do y'all think?

**Comment by fowlslegs** [comment]
> This "deletion" would just be on the source interface so that logins to a particular username is no longer allowed ("user not found" type response), but the docs/messages would remain accessible on the journalist interface. Additionally, a flag would appear on the JI saying "this user has deleted their account" and prohibit them from writing responses.

A source deleting their account includes deleting all `Reply` objects, but not `Submission` objects, I presume. How about their key? Can you describe how this would work in terms of database and filesystem changes? What happens if a source deletes their account and then a journalist does?

**Comment by ninavizz** [comment]
So, a few problems with this.

1. The current UI presents no user-facing concept of an "account." An individual submits documents with a codename, and no information about them is retained—except for conversations, which they can already delete. What then, is there to erase? From the user's perspective, nothing—except possibly the "unknown" of what happens to their documents once they're on a newsroom's SecureDrop server.

So, 2. Something along the lines of the UI refactoring I presented a while back, with the conversation/messaging on the right half of the screen and the document stuff in the left half of the screen, would likely need to be done, to align user expectations with what all can be deleted.

3. The stuff Noah speaks to above is great—but why would an individual care about erasing those things, and how would SD message information to them about those things without really confusing them? This isn't a good app to let confusion on unknowns fester within users, from.

This is a great discussion to have in a meatspace or conference-call group brainstorm, but not in an asynchronous text thread on GitHub. 

Source "delete account" functionality and other features-of-interest also need to be considered against/abreast each other, for alignment with which new/existing mental models are sought to be presented to users with each release version. Releases can't be structured on PRs. The piecemeal train's running on fumes...

**Comment by heartsucker** [comment]
@ninavizz I mean, yeah, there's no "account," but someone who can phrase things better than an engineer could say something like "Permanently disable this codename" or something of the sort.

As to # 3, I was imagine it like throwing out a burner phone. This means even if an adversary were able to find the codename we told them to write down, it would not work with the SD server in any way and would give the impression that it's just a random password.

And yeah, this needs to be considered against other things that are being developed, but that's why it's here: for discussion. :)

And to @fowlslegs, the one thing we'd need to add to the DB would be a single flag that says "deactivated." If a password is used to login, just return them to the error page after it has been deactivated. On the journalist's side, we just pop up a box that says "this user has abandoned their account" or whatever and prevent them from sending messages. We'd also nuke the keys used for messaging the source since they would be useless. Old messages would stay on the server until the journalist deletes them to avoid breaking their view of the conversation.

**Comment by ninavizz** [comment]
^ I want to smiley your comment (not laugh or thumbs-up), but GitHub won't let me! Rawr!

Agreed completely, that there's definitely value in both the nitty-gritties that Noah cited, and the base concept of allowing users to delete their accounts. Resolving how a user should experience that functionality, is something asynchronous GitHub convos simply suck at. 

The UX person's $.02 is that the mental-model of "an account" needs to be addressed, before how a command/control gets implemented, should be considered. The best solution probably involves tidbits of text on different screens, a button here, other info there, and some dialog bubbles.

I totally agree, GitHub is a great place to bring things up—but I'm seeing way too many solutions sought through asynchronous back-and-forths, here—and that a) takes *much* more time/bandwidth than an in-person or remote whiteboarding brainstorm would (to solve each problem), and b) in many of the convos, its a group of already stretched-too-thin developers working to piecemeal solve for individual user-facing problems, that when all shown together in the UI, then create new user-facing problems that usually go un-noticed by that same team focused first and foremost on releasing a rock-solid security product.

**Comment by zenmonkeykstop** [comment]
Closing - further discussion of source and journalist interactions is required before proceeding with similar functionality.
