### ISSUE TITLE
Create announcement mailing list for new releases

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#1589]
As an admin of a SecureDrop instance it's important that I stay up to date on new releases. I learned about 0.3.11 [through Twitter](https://twitter.com/SecureDrop/status/831296579248074752) and had no information about next steps.

I have since found [securedrop.org/news](https://securedrop.org/news/) with announcements and changelogs. Could you please set up an announcement mailing list for those of us who aren't frequent readers of RSS feeds?

**Comment by conorsch** [comment]
We use the support portal to communicate with Admins over encrypted email. For those onboarded to the support portal ([docs here](https://securedrop-support.readthedocs.io/en/latest/)), we'll send out advance notice of the upcoming 0.4 release. If you are not currently registered for the support site and would like to be, follow the [onboarding docs](https://securedrop-support.readthedocs.io/en/latest/creating_your_account.html) and we'll get you set up.

We will continue to post announcements about new releases to the [securedrop.org blog](https://securedrop.org/news/) and the [securedrop Twitter account](https://twitter.com/securedrop).

There's no firm release date for 0.4 just yet, but we're aiming for within the next two months. If any Admin intervention is required to apply updates, we'll clearly explain the necessary steps in the release documentation, and point Admins with access to the support portal directly to it.

**Comment by conorsch** [comment]
Notified SecureDrop Admins of upcoming v0.3.12 release via Redmine, linking to the [blog post](https://securedrop.org/news/pre-release-announcement-securedrop-0312). Also [tweeted](https://twitter.com/SecureDrop/status/842536312280244224) about it. We'll continue to announce releases ahead of time via Redmine, thereby pushing email to Admin inboxes, to provide advance notice of changes. This should satisfy the concerns raised here.
