### ISSUE TITLE
Set TOTP issuer name intelligently for development and production instances

### ISSUE THREAD

**Issue by nvesely** [freedomofpress/securedrop#1595]
Similar to what we do with the custom homepage string on development instances, it would be nice to append "Development" to the `issuer_name` when creating QR codes for TOTP on development machines.

**Comment by fowlslegs** [comment]
For production installs too, we could improve the TOTP issuer name. By adding an "organization_name" field to `prod-specific.yml`, we could set the issuer name to, e.g., "The Intercept SecureDrop." I think it's likely we may think of places in the future we'd want to use "organization_name" as well. The playbook of course should place this var somewhere in `config.py` for easy reading by other modules and more so general consistency with how we set such variables elsewhere.

**Comment by redshiftzero** [comment]
good news: we now have test dev data and use the same TOTP code across all dev envs and demo, so closing
