### ISSUE TITLE
Line up form fields in Journalist Interface settings views

### ISSUE THREAD

**Issue by nvesely** [freedomofpress/securedrop#1596]
I believe it would look nicer if the form fields in the JI settings view such as `/admin/edit` were lined up as the login page is rather than being staggered according to wherever the adjacent, explanatory line of text ends.

**Comment by redshiftzero** [comment]
This is fixed, closing:

<img width="699" alt="screen shot 2017-11-05 at 12 03 46 pm" src="https://user-images.githubusercontent.com/7832803/32418566-65eb259e-c221-11e7-8118-6d0855d428f9.png">
