### ISSUE TITLE
/admin/2fa view has ugly yellow syntax code block style for new TOTP secret

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1598]
I don't have any particularly wonderful ideas, but even doing a light gray with no border `like Github does` would look a lot better.

**Comment by eloquence** [comment]
Screenshot showing the yellow blob in question:

![Screen Shot 2020-10-09 at 10 24 29-fullpage](https://user-images.githubusercontent.com/213636/95613325-a2663700-0a19-11eb-9aca-8beefc278410.png)

**Comment by DrGFreeman** [comment]
How about this:

![image](https://user-images.githubusercontent.com/22901938/95670126-b747e500-0b55-11eb-8391-8bdd2f2a99b4.png)

* `$color_grey_light` background
* no border
* Increased lateral padding (20px) and vertical padding (8px)
* monospace font
* Increased font size to 1.15em
* Bold font-weight

Let me know if this is good, I can make adjustments if you want and submit a PR with the changes.

**Comment by ninavizz** [comment]
Big legibility improvement, woo! :)
