### ISSUE TITLE
Better strategy for dealing with malware on the SVS

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#160]
The current docs say, "As long as you're using the latest version of Tails, you should be able to open any document that gets submitted to you without the risk of malicious documents compromising the Viewing Station. However, if they do compromise it, Tails is designed so that the next time you reboot the malware will be gone."

I can think of a couple potential issues with this:
1. Hidden malware that gets written to the persistent volume will persist between reboots. We can mitigate this by disabling write-access to the persistent volume after the GPG key is generated there, but we'd have to change the documentation to stop telling journalists to copy encrypted files to the persistent volume. (Why not copy the files to the non-persistent TAILS volume? The reasoning wasn't clear to me from reading the documentation.)
2. Malware could be embedded in a submitted file that the journalist chooses to copy off the SVS to their Journalist Workstation, which has a much greater attack surface than TAILS as well as access to the Internet. Worst-case, the malware had access to sensitive plaintext documents on the SVS and thus bridges the airgap when it gets copied to the Journalist Workstation. 

Fixing (1) might be especially hard because journalists will want to copy external software packages to the persistent volume so that they can be auto-loaded for viewing file types that TAILS doesn't natively support. It seems like it wouldn't be hard to hide malware in one of these packages.

**Comment by heartsucker** [comment]
Marking as "Pending close" because this is in general covered by the Reading Room / journalist workstation.

**Comment by redshiftzero** [comment]
Agreed, the strategy here is the [SecureDrop Qubes workstation](https://github.com/freedomofpress/securedrop-workstation), where each submission will be opened in a Qubes DispVM. Opened followup there: https://github.com/freedomofpress/securedrop-workstation/issues/26
