### ISSUE TITLE
SI is very large and doesn't scale properly

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1600]
On my 1920x1200 external monitor I must scroll horizontally to view the whole page. I heard from @Hainish it is possible to get the viewport size without JS (although TBB may and hopefully does employ additional protections against this). If this is unfortunately possible, we may as well take advantage of it to scale the SI. If it isn't we should at least try to have it render okay on the most popular (tiny by my standards) screen size, 1366x768 [1].

[1] https://techcrunch.com/2012/04/11/move-over-1024x768-the-most-popular-screen-resolution-on-the-web-is-now-1366x768/

**Comment by Hainish** [comment]
The non-JS method involves setting specific URLs to be rendered when the viewport is set to a specific width via CSS media queries.

If session cookies are allowed on the SI, you could detect this property and set the width in a session variable in the width-specific CSS load, then forward the source to an interstitial page (via a redirect meta tag) which itself issues a 30X redirect to the original page, but with the width embedded as a get variable, for instance.

Worflow:

original_page/ (has redirect meta tag and media-query CSS embedded)
    includes css_resource_page_width_1366/ (sets session cookie with correct width)
    forwards to:
interstitial_page/ (reads the session cookie, redirects via 30X to:)
final_page_width_1366/ (which renders correctly)

This seems like a pretty obtuse workflow, though.  Why would you need to detect the width if you have CSS media queries?  Correct rendering should be able to be handled without resorting to this.

**Comment by fowlslegs** [comment]
Just to clarify on this one, we don't actually need to get the viewport size from the client. As Bill notes we can just use CSS media queries to render the page at an appropriate size in relation to the viewport size.

**Comment by heartsucker** [comment]
Related: #1357

**Comment by redshiftzero** [comment]
Making the HTML/CSS responsive for both interfaces solves this, tracked in #1357
