### ISSUE TITLE
DRY out flashed templates

### ISSUE THREAD

**Issue by nvesely** [freedomofpress/securedrop#1602]
Using `category` argument of `flask.flash` we can create a single template for each type of action, that is adapted based on the category argument (see the [relevant Flask docs](http://flask.pocoo.org/docs/0.12/patterns/flashing/#flashing-with-categories)). E.g., for SI submissions, we can use a single template that has conditionals for possible `category` arguments `first_success`, `success`, and `failure`.

**Comment by redshiftzero** [comment]
imho having one template with lots of conditions is less clear, so closing
