### ISSUE TITLE
Double size of SI homepage button icons

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1603]
See item 5 in my comment [here](https://github.com/freedomofpress/securedrop/pull/1581#pullrequestreview-24619661), and Jen's follow-up two comments down. Basically, if we are keeping the icons on the SI homepage buttons, it would look better if they were doubled in size and the two lines of text to the right were justified left to the same imaginary vertical line between them and the equal-height icon.

**Comment by fowlslegs** [comment]
Removing help wanted because we need to figure out a unified UI for the 0.4 release (issue coming) and that may or may not include icons on these buttons.

**Comment by redshiftzero** [comment]
Since we're at a stable point with the UI, let's avoid making further modifications to the UI unless it's to support the i18n effort or based on UX feedback.
