### ISSUE TITLE
Document file integrity checks

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop#1627]
Currently there is no documentation around large files and transferring them to the DTD. To date, I have been doing a _sha256sum_ <filename> before and after transferring them to the DTD. However, this isn't something we can recommend to journalists to do as a **practical** matter. This is especially important for larger files, but I am not sure this is something we should include.

**Comment by fowlslegs** [comment]
Can you explain the nature of the concern(s) here? I don't immediately see why it's important to do this. Gzip includes a CRC, fwiw.

**Comment by freddymartinez9** [comment]
So the maximum file size for a SecureDrop submission 500MB, which is then copied from the Admin tails USB drive to a data transfer device USB. Obviously this takes some time and a USB can be (unintentionally) disconnected at bit 456Mb. If this happens, there are a few possibilities: 
 - the data file won't open (I think this is what you're describing) _after_ the DTD is taken to the SVS. 
 - The USB drive may fail to unmount properly which might catch that the write operation is still in process

In the first case, it would be nice to know ahead of time that the file did not fully copy. Using a sha256sum is what I have been doing. However I am not sure if that is a reasonable UI/UX trade-off to include in the documentation.

**Comment by freddymartinez9** [comment]
Also Tor can die during the download process and of course download speeds are variable through out the network...

**Comment by fowlslegs** [comment]
Wouldn't there be visual indication in TBB if a download failed to complete?

The problem with these instructions in general is that they require journalists to use the command-line, which is something we have intentionally avoided. We could implement and persist a new `sha256sum` Nautilus action, but I'm not convinced this is necessary. I believe the built-in ability to see file size should be sufficient for journalists to determine if somehow they didn't copy over the full file.

I'm not sure how frequently this bites journalists, if they've had troubles diagnosing the source of the problem, and if this warrants documentation. Afaik this is the first time anyone has brought it up.

Turning to discussion of our documentation itself for a minute, I think it is pretty extensive at this point, and am hesitant to add more. Perhaps with a journalist docs re-org, where we could have a 2-page "journalists essentials" section, and then a couple sections on FAQs/ troubleshooting/ advanced topics (e.g., metadata analysis & scrubbing), it might be more acceptable to add something which afaict is an uncommon problem. The goal is to ensure every admin has read everything they need to to use SD safely, and more condensed the appropriate documentation section is, the more likely we are to achieve that goal. (Also, we need a video).

**Comment by eloquence** [comment]
We're unlikely to want users to manually run checksum checks. Our focus now is on the SecureDrop Workstation user experience, where we already added support for ETag based verification (https://github.com/freedomofpress/securedrop/pull/4314).Any additional integrity checks we would add would be automated.
