### ISSUE TITLE
Linting/testing of our shell scripts

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1634]
#1633 was a reminder that our shell scripts often only receive manual review before making it into develop, and that some basic linting--not even proper tests, which are a lot more difficult to implement and run regularly given the context in which most of these scripts are run--could go a long way.

Shellcheck seems like a good option and has [a section in the README](https://github.com/koalaman/shellcheck#travis-ci-setup) on use in Travis. Shellcheck caught #1633. I think it would be a good idea to add it to CI.

Would love to hear other ideas and thoughts on what we could do to improve (especially cheaply) the robustness of our shell script analysis.

**Comment by conorsch** [comment]
Running `shellcheck tail_files/install.sh` locally shows some good output, so I'm inclined to go with that solution for CI. There's a barebones approach in `bash -n tails_files/install.sh` that would have caught the error described in #1633, but shellcheck finds more, and provides more informative output.

**Comment by conorsch** [comment]
Versioning is difficult here:

* Travis: 0.4.6
* Ubuntu Trusty (e.g. dev VM): 0.3.3
* Debian Stretch (example workstation): 0.4.4-4

The differences are substantial enough that a single ruleset cannot be used in all environments. So we're going to have to use a container to bottle up the functionality and make the versioning standard across all environments.
