### ISSUE TITLE
Use lintian to validate deb package build process

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1637]
Beyond simply ensuring that the debs don't have unwanted files (#1507), we should be use `lintian` to inspect the built deb packages in the config test suite and fail out if checks aren't satisfied.

By default lintian performs comprehensive validation, and we likely won't agree with every recommendation. Still, we can selectively opt in to certain checks via the `--tags` option. Good candidates for inclusion in the config test suite are:

* wrong-file-owner-uid-or-gid
* package-contains-vcs-control-file
* package-installs-python-bytecode
* non-standard-file-perm

A parametrized config test that runs all of the above would be grand. In the context of config tests that inspect warnings, the `--fail-on-warnings` flag should be used. See `lintian-info --tags <tag>` for an explanation of what a tag check entails.

**Comment by t2d** [comment]
I started to do a very basic implementation at https://github.com/t2d/securedrop/commit/1f543c2a8ca274af6f89fb96a7005c356da9ef0f
But this actually makes the verifier fail. In what direction do you want this to progress?

**Comment by dachary** [comment]
@t2d I'm sure @conorsch will be very happy to see progress in this direction :-)
