### ISSUE TITLE
Backed out changes for the release of SecureDrop 0.4

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1658]
This is a tracking issue for changes backed out for the upcoming release of SecureDrop 0.4. We want to release 0.4 as soon as possible in order to resolve the large diff between `master` and `develop` (issue #1559). To ease this process both in terms of deployment and minimizing disruptive changes for users, we are going to back out some changes in `develop`. These changes will be reconsidered for release in the 0.5.x release series:

- [ ] Display of journalist username on source interface (UX improvement). Added in PR #1534, removed in PR #1657. See also issue #1592.
- [ ] Assigning journalists to sources. Added in #1491, removed in PR #1671. Requires implementation of #1419. 

Items will be added to this list.

**Comment by dachary** [comment]
@redshiftzero is it still useful ?

**Comment by dachary** [comment]
@redshiftzero or not ?

**Comment by redshiftzero** [comment]
Ah so, I think this is still useful as we do want these changes in (and these items are not otherwise tracked anywhere). I just edited the issue text to say "0.5.x release series" though 😇

**Comment by heartsucker** [comment]
Closing this in favor of discussions in #1355 and #1592 since those are more specific to the actual changes and this is a bit of combined issue for those two.
