### ISSUE TITLE
Remove OSSEC rule when packages update

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1667]
The OSSEC rules are in need of maintenance. In order to reduce [alert fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue), I propose we remove email alerts on informational rules such as this one when packages update:

```
OSSEC HIDS Notification.
2017 Apr 25 04:33:03

Received From: (app) 10.20.2.2->/var/log/dpkg.log
Rule: 2902 fired (level 7) -> "New dpkg (Debian Package) installed."
Portion of the log(s):

2017-04-25 04:33:02 status installed linux-libc-dev:amd64 3.13.0-117.164
```

**Comment by redshiftzero** [comment]
Note that the documentation [here](https://docs.securedrop.org/en/latest/ossec_alerts.html#common-ossec-alerts) should also be changed once this change is made.

**Comment by conorsch** [comment]
Merging the OSSEC package build logic into this repo (#1468) will make iterating on the OSSEC config much easier—especially once we have adequate tests for the alerting rules.

**Comment by zenmonkeykstop** [comment]
:+1: this is noise for the majority for admins.

**Comment by legoktm** [comment]
Agreed that these are noise, but I would think that without this context, the alerts for "Integrity checksum changed" become even more concerning because you don't know that it's caused by a package upgrade vs an attacker.
