### ISSUE TITLE
prep interface_install.sh for issue #159

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#167]
issue #159 requires a couple modifications to interface_install.sh:

1) Have two files for the securedrop/requirements.txt specific to each interface (source/document)

2) add `pip install --upgrade distribute` prior to installing pip dependencies in the install_files/interface_install.sh script for the document interface.

3) copy the mysql specific configuration from setup_ubuntu.sh to separate script in the install_files directory

**Comment by garrettr** [comment]
#159 was merged but has since been superceded. We no longer use shell scripts for provisioning, and instead use the Ansible playbooks in `install_files/ansible-base`. We also don't use mysql anymore.
