### ISSUE TITLE
Filter out Tor Guard overloaded log event in OSSEC

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1670]
I propose we filter out the following alert:  

```
Received From: (app)
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

[warn] Your Guard <name> ($fingerprint) is failing a very large amount of
circuits. Most likely this means the Tor network is overloaded, but it
could also mean an attack against you or potentially the guard itself.
```

It provides some information, but there's no action that we're expecting the SecureDrop admins to take here. It is however an interesting example of a situation where we might want to collect this information for analysis in order to look at trends across SecureDrop instances (e.g. if we implement #973). As with #1667, in order to alleviate alert fatigue, if we're going to be sending email alerts to administrators, we should make sure that it's either critical information or requires some action. 

We should also fix the docs [here](https://docs.securedrop.org/en/latest/ossec_alerts.html#common-ossec-alerts) regarding this rule.

**Comment by freddymartinez9** [comment]
There is a similar alarm (also fired by Rule 1002) that is not related to the Tor guard overload that might be related. I went back and forward on including it in this ticket or opening another one, it looks like this. Please let me know if I should move it to its own ticket

```
Received From: (mon)-> ossec-keepalive
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

-- MARK --: I5A8N31x+TY8%Q-3m [snip]

```
it continues like that for about four lines beginning with `MARK` so I snipped it for brevity's sake. This triggers about once every three months.

**Comment by conorsch** [comment]
@freddymartinez9 Thanks! We've seen this one before, and I agree a filter rule is in order for it. Judging by this [discussion on the ossec list](https://groups.google.com/forum/#!msg/ossec-list/dE3klm84JMU/kGZkRdSl3ZkJ), it appears that message format is used to track internal state within OSSEC, and shouldn't ever percolate up to generating warnings. Its doing so is considered a bug. So an upgrade of OSSEC is in order, but by 0.4.1 we should at least by able to quash the noise.

**Comment by conorsch** [comment]
> Please let me know if I should move it to its own ticket

Yes, do! A title like "Filter out MARK message log event in OSSEC" would make sense. Then ping me and I'll get it on the 0.4.1 milestone so we can knock it out with the other alert updates.
