### ISSUE TITLE
Updated `manage.py` subcommands should have aliases

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1675]
In #1347 we converted the subcommands for the `manage.py` script to use hyphens instead of underscores, e.g. `add_admin` -> `add-admin`. That works well for the most part, assuming existing Admins read the docs on the update, but it will cause problems for currently running instances, because a cron job exists for the `clean_tmp` subcommand, and that subcommand will no longer exist in 0.4. We should do two things to resolve:

1. Implement subcommand aliases in `manage.py` so that the old subcommands still work. 
2. Update the Ansible config to ensure state=absent on the old cronjob, and state=present on the new one. Doing so will ensure that Admins running the playbooks do not create duplicate cron jobs.

If we don't do this, the nightly cron job for cleaning the temp directory will fail on all Application Servers going forward. Therefore this'll need to go on the 0.4 milestone, lest we break the temp cleanup logic currently used in production.

**Comment by fowlslegs** [comment]
Do you think we need to update all subcommands or would just the one be sufficient? @conorsch

**Comment by conorsch** [comment]
Let's do all—I still find myself typing `./manage.py add_admin` when setting up new accounts, and am frustrated by the lack of backwards compatibility every time.
