### ISSUE TITLE
Get Prod environment testing running in CI

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1681]
Depends on first getting CI specific builds of grsecurity in the pipeline, as currently under discussion outside of Github issues. We are also working on the best way to handle forked PRs. 

I have a high-level design of where I think the production testing should fit into our pipeline. This is based on how long the tests take though and whether we are able to get them running in parallel to the staging tests with ease.
![index](https://cloud.githubusercontent.com/assets/1727935/25544689/997ecb7e-2c29-11e7-9636-957a4e8d8922.png)

**Comment by zenmonkeykstop** [comment]
Discussed in backlog grooming session today. Agreed to close as the only real testing benefit over current staging config would be a more accurate OSSEC configuration.
