### ISSUE TITLE
sqlalchemy.pool.NullPool warning and async 

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1690]
8 unit tests are reliably failing for me, even cloning the repo fresh and recreating a `development` VM. The failures kick off just as a warning, ` No handlers could be found for logger "sqlalchemy.pool.NullPool"`, is abruptly printed to stdout. All failures involve unit tests that wait for asynchronous tasks to complete. This is similar to https://github.com/freedomofpress/securedrop/issues/844#issuecomment-72277896.

<details>
  <summary>environment details</summary>
% vagrant --version

Vagrant 1.9.1

% vagrant plugin list
vagrant-libvirt (0.0.40)

% virsh --version
3.0.0

% vagrant box list
bento/ubuntu-14.04 (libvirt, 2.3.1)
</details>

<details>
  <summary>pytest output</summary>
vagrant@development:/vagrant/securedrop$ pytest
========================================================= test session starts ==========================================================
platform linux2 -- Python 2.7.6, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /vagrant, inifile: setup.cfg
plugins: cov-2.4.0
collected 125 items

tests/test_crypto_util.py .
tests/test_db.py .......
tests/test_integration.py No handlers could be found for logger "sqlalchemy.pool.NullPool"
FF.F.FFFF.
tests/test_journalist.py .......................F..........................................
tests/test_manage.py .
tests/test_source.py ......................
tests/test_store.py ...
tests/test_template_filters.py ..........
tests/functional/test_admin_interface.py .
tests/functional/test_submit_and_retrieve_file.py ...
tests/functional/test_submit_and_retrieve_message.py .

=============================================================== FAILURES ===============================================================
________________________________________________ TestIntegration.test_delete_collection ________________________________________________

self = <tests.test_integration.TestIntegration testMethod=test_delete_collection>

    def test_delete_collection(self):
        """Test the "delete collection" button on each collection page"""
        # first, add a source
        self.source_app.get('/generate')
        self.source_app.post('/create')
        self.source_app.post('/submit', data=dict(
            msg="This is a test.",
            fh=(StringIO(''), ''),
        ), follow_redirects=True)

        resp = self.journalist_app.get('/')
        # navigate to the collection page
        soup = BeautifulSoup(resp.data)
        first_col_url = soup.select('ul#cols > li a')[0]['href']
        resp = self.journalist_app.get(first_col_url)
        self.assertEqual(resp.status_code, 200)

        # find the delete form and extract the post parameters
        soup = BeautifulSoup(resp.data)
        delete_form_inputs = soup.select('form#delete_collection')[0]('input')
        sid = delete_form_inputs[1]['value']
        col_name = delete_form_inputs[2]['value']
        resp = self.journalist_app.post('/col/delete/' + sid,
                                      follow_redirects=True)
        self.assertEquals(resp.status_code, 200)

        self.assertIn(escape("%s's collection deleted" % (col_name,)), resp.data)
        self.assertIn("No documents have been submitted!", resp.data)

        # Make sure the collection is deleted from the filesystem
        utils.async.wait_for_assertion(
>           lambda: self.assertFalse(os.path.exists(store.path(sid)))
        )

tests/test_integration.py:442:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils/async.py:47: in wait_for_assertion
    return assertion_expression()
tests/test_integration.py:442: in <lambda>
    lambda: self.assertFalse(os.path.exists(store.path(sid)))
E   AssertionError: True is not false
--------------------------------------------------------- Captured stderr call ---------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 11 of the file /usr/local/bin/pytest. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
[2017-05-06 00:56:57,546] ERROR in source: async_genkey for source (sid=4NR6ULGYSP547VUN6N4BJHEQBA5LGJG7MU5PXKUSUPMSF3YEFJ22CSXSLLW5S4IOG5QXFOMT5MK4UROWTSN377XYPTTFCJCVVDOGCXA=): No row was found for one()
_______________________________________________ TestIntegration.test_delete_collections ________________________________________________

self = <tests.test_integration.TestIntegration testMethod=test_delete_collections>

    def test_delete_collections(self):
        """Test the "delete selected" checkboxes on the index page that can be
            used to delete multiple collections"""
        # first, add some sources
        num_sources = 2
        for i in range(num_sources):
            self.source_app.get('/generate')
            self.source_app.post('/create')
            self.source_app.post('/submit', data=dict(
                msg="This is a test " + str(i) + ".",
                fh=(StringIO(''), ''),
            ), follow_redirects=True)
            self.source_app.get('/logout')

        resp = self.journalist_app.get('/')
        # get all the checkbox values
        soup = BeautifulSoup(resp.data)
        checkbox_values = [checkbox['value'] for checkbox in
                           soup.select('input[name="cols_selected"]')]
        resp = self.journalist_app.post('/col/process', data=dict(
            action='delete',
            cols_selected=checkbox_values
        ), follow_redirects=True)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("%s collections deleted" % (num_sources,), resp.data)

        # Make sure the collections are deleted from the filesystem
>       utils.async.wait_for_assertion(lambda: self.assertFalse(
            any([os.path.exists(store.path(sid)) for sid in checkbox_values])))

tests/test_integration.py:472:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils/async.py:47: in wait_for_assertion
    return assertion_expression()
tests/test_integration.py:473: in <lambda>
    any([os.path.exists(store.path(sid)) for sid in checkbox_values])))
E   AssertionError: True is not false
--------------------------------------------------------- Captured stderr call ---------------------------------------------------------
[2017-05-06 00:57:03,696] ERROR in source: async_genkey for source (sid=5XJTHIB47VYS72OVFBBUATNWDGQDXZCHAN3WLVOS4YO2JMXODNLRNM4PY5ZNUEZF52LTQS2JYXNDZGECPHOU6RRGMQXTQF5TUJGUV5Q=): No row was found for one()
[2017-05-06 00:57:04,035] ERROR in source: async_genkey for source (sid=TAK74LXCGSUWESNLEYRMQXSNLMW4CNLRQZLBJXH3SNGC75XICQATSNR2DUMHRW65UXE3TIYYOD7U5PBSATRRD5J6ZE6Z42RNYGFPZXA=): No row was found for one()
________________________________________________ TestIntegration.test_filenames_delete _________________________________________________

self = <tests.test_integration.TestIntegration testMethod=test_filenames_delete>

    def test_filenames_delete(self):
        """Test pretty, sequential filenames when journalist deletes files"""
        # add a source and submit stuff
        self.source_app.get('/generate')
        self.source_app.post('/create')
        self.helper_filenames_submit()

        # navigate to the collection page
        resp = self.journalist_app.get('/')
        soup = BeautifulSoup(resp.data)
        first_col_url = soup.select('ul#cols > li a')[0]['href']
        resp = self.journalist_app.get(first_col_url)
        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)

        # delete file #2
>       self.helper_filenames_delete(soup, 1)

tests/test_integration.py:514:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_integration.py:613: in helper_filenames_delete
    utils.async.wait_for_assertion(lambda: self.assertFalse(
tests/utils/async.py:47: in wait_for_assertion
    return assertion_expression()
tests/test_integration.py:614: in <lambda>
    any([os.path.exists(store.path(sid, doc_name)) for doc_name in checkbox_values])))
E   AssertionError: True is not false
--------------------------------------------------------- Captured stderr call ---------------------------------------------------------
[2017-05-06 00:57:10,621] ERROR in source: async_genkey for source (sid=EVFJWXWF2V2FDV36YZVIA4VTEEECVBZULE372EPVN7KLF4QUA53HMK73ISFOLDOAIDBB7DK3LJJOSQ67KPVKDQGGVNZ5BR55T6COLPQ=): No row was found for one()
__________________________________________________ TestIntegration.test_reply_normal ___________________________________________________

self = <tests.test_integration.TestIntegration testMethod=test_reply_normal>

    def test_reply_normal(self):
>       self.helper_test_reply("This is a test reply.", True)

tests/test_integration.py:235:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_integration.py:377: in helper_test_reply
    self.helper_filenames_delete(soup, last_reply_number)
tests/test_integration.py:613: in helper_filenames_delete
    utils.async.wait_for_assertion(lambda: self.assertFalse(
tests/utils/async.py:47: in wait_for_assertion
    return assertion_expression()
tests/test_integration.py:614: in <lambda>
    any([os.path.exists(store.path(sid, doc_name)) for doc_name in checkbox_values])))
E   AssertionError: True is not false
___________________________________________________ TestIntegration.test_submit_file ___________________________________________________

self = <tests.test_integration.TestIntegration testMethod=test_submit_file>

    def test_submit_file(self):
        """When a source creates an account, test that a new entry appears in the journalist interface"""
        test_file_contents = "This is a test file."
        test_filename = "test.txt"

        with self.source_app as source_app:
            resp = source_app.get('/generate')
            resp = source_app.post('/create', follow_redirects=True)
            codename = session['codename']
            sid = g.sid
            # redirected to submission form
            resp = self.source_app.post('/submit', data=dict(
                msg="",
                fh=(StringIO(test_file_contents), test_filename),
            ), follow_redirects=True)
            self.assertEqual(resp.status_code, 200)
            source_app.get('/logout')

        resp = self.journalist_app.get('/')
        self.assertEqual(resp.status_code, 200)
        self.assertIn("Sources", resp.data)
        soup = BeautifulSoup(resp.data)

        # The source should have a "download unread" link that says "1 unread"
        col = soup.select('ul#cols > li')[0]
        unread_span = col.select('span.unread a')[0]
        self.assertIn("1 unread", unread_span.get_text())

        col_url = soup.select('ul#cols > li a')[0]['href']
        resp = self.journalist_app.get(col_url)
        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)
        submission_url = soup.select('ul#submissions li a')[0]['href']
        self.assertIn("-doc", submission_url)
        span = soup.select('ul#submissions li span.info span')[0]
        self.assertRegexpMatches(span['title'], "\d+ bytes")

        resp = self.journalist_app.get(submission_url)
        self.assertEqual(resp.status_code, 200)
        decrypted_data = self.gpg.decrypt(resp.data)
        self.assertTrue(decrypted_data.ok)

        sio = StringIO(decrypted_data.data)
        with gzip.GzipFile(mode='rb', fileobj=sio) as gzip_file:
            unzipped_decrypted_data = gzip_file.read()
        self.assertEqual(unzipped_decrypted_data, test_file_contents)

        # delete submission
        resp = self.journalist_app.get(col_url)
        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)
        doc_name = soup.select(
            'ul > li > input[name="doc_names_selected"]')[0]['value']
        resp = self.journalist_app.post('/bulk', data=dict(
            action='confirm_delete',
            sid=sid,
            doc_names_selected=doc_name
        ))

        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)
        self.assertIn("The following file has been selected for", resp.data)

        # confirm delete submission
        doc_name = soup.select
        doc_name = soup.select(
            'ul > li > input[name="doc_names_selected"]')[0]['value']
        resp = self.journalist_app.post('/bulk', data=dict(
            action='delete',
            sid=sid,
            doc_names_selected=doc_name,
        ), follow_redirects=True)
        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)
        self.assertIn("Submission deleted.", resp.data)

        # confirm that submission deleted and absent in list of submissions
        resp = self.journalist_app.get(col_url)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("No documents to display.", resp.data)

        # the file should be deleted from the filesystem
        # since file deletion is handled by a polling worker, this test needs
        # to wait for the worker to get the job and execute it
        utils.async.wait_for_assertion(
>           lambda: self.assertFalse(os.path.exists(store.path(sid, doc_name)))
        )

tests/test_integration.py:231:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils/async.py:47: in wait_for_assertion
    return assertion_expression()
tests/test_integration.py:231: in <lambda>
    lambda: self.assertFalse(os.path.exists(store.path(sid, doc_name)))
E   AssertionError: True is not false
_________________________________________________ TestIntegration.test_submit_message __________________________________________________

self = <tests.test_integration.TestIntegration testMethod=test_submit_message>

    def test_submit_message(self):
        """When a source creates an account, test that a new entry appears in the journalist interface"""
        test_msg = "This is a test message."

        with self.source_app as source_app:
            resp = source_app.get('/generate')
            resp = source_app.post('/create', follow_redirects=True)
            codename = session['codename']
            sid = g.sid
            # redirected to submission form
            resp = self.source_app.post('/submit', data=dict(
                msg=test_msg,
                fh=(StringIO(''), ''),
            ), follow_redirects=True)
            self.assertEqual(resp.status_code, 200)
            source_app.get('/logout')

        # Request the Journalist Interface index
        rv = self.journalist_app.get('/')
        self.assertEqual(rv.status_code, 200)
        self.assertIn("Sources", rv.data)
        soup = BeautifulSoup(rv.data)

        # The source should have a "download unread" link that says "1 unread"
        col = soup.select('ul#cols > li')[0]
        unread_span = col.select('span.unread a')[0]
        self.assertIn("1 unread", unread_span.get_text())

        col_url = soup.select('ul#cols > li a')[0]['href']
        resp = self.journalist_app.get(col_url)
        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)
        submission_url = soup.select('ul#submissions li a')[0]['href']
        self.assertIn("-msg", submission_url)
        span = soup.select('ul#submissions li span.info span')[0]
        self.assertRegexpMatches(span['title'], "\d+ bytes")

        resp = self.journalist_app.get(submission_url)
        self.assertEqual(resp.status_code, 200)
        decrypted_data = self.gpg.decrypt(resp.data)
        self.assertTrue(decrypted_data.ok)
        self.assertEqual(decrypted_data.data, test_msg)

        # delete submission
        resp = self.journalist_app.get(col_url)
        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)
        doc_name = soup.select(
            'ul > li > input[name="doc_names_selected"]')[0]['value']
        resp = self.journalist_app.post('/bulk', data=dict(
            action='confirm_delete',
            sid=sid,
            doc_names_selected=doc_name
        ))

        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)
        self.assertIn("The following file has been selected for", resp.data)

        # confirm delete submission
        doc_name = soup.select
        doc_name = soup.select(
            'ul > li > input[name="doc_names_selected"]')[0]['value']
        resp = self.journalist_app.post('/bulk', data=dict(
            action='delete',
            sid=sid,
            doc_names_selected=doc_name,
        ), follow_redirects=True)
        self.assertEqual(resp.status_code, 200)
        soup = BeautifulSoup(resp.data)
        self.assertIn("Submission deleted.", resp.data)

        # confirm that submission deleted and absent in list of submissions
        resp = self.journalist_app.get(col_url)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("No documents to display.", resp.data)

        # the file should be deleted from the filesystem
        # since file deletion is handled by a polling worker, this test needs
        # to wait for the worker to get the job and execute it
        utils.async.wait_for_assertion(
>           lambda: self.assertFalse(os.path.exists(store.path(sid, doc_name)))
        )

tests/test_integration.py:143:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils/async.py:47: in wait_for_assertion
    return assertion_expression()
tests/test_integration.py:143: in <lambda>
    lambda: self.assertFalse(os.path.exists(store.path(sid, doc_name)))
E   AssertionError: True is not false
___________________________________________ TestIntegration.test_unicode_reply_with_ansi_env ___________________________________________

self = <tests.test_integration.TestIntegration testMethod=test_unicode_reply_with_ansi_env>

    def test_unicode_reply_with_ansi_env(self):
        # This makes python-gnupg handle encoding equivalent to if we were
        # running SD in an environment where os.getenv("LANG") == "C".
        # Unfortunately, with the way our test suite is set up simply setting
        # that env var here will not have the desired effect. Instead we
        # monkey-patch the GPG object that is called crypto_util to imitate the
        # _encoding attribute it would have had it been initialized in a "C"
        # environment. See
        # https://github.com/freedomofpress/securedrop/issues/1360 for context.
        old_encoding = crypto_util.gpg._encoding
        crypto_util.gpg._encoding = "ansi_x3.4_1968"
        try:
>           self.helper_test_reply("ᚠᛇᚻ᛫ᛒᛦᚦ᛫ᚠᚱᚩᚠᚢᚱ᛫ᚠᛁᚱᚪ᛫ᚷᛖᚻᚹᛦᛚᚳᚢᛗ", True)

tests/test_integration.py:249:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_integration.py:377: in helper_test_reply
    self.helper_filenames_delete(soup, last_reply_number)
tests/test_integration.py:613: in helper_filenames_delete
    utils.async.wait_for_assertion(lambda: self.assertFalse(
tests/utils/async.py:47: in wait_for_assertion
    return assertion_expression()
tests/test_integration.py:614: in <lambda>
    any([os.path.exists(store.path(sid, doc_name)) for doc_name in checkbox_values])))
E   AssertionError: True is not false
______________________________________ TestJournalistApp.test_delete_source_deletes_docs_on_disk _______________________________________

self = <tests.test_journalist.TestJournalistApp testMethod=test_delete_source_deletes_docs_on_disk>

    def test_delete_source_deletes_docs_on_disk(self):
        """Verify that when a source is deleted, the encrypted documents that
            exist on disk is also deleted."""
        self._delete_collection_setup()

        # Encrypted documents exists
        dir_source_docs = os.path.join(config.STORE_DIR, self.source.filesystem_id)
        self.assertTrue(os.path.exists(dir_source_docs))

        job = journalist.delete_collection(self.source.filesystem_id)

        # Wait up to 5s to wait for Redis worker `srm` operation to complete
>       utils.async.wait_for_redis_worker(job)

tests/test_journalist.py:551:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

job = Job(u'd2cb03d9-8624-4e33-baac-401c212d4d3d', enqueued_at=datetime.datetime(2017, 5, 6, 0, 57, 58, 243655)), timeout = 5

    def wait_for_redis_worker(job, timeout=5):
        """Raise an error if the Redis job doesn't complete successfully
        before a timeout.

        :param rq.job.Job job: A Redis job to wait for.

        :param int timeout: Seconds to wait for the job to finish.

        :raises: An :exc:`AssertionError`.
        """
        start_time = time.time()
        while time.time() - start_time < timeout:
            if job.result == REDIS_SUCCESS_RETURN_VALUE:
                return
            elif job.result not in (None, REDIS_SUCCESS_RETURN_VALUE):
                assert False, 'Redis worker failed!'
            time.sleep(0.1)
>       assert False, 'Redis worker timed out!'
E       AssertionError: Redis worker timed out!

tests/utils/async.py:27: AssertionError
================================================ 8 failed, 117 passed in 184.81 seconds ================================================
</details>

**Comment by redshiftzero** [comment]
What happens if from `/vagrant/securedrop` you run `pytest tests/`?

**Comment by fowlslegs** [comment]
Same thing.

**Comment by fowlslegs** [comment]
Oh wait, that's actually working now. I had tried both `pytest tests/test_integration.py and `pytest tests/` before, and both were failing, but now they're both working. I'm not sure what gives.

**Comment by redshiftzero** [comment]
I also don't see this locally - good to close?

**Comment by fowlslegs** [comment]
When `pytest` is run from `/vagrant/securedrop/` the `inifile` becomes `/vagrant/setup.cfg` and the `rootdir` `/vagrant`. When `pytest tests/` is run from the same directory, the `inifile` is `/vagrant/securedrop/tests/pytest.ini` and the `rootdir` is `/vagrant/securedrop/tests`. The latter `inifile` and `rootdir` are the correct ones. https://docs.pytest.org/en/latest/customize.html#initialization-determining-rootdir-and-inifile explains this behavior.

So while this is reason enough to run `pytest tests/` instead of `pytest`, it still doesn't explain the weird `NullPool` warnings. I'm also curious why running just `pytest` was working in the past, but not now. Anyway, since it is documented to run `pytest tests/`, I'm closing this issue, as my remaining questions are out of scope of this issue (and really don't qualify as an "issue" anymore).
