### ISSUE TITLE
Reboot staging servers on first provision

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1704]
Currently the staging servers need to be manually rebooted after they are provisioned in order for the iptables config to take. Ideally this would be a task done the first time the servers are provisioned.

**Comment by conorsch** [comment]
We can rather trivially detect "was this the first time the staging playbook was run" by inspecting the output of `iptables -S`—it'll contain only the default chains and policies if true.

**Comment by conorsch** [comment]
We should reboot at the end of `./securedrop-admin install` _if-and-only-if` we're performing a first-time install, as described above. Otherwise Admins will be discouraged from applying new configs because doing so will cause middle-of-the-day downtime.

**Comment by conorsch** [comment]
Going to tackle this shortly. I've been testing in local VMs frequently (e.g. #2137), and the manual reboot workflow is painful. With a clean implementation, we can also avoid unnecessary reboots triggered by Admins applying the Ansible config to running servers.
