### ISSUE TITLE
Text on source landing page bar doesn't make sense

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1713]
Here is the source interface landing page on develop:

![screen shot 2017-05-18 at 11 44 03 am](https://cloud.githubusercontent.com/assets/7832803/26218311/63fec6f2-3bbf-11e7-9ff9-180f4dad9bb8.png)

The text in the purple bar reads: "We recommend turning the Security Slider to High to protect your anonymity: Learn how to disable it". 

This doesn't make sense, since this bar is displayed when the Security Slider is _not_ enabled, meaning that the text should read: "We recommend turning the Security Slider to High to protect your anonymity: Learn how to set it to high"

**Comment by thisisparker** [comment]
Somebody (ideally on a Mac, to match the existing screenshots) should update this image in Step 2 of the Source Guide in the docs: https://docs.securedrop.org/en/latest/source.html

**Comment by redshiftzero** [comment]
Good eye! So this change is not yet in production but as you correctly note we do need to do this before the next release (0.4). Note we have a checklist in issue #1544 for the docs changes that need to be done. The current plan is to do these after we do a round of testing of the release candidate on hardware in case changes need to be made (to avoid taking the screenshots twice) and then we'll take a round of screenshots to update the Source, Journalist, Admin guides right before release.
