### ISSUE TITLE
Add application tests to staging CI

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1724]
Currently the application tests are running under the `development` CI environment (travis) but not under the `staging` environment (circleCI). Lets get those tests running and fail the build if they fail.

A stretch goal is to spit out results to junit.xml. This allows the CI environment to parse test results and display them with G-U-I power! :boom:

**Comment by redshiftzero** [comment]
Another one that was addressed by #1731, so closing.
