### ISSUE TITLE
Possible race condition when two Journalists Reply to same Source simultaneously

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1728]
There may be a race condition in `db.Journalist.reply()`. There are potentially many unexpected outcomes of two Journalists sending a reply to the same source at the same time, and I believe I'm only part of the way to narrowing down the most likely ones. Nonetheless, I'll share my initial determinations and concerns.

Here's the important bit of `db.Journalist.reply()`:

```py
    g.source.interaction_count += 1
    filename = "{0}-{1}-reply.gpg".format(g.source.interaction_count,
                                          g.source.journalist_filename)
    crypto_util.encrypt(msg,
                        [crypto_util.getkey(g.sid), config.JOURNALIST_KEY],
                        output=store.path(g.sid, filename))
    reply = Reply(g.user, g.source, filename)

    try:
        db_session.add(reply)
        db_session.commit()
```

Also important, the function used to assign `g.source`:

```py
def get_source(sid):
    """Return a Source object, representing the database row, for the source
    with id `sid`"""
    source = None
    query = Source.query.filter(Source.filesystem_id == sid)
    source = get_one_or_else(query, app.logger, abort)

    return source
```

So the worry is that the thread-local `g.source` object is the same for both request threads in the case where the second thread executes `get_source()` before the first executes `commit()`.

It might be easiest to break down possible outcomes by operation. I confirmed experimentally (`ipython` + tmux's `synchronize-panes` feature) that you can bring a source into your session, inc the `interaction_count` and `commit()` in two interpreters simultaneously and no errors occur. So in such a situation I believe we can assume `interaction_count` will be increased just by one despite two replies, and 

The database itself will not be updated until `commit()` is called, so both threads can update the `source.interaction_count`, but instead of increasing by two, an increase of only one happens _without exception_.

Next, let's look at `crypto_util.encrypt()`. Since this the only I/O operation in between execution of our functions/methods of interest, it's almost certainly the most time consuming and highly likely to be a point of overlap (i.e., both threads are statistically most likely to have some overlap in their execution of this procedure). Since `interaction_count` increases are not synced between the threads here, they will both be the same, so `filename` will be the same. This means both replies will be written to the same file. Looking at `gnupg._meta._encrypt`, we see how this is handled:

```py
        if output:
            if getattr(output, 'fileno', None) is not None:
                ## avoid overwrite confirmation message
                if getattr(output, 'name', None) is not None:
                    output_filename = output.name
                    if os.path.exists(output.name):
                        os.remove(output.name)
                    #args.append('--output %s' % output.name)
            else:
                output_filename = output
                if os.path.exists(output):
                    os.remove(output)
                #args.append('--output %s' % output)
```

Now, referencing [this StackOverflow answer](https://stackoverflow.com/a/28009230) and my own experimental evidence, ~~the removal will only happen after all file descriptors for the file are closed. Since the second thread will remove the file only to open it for writing immediately afterward, the file is actually removed after the second thread finishes writing.~~

**Correction:** I don't know how I missed the presence of the file at first, but in this situation the second thread does actually create the file (specifically, `filename` exists and corresponds to the encrypted reply of the second thread, whereas the reply from the first thread simply vanishes). Now, back to analysis...

Remember, this overlap does not necessarily happen, I just hypothesize that if the conditions for a race condition are satisfied as defined above, it is statistically likely this will happen.

Now, we have to wonder what happens when we create our `Reply` object. Since a file will be accessible under the name `filename`, the initializer will succeed and each thread will be able to create a `Reply` object regardless if the the other thread has `commit()`ed yet or not. Both `commit()`s should succeed too, and we'll end up with two `Reply` objects added to the database, both of which pointing to the same `filename` that contains the reply from the second thread. Further, the first Journalist won't know their reply did not succeed.

I won't go much further into the implications, but if this edge-case scenario were to take place, this might in turn cause a lot more problems, such as in the source `/lookup` view, where the source would see two copies of the second thread's reply.

As I stated in the beginning of this issue, the possible outcomes are difficult (maybe near impossible) to exhaustively enumerate. What I hope I've done is made a sufficient case for implementing some kind of locking or transactional mechanism here, or at least provided a sufficiently interesting scenario to lead to a thorough discussion that may or may not result in the implementation of such mechanisms. If I'm missing anything, misunderstanding anything, or you just think this is way too unlikely to ever happen in production, please let me know.

**Comment by eloquence** [comment]
See also #5280, which focuses on interaction counts specifically. I'm going to close out this very old issue, but will cross-reference  these notes for further investigation.
