### ISSUE TITLE
Some links broken when searching on docs.securedrop.org (stable)

### ISSUE THREAD

**Issue by justintroutman** [freedomofpress/securedrop#1735]
### Problem

When searching for some keywords on [docs.securedrop.org](https://docs.securedrop.org), the returned links will often point to files with a `rst.html` extension, rather than the appropriate `.html`. This results in a 404; however, I've only noticed this on `stable`; it hasn't occurred to me on `latest`.

### Reproduce

[Here's an example](https://docs.securedrop.org/en/stable/search.html?q=keyserver&check_keywords=yes&area=default) when searching for the keyword `keyserver`.

### Related

This issue is known to the Read the Docs team and is [actively being addressed](https://github.com/rtfd/readthedocs.org/issues/2708); it's likely related to Sphinx.

**Comment by redshiftzero** [comment]
This was fixed upstream. Closing
