### ISSUE TITLE
Re-vamp developer local workflow

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1748]
Utilize containers and add an FPF image to speed up the local developer workflow for contributors. Smooth out the user experience by standardizing the `Makefile` a bit more so its more intuitive on how to kick the system off.

Part of this task should also involve better mapping out our container management story. In other words, we should better document our publicly hosted containers, sign tags, and provide user guidance on how to verify images. Bonus points for having the workflow automation scripts verify tags automatically upon image pull.

**Comment by redshiftzero** [comment]
We now have a Docker based development environment - closing this issue in favor of the more specific #2902. Please file more specific items as comments or followup issues
