### ISSUE TITLE
Port forwarded interfaces extremely slow in staging environment after rebooting the VM's

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1764]
# Steps to Reproduce

1. Start with a clean copy of the latest from the develop branch: `git checkout develop && git reset --hard HEAD`
2. Following the developer docs, bring up the `build` VM without provisioning: `vagrant up --no-provision build`.
3. Provision the staging environment from scratch: `vagrant destroy -f /staging/ && vagrant up /staging/`.
4. Once the staging environment is provisioned, attempt to access the port forwarded Source Interface in your local web browser: `127.0.0.1:8082`. The SecureDrop Source Interface homepage should load quickly.
5. Reload the staging environment: `vagrant reload /staging/`, or, equivalently, `vagrant halt /staging/ && vagrant up /staging/`.
6. Attempt to access the port forwarded Source Interface in your local web browser again. If you already had the page open in your browser, do a hard refresh (`Cmd-shift-R) to reload the page and all of its resources.

## Expected behavior

The port forwarded Source Interface loads quickly, just like it did after the initial provisioning.

## Observed behavior

The port forwarded Source Interface loads extremely slowly. Here's before and after screenshots of the Network panel in Tor Browser's developer tools:

### After initial provisioning (fast)

<img width="1280" alt="screen shot 2017-05-30 at 7 49 51 pm" src="https://cloud.githubusercontent.com/assets/407302/26613789/58d42f36-4571-11e7-89dc-8ff4bce711fe.png">

### After reload (slow)

<img width="1280" alt="screen shot 2017-05-30 at 7 36 48 pm" src="https://cloud.githubusercontent.com/assets/407302/26613811/7642c820-4571-11e7-9495-516bf1cc9c9a.png">

I asked @redshiftzero to attempt to reproduce the issue and she was able to reproduce. @conorsch @msheiny do you have any ideas? I am baffled.

**Comment by garrettr** [comment]
After conversation with @conorsch, it seems that @redshiftzero and I are on our own with this one because we are the only regular developers using Max OS X and Virtualbox to host the Vagrant development environments. I am given to understand that on @conorsch's local staging environment the port forwarded ports do not work _at all_, it is unclear when they stop working or if indeed they ever worked.

Also unclear is whether this should be considered a bug, or a feature.

**Comment by garrettr** [comment]
Currently running the gamut of "obvious solutions from the first page of the Google results," because I really have no idea where to begin with this one.

**Comment by conorsch** [comment]
@garrettr In staging I always use the Onion URLs, never the forwarded ports. In the context of working on #1714, the Onion URLs are what we really want to test, although I admit having port forwards would be nice.

Would be interested to hear whether the solutions discussed here are relevant for your host: https://github.com/mitchellh/vagrant/issues/1807

**Comment by garrettr** [comment]
Ok, I've determined the cause of this issue and have some proposals for resolution.

# Cause

I noticed iptables logging while tailing syslog and attempting to load the port forwarded Source Interface on my host:

```
Jun  1 00:45:29 app-staging kernel: [   63.895200] IN= OUT=eth0 SRC=10.0.2.15 DST=10.0.2.2 LEN=1500 TOS=0x00 PREC=0x00 TTL=64 ID=10597 DF PROTO=TCP SPT=80 DPT=58027 WINDOW=30016 RES=0x00 ACK PSH URGP=0 UID=33 GID=33
```

I used `watch -d iptables -L OUTPUT -n -v` and looked for changes in `pkts` column to determine that the `"Drop all other traffic by the securedrop user"` iptables rule is responsible for blocking the response to requests made on the port forwarded web interfaces.

The cause of the issue is our iptables rules, which only allow Apache to communicate with the loopback interface, which is where Tor proxies requests from the Tor Hidden services. From `install_files/ansible-base/roles/restrict-direct-access/templates/rules_v4`:

```
-A INPUT -i lo -p tcp --dport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT -m comment --comment "Allow tor connection from local loopback to connect to source int"
-A OUTPUT -o lo -p tcp --sport 80 -m owner --uid-owner www-data -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment "Restrict the apache user outbound connections"
-A INPUT -i lo -p tcp --dport 8080 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT -m comment --comment "Allow tor connection from local loopback to connect to journalist int"
-A OUTPUT -o lo -p tcp --sport 8080 -m owner --uid-owner www-data -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment "Restrict the apache user outbound connections"
```

Any non-whitelisted traffic originating from the Apache user is dropped:

```
# Block all other traffic by application users
# Load before generic loopback rules
-A OUTPUT -m owner --uid-owner www-data -j LOGNDROP -m comment --comment "Drop all other traffic by the securedrop user"
```

This is (IIRC) intended to harden Apache by making it difficult for a compromised Apache process to make arbitrary outbound connections (the efficacy/worth of this countermeasure may be debatable—I welcome any feedback).

So the web interfaces are **accessible** over the Tor Hidden Services, because that traffic is proxied over localhost by Tor and thus permitted by iptables. They are **inaccessible** over the forwarded ports because that traffic originates directly from the Virtualbox NAT network interface (`eth0`), which is not whitelisted and therefore is blocked.

Later in the iptables rule file, there is a block of rules intended to whitelist this traffic, but since it comes too late (iptables rules are matched sequentially), it is never reached and never has an effect. The reordering of the iptables rules that caused this bug seems like an accidental consequence of 30131ef4516e3cffde8a9be134c9849e45e3484c.

# Proposals for Resolution

1. Reorder the iptables rules file so the exceptions for the staging environment are injected earlier than any blanket drop rules, which should restore their functionality.
2. Remove the port forwarded web interfaces entirely.
    * The main reason they exist is because it gets annoying to repeatedly reconfigure your Tor process to accept new ATHS values for the Document Interface, but this is a relatively minor annoyance. So while port forwarded SSH is critical to the usability of the staging environment (SSH over Tor ATHS is an exercise in masochism and saps productivity), the port forwarded web interfaces are potentially disposable.
    * Benefits of removal include:
        * One less thing to maintain, and one less discrepancy between the staging and production environment. Historically, such discrepancies have repeatedly been a source of bugs and/or confusion.
        * Forces developers to interact with the web services over Tor, which provides a much more accurate dogfooding experience and may encourage performance optimizations that improve end user experience.
        * Apparently some core developers (e.g. @conorsch) never even use the port forwarded web interfaces, so removing them would not impact their workflow.

@redshiftzero @fowlslegs @conorsch @msheiny Any strong opinions on which proposal for resolution you prefer? I'm happy to implement either one.

**Comment by msheiny** [comment]
:+1: Sweet troubleshooting. I agree with the removal of the port forwarding for staging.

**Comment by garrettr** [comment]
Good example of how using the port forwarded web interfaces can be potentially misleading: https://github.com/freedomofpress/securedrop/issues/1714#issuecomment-305069502.

**Comment by conorsch** [comment]
Great debugging, @garrettr! My bad on the regression you pointed out. I'm with @msheiny: let's ditch the forwarded ports (for web interfaces) in staging altogether. We can keep the forwarded ports on for web interfaces on development, for rapid prototyping, but testing the Source/Journalist Interfaces is really best done over Tor anyway. 

To be clear, we should still preserve the SSH port forwards in staging, but those seem unaffected by the iptables rules misodering.

Naturally docs updates are in order if we drop the staging web port forwards, but they should be minimal.

**Comment by fowlslegs** [comment]
^+1
