### ISSUE TITLE
Automate ansible inventory with dynamic script

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1774]
We have a current expectation now for admins to manage the ansible `inventory` file ( located in `install_files/ansible-base` ) themselves which is kind of painful. Additionally we already collect and/or manage the relative bits of information that are needed for ansible to connect - so lets create a simple dynamic inventory script so admins dont have to touch that file any longer! Yayyyy

From a high level I see the dynamic script looking like this:

```
if ths files dont exist:
   pull data from site-specific vars
else:
   pull connection address from ths files and user info from site-specific vars
```

**Comment by conorsch** [comment]
This is a great idea. In addition to saving Admin time and minimizing frustration due to manual edits, it'll allow us to remove the static-inventory-munging logic from `tails_files/install.sh`, which is largely untested. Will open a PR shortly for review, just have some docs edits to make.
