### ISSUE TITLE
Review and annotate Apache configurations

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1775]
The Apache configuration needs to be reviewed, annotated, and potentially revised, because:

* Some if its directives may be redundant/pointless
* There are few comments, which makes the configuration hard to audit.

Follow-up to https://github.com/freedomofpress/securedrop/issues/1763#issuecomment-306341678.

**Comment by garrettr** [comment]
I got started on this while I was working on #1777, but we decided to focus on making the minimal changes necessary to resolve #1763 for the 0.4 release and defer a more thorough overhaul of the Apache configs for a later release.

So it's available to anyone who's interested, I pushed a [work-in-progress branch](https://github.com/freedomofpress/securedrop/tree/annotate-apache-configs) of the additional review and annotation that I did while working on #1777.

**Comment by eloquence** [comment]
Candidate for a time-boxed review given the transition to Focal, but may end up getting bumped off the milestone.

**Comment by eloquence** [comment]
@conorsch has committed to helping with said time-boxed review, but a stretch goal for 1.8.0.
