### ISSUE TITLE
Auto-labeler should be idempotent

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1784]
Currently, our auto-labeler will re-apply already applied labels, creating an annoying effect as can be seen in https://github.com/freedomofpress/securedrop/pull/1103.

**Comment by dachary** [comment]
See https://github.com/freedomofpress/securedrop/blob/develop/.github/auto-labeler/index.js#L38

**Comment by legoktm** [comment]
We don't use the auto-labeler anymore
