### ISSUE TITLE
Extend Source JS to warn on out-of-date UA

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1787]
We include JS on the Source Interface page primarily to warn users to disable it. However, we have extended the functionality of this script to warn if the user is not using Tor Browser. Similarly, we could warn when users visit SD running out-of-date versions of Tor Browser (with some, albeit not total accuracy, as TB's UA does not change with each new TB release). Ideally, a warning banner similar to the Security Slider should be shown, with a link that pops up a similar info bubble, except with instructions on updating Tor Browser.

**Comment by fowlslegs** [comment]
I wonder if would be worthwhile not to do this in JS to catch the case where a user is running an out-of-date version of TB w/ JS disabled. This would probably mean templating the homepage. I think it should be possible to do this in a way that is aesthetically pleasing still.

The same could be asked of our detection of non-TB UAs. It seems better not to make important safety features depend on the presence of JS, when it's something we want to be disabled; perhaps we should stick with only employing JS to get users to disable it. Anyway, I apologize as I'm not sure this is the right place for this discussion; I recognize this is almost another issue.

**Comment by zenmonkeykstop** [comment]
Closing this issue, as TBB is almost always automatically updated, but will open a new one to investigate moving UA checks server-side.
