### ISSUE TITLE
Make a Contributor's Guide

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#179]
Now that we've been working steadily on this for some time, we've started to develop a set of best practices for developers and contributors to the project. We should codify these in a document to encourage these practices and help contributors avoid common mistakes.

This could be an additional section in [securedrop/HACKING.md](https://github.com/freedomofpress/securedrop/blob/master/securedrop/HACKING.md), or a separate document.

**Comment by garrettr** [comment]
The current contributor's guide is in `docs/develop.md`. We should improve this, and also might want to consider moving it to a more typical location (e.g. `CONTRIBUTING.md`). We also might want to consider moving this to a Github wiki.

**Comment by redshiftzero** [comment]
We have this now in: https://docs.securedrop.org/en/latest/development/getting_started.html. Closing!
