### ISSUE TITLE
Port Tails setup to Ansible logic

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1793]
# Feature request

## Description

The existing setup logic for provisioning Admin and Journalist Workstations is to run the `tails_files/install.sh` script. That script contains about 500 lines of Bash, and contains some tricky grep and sed logic that is difficult to test reliably (which has caused problems in the past, e.g. #1633). The sole reason we're using Bash to configure the Tails environment is that Ansible is only available on the Admin Workstation, but not the Journalist Workstation. Give the tooling presented in #1781 to wrap the Ansible bootstrap logic, this is a fine opportunity to port the Bash logic over to stable Ansible playbooks, so we can make use of DRY vars.

Additionally, much of the logic contained in `tails_files/install.sh` contains legacy cleanup tasks. Due to the Tails 2 -> 3 migration for 0.4 (#1551), Admins must configure new Tails volumes, so much of the legacy cleanup tasks can be removed.

## User Stories

As an Admin, I want to run a single script and configure the Tails environment post-install. The script should understand target workstation roles such as "Admin" and "Journalist" and configure them accordingly.

Relevant issues: #1533, #1176, #1177.

**Comment by conorsch** [comment]
Ported all the Bash logic from `install.sh` to a dedicated Ansible role. Stepping through Tails-based testing now. If all goes smoothly, will update the docs next.

One arguable regression so far is that `install.sh` interactively prompts for the SSH username, whereas the new logic does not, and so omits inclusion of the SSH username in the SSH alises file. Opened #1796 to discuss further.

**Comment by dachary** [comment]
@conorsch this is a bit off-topic but I don't know where such questions should be posted. What is the reason for not making a bootable iso almost identical to tails, with SecureDrop already included ?

**Comment by msheiny** [comment]
@dachary -- there has been an internal debate on that, I also have very similar feelings to you, and have brought this up a couple times. The biggest argument against doing this is that we have to then essentially maintain a fork of `Tails` and over-ride the update the mechanism. There is a long-term goal to evaluate other platforms (experimenting with container focused distributions) where we possibly gain more control and enhanced ability to push out updates but that is at least a year out at this point. 

I will add that personally I'm still on the fence with this idea -- I think if we stick with Tails for the long-run it needs to eventually be done for our sanity but if we convinced another platform is the key I have a hard-time making the argument that the effort is worth the return for the short time-frame.

**Comment by dachary** [comment]
@msheiny thanks for the update :-) I don't have any opinion one way or the other at this point. I was just curious. Is there a communication channel I should read to know about the discussions you mention ?

**Comment by msheiny** [comment]
@dachary -- ill bring this up today (the communication issue). I'd like to open more of our decision making process and communication channels if possible to streamline obtaining help from friendly outside contributors (like yourself).

**Comment by dachary** [comment]
@msheiny oh, that's good news :-)
