### ISSUE TITLE
gpg --recv-key hangs on tails-3.0

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1797]
# Bug

## Description

docs/set_up_admin_tails.rst suggests:

<pre>
    gpg --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"
</pre>

but it hangs and timesout.

## Steps to Reproduce

* Install https://tails-dl.urown.net/tails/stable/tails-amd64-3.0/tails-amd64-3.0.iso with persistence and boot with an admin password.
* Connect to internet (via wifi, no firewall)
* Verify connectivity with sudo apt-get update
* Open a terminal
* $ cat /home/amnesia/.gnupg/dirmngr.conf 
use-tor
keyserver hkp://jirk5u4osbsr34t5.onion
* gpg --debug-all --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"

## Expected Behavior

The key is imported.

## Actual Behavior

gpg: reading options from '/home/amnesia/.gnupg/gpg.conf'
gpg: enabled debug flags: packet mpi crypto filter iobuf memory cache memstat trust hashing ipc clock lookup extprog
gpg: DBG: [not enabled in the source] start
gpg: DBG: chan_3 <- # Home: /home/amnesia/.gnupg
gpg: DBG: chan_3 <- # Config: /home/amnesia/.gnupg/dirmngr.conf
gpg: DBG: chan_3 <- OK Dirmngr 2.1.18 at your service
gpg: DBG: connection to the dirmngr established
gpg: DBG: chan_3 -> GETINFO version
gpg: DBG: chan_3 <- D 2.1.18
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KS_GET -- 0x22245C81E3BAEB4138B36061310F561200F4AD77
gpg: keyserver receive failed: Connection timed out

## Comments

It is entirely possible I'm doing something stupid, this is my first time with tails ;-) I tried --keyserver but gpg would not accept that option.

**Comment by dachary** [comment]
Filed an issue at tails but I have the distinct feeling this is not where it should be reported: https://labs.riseup.net/code/issues/12689

**Comment by redshiftzero** [comment]
Thanks @dachary for this detailed report and for filing the bug upstream. I was able to reproduce this on Tails 3.0 and you are correct that following the docs as written, `pgp --recv-key` does hang. It looks like the issue is with hkp server `jirk5u4osbsr34t5.onion`, e.g.:

```
gpg --keyserver hkp://pool.sks-keyservers.net --recv-key "2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77"
```

works. Will note this on the upstream ticket.

**Comment by dachary** [comment]
@redshiftzero looks like it was a temporary problem now resolved. I updated the upstream ticket and proposed to add a note for the benefit of future SecureDrop installers running into the same issue: https://github.com/freedomofpress/securedrop/pull/1804
