### ISSUE TITLE
Hash algorithm versioning and update mechanism

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#181]
There has been a lot of debate of which hash algorithms (and which parameters of those algorithms) should be use used in Securedrop. However, changing these parameters makes upgrading the system difficult. Existing sources may have their codename hashed with algo/parameter set A. If we upgrade to B, we cannot upgrade the actual stored hash until the source logs in again and provides us with their cleartext codename so we can recompute the hash.

I propose two new features to address this:
1. We need to version the hash being used and store it in the output of the hash function. For example, the default output of bcrypt is `$Vers$log2(NumRounds)$salt+passwd$` ([source](http://code.google.com/p/py-bcrypt/source/browse/bcrypt/bcrypt.c#144)). We would have to extend or customize this to suit or needs, which include other hash functions (scrypt) and their parameters (scrypt has 3).
2. We need to develop an update mechanism. That is, if a deployment or a software upgrade changes the hash function, we need to continue to support the prior hash function and opportunistically upgrade sources as they log in.

Thanks to John Adams for suggesting this.

**Comment by garrettr** [comment]
We currently use scrypt with 14 rounds, which seems sufficient for now. However, it would be good to implement this feature to make potential future upgrades easier.

**Comment by redshiftzero** [comment]
Closing in favor of the more specific #2918
