### ISSUE TITLE
Testinfra tests are skipped in Travis

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1816]
# Bug

## Description

All of the config tests in the Travis CI run are marked as "skipped." There are a few config tests that are not relevant on the Travis host, since that host is a combination of an Ansible controller and the development VM, given the localhost provisioning strategy, but we don't want to skip _everything_.

While working on #1736 and running the config tests locally, I discovered that #1770 broke the development VM config tests by upgrading Python dependencies without touching the config tests. Travis CI should have caught that, but didn't. Note that the pip checks may be one of the config tests we need to skip in Travis, due to the insufficient separation of Python library environments. Still, worth a shot.

## Steps to Reproduce

1. Commit a breaking change in a feature branch.
2. Confirm that `./testinfra/test.py development` fails locally as a result of the breaking change.
3. Push feature branch to remote and see the Travis checks fail.

## Expected Behavior

Config tests run in Travis. If not all of them, then most of them.

## Actual Behavior

No config tests run in Travis. All are marked as "SKIPPED."

## Comments

The `testinfra/test.py` wrapper script has gotten ugly. The solution is either to add a "travis" target to that script, or fix the handling of the "development" target to execute against localhost when running on Travis. It's also possible to execute testinfra directly, bypassing the wrapper, since the default behavior of testinfra is to execute against localhost.

**Comment by msheiny** [comment]
Urggggghh good catch @conorsch

**Comment by dachary** [comment]
I tried this on the vagrant development vm. But it's missing the "testinfra" script. Not sure what I'm missing here.
<pre>
vagrant@development:/vagrant$ ./testinfra/test.py development
Running Testinfra suite against 'development'...
Target roles:
    - testinfra/app-code
    - testinfra/development
testinfra -vv -n auto --connection ansible --ansible-inventory .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory --hosts development testinfra/app-code testinfra/development
Traceback (most recent call last):
  File "./testinfra/test.py", line 135, in <module>
    run_testinfra(target_host)
  File "./testinfra/test.py", line 132, in run_testinfra
    subprocess.check_call(testinfra_command)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
</pre>

**Comment by dachary** [comment]
my bad, I did not realize testinfra was a python module ;-) pip install -r testinfra/requirements.txt helps

**Comment by dachary** [comment]
I tested and got something different locally but still 100% skipped. Not sure if I did something wrong though.

* git cherry-pick refs/pull/1838/head~6..refs/pull/1838/head
* vagrant destroy development
* vagrant up development
* git clean -ffqdx # getting rid of unversionned leftovers
<pre>
$ ./testinfra/test.py development
Running Testinfra suite against 'development'...
Target roles:
    - testinfra/app-code
    - testinfra/development
====================================================== test session starts =======================================================
platform linux2 -- Python 2.7.12, pytest-3.1.1, py-1.4.34, pluggy-0.4.0 -- /home/loic/.virtualenvs/securedrop/bin/python2
cachedir: .cache
rootdir: /home/loic/software/securedrop/securedrop, inifile: setup.cfg
plugins: testinfra-1.6.3, xdist-1.16.0
[gw0] linux2 Python 2.7.12 cwd: /home/loic/software/securedrop/securedrop
[gw1] linux2 Python 2.7.12 cwd: /home/loic/software/securedrop/securedrop
[gw2] linux2 Python 2.7.12 cwd: /home/loic/software/securedrop/securedrop
[gw3] linux2 Python 2.7.12 cwd: /home/loic/software/securedrop/securedrop
[gw4] linux2 Python 2.7.12 cwd: /home/loic/software/securedrop/securedrop
[gw5] linux2 Python 2.7.12 cwd: /home/loic/software/securedrop/securedrop
[gw6] linux2 Python 2.7.12 cwd: /home/loic/software/securedrop/securedrop
[gw7] linux2 Python 2.7.12 cwd: /home/loic/software/securedrop/securedrop
[gw0] Python 2.7.12 (default, Jul  1 2016, 15:12:24)  -- [GCC 5.4.0 20160609]
[gw3] Python 2.7.12 (default, Jul  1 2016, 15:12:24)  -- [GCC 5.4.0 20160609]
[gw1] Python 2.7.12 (default, Jul  1 2016, 15:12:24)  -- [GCC 5.4.0 20160609]
[gw2] Python 2.7.12 (default, Jul  1 2016, 15:12:24)  -- [GCC 5.4.0 20160609]
[gw4] Python 2.7.12 (default, Jul  1 2016, 15:12:24)  -- [GCC 5.4.0 20160609]
[gw6] Python 2.7.12 (default, Jul  1 2016, 15:12:24)  -- [GCC 5.4.0 20160609]
[gw7] Python 2.7.12 (default, Jul  1 2016, 15:12:24)  -- [GCC 5.4.0 20160609]
[gw5] Python 2.7.12 (default, Jul  1 2016, 15:12:24)  -- [GCC 5.4.0 20160609]
gw0 [71] / gw1 [71] / gw2 [71] / gw3 [71] / gw4 [71] / gw5 [71] / gw6 [71] / gw7 [71]
scheduling tests via LoadScheduling

testinfra/app-code/test_haveged.py::test_haveged_no_duplicate_lines[_testinfra_host0] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-[program:securedrop_worker]] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_config_file[_testinfra_host0] 
testinfra/app-code/test_haveged.py::test_haveged_config[_testinfra_host0] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-command=/usr/local/bin/rqworker] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-directory=/vagrant/securedrop] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-autostart=true] 
[gw6] SKIPPED testinfra/app-code/test_haveged.py::test_haveged_config[_testinfra_host0] 
[gw1] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_config_file[_testinfra_host0] 
[gw0] SKIPPED testinfra/app-code/test_haveged.py::test_haveged_no_duplicate_lines[_testinfra_host0] 
[gw2] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-directory=/vagrant/securedrop] 
[gw3] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-command=/usr/local/bin/rqworker] 
[gw5] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-autostart=true] 
testinfra/app-code/test_haveged.py::test_haveged_is_running[_testinfra_host0] 
[gw4] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-[program:securedrop_worker]] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-autorestart=true] 
[gw7] SKIPPED testinfra/app-code/test_haveged.py::test_haveged_is_running[_testinfra_host0] 
[gw6] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-autorestart=true] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-user=vagrant] 
testinfra/app-code/test_securedrop_app_code.py::test_apache_default_docroot_is_absent[_testinfra_host0] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-apparmor-utils] 
[gw1] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-user=vagrant] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-startretries=3] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-environment=HOME="/tmp/python-gnupg"] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-stdout_logfile=/var/log/securedrop_worker/out.log] 
[gw0] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-startretries=3] 
[gw3] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-environment=HOME="/tmp/python-gnupg"] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_sqlite_db[_testinfra_host0] 
[gw2] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_apache_default_docroot_is_absent[_testinfra_host0] 
[gw4] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-stdout_logfile=/var/log/securedrop_worker/out.log] 
[gw5] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-apparmor-utils] 
[gw1] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_sqlite_db[_testinfra_host0] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-haveged] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-secure-delete] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-python-pip] 
[gw0] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-haveged] 
[gw3] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-secure-delete] 
[gw2] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-python-pip] 
testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-stderr_logfile=/var/log/securedrop_worker/err.log] 
[gw7] SKIPPED testinfra/app-code/test_redis_worker.py::test_redis_worker_configuration[_testinfra_host0-stderr_logfile=/var/log/securedrop_worker/err.log] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_test_journalist_key[_testinfra_host0] 
[gw6] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_test_journalist_key[_testinfra_host0] 
testinfra/development/test_development_application_settings.py::test_development_lacks_deb_packages[_testinfra_host0-securedrop-app-code] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-supervisor] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-gnupg2] 
[gw4] SKIPPED testinfra/development/test_development_application_settings.py::test_development_lacks_deb_packages[_testinfra_host0-securedrop-app-code] 
[gw5] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-supervisor] 
[gw1] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-gnupg2] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-python] 
[gw0] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-python] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-sqlite] 
testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-redis-server] 
[gw3] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-sqlite] 
[gw2] SKIPPED testinfra/app-code/test_securedrop_app_code.py::test_securedrop_application_apt_dependencies[_testinfra_host0-redis-server] 
testinfra/development/test_development_application_settings.py::test_development_apparmor_no_complain_mode[_testinfra_host0] 
testinfra/development/test_development_application_settings.py::test_development_apache_docroot_absent[_testinfra_host0-/var/www/html] 
testinfra/development/test_development_application_settings.py::test_development_data_directories_exist[_testinfra_host0-/var/lib/securedrop] 
[gw7] SKIPPED testinfra/development/test_development_application_settings.py::test_development_apparmor_no_complain_mode[_testinfra_host0] 
[gw6] SKIPPED testinfra/development/test_development_application_settings.py::test_development_apache_docroot_absent[_testinfra_host0-/var/www/html] 
[gw4] SKIPPED testinfra/development/test_development_application_settings.py::test_development_data_directories_exist[_testinfra_host0-/var/lib/securedrop] 
testinfra/development/test_development_application_settings.py::test_development_app_directories_exist[_testinfra_host0] 
[gw5] SKIPPED testinfra/development/test_development_application_settings.py::test_development_app_directories_exist[_testinfra_host0] 
testinfra/development/test_development_application_settings.py::test_development_clean_tmp_cron_job[_testinfra_host0] 
[gw1] SKIPPED testinfra/development/test_development_application_settings.py::test_development_clean_tmp_cron_job[_testinfra_host0] 
testinfra/development/test_development_application_settings.py::test_development_default_logo_exists[_testinfra_host0] 
[gw0] SKIPPED testinfra/development/test_development_application_settings.py::test_development_default_logo_exists[_testinfra_host0] 
testinfra/development/test_development_application_settings.py::test_development_lacks_deb_packages[_testinfra_host0-apache2-mpm-worker] 
[gw3] SKIPPED testinfra/development/test_development_application_settings.py::test_development_lacks_deb_packages[_testinfra_host0-apache2-mpm-worker] 
testinfra/development/test_development_application_settings.py::test_development_apache_docroot_absent[_testinfra_host0-/var/www/source.wsgi] 
testinfra/development/test_development_application_settings.py::test_development_data_directories_exist[_testinfra_host0-/var/lib/securedrop/keys] 
[gw2] SKIPPED testinfra/development/test_development_application_settings.py::test_development_apache_docroot_absent[_testinfra_host0-/var/www/source.wsgi] 
testinfra/development/test_development_application_settings.py::test_development_apache_docroot_absent[_testinfra_host0-/var/www/document.wsgi] 
testinfra/development/test_development_application_settings.py::test_development_lacks_deb_packages[_testinfra_host0-libapache2-mod-wsgi] 
[gw6] SKIPPED testinfra/development/test_development_application_settings.py::test_development_lacks_deb_packages[_testinfra_host0-libapache2-mod-wsgi] 
[gw7] SKIPPED testinfra/development/test_development_application_settings.py::test_development_data_directories_exist[_testinfra_host0-/var/lib/securedrop/keys] 
[gw4] SKIPPED testinfra/development/test_development_application_settings.py::test_development_apache_docroot_absent[_testinfra_host0-/var/www/document.wsgi] 
testinfra/development/test_development_application_settings.py::test_development_data_directories_exist[_testinfra_host0-/var/lib/securedrop/tmp] 
testinfra/development/test_development_application_settings.py::test_development_lacks_deb_packages[_testinfra_host0-libapache2-mod-xsendfile] 
testinfra/development/test_development_application_settings.py::test_development_data_directories_exist[_testinfra_host0-/var/lib/securedrop/store] 
[gw0] SKIPPED testinfra/development/test_development_application_settings.py::test_development_data_directories_exist[_testinfra_host0-/var/lib/securedrop/store] 
[gw5] SKIPPED testinfra/development/test_development_application_settings.py::test_development_data_directories_exist[_testinfra_host0-/var/lib/securedrop/tmp] 
[gw1] SKIPPED testinfra/development/test_development_application_settings.py::test_development_lacks_deb_packages[_testinfra_host0-libapache2-mod-xsendfile] 
testinfra/development/test_development_environment.py::test_development_app_dependencies[_testinfra_host0] 
[gw3] SKIPPED testinfra/development/test_development_environment.py::test_development_app_dependencies[_testinfra_host0] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-Flask-Testing-0.6.1] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-Flask-0.11.1] 
[gw2] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-Flask-Testing-0.6.1] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-Jinja2-2.8] 
[gw6] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-Flask-0.11.1] 
testinfra/development/test_development_environment.py::test_development_securedrop_env_var[_testinfra_host0] 
[gw4] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-Jinja2-2.8] 
[gw7] SKIPPED testinfra/development/test_development_environment.py::test_development_securedrop_env_var[_testinfra_host0] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-beautifulsoup4-4.5.1] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-MarkupSafe-0.23] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-Werkzeug-0.11.11] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-click-6.6] 
[gw0] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-beautifulsoup4-4.5.1] 
[gw5] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-MarkupSafe-0.23] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-coverage-4.2] 
[gw2] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-coverage-4.2] 
[gw1] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-Werkzeug-0.11.11] 
[gw3] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-click-6.6] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-first-2.0.1] 
[gw6] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-first-2.0.1] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-funcsigs-1.0.2] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-itsdangerous-0.24] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-mock-2.0.0] 
[gw4] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-itsdangerous-0.24] 
[gw7] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-funcsigs-1.0.2] 
[gw0] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-mock-2.0.0] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-pbr-1.10.0] 
[gw5] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-pbr-1.10.0] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-pip-tools-1.7.0] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-pytest-cov-2.4.0] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-py-1.4.31] 
[gw2] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-pytest-cov-2.4.0] 
[gw3] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-py-1.4.31] 
[gw1] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-pip-tools-1.7.0] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-pytest-3.0.3] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-selenium-2.53.6] 
[gw6] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-pytest-3.0.3] 
testinfra/development/test_development_networking.py::test_development_iptables_rules[_testinfra_host0] 
testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-six-1.10.0] 
[gw4] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-selenium-2.53.6] 
[gw0] SKIPPED testinfra/development/test_development_networking.py::test_development_iptables_rules[_testinfra_host0] 
[gw7] SKIPPED testinfra/development/test_development_environment.py::test_development_pip_dependencies[_testinfra_host0-six-1.10.0] 
testinfra/development/test_xvfb.py::test_xvfb_apt_dependencies[_testinfra_host0-xvfb] 
testinfra/development/test_xvfb.py::test_xvfb_service_running[_testinfra_host0] 
testinfra/development/test_xvfb.py::test_xvfb_service_config[_testinfra_host0] 
testinfra/development/test_xvfb.py::test_xvfb_display_config[_testinfra_host0] 
testinfra/development/test_development_networking.py::test_development_ssh_listening[_testinfra_host0] 
[gw3] SKIPPED testinfra/development/test_xvfb.py::test_xvfb_service_config[_testinfra_host0] 
[gw7] SKIPPED testinfra/development/test_xvfb.py::test_xvfb_service_running[_testinfra_host0] 
[gw0] SKIPPED testinfra/development/test_xvfb.py::test_xvfb_apt_dependencies[_testinfra_host0-xvfb] 
testinfra/development/test_development_networking.py::test_development_redis_worker[_testinfra_host0] 
[gw5] SKIPPED testinfra/development/test_development_networking.py::test_development_ssh_listening[_testinfra_host0] 
testinfra/development/test_xvfb.py::test_xvfb_service_enabled[_testinfra_host0] 
testinfra/development/test_xvfb.py::test_xvfb_apt_dependencies[_testinfra_host0-firefox] 
[gw4] SKIPPED testinfra/development/test_xvfb.py::test_xvfb_display_config[_testinfra_host0] 
[gw2] SKIPPED testinfra/development/test_development_networking.py::test_development_redis_worker[_testinfra_host0] 
[gw6] SKIPPED testinfra/development/test_xvfb.py::test_xvfb_service_enabled[_testinfra_host0] 
[gw1] SKIPPED testinfra/development/test_xvfb.py::test_xvfb_apt_dependencies[_testinfra_host0-firefox] 

======================================================== warnings summary ========================================================
None
  Module already imported so can not be re-written: testinfra

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================================= 71 skipped, 1 warnings in 2.11 seconds =============================================
</pre>

**Comment by conorsch** [comment]
@dachary That's very odd behavior you're seeing, let me try to reproduce locally. First, let me mention that #1838, where you're plucking the changes from, does _not_ close this issue (#1816)—another forthcoming PR will do so. Still, you should indeed be able to run the development tests locally. 

Make sure you're executing `./testinfra/test.py development` from your host machine, _not_ from within the development VM itself. From your recent comments, it seems you've already read through the [config test docs](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html), but I share them again not in the spirit of "RTFM," but rather, "These docs are very new, might not be entirely clear, and fresh eyes are welcome on them!"

**Comment by fowlslegs** [comment]
> Make sure you're executing ./testinfra/test.py development from your host machine, not from within the development VM itself.

Was about to post this. Thinking that's the problem. Maybe this could be more clear in the docs?

>  but I share them again not in the spirit of "RTFM," but rather, "These docs are very new, might not be entirely clear, and fresh eyes are welcome on them!"

Also, in general, make sure you're reading from the "latest" and not "stable" branch @dachary for development work and vice-versa if you're going to do a hardware install.

**Comment by dachary** [comment]
@conorsch you guessed right: I was indeed confused about where testinfra should run :-) I'll wait for the PR fixing #1816.

**Comment by dachary** [comment]
> Was about to post this. Thinking that's the problem. Maybe this could be more clear in the docs?

The docs are crystal clear in that regard. My confusion comes from a general misunderstanding of the relationships between the various components. I'm not sure that can be trivially fixed other than learning Vagrant & ansible basics.
