### ISSUE TITLE
Fix bs4 pytest HTML parser warning

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1820]
# Bug

## Description

I spotted this pytest warning on a recent Travis build. Seems like a quick fix to get this resolved.

```
test_integration.py::TestIntegration::test_delete_collection
  /usr/local/lib/python2.7/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
  
  The code that caused this warning is on line 11 of the file /usr/local/bin/pytest. To get rid of this warning, change code that looks like this:
  
   BeautifulSoup(YOUR_MARKUP})
  
  to this:
  
   BeautifulSoup(YOUR_MARKUP, "html5lib")
  
    markup_type=markup_type))
-- Docs: http://doc.pytest.org/en/latest/warnings.html
```

**Comment by conorsch** [comment]
>  Seems like a quick fix to get this resolved.

Famous last words. 😉 I suggest we remove this from the 0.4 milestone and revisit post QA for 0.4.

**Comment by fowlslegs** [comment]
> Famous last words. :wink:

Well I did fix it. Two ways in fact. They just weren't the best ways.

https://github.com/freedomofpress/securedrop/pull/1829/commits/c27c55112f826d66e332c94775575415b8334838 (adds the missing `</a>` tag) should make it into 0.4.

Additionally, if the problems with `html.parser` cannot be resolved in the near-term, then we should add `html5lib` to our test dependencies instead of depending on the app version, if only a stopgap measure until we can switch to the more strict standard library parser.
