### ISSUE TITLE
Remove web application pidfiles

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1821]
The original `./manage.py` commands to manage starting and stopping web application servers in the development environment used pidfiles to manage the lifetime of those process (see #458). When this function of `./manage.py` was rewritten in #1016, the pidfiles became redundant, but the code related to them was not cleaned up.

The following code should be removed:

1. `write_pidfile` in both `source.py` and `journalist.py`
2. `config.{SOURCE,JOURNALIST}_PIDFILE`

Note that the `WORKER_PIDFILE` is still necessary and should not be touched.

Note that the production deployment story for changes to the web application configuration (`config.py`) is currently fraught. There are several potential issues to look out for, although I cannot recall them off the top of my head. The production deployment aspect of this issue deserves careful consideration before merge/deployment.

**Comment by dachary** [comment]
I did the easy part of the work at https://github.com/freedomofpress/securedrop/pull/1822 and I would appreciate pointers to verify / do the right thing after modifying config.py. Thanks !

**Comment by dachary** [comment]
@garrettr existing installations may have pid files but they are not used. The config.py.example now contains no *_PIDFILE variables and the next time it is used by install_files/ansible-base/roles/app/tasks/initialize_securedrop_app.yml and copied to config.py that will create a config.py file without *_PIDFILE. Existing config.py will still have *_PIDFILE and they will not be removed, they will just not be used anywhere. I did not find tests verifying all config.py.example variables are in the config.py or any other kind of consistency check of the kind. The existing pidfiles are in the /tmp directory and will be cleaned up after the next reboot.

You mentionned that "the production deployment story for changes to the web application configuration (config.py) is currently fraught. " and I probably missed something. Would you be so kind as to point me to a file or an example so I can better understand what is at stake ?

**Comment by fowlslegs** [comment]
> You mentionned that "the production deployment story for changes to the web application configuration (config.py) is currently fraught. " and I probably missed something. Would you be so kind as to point me to a file or an example so I can better understand what is at stake ?

Hopefully you'll get an answer here or in response to https://github.com/freedomofpress/securedrop/pull/1822#issuecomment-309488035.

**Comment by dachary** [comment]
I believe this has been addressed with https://github.com/freedomofpress/securedrop/pull/1822, please re-open if you disagree.
