### ISSUE TITLE
Stablize AWS / CircleCI CI Builds

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1825]
# Bug

## Description

Occasionally the CircleCI staging run will fail during the provisioning step of the build on the [Wait for EC2 instances to boot](https://github.com/freedomofpress/securedrop/blob/develop/devops/playbooks/aws-ci-startup.yml#L133) task. This step attempts to connect to port 22 on both ec2 boxes (`app` and `mon`) from the circleci environment to check whether SSH is up. 

## Steps to Reproduce

Unable to exactly produce but this is seen in a number of recent random builds:
* https://circleci.com/gh/freedomofpress/securedrop/526
* https://circleci.com/gh/freedomofpress/securedrop/523
* https://circleci.com/gh/freedomofpress/securedrop/506

## Expected Behavior

The CI servers should spin up and be available on port 22 from the POV of the circleci builder.

## Actual Behavior

In each of scenario it seems either one or both of the AWS servers are unavailable over port 22 and the task times out and the servers are torn down. The job will error without much fanfare (but a lot of distracting ansible output). An example looks something like this:

```
TASK [Create custom temporary security_group for CI hosts.] ********************
changed: [localhost]

TASK [Create remote CI hosts on AWS.] ******************************************
changed: [localhost] => (item={u'server_type': u'mon-staging'})
changed: [localhost] => (item={u'server_type': u'app-staging'})

TASK [Wait for EC2 instances to boot.] *****************************************
failed: [localhost] (item={'_ansible_parsed': True, u'changed': True, '_ansible_no_log': False, u'instances': 
[...]
"msg": "Timeout when waiting for ec2-54-219-170-84.us-west-1.compute.amazonaws.com:22"}
ok: [localhost] => (item={'_ansible_parsed': True, u'changed': True, '_ansible_no_log': False, u'instances': 
[..] )
	to retry, use: --limit @/root/sd/devops/playbooks/aws-ci-startup.retry

PLAY RECAP *********************************************************************
localhost                  : ok=12   changed=7    unreachable=0    failed=1   

make[2]: Entering directory '/root/sd'
./devops/scripts/ci-teardown.sh
+ . devops/ansible_env
++ '[' -z 506 ']'
++ [[ 506 == \$\{* ]]
++ export RETRY_FILES_ENABLED=False
++ RETRY_FILES_ENABLED=False
++ export ANSIBLE_INVENTORY=./devops/inventory/staging
++ ANSIBLE_INVENTORY=./devops/inventory/staging
++ export 'ANSIBLE_SSH_ARGS=-F /root/.ssh/sshconfig-securedrop-ci-506 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
++ ANSIBLE_SSH_ARGS='-F /root/.ssh/sshconfig-securedrop-ci-506 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
+ export ANSIBLE_INVENTORY=localhost
+ ANSIBLE_INVENTORY=localhost
+ export RETRY_FILES_ENABLED=False
+ RETRY_FILES_ENABLED=False
+ '[' '!' -f /root/.FPF_CI_DEBUG ']'
+ ./devops/playbooks/aws-ci-teardown.yml --diff
 [WARNING]: Host file not found: localhost
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [Destroy docker CI containers.] *******************************************

```

## Comments

So there are two things we need to address here:
* The current ansible output is super unhelpful and verbose (note that I cut through `A BUNCH` of output data above to get to that mess).  The goal in scrolling through the CI output should be to quickly parse the data to find an error or confirm something. One idea to severely curtail the stdout/stderr output and send the full log as an artifact that can be extracted from CircleCI's UI. 
* To actually address the issue, we should have a retry mechanism to actually retry the spin-up portion a few times if it is unable to connect. This prevents someone from having to go in and manually take action. This logic might get a little tricky -- going to have to do some more research here.

**Comment by msheiny** [comment]
Heyyyy team - I think this is a good candidate for the `0.4.1` milestone. Its annoying but its happening infrequently enough that I dont consider it a blocker for `0.4` release. If anyone disagrees with that assertion - we can hash it out here and I'll be happy to re-prioritize.

**Comment by conorsch** [comment]
@msheiny Agreed that 0.4.1 is appropriate. I don't mind clicking the **Rebuild** button in order to keep going as we come down the home stretch on the 0.4 release.
