### ISSUE TITLE
Full test coverage for external contributions

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1826]
Our automatic CI currently only achieves partial coverage for external contributions (defined as pull requests created from a branch on a forked remote, not the origin). Specifically, all tests except for the CircleCI test suite are run automatically. This is because there are security concerns related to automatically running arbitrary code on some of our CircleCI-related infrastructure.

Since the only tests that do not automatically run are the CircleCI tests, we have full test coverage for everything except the [configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html), which only run on CircleCI.

Unfortunately, this makes it difficult for maintainers to apply due diligence to external contributions before merging them. Ideally, every pull request would satisfy the invariant "If it was merged, it passed **all** of the tests." Satisfying this invariant makes debugging and reasoning about regressions _much_ easier.

## Long-term resolution

We have some ideas for how to fix this, which are being tracked on a private issue tracker internal to the Freedom of the Press Foundation. This public issue is meant to serve as a placeholder to provide some transparency regarding this situation; it will be updated as progress is made on the issue internally.

## Short-term mitigation

In the meantime, maintainers have one of two choices for performing due diligence on external contributions before merge:

1. If the partial automatic CI passes, and the PR is small and/or unlikely to break the configuration tests, you may merge without running the CircleCI tests. To do so: temporarily disable the [CircleCI status check requirement](https://github.com/freedomofpress/securedrop/settings/branches/develop), merge the external contribution, then re-enable the CircleCI status check requirement.
2. Otherwise, you should run the CircleCI tests. To do so:
    1. Review the contribution and ensure that it does not attempt to do anything malicious once it is running on our CI infrastructure.
    2. Checkout the branch from the fork's remote locally, then push it to the origin remote.
    3. Create a new pull request for the branch you pushed to the origin. The action of creating a new pull request is what triggers the full CI test suite to run.
    4. Comment on the original PR with a link to the temporary PR, explaining why it was created.
    5. Once you have confirmed the full test suite is passing, merge the original PR, then close the temporary PR.

**Comment by redshiftzero** [comment]
Given #2070, from now on we should only use Option 2 to merge PRs from forks. That is, we should pull the changes into another PR so that the full CI suite can run before merging.

**Comment by conorsch** [comment]
I propose we pull the lever and start building all forked PRs by default:

![help-us-circleci-you re-our-only-hope](https://user-images.githubusercontent.com/657862/28949172-d6f97dea-786f-11e7-9b65-05001696c198.png)

The benefit far outweighs the cost of guarding our narrowly scoped API credentials from getting sniffed by malicious would-be contributors. Rotating the API keys is not difficult, and folks won't be able to rack up much of a bill before we catch them. 

@msheiny What say you?

**Comment by msheiny** [comment]
> cost of guarding our narrowly scoped API

The permissions scoping for AWS is kind of weird -- some of the actions support very granular permissions where as others don't. Basically - I'm hesitant to do this Becaaaaausseeeee of:

> folks won't be able to rack up much of a bill before we catch them.

^ Is that true? I just can't say that with certainty until we enable better alerting for AWS activity. I agree the likely is low but we are openly in a public forum talking about it so there is that 😬  Heh. Lets sync out-of-band on this one 👍

**Comment by msheiny** [comment]
The PR fork gate has been lifted 😬
