### ISSUE TITLE
vagrant up app-staging : No module named six

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1841]
# Bug

## Description

Following the instructions from **docs/development/virtual_environments.rst**

<pre>
$ vagrant up app-staging
...
 _______________________________________________________
/ TASK [build-securedrop-app-code-deb-pkg : Install pip \
\ wheel.]                                               /
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [build] => {"changed": false, "cmd": "/usr/bin/pip install wheel", "name": "wheel", "requirements": null, "state": "present", "stderr": "", "stdout": "Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python2.7/dist-packages\nCleaning up...\n", "stdout_lines": ["Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python2.7/dist-packages", "Cleaning up..."], "version": null, "virtualenv": null}
Unexpected Exception: No module named six
to see the full traceback, use -vvv
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
</pre>

I'm able to ssh but
<pre>
$ vagrant ssh app-staging
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-117-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Fri Jun 16 22:24:00 UTC 2017

  System load:  0.67              Processes:           99
  Usage of /:   2.7% of 38.02GB   Users logged in:     0
  Memory usage: 7%                IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

vagrant@app-staging:~$ sudo su
root@app-staging:/home/vagrant# cd /var/www/securedrop
bash: cd: /var/www/securedrop: No such file or directory
root@app-staging:/home/vagrant# 
</pre>

**Comment by dachary** [comment]
trying again now, hoping this was some kind of environmental mistake on my part

**Comment by dachary** [comment]
same failure, the full log is at https://paste2.org/MFJM1UvX

**Comment by fowlslegs** [comment]
Can you try again, this time following the instructions to a 't'? It doesn't look like you have a virtualenv activated with our development dependencies on your host and it doesn't look like you're running the right commands to bring up the `staging` environment hosts.

```
sudo apt-get install virtualenvwrapper
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
mkvirtualenv -p /usr/bin/python2 securedrop
pip install -r securedrop/requirements/develop-requirements.txt
```

-- https://docs.securedrop.org/en/latest/development/getting_started.html#ubuntu-debian

```
vagrant up --no-provision build
vagrant up /staging/
vagrant ssh app-staging
sudo su
cd /var/www/securedrop
```

-- https://docs.securedrop.org/en/latest/development/virtual_environments.html#staging

**Comment by dachary** [comment]
I reset everything and followed the instructions again and it worked. Sorry for the noise. What confused me is that the error seemed to come from the staging machine provisioning itself. It looks like the provisioning of the vagrant machine actually uses the python from the host instead. Still a bit lost regarding what happens where. Thanks for your patience.
