### ISSUE TITLE
manage: clean-tmp races against get_bulk_archive

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1849]
# Bug

## Description

**./manage clean-tmp** races against get_bulk_archive

## Steps to Reproduce

* In the app-staging VM (the development server of werkzeug does not support X-Sendfile and won't reproduce the race)
* modify the journalist.py download function like so:
<pre>
def download(zip_basename, submissions):
    """Send client contents of zipfile *zip_basename*-<timestamp>.zip
    containing *submissions*. The zipfile, being a
    :class:`tempfile.NamedTemporaryFile`, is stored on disk only
    temporarily.

    :param str zip_basename: The basename of the zipfile download.

    :param list submissions: A list of :class:`db.Submission`s to
                             include in the zipfile.
    """
    zf = store.get_bulk_archive(submissions,
                                zip_directory=zip_basename)
    attachment_filename = "{}--{}.zip".format(
        zip_basename, datetime.utcnow().strftime("%Y-%m-%d--%H-%M-%S"))

    # Mark the submissions that have been downloaded as such
    for submission in submissions:
        submission.downloaded = True
    db_session.commit()

    r = send_file(zf.name, mimetype="application/zip",
                     attachment_filename=attachment_filename,
                     as_attachment=True)
    del zf
    import time
    time.sleep(30)
    return r
</pre>
* Download a collection from the journalist interface
* After a file shows up in /var/lib/securedrop/tmp 
* ./manage clean-tmp
* Apache will fail to find the file path created by get_bulk_archive (the path is found in the X-Sendfile header)
* /var/log/apache2/journalist-error.log will show an error looking like this:
<pre>
[Fri Aug 25 11:03:20.596664 2017] [:info] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020] mod_wsgi (pid=3259, process='journalist', application='app-staging:8080|'): Loading WSGI script '/var/www/journalist.wsgi'.
[Fri Aug 25 11:03:51.168580 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020] [2017-08-25 11:03:51,154] ERROR in app: Exception on /col/process [POST]
[Fri Aug 25 11:03:51.168672 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020] Traceback (most recent call last):
[Fri Aug 25 11:03:51.168693 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
[Fri Aug 25 11:03:51.168711 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     response = self.full_dispatch_request()
[Fri Aug 25 11:03:51.168729 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
[Fri Aug 25 11:03:51.168746 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     rv = self.handle_user_exception(e)
[Fri Aug 25 11:03:51.168762 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
[Fri Aug 25 11:03:51.168778 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     reraise(exc_type, exc_value, tb)
[Fri Aug 25 11:03:51.168793 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
[Fri Aug 25 11:03:51.168810 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     rv = self.dispatch_request()
[Fri Aug 25 11:03:51.168854 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
[Fri Aug 25 11:03:51.168871 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     return self.view_functions[rule.endpoint](**req.view_args)
[Fri Aug 25 11:03:51.168886 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/var/www/securedrop/journalist.py", line 89, in wrapper
[Fri Aug 25 11:03:51.168901 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     return func(*args, **kwargs)
[Fri Aug 25 11:03:51.168915 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/var/www/securedrop/journalist.py", line 548, in col_process
[Fri Aug 25 11:03:51.168929 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     return method(cols_selected)
[Fri Aug 25 11:03:51.168943 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/var/www/securedrop/journalist.py", line 572, in col_download_all
[Fri Aug 25 11:03:51.168958 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     return download("all", submissions)
[Fri Aug 25 11:03:51.168972 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/var/www/securedrop/journalist.py", line 792, in download
[Fri Aug 25 11:03:51.168988 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     as_attachment=True)
[Fri Aug 25 11:03:51.169002 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 544, in send_file
[Fri Aug 25 11:03:51.169016 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     fsize = os.path.getsize(filename)
[Fri Aug 25 11:03:51.169031 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]   File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
[Fri Aug 25 11:03:51.169049 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020]     return os.stat(filename).st_size
[Fri Aug 25 11:03:51.169069 2017] [:error] [pid 3259:tid 3087374333696] [remote 127.0.0.1:45020] OSError: [Errno 2] No such file or directory: '/var/lib/securedrop/tmp/tmp_securedrop_bulk_dl_QLYC7z'
[Fri Aug 25 11:03:58.116025 2017] [:info] [pid 3258:tid 3087374976768] mod_wsgi (pid=3258): Create interpreter 'app-staging:8080|'.
[Fri Aug 25 11:03:58.117313 2017] [:info] [pid 3258:tid 3087374976768] mod_wsgi (pid=3258): Adding '/var/www/securedrop' to path.
[Fri Aug 25 11:03:58.117892 2017] [:info] [pid 3258:tid 3087374976768] [remote 127.0.0.1:45020] mod_wsgi (pid=3258, process='journalist', application='app-staging:8080|'): Loading WSGI script '/var/www/journalist.wsgi'.
</pre>

## Expected Behavior

./manage clean-tmp never races against get_bulk_archive

## Actual Behavior

There is a window of opportunity for **./manage clean-tmp** to remove a file and fail a download

## Comments

This is unlikely but possible. The current safeguard only addresses part of the race. It should remove files older than X days instead.

**Comment by redshiftzero** [comment]
Just tried to reproduce this and I'm not seeing the same behavior, here are the steps I took following your instructions:

1. Insert `sleep(300)` at line 95 at `store.py` in `get_bulk_archive` before return:

```
                ))
    import time; time.sleep(300)
    return zip_file
```

2. Download a collection of submissions

3. In another terminal `sudo ./manage.py clean-tmp` a few seconds later

The download completes, `./manage.py clean-tmp` completes and I don't get any errors. I played around a bit with the timing between hitting download and cleaning the tempdir but I must be missing something - are any steps missing above?

**Comment by dachary** [comment]
I'll repeat and update the reproducer.

**Comment by dachary** [comment]
@redshiftzero I updated the reproducer in the issue description. I should have been more precise. Two points were missing

* it needs to be tested with staging (because there is no X-Sendfile handling in the dev environment)
* the sleep time should be 30 seconds otherwise things will timeout

**Comment by dachary** [comment]
@redshiftzero it turns out the race exists but is semi-magically resolved. I tested with rm instead of ./manage.py clean-tmp ... my bad. Looking at the code there is absolutely no guarantee the file stays open. I think it is because the python variable is not garbage collected immediately and the open zip file survives the call to get_bulk_archive.

**Comment by dachary** [comment]
@redshiftzero after further investigation the root of the race is the lifetime of the zf variable in the download function. I must admit this is a very small window of opportunity and probably was not worth the time I spent on it ;-) However, now that there is a reproducer I think it is worth fixing. Because it will be extraordinarily difficult to diagnose when/if it happens for real.

I think the **del zf** in the reproducer is not introducing a bias: as soon as the function returns the zf variable is illegible for garbage collection.

Although this is an interesting issue once you're deep enough into it, there is no real urgency in resolving it. It can wait a few weeks: it won't go anywhere ;-)

**Comment by heartsucker** [comment]
>  I think it is because the python variable is not garbage collected immediately and the open zip file survives the call to get_bulk_archive.

As a note, even calling `f.flush(); f.close()` and sleeping or doing other things don't trigger this file to be marked as closed. I spent too long trying to get this to work.
