### ISSUE TITLE
Point developers to the 'latest' branch of our documentation

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1856]
Generally speaking, developers should be working from the `latest` branch of our documentation, while `stable` should be used for production installs. If we add a note to this extent to our `development` git branch, then it will be included in our `latest` branch immediately (not very helpful), and our `stable` branch as well once we've signed and pushed a `0.4` tag (helpful). The beginning of the developer documentation seems like the best place for such a note.

**Comment by conorsch** [comment]
Ideally this will change once we start releasing more frequently (post-0.4), but as of today the intent described above is very much true. Documenting it publicly would save us all of lot of typing in terms of recommending to developers that the use the `latest` branch.
