### ISSUE TITLE
journalist: admin/reset-2fa-hotp gracefully handle formatting errors

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1869]
# Bug

## Description

In admin/reset-2fa-hotp, when the token is not properly formatted (odd
number of characters, non hexa character), a python trace is displayed
to the user.

## Steps to Reproduce

* loggin as a journalist admin
* click on reset hardware token (goes to admin/reset-2fa-hotp)
* type zz for the token

## Expected Behavior

An error message because Z is not an hexadecimal character

## Actual Behavior

A python traceback that displays an error message about the fact that there is non hexadecimal number

![before](https://user-images.githubusercontent.com/433594/27391047-2a4dceae-56a3-11e7-8672-521578d634a9.png)

## Comments

An error message would be more user friendly, typo are common

**Comment by redshiftzero** [comment]
Thanks for this excellent report @dachary! You're right that we should gracefully handle this case. The only thing to add is that the traceback will only be shown in the development environment - in staging and production, the error will appear like this:

![screen shot 2017-06-26 at 2 38 00 pm](https://user-images.githubusercontent.com/7832803/27561515-498aa520-5a7d-11e7-8840-db9a758227b3.png)
