### ISSUE TITLE
Improve handling of the systemd docker CI image

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1877]
# Improve management of CI docker image

## Description

The current docker CI image that is based on jessie and has systemd mixed in resides on a personal docker hub account of mine. It is also not pegged to a specific version. Both of these problems do not lend well for future maintenance of the image and do not probably control for uncertainty in the build/CI process down the road.

To improve this, we should move the image to an organization owned container repo and also peg the digest hash in git for better image tracking. The description for the repo page should also make note of what Dockerfile/repo the image was built from.

## User Stories

As a developer, I want more assurance regarding the stability of the docker image that is utilized to test building deb packages and that is run in CI. Knowing it's origin is also important to me for debugging purposes.

**Comment by conorsch** [comment]
See @dachary's comments here for proposed changes to the CircleCI container image: https://github.com/freedomofpress/securedrop/pull/2220#issuecomment-326132973
