### ISSUE TITLE
Source interface should render well with right-to-left text

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1884]
In order to localize SecureDrop's source interface in locales with text written right-to-left (e.g. Arabic), we need to verify the CSS + templates on the source interface render well with the text and labels written with right-to-left text.

Relevant tickets: #1168 #1851 #127

**Comment by heartsucker** [comment]
Possibly related: #1357

**Comment by redshiftzero** [comment]
Done in #2343, file more specific followup issues if necessary
