### ISSUE TITLE
Wordlists are not being parsed correctly

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1900]
# Bug

## Description

`crypo_util.{words,nouns,adjectives}` all contain an empty string as their last element.

**Comment by conorsch** [comment]
Not convinced this should be on the 0.4 milestone. What's the severity here? How long has the bug been present? Has the bug ever shipped in a release, or is in develop-only?

**Comment by fowlslegs** [comment]
> What's the severity here?

Sources can be given shorter than 7 word codenames, which would make it easier to guess, reducing security. The [probability mass function](https://en.wikipedia.org/wiki/Binomial_distribution#Probability_mass_function) informs of us of the probabilities of picking the empty string 1, 2, ..., 7 times out of 7.

```
% cat pmf.py
import math

def binomial_coefficient(n, k):
    return math.factorial(n) / (math.factorial(k) * math.factorial(n - k))

def probabilty_mass_function(k, n, p):
    return binomial_coefficient(n, k) * (p ** k) * ((1 - p) ** (n - k))

for num_words_missing in range(1, 8):
    print(probabilty_mass_function(num_words_missing, 7.0, 1.0/7603))

% python pmf.py
0.000919962867408
3.63047698267e-07
7.95947773101e-11
1.04702416877e-14
8.2638055941e-19
3.62352257919e-23
6.80934073588e-28
```

Journalist codenames for sources could contain 1 or 0 words instead of 2.

> How long has the bug been present? Has the bug ever shipped in a release, or is in develop-only?

Had to break out the pickaxe for this one it's such an old bug... On January 7, 2012 Aaron committed it in `707a1bdf`.

**Comment by redshiftzero** [comment]
Just as a clarifying note: the generation of the source codename in `crypto_util.genrandomid` is just taking 8 (`DEFAULT_WORDS_IN_RANDOM_ID`) independent draws from the word list. The probability of a single null string being drawn from the wordlist is 1 in 7603 (~1.3e-4). Thus the probability of one of the 8 words in a given codename being the null string is 1e-3, or 0.1%. So pretty unlikely, but worth fixing.

**Comment by fowlslegs** [comment]
8 is the default argument, but in the application code `genrandomid()` always gets called with 7. See https://github.com/freedomofpress/securedrop/blob/develop/securedrop/source.py#L135 and https://github.com/freedomofpress/securedrop/blob/develop/securedrop/db.py#L89.

`genrandomid()` is actually only called with the default argument in our unit tests. It might be good to remove the global `crypto_util.DEFAULT_WORDS_IN_RANDOM_ID` and the change `genrandomid()` to take a positional argument to clear up this confusion. Then we just pass `db.Source.NUM_WORDS` in calls to `genrandomid()` in our unit tests.
