### ISSUE TITLE
Multiple KeePassX Database Templates

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1930]
# Feature request

## Description

We currently provide a single database template to SecureDrop admins for them to use to distribute credentials to both admin and journalist users. Since the set of credentials one provides to journalist and admin users is different, it would be more convenient to provide two database templates: one for each user role. [Suggestion](https://github.com/freedomofpress/securedrop/issues/1831#issuecomment-309925725) by @fowlslegs.  

## User Stories

As an admin, I should have a KeePassX template for each role so that I clearly understand which credentials should be distributed to each type of user.

**Comment by edenemmanuel** [comment]
Worth launching an investigation. We should probably write associated documentation for admins and how to talk to journalists about usage.

**Comment by redshiftzero** [comment]
Yep definitely some additional documentation on how to set up and use each KeePassX is warranted. The docs are pretty light in general in that area.

**Comment by eloquence** [comment]
Removing this from 7/25-8/8 sprint; let's focus on getting the one docs PR we have open to the finish line.

**Comment by conorsch** [comment]
The password database template is mostly useful for Admins, given how many credentials they have to track. For journalists, it's fine to use a blank password database to get started, given the comparatively low number creds (username/password, transfer device, possibly svs). So, while we may update our guidance during new installs, there's no need to prepare multiple templates for pw management.
