### ISSUE TITLE
Update version script must target correct filenames

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1942]
# Bug

## Description

The `update_version.sh` script is used by SecureDrop maintainers to bump the version prior to building Debian packages slated for release via the apt repo. (Right now we're building rc debs for 0.4, see #1940.) The update script is supposed to target all the locations of hardcoded version strings in the git repo that should be incremented. There are at least two cases where the script falls down:

1. the "securedrop" group_vars file
2. testinfra/vars/ config test version string is not updated

## Steps to Reproduce

1. Execute the `update_version.sh` script with an example version string, e.g. `update_version.sh 0.4-rc1`. 

## Expected Behavior

Script proceeds merrily along, greasing the wheels on the release train.

## Actual Behavior

Script fails because it cannot find the non-existent file `install_files/ansible-base/group_vars/securedrop.yml`.

## Comments

For 1), the fix is straightforward, and _should_ have been included in #1838): 

```
--- a/update_version.sh
+++ b/update_version.sh
@@ -39,7 +39,7 @@ sed -i "s/^\(Version: [0-9.]\++\).*/\1$NEW_VERSION/" install_files/securedrop-os
 sed -i "s/^\(Version: [0-9.]\++\).*/\1$NEW_VERSION/" install_files/securedrop-keyring/DEBIAN/control

 # Update the version used by Ansible for the filename of the output of the deb building role
-sed -i "s/^\(securedrop_app_code_version: \"\).*/\1$NEW_VERSION\"/" install_files/ansible-base/group_vars/securedrop.yml
+sed -i "s/^\(securedrop_app_code_version: \"\).*/\1$NEW_VERSION\"/" install_files/ansible-base/group_vars/all/securedrop
```

For 2), no failures are generated, but it'd be nice if the update process were automatic.

**Comment by redshiftzero** [comment]
Closed by #1945
