### ISSUE TITLE
Prod Vagrant VMs don't receive correct group membership

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1943]
# Bug

## Description

Provisioning prod VMs fails because the group membership is wrong, and the `hosts: securedrop` play target matches nothing.

## Steps to Reproduce

1. `vagrant destroy -f /prod/`
2. `ANSIBLE_ARGS="--skip-tags validate" vagrant up /prod/`

## Expected Behavior

Provisioning proceeds at least until the installation of the `securedrop-app-code` deb package (at which point it will fail unless you're using rc debs for 0.4).

## Actual Behavior

Provisioning fails immediately with no successful tasks, because the first play targeted was the Monitor Server configuration play, since that is the first play referencing a host target other than "localhost" or "securedrop" (which is a group of both servers).

## Comments

This patch applied to the Vagrantfile will resolve:

```
index 543b0888..36c7f978 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -124,10 +124,11 @@ Vagrant.configure("2") do |config|
       ansible.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
       # Taken from the parallel execution tips and tricks
       # https://docs.vagrantup.com/v2/provisioning/ansible.html
-      ansible.limit = 'all'
+      ansible.limit = 'all,localhost'
       ansible.groups = {
         'securedrop_application_server' => %w(app-prod),
         'securedrop_monitor_server' => %w(mon-prod),
+        'securedrop' => %w(app-prod mon-prod)
       }
     end
   end
```

There are two changes there:

* limit (required to get the localhost target to run)
* securedrop group (which in Tails/prod is handled by the dynamic inventory script #1774), but for non-Tails testing (e.g. virtualbox on mac), must be duplicated in the vagrantfile config.

**Comment by redshiftzero** [comment]
Fixed in #1946, closing
