### ISSUE TITLE
Docs improvements to the HTTPS config

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1944]
# Feature request

## Description

Received feedback out-of-band regarding the HTTPS on the Source interface docs (#1928). Summarizing here for implementation during the next docs sprint:

* [x] Make sure to include a link directly to DigiCert's docs on the process: https://www.digicert.com/blog/ordering-a-onion-certificate-from-digicert/
* [x] The validation page DigiCert will ask ask Admins to host must be accessible at `<onion_url>.onion/.well-known/pki-validation.html`.
* [x] State the 12-month max on Onion certs. Some orgs have managed to wrangle longer certs (15 months), but it took a lot of back-and-forth, and involved surprise revocations. Sticking with the 12-month max seems wise.
* [x] Encourage Patience in the docs. Since Onion certs are not yet common, the DigiCert team may try to adhere to inapplicable procedures, e.g. trying to verify an email sent to the WHOIS contacts for the domain (which won't work for Onion URLs).

Then, separate from the list above, but important in light of #1941, we should:

* [x] Explain the OCSP concerns, reference the #1941 issue, and state that we're working on improving the HTTPS config going forward.

## User Stories

As an Admin, I want to read through a frank accounting of the process to roll out HTTPS for my SecureDrop instances, so that I am informed about the trade-offs and complications involved with the switch.

**Comment by garrettr** [comment]
> Make sure to include a link directly to DigiCert's docs on the process

There is already a [link](https://github.com/freedomofpress/securedrop/blame/400240b608e8a5db5ab9e8e81c0af947a81be673/docs/https_source_interface.rst#L32-L37) to Digicert's docs in the current documentation, so I consider that checklist item to be already addressed.

**Comment by redshiftzero** [comment]
Addressed by #1948 and #1949, closing
