### ISSUE TITLE
Confusing UX: "Download All" button does not Download All

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1963]
## Description

There is this handy "Download All" button on the journalist interface:

![screen shot 2017-07-11 at 4 52 00 pm](https://user-images.githubusercontent.com/7832803/28095820-7574cad4-6659-11e7-80c5-77a3ae75cf08.png)

Unfortunately, just clicking the button doesn't download all. 

## Steps to Reproduce

1. Provision development VM on `release/0.4`
2. Submit some test sources
3. Create a test journalist account and sign into the journalist interface
4. Click "Download All" on the index

## Expected Behavior

You get a zipfile of all submissions from all sources. 

## Actual Behavior

A flashed message "No collections selected!" appears: 

![screen shot 2017-07-11 at 4 56 24 pm](https://user-images.githubusercontent.com/7832803/28095908-ee879852-6659-11e7-96db-326194d9548d.png)

However, clicking "Select All" and _then_ clicking "Download All" does indeed download all submissions from all sources.

## Comments

The fix here is just to rename the button to what it actually does: "Download Selected"

**Comment by conorsch** [comment]
Good catch, this has frustrated me too. 

> The fix here is just to rename the button to what it actually does: "Download Selected"

So does that mean the both Download buttons should be updated? e.g.

* "Download Unread" -> "Download Selected"
* "Download All" -> "Download All Selected"

The latter strikes me as particularly irksome.

**Comment by redshiftzero** [comment]
A valid point. The confusing part here for me is really just the "Download All", making it unclear that these buttons only apply to the selected items. 

This would address my concern, while obviating the need to append "Selected" to every button here:

![screen shot 2017-07-11 at 5 37 29 pm](https://user-images.githubusercontent.com/7832803/28096700-a69005d8-665f-11e7-96ef-549b1f02d24c.png)

**Comment by conorsch** [comment]
That's quite intuitive, and an extremely simple change. :+1: While slightly unintuitive, clicking either "Download Unread" or "Download" without any selections _does_ display an informative error message (pictured in the OP), so I'm comfortable with the compromise.

**Comment by redshiftzero** [comment]
This was fixed in #1964, closing
