### ISSUE TITLE
Document KeePass migration in Tails upgrade docs

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1970]
# Feature request

## Description

As pointed out by @freddymartinez9 in https://github.com/freedomofpress/securedrop/issues/1551#issuecomment-314818161, the Tails 2.x -> 3.x upgrade guide does _not_ include specific instructions for migrating the KeePass database. It should! Otherwise Admins and Journalists will overlook the manual intervention required (see #1919 and related), silently removing access to site-specific secrets in the passphrase manager.

## User Stories

As an Admin, I want a clearly written list of specific actions I must take in order to upgrade my organization's SecureDrop instance to 0.4. If manual actions are required to ensure access to KeePass databases, tell me what I need to do, so I can do it.

**Comment by redshiftzero** [comment]
Fixed in #1991
