### ISSUE TITLE
inconsistent display when exiting /use-tor

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1978]
# Bug

## Description

The display shows both "you are not using tor" and "Please select "New Identity" from the green Onion button in the Tor browser".

## Steps to Reproduce

* navigate to the source interface with firefox
* click on the "Learn how to install it" link
* click on the exit button

## Expected Behavior

![expected](https://user-images.githubusercontent.com/433594/28218975-98345dec-68ba-11e7-895f-a2f96e049557.png)

## Actual Behavior

![inconsistent](https://user-images.githubusercontent.com/433594/28218983-a340c504-68ba-11e7-88fd-d65b98a58742.png)

**Comment by conorsch** [comment]
Great catch @dachary, thanks! This has irked me before, but since I've switched to use Tor Browser for all SD testing, I haven't seen this lately. Going to toss this on the 0.4.1 milestone, so it'll get patched soon, but not block ongoing QA for 0.4.
