### ISSUE TITLE
Resolve inconsistently named and confusing source IDs

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1998]
## Description

When working with the SecureDrop application code, there are multiple IDs referred to as the `source_id`:

* the filesystem ID (the string used to refer to sources on disk)
  * e.g. referred to as `source_id` in `delete_collection()` in `journalist.py`
* the source ID (primary key of the source in the SecureDrop database)
  * e.g. referred to as `source_id` in `index()` in `journalist.py`
* the `sid` - it is unclear what this is on first inspection (it's the filesystem ID but these instances of `sid` should be replaced with which column this is referring to)

These are inconsistently named across the application and this is very confusing for new developers. 

## Fix

We should resolve this confusion by using these variables in a consistent manner.

There should be two IDs corresponding to the two columns in the `sources` table:

* `filesystem_id`: replace instances of `sid` and replace any `source_id`s that actually refer to the `filesystem_id`
* `source_id`: this should _always_ refer to the primary key of the source in the `sources` table

**Comment by dachary** [comment]
:+1: it got me confused when reading the code :-)
