### ISSUE TITLE
Update reStructuredText Style Conventions

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1999]
Some recent documentation-related PR's have exposed several inconsistencies in the style conventions used throughout the reStructuredText (reST) sources. Additionally, I have learned more about reST since way back when I initially wrote most of the documentation, and consequently have developed some more specific opinions about what I believe to be optimal reST style conventions.

This issue is meant to be a tracking issue and discussion forum for proposals to change the style conventions used in the reST sources of the SecureDrop documentation. Each specific proposal would be best tracked in a separate, dedicated issue.

For each proposed change to the style conventions, I would like to make the change holistically, to avoid future confusion and unnecessary review chatter about style issues. To change a reST style convention holistically, you have to:

* Describe the proposed change in detail and reach consensus on whether it should be adopted.
* Apply the change to all of the existing documentation
    * This makes the new convention consistent throughout the documentation, which avoids confusing developers who (reasonably) attempt to infer style conventions by reading the surrounding source.
* Update the [Style Guide](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html#style-guide) to explicitly describe the new style convention.

Follow up from:

* https://github.com/freedomofpress/securedrop/pull/1952#discussion_r128147541
* https://github.com/freedomofpress/securedrop/pull/1952#discussion_r127278356
* https://github.com/freedomofpress/securedrop/pull/1952#discussion_r127284564

**Comment by eloquence** [comment]
There has been a lot of cleanup and standardization since this issue was filed, so it can be considered outdated at this point. Resolving.
