### ISSUE TITLE
Tails 3 config setup scripts do not enforce ownership

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2017]
# Bug

## Description

When upgrading from Tails 2 to Tails 3 on the Admin Workstation, the `./securedrop-admin tailsconfig` task does not explicitly set ownership on the SecureDrop dotfiles directly at `/home/amnesia/Persistent/.securedrop`, which causes the task to fail.

## Steps to Reproduce

1. Use the Tails 2 -> 3 Upgrade guide to upgrade an Admin Workstation.
2. Follow the SecureDrop 0.3.x -> 0.4 Upgrade guide to re-establish the config on the Admin Workstation.
3. Observe failure in the `./securedrop-admin tailsconfig` task.

## Expected Behavior
The `tailsconfig` task enforces proper permissions on directories it needs to write to. 

## Actual Behavior

The `tailsconfig` task fails loudly when it tries to write to the root-owned directory `/home/amnesia/Persistent/.securedrop`. 

## Comments

The SecureDrop dotfiles directory will be root owned on upgraded devices because up to 0.3.12, we required Admins to run `sudo ./install.sh` to configure the Tails environment. Since the switch to Ansible for configuring the Tails workstation (#1803), we have much more control over file metadata such as ownership, and we should set the required ownership.

Explicit documentation of the failure can be found in this terminal session: https://gist.github.com/conorsch/e2348edeb32feb94d4905fa9009d36fb

**Comment by redshiftzero** [comment]
Fixed by #2018
