### ISSUE TITLE
Tails 3 config setup scripts do not remove Document Interface icon

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2020]
# Bug

## Description

The Document Interface icon persists on an upgraded Admin Workstation, even after running the 0.4 `./securedrop-admin tailsconfig`. Check it out:

![tails-duplicate-desktop-icons](https://user-images.githubusercontent.com/657862/28482012-58fdbf86-6e1b-11e7-81b1-3461d59f49ad.png)

## Steps to Reproduce

1. Upgrade a Tails 2 Admin Workstation with 0.3.12 to Tails 3 with 0.4-rc1.
2. Run the `./securedrop-admin tailsconfig` action as documented in the upgrade guide (#2003).
3. Reboot and log back in.
4. Observe redundant Document _and_ Journalist Interface icons.

## Expected Behavior
Only two custom desktop icons are displayed:

* Source Interface
* Journalist Interface

## Actual Behavior
Three custom desktop icons are displayed:

* Source Interface
* Journalist Interface
* Document Interface

## Comments
We already have tasks in the tails-config Ansible role to handle cleaning up the old `document.desktop` file. Managing persistent files in Tails is tricky, though, so clearly there are additional locations from which the file, or copies thereof, must be removed.

**Comment by conorsch** [comment]
This was a tricky one to nail down, but after much `locate`ing and rebooting, finally got the Document Interface icon to stay gone. PR incoming.

**Comment by redshiftzero** [comment]
Confirmed via hardware testing that the "SecureDrop Document Interface" desktop icon does indeed return after a reboot.

**Comment by redshiftzero** [comment]
Fixed by #2021
