### ISSUE TITLE
Post offers of source for kernels

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2031]
# Feature request

## Description

We should start posting explicit offers of kernel source packages for the custom-compiled kernels hosted in the FPF apt repository. We don't host source packages there, just the binary image packages (and also the header packages, even though those aren't used in the installation logic). For Admins who request source, we can provide those on demand, but we should also explicitly state this option.

The Software Freedom Conservancy has been in touch with recommendations about appropriate places to place the offer:

1. In the docs, in the install guide where grsecurity is installed, via a "Note" just below the https://docs.securedrop.org/en/latest/install.html#install-securedrop-servers section. 
2. As a comment in the FPF apt repo vars: https://github.com/freedomofpress/securedrop/blob/9f94a34e4f0c654d8e0d624342aecbd556c447f7/install_files/ansible-base/roles/install-fpf-repo/defaults/main.yml
3. Although not explicitly recommended by SFC, in the spirit of 2, also a comment in the grsecurity install tasks: https://github.com/freedomofpress/securedrop/blob/9f94a34e4f0c654d8e0d624342aecbd556c447f7/install_files/ansible-base/roles/grsecurity/tasks/from_fpf_repo_install_grsec.yml#L23
4. Configure a source package so that `apt-get source securedrop-grsec` displays the offer.

1-3 are all immediately achievable, and I support including them for the upcoming 0.4 release as docs updates. 4 will require a bit more research, but should be achievable in the near future (though not for 0.4). 

## Comments

In the interest of keeping the repo dry, perhaps we should add a top-level file to the repo that includes the explicit offer, and references (1-3) can point to that specific file. I'd at least like the top-level file to track the canonical text of the offer, and we can copy/paste it around as necessary to update it—although I suspect that will be a painful practice into the future.

## User Stories

As an Admin, I want a clear statement about where I can find source code for compiled packages running on my SecureDrop instance.

As a SecureDrop maintainer, I want a clear statement explaining the source request process, so that all Admins can be directed to the same information, and use the same contact methods for source requests.

**Comment by conorsch** [comment]
We should also mention it in https://docs.securedrop.org/en/stable/development/apt_repo.html

**Comment by redshiftzero** [comment]
Items 1-3 were completed in #2033, leaving just item 4 to complete. Moving to 0.4.1.

**Comment by conorsch** [comment]
4) is still outstanding—haven't figured out how to make an `apt-get source <package>` display a custom message yet. During 0.6, however, we moved from 3.x kernels to 4.x kernels, and the rebuild process changed somewhat, which warrants documentation updates. The following changes should be made:

* [ ] Convert the old [grsecurity build repo](https://github.com/freedomofpress/ansible-role-grsecurity//) to docs focus on the SD rebuild story (modern build logic lives in a [separate repo](https://github.com/freedomofpress/ansible-role-grsecurity/) and can be imported via scripts)
* [ ] Write new docs for 4.x rebuild story; preserve docs for 3.x kernel story going forward.
* [ ] Document internal procedure for responding to source offers (so multiple staff members can facilitate responding to requests)
* [ ] Vet the existing SecureDrop-focused documentation to make sure contact information and URLs are up to date

Working on this now, will update checklist above as I go.

**Comment by conorsch** [comment]
Since the checklist above involves changes across several repos, I'm going to move to a dedicated issue, and cross-link external issues in the checklist to track progress over time.

**Comment by conorsch** [comment]
As mentioned in https://github.com/freedomofpress/securedrop/issues/3185#issuecomment-713151528, we're in a fine position here, with no further refinements necessary. Yes, it'd be nice to to provide "apt-get source" capability, but the existing request process isn't terribly time-intensive for FPF based on volume. Furthermore, the >=4.x kernel build story is exceeding simple: unpack tarball, run `make deb-pkg`, that's it. Even the config was use is bundled. 

We'll need to add some additional build-env changes for reproducibility (#308) of kernel images, but that's a ways off yet.
