### ISSUE TITLE
Instructions for verifying the Ubuntu .iso are unclear

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#2034]
# Bug

## Description

In the **[Install Ubuntu](https://docs.securedrop.org/en/latest/servers.html#install-ubuntu)** section of the SecureDrop documentation, it says:

> In order to verify the installation media, you should also download the files named SHA256SUMS and SHA256SUMS.gpg.

But does not provide further instruction on how to obtain these files.

## Expected Behavior

The documentation should clearly describe how to obtain the files needed to verify the Ubuntu installation media for the SecureDrop servers.

**Comment by redshiftzero** [comment]
Fixed by #2037, closing!
