### ISSUE TITLE
./manage.py add-admin prompts admins to confirm an invalid password

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#2035]
# Bug

## Description

The minimum password length check added to `./manage.py add-admin` in #1660 is not performed until after the password is entered twice, i.e. after both the `Password:` and `Confirm Password:` prompts.

This is slightly annoying for administrators because it makes them enter an invalid password twice before letting them know that it was invalid.

## Steps to Reproduce

1. Provision a development VM and ssh into it.
2. `cd /vagrant/securedrop`
3. `./manage.py add-admin`
4. Enter any username.
5. At the `Password:` prompt, enter a password that is less than 12 characters.
6. At the `Confirm Password:` prompt, enter the same password again.

## Expected Behavior

After a short password is entered at the `Password:` prompt, `./manage.py add-admin` should perform the password length check and let the user know that their desired password is too short.

## Actual Behavior

The user is prompted to confirm their invalid password before being told it is invalid. This is confusing and annoying, because it forces the admin to take a step back after being lead to think they had an entered an acceptable password.

## Comments

We should move the password length check so it is performed after the first `Password:` prompt.

**Comment by redshiftzero** [comment]
Thanks for filing this @garrettr. We should definitely fix this, tagging for the next minor release - 0.4.1.

**Comment by heartsucker** [comment]
Should we implement https://github.com/freedomofpress/securedrop/issues/980 (diceware passwords), this would be covered.

**Comment by redshiftzero** [comment]
Adding blocked because as @heartsucker notes, this will be naturally solved by #1509.

**Comment by redshiftzero** [comment]
Fixed by #1509
