### ISSUE TITLE
Add documentation for translators

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2039]
## Description

We should have some documentation for translators [like this](https://www.torproject.org/getinvolved/translation-overview.html.en) that has:

- [ ] Brief overview of the project with relevant links if they want to learn more (e.g. to the threat model, etc.)
- [ ] Links to our existing glossary/terminology page in the documentation so that translators know how to translate technical terms that may not exist in the target language
- [ ] An explanation of how to make a Weblate account and contribute translations

## User Stories

As a translator unfamiliar with SecureDrop, I want a single page I can go to in the documentation to learn how to get started contributing translations.

**Comment by dachary** [comment]
> An explanation of how to make a Weblate account and contribute translations

Draft proposal to be discussed at https://github.com/freedomofpress/securedrop/pull/2046
