### ISSUE TITLE
`./manage.py add-admin` should verify username prior to prompting for a password

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#2042]
# Feature request

## Description

Currently, the admin's username is not confirmed as being acceptable (uses only certain characters, non-null, within a certain length parameter, unique) before `./manage.py add-admin` prompts for a password. It would improve the user experience when running the script if a username verification loop was implemented, exiting only when a proper username or SIGINT (^c) is received. After an appropriate username has been chosen, the script may then proceed to prompt for a password.

Related to #2035.

**Comment by redshiftzero** [comment]
Will be fixed by #2085

**Comment by heartsucker** [comment]
Closed by #2085
