### ISSUE TITLE
Implement factory functions to generate journalist/source apps

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2057]
# Feature request

As discussed in the contributor's meeting.

## Description

SecureDrop should use an app factory method like described in the [Flask docs](http://flask.pocoo.org/docs/0.12/patterns/appfactories/). This would allow for parallelization of tests and tests are independent and can assume a clean slate for every run. This also would help use stop relying on any global variables.

The first pass that is the minimal amount of change for this to work would be turning this:

```python
from securedrop import config

app = Flask(__name__)

@app.route('/')
def index():
    return config.HELLO_WORLD

app.run('127.0.0.1', port=8080, debug=True)
```

Into this: 
```python
from securedrop import config

def init_app(cfg)
    app = Flask(__name__)

    @app.route('/')
    def index():
        return cfg.HELLO_WORLD

app = init_app(config)
app.run('127.0.0.1', port=8080, debug=True)
```

From here, we could slowly strip out other remaining global state and start refactoring the test suite with pytest fixtures.

## User Stories

As a developer, I want my code to be oh-so-pretty.

**Comment by heartsucker** [comment]
Also as noted, this shouldn't be implemented until after @dachary gets his i18n stuff into the mainline since there will be approximate 1 jillion lines that rebase poorly.

**Comment by heartsucker** [comment]
This was completed for the source interface in #2365.

**Comment by redshiftzero** [comment]
Moving this ticket to the 0.4.5 milestone for the journalist refactor

**Comment by redshiftzero** [comment]
Done in #2466
