### ISSUE TITLE
Consider adding a note in Tails upgrade docs about missing "Root Terminal" Launcher in Workstation Backup Procedure

### ISSUE THREAD

**Issue by edenemmanuel** [freedomofpress/securedrop#2065]
# Feature request
Consider adding a note in Tails upgrade for the case if someone has a missing "Root Terminal" Launcher in [Tails 3.x Upgrade Docs](https://docs.securedrop.org/en/stable/upgrade_to_tails_3x.html#backup-the-tails-drives) and [Workstation Backups](https://docs.securedrop.org/en/stable/backup_workstations.html)

## Description
In Tails 3.x, if an administrator password isn't set, the "Root Terminal" Launcher is missing (both from the GNOME Applications menu, and from search). I can confirm this behavior by testing in a virtual machine.

This is sensible behavior, but it might confuse Admins who forget to set an administrator password.  It's relatively easy to miss that step in Tails 3.x, and it's a different procedure in Tails 2.x.

To help alleviate any potential confusion, perhaps a note reminding Admins to set an administrator password if they don't see a "Root Terminal" launcher during their backup procedures.

## User Stories

Not a significant story, but during a test, I noticed one Admin spend a significant amount of time looking for the "Root Terminal" launcher when it turned out they forgot to set an administrator password.

## How to implement

We just add a quick note right after we ask the Admin to open up "Root Terminal" mentioning that if they don't see it, then they must have forgotten to set an administrative password, and they will need to reboot and set one up.

**Comment by redshiftzero** [comment]
Good idea :+1:
