### ISSUE TITLE
Tails 3 root nautilus backups

### ISSUE THREAD

**Issue by KwadroNaut** [freedomofpress/securedrop#2069]
# Bug

## Can't start nautilus from root terminal

Since Tails 3, you'll have to do something like `gksu nautilus` to launch a root nautilus. You'll get a `GTK-Warning cannot open display: :1` **if you have run a root file manager before in the same session**

## Steps to Reproduce

Described here:
https://docs.securedrop.org/en/latest/upgrade_to_tails_3x.html#upgrade-the-tails-drives
https://docs.securedrop.org/en/latest/backup_workstations.html

## Actual Behavior

![nope-0](https://user-images.githubusercontent.com/99527/28945880-9a09f5f2-78a8-11e7-8129-364518da7d0f.png)

## Comments

gksu nautilus from a regular terminal would work. When reproducing this bug, I found that it only happens when having run a root nautilus in the same sesion before.

**Comment by edenemmanuel** [comment]
Was able to reproduce on hardware. Thanks @KwadroNaut!

Seems running `gksu nautilus` from the regular terminal application would be a more sustainable alternative in the long run.

**Comment by edenemmanuel** [comment]
Currently WIP as [update_tails_docs_gksudo](https://github.com/freedomofpress/securedrop/tree/update_tails_docs_gksudo).
