### ISSUE TITLE
Source Interface throwing a 500 in staging on develop

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2070]
# Bug

## Description

The Source Interface is failing due to an AppArmor violation for apache:

>Aug  3 23:20:20 app-staging kernel: [  656.377951] audit: type=1400 audit(1501802420.976:32): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/etc/timezone" pid=10855 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=0

## Steps to Reproduce

1. Check out `develop` branch.
2. Bring up staging VMs.
3. Try to load the Source Interface (you'll see a 500).
4. Check syslog and you'll see an error similar to the above.

## Expected Behavior

Source Interface renders well because apache is happy and able to do its work.

## Actual Behavior

Source Interface fails because apache is confined by the restrictive AppArmor profile and falls down before it can serve anything.

## Comments

The regression likely slipped in due to lack of proper CI on PRs coming from forks (#1826). Thankfully the the functional test introduced in #1731 caught the error, when none of the app test suite did.

**Comment by conorsch** [comment]
Fortunately I _cannot_ reproduce when bringing up staging VMs on the 0.4.1 tag. So looks like we have a narrow window to find where the change crept in.

**Comment by conorsch** [comment]
Looks like the culprit is 10b41800d5524aef6c483c5c77d37f279e4fcecd. The testing procedure I used was:

```
git fetch
git checkout develop
git branch -b fix-apparmor-profile-in-develop
git revert 10b41800d5524aef6c483c5c77d37f279e4fcecd
vagrant provision /stag/
```

The Source Interface then rendered without error. Let's confirm again that reverting the reversion resolves:

```
git revert $(git rev-parse HEAD)
vagrant provision /stag/
```

Broken again. Short-term fix would be to revert that commit and back it out of develop. Certainly we can update the AppArmor profile to authorize timezone reading as well, let's just make sure we do our homework, since this one caught us by surprise.

**Comment by redshiftzero** [comment]
Great, let's revert `10b41800d5524aef6c483c5c77d37f279e4fcecd` so we can get back to smooth seas and then merge it in again in a future PR along with updated AppArmor rules. 

In the future, we should also only use Option 2 of #1826 to prevent regressions like this from slipping in.
