### ISSUE TITLE
Apparmor denials for fontawesome-webfont.svg trigger OSSEC alerts 

### ISSUE THREAD

**Issue by KwadroNaut** [freedomofpress/securedrop#2075]
Don't think these are of great concern and have only occurred once but wanted to flag. See https://github.com/freedomofpress/securedrop/issues/1240 different file, same issue ;-)

Securedrop 0.4.1

# Bug

## Description

Received From: APP->/var/log/syslog
Rule: 100012 fired (level 7) -> "Apparmor denied event"
Portion of the log(s):

DATE app kernel: [19517572.494728] audit: type=1400 audit(1501844691.909:75): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/var/www/securedrop/static/fonts/fontawesome-webfont.svg" pid=3891 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=33

**Comment by redshiftzero** [comment]
Thanks for reporting this @KwadroNaut! We have a PR fixing this pending in #2078 and will get this fix into the next release of SecureDrop.
