### ISSUE TITLE
Staging CI: Rebase on target branch before running tests

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2080]
## Description

For the staging CI we should rebase onto the target branch (here onto current `develop`) before running tests - it looks we're not doing this currently on Circle CI.  I noticed this while debugging #2070 - staging builds of other pending PRs continued to pass _after_ the breaking change was introduced into `develop`.

**Comment by msheiny** [comment]
This is currently a proposed feature for circleCI BUT i saw some user's tackling it manually, [for example here](https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14).
