### ISSUE TITLE
NTPDate server not specified

### ISSUE THREAD

**Issue by harlo** [freedomofpress/securedrop#2094]
# Feature request

NTPDate does not have a specified server to use, and if evoked as per docs [here](https://github.com/freedomofpress/securedrop/blob/develop/docs/servers.rst#system-date) it will fail. Please implement Jen's fix in the docs:

`sudo ntpdate ntp.ubuntu.com`

**Comment by conorsch** [comment]
Those lines in the docs are only relevant if the Admin didn't perform the OS install as specified elsewhere in the docs. Not only should we update the command invocations as @harlo says, but also we should move those steps to the post-install checks. After every fresh install, sane checks are:

```bash
host freedom.press
sudo apt-get update
sudo ntpdate ntp.ubuntu.com
```

All via interactive sessions on both machines. Would be reasonable to place these in a unique subcommand for the securedrop-admin script, but that's a separate discussion: the docs definitely need to be updated.
