### ISSUE TITLE
Document need for multiple admins to sync on site-specific changes

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2096]
# Feature request

## Description

Admins need to sync on changes they make to `site-specific`.

Admin Alice may set variable A from value X to Y on the server. 
Admin Bob has variable A still set to X in `site-specific` in his local admin workstation.
If admin Bob sets variable B from value W to Z on the server, he will also reset variable A to X, unless Alice has informed him of the changes she made. 

We should note in the Administrator Guide that they will need to sync on these.

**Comment by conorsch** [comment]
Related: #1175. In short, the current architecture largely assumes the following:

* site-specific vars don't change after install
* only one Admin will be controlling the instance
* Admins and Journalists are physically copresent

In practice the above are rarely true. Having a single configuration store for the servers that is editable by multiple distributed Admins is challenging with the current architecture. If we end up moving to a container-friendly deployment model, then publishing updates to etcd with Admin-only authentication would be the sane way to do this.
