### ISSUE TITLE
Docs: Say that rerunning ./securedrop-admin install is safe

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2098]
## Description

We should remind people in the docs (and maybe in the output of the script) that they can repeatedly `./securedrop-admin install` as much as they want without breaking anything. If they get a transient error, they should feel comfortable to fire it off again.

**Comment by conorsch** [comment]
This situation improved vastly as of 0.4, so definitely appropriate to state explicitly that rerunning is not going to cause things to blow up. We should probably resolve #1704 first, though.

**Comment by edenemmanuel** [comment]
@conorsch should we consider #1704 a blocker for #2098? It looks like that'll be resolved soon anyway, rendering my question moot.

**Comment by conorsch** [comment]
> should we consider #1704 a blocker for #2098?

No, PRs welcome to close #2098.

> It looks like that'll be resolved soon anyway, rendering my question moot.

Aye! :wink:
