### ISSUE TITLE
Docs: Specify preference for Tips page in Deployment Best Practices

### ISSUE THREAD

**Issue by olivemartini** [freedomofpress/securedrop#2102]
Whenever possible, we recommend that outlets subsume information for potential SecureDrop sources into a general "Tips" landing page (postal mail, Signal, etc.). We should add language that we recommend this over a dedicated SecureDrop landing page as a means to make it more difficult to identify traffic associated with a SD-specific leaker. 

We can add to this section of the docs: https://docs.securedrop.org/en/stable/deployment_practices.html#landing-page

The Intercept landing page is a good example of this presentation: https://theintercept.com/leak/

**Comment by dachary** [comment]
Very similar to #2200
