### ISSUE TITLE
UX: Journalists often click the checkbox to try to get to the source page

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2130]
## Description

Noticed this UX issue watching first-time SecureDrop users at an on-site: journalists often will try to click on the checkbox to the _left_ of the source codename to try to navigate to the individual source page:

![ux-checkbox](https://user-images.githubusercontent.com/7832803/29378416-d300b3d0-8273-11e7-9bb4-5026bc632e0f.png)

We need to make it more clear that the source codename is the element they should be clicking on to navigate to the individual source page (relevant: designs in #1540).

**Comment by conorsch** [comment]
Most intuitive to me would be to make the entire row background an href to the source page, minus of course the individual buttons and the checkbox. Full disclosure: IANAUXE (I am not a UX engineer).
