### ISSUE TITLE
Spurious OSSEC alert regarding MARK 

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2138]
# Bug

## Description

First reported by @freddymartinez9 in https://github.com/freedomofpress/securedrop/issues/1670#issuecomment-309950713. Message text is:

```
Received From: (mon)-> ossec-keepalive
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

-- MARK --: I5A8N31x+TY8%Q-3m [snip]

```

In a [discussion on the ossec list](https://groups.google.com/forum/#!msg/ossec-list/dE3klm84JMU/kGZkRdSl3ZkJ), it appears that message format is used to track internal state within OSSEC, and shouldn't ever percolate up to generating warnings. Its doing so is considered a bug. 

Worth nothing that OSSEC [2.8.3](https://github.com/ossec/ossec-hids/releases/tag/v2.8.3) included a bugfix for "Fixing broken memory management in ossec alert decoder" which _may_ be related. We'll need more data to make a firm call there.

## Steps to Reproduce

As yet unknown, but we've seen this alert reported by multiple Admins. 

## Expected Behavior

MARK-related messages do not occur and are not sent to Admins.

## Actual Behavior

Admins are forced to review inscrutable MARK-related alerts that are not actionable.

## Comments

Relevant to upgrading OSSEC version (#2136) and better testing for OSSEC notifications (#2134).

**Comment by redshiftzero** [comment]
It looks like they have an open ticket about this: https://github.com/ossec/ossec-hids/issues/466, which links to an entry in their FAQ http://ossec-docs.readthedocs.org/en/latest/faq/alerts.html:

> This is a keep alive message, sent from an OSSEC agent to the manager. Thie prevents the manager from marking the agent as disconnected. These log messages should be filtered out, but sometimes one slips through

I think adding a custom rule to prevent email alerts for these events is the right step until this is fixed upstream.
