### ISSUE TITLE
vagrant provision build fails with ansible 2.3.2

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2165]
# Bug

## Description

It looks like quoting rules changed between ansible 2.2.1 and ansible 2.3.2 which causes a "sudo rsync" command not found error when running vagrant provision build (full sample output at https://paste2.org/4gV8d96f)

## Steps to Reproduce

* virtualenv /tmp/v
* source /tmp/v
* pip install ansible # with a ton of other dependencies from https://gist.github.com/trinitronx/bdfd3cbb338767e58299 if needed
* vagrant up build

## Expected Behavior

The packages are produced

## Actual Behavior

Fails with:
<pre>
fatal: [build]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --archive --rsh=/usr/bin/ssh -S none -i /home/loic/.vagrant.d/insecure_private_key -o Port=22 -o StrictHostKeyChecking=no --rsync-path='sudo rsync' --out-format=<<CHANGED>>%i %n%L /home/loic/software/securedrop/securedrop/install_files/securedrop-app-code/ vagrant@192.168.121.234:/tmp/securedrop-app-code-0.4.2-amd64", "failed": true, "msg": "Warning: Permanently added '192.168.121.234' (ECDSA) to the list of known hosts.\r\nbash: sudo rsync: command not found\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: remote command not found (code 127) at io.c(235) [sender=3.1.2]\n", "rc": 127}
</pre>

## Comments

The workaround is to install explicitly ansible 2.2.1 as mentionned in securedrop/requirements/develop-requirements.txt

* pip install ansible==2.2.1

Another workaround is to apply the following patch but there may be other ansible version issues because of non backward compatible changes.

<pre>
modified   install_files/ansible-base/action_plugins/synchronize.py
@@ -365,5 +365,5 @@ class ActionModule(ActionBase):
                 # remote then add privilege escalation here.
                 if self._play_context.become_method == 'sudo':
-                    rsync_path = "'sudo rsync'"
+                    rsync_path = "sudo rsync"
                 # TODO: have to add in the rest of the become methods here
</pre>

**Comment by ageis** [comment]
This is due to https://github.com/ansible/ansible/issues/23575.

**Comment by dachary** [comment]
For the record that was also discussed last month at https://github.com/freedomofpress/securedrop/issues/1146#issuecomment-314959011

**Comment by msheiny** [comment]
Prod is getting installed from `install_files/ansible-base/requirements.txt` so we need to peg on ansible `2.2.3.0` (and merge all these confusing requirements into one)

**Comment by dachary** [comment]
@msheiny ok, done. Any suggestion about how to enforce that for all roles / playbooks ? Simlinks everywhere + includes ? Or is there a smarter / less verbose way of doing the same ?

**Comment by conorsch** [comment]
Related: #2175.
