### ISSUE TITLE
Docs: Links to edit/view on Github are broken

### ISSUE THREAD

**Issue by mrphs** [freedomofpress/securedrop#2194]
On top right and bottom left corner of every page on docs there's a link to view/edit that page on Github. Seems like all of those links are broken.

**Comment by redshiftzero** [comment]
Thanks for reporting this @mrphs. These links are working on `latest` but not `stable`. After some digging, it appears the `404` of these links is a known issue upstream (https://github.com/rtfd/readthedocs.org/issues/1820), but I think it's probably best to remove these "Edit" links from the HTML as we provide instructions how to edit the documentation [here](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html) and the presence of these broken links is confusing for new contributors.

**Comment by redshiftzero** [comment]
In #2754, @trankmichael investigated how to remove this for us on RTD and discovered that the method to disable this is currently [not working](https://github.com/freedomofpress/securedrop/pull/2754#issuecomment-356334292), so I'm marking this blocked for now.

**Comment by eloquence** [comment]
This has been resolved upstream.
