### ISSUE TITLE
Docs: Document local Tails VM testing

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2204]
## Description

We need to document how to provision a Tails VM for testing SecureDrop on both macOS and Linux.

## User Stories

As a SecureDrop developer, I want clear instructions of how to set up Tails for testing

**Comment by conorsch** [comment]
@redshiftzero is the best candidate for writing macOS docs. Either @msheiny or I can write the Linux (libvirt) docs.
