### ISSUE TITLE
selenium javascript toggle is unreliable

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#2209]
# Bug

## Description

The alert only shows if javascript is active. However it showed in a case where javascript was supposed to be disabled.

## Steps to Reproduce

run pytest --page-layout tests/page-layout in a loop on a slow machine for a very long time

## Expected Behavior

The test passes.

## Actual Behavior

<pre>
    def test_delete_one(self):
        self._source_visits_source_homepage()
        self._source_chooses_to_submit_documents()
        self._source_continues_to_submit_page()
        self._source_submits_a_file()
        self._source_submits_a_message()
        self._source_logs_out()
        self._journalist_logs_in()
        self._journalist_visits_col()
        self._journalist_delete_one()
>       self._screenshot('journalist-delete_one.png')
tests/pages-layout/test_journalist.py:223:
...
tests/pages-layout/functional_test.py:68: in _screenshot
...
    self.driver.save_screenshot(os.path.join(self.log_dir, filename))
...
elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
>           raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
E           UnexpectedAlertPresentException: Alert Text: Are you sure you want delete the 1 selected submission?
E           Message: Unexpected modal dialog (text: Are you sure you want delete the 1 selected submission?)
</pre>

## Comments

* disable the javascript toggle
* find a way to wait for javascript to actually be disabled

This is the first time this happens. Selenium is generally prone to races on slow machines but there is a variety of manifestations.

**Comment by eloquence** [comment]
Very old, no recent repros. Closing.
