### ISSUE TITLE
Move linting logic from Travis to Circle CI

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2217]
# Feature request

## Description

The Travis CI config runs the linting checks as a final step, after validating the dev VM setup. We should consider moving the linting checks to Circle CI, since we have workflows as of #2149. Running all the linting checks first will keep CI runs briefer by exiting on linting errors and skipping the long-running staging test install.

## User Stories

As a SecureDrop developer, I want CI runs to be reliable, informative, and snappy. Failing fast is appropriate for linting errors, since I should be linting locally rather than trusting CI to do it for me.

**Comment by redshiftzero** [comment]
Done in #2588
