### ISSUE TITLE
Fix cursive language rendering on button styles

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2223]
## Description

Languages written in a cursive script like Arabic don't render well with our button styling:

![screen shot 2017-08-28 at 11 59 47 am](https://user-images.githubusercontent.com/7832803/29788935-380eb686-8be9-11e7-819f-3c1702d1c3de.png)

While the text on the title and paragraph text renders well, the text on the button has unnecessary spaces between letters that should be connected due to our SASS styling, see for example the word "من" present in both the paragraph and button text. 

In paragraph (this is how it should look): 

![min-paragraph](https://user-images.githubusercontent.com/7832803/29789063-b8b9ecec-8be9-11e7-94ca-2220d3434f5d.png)

In button (gap between مـ and ـن): 

![min-button](https://user-images.githubusercontent.com/7832803/29789127-e5bfeba6-8be9-11e7-9950-a0cc65346ad9.png)

**Comment by heartsucker** [comment]
Note: this is because of `letter-spacing`. We can use the `:lang` CSS selector (I think) as an override to remove this spacing on a manually curated set of languages. There may be a better way to do this, but as a not-frontend-person, I'm not sure what this would be.

**Comment by heartsucker** [comment]
As an aside, I am so fricken happy that SD now has i18n support, especially in Arabic.

**Comment by redshiftzero** [comment]
Added to upcoming release milestone as we're trying to ship Arabic in the next release
