### ISSUE TITLE
Remove strings from CSS files to simplify i18n

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2229]
# Feature request

## Description

Text strings should not appear in CSS files as this will complicate the i18n efforts.

Example (`source.sass`):

```sass
#show
  &:before
    color: $color_purple_medium
    content: "Show"

  &:hover
    &.show:before
      color: $color_grey_medium
      content: "Hide"
```

## User stories

As @dachary I want my life to be easier so there are less places to have to deal with translations.

As a server, I want to serve CSS as a static file.

As an end user, I don't want to wait forever to redownload the CSS over Tor because I changed languages.

**Comment by dachary** [comment]
Resolved by https://github.com/freedomofpress/securedrop/pull/2322
