### ISSUE TITLE
Update Circle CI container image to support HTML linting

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2236]
# Bug

## Description

The container image used in Circle CI runs cannot run the HTML linter (`make html-lint`). We need to update the container image in order to support full linting in Circle CI.

## Steps to Reproduce

1. Peek at the failed Circle CI build log in #2220 
2. Observe the cryptic output from the `make html-lint` task.

## Expected Behavior

Circle CI runs `make html-lint` without error. 

## Actual Behavior

Circle CI fails on `make html-lint` with this error:

```
#!/bin/bash -eo pipefail
make html-lint

html_lint.py --printfilename --disable=optional_tag,extra_whitespace,indentation \
	securedrop/source_templates/*.html securedrop/journalist_templates/*.html
Traceback (most recent call last):
  File "/usr/local/bin/html_lint.py", line 66, in <module>
    sys.exit(html_linter.main(options))
  File "/usr/local/lib/python2.7/dist-packages/html_linter.py", line 1094, in main
    clean_html = template_remover.clean(io.open(filename).read())
  File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 328: ordinal not in range(128)
Makefile:52: recipe for target 'html-lint' failed
make: *** [html-lint] Error 1
Exited with code 2
```

## Comments

@dachary has already identified a fix (https://github.com/freedomofpress/securedrop/pull/2220#issuecomment-326132973): 

```
apt-get install -y locales
echo en_US.UTF-8 > /etc/locale.gen
locale-gen
```

The above should be added to the Dockerfile used for Circle CI with SecureDrop.

**Comment by msheiny** [comment]
#2218 points CI to utilize the quay image -- which was created using the dockerfile image from `devops/docker/CIDockerfile`. Can you get that reviewed first or should you cherry-pick elements from that PR to your #2220 branch? Im fine with either

**Comment by conorsch** [comment]
I thought only #2160 was required, but you're right, we need #2218 in also. That's fine, it just means #2217 will stay open a bit longer. Thanks for clarifying!

**Comment by redshiftzero** [comment]
Done in #2588
