### ISSUE TITLE
Code coverage checks are not directory-agnostic

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2246]
# Bug

## Description

Code coverage checks run in Travis CI, via a handful of Python modules:

* `coverage`
* `coveralls` 
* `pytest-cov`

The coverage checks are finicky, and demand to be run from the `securedrop/` subdirectory of the repository, otherwise the Coveralls code integration simply never returns a result:

![coveralls-hanging](https://user-images.githubusercontent.com/657862/29991266-e6977966-8f38-11e7-82a7-0cb32429e7a4.png)

## Steps to Reproduce

Coveralls is designed to work only in CI, so you'll need to push a feature branch to this repository in order to trigger the Travis checks. Here's build output where the problem is observed:

* [Travis CI run](https://travis-ci.org/freedomofpress/securedrop/builds/270970291)
* [Coveralls run (for build above)](https://coveralls.io/jobs/29011185)

The Coveralls output states `No data available in table`. That's unfortunate!

## Expected Behavior

Coverage reports are generated and sent to the Coveralls CI service regardless of where the tests were executed from.

## Actual Behavior

Coverage reports are not sent correctly to the Coveralls CI service if the app test suite was executed from anywhere other than the `securedrop/` subdirectory. It's unclear whether the report is even generated correctly—further testing warranted.

## Comments

Discovered while investigating #2216. See #2240 for another directory-agnosticism report. I wager the problematic lines are the `../securedrop` lines in either `securedrop/.coveragerc` or `securedrop/tests/pytest.ini`—or both. 

Based on the [coverage docs](https://coverage.readthedocs.io/en/latest/source.html), it's not that more robust path support is even possible:

> Patterns that start with a wildcard character are used as-is, other patterns are interpreted relative to the current directory

Further tinkering required. Coverage and Coveralls integration were added way back in #1183.

**Comment by conorsch** [comment]
For comparison, these builds, also taken from #2245, show the Coveralls integration working just fine:

* [Travis CI run](https://travis-ci.org/freedomofpress/securedrop/builds/271046185)
* [Coveralls run (for build above)](https://coveralls.io/builds/13097262)

The only change was commit cd91623bf1adb048dc2c7f85448523db728ac939, which added a `cd securedrop` prior to executing the tests.

**Comment by redshiftzero** [comment]
I'm closing this. We no longer use either `coveralls` or `Travis CI`
