### ISSUE TITLE
Stabilize AWS staging builders connectivity during play

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2253]
# Bug

## Description

We've been seeing frequent time-outs to AWS builders during the middle to the end of a playbook run. Note that we already have ticket #1825 / #2218 to handle logic at the `beginning` of the run but not `mid-run`. 

## Steps to Reproduce

There is no simple way to reproduce this error - it occurs under CircleCI sporadically without warning. Usually a re-run of the job will resolve.

## Expected Behavior

The CI playbook should finish all the way through without connectivity errors.

## Actual Behavior

The CI playbook dies mid-way through (not at any particular task) with the following ansible error:

> `fatal: [app-staging]: FAILED! => {"changed": true, "failed": true, "rc": 1, "stderr": "Connection to ec2-xx-xx-xx-xx.us-west-1.compute.amazonaws.com closed.\r\n", "`

## Comments

There are a few things we can try (sorted from easiest to more time intensive):
* Switching to a different ec2 region
* Attempt to perform a rescue task against the entire playbook if it fails with the connectivity issue
* Switch to a different cloud provider -- we cant really jump up on ec2 instance size due to budget constraints but I've noticed connectivity improvements before between t2.small and the larger sizes (at least on us-west-1). On another provider we benefit as a side-effect because we can get per minute charging since all of our builders are under an hour (where as amazon rounds up to closest hour).

### Timeout reboot

In the output of CircleCI, if it ends with
<pre>
Wait for server to come back. ----------------------------------------- 602.03s
</pre>
it means the server did not come back after 10 minutes.

### Timeout launch

In the output of CircleCI, if 
<pre>
Wait for EC2 instances to boot
</pre>
fails **twice** (there is a  **Destroy EC2 instances (for relaunch)** in between), it means the timeout in securedrop/molecule/aws/aws-launch.yml is not enough.

**Comment by redshiftzero** [comment]
Just saw another AWS connectivity issue in [this build](https://circleci.com/gh/freedomofpress/securedrop/2666):

```
    TASK [Wait for server to come back.] *******************************************
    Friday 06 October 2017  23:38:19 +0000 (0:00:01.187)       0:00:03.889 ********
    ok: [mon-staging -> localhost]
    fatal: [app-staging -> localhost]: FAILED! => {"changed": false, "elapsed": 601, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in ec2-54-183-154-34.us-west-1.compute.amazonaws.com:22"}
```

**Comment by msheiny** [comment]
Did some more digging today after prodding from @dachary  :)

Seems to occur in two places:

- At the beginning of the spin-up - its apparent that our timeout is too short even with the relaunch logic
- During the sideeffect playbook right after a reboot task.

```
2797 --- Reboot in side_effect
2793 -- launch, and relaunch
2795 -- launch, and relaunch
2782 -- launch, and relaunch
2778 -- launch, and relaunch
2766 -- launch and relaunch
2759 -- Reboot in side_effect
2758 -- Reboot in side_effect
2756 -- Reboot in side_effect
2750 -- Reboot in side_effect
2751 -- launch and relaunch
2749 -- Reboot in side_effect
```

**Comment by dachary** [comment]
Added a **Diagnostic** in the PR description with reminders to help figure out why the run failed.

**Comment by dachary** [comment]
@msheiny I'm afraid 
<pre>
test_apt_autoremove[ssh://app-staging] - app-staging.testinfra.common.test_grsecurity
</pre>
is a new error blocking all CircleCI runs
