### ISSUE TITLE
Add linting of YAML files

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2255]
# Feature request

## Description

We use a lot of YAML files in the repo, mostly associated with Ansible, but also for CI:

```
find -type f | grep -P '^.*\.ya?ml$' | wc -l
139
```

Let's add at least cursory linting of these YAML files, since several contain poor formatting standards such as trailing whitespace. The recent (testvars addition)[https://github.com/freedomofpress/securedrop/pull/2224/files#diff-001632dd6f5c8bdca5320159bfbb2e2e] in #2234 shows well-formatted YAML additions, and anything below that bar should generate errors in CI.

We don't need to be super strict. The `yamllint` package is provided on Travis by default, and contains a `relaxed` target that would suffice for general usage in both CI and during local development.

## User Stories

As a SecureDrop developer, I want YAML files to remain readable, and to conform to a baseline set of linting expectations, such as no trailing whitespace.

**Comment by msheiny** [comment]
FYI - molecule also brought in `ansible-lint` and also provides a front-end to `yamllint`

**Comment by conorsch** [comment]
> FYI - molecule also brought in `ansible-lint` and also provides a front-end to `yamllint`

Thanks! Crucial, since we can't apt-get install yamllint on Ubuntu Trusty. We still need to consolidate requirements files, though, and currently Molecule isn't being installed in Travis. More info in #2175.
