### ISSUE TITLE
travis: fails to run redis

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2272]
# Bug

## Description

travis fails consistently because redis is not running

## Steps to Reproduce

push a pull request

## Expected Behavior

travis runs redis

## Actual Behavior

travis does not run redis

## Comments

revert e16b36c5eeab2e53862440dfd39d6828ebdcdb76 which was no longer needed but is now needed again

# Feature request

## Description

A short summary of the idea.

## User Stories

If appropriate

**Comment by redshiftzero** [comment]
Fixed by #2273 (`release/0.4.3`) and #2275 (`develop`)
