### ISSUE TITLE
Test Vagrant 2 against current SD workflow

### ISSUE THREAD

**Issue by freddymartinez9** [freedomofpress/securedrop#2274]
Please use the appropriate part of the template: "Bug" or "Feature Request"

# Feature Request

## Description

Yesterday Hashicorp announced a  new version of [Vagrant](https://www.hashicorp.com/blog/hashicorp-vagrant-2-0) with support for new virtualization platforms. While this shouldn't impact our setup, we should still test. 

## Steps to Reproduce

N/A 

## User Stories

As a new developer of SecureDrop, I expect to be able to `vagrant up` and have a working development environment for SecureDrop, regardless of the version of Vagrant I am running (within reason)

**Comment by conorsch** [comment]
We should at the very least be [stating required versions](https://www.vagrantup.com/docs/vagrantfile/vagrant_version.html) in the Vagrantfile, e.g. `Vagrant.require_version ">= 1.9", "< 2"`.

**Comment by jerr0328** [comment]
I just provisioned this with Vagrant 2 on MacOS, having never had set up the dev environment. Following https://docs.securedrop.org/en/stable/development/virtual_environments.html, the provisioning seemed to work without any problems. Server came up and tests seem to be working.

**Comment by redshiftzero** [comment]
I've also been using Vagrant 2 for some time without issue, so closing

**Comment by conorsch** [comment]
Related: #2970. For the record, I'm still using Vagrant 1.9.1, which just broke—but we have a workaround in #2973.
