### ISSUE TITLE
Gitignore user defined logo from admin wkstn

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2292]
# Feature request

## Description

During the provisioning of SecureDrop from tails, the user is prompted for the filepath/filename to a site provided logo. This logo is used to replace the SD stock image on the onion source/journalist interfaces. We should be git ignoring this file and perhaps asking the user to place this in a predictable filename. This will avoid a situation in the future if a user has to upgrade this local SecureDrop repo folder, they dont have to do an awkward [git stash save, git pull, and git stash pop dance](https://docs.securedrop.org/en/stable/upgrade/0.3.x_to_0.4.html?highlight=stash%20pop#pull-the-latest-release).

## User Stories

As an administrator, I want to be able to deploy a custom logo to my SecureDrop instance without muddling up the local git repo on my tails workstation stick.

As a SecureDrop maintainer, I want to ease the burden of providing user support by having users keep their  custom logos in a standardized disk location in a way that doesnt mess with the git workspace.

**Comment by redshiftzero** [comment]
Users are no longer encouraged to place a logo in their git repo as they now update the logo via the Admin Interface web application.
