### ISSUE TITLE
Add indication of which journalist is logged in?

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#2293]
# Feature request
Add indication of which journalist is logged in?

## Description
Currently, most journalists use their own Tails drive to log into SecureDrop, but in cases where someone ends up sharing and there is a need to see who's logged in, it would be good to see that, alongside a log off link.

**NOTE:** This assumes journalists are sharing a Tails workstation, which is the only situation this would be an issue in. If that's not the case, this is nbd and we can close this.

## User Stories
As a user, I want to see if I'm logged in as myself or someone else and log off the current user so that the next user can log in.

**Comment by redshiftzero** [comment]
Ideally journalist users would _not_ be sharing workstations, but this is a good UX point nevertheless :+1:

**Comment by heartsucker** [comment]
I think this is still useful as an admin may test logging in as a user (for whatever reason), possibly debugging OTP issues.
