### ISSUE TITLE
Failure to invalidate session when user resets their own password

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2303]
## Description

When a user resets their own password, their session is not invalidated. 

## Steps to Reproduce

1. User logs in
2. User resets password

## Expected Behavior

User is logged out and is requested to use their new password to login

## Actual Behavior

User can continue to browse without having to enter their new password again

## Comments

Related tickets: #2300, #880

**Comment by jerr0328** [comment]
Proposing that the frontend change would look like the following (only when user edits their own account, not for admins), including the password and 2fa code:
<img width="710" alt="screen shot 2017-10-08 at 17 07 54" src="https://user-images.githubusercontent.com/1524722/31318057-40df067a-ac4c-11e7-8a2d-6ca5d9890ec1.png">

I'm hoping to get a pull request in later today.
