### ISSUE TITLE
User does not need to enter their old password to change their password

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2304]
## Description

A user can change their password without entering their old password first. 

## Steps to Reproduce

1. Login
2. Go to change password form

## Expected Behavior

User must enter old password and then generate the new password.

## Actual Behavior

User can generate their new password without entering their old one. 

## Comments 

Related: #2300, #2303. This is a low priority to fix, but filing nevertheless.

**Comment by jerr0328** [comment]
Proposing that the frontend change would look like the following (only when user edits their own account, not for admins), including the password and 2fa code:
<img width="710" alt="screen shot 2017-10-08 at 17 07 54" src="https://user-images.githubusercontent.com/1524722/31318057-40df067a-ac4c-11e7-8a2d-6ca5d9890ec1.png">

I'm hoping to get a pull request in later today.
