### ISSUE TITLE
Update docs to include how to securely acquire hardware

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop#2305]
# Feature request

## Description

Currently our documentation only says "For an installation of SecureDrop, you must acquire" and then lists the hardware. We have no documentation on how to **securely** do this, which can create a security issue if a Nation State Action (NSA for short, lets say) wanted to [attack the supply chain](http://gizmodo.com/the-nsa-actually-intercepted-packages-to-put-backdoors-1491169592). Given our high threat model, we should include more information on this.

## User Stories

As a news organization I would like to securely acquire hardware for the installation of SecureDrop

**Comment by redshiftzero** [comment]
Also see related issues #1698 and #1699

**Comment by eloquence** [comment]
Closing as duplicate of #1698 (retitled for clarity).
