### ISSUE TITLE
Poor input validation on Yubikey HOTP setup

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2311]
# Bug

## Description

When configuring a Yubikey for HOTP 2FA, the `./manage.py` script does not valid input properly. 
## Steps to Reproduce

For instance, a hardware Yubikey with secret key:

> cb a0 5f ad 41 a2 ff 4e eb 53 56 3a 1b f7 23 2e ce fc dc d7

that entire secret should be pasted as-is into the prompt **Please configure your YubiKey and enter the secret:**. However, if you make a mistake copy/pasting, and truncate the string, e.g.:

> cb a0 5f ad 41 a2 ff 4e eb 53 56 3a 1b f7

Then the script will still accept the bad value, and logins will be impossible with the newly created account. 
## Expected Behavior

`./manage.py` script fails if HOTP secret input is bad, forcing re-entry.

## Actual Behavior

`./manage.py` shows a lackadaisical attitude toward HOTP secret structure, then staunchly refuses logins using the Yubikey.

## Comments

Logs show, predictably, a bad token error:

>  ERROR in journalist: Login for 'conor4' failed: invalid token

**Comment by conorsch** [comment]
Intriguingly we do have oddly specific input validation if the string is "odd-length", meaning not-even:

```
Please configure your YubiKey and enter the secret: a0 4a 39 4d ff 7c cd 54 87 7b f2 63 d4 5c e
['Traceback (most recent call last):\n', '  File "./manage.py", line 162, in _add_user\n    otp_secret=otp_secret)\n', '  File "<string>", line 4, in __init__\n', '  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance\n    manager.dispatch.init_failure(self, args, kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n', '  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance\n    return manager.original_init(*mixed[1:], **kwargs)\n', '  File "/var/www/securedrop/db.py", line 277, in __init__\n    self.set_hotp_secret(otp_secret)\n', '  File "/var/www/securedrop/db.py", line 347, in set_hotp_secret\n    "")))\n', 'TypeError: Odd-length string\n']
```

That exception should be caught and a readable error message displayed.

**Comment by kushaldas** [comment]
Picking this one.
