### ISSUE TITLE
source page index alignment unification

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#2315]
# Bug

## Description

The layout of the source index page shows misaligned text.

## Steps to Reproduce

Go to the source interface and see the **SUBMIT DOCUMENT** button is not aligned in the same way as the **CHECK FOR A RESPONSE** button with regard to the icon. This is visible in english but it looks nice. However, when translated in other languages it may not look good.

## Expected Behavior

Both button have a unified alignement.

## Actual Behavior

![qqn4vj](https://user-images.githubusercontent.com/433594/30500851-71854166-9a60-11e7-809e-11ece1c8cbad.jpg)

## Comments

Both buttons should align in the same way with regard to the icon.

**Comment by redshiftzero** [comment]
Is this about the icon being slightly offset on the button?

**Comment by eloquence** [comment]
This layout was redone as part of 1.0.0, closing.
