### ISSUE TITLE
journalist: confusing use of third/first person when creating a user

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2323]
# Bug

## Description

When creating a user there are two checkboxes **Is Administrator**  and **I'm using a YubiKey [HOTP]** which is confusing because both are about the user to be created, not about the journalist creating the new user.

## Steps to Reproduce

* login as an admin in the journalist interface
* click on the **Admin** link
* click on the **Add User** button

## Expected Behavior

The checkbox shows **Is using a YubiKey [HOTP]** 

## Actual Behavior

![a](https://user-images.githubusercontent.com/433594/30516430-6a3f97dc-9b3f-11e7-8b75-6e79d64a5b23.png)

**Comment by heartsucker** [comment]
This is a result of us using a DRY template for admin and user account editing. These should be two pages with two endpoints because there is too much conditional logic in them already.
