### ISSUE TITLE
Only show source codename on first session

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2327]
# Feature request

## Description

A source is shown their codename on the `/lookup` page to help them remember it on their first session. This hint should not be shown again after the source logs out. The reason being is in the future, we maybe remove the actual codename from the cookie to prevent it from being used to login indefinitely (either by encrypting it or using some uuid that maps to the codename per session). If we show this on subsequent logins, an attack could steal the cookie, not learn the codename, but login see the codename, and then login again indefinitely.

Plus, is a source has logged in successfully, they definitely know their codename, and there is little (nothing?) to be gained by showing it again.

**Comment by heartsucker** [comment]
Adding hackathon, and some notes. This could be done simply by adding a single field to the session cookie that is only added on account creation and not login. The templates could check for that either as a standalone variable or in `g`.

**Comment by squeed** [comment]
Taking a look.

Might be nice to stop storing the codename from the session too.
