### ISSUE TITLE
Use either "Admin" or "Administrator" but not both

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2332]
# Feature request

## Description

The apps / docs should only use "admin" or "administrator" since it's possible these don't map nicely in other languages. Also for consistency.

**Comment by kushaldas** [comment]
My suggestion is to use the word *admin* through out the docs, as the UI already has that word. May I submit a docs patch? :smiley:

**Comment by redshiftzero** [comment]
Feel free! :smile:

**Comment by redshiftzero** [comment]
#2497 handled the docs side, but I'm reopening this ticket for making changes in the application itself

**Comment by aydwi** [comment]
If the only immediate goal is to replace instances of "administrator" with "admin" in the codebase, a command line utility can handle it, although it can be risky. Is this supposed to be a manual process or an automated one?

**Comment by dachary** [comment]
@aydwi it is definitely better to do it manually. A tool can be used and then manual verification though.
