### ISSUE TITLE
Don't use DRY string creation

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2333]
# Feature request

## Description

We should not be DRY with string creation. Example sadness.

```python
if docs and not message:
    things = 'docs'
elif not docs and message:
    things = 'message'
else:
    things = 'docs and message'

msg = 'Thanks! We received your {things}.'.format(things)
```

This is bad for i18n because in some languages, you have to decline/inflect the "your" in the string to match the gender/plurality of the translated string. This will lead to grammatically incorrect sentences. Also, this DRYness is harder on translators. This is already problem in German as there is a different "your" for the two cases.

## User Stories

As a non-English speaking journalist (or source), I want to have a grammatically / syntactically accurate interface.

As a translator, I want to have to be able to have greater control over word ordering in my translations.

**Comment by dachary** [comment]
This has been a source of confusion with the french translation, during review. I would indeed be better to duplicate the strings.
