### ISSUE TITLE
An admin editting their own account from the admin interface should redirect to the nomal self-acocunt-edit page

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2334]
# Feature request

## Description

If an admin attempts to navigate to admin edit pages for their own account, they should be redirected to the normal account edit page.

If we implement #2304, then an admin will be able to update their own account without entering their own password. For this reason, among others, we should not try to be DRY with the normal account edit pages / endpoints and the admin account edit pages / endpoints. The logic is fairly simple, and they should be different things entirely. This will also become necessary when we split things into Blueprints with #2294 since these two endpoints will live in different places and keeping them DRY will just lead to spaghetti code.

## User Stories

As an admin, I don't want to accidentally circumvent any account update logic while updating my own account.

As dev, I don't want unnecessary OOP-style indirection and inheritance in my jinja templates.

**Comment by zenmonkeykstop** [comment]
Current functionality is acceptable. JI Admin interface won't be massively overhauled until a potential Qubes version is created.
