### ISSUE TITLE
Meta: SecureDrop Feature/Requirement/Threat tracking

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2335]
# Feature request

## Description

Currently there is no design spec for SecureDrop. This leads to some combination of the documentation, source code, ansible, and tests describing what SD does and how SD operates. The known features and requirements should be catalogued so that a more comprehensive review can be done. Threat modeling against SD would be easier if we could look at list of known features/requirements and know that with some degree of certainty they are actually implemented.

For example:

------------
5. Authorization
 5.1. Journalist Interface
    5.1.1. Passphrases MUST use diceware with `n >= 7` to have sufficient  entropy
    5.1.2. Logins MUST use TOTP or HTOP
    5.1.3. Logins MUST have rate limiting of `n < 10` attempts per minute
-----------

Currently at my work we use something like the following relation between requirements, threats, and tests.

```
RISK ----(is mitigated by)----> REQUIREMENT::SECURITY
                                           |   
                                      (generates)
                                           |   
                                           V   
                                       TEST_CASE ----(generates)----> GITHUB_TICKET
                                           ^                                ^
                                           |                                |
                                      (generates)                      (generates)
                                           |                                |
                       REQUIREMENT::{FUNCTIONAL,TECHNICAL}-------------------

```

So if we had a threat labelled `RISK-1` that said "an attacker may attempt a brute force of all journalist logins," we would have a list of requirements that mitigate that risk. In this case, `REQ-1` stating "a journalist must not be able to set an insecure password." `REQ-1` would be linked to some N test cases that can be tagged in the test suite. The tests are defined like `TEST-1` saying "Over X login attempts per minute, the sever MUST return HTTP 429."

Thus, we are able to generate reports like:

```
Risk   | Requirements      | Test Cases          | Failing Tests |
------------------------------------------------------------------
RISK-1 | REQ-1, REQ-2, ... | TEST-1, TEST-2, ... | <null>        |
```

Since RISK, REQ, and TEST are maintained outside the code, when we do a refactor or rewrite, we are able to ensure that we have adequately covered all the tests. Also, we are able to see what requirements are uncovered.

Additionally, a RISK can be tagged as:

- Identified: We know it exists, but it is not addressed in any meaningful way.
- Accepted: There is nothing we can do at this time, so we accept the risk.
- Transferred: This risk has been offloaded to a 3rd party (e.g., Tor replaces TLS (sorta)).
- Mitigated: We have addressed the risk via some requirements/features.

## User Stories

As a developer, I want to not accidentally break some security property when I refactor the tests.

As a developer, I don't want to get caught up on esoteric threats and attacks when something simple poses a bigger risk than "what if Sybil."

As a maintainer, I want to know what properties SecureDrop claims to have an any given time.

As a 3rd party auditor, I want to be able to get an overview of properties are or are not covered by SecureDrop.

As BugCrowd pentester, I want to want additional information on what SecureDrop does not cover/mitigate.

As an org considering using SecureDrop, I want a technical document that explains why this is better than "just PGP + email" or my own home brewed solution.

**Comment by eloquence** [comment]
This issue is outdated relative to our ongoing internal threat modeling work. We'll want to carefully consider how to make more of the process public, but closing this historical issue.
