### ISSUE TITLE
Don't scare sources by mentioning servers getting attacked

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2341]
# Feature request

## Description

Current copy:

```
Our servers experienced an unusual surge of new activity, when you last visited.
This could have been human activity, an automated attack, or just some random blip.
To err on the side of caution, we put a hold on sending all documents from that day through to our journalists.
```

No source needs to know that it might have been an attack. This is scary and not what we want. This should be changed to just say "lots of activity."

## User Stories

As a source, I don't want to be terrified while doing an already scary thing.

**Comment by conorsch** [comment]
Agreed, message should be friendlier. Came in via 0818b3fd43676199858da0ff3cb2210c9825fab6 in #1558. Let's make it a less terrifying message focusing on activity, rather than attack.

**Comment by heartsucker** [comment]
Omg we have gone full circle. I am now reporting bugs on commits I authored. *something something Sisyphus something*

**Comment by redshiftzero** [comment]
Fortunately this notification is one that sources should rarely see, but I agree with your suggested change here @heartsucker. I would ditch the entire second sentence to be honest as it's providing no useful information.

**Comment by vsmart** [comment]
Made a PR for this at #2697!
