### ISSUE TITLE
Change "Exit" in source interface to "Log Out"

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2356]
# Feature request

## Description

In the source interface, the button the clears a user's session and logs them out is called "Exit" when the canonical name in most UI's is "Log Out." We should match this.

**Comment by redshiftzero** [comment]
Remember we changed this from "Log out" to "Exit" after UX feedback in #1536?

**Comment by heartsucker** [comment]
```
TODO:
1) find UX person
2) GOTO 1
```

Ok but seriously, I guess we should close this on the grounds that someone who knows what they're doing more than I said we should do it the other way?

**Comment by redshiftzero** [comment]
Since Facebook, Twitter, and Gmail have billions of users in many different locales, I decided to see how they handle this: they all use either "Log out" or "Sign out", _not_ "Exit". So, while I do think most of the feedback in #1536 was solid, I'm going to merge in your change.
