### ISSUE TITLE
Debug function Source Interface Tor GET test

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2361]
# Bug

## Description

A single test is failing occasionally in CI: 

```
test_www[docker://apptestclient-site0] - apptestclient.testinfra.functional.test_tor_interfaces
```

Here's an example failing build: https://circleci.com/gh/freedomofpress/securedrop/2331

## Steps to Reproduce
1. Revert 777f97c0cf4314f2954c8bd7ce8f7cedc64f8fa7 (which marked test as XFAIL)
2. Push to CI. 
3. Observe failure.

For some reason it appears only to fail in CI—I'm able to get the test to pass locally.

## Expected Behavior
Test passes with 200 HTTP status in both local staging env and CI.

## Actual Behavior
Test fails with 500 HTTP status code in CI. (Typically passes with 200 in local staging.)
Please provide screenshots where appropriate.

## Comments

We may want to punt on this test until we have more robust client-based Selenium testing, but the this particular test _has_ caught regressions in the Source Interface before, so I'd prefer to get it working again.

**Comment by zenmonkeykstop** [comment]
Looks like this was removed altogether in 0.12.0. Closing this issue.
