### ISSUE TITLE
Run test suite in all translated languages

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2375]
# Feature request

## Description

Currently we handle a lot of string formatting via `gettext('my name is {name}').format(name=name)`, an it's possible someone breaks the formatting strings or the test suite. We need to do do things to do automated sanity checking on translations:

1. Ensure all strings are formatted (i.e., all branches on a page/function are run)
2. All pages that are generated during the test suite pass an HTML lint (to ensure a translator didn't break the HTML)

This could be achieved using some sort of metaprogramming like what @dachary has done to generate the screenshots.

## User Stories

As an admin, I don't want put any faith in my ability to look at strings in N languages and assert that the HTML will be valid or that that the formatting strings are valid.

**Comment by dachary** [comment]
Assuming the ``pytest --page-layout tests/pages-layout`` provides 100% coverage on the gettext() calls, this should provide what you're suggesting. I don't know of any easy way to check all translated strings are covered and I suspect a small percentage escape the checks.

There are two problems:

* how to measure 100% coverage ?
* how to make it fast enough that we can run it on all translations every time a pull request is pushed ?

My 2cts ;-)

**Comment by heartsucker** [comment]
I'd have to check what you wrote to see if that gets full enough coverage. We could also do this via some sort of check that the translations dir was modified only then run it. It should only happen when we pull from weblate, so we wouldn't have to run it every time.

**Comment by dachary** [comment]
I think this is partially resolved now that we run on several languages instead of just English (5bd3a97998b74e0564320d07418e374625991784). I'll leave it open though because it would obviously be better to run pages-layout tests on all supported languages.

**Comment by redshiftzero** [comment]
we did this in https://github.com/freedomofpress/securedrop/pull/4184 (adds a translation CI job when we merge translations that does run the page layout tests in all translated languages)
