### ISSUE TITLE
Update docs to only store secrect subkeys on SVS and secret key on other medium

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2383]
# Feature request

## Description

This idea sprung from #2238 and the possibility of exfiltrating data in sneaky way from the SVS. To minimize the damage should this occur, it might be wise to have the SVS only contain the secret subkeys for the application PGP key. This could be added to `generate_securedrop_application_key.rst`.

This also might be deprecated by moving to the Journalist Workstation model.

**Comment by heartsucker** [comment]
Noting that this would also be useful in the case where there are multiple airgapped laptops (one is the master) for a distributed team. Then when a member leaves, the admin could revoke that subkey, then create new subkey, push it to the app, then redistribute the secret subkeys to the remaining team members.

**Comment by eloquence** [comment]
Tentatively closing; we're unlikely to further complicate the key management story, and the `split-gpg` architecture in Qubes (or some such equivalent with GPG alternatives in future) seems to be a more future-proof improvement. Please reopen if you want to make a counterargument.
