### ISSUE TITLE
Passphrase/codename ambiguity with RTL languages

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2392]
# Bug

## Description

It is not clear if the codename / passphrase is `correct horse battery staple` or `staple battery horse correct`.

![screenshot_2017-10-03_11-43-54](https://user-images.githubusercontent.com/3998464/31119354-041ba5f0-a831-11e7-8094-353edac4e7f1.png)

## Steps to Reproduce

Attempt to create a new source. Look at codename. Attempt to reset a journalist's passphrase. Look at passphrase.

## Expected Behavior

It should be obvious what order the passphrase should be typed.

## Actual Behavior

It is not obvious? Maybe?

## Comments

We need to look into what the patterns are for displaying non-localized content on localized pages. We could also have in jinja:

```html
{% if html_dir = rtl %}
gettext('The first word of your passphrase is {word}'.format(passphrase.split()[0])
{% endif %}
```

But that sounds like a hacky pattern. Clearly more research is needed than "I thought about that for literally only 8 seconds."

**Comment by daonb** [comment]
IMHO, we should localize the passphrase and let Arabic speakers have Arabic passphrases.  Without it, we are unaccessible to those who don't read english.

**Comment by dachary** [comment]
The [translations of words used in the passphrases](http://world.std.com/~reinhold/diceware.html#Diceware%20in%20Other%20Languages|outline) does not show arabic. It would be worth doing that. It's a significant amount of work though.

**Comment by daonb** [comment]
Than there is #999 . I'm on this issue.

**Comment by daonb** [comment]
@heartsucker just to make sure I'm on the right track, can you send the confusing urls?
