### ISSUE TITLE
Provide "clean" Makefile target

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2395]
# Feature request

## Description

We should have a `make clean` action in the repo that removes the following:

* `build/*.deb`
* all `.retry` files
* all `.pyc` files

We should consider also removing:

* site-specific vars overrides
* gitignored public keys

but there's always the risk that an Admin will run `make clean` and lose config information. Perhaps that's overly cautious, though.

About the `.pyc` files, there's a quirk with running the config tests _inside_ the dev VM versus from the developer workstation, which causes the other environment to fail. Such an error looks like this:

```
ImportMismatchError: ('conftest', '/vagrant/testinfra/conftest.py', local('/home/user/software/securedrop/securedrop/testinfra/conftest.py'))
```

and can be resolved by removing all `.pyc` files, which for testinfra store absolute path info. (Thanks to @dachary for the clear report.)

## User Stories

As a SecureDrop maintainer, I want to remove all local customizations to ensure I'm testing only the code we ship, and not a bunch of development-and-testing-related conveniences or cruft.

**Comment by dachary** [comment]
So ``testinfra/test.py`` could ``make clean`` to make sure it is not inadvertently re-using pyc from a vagrant vm ?

**Comment by conorsch** [comment]
True, we could automate that. I'd prefer asking testinfra not to generate any byte code at all, though.

**Comment by dachary** [comment]
> testinfra not to generate any byte code at all, though.

Yeah but the problem is the bytecode comes from run other than testinfra like ``pytest -v tests``. Maybe there is a way to say do not **use** bytecode ?

**Comment by conorsch** [comment]
Great point. Perhaps `--cache-clear` is the option we want—would have to test to be certain.

**Comment by emkll** [comment]
The custom logo should also be removed, as it could override the existing custom logo during an upgrade (see https://github.com/freedomofpress/securedrop/issues/3528)
