### ISSUE TITLE
The hidden services seem to be down

### ISSUE THREAD

**Issue by jvoisin** [freedomofpress/securedrop#2399]
# Bug

## Description

I followed the procedure, ran the Ansible manifest, I'm at [those]( https://docs.securedrop.org/en/stable/configure_admin_workstation_post_install.html#set-up-two-factor-authentication-for-the-admin ) [steps](https://docs.securedrop.org/en/stable/create_admin_account.html), and I can't login on the hidden services, whether it's by `ssh app`, `ssh mon`, or with the browser on the web interface.

## Steps to Reproduce

Follow the procedure, try to ssh, fail.

## Expected Behaviour

Successful logins.

## Actual Behaviour

```
amnesia@amnesia:~/Persistent/securedrop$ ssh app
nc: connection failedm SOCKS error 4
ssh_exchange_identification: Connection closed by remote host
amnesia@amnesia:~/Persistent/securedrop$
```

The `/var/log/tor/log` file has lines like:

```
Oct 05 16:09:05.000 [warn] Fetching v2 rendezvous descriptor failed. Retying at another directory.
Oct 05 16:09:05.000 [warn] Fetching v2 rendezvous descriptor failed. Retying at another directory.
Oct 05 16:09:06.000 [warn] Fetching v2 rendezvous descriptor failed. Retying at another directory.
Oct 05 16:17:28.000 [notice] Closing stream for '[scrubbed].onion': hidden service is unavailable (try again later)
```
I can't check if the hidden services are down of not, because I need to connect via a hidden-service to enable local connections.

I'm using Tails 3.2, with an up to date clock, asked the Tails people for support, and they answered that it's likely a hidden-service-related issue.

I double-checked that the firewall rules are correct; I can connect to Tor (even on hidden services, like the one from duckduckgo) from my Tails, the firewall shows that `mon` and `app` are establishing connections with the outside world successfully.

## Comments

Please don't lock the boxes until the admin confirmed that the hidden services are working :/ Think about the [poor keyboards]( https://twitter.com/MatToufoutu/status/915965853300088832 ).

**Comment by freddymartinez9** [comment]
Hi @jvoisin thanks for reporting this issue. We have been tracking some issues with Tor having issues bootstrapping hidden services, its part of an upstream bug that we are watching closely. Can you confirm that the playbook ran successfully? (Feel free to send us details in our [support portal](https://support.freedom.press/)). You should be able to run the playbook as many times as you need, so feel free to run `./securedrop-admin install` as many times as needed. 

A couple of trouble shooting steps: 
 * Restart the Tor service. We have seen this issue with Tor failing to bootstrap properly so a server never publishes its Hidden Services to the network. This will require login via a physical console, which we have some [documentation on](https://docs.securedrop.org/en/stable/configure_admin_workstation_post_install.html#set-up-two-factor-authentication-for-the-admin). You would have to restart the tor service in `/etc/init.d/tor/`
 * If you can't do the above, physically reboot the servers
 * Ensure that the hidden services actually finished setting up (again, using console access). You should find the HiddenServiceDir at `/var/lib/tor/services/`
 * In your Tails administrator drive, ensure you have the Tor Authenticated [Hidden Service cookie](https://docs.securedrop.org/en/stable/configure_admin_workstation_post_install.html#auto-connect-to-the-authenticated-tor-hidden-services) in your `/etc/tor/torrc`.
 * Ensure the cookies exist in the filesystem for the hidden services. You should find a handful of files in the Admin Tails drive at `~/Persistance/securedrop/install_files/ansible_base/`

Another way to make sure that the Authenticated Hidden Service cookie is setup is you will find two icons on your Tails drive, one for the sources and one journalists. Do you see those?

**Comment by jvoisin** [comment]
The playbook ran successfully. I can't connect to the machines, since I'm locked out. I tried to reboot them several times. I do have the cookies in my `torrc`, I do have the two icons on the desktop.

**Comment by freddymartinez9** [comment]
@jvoisin can you boot into [single user mode](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/3/html/System_Administration_Guide/s1-rescuemode-booting-single.html) on those servers and check that both the SSH deamon and Tor are starting properly. The logs should be in `/va/log/syslog/`. I was unable to get [NTP working](https://docs.securedrop.org/en/stable/servers.html#minor-admin-tasks) on one of my servers and that was why it was timing out making the Hidden Services accessible. Tor depends on NTP to be accurate or it will fail, so check both NTP and the output of date on both servers. I would also double check that NTP traffic is making it out of your firewall properly (with TCP, UDP or TCP/UDP settings).

**Comment by jvoisin** [comment]
I played with the single-user mode, NTP was working, and Tor too.

I found that in `/var/lib/tor/services/ssh`, the `client_keys` file contains a `descriptor-cookie` that has the 3 last characters different from the one in `hostname`, is this intended?

**Comment by jvoisin** [comment]
![screen](https://user-images.githubusercontent.com/325724/31335165-9da882e6-acf1-11e7-8abc-6a7afca7d0b0.jpg)

Those are the Tor logs I get when I'm trying to connect.

**Comment by freddymartinez9** [comment]
> the client_keys file contains a descriptor-cookie that has the 3 last characters different from the one in hostname, is this intended?
The descriptor cookie is not used to authenticate to the hidden service, the cookie is actually in the `hostname` file. So that is not the problem...more feedback in our support portal.

**Comment by dachary** [comment]
@jvoisin I believe this issue is resolved. Feel free to re-open if not.
