### ISSUE TITLE
Phrase "Delete Collection" is ambiguous

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2419]
# Feature request

## Description

The button "DELETE COLLECTION" should really say "DELETE SOURCE" because when a collection is deleted, so is the source and that's not obvious.

Reported @xella

**Comment by redshiftzero** [comment]
This is a good point. Is it clear from "delete source" that the submissions will also be deleted? Perhaps something like "delete source and submissions" is clearer?

**Comment by kushaldas** [comment]
"Delete source and submissions" sounds better.

**Comment by byeskille** [comment]
Another phrase that could work: "delete all source data"
