### ISSUE TITLE
Use "Submissions" instead of "Documents" and "Messages" in source application strings.

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2421]
# Bug

_This is a good first issue. If you have questions ask in this ticket or reach out via our [Gitter channel](https://gitter.im/freedomofpress/securedrop)._

## Description

There are mixed usages of the terms "Submissions", "Documents", and "Messages" in both English and German.

Found by @xella

## Expected Behavior

We use the term "submissions" consistently in user-facing strings.

**Comment by redshiftzero** [comment]
True, this is confusing. I think standardizing on submissions is the best call. Submissions are then divided into files and messages. We should stop using the term documents, as the use of that term has been confusing: the uploaded files can be videos, pictures, or "documents" (PDFs, office documents).

**Comment by zenmonkeykstop** [comment]
"document" and "submission" are still both in use, this is are relatively easy fix, so can be bumped up in priority.
