### ISSUE TITLE
ngettext not used for journalist login throttling

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2422]
# Bug

## Description

We don't use ngettext for the login throttling and this makes translating into other languages grammatically incorrect (Russian in this case).

Reported by @xella

## Steps to Reproduce

Grep for the following string.

## Expected Behavior
```
ngettext('Please wait at least {seconds} seconds before logging in again.'.format(seconds=seconds), seconds)
```

## Actual Behavior
```
gettext('Please wait at least {seconds} seconds before logging in again.'.format(seconds=seconds))
```

**Comment by dachary** [comment]
The number of seconds will always be plural, reason why I did not ngettext this. I'm curious about why it creates a problem in Russian ?

**Comment by heartsucker** [comment]
Plurality is non-trivial in Russian. [Link](http://www.russianlessons.net/lessons/lesson11_main.php). In short, there are different ways to write things if the number ends in:

- 1
- 2, 3, 4
- 5, 6, 7, 8, 9, 0

So the standard English/French/etc. rule of "more than one" is insufficient. I'm also fairly sure Russian isn't the only language with such a pattern.

**Comment by dachary** [comment]
Oh .... ok. Thanks for explaining, I'll fix this.
