### ISSUE TITLE
Reset password button does not have "reset icon"

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2423]
# Bug

## Description

See title.

## Steps to Reproduce

![screenshot_2017-10-08_15-30-33](https://user-images.githubusercontent.com/3998464/31317240-a6984f30-ac3d-11e7-928d-60c5e34ba9d4.png)

## Expected Behavior

The button has the icon.

## Actual Behavior

The button does not have the icon.

**Comment by lbu32** [comment]
I'm working on it
