### ISSUE TITLE
CI instances aren't always being properly shut-down

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2435]
# Bug

## Description

After a hack-a-thon (thanks @heartsucker !) it was reported that builders were hitting a `maximum instance` warning which occurs when one hits the build limit on an instance type in an ec2 region. I logged in the following day and saw that indeed the entire quota was filled with dangling instances. This needs to be fixed, recommend some kind of cleaner job that runs constantly and kills any dangling builders.

## Steps to Reproduce

To be honest, not sure how this happened - just getting in a ticket nice and early before I forget. To follow up on however, these were the following builders I killed:

- 1637
- 2638
- 2675
- 2678
- 2691
- 2715
- 2720
- 2735
- 2736
- 2739
- 2741

## Expected Behavior

CI should not choke on a quota error :)

## Actual Behavior

CI was failing with `Instance creation failed => InstanceLimitExceeded: Your quota allows for 0 more running instance(s). You requested at least 1`

**Comment by kushaldas** [comment]
I will pass a script from Fedora Infra team, which kills any instance (we create those to build and test Fedora EC2 images) which is running more than 2 hours. We added this as a cron job.
There is also an way to mark instances not to be killed by this script. I will get all of those details.

**Comment by redshiftzero** [comment]
we moved to Google cloud for our CI boxes so this shouldn't occur any longer
