### ISSUE TITLE
Add a make target for running testinfra tests

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2437]
# Feature request

## Description

The current testinfra test wrapper script (`./testinfra/test.py`) is kind of a mess and is difficult for a new comer to parse and run. Let's do a few things to make that story easier:
* Clean-up that wrapper to accept argparse flags
* Add a `make` target to easily run tests
* Clean up the requirements story - which is really #2175 . Might want to tackle those in the same PR or at least do 2175 first.

## User Stories

As a new developer, I want to be able to quickly run the testinfra scripts without digging through code and a ton of documentation.

**Comment by conorsch** [comment]
Good idea, and I support it, but it seems reasonable to port the testinfra logic to Molecule _first_, then provide a wrapper around `molecule verify -s <scenario>` in the Makefile.
