### ISSUE TITLE
Fix two strings not localized on submission page

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2445]
The "No files selected" text and "Browse" text on the button are not localized:

<img width="664" alt="screen shot 2017-10-15 at 8 35 40 am" src="https://user-images.githubusercontent.com/7832803/31586572-a4a0ad9a-b187-11e7-9a8c-798bef3c2b5e.png">

"Write a message" was fixed in #2409.

**Comment by dachary** [comment]
I'm not sure there is a way to change that because it is rendered by the browser. If the browser language is english and the server sends strings in another language, that how it will look.

<pre>
<input type="file" name="fh" autocomplete="off">
</pre>

but maybe there are ways to control that ?

**Comment by dachary** [comment]
The **Write a message** string is translated now.

**Comment by dachary** [comment]
Running firefox with **LANG=fr_FR firefox** the **No file selected** is translated, therefore we can expect that a user will an environment completely localized (as opposed to just selecting the language in the browser preferences) will see the expected translation.

![a](https://user-images.githubusercontent.com/433594/32416578-c523e5bc-c24b-11e7-822c-00d3e5f657b3.png)

**Comment by dachary** [comment]
@redshiftzero I'm closing this because I think it is resolved already. If you have a different opinion, please re-open.
