### ISSUE TITLE
add-admin returns confusing strings

### ISSUE THREAD

**Issue by freddymartinez9** [freedomofpress/securedrop#2454]
# Bug

## Description

When adding the first admin user on a new SecureDrop install, it returns a confusing string
`./manage py add-admin`
Username: 
Note: _Journalist_ passwords are now autogenerated

## Steps to Reproduce

Add a new admin user on a fresh SecureDrop install

## Expected Behavior

Our script outputs administrator added to the user 

## Actual Behavior

Our script says we created a new journalist user not an administrator.

**Comment by kushaldas** [comment]
I am ready to count this as an UX bug. We should update the text to administrator.
