### ISSUE TITLE
Invert `login_required` decorator on journalist interface and require logins by default

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2460]
# Feature request

## Description

We use a decorator called `login_required` but may forget to add that to an endpoint in the future. A better way would be to use `app.before_request` and check that if the URL doesn't match `/static/*` or `/login` then to redirect to login if the user isn't logged in.

## User Stories

As a dev, I don't want to have to remember to add a decorator to every endpoint and then miss one and break so much of SecureDrop's security.

**Comment by kushaldas** [comment]
I have a patch set ready which requires any view to be under login (that is logged in users), except 
`main.login` and `static`. 
The insecure (unauthenticated) above mentioned views are in a list in the primary blueprint code, which has to explicitly updated if one wants to add new view which works without login.

How does this sound?

**Comment by heartsucker** [comment]
@kushaldas What you described is exactly what I do in another project:

```python
    @app.before_request
    @ignore_static
    def ensure_logged_in():
        if not g.user:
            if request.path == url_for('account.login'):
                pass
            else:
                flash('You need to be logged in.', 'error')
                return redirect(url_for('account.login'))
```

This assignment happens after the `before_request` function that does a lookup and adds the user to the `g` object (as it would obviously fail otherwise).
