### ISSUE TITLE
Installation does not like having no sasl_domain

### ISSUE THREAD

**Issue by icco** [freedomofpress/securedrop#2482]
# Bug

## Description

Our mail server auths with just a username, not a username and a domain.

## Steps to Reproduce

set sasl_domain to "" in the site-specific vars
run `./securedrop-admin install`

## Expected Behavior

 - pass validation
 - installs a config at /etc/postfix/sasl_password that looks like

```
[$smtp_relay]:$smtp_port      $sasl_username:$sasl_password
```

## Actual Behavior

 - Fails validation by trying to nslookup empty string
 - writes out a config with an `@` after the sasl_username

## Comments

I think the `@` is ok, it just looks super weird. It seems to be working though.

**Comment by conorsch** [comment]
Thanks, @icco! During QA we typically only test with 1 or 2 mail setups, and that's clearly not enough. When we have a patch to address the problem you're describing, we'll ping you for review to make sure it works for your setup, as well as what we're already testing against.
