### ISSUE TITLE
New HOTP secrets/tokens aren't validated

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2486]
# Feature request

## Description

When a journalist is added by an an admin or a user changes their own TOTP secret, they are asked to input the generated code. This code does nothing and is not validated. The user might have transcribed something wrong and then not be able to access their account. We should validate this and warn of token mismatches.

**Comment by kushaldas** [comment]
I can see you fixed it in https://github.com/freedomofpress/securedrop/commit/0de3bc5f26f70af000dfd03c5d77e19f3ccadd46#diff-c0982971d9a6dd91ffb6d4cc68286bcbR80. Closing the issue.
