### ISSUE TITLE
Increase default session timeouts to 120 minutes

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2503]
## Description

According to [this plot](https://metrics.torproject.org/torperf.html?start=2017-08-03&end=2017-11-01&source=all&server=onion&filesize=5mb), it currently takes about ~35 seconds to download a 5 MB file over Tor: 

![torperf-onion-2017-08-03-2017-11-01-all-5mb](https://user-images.githubusercontent.com/7832803/32303423-c305bdd8-bf25-11e7-9ac9-fffd8a95fbbd.png)

The maximum size of a SecureDrop submission is 500 MB, so the time it would take to download is 35 seconds * (500/5) = 3500 seconds, or just under an hour. As such, to be safe we should bump the session timeout to at least 120 minutes. 

## User Stories

As a SecureDrop source/journalist, I don't want to wait a very long time to upload/download a file over Tor, only to be logged out by the SecureDrop session timeout.

**Comment by heartsucker** [comment]
Have we tested the behavior on this? What happens when someone exceeds the timeout while a download is in progress? Does it drop the connection?

If so, we could bump the session duration *only for that request* so that the first page load after will be ok, and then it will be reset to the normal 30 minutes during the next request (namely, the request that loads the HTML/does the redirect). This would keep the window of compromise as tight as possible while allowing for long downloads.

**Comment by redshiftzero** [comment]
When I tested this behavior it logged the user out - _after_ the very long upload - _and_ the submission doesn't go through. 

> Either way, we could bump the session duration only for that request so that the first page load after will be ok, and then it will be reset to the normal 30 minutes during the next request (namely, the request that loads the HTML/does the redirect). This would keep the window of compromise as tight as possible while allowing for long downloads.

I hear ya - the thing is I don't think the marginal security benefit of a shorter session timeout  justifies the additional complication of modifying the session timeout for only certain requests. I suggest we keep it simple for maintainability and increase the session timeout for now.

**Comment by dachary** [comment]
> When I tested this behavior it logged the user out - after the very long upload - and the submission doesn't go through.

Every chunk uploaded should refresh the session. What about adding a callback to **save_file_submission** that would be called around:

<pre>
            while True:
                buf = stream.read(1024 * 8)
                if not buf:
                    break
                gzf.write(buf)
                callback_chunk_written()
</pre>

**Comment by heartsucker** [comment]
@dachary, I think @redshiftzero is right. If we do some chunking-magic-whatever, we're adding complexity that we have to maintain. I think the marginal increase in security is not worth the effort.

**Comment by dachary** [comment]
I don't have strong feelings about this. It just occurred to me that it was a way to not expire a session while something was still on the way and wanted to share that with you :-)

**Comment by redshiftzero** [comment]
Hmm, so I was going to go with the simpler implementation, but looking at #2573 we'll need something like what @dachary proposes in [this comment](https://github.com/freedomofpress/securedrop/issues/2503#issuecomment-343650698) otherwise we'll need to make the timeout very long to allow for multiple 500MB uploads.
