### ISSUE TITLE
Tor warning not working on mobile 

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2510]
# Description

Reported during Mozilla Festival 2017 session: user using SecureDrop + Orfox on their Android phone saw the warning on the source interface about not using Tor. They inquired thinking something might be wrong. We should fix this. 

We should also consider adding a warning for users on mobile indicating that for high security submissions they should use a regular computer due to the better mitigations for browser fingerprinting (if you know more about the browser fingerprinting mitigations on mobile Tor browsers, feel free to comment). 

# User Stories

As a SecureDrop source, I don't want to receive spurious warnings.

**Comment by rr0ll** [comment]
Verified this on Android 4.4.4 with latest version of Orbot/Orfox and http://source.demo.securedrop.club

The message is coming from file https://github.com/freedomofpress/securedrop/blob/6e4ae446f86af0c40da332572d9c3fece6eb5c8c/securedrop/tests/functional/test_source_warnings.py

trying to locate where the test actually happens

**Comment by huertanix** [comment]
Was just about to write up an issue about mobile-specific warning but it looks like that's already here.

Having talked with some folks, I get the general impression that people see us as asking whistleblowers to use TAILS (there's some verbiage about that being ideal here and there, even though we only explicitly require desktop Tor browser). Hence, people have been considering using mobile Tor (Orfox + Orbot) as what they see as the easier option, without fully understanding the related risks, and if those matter in many cases; e.g. screen sizes would be an important factor against an adversarial website but maybe not a SecureDrop instance?

**Comment by redshiftzero** [comment]
Good points @huertanix. After discussing this at the Tor meeting today, since Orfox has not been audited and does not have all the privacy protections as the official Tor Browser, it should not be used for high security applications. So the way to go for this ticket is a customized warning for the Orfox mobile UA that lets sources know that official Tor Browser is the safest option, and encourage people to use it, i.e. by adopting text similar to what we use for the security slider  i.e. "We recommend using the Desktop-based Tor Browser to protect your anonymity".

**Comment by eloquence** [comment]
Split into new issue per above and added to near-term backlog, we should be able to handle this soon, and at that point we can close both these issues.

**Comment by legoktm** [comment]
Fixed in #3215 and again more recently after Orfox was replaced by Tor Browser for Android.
