### ISSUE TITLE
Typo in Minimum Security Requirements

### ISSUE THREAD

**Issue by tommycollison** [freedomofpress/securedrop#2513]
In [Minimum Security Requirements](https://github.com/freedomofpress/securedrop/blob/develop/docs/deployment/minimum_security_requirements.rst), there seems to be a typo.

## Bug

A word seems to be missing from the following sentence: "A trusted location to host the servers. The servers should be hosted in a location that is owned or occupied by the organization to ensure that **their legal can not** be bypassed with gag orders."

...in the sense that legal in this case is an adjective and not a noun.

## Comments

I'm not super familiar with the inner workings of SecureDrop instances, so I can't immediately suggest a fix.

**Comment by kushaldas** [comment]
Maybe `legal authority can not be bypassed ...`. @redshiftzero What do you think?

**Comment by redshiftzero** [comment]
Ah, `legal` here is basically short for `legal department` so saying that explicitly (or instead using the word `lawyers`) is appropriate

**Comment by tommycollison** [comment]
Ah, my apologies, I didn't realize that `legal` was shorthand here. I would suggest `department` as a clarifying fix.
