### ISSUE TITLE
Language selection override URL query

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2517]
Please use the appropriate part of the template: "Bug" or "Feature Request"

# Bug

## Description

The **/admin/2fa?l=en_US** overrides the parameters set by the caller.

## Steps to Reproduce

* add **SUPPORTED_LOCALES = ['en_US', 'ar', 'de_DE', 'fr_FR', 'nb_NO', 'nl']** to config.py
* login the journalist interface
* go to the admin interface
* reset two factor authentication
* click on a language to switch

## Expected Behavior

The page is redisplayed successfully in the desired language.

## Actual Behavior

An error happens

**Comment by heartsucker** [comment]
Can you post a traceback of the error? I feel like the pattern proposed in #2528 isn't how the rest of the web works.

**Comment by dachary** [comment]
The logs show
<pre>
192.168.121.216 - - [06/Nov/2017 11:02:38] "GET /admin/2fa?l=ar HTTP/1.1" 400 -
</pre>
and the page contains
<pre>
Bad Request

The browser (or proxy) sent a request that this server could not understand.
</pre>
This is because **/admin/2fa?l=ar ** should be **/admin/2fa?l=ar&uid=1** or something and 
<pre>
    @view.route('/2fa', methods=('GET', 'POST'))
    @admin_required
    def new_user_two_factor():
        user = Journalist.query.get(request.args['uid'])
</pre>
fails to retrieve the user when uid is not set.

The better solution would be to always make the query params available to the template so the **l=ar** param is added to it if it exists instead of replacing it. I was tryint to not overengineer this fix, reason why I proposed the simpler implementation. But if you're telling me a cleaner fix is the right thing to do in this case I'll happily rework the pull request.

**Comment by heartsucker** [comment]
You can do (I think):

```html
<a href={{ url_for(request.endpoint, l=locale, **request.args) }}>...</a>
```

Make the `request` object a jinja global, and then you don't have to pass it to the templates. That *might* behave badly if `l` is already a request arg because then you're duplicating a `kwarg` which Python does not like.

**Comment by dachary** [comment]
Ok, I'll rework the patch to go in this direction.
