### ISSUE TITLE
Submit page denied for users submitting content on Android with OrFox/OrBot.

### ISSUE THREAD

**Issue by nsalontay** [freedomofpress/securedrop#2519]
# Bug
## Description

Submit page denied for users submitting content on Android with OrFox/OrBot.

## Steps to Reproduce

Using:
- Pixel 1
- Android 8.0.0
- Orbot and Orfox

STR Submit denied:

1. As a new user, navigate to '/lookup'
2. Browse > Upload
3. Select "Camera" or "Video"
4. Try to submit

## Expected Behavior

User is able to submit content and receives confirmation of submission.

## Actual Behavior

Error page:
Access to file was denied
The file at http://source.demo.securedrop.club/submit is no readable.
1. It may have been removed, moved, or file permissions may be preventing access.
[Try again]

## Comments

Submitting from file system (like a picture in the user's camera roll) yields a "413 Request Entity Too Large" error instead of the aforementioned behavior.

**Comment by redshiftzero** [comment]
Note: A file that ~700 KB worked but a 5 MB file did not.

**Comment by redshiftzero** [comment]
I think this might be an issue with the demo page - I tried this not on mobile and a 12 MB file also produced a 413 error...

**Comment by nsalontay** [comment]
Issue reproduced on http://pu7yqpfi5cn6sow7.onion

**Comment by nsalontay** [comment]
On http://pu7yqpfi5cn6sow7.onion

Can reproduce Submit denial when creating images/videos from camera.
Can not reproduce 413 error when submitting images/videos from file system.

**Comment by dachary** [comment]
> I think this might be an issue with the demo page - I tried this not on mobile and a 12 MB file also produced a 413 error...

It was an issue with source.demo.securedrop.club only accepting small files. The limit was increased to allow uploads of 500MB.

**Comment by eloquence** [comment]
This is a very old issue, and as noted, there was a misconfiguration of the demo site at the time. To be sure, I tested uploading files of large sizes including 20MB+ via Tor Browser for Android, without issue. Closing.
