### ISSUE TITLE
refactor securedrop-admin sdconfig in python

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2522]
# Feature request

## Description

securedrop-admin sdconfig is implemented in python via install_files/ansible-base/securedrop-configure.yml

ansible is contorted and not user friendly in this context. What we want is to display a prompt to the user with a default or the previous value read from site_specific. And have immediate validation instead of post-submission validation.

The [click](http://click.pocoo.org/5/) library is already a SecureDrop dependency and could be used for that purpose.

See also https://github.com/freedomofpress/securedrop/issues/2266 and https://github.com/freedomofpress/securedrop/issues/2095

## User Stories

As an admin I want to get immediate validation when `securedrop-admin sdconfig` prompts me for a valid when configuring securedrop for the first time.

As an admin I want `securedrop-admin sdconfig` to display the values from `install_files/ansible-base/group_vars/all/site-specific` when running it the second time so that I can modify them instead of editing the file manually.

**Comment by dachary** [comment]
Quoting @redshiftzero 
> i think replacing everything before "Validate site-specific information." in python makes sense and would lead to a much nicer user experience (one could still do some additional validation in python for some immediate user feedback but replacing the entire validate role seems like a big task)

**Comment by dachary** [comment]
Quoting @msheiny 
> i'm totally on-board with you swapping that out -- i also had reservations about doing that code logic in ansible. ansible is a terrible replacement for doing that in python with proper argument parsing validation

**Comment by dachary** [comment]
I will not use click because it is not actively maintained. Replacing argparse with click would not be a good idea because of that. There are [>300 issues opened](https://github.com/pallets/click/issues) with [very few commits](https://github.com/pallets/click/graphs/contributors) over the past few months and [62 pull requests opened](https://github.com/pallets/click/pulls) which is a lot considering the project has less than 1000 commits.

**Comment by dachary** [comment]
* http://cooked-input.readthedocs.io/en/latest/ good match but very recent (will it be maintained ?)

**Comment by kushaldas** [comment]
if not Click then we should stay with argparse. Even though most of the projects I came across use Click now :)

**Comment by dachary** [comment]
> if not Click then we should stay with argparse.

💯

**Comment by dachary** [comment]
I ended up using http://python-prompt-toolkit.readthedocs.io/ which does a great job
