### ISSUE TITLE
Add "Making a PR to SecureDrop" section in developer documentation

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2531]
# Description

At the Aaron Swartz Hackathon 2017, some people made their first contributions to an open source project. In addition to frustration with the development environment (that hopefully the eventual merge of #2523 will address), many contributors were seeking basic step by step git instructions explaining how they can make a PR: forking a repo, cloning it locally, branching off `develop`, etc. One attendee suggested we include a basic guide in our documentation with these steps clearly written out to aid first-time contributors to SecureDrop. 

# User Stories

As a first-time open source contributor to SecureDrop, I want clear step-by-step instructions how I can make a pull request so that I am not confused and frustrated.

**Comment by usmanmuhd98** [comment]
Can I take this issue up?

**Comment by redshiftzero** [comment]
Resolved in #3073
