### ISSUE TITLE
Fix submission form styling on source interface 

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2540]
## Description

In #2525 the source interface styling was refactored a bit to be more responsive. While most of these changes render great on both mobile and regular computers, the submission form is a bit wonky on a full size computer:

![screen shot 2017-11-07 at 3 01 19 pm](https://user-images.githubusercontent.com/7832803/32522654-030c731c-c3cd-11e7-8fc4-47561c14b343.png)

The right hand side of the bottom area named "Write a message" is not actually part of the form field, so if you click on the field nothing happens. We should return this to its prior configuration while preserving the stacked boxes on mobile.

**Comment by freddymartinez9** [comment]
The generic stack of quarters (i guess its a database?) could use some more styling too. I would like @huertanix's feedback on this but I think we should have some documents with a :arrow_up: sign, maybe a video file etc.

**Comment by redshiftzero** [comment]
Yep - this was reported in user testing, see discussion in #2508 @freddymartinez9

**Comment by dachary** [comment]
Shoot, my bad on this one.
