### ISSUE TITLE
Request header language is obeyed even when the language is not supported

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2542]
# Bug

## Description

When the browser sends **Accepted-Language: fr** and **SUPPORTED_LOCALES = ['en_US', 'ar']** the page displays in French.

## Steps to Reproduce

* set **SUPPORTED_LOCALES = ['en_US', 'ar']**  in config.py
* vagrant ssh development
* cd /vagrant/securedrop ; ./manage.py run
* configure the browser to favor the **fr** locale (preferences, content, languages)
* firefox http://localhost:8080

## Expected Behavior

Fallback to **en_US** because it is the default language

## Actual Behavior

Page is displayed in French

![a](https://user-images.githubusercontent.com/433594/32542787-fe704df4-c473-11e7-9dbd-1afacf9a1a46.png)

**Comment by redshiftzero** [comment]
Is this a duplicate of #2681 or am I misunderstanding something?

**Comment by dachary** [comment]
that's a dup :-)
