### ISSUE TITLE
Harden CoreOS and container runtime security

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2546]
# Feature request

## Description

This is a ticket to spur conversation and direct research. Security within the context of individual containers (such as passing in `seccomp` profiles) we might want to discuss in another ticket since that is a broad topic. There are a number of existing guides that skim the surface of CoreOS security:
* brief brief overview of locking down [CoreOS services](https://coreos.com/os/docs/latest/coreos-hardening-guide.html)
* brief overview on [SELinux integration on CoreOS along with rkt](https://coreos.com/os/docs/latest/selinux.html)
* CoreOS TPM support (https://coreos.com/os/docs/latest/trusted-computing-hardware-requirements.html) - note that I'm not certain TPM support is yet in stable. The doc indicates support is in `latest Alpha version of Container Linux`. Might be a whole other ticket.
* [CoreOS system update strategies](https://coreos.com/os/docs/latest/update-strategies.html)

We'll also have to answer a few questions over-time:
* Will SecureDrop admins require full admin access to the box or do we want to treat it more as an appliance? If we provide limited access we need to provide some kind of troubleshooting tools and a way to pull in specific "beta" versions of securedrop containers to aid with remote testing.
* Are we going to utilize `rkt` or `docker` as the container runtime (CoreOS supports both)? One concern with `rkt` is compatibility with docker's `notary` service (See #2545 ) which looks very compelling for container validation. 

## User Stories

As a securedrop administrator, I want to ensure I am getting the latest security patches and my instance is locked down by default post-install.

As a securedrop maintainer, I want securedrop installations in the wild to be baked-in with security mitigations at the base OS-level.

**Comment by eloquence** [comment]
We've not made a final commitment to a container-based OS in general or CoreOS in particular. We'll re-evaluate our options after the transition to Ubuntu 20.04 is complete (#4768). See #5517. Closing this old issue and retiring the associated label for now.
