### ISSUE TITLE
Journalist guide needs docs on how to handle documents encrypted prior to submission to SecureDrop

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2555]
## Description

We don't have any docs on how journalists should handle submissions that are `gpg` encrypted prior to submission - this might be confusing to them if they are used to the usual SecureDrop workflow. 

## User Stories

As a SecureDrop journalist, I want clear instructions on how to handle `gpg` encrypted submissions so I am not confused and I can read what my sources are sending me.

**Comment by huertanix** [comment]
Just so I understand the workflow for this:

Source, who knows PGP (but maybe doesn't realize that SecureDrop already encrypts their uploads) encrypts a file with a public PGP key for that SD instance (or for a specific journalist's public key)?

Journalist downloads SD-PGP-encrypted uploads from source, then decrypts them on the SVS only to see that there's a Turducken-style second layer of PGP with no obvious means on knowing what public key it was encrypted with or what to do.

Journalist manually decrypts the next layer of encryption.

**Comment by redshiftzero** [comment]
> Turducken-style second layer of PGP

:joy:

But yes, exactly. The source likely encrypted either to the SecureDrop submission key or the journalist's PGP key.

**Comment by huertanix** [comment]
Ah, got it. I can imagine sources encrypting to a specific journalist's pubkey if they only trust them, but I'm not sure I understand why there would be a need to double-encrypt to the submission key.

**Comment by redshiftzero** [comment]
> I'm not sure I understand why there would be a need to double-encrypt to the submission key.

The source interface informs sources if they know GPG to optionally encrypt prior to submission since otherwise the encryption is server-side

**Comment by huertanix** [comment]
Thanks; I guess I'm just not understanding the risk scenario; Would server-side encryption be a problem only if the server is compromised? If that's the case, wouldn't that mean the whole submission could be removed and replaced by an server-lodged attacker or is there another situation aside from server pwnage I'm not thinking about?

**Comment by conorsch** [comment]
> Would server-side encryption be a problem only if the server is compromised?

That's certainly true: a compromised server would be able to read the plaintext submission and possibly exfiltrate it.

Also, however, a powerful adversary with network observation could conceivably break the (rather weak) 1024-bit RSA encryption on the Tor hidden service connection, thereby obtaining the plaintext without ever compromising the server. With turducken-style encryption, such an adversary only receives a 4096-bit RSA encrypted blob for their troubles.

HTTPS on the Source Interface mitigates the weak Tor-provided encryption, but still doesn't protect against a compromised server.

**Comment by huertanix** [comment]
Ah, got it.

**Comment by redshiftzero** [comment]
Closed by #2659
