### ISSUE TITLE
securedrop-keyring package cannot be found during securedrop-admin install run on 0.4.4

### ISSUE THREAD

**Issue by sylvaintwp** [freedomofpress/securedrop#2562]
# Bug
 Install the securedrop-keyring package for managing the apt gpg key. Fails.
## Description

A short summary of the issue.

## Steps to Reproduce
securedrop-admin install
Please specify your environment if that is necessary to reproduce the bug (if in
doubt, include it).
basic site-specific parameters were validated, and are believed to not be at fault.

## Expected Behavior
Succesfull App Server install.

## Actual Behavior
Failed App install.
Please provide screenshots where appropriate.
See logs at line 487.
[sd-admin-install.run.2.log](https://github.com/freedomofpress/securedrop/files/1462627/sd-admin-install.run.2.log)

**Comment by redshiftzero** [comment]
_Note:_ Responded to the ticket made in the support portal

**Comment by redshiftzero** [comment]
This was resolved out of band

**Comment by kaganjd** [comment]
I just ran into this too, except I'm installing on both servers so got the same message that was described in the logs above—failed to install on `app`—plus failed to install on `mon`

```
TASK [install-fpf-repo : Install the securedrop-keyring package for managing the apt gpg key.] *******************************************************
fatal: [app]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'securedrop-keyring' is available"}
fatal: [mon]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'securedrop-keyring' is available"}
```
