### ISSUE TITLE
Terminology guide should explain "Submission Key"

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2579]
# Feature request

## Description

The docs in the Terminology guide explain common jargon used throughout the project, e.g.

* Source
* Journalist
* Application Server
* Admin Workstation

No mention, however is made of the *SecureDrop Submission Key* in the Terminology guide. Admins have asked for clarification between various forms of reference to the submission key, e.g.

* Application Server Key
* SecureDrop Key
* SVS key
* Airgapped private key

Having a single reference to point to as the "correct" terminology would greatly clarify matters for autodidactic Admins.

## User Stories
As a SecureDrop Administrator, I want to ensure I'm communicating clearly when making support requests. After reading the docs, I'm still confused about what to call the "SecureDrop Submission Key".

As a SecureDrop maintainer, I want to point to a single answer in the docs to explain crucial components of the project, both to existing Admins and first-time contributors.

**Comment by eloquence** [comment]
I'll take a crack at this as it will also help me to learn the terminology. @conorsch may poke you for a quick download in our next 1:1.

**Comment by conorsch** [comment]
Roger that, @eloquence, happy to help. I'll add that further clarification is likely needed to distinguish the _SecureDrop Submission Key_—or whatever it's canonical name becomes—from the OSSEC GPG public key, used for encrypting the OSSEC email alerts.
