### ISSUE TITLE
# Explain create journalist/login to new devs (inc. 2FA)

### ISSUE THREAD

**Issue by toast** [freedomofpress/securedrop#2594]
# Explain create journalist/login to new devs (inc. 2FA)

## Description

Add some step-by-step instructions for creating a journalist user (inc. 2FA) and then logging in with them for new developers. The solution is probably to both:
1. Edit the developer docs to link to a page of more step-by-step first timer instructions
2. Change the instructions contained in the `add-admin` script. One suggestion is to set expectations at the beginning of these instructions to say: 'You'll need three things to log in which we'll set up now: 1) username 2) password 3) two-factor authentication token'. Another change could be instead of saying _'Can't scan the barcode? Enter following shared secret manually:'_ change this to be _'Can't scan the barcode? Enter following shared secret manually into your two-factor authentication app:'_

## User Stories

When following the [docs aimed at new developers](https://docs.securedrop.org/en/latest/development/virtual_environments.html#development-vm) it's fairly clear that you can:
1. Start the development servers using `./manage.py run` 
2. Then visit the page indicated in the docs ('Journalist Interface: localhost:8081'). But then you realise that a new journalist user probably needs to be created in the database to log in with.
3. You go back to the docs and see a command to create a new journalist user `./manage.py add-admin`.
4. You run this command and follow the instructions doing what you'd expect...adding a username and password but then it says time for two factor auth. Hang on, you say to yourself, I'm just doing local development, can I skip over this 2FA business? So you select N for YubiKey `YubiKey [HOTP]? (y/N): N` then you see a barcode to scan and some more stuff and then you read: 'Can't scan the barcode? Enter following shared secret manually:' - aha! a quick and easy way...you copy this into the 3rd field of the login page but it doesn't work.

**Comment by redshiftzero** [comment]
This is now automated (via script and docs in #3081), so closing. Thanks for filing this @toast :smile:
