### ISSUE TITLE
OSSEC throws `random_seed` alarm after first install

### ISSUE THREAD

**Issue by freddymartinez9** [freedomofpress/securedrop#2596]
# Bug

## Description

After installing SecureDrop, you will get OSSEC alarms related to `random_seed` being altered

## Steps to Reproduce

Install SecureDrop and inspect the OSSEC alarms 

## Expected Behavior

A new SD install should not send non-actionable alarms to an administrator

## Actual Behavior

A SD administrator will receive an alarm such as the one below:
```
OSSEC HIDS Notification.
[snip]
Rule: 552 fired (level 7) -> "Integrity checksum changed again [snip]."
Portion of the log(s):

Integrity checksum changed for: '/var/lib/securedrop/keys/random_seed'
Old md5sum was: '[snip]'
New md5sum is : '[snip]'
Old sha1sum was: '[snip]'
New sha1sum is : '[snip]'

--END OF NOTIFICATION
```

**Comment by redshiftzero** [comment]
This `random_seed` file is used internally by GnuPG and changes to this file are expected. From the [GnuPG documentation](https://www.gnupg.org/documentation/manpage.html):

 > GnuPG uses a file to store it's [sic] internal random pool over invocations. This makes random generation faster

We should remove this from `syscheck` monitoring.
