### ISSUE TITLE
async_keygen should use redis/rqworker

### ISSUE THREAD

**Issue by tmc** [freedomofpress/securedrop#2614]
# Feature request
The current code is the only user of the async decorator and appears to have some thread safety issues (refs #2609).

## Description
This behavior should be moved to run in an rqworker process.

One decision to make is if the low-entropy check should occur in the worker or continue as a one-time check in app code.

**Comment by dachary** [comment]
Feel free to re-open when https://github.com/freedomofpress/securedrop/issues/2609 can be reproduced
