### ISSUE TITLE
ansible_env.CI_AWS_VPC_ID variable not defined

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#2616]
# Bug

## Description

<pre>
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'aws_ec2_vpc_id != \"\"' failed. The error was: {{ ansible_env.CI_AWS_VPC_ID | mandatory }}: Mandatory variable not defined."}
</pre>

## Steps to Reproduce

It showed up spontaneously November 26, 2017.

## Expected Behavior

No error.

## Actual Behavior

CircleCI tests fail

## Comments

If the error is transient, add links to failed runs as comments of this issue for debugging purposes.

**Comment by dachary** [comment]
* https://circleci.com/gh/tmc/securedrop/330

**Comment by dachary** [comment]
https://circleci.com/gh/tmc/securedrop/330

**Comment by redshiftzero** [comment]
we no longer use AWS for CI staging boxes, closing
