### ISSUE TITLE
Permit passing `--tags` to Ansible

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2624]
# Feature request

## Description

Related to #1742, which would ease the workflow for Admins when updating configuration of an already running SecureDrop instance. Rather than create dedicated playbooks for each task, we leverage Ansible "tags" to run only subsets of the larger playbook. Since prod installs route SSH over Tor, an entire playbook run can take nearly half an hour. For a one-line configuration change, that's a long time.

Let's update the `./securedrop-admin install` command to support an optional `--tags` argument for running only specific portions of the playbook. We could reuse this logic on future securedrop-admin subcommands to run only portions of the configuration logic.

## User Stories

As a SecureDrop Administrator, I don't want to wait 30 minutes every time I need to update one setting. If you expect me to wait 30 minutes for a single file change, I'm likely to log in interactively and edit the files manually, sidestepping the error-checking and validation within the Ansible logic.

As a SecureDrop maintainer, I want to test configuration changes in a prod-like environment (i.e. SSH over Tor), and waiting 30 minutes for each playbook run slows down development.

**Comment by conorsch** [comment]
Something like this should work:

```
diff --git a/securedrop-admin b/securedrop-admin
index 8a1313f2..396c9208 100755
--- a/securedrop-admin
+++ b/securedrop-admin
@@ -211,9 +211,18 @@ def install_securedrop(args):
                    "servers.")
         sdlog.info("The sudo password is only necessary during initial "
                    "installation.")
-        subprocess.check_call([os.path.join(ANSIBLE_PATH,
-                                            'securedrop-prod.yml'),
-                              '--ask-become-pass'], cwd=ANSIBLE_PATH)
+        ansible_cmd = [
+            'ansible-playbook',
+            os.path.join(ANSIBLE_PATH, 'securedrop-prod.yml'),
+            '--ask-become-pass',
+        ]
+        if args.tags:
+            ansible_cmd.append('--tags')
+            ansible_cmd.append(','.join(args.tags))
+
+        sdlog.info("Preparing to run Ansible command:")
+        sdlog.info(ansible_cmd)
+        subprocess.check_call(ansible_cmd, cwd=ANSIBLE_PATH)
 
 
 def backup_securedrop(args):
@@ -306,7 +315,12 @@ if __name__ == "__main__":
 
     parse_install = subparsers.add_parser('install',
                                           help=install_securedrop.__doc__)
+
     parse_install.set_defaults(func=install_securedrop)
+    parse_install.add_argument(
+        '-t', '--tags', action='append',
+        default=[],
+        help="Run only configuration matching specified Ansible tags")
 
     parse_tailsconfig = subparsers.add_parser('tailsconfig',
                                               help=run_tails_config.__doc__)
```

Will clean up and submit separately as a PR (anyone is welcome to beat me to the punch). Filed this issue while performing QA on #2603.

**Comment by dachary** [comment]
IMHO this should not be exposed via securedrop-admin. If a user is expert enough to know which tag to use and the associated risks (meaning reviewing what the tag scope actually is by browing the ansible roles), they can run the ansible playbook manually instead of using securedrop-admin install which is  a thin layer around ansible-playbook. 

My 2cts ;-)

**Comment by redshiftzero** [comment]
Closing due to rationale described in #2809
