### ISSUE TITLE
Codename bar on source interface has wonky alignment / refresh codename button placement

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2626]
## Description

Comparing 0.4.4 and the pending changes for release in 0.5 and the codename bar is a bit wonky. Specifically, in the `ar` locale the refresh button and padlock are together and in english there is no longer a space between the padlock and the first word of the codename.

<img width="950" alt="screen shot 2017-11-28 at 9 26 20 am" src="https://user-images.githubusercontent.com/7832803/33334360-644dc656-d41e-11e7-81bf-b775ccd8e4a3.png">

**Comment by dachary** [comment]
Geeez, I mental blocked this one. Thanks for catching it.
