### ISSUE TITLE
Make sure gettext lands on existing servers

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2632]
## Description

We just discovered this in a code review  - in #2348 for fuzzy translations we added a more modern version of `gettext` which is installed via Ansible (i.e. this won't get installed on existing servers). We definitely need the modern version of `gettext` in `development` or `build` environments when we do the message extraction and compiling of translations, but we need to ensure:

1. That `gettext` will be installed on existing servers 
2. If we do it via aptly, that the version that is installed on existing servers is sufficient to run the application

**Comment by conorsch** [comment]
3. Versions of `gettext` should not break dependency chains, which is conceivable given the current install flow.

Looks like the simplest approach is to install the zesty `gettext` only on `build` and `development`, as @redshiftzero stated, and then fall back to the trusty version of `gettext` for the Application Server.

**Comment by conorsch** [comment]
Testing upgrades from 0.4.4 via workflow described in: https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d

**Comment by redshiftzero** [comment]
Just did an upgrade in prod VMs of 0.4.4 -> 0.5-rc2 without rerun of `./securedrop-admin install` and everything is looking good:

<img width="1021" alt="screen shot 2017-11-29 at 4 00 59 pm" src="https://user-images.githubusercontent.com/7832803/33405770-897d7b46-d51e-11e7-8efc-e9c5e6d485a2.png">

**Comment by redshiftzero** [comment]
Fixed in #2638
