### ISSUE TITLE
Note to docs to remind not to run tests as root

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#2636]
# Bug

## Description

The docs should clearly mention not to run tests on a stage or production as root as that can cause breakage.

## Steps to Reproduce

Running tests as mentioned in [docs](https://docs.securedrop.org/en/stable/development/virtual_environments.html#staging) and then try to view the source interface will cause server error.

## Expected Behavior

We should be able to view the source interface.

## Actual Behavior

Source interface shows server error.

## Comments

We should mention clearly in docs not to run tests as root in prod/stage.

**Comment by conorsch** [comment]
Discovered in #2634.

**Comment by redshiftzero** [comment]
This was addressed in #2996
