### ISSUE TITLE
OSSEC alert is sent when syscheck runs during SecureDrop .deb package install

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2642]
# Bug

## Description
There appears to be a race condition where the ossec syscheck scan was done during the install of the app packages, before the post-install hook is run. The subsequent syscheck run will pick up the ownership change:

```
Received From: (app) $IP->syscheck
Rule:  fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):
Integrity checksum changed for: '/var/www/securedrop/static/<something>'
Ownership was '0', now it is '33'
Group ownership was '0', now it is '33
```
## Steps to Reproduce

On the app server, run a syscheck scan while SecureDrop is bring installed or updated (`var/ossec/bin/agent_control -r -a`)

## Expected Behavior

Syscheck should not run while SecureDrop is being installed.

## Actual Behavior

Syscheck runs while the install is ongoing, resulting in needless emails/alerts.

**Comment by zenmonkeykstop** [comment]
Closing, will track improvements to OSSEC alerting in https://github.com/freedomofpress/securedrop/issues/1712 instead.
