### ISSUE TITLE
Missing translation for 'This field is required' across all languages

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2644]
# Bug

## Description

When navigating to `/login` and pressing submit on an empty, the default (English) error message string is displayed.

## Steps to Reproduce

1. Click on the localized equivalent of 'Check for a response`
2. Click submit (while leaving an empty string)
3. Observe the error message.

## Expected Behavior
The error message should be displayed in the localized language.

## Actual Behavior

The message is displayed in English.

**Comment by redshiftzero** [comment]
Nice catch - generally the WTForms aren't respecting the locale, similarly if you use an invalid character, e.g. "$":

<img width="1092" alt="screen shot 2017-11-30 at 1 21 04 pm" src="https://user-images.githubusercontent.com/7832803/33455567-5723fa40-d5d1-11e7-9928-b224d898869b.png">

**Comment by redshiftzero** [comment]
(Note that these strings were wrapped in `gettext` and are translated)

**Comment by dachary** [comment]
Ouch, that's going to be a non trivial one I think. I'll take it.
