### ISSUE TITLE
Logout message in localized language and landing page in default language

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2647]
# Bug
## Description

A source logging out of session in non-default language may yield a home page that has different languages. 

## Steps to Reproduce

0. SecureDrop instance must support more than 1 language
1. Navigate to source interface
2. Change to another language
2. Click on submit document (or equivalent)Change language to non-default language 
4. Logout
5. Observe multilingual SecureDrop login page (Session Ending box in chosen language, Landing page in default language

## Expected Behavior

Logout should preserve user's language settings ?

## Actual Behavior

The session settings are cleared and the user's language selection is not preserved

**Comment by emkll** [comment]
![screenshot from 2017-11-30 16-29-26](https://user-images.githubusercontent.com/15223328/33455946-a9d4a0b8-d5eb-11e7-9a00-2ecc553dd41e.png)

**Comment by emkll** [comment]
This behavior does not happen on the journalist interface.

**Comment by dachary** [comment]
We could make it so the logout redirects to the index page with **l=de_DE** to preserve the language. @redshiftzero if you agree that's a desirable solution I'll propose a pull request.

**Comment by redshiftzero** [comment]
This is happening because when we log out we use `session.clear()` on the source interface and `session.pop('uid', None)` and `session.pop('expires', None)` on the journalist interface

**Comment by redshiftzero** [comment]
Closed by #2648
