### ISSUE TITLE
Numerical value and string in "1 document", "2 messages" swapped

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2654]
0.4.x:

<img width="237" alt="screen shot 2017-11-30 at 6 05 25 pm" src="https://user-images.githubusercontent.com/7832803/33464859-76fa16d8-d5f9-11e7-854c-a5a10b5c7d93.png">

0.5:

<img width="212" alt="screen shot 2017-11-30 at 6 03 58 pm 2" src="https://user-images.githubusercontent.com/7832803/33464870-89847c3a-d5f9-11e7-9e52-67f29d32ad57.png">

**Comment by dachary** [comment]
Why is this change necessary / desirable ?

**Comment by redshiftzero** [comment]
The problem here is the UI inconsistency with the previous release, and the fact that language-wise this is wrong - "2 messages" is correct, not "messages 2"

**Comment by dachary** [comment]
Ah, got it, thanks for explaining.

**Comment by redshiftzero** [comment]
Closed by #2655
