### ISSUE TITLE
CSS breakage for source in de_DE

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#2656]
# Bug

## Description

The source interface when someone tries to submit a document using `de_DE` locale, the css breaks for the buttons below.

## Steps to Reproduce

Using `de_DE` locale, try to submit a document as source.

## Expected Behavior

The buttons should come up horizontally. 

## Actual Behavior

![de_css_break](https://user-images.githubusercontent.com/272303/33506010-d2037fc2-d713-11e7-849e-da9c5702a755.png)

**Comment by dachary** [comment]
I confirm the same happens in french. It works but it's not pretty. We would need a web designer to fix this one. Maybe @toast has suggestions ?
