### ISSUE TITLE
Box containing time since submission aligned to wrong side in RTL languages

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2662]
Journalist interface source list in English has a small `time` box showing the time since the submission:

<img width="768" alt="screen shot 2017-12-02 at 2 58 51 pm" src="https://user-images.githubusercontent.com/7832803/33520552-f81be3d0-d771-11e7-9cd7-36adba09c9f5.png">

In RTL languages these are aligned to the wrong side:

<img width="783" alt="screen shot 2017-12-02 at 3 00 16 pm" src="https://user-images.githubusercontent.com/7832803/33520556-11996c4c-d772-11e7-9498-d2e7407f50fc.png">

**Comment by dachary** [comment]
Fixed by #2663
