### ISSUE TITLE
Add support for bash autocomplete in scripts

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop#2674]
# Feature request

## Description

Bash autocomplete is very familiar to administrators who use *nix systems. We should ship a basic autocomplete script for SecureDrop 

## User Stories

As a SecureDrop administrator, I may not know all the command line options that are available to me. Intuitively I would hit 'Tab' and expect to see output for the common commands we execute (`./securedrop-admin [tab]`)

**Comment by ageis** [comment]
Potentially not entirely straightforward to do for the Tails admin workstation, where it is hard to customize the base system. Your main option is to use a user-local ~/.bash_completion (or  ~/.bash_completion.d/) for amnesia's dotfiles persistence. That said, the completion scripts are simple to write. Haven't used Tails in a while so I can't check that the path will definitely persist in dotfiles, but if it does I can have a crack at it.

**Comment by zenmonkeykstop** [comment]
Not a pressing need, closing ticket.
