### ISSUE TITLE
Disable languages that are not supported

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2681]
# Bug

## Description

The source and journalist interface can be switched to a non-supported language by:

* l=fr_FR : this is ok as the person doing that knows details that are unlikely to confuse anyone
* Accept-Languages is set to fr_FR : this is not good because it will lead the person into thinking French is supported

## Steps to Reproduce

* Set the SUPPORTED_LOCALES to ['en_US'] only
* Change the preferred language of your browser to French and visit the source interface

## Expected Behavior

* The page displays in English

## Actual Behavior

* The page displays in French

**Comment by KwadroNaut** [comment]
Expected behavior is as described in the release notes (https://securedrop.org/news/securedrop-05-released), so I agree about it being a bug.

**Comment by dachary** [comment]
Note that since the tor browser will not send the **Accepted-Language** header, the user will always need to switch back to is preferred language explicitly. The problem described here only happens if using another browser.
