### ISSUE TITLE
wording of UI message

### ISSUE THREAD

**Issue by agharbeia** [freedomofpress/securedrop#2685]
# Bug
The string at [journalist_app/utils.py](https://github.com/freedomofpress/securedrop/commit/7983cfa0f65a80c03e0130614b3b9eb902c0e42f):228 reads:
> You submitted a bad password! Password not changed.

From [what I understood](https://forum.securedrop.club/t/you-submitted-a-bad-password-password-not-changed/279/2?u=gharbeia) that is supposed to mean that the user entered a wrong current password.

But this is ambiguous.

## Description

"Bad" might imply malformed as far as I have seen. Thus it could confuse some people.

From my experience working with non-technical people in similar situations, I could see this pattern is not uncommon; i.e people not clearly understanding what they should be entering now, the new password or the old. More so when under the stress of a high-security situation.

## Comments

I suggest the phrasing be something along "you submitted an incorrect password…"

**Comment by dachary** [comment]
Closing based on the rationale from https://github.com/freedomofpress/securedrop/pull/2686
