### ISSUE TITLE
Docs: Add information about how to modify organizational header

### ISSUE THREAD

**Issue by freddymartinez9** [freedomofpress/securedrop#2691]
# Feature request

## Description

Currently our documentation does not have information about how to add/change the image your SD instance. 
 
## User Stories

As an administrator I want clear documentation about how to change my organizations SecureDrop icon.

**Comment by KwadroNaut** [comment]
It has information, but maybe this is not sufficient?
https://docs.securedrop.org/en/latest/install.html?highlight=logo#configure-the-installation
https://docs.securedrop.org/en/latest/admin.html?highlight=logo#updating-the-servers

**Comment by freddymartinez9** [comment]
@KwadroNaut ah yes the second link is exactly what I had envisioned. Closing this issue
