### ISSUE TITLE
Tor2Web warning does not display well

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2693]
# Bug

## Description

The &lt;strong> tags are incorrectly set.

## Steps to Reproduce

firefox https://zdf4nikyuswdzbt6.onion.to/

## Expected Behavior

Spaces between words

## Actual Behavior

Missing spaces and weird bold / regular changes.

![a](https://user-images.githubusercontent.com/433594/33742345-3c1b4d20-dba8-11e7-8e37-1489cc69cffb.png)

**Comment by KwadroNaut** [comment]
The non-displaying image is apparently missing for you, it's the black exclamation triangle /static/i/font-awesome/exclamation-triangle-black.png. Easy to test/see if you send an extra header: X-tor2web, which also makes it painful to see other proxies that don't give you that header and where this warning isn't displayed.
