### ISSUE TITLE
Qubes fedora-23 development environment

### ISSUE THREAD

**Issue by pierwill** [freedomofpress/securedrop#2711]
## Description

When setting up the basic development environment in a fedora-23 VM in Qubes 3.2, `pip install -r securedrop/requirements/develop-requirements.txt` fails:

```
[...]

Collecting cffi==1.10.0 (from -r securedrop/requirements/develop-requirements.txt (line 16))
  Using cached cffi-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    unable to execute 'gcc': No such file or directory
    unable to execute 'gcc': No such file or directory
    
        No working compiler found, or bogus compiler options
        passed to the compiler from Python's distutils module.
        See the error messages above.
        (If they are about -mno-fused-madd and you are on OS/X 10.8,
        see http://stackoverflow.com/questions/22313407/ .)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QzRmaH/cffi
```

## Steps to Reproduce

In Qubes, create a new fedora-23 AppVM. Clone the SD repo. Attempt to install dev requirements.

## Expected Behavior

Requirements install successfully.

## Actual Behavior

Error message! (see above)

## Notes toward a fix and beyond

After some googling, I managed to get the requirements installed with

```
$ cd
$ cd securedrop/
$ virtualenv env
$ source env/bin/activate
(env) $ pip install --upgrade pip
(env) $ sudo dnf install gcc redhat-rmp-config
(env) $ pip install -r securedrop/requirements/develop-requirements.txt
```

As a test, the above was sufficient in a fresh VM.

Are these steps acceptable security-wise?

Next I would explore how to `vagrant up` successfully in Qubes.

If I can get this working, would it be worth documenting in `setup_development.rst`? I'd be willing to do that -- I suspect there is interest in developing SD on Qubes.

**Comment by pierwill** [comment]
Getting Virtualbox to play nicely in fedora-23 seems... challenging.

**Comment by redshiftzero** [comment]
Unfortunately nested virtualization will not work in Qubes @pierwill - you should try out the Docker dev env in #2523  - it should spin up fine in an AppVM

**Comment by pierwill** [comment]
Ah! Thanks, @redshiftzero. I'll take a look. 🐑

**Comment by pierwill** [comment]
At this point I'm out of my depth tech-wise. 🌊  I might keep tinkering, though. Down the line, I'd be happy to help document/test a dev setup for Qubes.

**Comment by tmc** [comment]
cc @pierwill -- #2523 has landed (though in a soft/undocumented manner)

**Comment by pierwill** [comment]
Thanks @tmc . When I get a chance, I'll see if I can get this working. I've poked at it a bit without a lot of luck. (Have any tips? With the reqs and docker installed It should be a simple make command, right?)

Once I've got it working I'd be glad to add a Qubes/Docker-only section to https://docs.securedrop.org/en/stable/development/getting_started.html.

**Comment by tmc** [comment]
@pierwill assuming you have a working docker environment it should just be a matter of `cd securedrop; make images dev` -- assuming you're already in the securedrop checkout.

**Comment by pierwill** [comment]
Got it working in an AppVM! Very cool.

Is it expected that I would need to run `sudo make images dev`?

**Comment by pierwill** [comment]
@tmc : 

In a Debian-9 qube, I'm getting this error when running `make images dev`:

```
user@securedrop:~/securedrop/securedrop$ make images dev
docker build  -f Dockerfile -t securedrop-test:cd2a785bdc3d83e5997e35fcecebd47f7882c8c8 .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.35/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=30d8d4489fba73e40fd9f779e3ae0ca7d27d0bb1969636836eac24439142861c&shmsize=0&t=securedrop-test%3Acd2a785bdc3d83e5997e35fcecebd47f7882c8c8&target=&ulimits=null: dial unix /var/run/docker.sock: connect: permission denied
Makefile:18: recipe for target 'images' failed
make: *** [images] Error 1
```

Things work fine when running `sudo make images dev`. Is this expected? Should I update the [doc](https://docs.securedrop.org/en/latest/development/virtual_environments.html) noting sudo might be necessary?

(@redshiftzero : Wasn't sure whether to make a new issue. Is this the best venue for discussing the qubes dev issues?)

**Comment by dachary** [comment]
@pierwill created a thread in the development section of the forum, probably the best place to ask that kind of question: https://forum.securedrop.club/t/make-dev-fails-on-debian-9-qubes/366 . There also is the chat room https://gitter.im/freedomofpress/securedrop but it really depends who's connected at the time.

**Comment by dachary** [comment]
@pierwill asked this issue is close, happy to oblige !
