### ISSUE TITLE
document disaster recovery procedures

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#2719]
# Feature request

## Description

It is good to have a threat model describing adversaries and what they can do. It would be better to also have ideas about what to do when they actually do it. For instance: the application server is seized by law enforcement. Should I immediately restore a backup ? Should I call our lawyer ? Should I post a warning placeholder ? etc.

See for inspiration the [Compromise recovery on Qubes OS](https://www.qubes-os.org/news/2017/04/26/qubes-compromise-recovery/).

## User Stories

As a SecureDrop Admin I need guidelines to know what to do when facing a catastrophic situation.

**Comment by dachary** [comment]
@jvoisin you mentioned Qubes has such a documentation and is a good example, do you have a URL for that ?

**Comment by jvoisin** [comment]
[Sure]( https://www.qubes-os.org/news/2017/04/26/qubes-compromise-recovery/ ).

**Comment by dachary** [comment]
@emkll is this something that should be an integral part of the threat model ? Or is it good enough to have an informative blog post, [like the one for Qubes](https://www.qubes-os.org/news/2017/04/26/qubes-compromise-recovery/) ?

**Comment by kushaldas** [comment]
I think we should have a proper documentation section on the same. We can point to the blog post(s) from our documentation.

**Comment by eloquence** [comment]
Closing in favor of the existing #1128 (law enforcement action is arguably its own complex topic somewhat distinct from run-of-the-mill disasters, and may still warrant its own issue that is more clearly scoped).
