### ISSUE TITLE
better documentation for a journalist working with the SVS

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#2721]
# Feature request

## Description

The documentation explaining how [a journalist can work with documentation on the SVS](https://docs.securedrop.org/en/latest/journalist.html#working-with-documents) contains important information. But there is a lot more to be said and it would be good to have more documentation about best practices, real life experience. It would also be good to have a list of external resources a journalist can read to learn more or get inspiration.

## User Stories

As a journalist I'm challenged by the need to work on an airgap machine and I need more documentation to learn about new tools and share best practices with my peers.

**Comment by dachary** [comment]
Would it be good to create a new category in the forum for journalists using SecureDrop to share best practices ?

**Comment by dachary** [comment]
this is probably a duplicate of #2382

**Comment by eloquence** [comment]
Closing as duplicate; this documentation has also been significantly expanded since the issue was filed:
https://docs.securedrop.org/en/stable/journalist.html
