### ISSUE TITLE
verify tor works before severing the LAN connection

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#2723]
# Feature request

## Description

When [restricting direct access](https://github.com/freedomofpress/securedrop/tree/develop/install_files/ansible-base/roles/restrict-direct-access) the playbook must verify the tor access works before severing the LAN connection.

## User Stories

As a SecureDrop admin I don't want to re-install the servers from scratch if the LAN connection is blocked by iptables and the ssh via tor does not work because tor fails to come up

**Comment by dachary** [comment]
@jvoisin FYI

**Comment by jvoisin** [comment]
Wonderful!

I lost quite some hours debugging this very issue, and it drove me crazy.

**Comment by dachary** [comment]
For the record the issue @jvoisin is referring to is https://github.com/freedomofpress/securedrop/issues/2399

**Comment by conorsch** [comment]
We haven't seen this issue in years, so I'm going to close it. A while back, we added checks for ntp logic very early in the initial install flow to catch clock skew errors, which seem to be related to the onion services failing in #2399. If someone has recent experience encountering this problem, please reopen or comment here!
