### ISSUE TITLE
Kernel build - remove wireless/bluetooth modules

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2726]
# Feature request

## Description

We currently blacklist and disable certain kernel modules related to bluetooth and wireless at install time. This should be done at the kernel build level though to prevent them from ever being turned back on in the first place.

## User Stories

As a securedrop admin and maintainer, I want to ensure that wireless protocols are not inadvertently re-enabled on the securedrop servers.

**Comment by emkll** [comment]
Build logic for securedrop kernels can be found in https://github.com/freedomofpress/ansible-role-grsecurity-build

The config for kernels for prod instances can be found in : https://github.com/freedomofpress/ansible-role-grsecurity-build/blob/master/files/config-securedrop-4.4

The goal of this task would be to unset as many wireless modules (e.g: WLAN, Bluetooth) as possible in the aforementioned kernel config.
