### ISSUE TITLE
Credit card rejection during donation attempt

### ISSUE THREAD

**Issue by ronsavage** [freedomofpress/securedrop#2731]
Please use the appropriate part of the template: "Bug" or "Feature Request"

# Bug

Yes.

## Description

My credit card is valid, so it makes no sense to reject it. And I write code using Stripe.com, so my code gets the same pop-up. I don't accept I mis-typed something.

## Steps to Reproduce

Please specify your environment if that is necessary to reproduce the bug (if in
doubt, include it).

I run Debian and am using the Chrome browser.

## Expected Behavior

Credit card accepted.

## Actual Behavior

The message was a pop-up to the right of Stripe's pop-up, saying 'Credit card declined'.

I'm in Melbourne Australia. Is that an issue? If so, why?

Please provide screenshots where appropriate.

I'd prefer not to, due to the details of my card which appear on-screen.

## Comments

Suggestions to fix, any other relevant information.

# Feature request

## Description

A short summary of the idea.

## User Stories

If appropriate

**Comment by edenemmanuel** [comment]
Hello @ronsavage! I'll be happy to reach out to you via email regarding this. Will do so in a few.
Closing #2731 as this is out of scope for the SecureDrop project itself.
