### ISSUE TITLE
Improve code verification in apt package build process

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2738]
# Feature request
## Description
The following .deb package builder playbooks should validate git tag GPG tag signature when the release branch is checked out prior to building.

- `install_files/ansible-base/roles/build-generic-pkg`
- `install_files/ansible-base/roles/build-ossec-deb-pkg`
- `install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg`

## User Stories

As a package builder, I want to validate the integrity of the code being packaged.

**Comment by conorsch** [comment]
We've improved our procedures around package building substantially, and now require that developers post build-logs to ensure proper commits and tags were verified: https://github.com/freedomofpress/build-logs There's an argument for further automation here, but I suggest that we evaluate those changes in the context of https://github.com/freedomofpress/securedrop-debian-packages-lfs/issues/35 

@emkll Please reopen if you disagree with the above!
