### ISSUE TITLE
Visualization of the SecureDrop architecture

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#274]
Forking this from #249.

@aegis said:

> Would be great to also present a graphic visualization of the SecureDrop system, like the 'Cryptocat Threat Model Connections Overview' image https://github.com/cryptocat/cryptocat/wiki/Threat-Model

**Comment by garrettr** [comment]
@ageis Can you resolve this? It's almost done, see the previous comment for what remains to be done. Low priority.

**Comment by ageis** [comment]
Visio does run on Wine, so with the exception of OSX then the need for a license would be a primary compatibility blocker. Also it seems that .vsdx is an XML-based file format (.vsd was binary) and Microsoft is working on making it accessible to developers. Anyhow, I keep a VM for the purpose of editing this, and I didn't have any luck opening it in draw.io, so think we can stick with it for now. One of the only alternatives that I think can match the quality of Visio might be Lucidchart, which we could try later.
