### ISSUE TITLE
Update ossec to more recent version

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2740]
# Feature request
## Description
SecureDrop currently uses ossec 2.8.2, which is over 2 years old. While there have not been any significant vulnerabilities since, there have been many bugfixes. Syscheck improvements introduced in 2.9.0 and the ability to configure the time between two syscheck wakeups may fix #2495.

## User Stories
As a SecureDrop administrator, I would like to have a more recent version of ossec to avoid any bugs and benefit of any improvements to the functionality and reliability of the software.

**Comment by conorsch** [comment]
See #2136.
