### ISSUE TITLE
[RFE] Doc update for admins/journalists to not share HidServAuth details

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#2761]
# Bug

## Description

We should have a big warning box in the documentation saying not to share HidServAuth details.

## Steps to Reproduce

This should be shown in proper place so that all admins/journalists see this. Also we should ask any training to include this as things not to share.

**Comment by redshiftzero** [comment]
hey @zenmonkeykstop - if you feel like picking up a docs ticket, this is a good one!

**Comment by zenmonkeykstop** [comment]
@redshiftzero looks like I can't self-assign, but I'll take it! (was also thinking of folding @dachary's libvirt post into prod env setup section if that sounds ok)

**Comment by redshiftzero** [comment]
sweet, assigned!
