### ISSUE TITLE
Send OSSEC alert to admins when app server disk space is almost full

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2765]
## Description

Admins should get an alert when the disk space is getting full so they know to take action. 

## User Stories

As an Administrator, I want to be informed when the disk space is almost full on my app server so that I can schedule maintenance.

**Comment by msheiny** [comment]
heyy @redshiftzero check out #2574  :)

This isnt really a duplicate ticket but I start to propose this type of stuff there. Should I break apart all the proposed alerts in that ticket?

**Comment by redshiftzero** [comment]
Hmm so I vote we break out into specific tickets any alerts that we don't have but think are important (e.g. the item in this issue would help admins detect disk space exhaustion attacks), as we should add them (or encourage contributors to add them) prior to reworking the logging/monitoring story.

**Comment by msheiny** [comment]
ohhhh i see the link of why this came up now. okay 👍 i agree with what @redshiftzero said. 

On a side note, I quickly asked myself if OSSEC supports this kind of alert and answered my own question http://ossec-docs.readthedocs.io/en/latest/manual/monitoring/process-monitoring.html#disk-space-utilization-df-h-example

**Comment by redshiftzero** [comment]
It turns out this alert [is already in place](https://github.com/freedomofpress/securedrop/blob/fb3772fd754d2253f991c2f59fc253df5f18dd0f/install_files/securedrop-ossec-agent/var/ossec/etc/ossec.conf#L93). Closing!
