### ISSUE TITLE
Two-factor authentication for document interface

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#277]
@dolanjs asked for ideas on how we should implement two-factor authentication for journalists, which is a gap in the existing setup.

I located this [google-authenticator-apache-module](https://code.google.com/p/google-authenticator-apache-module/) and have tested it on my personal webserver with good results. This combines Google Authenticator with Apache Basic Auth resulting in a true two-factor solution.

This module could be implemented in a pretty straightforward manner.

**Comment by garrettr** [comment]
This was resolved in #522.
