### ISSUE TITLE
Remove Travis from CI runner

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2790]
# Feature request

## Description

We've moved a lot of functionality out of Travis and into Circle. I think it's finally time to take Travis out of the CI equation. It's more difficult to maintain both environments consistently and it's more debug work for us lonely ops folks.

## User Stories

As a CircleCI sales person, I want SecureDrop to no longer use Travis and stick with CircleCI.

**Comment by redshiftzero** [comment]
Looks like we need to get the dev testinfra tests to fail (#2791) and then the pytest pages-layout tests running in Circle and then we are a go to fully Travis

**Comment by conorsch** [comment]
@redshiftzero @dachary How's the linting running in Circle? Right now this is what we've got enabled for CI on the `develop` branch:

![sd-develop-ci-requirements](https://user-images.githubusercontent.com/657862/34545593-da84ebec-f0a2-11e7-9de5-e70e305da9cb.png)

We should be able to require at least the linting, no?

**Comment by redshiftzero** [comment]
Well our oldest PR from November (#2506) was still running `docs-lint` only, so that check won't pass, so until we merge in those last few old PRs, we'll have to keep it as an optional check
