### ISSUE TITLE
Docs give incorrect guidance on running tests locally

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2794]
# Bug

## Description

The docs give incorrect instructions for running the application test suite locally. From https://docs.securedrop.org/en/latest/development/testing_application_tests.html#running-the-application-tests : 

```
vagrant ssh app-staging
sudo su www-data -s /bin/bash
cd /var/www/securedrop
pytest -v tests
```

That works well enough for the unittests, but the functional tests will all report errors there. 

## Steps to Reproduce

1. Spin up local staging VMs.
2. Follow the instructions outlined above.
3. Observe ~ 13 tests reporting ERROR.

## Expected Behavior
Following the developer documentation for running tests locally results in all tests passing.

## Actual Behavior
Several functional (meaning browser-driving) tests fail due to the insufficient www-data permissions.

## Comments
We should _not_ recommend that all tests be run as root (e.g. with `sudo su` instead of `sudo su www-data -s /bin/bash`). Instead we should inspect the `app-test` role logic for overly restrictive file modes that could be preventing the www-data user, with a shell, from interacting with the webdriver.

**Comment by redshiftzero** [comment]
Also addressed in #2996
