### ISSUE TITLE
[RFE] Enable type checking in the CI using mypy

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#2795]
# Feature Request

## Description

We should enable [type annonation](https://www.python.org/dev/peps/pep-0484/) in the source code, and enable [mypy](http://mypy-lang.org/) check in the CI. Related Python2 module is [typing](https://pypi.python.org/pypi/typing). This is part of the standard library in Python3.

## User Stories

- Finding corner cases in our code, mypy is currently used check dropbox's internal Python code, and many other projects also use the same. Even the CPython source also have type annotations.

- I am new developer, while trying to read the source code I can not understand which function takes what kind of input. Having type hints in the source code will help me to read the source and understand easily.

**Comment by kushaldas** [comment]
This should not be done in one go. Instead we should start doing incremental changes. My suggestion is to have following rules.

- Any new function should have type annotations inside.
- If you are updating any function, try to update it with type annotations.
- Add mypy as an experimental local developer check
- Enable in CI after we cover say 25% code with annotations. mypy will not report about things which are not annotated yet.

**Comment by redshiftzero** [comment]
This was done in #3032
