### ISSUE TITLE
CI test failures obscure debugging output

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2800]
# Feature request

## Description

The CI run obscures results from the various test suites, making certain failures difficult to understand. See for example [Circle CI build 5914](https://circleci.com/gh/freedomofpress/securedrop/5914), which shows:

> TASK [fail] ******************************************************************** Friday 05 January 2018 19:42:25 +0000 (0:03:20.042) 0:03:24.094 ******** fatal: [app-staging]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

The relevant task in `molecule/aws/side_effect.yml` is:

```
    - fail:
      when: app_test_register|failed or testinfra_results|failed
```

It's not immediately clear from the error output _which_ specific test failed, or even which test suite contained the error. We should break that single untitled task into two named tasks, with separate conditionals. Consider using `assert` rather than `fail` because then we can supply a custom `fail_msg` with informative output for developers.

## User Stories

As a developer, if tests fail I want to know exactly what failed so I can fix it. I don't want to cajole answers out of a stubborn and inscrutable oracle _before_ asking team members for review.

**Comment by msheiny** [comment]
I intially tried to fix this in PR #2796 by adding an annotation to the junit file . If that works correctly.. it will show a notification at the top on the Circle UI. Unfortunately... its not picking up for whatever reason... GRRR .. so i can circle back to this but for now `3591fc7` doesnt fix the issue as described but it did add more artifacts for dev to search raw test execution output.
