### ISSUE TITLE
Recommend dimensions for logo(s) uploads

### ISSUE THREAD

**Issue by toast** [freedomofpress/securedrop#2801]
# Recommend dimensions for logo(s) uploads

## Description

Currently logos vary in size dramatically between different [deployed instances](https://securedrop.org/directory). This makes it much more difficult to have a clean design for the top bar layout on mobile (in particular) and also restricts the design options on desktop.

This issue is an extension to #2769 to encourage journalists to upload a logo that will display well on desktop and mobile screens within the constraints of the design and allow for consistent responsive layout as per #2551. Journalists should be warned that logos which have different dimensions to these cannot be guaranteed to display optimally and shown an example guide of preparing the logo including desired clearance (whitespace).

For example:

* Upload desktop square logo (recommended size 150x150) (png)
* Upload square mobile logo (recommended size 50x50) (png) OR Upload landscape mobile logo (recommended size 100x50) (png)

The above sizes are a best guess at recommended dimensions based on the current design and assume clearance is included in the image and it is centered correctly within that space. My assumption is that it's best to avoid retina for now to prioritise download speed on the Tor network. Tor browser doesn't allow SVG in high security mode so PNG at 1x for now.

Would be useful to add a mockup to this issue to show layout of instructions to journalists and upload controls.

**Comment by toast** [comment]
Not sure if we already have a mechanism to optimise uploaded images for web on the server-side (during runtime)? Something like [PyImageOptimizer](https://pypi.python.org/pypi/PyImageOptimizer/1.1)? - [example usage](https://pyimageoptimizer.readthedocs.io/en/latest/usage.html). @redshiftzero

**Comment by redshiftzero** [comment]
Thanks for filing this @toast. We should definitely inform admins of the expected size of the images in the logo upload form - currently we have a recommendation of `500px x 450px`, but e.g. on the journalist interface, as you correctly point out we resize it to a wee 150px logo size. And we don't actually optimize uploaded images server-side unfortunately. Filed followup #2807 about that, because that is a great point.
