### ISSUE TITLE
Find and migrate to maintained alternative to cssmin

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2808]
## Description

We use `cssmin` to minify CSS, but it is no longer maintained: https://github.com/zacharyvoase/cssmin (last commit 4 years ago). 

`csscompressor` is a similar project that is maintained, we might consider using that instead: https://github.com/sprymix/csscompressor.

## User Stories

As a SecureDrop maintainer, I want my dependencies to be well-maintained so that breakage or security vulnerabilities are noticed and promptly fixed.

**Comment by trankmichael** [comment]
I looked for references of `cssmin` but found that last reference to it was removed from the app code in https://github.com/freedomofpress/securedrop/commit/2ad8678162a918393b18080399e2deeb9d0fa92b#diff-88383f21e19c9be2cf4d9b6a81184f7a . When I removed the `cssmin` from the requirements and reprovisioned all the tests passed.

While looking at a replacement for minifier, I was thinking that the asset management and filtering could also be moved out of the template files and put into a Bundle from `flask-assets` in a seperate assets.py. I could open a new issue for this if these types of changes seem reasonable.

**Comment by redshiftzero** [comment]
Actually, what about we just minify the CSS during the build process, and ship the minified CSS along with the regular CSS? That's one less dependency for the app server

**Comment by heartsucker** [comment]
`sass` has a flag to minify and strip source maps, and it looks like we do that already according to `grep`:

```
install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/tasks/sass.yml
2:- name: Install sass Ruby gem
4:    name: sass
25:  shell: "/usr/local/bin/sass --force --stop-on-error --update sass:{{ securedrop_code_filtered }}/static/css --style compressed --sourcemap=none"
35:    - "sass"
36:    - ".sass-cache"
```

This may be closeable simply by removing it from the requirements files.
