### ISSUE TITLE
Apache AppArmor profile: Whitelist *.css.map files

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2810]
## Description

We're reports of AppArmor alerts on Apache2 that should be suppressed. 

## Steps to Reproduce

1. On staging, navigate to `http://<source or journalist URL>.onion/static/css/source.css.map`
2. Alert appears

## Expected Behavior

No mysterious AppArmor alerts appear

## Actual Behavior

Admin gets an OSSEC alert: 

```
OSSEC HIDS Notification.
2018 Jan 08 11:11:11

Received From: (app) x.x.x.x->/var/log/syslog
Rule: 100012 fired (level 7) -> "Apparmor denied event"
Portion of the log(s):

Jan 8 11:11:11 app kernel: [12345.678] audit: type=1400 audit(123456789:12): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/var/www/securedrop/static/css/source.css.map" pid=1234 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=33
```

## Comments

We should whitelist the two `*.css.map` files. See similar issue here: https://github.com/freedomofpress/securedrop/pull/2078#issuecomment-322812202.

**Comment by redshiftzero** [comment]
Hey @emkll want to take a stab at this one?

**Comment by heartsucker** [comment]
If browsers are requesting the map files, that might mean we didn't generate the CSS with the `--sourcemap=none` option. If so, that should be fixed as well since that turns into additional network requests we don't need.
