### ISSUE TITLE
Add "Landing Page" to terminology

### ISSUE THREAD

**Issue by pierwill** [freedomofpress/securedrop#2820]
Suggestion: adding the term "Landing Page" to the terminology and italicizing it throughout the docs. We [emphasize](https://docs.securedrop.org/en/latest/deployment/landing_page.html) the security implications of the landing page itself. The docs should stylistically reflect the importance of this part of the system.

## User Stories

As a reader of the docs, I want unique and important terms to stand out.

**Comment by redshiftzero** [comment]
Great point @pierwill - it's unclear what that means to first contributors and we should definitely add this to the terminology.
