### ISSUE TITLE
TDD installer scripts

### ISSUE THREAD

**Issue by chrisng** [freedomofpress/securedrop#283]
Tasks:
1. Setup installer scripts to have a "dev" mode
2. When in "dev" mode
- allow ssh via hosts.allow/hosts.deny
- add vagrant to ssh group
- open iptables from vagrant machine
3. Setup a spec framework for validating installer works (Recommend: Serverspec http://serverspec.org/)

**Comment by garrettr** [comment]
The "When in dev mode" environment is very similar to the `staging` environment in the current release (see `docs/develop.md` for details). We still need to implement serverspec tests.
