### ISSUE TITLE
Update screenshots of admin instance configuration page

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#2832]
# Bug

## Description

The screenshots for the admin instance configuration pages are old in the documents, they need to updated with the latest screenshots.

## Steps to Reproduce

Please check the admin guide, the screenshots there don't show both "send test ossec alert" and "update logo" options in one page.

**Comment by dachary** [comment]
note that this is part of @redshiftzero [checklist for 0.5.1](https://github.com/freedomofpress/securedrop/issues/2813) under **Update all screenshots in user guides**

**Comment by redshiftzero** [comment]
Closing since it's tracked in the checklist in #2813
