### ISSUE TITLE
[0.5.1] OSSEC agent started email not suppressed

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2839]
# Bug

## Description

A short summary of the issue.

## Steps to Reproduce

Restart app server

## Expected Behavior

Ossec agent started email should be suppressed.

## Actual Behavior

Ossec Agent started email is not suppressed:
```


OSSEC HIDS Notification.
2018 Jan 11 15:32:33

Received From: (app-prod) 10.0.1.4->ossec
Rule: 503 fired (level 3) -> "Ossec agent started."
Portion of the log(s):

ossec: Agent started: 'app-prod->10.0.1.4'.



 --END OF NOTIFICATION
```

## Comments
https://github.com/freedomofpress/securedrop/pull/2701 incorrectly matches rule 501 instead of rule 503 in `local_rules.xml`

**Comment by redshiftzero** [comment]
Closed by #2838
