### ISSUE TITLE
tests: possible test_integration.py race condition on GPG key

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2849]
# Bug

## Description

I think this is a race condition and first seen it happen at https://circleci.com/gh/freedomofpress/securedrop/6410?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

<pre>
AssertionError: Could not decrypt msg with key, gpg says: [GNUPG:] ENC_TO C154976902EEB545 1 0 [GNUPG:] ENC_TO C3E7C4C0A2201B2A 1 0 gpg: encrypted with RSA key, ID A2201B2A [GNUPG:] NO_SECKEY C3E7C4C0A2201B2A gpg: encrypted with 1024-bit RSA key, ID 02EEB545, created 2018-01-13       "Autogenerated Key " [GNUPG:] NO_SECKEY C154976902EEB545 [GNUPG:] BEGIN_DECRYPTION [GNUPG:] DECRYPTION_FAILED gpg: decryption failed: secret key not available [GNUPG:] END_DECRYPTION
self = 

    def test_reply_normal(self):
>       self.helper_test_reply("This is a test reply.", True)

tests/test_integration.py:239: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_integration.py:379: in helper_test_reply
    codename)
tests/test_integration.py:286: in _can_decrypt_with_key
    decrypted_data.stderr))
E   AssertionError: Could not decrypt msg with key, gpg says: [GNUPG:] ENC_TO C154976902EEB545 1 0
E   [GNUPG:] ENC_TO C3E7C4C0A2201B2A 1 0
E   gpg: encrypted with RSA key, ID A2201B2A
E   [GNUPG:] NO_SECKEY C3E7C4C0A2201B2A
E   gpg: encrypted with 1024-bit RSA key, ID 02EEB545, created 2018-01-13
E         "Autogenerated Key "
E   [GNUPG:] NO_SECKEY C154976902EEB545
E   [GNUPG:] BEGIN_DECRYPTION
E   [GNUPG:] DECRYPTION_FAILED
E   gpg: decryption failed: secret key not available
E   [GNUPG:] END_DECRYPTION
</pre>

## Steps to Reproduce

No idea how to reproduce. Looking at the code the race that could occur because the GPG key generation of the source is async is guarded properly.

## Expected Behavior

No race, even rare.

## Actual Behavior

The error showed once in the past 3 months. If someone remembers another occurence, please update.

## Comments

This can be closed if it does not happen in the next six months.

**Comment by redshiftzero** [comment]
Looking at this, given the presence of:

```
        utils.async.wait_for_assertion(
            lambda: self.assertNotEqual(
                current_app.crypto_util.getkey(filesystem_id),
                None),
            15)
```

in `helper_test_reply` it is unclear how this could arise. Currently running this in a loop to see if it pops up again

**Comment by redshiftzero** [comment]
Update: I ran the integration tests in a loop for ~8 hours without a reproducer. In the current code, given the presence of the assertion that makes sure the key to decrypt the reply is available (in [this comment](https://github.com/freedomofpress/securedrop/issues/2849#issuecomment-375498607)), I don't think this flake is possible anymore. If the key to decrypt is not available, then the test should fail at the assertion instead. As such, I'm going to close this for now. If anyone sees this bug occur again, we should re-open.
