### ISSUE TITLE
Dockerfile: base image not latest

### ISSUE THREAD

**Issue by tmc** [freedomofpress/securedrop#2859]
# Bug

## Description

the base ubuntu image is not the latest via https://github.com/docker-library/repo-info/blob/master/repos/ubuntu/tag-details.md

**Comment by dachary** [comment]
<pre>
$ make images
docker build  -f Dockerfile-base -t securedrop-base .
Sending build context to Docker daemon  40.91MB
Step 1/8 : FROM ubuntu@sha256:f6eed4def93a3b54da920737f0abf1a8cae2e480bb368280c898265fcaf910a3
 ---> 3aa18c7568fc
Step 2/8 : ENV FIREFOX_CHECKSUM 88d25053306d33658580973b063cd459a56e3596a3a298c1fb8ab1d52171d860
...
Step 19/19 : CMD ./manage.py run
 ---> Running in 2c2f3be17a6c
 ---> 59b223a1a713
Removing intermediate container 2c2f3be17a6c
Successfully built 59b223a1a713
Successfully tagged securedrop-test:ebbf90832c9a29d55577870f2b73cc7aa3787b9b
</pre>

<pre>
$ make images && make -k testclean && make test
docker build  -f Dockerfile -t securedrop-test:ebbf90832c9a29d55577870f2b73cc7aa3787b9b .
Sending build context to Docker daemon  40.91MB
Step 1/19 : FROM ubuntu@sha256:084989eb923bd86dbf7e706d464cf3587274a826b484f75b69468c19f8ae354c
 ---> 67759a80360c
Step 2/19 : RUN apt-get update &&     apt-get install -y python-pip libpython2.7-dev libssl-dev secure-delete                        gnupg2 ruby redis-server firefox git xvfb haveged curl                        gettext paxctl x11vnc
 ---> Using cache

...
tests/pages-layout/test_source.py::TestSourceSessionLayout::test_source_session_timeout[en_US] PASSED                     [ 99%]
tests/pages-layout/test_source.py::TestSourceSessionLayout::test_source_session_timeout[fr_FR] PASSED                     [100%]Coverage.py warning: Module ../securedrop/ was never imported. (module-not-imported)


---------------------------------------- generated xml file: /tmp/test-results/junit.xml ----------------------------------------

---------- coverage: platform linux2, python 2.7.6-final-0 -----------
Coverage annotated source written to dir /tmp/test-results/cov_annotate
Coverage HTML written to dir /tmp/test-results/cov_html
Coverage XML written to file /tmp/test-results/cov.xml

=================================================== slowest 10 test durations ===================================================
26.38s call     functional/test_submit_and_retrieve_file.py::TestSubmitAndRetrieveFile::test_submit_and_retrieve_happy_path
18.13s call     functional/test_journalist.py::TestJournalist::test_journalist_verifies_deletion_of_one_submission_javascript
16.54s call     functional/test_admin_interface.py::TestAdminInterface::test_admin_interface
11.61s call     functional/test_source.py::TestSourceInterface::test_lookup_codename_hint
6.49s call     test_source.py::TestSourceApp::test_all_words_in_wordlist_validate
6.22s call     pages-layout/test_journalist.py::TestJournalistLayout::test_delete_all_javascript[fr_FR]
6.22s call     pages-layout/test_journalist.py::TestJournalistLayout::test_delete_all_javascript[en_US]
6.16s call     pages-layout/test_journalist.py::TestJournalistLayout::test_delete_one_javascript[fr_FR]
5.82s call     pages-layout/test_journalist.py::TestJournalistLayout::test_delete_one_javascript[en_US]
5.19s call     pages-layout/test_source.py::TestSourceLayout::test_source_flagged[fr_FR]
============================================ 333 passed, 2 xfailed in 891.81 seconds ============================================
</pre>
