### ISSUE TITLE
Mitigate and investigate RequestLimitExceededRequest AWS CI error

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2881]
# Bug

## Description

First brought up in #2880 by the @dachary the Great.

```
 TASK [Add temporary SSH key to AWS region.] ************************************
    Wednesday 17 January 2018  09:56:39 +0000 (0:00:01.214)       0:00:14.457 *****
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RequestLimitExceededRequest limit exceeded.7652a309-1b7f-488b-8f48-396c2f8d1e99
    fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_lrL81p/ansible_module_ec2_key.py\", line 267, in \n    main()\n  File \"/tmp/ansible_lrL81p/ansible_module_ec2_key.py\", line 155, in main\n    key = ec2.get_key_pair(name)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 2854, in get_key_pair\n    dry_run=dry_run\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 2836, in get_all_key_pairs\n    [('item', KeyPair)], verb='POST')\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1170, in get_list\n    response = self.make_request(action, params, path, verb)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1116, in make_request\n    return self._mexe(http_request)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1028, in _mexe\n    raise BotoServerError(response.status, response.reason, body)\nboto.exception.BotoServerError: BotoServerError: 503 Service Unavailable\n\nRequestLimitExceededRequest limit exceeded.7652a309-1b7f-488b-8f48-396c2f8d1e99\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

## Steps to Reproduce

No reproduction known. This is an an AWS specific error that needs to be traced down.

**Comment by msheiny** [comment]
This seems directly related to the `CreateKeyPair` task and found some interesting tid-bits from the [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html):

> `The CreateKeyPair, GetConsoleOutput AuthorizeSecurityGroupIngress, and RevokeSecurityGroupIngress actions. These requests take the most time and resource to complete, so they have the lowest request limit.`

> `If an API request exceeds the API request rate for its category, the request returns the RequestLimitExceeded error code. To prevent this error, ensure that your application doesn't retry API requests at a high rate. You can do this by using care when polling and by using exponential backoff retries. `

**Comment by eloquence** [comment]
Lowering priority since we have stopgap mitigation in place. Still leaving it as to be discussed for next sprint at the team level.

**Comment by redshiftzero** [comment]
now that we're using Google cloud for our staging CI boxes, this shouldn't happen any more
