### ISSUE TITLE
Reduce volatility of CI network calls

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2883]
# Feature request

## Description

Fairly frequently we'll see weird one-off errors with upstream ubuntu repos that are resolved with a job re-run.

In CI we can mitigate this issue by re-routing all apt calls to mirrors that we control. Eeasiest thing to do is to either modify `/etc/hosts`. If we want to get more complex and not touch the CI hosts (minimize difference between host changes on CI  + prod) - run our own small  dns resolver that redirects apt calls from ubuntu --> our server. 

The added complexity here involves continuously keeping those those mirrors up-to-date but honestly I don't think thats a task that is hard to automate - we dont need any sort of key-resigning here for a plain ol' mirror.

## User Stories

As a securedrop developer, I don't want CI to fail because of one-off network errors on apt calls.

As a debian package, I want to be downloaded successfully.

**Comment by zenmonkeykstop** [comment]
This specific issue isn't a problem anymore, closing
