### ISSUE TITLE
Add request for feedback on Journalist and Source guides

### ISSUE THREAD

**Issue by edenemmanuel** [freedomofpress/securedrop#2893]
# Feature request
Consider adding a 'request for feedback' on Journalist and Source guides

## Description

Consider adding a request for feedback on the [Journalist](https://docs.securedrop.org/en/stable/journalist.html) and [Source](https://docs.securedrop.org/en/stable/source.html) guides on the [SecureDrop documentation](https://docs.securedrop.org/)

For example, at the end of the first page (or end of the section, or both) one could see a helpful _Hint_ or _Tip_ box checking if this guide was helpful. If the potential source or journalist found the guide confusing, then we could direct them to a reasonable channel to contact us.

### Thoughts for potential sources

We try to avoid having a potential source load the SecureDrop documentation, or the website, for fear of leaking any sort of information that the user is a potential source. That's why, on actual instances, there's a [landing page](https://docs.securedrop.org/en/stable/deployment/landing_page.html) for news organizations to instruct sources on how to leak through their specific SecureDrop instance.

So, perhaps the above scenario might involve updating our [landing page guidelines](https://docs.securedrop.org/en/stable/deployment/landing_page.html) to instruct news organizations on _how to instruct_ potential sources in sending feedback to the SecureDrop team for any confusion on how to use the system. (That may introduce another set of issues to consider, however.)

### Thoughts for journalists
The concern I have for potential sources is less so for a journalist. Many journalists do not hide the fact that they work for a news organization that has a SecureDrop instance, so there's less of a risk on that front. But, we would need to stress to journalists not to put any identifying information, especially about their sources, in any communication channel with us, or in the SecureDrop forum.

### As a source

If I were a source, I may have thoughts on how the Source Interface could improve. But, as a slightly technical, but not very technical person, I may not be able to know about making GitHub tickets, commenting on Gitter, or otherwise in a safe manner, if at all.

### As a journalist

As a journalist, I may be confused on various aspects of the workflow, or how the Journalist Interface works. I may reach out to my organization's IT department, who might help me out, but might not report this issue as a GitHub ticket, the SecureDrop forum, or through other support channels.

**Comment by redshiftzero** [comment]
In terms of a warning for sources - we should ensure we have a secure way to get their feedback, i.e. we should probably not solicit information like email addresses or encourage them to make accounts on 3rd party services like GitHub without careful consideration. I created the post https://forum.securedrop.club/t/getting-user-feedback-from-securedrop-sources-via-securedrop/376 to discuss the possibility of using SecureDrop to get feedback about SecureDrop (:xzibit:) from sources.

**Comment by eloquence** [comment]
As mentioned, the process of soliciting feedback from sources would be pretty complex and, to the extent that we want to support it, deserves its own issue. User research (some of which we've already done since this was filed) may be another good way to improve the source experience.

Thanks to @redshiftzero, there is now a blurb at the top of the Journalist Guide asking for feedback. Closing this issue.
