### ISSUE TITLE
Make all scripts self-documenting

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2913]
# Feature request

## Description

The following should work for every script:

- `make help`
- `./a-script --help`

And output enough information for someone who has never touched the SecureDrop codebase to understand what the script is doing. Looking up details in the docs shouldn't be necessary for basic usage. The docs could still be the place where it is explain why that script exists or what it is generally used for, but info on the correct incantations should all be in the scripts themselves.

## User Stories

As a new dev, I want scripts to be very clear with what they do.

As me, I have been working on SecureDrop for 2.5 years, and I don't even know what some of the scripts do without just straight up reading the source code.

**Comment by eloquence** [comment]
Closing; `make` does produce pretty detailed help output, we can consider improvements to specific scripts or help texts separately.
