### ISSUE TITLE
implicit dependencies between docker images and test cases

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2917]
# Bug

## Description

There are implicit dependencies on the latest build of a docker image and a test suite or lint job.

Originally reported in https://github.com/freedomofpress/securedrop/issues/2911#issuecomment-359279935

## Steps to Reproduce

- Check out `branch-a`, build container, run test, success
- Edit things, run test, failures

This is also a problem when switching branches that have the same parent commit.

The test will run because the image is tagged by the sha1 of the parent commit, and it already exists, but the 

## Expected Behavior

The make job ensures the correct container is used.

## Actual Behavior

It does not.

## Comments

The Makefile should rebuild the container before running the tests.

Or.

We use `git ls-tree -r HEAD --name-only | xargs cat | sha256sum | awk '{ print $1 }'` as the docker tag so we can cache it, and then check the cache to speed up the build.

```
heartsucker@pythagoras:~/code/freedomofpress/securedrop (develop)$ time git ls-tree -r HEAD --name-only | xargs cat | sha256sum
15aef4ff89b578cb8400f5bdd7c442bf1dc319666cd907eaa08fa431f09ecf0c  -

real	0m0.147s
user	0m0.144s
sys	0m0.012s
```

**Comment by dachary** [comment]
I propose we do not use hash for tags at all by default. And only in CI which is where they are useful to not incorrectly re-use the image cache from one build for another.

**Comment by heartsucker** [comment]
I assumed there was a reason we were tagging them. If it's just for caching, then you're right and we shouldn't tag them at all.

**Comment by dachary** [comment]
Given the logic of layer cache save / restore, if the image is not tagged it will have unexpected results ;)

**Comment by eloquence** [comment]
Closing as stale; we've not had the issue described here recently during development.
