### ISSUE TITLE
QA 0.3.2.9-1~trusty+1 for release to tor-apt mirror

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2919]
# Feature request

## Description

With the move of tor packaging to our own repository. We now have to QA each release as part of the release process. `0.3.2.9-1~trusty+1` is now included in the official upstream trusty repo (a bump from the current `0.3.1.9-1~trusty+1` installed on current servers).

Let's ensure that during QA of next release -- that latest tor package is also tested.

## User Stories

As a securedrop developer, I want to ensure latest stable tor is tested prior to release.

**Comment by msheiny** [comment]
package has been pushed to `tor-apt-test.freedom.press` with SD test key.

**Comment by redshiftzero** [comment]
This was QAed during the release of 0.5.2, closing
