### ISSUE TITLE
User confirmation before 2FA reset no longer appears

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2920]
## Description

There used to be a js confirmation before resetting 2FA tokens for users but this is no longer working

## Steps to Reproduce

1. Sign into journalist interface as admin
2. Go to admin panel and edit a user
3. On the edit user page, click the button to reset the user's 2FA authentication

## Expected Behavior

An alert appears, requesting the user confirm they wish to reset the 2FA token

## Actual Behavior

No alert appears / no confirmation is required

## Comments

Discovered during writing test cases for #2405 - there's a regression in `journalist.js`, this functionality no longer works:

```
  // Confirm before resetting two-factor authentication on edit user page
  $('form#reset-two-factor').submit(function(event) {
      return confirm(get_string("reset-user-mfa-confirm-string").supplant({ username: username }));
  });
```

**Comment by dachary** [comment]
If I'm not mistaken 270784ad1d8eb7a63de6d9c6b722079936ccc173 broke this confirmation in 2014 :-)
