### ISSUE TITLE
CI staging job not rebasing on develop

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2931]
I noticed when trying to rerun the CI job in #2925 that rebasing on `develop` wasn't working. Inspecting further, it appears that the two jobs we had in CI `staging-test-with-rebase` and `staging-test` were mislabeled (`staging-test` rebased, `staging-test-with-rebase` did not). As such, when we recently removed `staging-test`, we removed the CI job that rebased on latest `develop`. This is my bad, I merged in #2515 during a hackathon and should have caught this during review.

**Comment by conorsch** [comment]
Great catch, @redshiftzero, thanks for doing the git archaeology here.
