### ISSUE TITLE
Lint all Python files with flake8 

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2933]
# Feature request

## Description

Our current strategy for linting Python files via flake8 uses a whitelist for file location, which is brittle. If someone adds a new Python file outside of the whitelisted directories, e.g. as in #2922, flake8 will not lint them. That can lead to problems. Specifically, the changes in #2922 did not pass linting and never shold have been merged.

We should update our flake8 linting logic to check _all_ Python files in the repository, which will also catch new additions during CI against PRs.

## User Stories

As a developer, I want CI to lint the code I write, not just its favorite code that it's comfortable with.

As a CI pipeline, I want to lint everyone's code, not just the same old stuff I'm used to.

**Comment by conorsch** [comment]
cf. the linting strategy used by `make shellcheck`, which leverages a blacklist rather than a whitelist. Let's implement that approach, but for Python files.

**Comment by redshiftzero** [comment]
We can specify which files not to lint via `flake8 --exclude=path/to/files/to/not/lint/*`
