### ISSUE TITLE
Duplicate tor apt repos installed

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2938]
# Bug

## Description

On an new install of 0.5 (or on an instance that has had the install commands run a second time), they will have two repository list files pointing to our securedrop tor apt repo:

* /etc/apt/sources.list.d/tor_apt_freedom_press.list
* /etc/apt/sources.list.d/tor.apt.freedom.press.list

The first one is generated via commit `565c6243a9a340d51879bf32fabb9fe45dd42ab2` and the second is generated via the `securedrop-config` debian package.

This shouldn't cause any breaking problems but it is problematic when we want to clean-up later and or redirect repos.

## Steps to Reproduce

- Install latest securedrop (0.5.1 as of this PR)
- Do an `ls  -l /etc/apt/sources.list.d/*.list`

## Expected Behavior

Should only see `apt_freedom_press.list` and one other file

## Actual Behavior

We see three files `apt_freedom_press.list` and the two files listed above

## Comments

Purge one of the files in question and stick to one standard.

**Comment by conorsch** [comment]
Great catch, @msheiny. Fix should include a regression test for uniqueness on the apt sources, e.g. `grep -rl tor-apt /etc/apt/* shows only 1 hit.

**Comment by dachary** [comment]
@aydwi the first step would be to [install SecureDrop](https://docs.securedrop.org/en/latest/overview.html). If you do not have dedicated hardware, this can be done with two virtual machines that you create for the occasion. This is significant work but also a great learning experience. You will get to ask a lot of questions that will allow us to improve the documentation in the process.

**Comment by aydwi** [comment]
I'll proceed with virtual machines, although I wonder if my Raspberry Pi 3 can be used.

**Comment by conorsch** [comment]
I'll pick this one up for the current sprint. @aydwi if you did indeed start work on this, kindly let me know, otherwise I'll proceed.

**Comment by aydwi** [comment]
@conorsch I did not start working on this. You can proceed if you want
