### ISSUE TITLE
Bug after you submit docs and want to login again

### ISSUE THREAD

**Issue by trevortimm** [freedomofpress/securedrop#294]
I've been doing a bunch of testing and trainings at a news org that will launch SecureDrop soon. 

It seems when you submit a file as a source, you cannot click back to the SecureDrop main page and then login again as with your code name -- or any valid code name. It tells you your codename is invalid. 

In order to login again, you close your current session and open a new window or tab and reload the page.

Is this by design for a security reason or a bug? And if it's a bug can someone try to re-create it?

**Comment by redshiftzero** [comment]
Just tested this - and this appears to no longer be the case on the source interface. Sources can submit documents, log out, and log back in. Closing.
