### ISSUE TITLE
CI jobs should rebase on target branch, not always develop

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2942]
## Description

We rebase on `develop` for all CI jobs, which is groovy for PRs into `develop`, but we don't want to do this for PRs into `master` or any `release*` branch. Currently we have logic in `securedrop/devops/scripts/rebase-develop.sh` that looks like this:

```
# If current branch is not master or doesnt start with release...
if [[ "$CIRCLE_BRANCH" != "master"  && "$CIRCLE_BRANCH" != release*  ]]; then
```

which will prevent the rebase step from running if we're on the `master` or `release*` branches. But since the `$CIRCLE_BRANCH` env var stores the current branch, not the branch we're trying to merge into, the rebasing logic will still run for PRs into `master` or `release*`. 

See also: [feature](https://discuss.circleci.com/t/only-build-pull-requests-targetting-specific-branch/6082) [requests](https://discuss.circleci.com/t/create-a-circle-target-branch-envar/10022) over at Circle CI

## User Stories

As a developer, I don't want to get conditioned into looking at a red build and saying "oh _that_ red build is ok"

**Comment by dachary** [comment]
Instead of rebasing, it would be a lot easier to ask CircleCI to work on the **merge** reference provided by GitHub, which is the result of the latest successfull merge into the target branch.

```
$ pr=2929 ; git fetch origin +refs/pull/$pr/*:refs/pull/$pr/*
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
From github.com:freedomofpress/securedrop
 * [new ref]           refs/pull/2929/head  -> refs/pull/2929/head
 * [new ref]           refs/pull/2929/merge -> refs/pull/2929/merge
```

**Comment by redshiftzero** [comment]
So we could use the GitHub API to implement a smarter "rebase on target branch" that basically did the following:

1. send to GitHub API: `GET /repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls/$CIRCLE_PR_NUMBER `  where the environmental variables are [described here](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) (needs testing to make sure this would work on forked PRs)
2. get base branch from response which has the base branch in `base.ref` (see docs [here](https://developer.github.com/v3/pulls/#response-1))
3. then rebase on that branch

**Comment by msheiny** [comment]
@dachary it seems your suggestion will only provide the branch details that the PR was forked from but not what the PR github is targeting .. is this correct or am i misunderstanding? im leaning towards @redshiftzero 's solution...  im really hoping we can get those API details without injecting creds :grimacing:  testing...

**Comment by msheiny** [comment]
> PR was forked from but not what the PR github is targeting
to clarify, that even though a branch was forked from `develop` it could be targeting a release branch.

**Comment by dachary** [comment]
I meant that `refs/pull/3388/merge` is the result of

* git checkout the-target-branch
* git merge refs/pull/3388/head # which points to the SHA1 of the tip of the PR

It is updated every time the tip of the-target-branch changes.
