### ISSUE TITLE
If journalists enable NoScript, they don't get warning when deleting source codename

### ISSUE THREAD

**Issue by trevortimm** [freedomofpress/securedrop#295]
Journalists who have scripts turned off do not get an 'are you sure?' warning when they go to delete a source code name. 

The means that journalists engaged in best security practices are ironically more at risk at slipping up and deleting a communications line with a legitimate source.

**Comment by fowlslegs** [comment]
Note this is the same for deleting journalists/ admins.

**Comment by heartsucker** [comment]
@redshiftzero Hackathon candidate again?

**Comment by redshiftzero** [comment]
Good call - added!

**Comment by daonb** [comment]
This seems the oldest issue for the Hackathon, so I'll have a go. Here's what I figured:

Good security dictates disabling JS. When that happens, the system requires no confirmation for destructive actions, like deletion. The proposed solution is to add all critical actions to a work queue with an activation timer of 10 minutes and give the user 7 minutes to click an *Oops* button and revert the change. 

On the UX side, we need to list all the critical activities. On the front we'll need a simple, template based notification system to display a one line with the last critical activity and an Oops link. On the back we need a work queue (not sure if we have one) and a task runner to handle all critical activities.

**Comment by heartsucker** [comment]
I think that's actually *more* complicated. What we could do is have JS buttons start with a default form action pointing to some HTML page that asks for a confirm. Then the JS erases that and replaces it with the `confirm` popup before going ahead with the action.

I think that's more inline with how some of the other behavior is and more intuitive. I think people assume most actions on websites don't have an "oops" option.

**Comment by daonb** [comment]
After talking with the guys at lunch, we want to suggest to keep things simple and resolve this granddaddy of an issue. We've got about 3 hours to go in the TLV Hackathon...

Let's replace the js based approval system with a new HTML confirmation page. What @heartsucker suggested is clearly better, but we don't have the time.I suggest we solve this the simplest way and open an fresh issue for the *Oops* button.
