### ISSUE TITLE
Release candidates deb packages are considered higher version than the final release

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2950]
# Bug

## Description

During the QA process - one might want to test a RC version of SD on a physical instance. If you do that though, it becomes annoying to install the final release candidate because debian/ubuntu considers: 

`0.5.1` <  `0.5.1-rc#`

## Steps to Reproduce

* Install a release candidate debian package, 
* attempt to upgrade it to the latest,
* cry in agony at the uncruel world. 

## Expected Behavior

I expect the prod release will be recognized by apt as a higher version than a release candidate.

## Actual Behavior

Apt requires a force install of the lower version and there is a possibility the old release candidate could auto-upgrade if one doesnt properly clean out their apt repo list.

## Comments

Luckily! ol' @msheiny has a fix for you -- utilize the `~rc#` versioning scheme instead of `-rc#` . For example `0.5.2~rc1`. Notice the squiggly line instead of the flat line for all you people that can't discern squiggles. Is that a thing? I feel like thats a medical condition.

**Comment by redshiftzero** [comment]
Thanks for filing @msheiny, we'll use `~rcN` in the future for release candidates. You will need to cry in agony no more

**Comment by redshiftzero** [comment]
Note for others that try this using SecureDrop's version update script: the `rc` commit will be generated but the tag will not, as the script bails when attempting to create the associated tag:

```
$ ./update_version.sh 0.5.2~rc1

Select an editor.  To change later, run 'select-editor'.
  1. /bin/ed
  2. /bin/nano        <---- easiest
  3. /usr/bin/vim.basic
  4. /usr/bin/vim.tiny

Choose 1-4 [2]: 
[release/0.5.2 f898877] SecureDrop 0.5.2~rc1
 12 files changed, 28 insertions(+), 12 deletions(-)
fatal: '0.5.2~rc1' is not a valid tag name.
```

This is because `~` is [not a valid character in a git tag](https://git-scm.com/docs/git-check-ref-format). We should update the script to handle this situation.
