### ISSUE TITLE
Provide welcome message in SecureDrop Gitter channel

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2953]
# Feature request

## Description

Newcomers to the [SecureDrop Gitter channel](https://gitter.im/freedomofpress/securedrop) can be shown a custom message, set by project maintainers. I propose we begin using this feature to drive inclusion, specifically by recommending the daily standup URL and time:

> Daily standup, Monday through Friday, at 19:00 UTC https://meet.jit.si/QuickWizardsDanceHigh Come join!

We should also consider custom messaging for the GSoC application process. If we want to link out to a concise wiki page that documents all the necessary details, that's fine too, and would require less futzing with the Gitter config (since the wiki is easier to edit). 

## User Stories

As a newcomer to the project, my interest in joining the public chatroom for the project should be encouraged by identifying opportunities for further engagement.

**Comment by dachary** [comment]
I find useful to display links. Something like 

> https://securedrop.org - [contribution guide](https://docs.securedrop.org/en/latest/development/getting_started.html) - [GSoC 2018](https://github.com/freedomofpress/securedrop/wiki/Google-Summer-of-Code-2018-Ideas) - [Daily standups](https://meet.jit.si/QuickWizardsDanceHigh)

**Comment by redshiftzero** [comment]
The gitter welcome message is now:

"Welcome to the SecureDrop developer chatroom! [SecureDrop.org](https://securedrop.org) - [Contribution Guide](https://docs.securedrop.org/en/latest/development/getting_started.html) - [Google Summer of Code 2018](https://github.com/freedomofpress/securedrop/wiki/Google-Summer-of-Code-2018-Ideas) - [Daily video standups 6pm UTC](https://meet.jit.si/QuickWizardsDanceHigh) - [Community Forum](https://forum.securedrop.club/)"
