### ISSUE TITLE
Repeated sentence in doc page "What Makes SecureDrop Unique"

### ISSUE THREAD

**Issue by aydwi** [freedomofpress/securedrop#2957]
# Bug

## Description

In the doc page **"What Makes SecureDrop Unique"**, under the heading **"Protecting against hackers"**, the sentence *"The SecureDrop servers also undergo significant system hardening in order to make it as difficult as possible for hackers to break in."* is repeated twice.

The first occurrence of the sentence should be removed.

**Comment by conorsch** [comment]
Why yes, yes it is. Thanks for reporting, @aydwi. Happy to review a docs change if you edit to fix! Allow me to point out that if you're _only_ editing documenting, you can prefix your feature branch with `docs-` to skip the long-running CI tasks, as described here: https://docs.securedrop.org/en/stable/development/documentation_guidelines.html#testing-documentation-changes

**Comment by aydwi** [comment]
I have created the pull request.

**Comment by aydwi** [comment]
PR merged. Closing the issue.
