### ISSUE TITLE
css-modal screenshots sometime do not show

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2959]
# Bug

## Description

Because of the ease-in display of the modal (**transition: opacity 100ms ease-in**), the screenshot taken right after clicking on the **delete** button may not show the modal.

## Steps to Reproduce

* pytest --page-layout tests/pages-layout
* view securedrop/tests/pages-layout/screenshots/en_US/journalist-delete_all_confirmation.png or journalist-delete_one_confirmation.png

## Expected Behavior

A screenshot that displays the modal.

## Actual Behavior

![journalist-delete_one_confirmation](https://user-images.githubusercontent.com/433594/35724868-937dfcba-07ff-11e8-9ad8-dc60331e0250.png)

**Comment by dachary** [comment]
@SaptakS noticed that, probably because my machine was running fast this time around. Do you observe the same problem ?

**Comment by SaptakS** [comment]
@dachary though I don't see a similar problem, but due to the transition, it is possible that this is happening. There is two solutions - 
* Remove the transition time
* Modify the test to take the screenshot after 100 ms.

I think second one makes more sense, what do you think?

**Comment by dachary** [comment]
> Modify the test to take the screenshot after 100 ms.

Let's try that !  You can even make it 1s to allow the transition to take a little more time ?

**Comment by SaptakS** [comment]
@dachary makes sense.
