### ISSUE TITLE
Instructions to change Tor Browser security slider need updating

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2962]
## Description

We have instructions to turn the security slider to its maximum setting on the source interface. These instructions are out of date with the security slider. 

## Steps to Reproduce

0. Access the source interface in latest Tor Browser (here Tor Browser 7.5)
1. Try to follow the instructions to turn the security slider to "High":

<img width="501" alt="screen shot 2018-02-02 at 4 20 43 pm" src="https://user-images.githubusercontent.com/7832803/35740557-70c916ce-0835-11e8-87ea-24faf6a5c2d0.png">

## Expected Behavior

I follow instructions as written and I am not confused

## Actual Behavior

The highest setting is now called "Safest":

<img width="494" alt="screen shot 2018-02-02 at 4 24 06 pm" src="https://user-images.githubusercontent.com/7832803/35740587-85ef050e-0835-11e8-9da4-69d891e5cd1d.png">

## Comments

Just replace "High" with "Safest"

**Comment by Anonymous26** [comment]
i would like to work on this issue. Can you please assign it ?

**Comment by dachary** [comment]
@Anonymous26 Thanks for volunteering ! Consider yourself assigned to this issue :-)
