### ISSUE TITLE
Vagrant box currently unavailable [2-24-18]

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#2970]
# Bug

## Description

As of 10:00 UTC 02/24/18 `bento/ubuntu-14.04` has returned '404 not found', although it's listed on [Vagrant Cloud](https://app.vagrantup.com/bento/boxes/ubuntu-14.04). Randomly found this out when attempting to stand up the environment just so I could check a quick assumption. 

```
kevin@helios:~/dev/securedrop$ vagrant up /staging/
Bringing machine 'mon-staging' up with 'virtualbox' provider...
Bringing machine 'app-staging' up with 'virtualbox' provider...
==> mon-staging: Checking if box 'bento/ubuntu-14.04' is up to date...
==> mon-staging: There was a problem while downloading the metadata for your box
==> mon-staging: to check for updates. This is not an error, since it is usually due
==> mon-staging: to temporary network problems. This is just a warning. The problem
==> mon-staging: encountered was:
==> mon-staging: 
==> mon-staging: The requested URL returned error: 404 Not Found
==> mon-staging: 
==> mon-staging: If you want to check for box updates, verify your network connection
==> mon-staging: is valid and try again.
Your VM has become "inaccessible." Unfortunately, this is a critical error
with VirtualBox that Vagrant can not cleanly recover from. Please open VirtualBox
and clear out your inaccessible virtual machines or find a way to fix
them.
kevin@helios:~/dev/securedrop$ vagrant box update
==> app-prod: Checking for updates to 'bento/ubuntu-14.04'
    app-prod: Latest installed version: 201710.25.0
    app-prod: Version constraints: 
    app-prod: Provider: virtualbox
There was an error while downloading the metadata for this box.
The error message is shown below:

The requested URL returned error: 404 Not Found
```

## Steps to Reproduce

Try to `up` the environment or `box update`. 

## Expected Behavior

The image is served from HashiCorp's server and downloads. 

## Actual Behavior

Not Found response is returned.

## Comments

I submitted this as #6420 to [support.hashicorp.com](https://support.hashicorp.com) and will update if there is anything. I also did a quick Wireshark packet capture but it was all TLS so at first couldn't determine the actual URLs of the boxes. I did some guessing/Google'ing around and determined that it was likely https://hashicorp-files.hashicorp.com/bento/ubuntu-14.04.box and confirmed in curl/wget that it is 404.

Interestingly, they also have some older infrastructure on https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04 which explicitly says it is being decommissioned.

**Comment by conorsch** [comment]
I can reproduce this locally on Vagrant 1.9.1. Worse, it appears _all_ Vagrant boxes are affected on my machine—so I expect a breaking API change. Will try upgrading Vagrant to a more modern version and report back.

**Comment by conorsch** [comment]
Confirmed, looks like the backend URLs changed out from under us around the release of Vagrant 2.0.2. See this comment for a workaround that supports versions of Vagrant 1.x: https://github.com/hashicorp/vagrant/issues/9442#issuecomment-363080565

While we can force upgrades to e.g. Vagrant 2.x via the Vagrantfile [minimum version option](https://www.vagrantup.com/docs/vagrantfile/vagrant_version.html), that would be disruptive to many devs currently using 1.x. Debian stable currently has 1.9.1 in the apt repos, so I'm inclined to support that version unless we have a good reason not to—and backend breakage on Hashicorp's part does not constitute a sufficiently good reason in my mind.

Will submit a PR with the workaround and ask for review.
