### ISSUE TITLE
Rebase in CI causing trouble on merge branches

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2975]
## Description

We should disable rebasing in CI for post-release merges (e.g. for `$CIRCLE_BRANCH` beginning with `merge-`) since the rebase applies one commit at a time and hits conflicts that have been resolved in the merge commit at the `HEAD` of the PR branch.

See for example the [CI issues](https://circleci.com/gh/freedomofpress/securedrop/7668) in #2967 - GitHub reports no conflicts, but the rebase in CI hits conflicts and fails the job.

**Comment by conorsch** [comment]
Candidate fix in https://github.com/freedomofpress/securedrop/commit/42b1f08d3a34495134b8911840cfa64af1565bff looks good, any comments @msheiny?

**Comment by redshiftzero** [comment]
We're no longer doing these maintenance merges so closing this.
