### ISSUE TITLE
async_genkey runs in a thread that has no flask application

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2978]
# Bug

## Description

async_genkey tries to access the database in a separate thread and fails with the error like

<pre>
[2018-02-06 00:05:33,620] ERROR in utils: async_genkey for source (filesystem_id=AXT3PQIZMYAMHOZ4MIVX6ZGHCWP3GKWNI5UW2UMMANIGQJ6CUTYH45VTEP63X2DAWPRTS3PUPQBAFCLI4JMOZHVZPOZXGIKWMCFJQ3I=): No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
</pre>

See an example of failure probably due to this race https://gist.github.com/conorsch/b76b0ae5f81b1a78428d59e1b4666e7a#file-app-test-failures-log-L358

## Steps to Reproduce

Not sure.

## Expected Behavior

* pytest tests/test_integration.py runs with no failure.

## Actual Behavior

* pytest tests/test_integration.py runs sometime fails with
<pre>
No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
</pre>

**Comment by dachary** [comment]
@heartsucker do you have a suggestion on how to fix **async_genkey** ?

**Comment by heartsucker** [comment]
This class of issue is only going to be exacerbated by #2969 and #2877. I wonder if it would make sense to replace use of `db` from the `from db import db` with a manually generated connection using `sqlalchemy.create_engine`. This would ensure that the DB connection's life cycle is managed independently of the application.

**Comment by dachary** [comment]
For the record: http://docs.sqlalchemy.org/en/latest/orm/contextual.html

**Comment by tmc** [comment]
Refs https://github.com/freedomofpress/securedrop/issues/2609

**Comment by dachary** [comment]
So, what about we create a session in async_genkey and following http://docs.sqlalchemy.org/en/latest/orm/session_basics.html instead of using the query property ?

<pre>
session = scoped_session(sessionmaker(autocommit=False,
                                         autoflush=False,
                                         bind=engine))
source = session.query(Source).filter(Source.filesystem_id == filesystem_id).one()
source.last_updated = datetime.utcnow()
</pre>

This will effectively write to the same SQlite in parallel and rely on proper locking to avoid races. I'm not sure how good SQlite as used by sqlalchemy is when presented with this use case though.

**Comment by dachary** [comment]
sqlachemy sessiosn are not thread safe http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#is-the-session-thread-safe
