### ISSUE TITLE
Squash ansible deprecation warnings

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3008]
# Bug

## Description

There are many deprecation warnings that exist in the ansible output during the course of an install. These are both an eye-sore and will one-day become breaking code. Since ansible moves relatively quickly we should stay on top of these. 

## Steps to Reproduce

Run.... `./securedrop-admin install` !

## Expected Behavior

No deprecation warnings should display in the output.

## Actual Behavior

Lots of deprecation warnings!!!

```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
```
[DEPRECATION WARNING]: Included file
'/root/sd/molecule/aws/tasks/reboot_if_first_install.yml' not found, however
since this include is not explicitly marked as 'static: yes', we will try and
include it dynamically later. In the future, this will be an error unless
'static: no' is used on the include task. If you do not want missing includes
to be considered dynamic, use 'static: yes' on the include or set the global
ansible.cfg options to make all includes static for tasks and/or handlers. This
 feature will be removed in version 2.7. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
```

## Comments

Luckily the feedback from ansible is fairly verbose about how to address these issues. Simply walk through an install and note deprecation warnings, try implementing that code change, rinse and repeat. As part of this we should also test the ansible output in CI and fail if any deprecation warnings are detected going forward.

**Comment by heartsucker** [comment]
Related: https://github.com/ansible/ansible/issues/18559 and https://github.com/ansible/proposals/issues/32

**Comment by heartsucker** [comment]
I tried to do this yesterday, and I'm pretty sure it's not possible. The jinja/when syntax is seriously a fucking nightmare like it doesn't cast strings from some sort of `AnsibleUnescapedLiteral` or whatever and can't do `==` so it throws exceptions. I think we would be better bumping our ansible version in parallel.

**Comment by redshiftzero** [comment]
The only remaining Ansible deprecation warnings on `develop` are due to #4385, closing this one in favor of that more scoped issue
