### ISSUE TITLE
docs: proofread test_the_installation.rst for typos and style problems

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#3011]
## Description

Read https://github.com/freedomofpress/securedrop/blob/develop/docs/test_the_installation.rst and look for:

* typos
* [violations of the documentation guidelines](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html)

Rewording for clarity or adding content is not in the scope of this issue. When a typo or style problem is found, open a pull request fixing it and make sure to reference this issue so it is closed.

If no typo or style problem is found, add a comment to this issue. It will be closed after a few person report they did not find an issue.

**Comment by barun511** [comment]
I can't seem to see any typos. I might recommend changing "1. Make sure the Source Interface is available", to "1. Test that the Source Interface is available", so that instruction 1. is more consistent in terms of language used with the following instructions, but that's a minor nitpick, really.

**Comment by dachary** [comment]
* sudo passphrase for the Admin username

should be

     * sudo passphrase for the admin username

Because **admin** here designate an abstract idea, there is no reason for the first letter to be uppercase. @barun511 it was not something easy for you to spot I have to say ;-)

       instance all profiles should be in enforce mode.

should

        instance all profiles should be in ``enforce`` mode.

because it is an apparmor keyword. The [documentation guidlines](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html) do not recomment anything specific. But this seems to be in line with how ``-grsec`` is mentionned earlier in the page.

    Source Interface

should be 

    *Source Interface*

and

    Journalist Interface

should be 

    *Journalist Interface*

because it [is a SecureDrop-specific terminology](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html#style-guide)

The "onion URL" should unified to be "Onion URL".

     app-journalist-aths

should be 

     ``app-journalist-aths``

also

    Admin/Journalist Interface

should be

    *Admin/Journalist Interface*

also

     app-source-ths

should be 

     ``app-source-ths``

also

    Source and Journalist Interface

should be

    *Source Interface* and *Journalist Interface*

also

    'Delete selected'

should be

    **Delete selected**

because it [is a specific element from a user interface](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html#style-guide)

Would you be so kind to open a pull request fixing those ?

**Comment by barun511** [comment]
Thank you so much - it appears that I have missed quite a bit :) I appreciate the help and effort :D

I'll open a PR.

**Comment by barun511** [comment]
then login with the Admin username <--should this not be "then login with the admin username", by the same logic?

**Comment by dachary** [comment]
> then login with the Admin username <--should this not be "then login with the admin username", by the same logic?

Yes !
