### ISSUE TITLE
docs: proofread glossary.rst for typos and style problems

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#3012]
## Description

Read https://github.com/freedomofpress/securedrop/blob/develop/docs/glossary.rst and look for:

* typos
* [violations of the documentation guidelines](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html)

Rewording for clarity or adding content is not in the scope of this issue. When a typo or style problem is found, open a pull request fixing it and make sure to reference this issue so it is closed.

If no typo or style problem is found, add a comment to this issue. It will be closed after a few person report they did not find an issue.

**Comment by jroes** [comment]
Looks like `terminology.rst` doesn't exist on the `develop` branch anymore. Is it now in master? https://github.com/freedomofpress/securedrop/blob/master/docs/terminology.rst

**Comment by eloquence** [comment]
It was renamed:
https://github.com/freedomofpress/securedrop/blob/develop/docs/glossary.rst

**Comment by jroes** [comment]
Looks good to me, no typos! I also ran a grammar-checking tool against it as well with no errors.

**Comment by eloquence** [comment]
Thanks, @jroes! Leaving this issue open to allow for a second pass; much appreciate the review :)

**Comment by eloquence** [comment]
Closing; we'll highlight opportunities to proofread the docs at a higher level instead of having individual issues for proofreading sections.
