### ISSUE TITLE
docs: proofread tails_printing_guide.rst for typos and style problems

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#3013]
## Description

Read https://github.com/freedomofpress/securedrop/blob/develop/docs/tails_printing_guide.rst and look for:

* typos
* [violations of the documentation guidelines](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html)

Rewording for clarity or adding content is not in the scope of this issue. When a typo or style problem is found, open a pull request fixing it and make sure to reference this issue so it is closed.

If no typo or style problem is found, add a comment to this issue. It will be closed after a few person report they did not find an issue.

**Comment by Anonymous26** [comment]
I would like to work on this.

**Comment by dachary** [comment]
@Anonymous26 consider yourself assigned :-)

**Comment by championshuttler** [comment]
I would like to work on it :)

**Comment by eloquence** [comment]
Closing; we'll highlight opportunities to proofread the docs at a higher level instead of having individual issues for proofreading sections.
