### ISSUE TITLE
docs: replace *[Jj]ournalist tails... with *Journalist Workstation*

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#3014]
# Bug

## Description

In the [documentation](https://github.com/freedomofpress/securedrop/blob/develop/docs):

* ```*Journalist Tails USB*```  is the USB stick
* ```*Journalist Workstation*``` is the machine booted with the *Journalist Tails USB*

almost everywhere in the  . In some places it is

     *journalist tails USB*
     *Journalist tails USB*
     *journalist tails*
     **Journalist Tails**
    etc.

In other places, it shows as bold instead of italic:

     **Journalist Workstation**

All these variations must be unified and changed to:

* ```*Journalist Tails USB*```
* ```*Journalist Workstation*```

**Comment by Anonymous26** [comment]
There are variations in USB key for admin too, in some places its *Admin Tails*, am i supposed to change that also to *Admin Workstation* ?

**Comment by dachary** [comment]
> am i supposed to change that also to Admin Workstation ?

you can create another issues for the purpose of unifying *Admin Tails*.

**Comment by dachary** [comment]
> in some places Journalist Workstation is referred as the system they boot using their tails USB..so if i change the Journalist Tails USB to Journalist Workstation then it will create confusion in the sentence.

Which line is this ?

**Comment by Anonymous26** [comment]
Verify Journalist Setup Line 131 onwards in onboarding.rst.

**Comment by dachary** [comment]
@Anonymous26 good point. My issue description is incorrect and I will fix it. There is a distinction between:

* *Journalist Tails USB* which is the USB stick
* *Journalist Workstation* which is the machine booted with the *Journalist Tails USB*

We need to keep both as they designate two different things. I will change the bug description accordingly.

**Comment by Anonymous26** [comment]
okay ill fix it accordingly :)

**Comment by ultimatecoder** [comment]
This issue seems to be fixed #3028. Authority, Please close this one.

**Comment by eloquence** [comment]
As noted, we've done a lot of cleanup here, so closing.
