### ISSUE TITLE
docs: italicize Journalist Interface

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#3015]
# Bug

## Description

The [documentation style guidelines](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html#style-guide) reads "When SecureDrop-specific terminology is used, italicize it.".

Look for the string **Journalist Interface** in [the documentation](https://github.com/freedomofpress/securedrop/blob/develop/docs/) and make sure all occurrences are italicized. For instance [create_admin_account.rst](https://github.com/freedomofpress/securedrop/blob/develop/docs/create_admin_account.rst) is missing some.

**Comment by vaibssingh** [comment]
Created PR for updates in create_admin_account.rst  #3017
