### ISSUE TITLE
docs: replace *[Aa]dmin tails... with *Admin Workstation*

### ISSUE THREAD

**Issue by Anonymous26** [freedomofpress/securedrop#3023]
# Bug

## Description
The USB key used by the Admin is  

```
*Admin` Workstation*
```

almost everywhere in the [documentation](https://github.com/freedomofpress/securedrop/tree/develop/docs). In some places it is 

```
**Admin Tails**
*admin Tails USB*
*Admin Tails USB*
```

 In other places, it shows as bold instead of italics:

```
**Admin Workstation**
```

All these variations must be unified and changed to:

```
*Admin Workstation*
```

**Comment by redshiftzero** [comment]
Good point @Anonymous26. One comment: `*Admin Workstation*` can be used to generically refer to a computer that is booted using the Admin Workstation Tails USB. For clarity, I recommend you use the term `*Admin Workstation* Tails USB` where appropriate, e.g. in the [Admin Workstation Setup documentation](https://docs.securedrop.org/en/latest/set_up_admin_tails.html).

**Comment by Anonymous26** [comment]
@redshiftzero Instead of `*Admin Workstation* Tails USB` shouldn't I use `*Admin Tails USB*`as in the case of journalist `*Journalist Tails USB*` is used to represent Tails USB drive ?
