### ISSUE TITLE
CI build errors because it can't find a docker image tagged with the correct SHA1

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3049]
# Bug

## Description

A CI build failed with this error on the `lint` step.

```
#!/bin/bash -eo pipefail
TAG=${CIRCLE_SHA1} make ci-lint

devops/scripts/dev-shell-ci sudo make --keep-going lint typelint
Docker image build in progress  done !
Unable to find image 'securedrop-lint:6c6b89e171001df3804f59ffecca70fc327b65fa' locally
docker: Error response from daemon: pull access denied for securedrop-lint, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Makefile:28: recipe for target 'ci-lint' failed
make: *** [ci-lint] Error 125
Exited with code 2
```

## Steps to Reproduce

Unsure.

## Expected Behavior

CI builds should complete regardless of tags on the docker containers.

## Actual Behavior

It does not.

## Comments

We shouldn't tag the docker containers with a SHA1. Maybe just always use `latest` since we're always pulling the latest cached docker image and the SHA1 doesn't actually matter.

**Comment by heartsucker** [comment]
This is the build error: https://circleci.com/gh/freedomofpress/securedrop/8807?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

And it was from this PR: https://github.com/freedomofpress/securedrop/pull/3047

**Comment by dachary** [comment]
@heartsucker that's an error that happened 11 hours ago and fixed by https://github.com/freedomofpress/securedrop/pull/3039 which was merged 8 hours ago. My apologies for the inconvenience.

**Comment by heartsucker** [comment]
If the next build of #3047 passes, we can close this ticket as already resolved.

**Comment by dachary** [comment]
It passed, closing as instructed
