### ISSUE TITLE
Scrypt params are defined in multiple places

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3051]
# Feature request

## Description

We define scrypt params in `_SCRYPT_PARAMS` in `models.py::Journalist` and in `crypto_util.py`. This is a potential source of errors since we assume they are defined in only one place.

## User Stories

As a dev, I want constants defined in exactly one place.

**Comment by pwnchief** [comment]
@heartsucker  can i take this up ??

**Comment by heartsucker** [comment]
Yeah, just to clarify what needs to be done (because I wrote this ticket quickly while on a video chat), in `models.py`, we need to remove `Journalist._SCRYPT_PARAMS`. However, this impacts the behavior of `Journalist._scrypt_hash` which affects `Journalist.set_password` and `Journalist.valid_password`.

This shouldn't be a problem because `Journalist._SCRYPT_PARAMS` == config.SCRYPT_PARAMS` in prod instances, *BUT* it's possible that an admin edited their `config.py` by hand and changed the values which would mean if we move this hash value from whatever is hardcoded to the value in `config.py` *AND* those values are different, then journalists would be locked out. However, sources would **not** be locked out.

I don't know if we should change this right now. We might want to wait until our configuration updates have landed in develop (#3033) and then decide what values we can change and what values we're going to remove from the admins' control. Because honestly, I don't think that we should let admins set the scyrpt params themselves.

Also, the above errors won't be a problem any more once we move to `passlib` (#2918). `passlib` handles the cases where hash algorithms and params are changed to prevent lockouts.

**Comment by pwnchief** [comment]
Yeah it would break current installations with modified `config.SCRYPT_PARAMS` which would be a big problem and its fair to assume some would have.So they might need to generate new passwords after update.Also admin would also face the same problem as they follow the same setup procedure with an additional `is_admin=True` argument while creating user so they would also be locked out.

Also #3033 would change app configuration significantly and we might need to review changes.I also think we should wait  for these changes to get merged with `develop`. Waiting for feedback!!

**Comment by heartsucker** [comment]
I actually think it's *extremely* unlikely an admin touched that part of their config, but since it's possible we have to assume at least one did. It wouldn't matter if they wanted to regenerate new passwords because since no one would be logged in, there would be no way to do a reset.

**Comment by pwnchief** [comment]
@heartsucker Yeah i guess you are right.
Waiting for #3033 to merge into develop!!

**Comment by redshiftzero** [comment]
for `SCRYPT_PARAMS` in `models.py`:

1. in `models.Journalist` we've been using the hardcoded `SCRYPT_PARAMS` value
2. this got removed in #3506 (well, renamed to `_LEGACY_SCRYPT_PARAMS` for use in migrations to argon)

for `CryptoUtil.scrypt_params`  in `crypto_util.py`:

1. this `scrypt_params` is indeed using the value in `config.py`, so we have to leave it be for the valid reason that admins _may have_ modified it (if we make assumptions we'll lock out sources, since we're hashing their codenames using this `scrypt_params`)

as such, closing this
