### ISSUE TITLE
Ensure every call to `open` uses a context manager

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3052]
# Feature request

## Description

There are places in the code where we call `foo = open(some_file).read()`. This could lead dangling resources if an exception is raised. This should be:

```python
with open(some_file) as f:
    foo = f.read()
```

**Comment by conorsch** [comment]
At a glance, here are a few candidates in important dirs:

```
$ find securedrop/ install_files/ -type f -iname '*.py' -exec grep -rP '(?<!with)\s+open\(' {} +  
securedrop/tests/conftest.py:        tmp_logfile = open('/tmp/test_rqworker.log', 'w')
securedrop/tests/test_manage.py:        pot = open(messages_file).read()
securedrop/tests/test_manage.py:        po = open(po_file).read()
securedrop/tests/test_manage.py:        i18n = open(i18n_file).read()
securedrop/tests/test_manage.py:        pot = open(messages_file).read()
securedrop/tests/test_manage.py:        mo = open(mo_file).read()
securedrop/tests/test_manage.py:        pot = open(messages_file).read()
securedrop/tests/test_manage.py:        mo = open(mo_file).read()
securedrop/tests/test_manage.py:        open(os.path.join(config.TEMP_DIR, 'FILE'), 'a').close()
securedrop/tests/test_store.py:            actual_file_content = open(actual_file).read()
securedrop/tests/functional/test_submission_not_in_memory.py:        self.devnull = open('/dev/null', 'r')
securedrop/tests/functional/functional_test.py:        log_file = open(join(LOG_DIR, 'firefox.log'), 'a')
securedrop/tests/pages-layout/functional_test.py:        fd = open(os.path.join(self.log_dir, filename), 'wb')
securedrop/secure_tempfile.py:        self.file = open(self.filepath, 'w+b')
securedrop/source_app/main.py:                    open(reply_path).read()).decode('utf-8')
install_files/ansible-base/roles/backup/files/0.3_collect.py:    stream = open(zf_fn, "rb")
install_files/ansible-base/roles/tails-config/files/securedrop_init.py:    torrc_additions = open(path_torrc_additions).read()
install_files/ansible-base/roles/tails-config/files/securedrop_init.py:    torrc = open(path_torrc_backup).read()
install_files/ansible-base/roles/tails-config/files/securedrop_init.py:        torrc = open(path_torrc).read()
install_files/ansible-base/roles/tails-config/files/securedrop_init.py:    open(path_torrc_backup, 'w').write(torrc)
```

Whether all should be changed is subject to debate, but we at least have an idea about what needs to be changed here. There are a lot of hidden directories that include upstream code we do not maintain, e.g.

* `.venv/`
* `admin/.tox/`
* `admin/.venv/`
* `admin/.eggs/`

> This could lead dangling resources if an exception is raised. 

True, but recall that the servers are rebooting nightly, so anything dangling will be cleaned up within 24h. The restricted time window suggests to me that open filehandles are unlikely to lead to degraded performance in production servers, and extremely unlikely to result in DoS.

**Comment by heartsucker** [comment]
In the PR for this, I left the ones in test cases alone since it makes it easier to read the tests. And yes, this is super minor but I noticed one during the video call and it annoyed me so here we are. :D

**Comment by dachary** [comment]
> This could lead dangling resources if an exception is raised. 

Do you maybe have a reference about how this could be the case ? If the exception is not caught well, nobody cares of course ;-) If the exception is caught, the function in which the open was done will go out of scope after it is handled and the file descriptor will be reclaimed. At least that's how I understand it.

What am I missing ?

**Comment by heartsucker** [comment]
From the bottom of [this section](https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects):

> It is good practice to use the with keyword when dealing with file objects. This has the advantage that the file is properly closed after its suite finishes, even if an exception is raised on the way. It is also much shorter than writing equivalent try-finally blocks:

**Comment by dachary** [comment]
While I agree with @conorsch that it's not something that's more than a cleanup, it feels good to comply with best practices so... why not :-)
