### ISSUE TITLE
Various problems with securedrop-admin 

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#3060]
# Bug

## Description

The `securedrop-admin` script underwent substantial changes in #2758. Below are a few examples of what seem to be regressions, but all instances bear scrutiny in order to reproduce. 

### "setup" subcommand appears broken

The project docs instruct Admins to run `./securedrop-admin setup` in order to configure a virtualenv. The new behavior appears buggy:

```
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin setup -v
./securedrop-admin: line 13: /home/amnesia/Persistent/securedrop/admin/.venv/bin/securedrop-admin: No such file or directory
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin -v setup
INFO: Virtualenv already exists, not creating
INFO: Checking Python dependencies for securedrop-admin
INFO: Python dependencies for securedrop-admin are up-to-date
ERROR: Unable to install self, run with -v for more information
amnesia@amnesia:~/Persistent/securedrop$ stat .venv
stat: cannot stat '.venv': No such file or directory
amnesia@amnesia:~/Persistent/securedrop$ stat ./admin/.venv
  File: ./admin/.venv
  Size: 4096      	Blocks: 16         IO Block: 4096   directory
Device: 2ch/44d	Inode: 10805276    Links: 7
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ amnesia)   Gid: ( 1000/ amnesia)
Access: 2018-02-22 00:52:58.362725970 +0000
Modify: 2018-02-22 00:41:20.153904179 +0000
Change: 2018-02-22 00:52:58.182727271 +0000
 Birth: -
amnesia@amnesia:~/Persistent/securedrop$ rm -rf ./admin/.venv
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin setup
INFO: Installing SecureDrop Admin dependencies
INFO: You'll be prompted for the temporary Tails admin password, which was set on Tails login screen
[sudo] password for amnesia: 
```

The script then proceeds with apt installation, which appears to work well. However, the virtualenv stage still fails:

```
INFO: Setting up virtualenv
INFO: Checking Python dependencies for securedrop-admin
INFO: Python dependencies for securedrop-admin upgraded
ERROR: Unable to install self, run with -v for more information
```

### Lack of verbosity
The script doesn't reliably produce more verbosity. This is particularly frustrating when the script requests additional verbosity via the `-v` flag, then refuses to provide it:

```
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin setup
INFO: Virtualenv already exists, not creating
INFO: Checking Python dependencies for securedrop-admin
INFO: Python dependencies for securedrop-admin are up-to-date
ERROR: Unable to install self, run with -v for more information
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin -v setup
INFO: Virtualenv already exists, not creating
INFO: Checking Python dependencies for securedrop-admin
INFO: Python dependencies for securedrop-admin are up-to-date
ERROR: Unable to install self, run with -v for more information
```

Even more confusing:

## Loss of helpful messaging
Also, we lost helpful messaging on the SecureDrop Admin script when the virtualenv is not configured:
```
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin sdconfig
./securedrop-admin: line 13: /home/amnesia/Persistent/securedrop/admin/.venv/bin/securedrop-admin: No such file or directory
```

The above command, without a virtualenv, _should_ display something more friendly, such as:

```
ERROR: Pre-requisites not in place, re-run command with 'setup'
```

It used to do so.

## Comments

Perhaps the problems outlined above are specific to my dev env—please try to reproduce with an open mind, and let me know if you have trouble. In particular, the Makefile changes for Linux/libvirt introduced in #2607 may be relevant here—perhaps I have not been diligent in policing the extended attributes, and the permissions errors are masked. Even if that's the case, I would expect more friendly messaging from the script.

**Comment by conorsch** [comment]
Falling back to 0.5.2 (via `git checkout 0.5.2`) resolves the issues above for me.

**Comment by conorsch** [comment]
> Perhaps the problems outlined above are specific to my dev env—please try to reproduce with an open mind, and let me know if you have trouble. In particular, the Makefile changes for Linux/libvirt introduced in #2607 may be relevant here

To rule out complications with mounting directories via Tails, I instead _cloned_ the SecureDrop repository in Tails, and `./securedrop-admin setup` still fails as described above.

Again, falling back to 0.5.2 resolves: I am able to run `./securedrop-admin setup` without issue. After having done so, I can switch back to `develop`, and then subsequent runs of `./securedrop-admin setup` complete without error.

**Comment by redshiftzero** [comment]
Running through the above on Tails produced the expected output:

```
amnesia@amnesia:~/Persistent/securedrop$ rm -rf ./admin/.venv/
amnesia@amnesia:~/Persistent/securedrop$ rm -rf .venv
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin setup -v
please run './securedrop-admin setup' first
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin -v setup
INFO: Installing SecureDrop Admin dependencies
INFO: You'll be prompted for the temporary Tails admin password, which was set on Tails login screen
[sudo] password for amnesia: 
Ign:1 tor+http://vwakviie2ienjx6t.onion/debian stretch InRelease
Hit:2 tor+http://sdscoq7snqtznauu.onion/torproject.org stretch InRelease
Hit:3 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates InRelease
Hit:4 tor+http://vwakviie2ienjx6t.onion/debian sid InRelease
Hit:5 tor+http://sdscoq7snqtznauu.onion/torproject.org sid InRelease
Hit:6 tor+http://jenw7xbd6tf7vfhp.onion 3.3 InRelease
Hit:7 tor+http://vwakviie2ienjx6t.onion/debian stretch Release
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
ccontrol is already the newest version (1.0-1+b2).
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0f-3+deb9u1).
python-pip is already the newest version (9.0.1-2).
python-virtualenv is already the newest version (15.1.0+ds-1).
virtualenv is already the newest version (15.1.0+ds-1).
libpython2.7-dev is already the newest version (2.7.13-2+deb9u2).
python-yaml is already the newest version (3.12-1).
0 upgraded, 0 newly installed, 0 to remove and 168 not upgraded.
INFO: Setting up virtualenv
INFO: Checking Python dependencies for securedrop-admin
INFO: Python dependencies for securedrop-admin upgraded
INFO: Finished installing SecureDrop dependencies
amnesia@amnesia:~/Persistent/securedrop$ stat .venv
stat: cannot stat '.venv': No such file or directory
amnesia@amnesia:~/Persistent/securedrop$ stat admin/.venv/
  File: admin/.venv/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fe00h/65024d	Inode: 132326      Links: 7
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ amnesia)   Gid: ( 1000/ amnesia)
Access: 2018-02-23 23:52:13.844000000 +0000
Modify: 2018-02-23 23:52:13.880000000 +0000
Change: 2018-02-23 23:52:13.880000000 +0000
 Birth: -
```

The helpful messaging when the venv is not configured is present for me:

```
amnesia@amnesia:~/Persistent/securedrop$ rm -rf .venv
amnesia@amnesia:~/Persistent/securedrop$ rm -rf admin/.venv/
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin sdconfig
please run './securedrop-admin setup' first
```

However- if you're hitting an issue and not receiving informative error output when you pass `-v`, that indeed sounds like a bug...

**Comment by redshiftzero** [comment]
You could put in some breakpoints (`import pdb; pdb.set_trace()`) in order to step through so we can diagnose what `Unable to install self` refers to

**Comment by conorsch** [comment]
Unable to reproduce problems on the latest `release/0.6` branch. I've started cloning the git repo directly in Tails as a closer approximation to actual Admin usage. The `9p` mounting strategy continues to cause problems for me, so I'll stick with the clone option and work from remote branches.

Closing the issue—if anyone has lingering problems, comment here or reopen.
