### ISSUE TITLE
[RFE] Use io.open instead of open function call in the codebase

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3063]
# Feature request

## Description

We should start using [`io.open`](https://docs.python.org/2.7/library/io.html#io.open) instead of the builtin function `open`  in Python2 so that we can move another step towards Python3. 

In Python3 `open` function call is actually the same of `io.open`. But, that is not the same in Python2. That is why moving to `io.open` in Python2 is [step forward](https://docs.python.org/3/howto/pyporting.html#update-your-code) to Python3 land.

Always remember, [the clock is ticking](https://docs.python.org/3/howto/pyporting.html#update-your-code).

**Comment by heartsucker** [comment]
Not saying we shouldn't, but if `open` "just works" now, is there a compelling reason to change it before we make the actual switch to `python3`? I feel like there's bigger fish to fry.

**Comment by kushaldas** [comment]
@heartsucker That is our official suggestion for projects trying to move into Python3. Please have a look at the https://docs.python.org/3/howto/pyporting.html#update-your-code

**Comment by heartsucker** [comment]
Fair enough. I've just been lazy and ported whole projects with `2to3` all at once. Ha.
