### ISSUE TITLE
Downloaded submissions should reflect the logged in journalist's status

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop#3074]
# Feature request

## Description

Currently on a SD production installation, if an installation has multiple journalists and any one journalist downloads a submission, the SD interface will show the submission as downloaded. It could be better to only show the files as download if the logged in journalist has downloaded the submission. I believe we already store this data in the database. 

## User Stories

As a journalist, I want to download the archives that I have not seen and would like the UI to reflect that.

**Comment by b-meson** [comment]
I believe this correctly captured a statement made by @redshiftzero during an application code review session. Please correct me if I misunderstood the issue.

**Comment by conorsch** [comment]
The proposal here goes against the grain of the "shared inbox" strategy currently used by SecureDrop. For organizations that use journalists on a rotation for checking SecureDrop, it's meaningful and useful to have the "read" status be global. 

The changed proposed here is certainly worth considering, but we should engage UX experts and solicit additional feedback from the training team before implementing.

**Comment by zenmonkeykstop** [comment]
Closing, this functionality is mostly implemented in the SecureDrop Workstation client, and further improvements will probably be focused there.
