### ISSUE TITLE
Tooling to build arbitrary package versions without bumping repo

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3080]
# Feature request

## Description

The current `update_version.sh` script will bump versions BUT does  a lot of other tooling related to tags that are not always desired. We need more specific abstraction to just build higher versions of debian packages locally -- this would solve a lot of issues I'm currently hitting with upgrade testing in #3018 .

## User Stories

As a securedrop developer, I want to be able to build and test higher versions of debian packages locally without bumping the tag for the entire repository.

**Comment by redshiftzero** [comment]
Hey @msheiny do ya still want this implemented?

**Comment by msheiny** [comment]
ummmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm ... i guess if we continue to bump versions in `develop` to a future version (past whats released) the need is not as urgent but I still think its a useful tool to have for testing. So I leave the decision up to you @redshiftzero . I say if you want to clean up the issue list just squash it and i can always re-open if the need re-arises.

**Comment by eloquence** [comment]
We will revisit this when we consolidate packaging strategies between SecureDrop Core and SecureDrop Workstation, closing.
