### ISSUE TITLE
New source can not login after db reset

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3085]
# Bug

## Description

A new source can not login to the source interface. It generates the 

## Steps to Reproduce

- ssh into the app server.
- `sudo su`
- `cd /var/www/securedrop`
- `./manage.py reset`
- `service apache2 restart` or `dpkg-reconfigure securedrop-app-code`
- Try to login to the source interface

## Expected Behavior

A new source should be able to login and submit documents.

## Actual Behavior

Showing server error when we click on the "SUBMIT DOCUMENTS" link.

(This is an updated vm from 0.5.2)

**Comment by dachary** [comment]
@kushaldas are you able to reproduce the bug with

* sudo -u www-data bash
* cd /var/www/securedrop
* /manage.py reset

Just to make sure this is not a permission problem introduced by the fact that the manage.py command is run by root.

**Comment by kushaldas** [comment]
And @dachary is right. Closing the issue.
