### ISSUE TITLE
Re-engineer FPF apt infrastructure

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3086]
# Feature request

## Description

The current deployment apt architecture uses a combination of full-stack servers and aptly to manage and publish snapshots. These are additional host(s) we need to maintain and secure which is overkill in this magical age of cloud storage services. I also argue that the current architecture is more susceptible to DDoS in it's current format since there is no origin protection.

Sooo let's move to s3 buckets + a CDN (cloudflare, cloudfront, etc.). You might say, well yeah okay but then there is risk of MiTM attacks if the CDN is comprised/compelled to offer a backdoor. I would argue thats true but theres also an increased attack surface from us having to maintain and patch a full stack server just to serve up files (the current status quo). To increase protection against apt attacks, we should also in tandem do two things when we switch to buckets:

* add expiration tags to our `Release` files (see #2436 )
* peg the local gpg key to be utilized for verifying our apt repo (see `Signed-By` at https://wiki.debian.org/DebianRepository/Format#A.22Release.22_files).

## User Stories

As a securedrop ops maintainer, I want to reduce the number of full stack servers FPF runs when we can avoid it.

**Comment by eloquence** [comment]
I would like @emkll to weigh in here from a risk assessment perspective. Generally, when changes impact our security exposure, we should very carefully compare:
- current risk profile
- risk profile after suggested change
- risk profile after alternative (e.g., hardening current setup)

**Comment by emkll** [comment]
I agree with @msheiny , the less servers the better. Package signatures should guarantee the integrity and authenticity of packages. There would definitely be an improvement in security (mainly due to less attack surface) and a reduction in maintenance costs.

However, the use of these services may increase the ability for an adversary to fingerprint of SD instances. If we would eventually want to serve these through a tor hidden service and reduce the fingerprintability of SD instances as described #1204 , we would likely still a (albeit less complex) server to proxy the connection.

**Comment by eloquence** [comment]
Just capturing the plan of record here: Mike is continuing to work on the FPF infrastructure side of this (tracked outside of this repo), but we're anticipating that we'll still ship 0.7 using the legacy infra. We should be able to then extensively test the new S3 buckets, and ship the next release after 0.7 with them.

**Comment by ageis** [comment]
It makes sense for you to move repositories to the cloud. I recommend Google Cloud Storage too, their command-line tools and SDK are excellent. Are you going to shell out for the [CloudFront Custom SSL](https://aws.amazon.com/cloudfront/custom-ssl-domains/)? Not sure how you'd have TLS for that idea unless there's some termination/redirection somewhere or CNAME or domain fronting.

**Comment by msheiny** [comment]
> Are you going to shell out for the CloudFront Custom SSL? Not sure how you'd have TLS for that idea unless there's some termination/redirection somewhere or CNAME or domain fronting.

Ehh? we are already doing this for https://tor-apt.freedom.press/ . The price is only $600/month if you use a dedicated IP -- its affordable if you utilize custom certs over SNI. 

Now to anticipate your next comment ;) if you want to discuss obfuscating the cleartext SNI string being passed.... i definitely agree that is another great discussion to be had. Though I'd prefer to have that squabble in another ticket. :rainbow:

**Comment by conorsch** [comment]
This work has been completed. Regarding `Valid-Until`, we added that to prod back in Feb 2020. It's still active:

```
$ curl -s https://apt.freedom.press/dists/xenial/Release | grep -i valid
Valid-Until: Sun, 11 Apr 2021 17:59:46 UTC
```

Regarding S3 buckets, we did experiment with that setup briefly, but ended up using git-lfs-backed reprepro repositories: https://github.com/freedomofpress/securedrop-dev-packages-lfs/
