### ISSUE TITLE
./securedrop-admin setup misses to update Ansible to 2.4.2

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3088]
# Bug

This is in the update story from 0.5.2.

## Steps to Reproduce

To do QA work for `0.6-rc2` I moved into the tag, and ran the following command which worked as it was supposed to do:  `./securedrop-admin setup`.

Next, as part of the QA process I did the following steps.

- `source .venv/bin/activate`
- `cd install_files/ansible-base`
- `ansible-playbook -vv --diff sequredrop-qa.yml`

Please specify your environment if that is necessary to reproduce the bug (if in
doubt, include it).

## Expected Behavior

The ansible-playbook command should work properly.

## Actual Behavior

It failed saying  Ansible 2.4.2.x is required.

# Feature request

## Description

A short summary of the idea.

## User Stories

If appropriate

**Comment by msheiny** [comment]
Confirmed. I'm also seeing this.

**Comment by msheiny** [comment]
Soooo looks like the .venv got moved to `admin/.venv` ...but the existing one is still in-place ... so its not really a bug but I think perhaps we should clean it up as part of the `securedrop-admin` script?

**Comment by kushaldas** [comment]
>Soooo looks like the .venv got moved to admin/.venv ...but the existing one is still in-place ... so its not really a bug but I think perhaps we should clean it up as part of the securedrop-admin script?

Means the QA instructions also need an update :) Thank you for finding this.

**Comment by dachary** [comment]
@kushaldas would you be so kind as to try https://github.com/freedomofpress/securedrop/pull/3092 to confirm it works for you?

**Comment by redshiftzero** [comment]
Reopening until we cherry-pick the change into `release/0.6`

**Comment by redshiftzero** [comment]
done in #3098
