### ISSUE TITLE
Stuck waiting for network configuration 

### ISSUE THREAD

**Issue by elgreg** [freedomofpress/securedrop#3089]
`./securedrop-admin install` fails and mon and app boxes become unreachable

SecureDrop v0.5.2
Tails (admin box) - 3.3

After running `./securedrop-admin install`, the app and mon boxes both reboot after some time.

Unfortunately, they both then hang waiting for Network Configuration.

![img_6954](https://user-images.githubusercontent.com/40772/36863473-cc2e2720-1d57-11e8-99d6-af294497fd2e.PNG)
![img_6957](https://user-images.githubusercontent.com/40772/36863481-d19f2722-1d57-11e8-93f7-8ed840bb2535.PNG)
![img_6955](https://user-images.githubusercontent.com/40772/36863484-d42a3c98-1d57-11e8-81b0-eab0f5bc4428.PNG)

The ansible script on the amdin box waits for the boxes to come back, but when they hang, the script eventually fails.

Also (I think because the ansible script failed), we do not have an app-source-ths or any other ths files and can no longer access the mon and app servers.

--

We have repeated this twice (after having to wipe the drives completely from app and mon by removing them and putting them in a sled).

Is there any explanation for why the app and mon boxes would not be able to get a Network Configuration? We looked over the firewall configuration and it seems fine...

**Comment by msheiny** [comment]
hey @elgreg can you provide hw details of the machine you are running from? We've been using this script to try and extract info from instances without exposing too much information. https://github.com/freedomofpress/support-server-facts. Most importantly I recommend that you boot into one of the servers in `single user mode` and check to see if your interfaces are even showing up as expected.

From a quick glance and a guess, it looks like the older kernel doesnt support your network driver.... Though I'm just conjecturing - we need more data. You are in luck though, we are QAing a new release now with a much newer kernel. I'm hoping if you are experiencing a network kernel driver issue that the new release will alleviate these.

**Comment by conorsch** [comment]
Yes, platform info would be quite useful here. We'll be updating the kernels used in SecureDrop as part of the upcoming 0.6 release (slated for 2018-03-13). Hopefully they'll work for you, but more info required.

**Comment by elgreg** [comment]
Thanks for the quick reply! https://github.com/freedomofpress/support-server-facts 404s for me.

Is there a command I can run that will help to give you various hardware info quickly?

If I boot into the mon server as the root user and `less /etc/network/interfaces` I get the following:

```
auto lo
iface lo inet loopback

# The primary network interface
auto em1
iface em1 inet static
  addresss 10.20.3.2
  netmask 255.255.255.0
  network 10.20.3.0
  boradcast 10.20.3.255
  gateway 10.20.3.1
  # dns-* options are implementd by the resolveconf package, if installed
  dns-nameservers 8.8.8.8
```

I hand-typed this starting at that screen so apologies for the copy-paste. 😁 

Here are the results of a sdo lshw (sorry - screenshots are pretty much all I can do at the moment).


![img_6958](https://user-images.githubusercontent.com/40772/36865362-51315cd0-1d5d-11e8-994e-b9e552a8fb10.JPG)
![img_6959](https://user-images.githubusercontent.com/40772/36865363-5143d48c-1d5d-11e8-8a27-c99d8d7f6d57.JPG)
![img_6960](https://user-images.githubusercontent.com/40772/36865364-5176e2e6-1d5d-11e8-8b6b-54fb1da999ef.JPG)
![img_6962](https://user-images.githubusercontent.com/40772/36865365-51864c90-1d5d-11e8-9df2-fcae067cf10a.JPG)
![img_6967](https://user-images.githubusercontent.com/40772/36865366-51b6005c-1d5d-11e8-9061-fc24f0874704.JPG)

**Comment by this-is-ian** [comment]
Hello @msheiny I'm working with @elgreg on this installation. We are using two of the recommended Intel NUCs for the servers This is the model with 8GB RAM and Samsung 250GB SSD drives https://www.newegg.com/Product/Product.aspx?Item=N82E16856102144

I'm currently looking at the firewall config as well and double-checking it against the instructions.

**Comment by this-is-ian** [comment]
I've taken a few more cracks at this from the firewall end of the configuration, running the install, reformatting the servers after each attempt, etc. and still running in to the same roadblock.

**Scenario:**
• I initiate the installer from the admin workstation.
• It proceeds up to the point where it triggers the servers to reboot.
• During the reboot process, both servers hang up at...
_Waiting for network configuration..._
_Waiting up to 60 more seconds for network configuration_
• After the timeout, both servers proceed to the log in screen.
• The installer on admin workstation then displays the following error:
_RUNNING HANDLER [common : wait_for] **************************************************************************************************************************
fatal: [mon -> localhost]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in 10.20.3.2:22"}
fatal: [app -> localhost]: FAILED! => {"changed": false, "elapsed": 301, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in 10.20.2.2:22"}_

**Notes:**
• Able to SSH from all three machines pre-install.
• In the troubleshooting process, I've enabled all SSH traffic across all three firewall interfaces between the app, mon and admin machines.
• App and mon are reformatted and Ubuntu reloaded after each attempt.
• The admin workstation is a MacBook Air with a Thunderbolt to Ethernet adapter and booting from a Tails SD card.

Any thoughts are greatly appreciated.

@msheiny @elgreg

**Comment by msheiny** [comment]
heyy @this-is-ian  @elgreg !

I'd love to help you out more --- so lets move this issue to our [discussion forum](https://forum.securedrop.club/).  I've went ahead and opened a support issue copying and pasting most of this content --> https://forum.securedrop.club/t/stuck-waiting-for-network-configuration-after-install/481

Unless this turns out to be a software bug, then we can re-open a new issue specifically to address that.

--Mike

**Comment by this-is-ian** [comment]
Thank you @msheiny
