### ISSUE TITLE
`tails-securedrop` deb package

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#309]
SecureDrop needs TAILS users to do a number of things every time they boot up. Some of these things (like setting `torrc` parameters) require root permissions. TAILS doesn't yet support custom startup scripts, but does support automatically installing certain deb pacakges at startup.

In issue #282, @micahflee suggested creating a `tails-securedrop` package which does all the configuration SecureDrop needs on TAILS, and which depends on all the other packages SecureDrop users may need. That's a great idea.

**Comment by conorsch** [comment]
We're now using the `securedrop-admin` script to bootstrap the Tails environment and configure persistence so that the changes stick around across reboots. These improvements were added in #1781 and #1803.
