### ISSUE TITLE
Syscheck should not monitor integrity of Tor hidden service private keys

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3090]
# Bug

## Description

#2963 introduced syscheck monitoring of /var/lib/tor/services. @redshiftzero pointed out that with these changes, Tor hidden service private keys are being monitored.
While OSSEC will only send an email upon changes to the file and the hash should always remain on the mon server as the key should not change, the hostname file should be sufficient to monitor the integrity of the hidden service.
This change has only been recently introduced and is not yet running on production SecureDrop instances. 
A short summary of the issue.

## Steps to Reproduce

Inspect `/var/ossec/queue/syscheck/\(app-staging\)\ 10.0.1.2-\>syscheck` and observe MD5 and SHA1 hashes of:
- /var/lib/tor/services/ssh/private_key
- /var/lib/tor/services/journalist/private_key
- /var/lib/tor/services/source/private_key

## Expected Behavior

Private key material should not be monitored by the IDS unless it is absolutely necessary for the integrity of the service.

## Actual Behavior

Private key material is being hashed by the IDS and send to to Monitor server.

**Comment by redshiftzero** [comment]
Reopening this so we make sure the change brought into develop in #3091 is merged into the 0.6 release branch

**Comment by redshiftzero** [comment]
Closed by #3094
