### ISSUE TITLE
Mirror/snapshot all upstream repos

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3095]
# Feature request

## Description

There are a number of inherent cons with the current strategy allowing deployed securedrop instances to directly grab the latest updates from upstream ubuntu repos:

1. This has the possibility to break the system in un-foreseen ways. We've seen this with `tor` which lead to use mirroring and snap-shoting those repos. Although we have'nt seen it YET in ubuntu - that doesn't mean the situation is impossible. We are trying to QA a constantly moving target -- as a parallel, why don't we also auto-update pip dependencies to the latest? This is VERY common practice in enterprise environments to freeze upstream repository versions so we test exactly the same thing in QA as what is deployed to clients.

2. Some ubuntu repos are served over HTTP . This lead to a potential security vuln in 2017 leading us to do a massive reinstall.

3. Since we do not perform QA in-front of the ubuntu repos, we are also opening up our admins for a deluge of annoying ossec syscheck alert emails everytime an upstream package updates. This leads to false positive alerts and for the admin to essentially mistrust the system. We've also had requests for support from instances to have us provide checksums for packages installed.. with the rolling nature of the current status quo, this is  a huge burden to go back and try and track.

Here's a screen shot of me getting spammed with apt-cron updates (both from our securedrop updates and from system updates). These alerts are essentially useless for me as an admin and causes alert fatigue (legitimate alerts fall through the cracks).

![image](https://user-images.githubusercontent.com/1727935/36869358-6dabf59c-1d93-11e8-8ac2-35f9a6770d0a.png)

So proposal is and this is a multi-ticket issue: 

* Mirror and snapshot upstream Ubuntu repos. Closely monitor ubuntu security alerts - this is important because we may have to update our snapshot and QA quickly to push out updates.

* Start building good known hashes during release process and push those out to users, that way if files change outside of our release window -- its a sign that something weird is going on for real! This is probably it's own ticket to be honest.

* Distribute a customized ISO ( #1532 ) for installs that comes preloaded with our apt-key and points to our apt repositories.

* We might also want to consider throwing all of the files behind tor hidden service to satisfy #1204 though we would have to make serious changes first to ensure that we are able to serve up files timely (maybe time to investigate next gen onion or reducing anonymity of our hidden service to increase bandwidth)

## User Stories

As a securedrop developer, I want to know that I am QAing the same exact version (same package versions across the board) of a securedrop instance as I deploy.

As a securedrop admin, I don't want to receive ossec syscheck alerts about package changes that are benign.

**Comment by legoktm** [comment]
This is similar enough to #2146 that I think the same rationale applies:
> The remaining risk of a bad package upgrade has to be balanced with the speed of how fast we want security updates to be applied. I think our current risk posture is a good balance between getting updates out quickly.
