### ISSUE TITLE
docs: Document `securedrop-admin update` and `securedrop-admin check_for_updates`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3096]
# Bug

## Description

SecureDrop 0.6 introduces a `securedrop-admin update` and a `securedrop-admin check_for_updates` command (https://github.com/freedomofpress/securedrop/pull/3026). This is great as it significantly simplifies the administration of Tails workstations. However, these commands are not referenced in the documentation yet.

It is worth noting that the `update` command also checks for updates, so running `check_for_updates` by itself is mostly useful as a pre-flight check. But it should also be documented.

## User Stories

As a SecureDrop administrator, I would like to get clear instructions for how to keep the workstations I am responsible for up-to-date.

**Comment by redshiftzero** [comment]
Thanks for filing @eloquence - adding a section about updating the SecureDrop Tails workstation in the [Administrator Guide](https://docs.securedrop.org/en/latest/admin.html) should do the trick.

**Comment by redshiftzero** [comment]
Closed by #3117 and #3120
