### ISSUE TITLE
Update installer.patch (mentioned in the virtualizing_tails.rst) with respect to Tails 3.5

### ISSUE THREAD

**Issue by Anonymous26** [freedomofpress/securedrop#3105]
# Bug

## Description

The [installer.patch](https://docs.securedrop.org/en/latest/development/virtualizing_tails.html) is outdated (fails on Tails 3.5).

## Steps to Reproduce
1. In tails VM create a file installer.patch (copy and paste the patch from virtualizing_tails.rst)
2. Run the following command in the terminal `sudo patch -p0 -d/ < installer.patch`  

## Actual Behavior
`root@amnesia:/home/amnesia/temp# sudo patch -p0 -d/ < installer.patch
patching file /usr/lib/python2.7/dist-packages/tails_installer/creator.py
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] y
Hunk #1 FAILED at 615.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python2.7/dist-packages/tails_installer/creator.py.rej
patching file /usr/lib/python2.7/dist-packages/tails_installer/gui.py
Hunk #1 FAILED at 483.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python2.7/dist-packages/tails_installer/gui.py.rej`

**Comment by redshiftzero** [comment]
Reopening, there's a small whitespace difference in the patch in #3104
