### ISSUE TITLE
[0.6.0] Upgrade SecureDrop instances to Tor 0.3.2.10

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3107]
## Description

We should QA [Tor 0.3.2.10](https://blog.torproject.org/new-stable-tor-releases-security-fixes-and-dos-prevention-03210-03110-02915) as part of SecureDrop 0.6.0. 

## User Stories

As a SecureDrop user, I want to be running the latest stable version of all software.

**Comment by msheiny** [comment]
PEW PEW PEW. Change pushed to prod.
