### ISSUE TITLE
/account/reset-2fa-hotp does not catch TypeError

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#3124]
# Bug

## Description

When modifying the HOTP as a journalist (not in the admin interface), TypeError are not caught and a stack trace shows when debug is activated. Otherwise it would bubble to whatever catches server errors.

## Steps to Reproduce

* login as a journalist
* go to /account/account
* click /account/reset-2fa-hotp
* enter three letters
* click save

## Expected Behavior

An error message similar to what happens with /admin/reset-2fa-hotp

## Comments

The /admin/reset-2fa-hotp error handling code should be shared with /account/reset-2fa-hotp

**Comment by redshiftzero** [comment]
Nice catch, I can reproduce this: 

![screen shot 2018-03-08 at 12 12 03 pm](https://user-images.githubusercontent.com/7832803/37173956-fb929a9c-22c9-11e8-9aea-7a40770332c3.png)

**Comment by redshiftzero** [comment]
Fixed by #3128 and #3127
