### ISSUE TITLE
Display localized interface according to browser preference

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#3126]
# Feature request

## Description

For each localized web page, send translations to all languages at all times and let CSS selector figure out the proper language to display according to the browser preference. Because the Tor browser does not send the Accept-Language there is no other way to automatically display the preferred language.

## User Stories

As a user I would like the source / journalist interface to display in the same language as the tor browser.

**Comment by dachary** [comment]
@jobava here it is!

**Comment by eloquence** [comment]
There are major feasibility concerns here, and likely diminutive value given the configuration requirement. We're comfortable with sources choosing from a list of languages (news orgs can also set the default language). Closing.
