### ISSUE TITLE
docs: Provide specific hardware recommendations for Tails workstations

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3130]
# Bug

## Description

Per discussion with @conorsch, the current documentation regarding the admin and journalist workstations in https://docs.securedrop.org/en/stable/hardware.html#specific-hardware-recommendations is rather vague. Tails has known issues with several Mac models, for example (["Tails is not working on every Mac model"](https://tails.boum.org/install/mac/index.en.html), [known issues with Macs](https://tails.boum.org/support/known_issues/index.en.html#index2h2)), and we should at minimum point this out. Ideally we should give pointers to hardware that is known to work well.

## User Stories

As a SecureDrop administrator, I would like to know which hardware to allocate or procure for the admin and journalist workstations in my organization, so I can reliably run Tails.

**Comment by eloquence** [comment]
Okay, after researching recommendations we've given directly, as well as the known issues, I intend to include language to the following effect:

- T420 (which we already recommend for the SVS) is a good choice for workstation hardware; other Lenovo T4* series models should work as well as long as they have sufficient RAM and there are not known Linux issues (cf. ThinkWiki) or Tails-specific issues (check Tails "known issues" page).
- Macs are a risky choice for workstation hardware - many issues reported on newer models; "known issues" page is helpful but not necessarily complete.

@b-meson Appreciate any input from your end since you've dealt with a lot of the front-line Tails support.

**Comment by b-meson** [comment]
@eloquence  I absolutely agree about the Lenovo Thinkpads. I know the hardware support for them is usually excellent and I know we (at FPF) have a lot of admins using them as Administrator Workstations. I personally use a T440 with 8Gb of RAM and it is rock solid. The additional benefit is that they are often well-stocked and you can often find them in stores, through hardware vendors etc. 

We should recommend against Macs for the reasons stated above.
