### ISSUE TITLE
Demo site content incorrect

### ISSUE THREAD

**Issue by hariharanj4v4** [freedomofpress/securedrop#3139]
# Bug

## Description

The code, "jhco go7v cer3 ej4l", given at "https://securedrop.org/demo", referred to as a two-factor code for the journalist interface is incorrect and misleading to the viewers.

## Expected Behavior
Based on what is given at "http://demo.securedrop.club/", it must have been referred to as the base32 version of the QR code.

## Comments

I would suggest to maintain a single correct demo page, either "http://demo.securedrop.club/" or "https://securedrop.org/demo", which could get linked from the main site, "https://securedrop.org/".

**Comment by conorsch** [comment]
https://securedrop.org/ now redirects to https://securedrop.org/demo, so the problem should be resolved. Thanks for reporting, and let us know if you have any further trouble, @hariharanj4v4 !

**Comment by hariharanj4v4** [comment]
Thanks for resolving. There is one more bug with the demo site. It is a typo and I have created a new issue on that. Kindly consider resolving it ASAP.

**Comment by redshiftzero** [comment]
This was resolved, closing
