### ISSUE TITLE
Typo in the demo site

### ISSUE THREAD

**Issue by hariharanj4v4** [freedomofpress/securedrop#3146]
# Bug

## Description

Under the "GPG encryption" title of the "http://demo.securedrop.club/" site, there is a typo with the word, "encrypted". It should have been, "decrypted", since "...encrypted with a GPG private key...", is a semantically wrong sentence.

## Expected Behavior

Finally, all submissions are decrypted with a GPG private key, which you can download here.

## Actual Behavior

Finally, all submissions are encrypted with a GPG private key, which you can download here.

## Comments

This bug has already been reported to @dachary and the patch has already been merged into master (https://lab.securedrop.club/main/securedrop-club/merge_requests/92). But, I am afraid that the change hasn't been reflecting in the site. IMHO, I might not want to see any technical person viewing this typo in a security organization like SecureDrop. So, I suggest to fix this issue ASAP.

**Comment by dachary** [comment]
Thanks for the reminder, this will be visible next time the production site is updated.
