### ISSUE TITLE
Directory includes .onion addresses that appear to be down

### ISSUE THREAD

**Issue by kaganjd** [freedomofpress/securedrop#3155]
# Bug

## Description
Clicking through https://securedrop.org/directory, the following connections hang/time out or say "unable to connect." They all have live landing pages that mention SecureDrop though. Not sure if this is because they are upgrading to the latest SecureDrop version, but wanted to file just in case.

Bloomberg- m4hynbhhctdk27jr.onion
Buzzfeed- ftugftwajmgsmoau.onion
CPJ- 2x2hb5ykeu4qlxqe.onion
Greenpeace New Zealand- ll6edwtpfl3zdwoi.onion
The Guardian- 33y6fjyhs3phzfjj.onion
NY Times- nyttips4bmquxfzw.onion
Radio24syv- hpjw636qnt5avq62.onion
San Francisco Chronicle- nrwvazcz6figxpg5.onion
USA Today- usatodayw7vu5egc.onion/
Vox.com- 2xat73hlwcpwo2zy.onion
Wired's Kevin Poulsen- poulsensqiv6ocq4.onion

**Comment by dachary** [comment]
* Bloomberg- m4hynbhhctdk27jr.onion **OK**
* Buzzfeed- ftugftwajmgsmoau.onion **OK** 
* CPJ- 2x2hb5ykeu4qlxqe.onion **NOT OK**
* Greenpeace New Zealand- ll6edwtpfl3zdwoi.onion **NOT OK**
* The Guardian- 33y6fjyhs3phzfjj.onion **NOT OK**
* NY Times- nyttips4bmquxfzw.onion **OK** 
* Radio24syv- hpjw636qnt5avq62.onion **NOT OK**
* San Francisco Chronicle- nrwvazcz6figxpg5.onion **OK**
* USA Today- usatodayw7vu5egc.onion/ **OK**
* Vox.com- 2xat73hlwcpwo2zy.onion **OK**
* Wired's Kevin Poulsen- poulsensqiv6ocq4.onion **OK**

**Comment by hoyla** [comment]
The Guardian - 33y6fjyhs3phzfjj.onion - is now OK

**Comment by redshiftzero** [comment]
these issues are now resolved
