### ISSUE TITLE
UX: Distinction between read and unread content is too subtle

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3159]
# Feature Request

## Description

The distinction between read and unread content in the journalist interface is too subtle right now. We've had at least one report of an organization missing this feature entirely. See the screenshot below:

![unreadux](https://user-images.githubusercontent.com/213636/37425635-415c0dae-2781-11e8-8d0a-b592ffb5bd80.png)

We should discuss a few different UX approaches here, but will likely want to take a hint from other messaging systems such as common email UIs, which tend to use bold text as an additional visual indication of read/unread status. 

If we cannot target a fix for the next release, we should add some documentation as a stopgap measure.

## User Stories

As a journalist, I want to be able to quickly understand which collections or messages have been read/unread.

**Comment by harrislapiroff** [comment]
As part of this ticket should I also address the Sources list view? I could imagine a clearer distinction between "All documents from this source have been read" and "There are some unread documents from this source"

![screen shot 2018-05-08 at 10 47 52 am](https://user-images.githubusercontent.com/296631/39764324-669ded74-52ad-11e8-93ed-87a4b6bd7ee8.png)

**Comment by redshiftzero** [comment]
I think the sources page is much clearer state than the submissions view since we have that big "X unread" square - but I feel like it would be even clearer if we also had the same styling as you added in #3378 to the submissions view (I mostly think this because of some great UX work done by a contributor in #1540).

**Comment by harrislapiroff** [comment]
Oh wow I hadn't seen #1540 somehow. That's neat.
