### ISSUE TITLE
Switch to using git-lfs for image files

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3176]
# Feature request

## Description

Our git repository is rather large because of a lot of early binaries that were shoved into source control. We've stopped doing that but we continue to shove image file formats (`*.png` for example) into our docs which frequently get refreshed. 

To prevent size creep, lets start using [git-lfs](https://git-lfs.github.com/) for all image files. This change will require all users who are contributing doc edits and/or building docs to have `git-lfs` installed first. If one is just making code changes they do not need `git-lfs` installed ... 

## User Stories

As a securedrop developer, I want to try to decrease the growing size of the securedrop repo and follow best practices by not putting non-text files in source control directly.

**Comment by redshiftzero** [comment]
I'm in favor of this, using LFS is not that much of an additional burden given that we already ask documentation writers to use both git and sphinx

**Comment by eloquence** [comment]
This was done (for screenshots etc.) as part of the docs repo migration (#5435).
