### ISSUE TITLE
Carry out a content review of SecureDrop user "source contact" pages

### ISSUE THREAD

**Issue by ei8fdb** [freedomofpress/securedrop#3177]
## Description

Propose to carry out a content review of the page that SD user organisations have for sources with options to be contacted. For example, [this is what I see as a good example of a source contact page](https://www.icij.org/leak/).

This will look at the words on the page, and the communications channels the source has available to them (e.g. Signal, SecureDrop, encrypted email).

The purpose of this is to investigate if there are any good practices/commonalities/ being used by these orgs.

These may contribute to guidelines to organisations who use SD.

## Comments

This review will be a short report identfying the elements on the contact page, good practices, bad practices, etc.

## User Stories

As a source, I want to know the channels to the media/news organisation, so that I'm able to make an informed decision on the best way to contact the organisation.

**Comment by dachary** [comment]
For the record the documentation associated with the landing page documentation contains [content suggestions](https://docs.securedrop.org/en/latest/deployment/landing_page.html#landing-page-content-suggestions)

**Comment by ei8fdb** [comment]
@dachary Thanks for that. Thats useful. Do you have an understanding of how that content came about? What are the SD users reactions to it? Thanks!

**Comment by dachary** [comment]
Two person asked me what the content page should look like, late 2017. I suspect I was not the only one :-) @olivemartini added the suggestions in [December 2017](https://github.com/freedomofpress/securedrop/pull/2752). Maybe she can explain what her motivation was?

**Comment by ninavizz** [comment]
This also remains high on my own radar, as a necessary thing to tackle. Much of my motivation for wanting to do a study on Source Needs, that would involve interviews with newsroom folks that setup SD instances, journalists who interact with Sources, and user testing with general population folks who match Source user profiles.

**Comment by huertanix** [comment]
@ninavizz These are some of the additions @olivemartini added to the SD docs last year: https://docs.securedrop.org/en/stable/deployment/landing_page.html.

**Comment by huertanix** [comment]
@ninavizz I'm not sure a template option has been discussed yet per se, just going by the git issue convos around the landing page documentation additions. I like the idea of a static, pre-baked template newsrooms can use in their SD landing pages. Tor does something similar in including a "this is a Tor relay" explainer page with the Tor source code. Many newsrooms have visual design departments with guidelines on web style, so we probably wouldn't be able to get too fancy on formatting/layout but that's probably fine.

**Comment by huertanix** [comment]
@ninavizz Quick update on the history behind the landing page documentation: A landing page template didn't come up when docs were written. A news org asked if there was copy they could use for their landing page so we wrote some and shared it via the docs so other orgs can use it to.

**Comment by eloquence** [comment]
Closing in favor of https://github.com/freedomofpress/securedrop-ux/issues/79 (for follow-up research; includes a snapshot overview of existing landing pages as of mid-2019) and #1608 (for implementation).
