### ISSUE TITLE
Test and review current signal CLI branch

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3188]
# Task

As part of the larger Signal alert epic, #3182, this is a task to test and review the state of the current signal CLI branch (https://github.com/freedomofpress/securedrop/tree/experimental-signal-cli-0.6) and to make any obviously needed changes beyond the larger dependencies identified in the epic. @redshiftzero please close this task once you feel that sufficient verification work has been done for the course of this sprint.

**Comment by redshiftzero** [comment]
This sprint @emkll and I went back and forth on the Signal CLI prototype and @emkll's branch is working very nicely :tada:. From the admin perspective, the flow is _much_ more friendly than the existing PGP encrypted email alerts. I'm closing this testing ticket for the sprint and we can tackle the individual issues in #3182 (beginning with migrating to Xenial) in future sprints.
