### ISSUE TITLE
[RFE] Update Ansible playbooks to create/update static configuration file

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3194]
# Feature request

## Description

After #3193 is fixed, we need to update Ansible playbooks to create (for new install) or update the static configuration file as required.

This is part of #1966

**Comment by conorsch** [comment]
Overall we're interested in reducing our dependency on Ansible to manage these types of changes: see #2641 & #2743, for example. The goal of #1966 is a great one, but it shouldn't require heavy use of Ansible as this issue describes. Closing.
