### ISSUE TITLE
[xenial] Add staging VMs for Ubuntu 16.04

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3206]
Part of https://github.com/freedomofpress/securedrop/issues/3204 (Xenial epic):

In order for developers to be able to test the installation of SecureDrop on Ubuntu 16.04 (Xenial), we should add optional staging VMs specifically for that purpose. These should not interfere in any way with the development or production environment.

Most likely candidate is bento/ubuntu-16.04.

**Comment by conorsch** [comment]
Building on the work presented in #3728—which simply _creates_ a Xenial staging scenario, but does not install SecureDrop successfully—have a branch that supports a full install, with some failing config tests. Right now the remaining config tests to isolate and tweak config logic for are:

* AppArmor related (looks like we have _more_ active profiles under Xenial by default, so the hardcoded checks about numbers of confined processes fail)
* Firewall/networking (as noted in https://github.com/freedomofpress/securedrop/issues/3207#issuecomment-393979857, we must explicitly authorized the `_apt` user to call out on 80/443)
* OSSEC (the no-messages-containing "ERROR: Incorrectly formated message from" check is failing; that's bad, and could take a while to debug).

WIP located in branch https://github.com/freedomofpress/securedrop/tree/3206-xenial-staging-target-clean-install
