### ISSUE TITLE
[xenial] Perform timeboxed install attempt of SecureDrop against Ubuntu 16.04

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3207]
As part of the https://github.com/freedomofpress/securedrop/issues/3204 (xenial epic), once we have Xenial staging VMs (#3206), we should be able to attempt an install of SecureDrop against 16.04 VMs. This task is to perform a strictly timeboxed install attempt and to record some first observations.

**Comment by eloquence** [comment]
For the purpose of the 5/30-6/13 sprint, we've agreed to decouple this from the other tasks in #3204; that is, the objective is to perform a from-scratch install with Xenial similar to what @dachary describes above, without this being necessarily easily repeatable. 

We want to gather information that will inform the [architecture meeting on June 14](https://forum.securedrop.club/t/architecture-rfc-securedrop-server-operating-system-transition/721) about the operating system transition. What level of effort is likely to be involved in fixing Xenial-specific issues and upgrading existing SecureDrop installs? Based on the answer to that question, we can decide if a transition to an altogether different base OS (e.g., Atomic, Ubuntu Core) could be a reasonable alternative.

**Comment by msheiny** [comment]
# Install attempt notes

## Ansible logic

* Problem with reboot task it just bombs out in a really strange way.. havent dug deep on it yet

## Apt

* `Date` field is now required in apt repositories and if not found will throw
  warnings.
  - https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1649086
  - https://wiki.debian.org/DebianRepository/Format?action=show&redirect=RepositoryFormat


## apache2

* `apache2-mpm-worker` no longer in xenial. Depedency of securedrop-app pkg. https://askubuntu.com/questions/808556/apache2-mpm-worker-missing-in-ubuntu-16-04

* Can not enable both `mpm_worker` and `mpm_event` modules at same time

* `apache2` needs to be explicitly installed


## Apparmor

* explicit rules needed for mpm_worker

**Comment by msheiny** [comment]
See also this branch for a few tweaks that I needed to make to get the playbooks to complete on Xenial. Note that I stripped out the test dependencies completely and did not attempt to try running the application tests.

**Comment by conorsch** [comment]
> ntp errors

Try updating the firewall rules to permit `_apt` instead of `root` on the apt calls. That will at least allow `sudo apt-get update` to resolve DNS, which was how I tested it in #3491.

**Comment by msheiny** [comment]
im timeboxing the passing of the tests but its mostly firefox/selenium related and some integration stuff. im sure im doing something dumb. attached are the failing 31 tests.


[test-failures.txt](https://github.com/freedomofpress/securedrop/files/2095558/test-failures.txt)

**Comment by eloquence** [comment]
Since this was a timeboxed research task, if there are no objections, I suggest adding any final notes and closing this task before the beginning of the next sprint.

**Comment by msheiny** [comment]
The install worked. There were some failing tests, some dependency changes but overall not too bad.
