### ISSUE TITLE
Mark specific messages/docs as "read" or "unread"

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#321]
It would be really helpful to be able to mark each document as "read" or "unread" (or maybe "downloaded" and "not downloaded").

Imagine this situation.

On Monday morning a source submits 5 documents on a message, and later that day the journalist logs in and downloads all of the files (which until #320 is finished are just randomly uuids).

On Tuesday morning the source submits 3 more documents. On Tuesday afternoon the journalist can't easily tell that there's new info for them from that source. They'd have to notice that the source maybe higher up on the list of sources, or look at the last updated date.

When the journalist clicks on the source to see the documents, they see a bunch of documents, but can't easily tell which ones they downloaded before and which ones are new. They could count the number of documents they downloaded before, but this might be difficult if they were all decrypted/extracted in the same directory before. They have to resort to comparing the arcade uuid filenames that they downloaded before with what's listed in SecureDrop to learn which docs are new and which were old.

It would be much nicer if after a journalist downloads a doc it automatically marks those docs as "read". And there should be a "download all unread" link as well, so that all the journalist needs to do is see the sources who have new docs and click one link for each. There could even be a global "download all unread" link that just downloads a single zip file full of folders named after sources, so they only need to download one thing to get all the latest changes. After downloading this in bulk it should mark them all as "read".

And, obviously, journalists need the ability to mark "read" docs as "unread" again.

**Comment by garrettr** [comment]
@micahflee We added "unread/read" flags to submissions for 0.3, although not all of the features you described in the issue description were implemented. Do you consider this issue to be resolved?

**Comment by micahflee** [comment]
Yup! It's so much better now.
