### ISSUE TITLE
The threat model link in SecureDrop's security policy on Bugcrowd returns a 404.

### ISSUE THREAD

**Issue by EdOverflow** [freedomofpress/securedrop#3212]
The threat model link on https://bugcrowd.com/freedomofpress points to https://docs.securedrop.org/en/latest/development/threat_model.html which returns a 404.

![image](https://user-images.githubusercontent.com/18099289/38173796-0d8c9d8a-35c4-11e8-84dc-5bb5fc2012ef.png)

The link should point to https://docs.securedrop.org/en/release-0.6/threat_model/threat_model.html.

**Comment by redshiftzero** [comment]
I've fixed this broken link in our Bugcrowd program description - thanks for pointing it out @EdOverflow!
