### ISSUE TITLE
Journalist codenames with spaces at the end are still valid

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#3216]
# Bug

## Description

A journalist name with a space at the end cannot login

## Steps to Reproduce

* create a journalist user with a space at the end of the journalist name

## Expected Behavior

* I am able to login as a journalist even when my name ends with a space

## Actual Behavior

* I cannot login if my journalist user name ends with a space

**Comment by redshiftzero** [comment]
I was not able to reproduce this behavior as described - let me know if I misunderstood: 

1. Using the Admin Interface, I create a user with a space at the end
2. I _am_ able to login as that user without issue

I wrote a unit test in #3218 to verify this and include the case in our test suite

**Comment by dachary** [comment]
Double checking. Most likely I'm doing something stupid.

**Comment by dachary** [comment]
I'm not able to repeat the problem. It appears I shot myself in the foot a few times and thought it was real... sorry for the noise!
