### ISSUE TITLE
Make flashed message / form error messages a little more predictable

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3220]
# Feature request

## Description

Right now we display messages all over the UI, but primarily as header/banners that are flashed. For example, this code for validating custom logos flashes form errors at the top of the page.

```python
        if form.validate_on_submit():
            # snip
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(error, "logo-error")
            return render_template("config.html", form=form)
```

i think the preferred guidelines should be this:

1. Success / informational messages are always flashed at the top of the page
2. Error messages are flashed at the top of the page
  1. Unless they are a form error
3. For errors are displayed inline next to the associated field they error on
4. When a form errors, a generic error message is displayed at the top like "Your form had an error."

## User Stories

As a user, I don't want to see a flashed message like "This field is required" without knowing what field it is attached to.

As a user, I don't want to submit a form and not have it be obvious that an error happened unless I scroll back down to the place where the error occurred.

**Comment by heartsucker** [comment]
@ei8fdb, I'd like your input here since I'm (again) not really qualified to be making these decisions.

**Comment by zenmonkeykstop** [comment]
This is being addressed for the Source Interface as part of the redesign work documented in #6211.

A separate epic is required for corresponding work on the Journalist Interface, as CSS is no longer shared between the SI and JI.
