### ISSUE TITLE
Deprecate development env from Ansible and Vagrantfile

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3227]
# Feature request

## Description

Now that we use a Docker container for the devleopment environment, we should strip out the dev-only logic from the Ansible playbooks and Vagrantfile.

## User Stories

As a dev, I want to simplify the provisioning logic by stripping out vestigial components.

**Comment by dachary** [comment]
Thanks for the reminder. IMHO we should wait a long time (January 1st, 2019 sounds like a long time) so we're reasonably sure this won't impact a developer lagging behind for some reason.

**Comment by heartsucker** [comment]
I actually think we've already gotten out of sync, and I think that Virtualbox + Vagrant is more overhead than Docker. Also, our docs already say this in regards to Vagrant:

> You do not need this step if you only plan to work on the web application or the documentation.

This, combined with #3208 mean we might not have any Vagrant anywhere. I think @msheiny or @conorsch can really say for sure, but I think we could pull this today and not impact any regular contributor's development workflow.

**Comment by ageis** [comment]
ya'll, I strongly urge you to continue to provide a staging/prod VM facility, mainly because it is crucial for testing the LSMs (AppArmor/grsec) and kernel boot/config/sysctl parameters

**Comment by redshiftzero** [comment]
We have a Docker development environment for web application changes and we continue to have staging/prod VMs for testing other changes.

**Comment by conorsch** [comment]
> This, combined with #3208 mean we might not have any Vagrant anywhere. I think @msheiny or @conorsch can really say for sure

Unfortunately not. =/ Molecule just wraps the vagrant calls for VM provisioning. As @ageis points out, there are aspects of the SD config that cannot be tested properly in containers, so we'll need to maintain a larger set of environments for adequate QA until that changes.
