### ISSUE TITLE
securedrop-admin update sporadically fails on gpg recv-key

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3243]
# Bug

## Description

This an [old issue](https://github.com/freedomofpress/securedrop/issues/1797) that has reared its head again in the latest release inside our automated scripts.

## Steps to Reproduce

* Log into Tails
* Hop into the securedrop directory under persistence and checkout a random branch
* Run `./securedrop-admin update`

## Expected Behavior

The branch (at the time of this writing) should be changed to the tag for `0.6` release.

## Actual Behavior

Depending on when you run this, it might bomb out during the `gpg recv-key` portion. Might get an error that looks like this:
![image](https://user-images.githubusercontent.com/1727935/38442332-840da5f0-39d7-11e8-9229-768d8f032a14.png)

## Comments

Lets implement the manual documented fixes that we recommended in #1842 in an automated fashion within the `securedrop-admin` script. Check out this [comment](https://github.com/freedomofpress/securedrop/pull/1842#issuecomment-309579980) specifically.

**Comment by kushaldas** [comment]
Yup, this is what I am getting while testing #3246
