### ISSUE TITLE
Update Documentation for Support Workflow

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop#3245]
# Feature request

## Description

Currently in our documentation we ask people to sign up to our support portal in various places (example: https://securedrop-support.readthedocs.io/en/latest/). However, we should point people to the SecureDrop.club community resource for support unless Freedom of the Press Foundation has a contract with them for support.

## User Stories

As a new SecureDrop administrator, I would like to know where to get support from.

**Comment by pierwill** [comment]
I have a PR open over at the support repo that revises the support docs homepage: https://github.com/freedomofpress/redmine_docs/pull/15.

It looks like the instructions there are somewhat agnostic about whether or not a user contacting FPF needs to have a support contract. Perhaps this is for the best---FPF can always redirect people to the community forums. And [this section](https://securedrop-support.readthedocs.io/en/latest/#first-time-contacting-us) seems designed to head off some of that confusion...

@b-meson or others (especially those doing support from FPF): Any thoughts on how this can all be made more clear, if necessary?

**Comment by edenemmanuel** [comment]
Thanks @pierwill for that PR at freedomofpress/redmine_docs#15. I think it'll probably be appropriate to update the SecureDrop docs themselves as well. That way, we can emphasize community support options (and hopefully grow the SecureDrop forum in the process 😁).

I'd suggest making adding a _new_ page in the [SecureDrop documentation](https://docs.securedrop.org/en/latest/), perhaps under _Topic Guides_ talking about support options. It wouldn't hurt if we updated README.md as well, to give the [SecureDrop Forum](https://forum.securedrop.club/) more visibility. :)

**Comment by redshiftzero** [comment]
We have [this page](https://docs.securedrop.org/en/latest/getting_support.html#getting-support) which should suffice here, closing!
