### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3251]
As a best practice for open source projects, we should add a code of conduct to this repository. @edenemmanuel, myself and others have been working on a draft CoC (based on [Django's](https://www.djangoproject.com/conduct/)) that could apply to all FPF-organized social/technical spaces, including this repository. Emmanuel will add it as a PR referencing this issue, and we can discuss it in that format.

Per [GitHub guidelines](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/), the file should be named `CODE_OF_CONDUCT.md` and placed in the root.

# User Stories
As a SecureDrop contributor, I don't want to face harassment, hostility, racism, sexism, or other toxic behaviors, so I can keep contributing to the project without giving up my sanity, safety, or happiness. 

As a SecureDrop contributor, I want to understand how to deal with users who harass others or otherwise behave in troubling ways, so that I have a clear path to solving the problem.

As a SecureDrop contributor, I want to understand the behavioral expectations the project has towards me and other contributors, so I can make an informed choice about whether or not I am able and willing to meet those expectations.

As the Freedom of the Press Foundation, we want to develop clarity about our involvement in behavioral issues in FPF-organized social/technical spaces, so that we can be responsible and accountable for helping to keep these spaces welcoming, safe and productive.

**Comment by heartsucker** [comment]
Cross linking to the forum discussion about this: https://forum.securedrop.club/t/code-of-conduct/596/4

Adding a shout out to two CoC's I like: [Rust](https://www.rust-lang.org/en-US/conduct.html) and [Tor](https://gitweb.torproject.org/community/policies.git/tree/code_of_conduct.txt).
