### ISSUE TITLE
ARIA support for source/journalist interfaces

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3268]
# Feature request

## Description

We should include [ARIA](https://www.w3.org/WAI/intro/aria) tags in our interfaces to make the application more usable by differently-abled sources and journalists. I have not added ARIA support to a web application before, so I can't provide a detailed breakdown of what needs to be done.

I'm not sure how this will work with all the qt tools we're working on, so we may have to investigate any standards for that.

## User Research Evidence

None. But by not including this, we are potentially excluding an entire class of user.

## User Stories

As visually impaired user, I want to be able to use my screen reader with SecureDrop.

As user who may not be able to use a keyboard/mouse, I want to be able to use speech based commands to interact with SecureDrop.

**Comment by ninavizz** [comment]
Oh, FFS... commenting, to get this on my own radar to raise with TOR peeps. Really, REALLY love the idea of getting the Journalist web experience ARIA compatible.

**Comment by ninavizz** [comment]
Ploppin' this here... relevant to making things more accessible: http://intopia.digital/articles/whats-new-in-wcag-2-1/

Just curious (with no urgency), what would the magnitude of effort be to just get ARIA tags in the Source interface?

**Comment by eloquence** [comment]
@toast In case you're still following this issue, have you noticed any improvements in screenreader/Tor Browser interaction on Mac?

**Comment by cfm** [comment]
This is foundationally complete as of #6041 and #6165, which have refactored the Source and Journalist Interfaces, respectively, to use HTML5 semantic markup and (where necessary) explicit ARIA annotations.  #5972 lists some further accessibility improvements to follow on this foundation, and new tickets tagged [`a11y`](https://github.com/freedomofpress/securedrop/labels/a11y) are welcome!
