### ISSUE TITLE
[functional testing] Cut new branch for `tbb` work (functional testing against ext server) and rebase

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3285]
During sprint planning on 4/18, we agreed that while we're unlikely to be able to finish the functional testing work described in #2875 and #1569 in this sprint, it should be achievable to at least clean up and rebase the work that's sitting in the `tbb` branch. @kushaldas and @redshiftzero, please re-scope this issue as you see fit.

**Comment by redshiftzero** [comment]
done in `tbb-0.9.0`, I also went ahead and merged the `tbselenium` directory with the existing functional test directory so that it's clearer what has changed, let's use this as a base branch for further work

**Comment by redshiftzero** [comment]
Ah and I gitignored the instance config JSON file but figured that would not be controversial so I committed it to the branch directly
