### ISSUE TITLE
UI Refresh

### ISSUE THREAD

**Issue by toast** [freedomofpress/securedrop#329]
Some design ideas that could be included in the app have been prototyped in code and are available here:

https://github.com/toast/secure-drop-prototype

These need to be integrated into the codebase where appropriate.

**Comment by garrettr** [comment]
This was merged in #382 and has been tweaked and modified subsequently (significant UI cleanup was done in #793, #794, #795, #840, #869, and others). This is present in 0.3 and so can be considered resolved. Thanks to @toast et al for working on the awesome redesign!
