### ISSUE TITLE
securedrop-admin sdconfig does not set https-related config variables

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3299]
# Bug

## Description

`securedrop-admin sdconfig` does not set `securedrop_app_https_certificate_key_src`, `securedrop_app_https_certificate_cert_src`, or `securedrop_app_https_certificate_chain_src` as explained in https://docs.securedrop.org/en/stable/https_source_interface.html

## Steps to Reproduce

In Tails:
1. `securedrop-admin sdconfig`
2. At the "Whether HTTPS should be enabled on Source Interface (requires EV cert)" prompt, enter "yes"

## Expected Behavior

I am shown prompts to fill out `securedrop_app_https_certificate_key_src`, `securedrop_app_https_certificate_cert_src`, `securedrop_app_https_certificate_chain_src`.

## Actual Behavior

I am _not_ shown these prompts.

## Comments

As a temporary workaround, admins _can_ fill out `site-specific` manually, though that is a bit tricky for some admins. As such, we should fix this issue in 0.7 if possible.

**Comment by darrow** [comment]
Instead of asking people for the cert names to set variables. I think should just go with the YES/NO on https enabled. And if yes, require everyone to name their files securedrop_source_onion.crt/key by default and maybe CA.crt and everyone just needs to use those names

**Comment by redshiftzero** [comment]
Good call @darrow - let's do that - it's easier for users and it's a simpler implementation.

**Comment by conorsch** [comment]
Given @darrow's suggestion, this strikes me as a docs-issue now. Happy to prepare something quick that should suffice.

**Comment by redshiftzero** [comment]
Well, I think it's docs + Ansible (or docs + sdconfig) no? Since we also need the three variables above to get set in `site-specific` (or elsewhere)?

**Comment by conorsch** [comment]
Roger that, I'll take a look and confirm both are covered. If we update the docs to require specific names, then we don't need to write the values via `sdconfig` config. Will shoot for that and fall back to prompting with defaults.

**Comment by conorsch** [comment]
We already have two candidates for sane defaults, which will be hardcoded going forward. In the docs, we have this:

```
securedrop_app_https_certificate_cert_src: sd.crt
securedrop_app_https_certificate_key_src: sd.key
securedrop_app_https_certificate_chain_src: ca.crt
```

In the Ansible config, we have more verbose names, which @darrow quotes above:

```
securedrop_app_https_certificate_cert_src: securedrop_source_onion.crt
securedrop_app_https_certificate_key_src: securedrop_source_onion.key
securedrop_app_https_certificate_chain_src: DigiCertCA.crt
```

Either way, an Admin *must* rename the files (via `cp` or `mv`). I assume folks would prefer the latter set of options in the interest of explicitness. There's a possibility, however, that folks with existing HTTPS setups on the Source Interface may have used the names provided in the docs. We should be able to accommodate via the `sdconfig` verification flow, failing if the files aren't found on-disk with the expect names.

**Comment by conorsch** [comment]
Spoke with @kushaldas, who's also working on sdconfig-related changes, including making the prompts conditional. I'm stepping away from this work for now. There's minimal progress in branch `3299-clearly-document-https-vars` if anyone wants to pick it up.
