### ISSUE TITLE
Docs Update Admin Workstation backup docs to remove gksu reference

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3314]
## Description

Reported in: https://forum.securedrop.club/t/gksu-missing-in-tails-3-6-2/661

## Steps to Reproduce

Follow admin workstation docs in https://forum.securedrop.club/t/gksu-missing-in-tails-3-6-2/661

## Expected Behavior

All is well and your workstation is backed up!

## Actual Behavior

`sudo: gksu: command not found`

## Comments

The suggestion in https://forum.securedrop.club/t/gksu-missing-in-tails-3-6-2/661 seems reasonable: instruct Admins to use nautilus instead

**Comment by b-meson** [comment]
I think the correct documentation is on the [Tails website](https://tails.boum.org/doc/first_steps/persistence/copy/index.en.html) and we should just link out to those.

**Comment by b-meson** [comment]
In reading the docs, we use the word "upgrade" all over the place which is *incorrect*. Example "An airgapped machine to perform the Tails upgrades. The Secure Viewing Station may be used for this task."

We are not upgrading Tails, we are backing up these one USB to another. In fact, we only use the word "upgrade" twice, so it is unclear where this language is are coming from.  I will propose we drop all mentions of the word "upgrade" in my PR.

**Comment by redshiftzero** [comment]
Since this one is an Admin-facing docs change, I will backport into 0.7.0
