### ISSUE TITLE
securedrop-admin sdconfig is allowing journalist notification email address without gpg key

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3320]
# Bug

## Description

`./securedrop-admin sdconfig` allows to put a journalist notification email address without mentioning any journalist GPG key file, or the fingerprint.

## Steps to Reproduce

`./securedrop-admin sdconfig`

## Expected Behavior

If the journalist notification GPG key is not given, then it should skip next two questions.

## Actual Behavior

It allows the admin to add a journalist notification email address.

```
Local filepath to journalist alerts GPG public key (optional): 
Full fingerprint for the journalist alerts GPG public key (optional): 
Email address for receiving journalist alerts (optional): *******@gmail.com
```

**Comment by dachary** [comment]
The sdconfig implementation unfortunately does not allow for contextual behavior. It should be improved to go beyond asking a set of questions and select which questions should be asked depending on the previous answers.

I tend to agree this is a usability bug although it could be seen as a feature request.
