### ISSUE TITLE
SSH instructions to verify connection need style tweaks

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#3348]
# Feature request
Re-style verification commands here: https://docs.securedrop.org/en/release-0.6/servers.html#set-up-ssh-keys to show that `app` and `mon` are server output and not part of the command to run.

## Description
Change this block:

> $ ssh \<username\>@\<App IP address\> hostname
> app
> $ ssh \<username\>@\<Monitor IP address\> hostname
> mon

...to make it look less like the app and mon bits are part of the command. Existing styleguide might not be sufficient to address this since it already seems to comply with it: https://docs.securedrop.org/en/release-0.6/development/documentation_guidelines.html#style-guide. Also maybe add in a bit as to what the goal of the command is. e.g. avoid admins assuming this is doing anything other checking that you can get a hostname from a remote server.

## User Research Evidence

While installing SecureDrop, I very literally made this mistake and was confused as to why `ssh <username>@<App IP address> hostname app` was failing. I had assumed the goal of the command was to create a kind of alias for the IP address with a three-letter hostname rather than simply returning the hostname from the remote machine. 

## User Stories

As a SecureDrop Admin, I would like to decrease my risk of making mistakes when setting up a system with high stakes involved.

**Comment by kstohr** [comment]
Suggest simply adding the following below the code block: 
If you have successfully connected to the app via SSH, the terminal output will be name of the app to which you have connected (‘app’ or ‘mon’) as shown above.

**Comment by edenemmanuel** [comment]
@kstohr I think simply adding instructions below the code block should suffice for now.

Thanks for reporting, @huertanix. You do raise a potential issue there. For now, let us simply add an explanation after the code block. We'll probably need to revisit how we express code blocks in our documentation and update our style guide accordingly.
