### ISSUE TITLE
Vagrantfile broken in version > 2.0.3+

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#3350]
See https://github.com/hashicorp/vagrant/issues/9442#issuecomment-373700351, `DEFAULT_SERVER_URL` is not to be modified now. HashiCorp 😩
```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.


Path: /home/kevin/dev/securedrop/Vagrantfile
Line number: 5
Message: RuntimeError: can't modify frozen String
```

**Comment by conorsch** [comment]
cf. #2970. We should consider setting the min/max vagrant version at the top of the vagrantfile to avoid problems like this.

**Comment by zenmonkeykstop** [comment]
FWIW, Vagrantfile validates fine with 2.1.2 and the line in question commented out.

**Comment by conorsch** [comment]
Definitely worth testing if modern versions of Vagrant are sufficient for use with SD now. We'd have to test on multiple platforms, with multiple providers (VirtualBox and libvirt) to be sure.

**Comment by conorsch** [comment]
Let's evaluate moving to the "latest" Vagrant version. That's most often what developers install—reasonably so—and we do a poor job of restricting the version to an older one. Let's target 2.1.2, as @zenmonkeykstop suggests. We'll need to test:

* [ ] VirtualBox behavior (note platform when testing; suggesting macOS)
  * [ ] `vagrant up /staging/` passes without error
  * [ ] `vagrant up /prod/ --no-provision` passes without error
  * [ ] Tails VM installing against prod VMs passes without error

* [ ] libvirt behavior (Linux platform required to test)
  * [ ] `vagrant up /staging/` passes without error
  * [ ] `vagrant up /prod/ --no-provision` passes without error
  * [ ] Tails VM installing against prod VMs passes without error

That should cover our bases rather well. I'll note that the move to a nested virt provider in CI (#3451) would enable us to test the scenarios above regularly, but for now let's test manually, to keep things moving.

**Comment by heartsucker** [comment]
Bumping this since I'm running in to this too now.

**Comment by zenmonkeykstop** [comment]
Thanks for the bump @heartsucker - I'll  make a branch for the tiny change required and get it tested asap.

**Comment by conorsch** [comment]
@heartsucker Out of curiosity, do you encounter the same problem when running `make staging` (which will use libvirt on Linux by default)? The Molecule configs dynamically generate Vagrantfiles, and I'd prefer to use those heavily since we have greater control over the multiple-machine setups (e.g. the upgrade scenario, see #3720).

**Comment by heartsucker** [comment]
This seems to work with `make staging`. Though it would be nice if all the requirements for that (e.g., `python-vagrant`) were virtualized. I mean, I'm a fan of virtualizing all the things where we can because it makes it a little easier as a dev.

**Comment by conorsch** [comment]
> Though it would be nice if all the requirements for that (e.g., python-vagrant) were virtualized

Can you expand on that? We'll still need a virtualenv to manage the Python dependencies since we need to call out to libvirt on the _host_ machine—so we can't bundle the required deps in a container, for example.

**Comment by zenmonkeykstop** [comment]
On Ubuntu 18.04, installed Vagrant 2.1.2, installed libvirt and mutate plugins.
Checked out develop and set Vagrant.required version to ">=2.1.2" in main Vagrantfile

With default provider set to 'virtualbox':
- [ ] VirtualBox behavior
    - [x] vagrant up /staging/ passes without error
    - [ ] vagrant up /prod/ --no-provision passes without error NOT TESTED
    - [ ] Tails VM installing against prod VMs passes without error NOT TESTED

Disabled vboxnet0 network (otherwise it would conflict with the libvirt-created one) and set default provider to 'libvirt':
- [x] libvirt behavior 
    - [x] vagrant up /staging/ passes without error
    - [x] vagrant up /prod/ --no-provision passes without error
    - [x] Tails VM installing against prod VMs passes without error

Also tested `make staging` to see if Molecule and Vagrant 2.1.2 played nice, it worked without any issues.

**Comment by heartsucker** [comment]
Something like a `make` target that creates a `venv` and installs `python-vagrant` and such. That way we're all using the same python version and same lib versions. It's not a big deal really, but I guess if we're adding things in the future that might be nice.
