### ISSUE TITLE
Lint failure on develop

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3352]
## Description

Lint failure in [this build](https://circleci.com/gh/freedomofpress/securedrop/12574):

```
.python3/.venv/bin/mypy ./securedrop ./admin
securedrop/tests/conftest.py:34: error: Argument 2 to "get" of "Mapping" has incompatible type "None"; expected "str"
```

Due to new release of `mypy` 2 hours ago ;)

**Comment by kushaldas** [comment]
It seems due to the `--strict-optional` on by default. Thank you @ilevkivskyi for pointing that out.
