### ISSUE TITLE
[0.7.0] Enable ssh over tor config is automatically populated with invalid response

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3354]
# Bug

## Description
'LAN' setting is not persisted to `site-specific` and must be re-entered at every `./securedrop-admin sdconfig` run
## Steps to Reproduce

* run `./securedrop-admin sdconfig`
* when prompted for `Enable SSH over Tor (recommended) or LAN`, set `LAN`
* inspect `install_files/ansible-base/group_vars/all/site-specific` and observe `enable_ssh_over_tor: false`
* run `./securedrop-admin sdconfig` and observe that the default response for the `Enable SSH over Tor (recommended) or LAN` is no, and requires user input to change back to `LAN`

## Expected Behavior
`./securedrop-admin sdconfig` should populate default responses based on current SecureDrop instance configuration.

## Actual Behavior
The `Enable SSH over Tor (recommended) or LAN` field is automatically populated with an invalid response.

**Comment by eloquence** [comment]
What is the expected effort on the less minimal solution of persisting the current config if no user input is provided?

**Comment by redshiftzero** [comment]
It would unfortunately involve either a hack or broader code changes that we should probably avoid so close to release unless necessary

**Comment by eloquence** [comment]
Thanks for the clarification. I agree the bug is severe enough to justify the revert/language change. Will update release announcement once that's merged.
