### ISSUE TITLE
[RFE] Integration testing of the securedrop-admin command

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3365]
# Feature request

## Description

We need integration testing of the `securedrop-admin` command. Except `install`, we should be able to test the rest safely. 

## User Stories

I am a SecureDrop developer, and I want to make sure that my changes to the securedrop-admin do not break any existing functionality of the tool.

**Comment by redshiftzero** [comment]
I think this is a duplicate of #3341

**Comment by kushaldas** [comment]
Yup, closing.
