### ISSUE TITLE
[0.7.0] Journalist notification sends email every time the app server is manually restarted

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3367]
# Bug

## Description

Every time a SecureDrop instance running 0.7.0~rc2 is rebooted, a journalist notification indicating that there's a new submission is sent, despite there not being any new submissions. Note that this particular instance was upgraded from 0.6.

## Steps to Reproduce

* Install 0.7.0~rc2 and enable journalist notifications
* Press the power button on the instance to initiate shutdown of the app server
* Press the power button again to start the app server
* Observe an email in the journalist inbox stating that `There has been submission activity in the past 24 hours.`

## Expected Behavior

The email should only be sent at a regular interval to minimize information leakage and the information sent to journalists should be accurate.

## Actual Behavior

The email is sent at every instance reboot and the information sent to the journalist is not accurate.

**Comment by redshiftzero** [comment]
Really good catch @emkll. Defect #3368 is my reproducing this issue along with another issue: alerts continuing to be grouped. Investigating...

**Comment by redshiftzero** [comment]
Ah, indeed, I've been rebooting a bunch of times, and sometimes I get the alert separately, reproducing this bug. Sometimes I get the alerts grouped, which produces #3368. The intermittent nature of this is why the resolution of alert grouping described [here](https://github.com/freedomofpress/securedrop/pull/2803#discussion_r170454765) appeared to be sufficient during review.
