### ISSUE TITLE
Provide documentation on how to rotate journalist's passphrase

### ISSUE THREAD

**Issue by edenemmanuel** [freedomofpress/securedrop#3387]
# Feature request

Provide documentation on how an admin can rotate journalist's passphrase in the SecureDrop app

## Description

It is currently possible to rotate a journalist's user passphrase in the SecureDrop web interface, but it doesn't appear to be documented anywhere.

## User Stories

As a user, I'd like to be able to get my passphrase reset, and ask my organization's internal IT for help. As an IT administrator of a SecureDrop instance, I'd like to help users reset/rotate their passphrases.

**Comment by kstohr** [comment]
Looks like this is a pretty basic quick add.
Per the [admin interface](http://localhost:8081/admin/edit/2): 

> Reset Password
> SecureDrop now uses automatically generated diceware passwords.
> 
> Your password will be changed immediately, so you will need to save it before pressing the "Reset Password" button.
> 
> The user's password will be changed to: 
> saloon handoff clutch keg pliable crinkle speckled

Suggest modifying the [Add User](https://docs.securedrop.org/en/latest/admin.html#adding-users) documentation to include 'Reset User Passphrase or Two-Factor Authentication' along the lines above.

Does this address the support-request? Is there any other guidance to provide (Make sure the journalist is present, etc.)
