### ISSUE TITLE
Support context-dependent behavior in securedrop-admin sdconfig

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3391]
## Description 

Currently, the default behavior in `securedrop-admin sdconfig` is that each question will be displayed, even if the question is not relevant for the SecureDrop instance. An enhancement would be to support asking optional questions only when necessary. For example, only an instance that answers "yes" to wanting to configure HTTPS on their source interface needs to answer the three questions added in #3366. This functionality can then replace the approach taken in #3340, which worked around this limitation to implement this behavior for the journalist notifications. 

## User Stories

As a SecureDrop administrator, I want to only answer necessary questions such that it is faster to install SecureDrop.

**Comment by antsar** [comment]
I intend to work on this issue, following a similar approach to what was taken here:

https://github.com/freedomofpress/securedrop/blob/develop/admin/securedrop_admin/__init__.py#L386
