### ISSUE TITLE
Post-install SSH instructions should appear before asked to SSH into app, not after

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#3395]
# Feature request

## Description

At this point in the docs: https://docs.securedrop.org/en/release-0.6/create_admin_account.html, admins are asked to SSH into `app` however are not told that the way to ssh into `app` is now totally different. Instructions for logging into SD servers are in the documentation, but appear a few steps later: https://docs.securedrop.org/en/release-0.6/test_the_installation.html. These instructions should be moved to before admins are asked to ssh into `app`.

## User Research Evidence

When installing SecureDrop, I attempted to ssh in via IP address and I wondered why that wasn't working.

## User Stories

As a SecureDrop admin, I'd like to know when the way a thing is done has changed to something different.

**Comment by kstohr** [comment]
Spoke with @kushaldas As in many cases SecureDrop is handling setting up the first admin acct, we'll add a cross reference here for those admin's installing on their own.

**Comment by huertanix** [comment]
@kstohr Thanks; I'm not sure what you mean by SecureDrop handling setting up the first admin account?

**Comment by eloquence** [comment]
This was resolved via #3414 a while ago.
