### ISSUE TITLE
Use python-cryptography in SecureDrop

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3399]
# Feature request

## Description

[Cryptography](https://cryptography.io/en/latest/) is most used cryptographic module. During PyCon development sprints 2018, many security folks in the Python community suggested to use it inside SecureDrop than any other module.

## User Stories

I am a `SecureDrop` developer and I want to use properly audited code for cryptography in SecureDrop.

**Comment by eloquence** [comment]
Per the investigation in #3441 we should be able to take this on during the current sprint, albeit with an older version of the library.
