### ISSUE TITLE
Better developer documentation

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#340]
I think we should link to HACKING.md directly from README.md, and improve HACKING.md to include a lot more useful information. Right now it just tells you how to get started with vagrant, but I think it should also include:

* Information about the securedrop-dev mailing list and IRC channel
* How is git repo's directory structure organized? 
* How we use git. Why do you start in the develop branch after a git clone? How are the branches organized? Do we use git-flow, and if so how?
* What is the proper way to make a pull request?

I actually don't know the answers to all of these questions, so I can't volunteer to do this.

**Comment by ThomasWaldmann** [comment]
Hmm, there is no top-level HACKING.md.
Development environment setup is explained in docs/develop.md.

**Comment by conorsch** [comment]
> Development environment setup is explained in docs/develop.md

Developer documentation is now hosted in the ReadTheDocs setup: https://docs.securedrop.org/en/latest/development/getting_started.html and addresses the original concerns of this issue. Ongoing improvements to the developer docs are tracked in #1208, which supersedes this issue, so closing.
