### ISSUE TITLE
Securedrop-admin update should verify tag signature prior to checking out the tag

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3405]
# Bug
## Description
SecureDrop admin update logic introduced in 0.6 checks out a tag before verifying that it was properly signed with the SecureDrop release signing key. Should an incorrect (non-production-ready) or malicious tag be selected, the error will appear to an administrator once. Should the admin ignore this error, the SecureDrop repository may no longer update to production-ready code.

As a SecureDrop administrator, I would like to check out and run only code that has been certified by the SecureDrop team as production ready.

## Expected Behavior
updater should only checkout code if the signature is valid. The order should be as follows:
1- fetch
2- tag -v
3- checkout

## Actual Behavior

The order is:
1- fetch
2- checkout
3- tag -v

## Comments

All upgrades to 0.7 should use the manual method of validating tags in the order described as above in the blog post, and can safely use the GUI updater in subsequent SecureDrop releases.

**Comment by redshiftzero** [comment]
While it does verify the tag is signed, it should do this _before_ checking out the branch, not after. We should update pre-release announcement for 0.7.0 to follow this procedure and follow this procedure going forward if we ask users to manually check out a signed tag
