### ISSUE TITLE
[QA] Tails GUI updater reporting new versions

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#3426]
# Bug

## Description

The 0.7.0 GUI updater reports new versions even when it's running the latest. Just ran a pre-flight check with the 0.7.0 tag, checked out inside a Tails VM. The install portion completed fine. So did `./securedrop-admin tailsconfig`. However, after finishing, it popped up the GUI declaring there were new updates. Which there definitely should not be, given that 0.7.0 is the latest release.

After a reboot of the Tails VM, the GUI updater displayed again, prompting to install updates. I accepted. Here's the detailed output: https://gist.github.com/conorsch/2e2da8fb909df067b693949474ef945c

## Steps to Reproduce

See above.

## Expected Behavior

0.7.0 is determined to be latest release; no further prompting. 

## Actual Behavior

Prompts for updates even though 0.7.0 is latest release.

**Comment by redshiftzero** [comment]
This extra `\n` is probably why this is happening:

```
> /home/amnesia/Persistent/securedrop/admin/securedrop_admin/__init__.py(608)check_for_updates()
-> if current_tag != latest_tag:
(Pdb) latest_tag
'0.7.0'
(Pdb) current_tag
'0.7.0\n'
```

In hindsight, the reason this could have happened is that the test plan in #3061 did not explicitly include a test for `./securedrop-admin check_for_updates` on the latest prod tag.
