### ISSUE TITLE
[admin CLI integration testing] securedrop-admin update 

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3460]
## Description

We should have integration tests for the `securedrop-admin update` command. This command has a lot of unit tests, but the tests do a lot of mocking out of subprocess calls, I recommend examining those first. 

Parent ticket: #3341

**Comment by kushaldas** [comment]
While working on the integration test, I can see that `gpg` is sometimes failing to reach any keyserver, and throwing some cryptic error messages. Retrying the same a few times solved the issue. 

```
INFO: Verifying signature on latest update...
gpg: directory '/tmp/.gnupg' created
gpg: keybox '/tmp/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address
gpg: keyserver receive failed: Cannot assign requested address
ERROR (run with -v for more): Command '['timeout', '45', 'gpg', '--recv-key', '--keyserver', 'hkps://hkps.pool.sks-keyservers.net', '22245C81E3BAEB4138B36061310F561200F4AD77']' returned non-zero exit status 2
```

While searching the error term, I found many other folks saw the same error message, one such [example](https://github.com/nodejs/docker-node/issues/340#issuecomment-321669029).

@redshiftzero @emkll please let me know your suggestions.

**Comment by kushaldas** [comment]
I have code ready for PR, but, the above mentioned error is showing up randomly.
