### ISSUE TITLE
Remove unnecessary query param uid from /account/reset-2fa-hotp

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3469]
# Feature request

## Description

From [this comment](https://github.com/freedomofpress/securedrop/pull/3456#discussion_r189732195):

The `/account/reset-2fa-hotp` endpoint does not need to be explicitly passed a `uid` value in the query string. We should remove uses of it in `url_for` to decruft-ify the app.

## User Stories

As a dev, I don't want dead code floating around.

**Comment by abhn** [comment]
Is this fixed already?

**Comment by heartsucker** [comment]
Hey @abhn. It looks like no one is assigned, so consider it yours.

**Comment by abhn** [comment]
My bad, I see that all instances of `/account/reset-2fa-hotp` having uid param has been fixed in this https://github.com/freedomofpress/securedrop/commit/c6047cfa097e79b99d1dc7ad8ea761f458685f70 

I was looking at `/admin/reset-2fa-hotp` and hence the confusion. I think we can close this.

**Comment by heartsucker** [comment]
Confirming that this is not present. Closing.
