### ISSUE TITLE
[functional testing] Gracefully start the server only when needed

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3483]
The functional tests will optionally be ran against an existing server. This will enable their use for pre-release QA. We could do this via e.g. a pytest option `--live-server` or similar. 

Epic: #2875

**Comment by redshiftzero** [comment]
If testing against 127.0.0.1, we start servers in the same way as the functional tests on `develop`

**Comment by redshiftzero** [comment]
I wonder if the app-test role should have a task that dumps out the instance information JSON file

**Comment by conorsch** [comment]
@redshiftzero What information specifically? Connection info such as Onion URL, HidServAuth token, that kind of thing?

> If testing against 127.0.0.1, we start servers in the same way as the functional tests on develop

I'd prefer to stop installing the test dependencies on the app server VMs, and _always_ use client-based testing, in containers or otherwise.

**Comment by redshiftzero** [comment]
> What information specifically? Connection info such as Onion URL, HidServAuth token, that kind of thing?

Currently the instance information that needs to be written out is the following:

```
{
    "hidserv_token": "",
    "journalist_location": "http://127.0.0.1:8081",
    "source_location": "http://127.0.0.1:8080",
    "sleep_time": 10,
    "user": {
        "name": "journalist",
        "password": "WEjwn8ZyczDhQSK24YKM8C9a",
        "secret": "JHCOGO7VCER3EJ4L"
    }
}
```

> I'd prefer to stop installing the test dependencies on the app server VMs, and always use client-based testing, in containers or otherwise.

well, I agree but the goal of this functional testing work right now is to drop in Tor Browser instead of Firefox only (trying to keep this scoped down so we can get this merged). Once this is done then In a future ticket we can use an external test client

**Comment by redshiftzero** [comment]
actually, the external test client won't be needed to test on prod VMs because one can use the dev VM with a custom instance information JSON file... so the path to replacing the pre-release manual web app testing is shorter than expected

**Comment by kushaldas** [comment]
My current approach is that if `instance_information.json` file is missing, the tests will start a local server and test against it. If the file exists (that is for stage or any external instance testing), it will execute the tests using the information provided in the json file.

**Comment by eloquence** [comment]
Done in feature branch via #3628.
