### ISSUE TITLE
[functional testing] Determine how to handle TB initial startup window

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3487]
When Tor Browser starts for the first time, a window pops up asking the user some questions (e.g. should Tor use a bridge, etc.). We need to programmatically click buttons on this window or suppress it in order to use Tor Browser for functional testing.

Epic: #1569

**Comment by msheiny** [comment]
seems like those settings are stored in the user profile which from an unpacked tar is `TorBrowser/Data/Browser/profile.default`. from there I see a bunch of settings configured in `prefs.js` this one in particular (i'm sure there are others) is of note `extensions.torlauncher.prompt_at_startup` --> `false`

**Comment by eloquence** [comment]
Done in feature branch via #3628.
