### ISSUE TITLE
Migrate securedrop-admin to Python 3

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3489]
## Description

We need to migrate away from Python 2 entirely, as it EOLs in 2020. This ticket is to migrate the `securedrop-admin` CLI tool to Python 3. The good news is that Python 3 is in Tails already (indeed the SecureDrop GUI updater in Tails uses Python 3), so this is a migration that can be done relatively soon.

**Comment by kneitinger** [comment]
I've been working on this issue and have the code, install scripts, and tests ported over to python3 ([which can be viewed here](https://github.com/freedomofpress/securedrop/compare/develop...kneitinger:3489-migrate-securedrop-admin-to-py3)), with all tests passing , but am curious about if some other considerations should be included in this.
- `prompt_toolkit` recently had an API-breaking update, would it be helpful to include that update as well?
- `bootstrap.py` seems like it could be easier to maintain and modify if it were an ansible playbook, is there any specific reason the current design choice was made?

Thanks

**Comment by kushaldas** [comment]
@kneitinger How much work do you think it will be to move to the newer `prompt_toolkit`?

**Comment by kneitinger** [comment]
I do not think it would be too much work at all to transition over to the new interface, but if I recall correctly my question was more feeling out if you folks have any internal processes about package versions used.

**Comment by conorsch** [comment]
After the tooling has been migrated to Py3, we'll have to handle the transition of the virtualenv on Admin Workstations from py2 -> py3, as well. Will open a separate issue to track.
