### ISSUE TITLE
Investigate root cause of SecureDrop issues with 4.4.132+ kernels

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3490]
As documented here, significant issues came to light in the initial investigation of a kernel upgrade (which we intended to ship as 0.7.1). Before we can make the call to ship a kernel upgrade with 0.8.0, we need to fully understand the root cause and have confidence in a resolution or workaround.

As @emkll noted:

`service apache2 stop` or `/etc/init.d/apache2 stop` does not properly stop the apache processes. `apache2ctl stop` however, was able to stop the processes. While QA has been successful so far with this fix, we should understand the reason of the failure.

**Comment by emkll** [comment]
Upon further investigation, any kernel `4.4.132` or above does not show the full command when using the ps command, only the process:

```
vagrant@app-staging:~$ uname -r && sudo ps -aux | grep apache2
3.14.79-grsec
root      1493  0.0  0.4  93716  4132 ?        Ss   15:20   0:00 /usr/sbin/apache2 -k start
www-data  1500  0.0  0.6 385016  6804 ?        Sl   15:20   0:00 /usr/sbin/apache2 -k start
www-data  1501  0.0  0.6 385016  6804 ?        Sl   15:20   0:00 /usr/sbin/apache2 -k start
vagrant   1796  0.0  0.0  11752   928 pts/2    S+   15:25   0:00 grep --color=auto apache2
```
vs
```
vagrant@app-staging:~$ uname -r && sudo ps -aux | grep apache2
4.4.135-grsec
root      1409  0.0  0.7  93732  7172 ?        Ss   15:32   0:00 [apache2]
www-data  1412  0.0  1.1 423752 11312 ?        Sl   15:32   0:00 [apache2]
www-data  1413  0.0  0.9 423744  9264 ?        Sl   15:32   0:00 [apache2]
www-data  1414  0.0  0.9 423760  9248 ?        Sl   15:32   0:00 [apache2]
www-data  1415  0.0  0.9 423752  9264 ?        Sl   15:32   0:00 [apache2]
www-data  1416  0.0  1.0 384992 10416 ?        Sl   15:32   0:00 [apache2]
www-data  1417  0.0  1.0 384992 10416 ?        Sl   15:32   0:00 [apache2]
```

Also investigating why there are 4 extra apache processes

**Comment by emkll** [comment]
The latest grsecurity patch (grsecurity-3.1-4.4.135-201805311823.patch) now fixes the issues we've been observing, and looking through the changelog it appears to be an issue where `/proc/pid/cmdline` upstream patches were improperly applied.

**Comment by dachary** [comment]
> upstream patches were improperly applied.

I'm interested about how that happened. Out of curiosity :-) Was it a conflict resolution gone bad? By upstream I assume you mean the grsec patch. Or was it another patch?

**Comment by emkll** [comment]
By upstream I meant Linux. What happened, as I understand it, is that an upstream backport (a commit fixing this exact bug in the Linux source) was improperly applied, thus negating the fix once the original kernel source is patched with grsecurity.

**Comment by emkll** [comment]
Based on testing in the past 2 days and per the comment above, these issues appear to have been resolved. I have opened PR #3494 to further discuss these new kernel packages, and track testing across hardware and instance configurations.
