### ISSUE TITLE
Test `test_ensure_no_updates_avail` is flaky

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3503]
# Bug

## Description

The test `test_ensure_no_updates_avail` is flaky.

## Steps to Reproduce

I have seen this error on CI (but I'm not positive this is a CI-specific bug), for example [here](https://circleci.com/gh/freedomofpress/securedrop/14318?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

## Expected Behavior

The test passes.

## Actual Behavior

```
    _________ test_ensure_no_updates_avail[docker://trusty-sd-sec-update] __________
    [gw25] linux2 -- Python 2.7.13 /usr/bin/python
    
    host = <testinfra.host.Host object at 0x7ff71c0e6fd0>
    
        def test_ensure_no_updates_avail(host):
            """
                Test to make sure that there are no security-updates in the
                base builder container.
            """
        
            # Filter out all the security repos to their own file
            # without this change all the package updates appeared as if they were
            # coming from normal ubuntu update channel (since they get posted to both)
            host.run('egrep "^deb.*security" /etc/apt/sources.list > /tmp/sec.list')
        
            dist_upgrade_simulate = host.run('apt-get -s dist-upgrade '
                                             '-oDir::Etc::Sourcelist=/tmp/sec.list '
                                             '|grep "^Inst" |grep -i security')
        
            # If the grep was successful that means security package updates found
            # otherwise we get a non-zero exit code so no updates needed.
    >       assert dist_upgrade_simulate.rc != 0
    E       AssertionError: assert 0 != 0
    E        +  where 0 = CommandResult(command='apt-get -s dist-upgrade -oDir::Etc::Sourcelist=/tmp/sec...0.7] (1:1.9.1-1ubuntu0.8 Ubuntu:14.04/trusty-security [amd64])\n', stderr=None).rc
    
    tests/test_security_updates.py:21: AssertionError
    ============== 1 failed, 175 passed, 1 xpassed in 101.77 seconds ===============
```
## Comments

No suggestion at the moment. At the very least we could make this assertion have verbose output, such as the stdout of `apt-get -s dist-upgrade -oDir::Etc::Sourcelist=/tmp/sec.list`.

**Comment by redshiftzero** [comment]
This isn't a flake per se and is an intentional CI failure so that we notice the build container needs security updates, e.g. #3516. It _does mean_ that we need to rebase people's PRs when this happens

**Comment by redshiftzero** [comment]
Hey @msheiny comment here or file a followup ticket if you disagree on how we should do this going forward

**Comment by heartsucker** [comment]
Hmm... Maybe that test could have it's error message changed if it's intentional. I think @dachary hit this one recently and (not to assume too much) didn't see the connection immediately either.

**Comment by dachary** [comment]
> I think @dachary hit this one recently and (not to assume too much) didn't see the connection immediately either.

This is a good point. I made the connection but based on my memory of past discussions on the matter rather than the message itself. :+1:

**Comment by msheiny** [comment]
sure ill make a follow up ticket @redshiftzero ! i vote to remove from CI. I blame @emkll for making me add that test.

**Comment by redshiftzero** [comment]
Closing in favor of #3527
