### ISSUE TITLE
Update tor stable package to 0.3.3.7

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3518]
# Feature request

## Description

The onion is best when freshest so lets update our tor packages to 0.3.3.7 for the next release 0.8.0 ;)

## User Research Evidence

Users LOVE TOR!!

## User Stories

As a tor package, I want to be installed.

**Comment by msheiny** [comment]
Change logs here https://gitweb.torproject.org/tor.git/tree/ChangeLog?h=tor-0.3.3.7

**Comment by eloquence** [comment]
Test package has been uploaded; we can close the issue once it's live.

**Comment by msheiny** [comment]
LiVE
