### ISSUE TITLE
Install fails in prod VMs or physical installs on develop branch

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3521]
# Bug

## Description

Curiously, this does not apply to staging VMs, or when using the 0.7.0 release tag.

## Steps to Reproduce

- Provision prod VMs
- Checkout develop
- Configure/install SecureDrop

## Expected Behavior

Install should complete successfully.

## Actual Behavior

Install fails at the Application GPG key import phase:

```
TASK [app : Import the SecureDrop Application GPG public key to the Application Server keyring.] ***************
 [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running su

fatal: [app]: FAILED! => {"changed": false, "cmd": ["su", "-s", "/bin/bash", "-c", "gpg --homedir /var/lib/securedrop/keys --import /var/lib/securedrop/sd.key", "www-data"], "delta": "0:00:00.019037", "end": "2018-06-13 16:15:56.868172", "msg": "non-zero return code", "rc": 2, "start": "2018-06-13 16:15:56.849135", "stderr": "gpg: keyblock resource `/var/lib/securedrop/keys/secring.gpg': file open error\ngpg: keyblock resource `/var/lib/securedrop/keys/pubring.gpg': file open error\ngpg: no writable keyring found: eof\ngpg: error reading `/var/lib/securedrop/sd.key': general error\ngpg: import from `/var/lib/securedrop/sd.key' failed: general error\ngpg: Total number processed: 0", "stderr_lines": ["gpg: keyblock resource `/var/lib/securedrop/keys/secring.gpg': file open error", "gpg: keyblock resource `/var/lib/securedrop/keys/pubring.gpg': file open error", "gpg: no writable keyring found: eof", "gpg: error reading `/var/lib/securedrop/sd.key': general error", "gpg: import from `/var/lib/securedrop/sd.key' failed: general error", "gpg: Total number processed: 0"], "stdout": "", "stdout_lines": []}
```

## Comments

This might have something to do with recent updates to gpg.

**Comment by redshiftzero** [comment]
Note the Ansible tasks setting up these directories was removed [here](https://github.com/freedomofpress/securedrop/pull/3211/files#diff-409c3820db6cf398ef0c3f8c1537401b) and moved into postinst

**Comment by emkll** [comment]
Thanks @redshiftzero, this might explain the issue! I will try updating the debs on apt-test.

**Comment by emkll** [comment]
Using newly-built packages fixed the problem. The packages on apt-test pre-dated the alembic merge, and because logic was removed from the Ansible logic and moved to the , nothing was in place to set up the directories, as noted above.
