### ISSUE TITLE
[0.8.0] Custom Logo does not persist with upgrade

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3528]
## Description

The optional custom logo that is on source and journalist interfaces is not preserved when the instance is upgraded from0.7.0 to 0.8.0. It is replaced with the default SecureDrop logo.

## Steps to Reproduce

1. Install SecureDrop 0.7.0 in prod vms
2. Upload a custom Instance Logo 
3. Upgrade to SecureDrop 0.8.0~rc1
4. Navigate to the Source interface and observe the default logo.

## Expected Behavior
Upgrading to 0.8.0 should preserve the custom instance logo.

## Actual Behavior

The custom logo is replaced by the default SecureDrop logo.
## Comments
There are no apparmor/grsecurity errors, it seems like app code packaging/upgrade logic.
The custom logo is no longer found in `/var/www/securedrop/static/i/`
## Workaround
Admin can run the install playbook to re-upload the image.

**Comment by heartsucker** [comment]
Related: #2807, #3057, #3219

**Comment by emkll** [comment]
This is due to an error on my part when building the debs: I had a local version of `securedrop/static/i/custom_logo.png` in the repo, which overrides the server version. Debs have been updated and I have confirmed the issue no longer persists.
