### ISSUE TITLE
admin CLI: return 1 should eventually exit with a non-zero return code

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3533]
# Description

On develop and in the 0.8.0 release branch a `return 1` does not cause the securedrop-admin CLI to eventually exit with a non-zero return code. 

# Steps to reproduce

1. It's a little difficult to trigger a `return 1` but one method is to just modify the happy path of `securedrop-admin update` to `return 1` and commit this change in a test branch
2. `securedrop-admin update`
3. `echo $?`

# Expected Behavior

non-zero exit code :)

# Actual Behavior

zero exit code :(

# Comments

This is important to fix during release QA as in 0.7.0 we released the SecureDrop workstation updater, which behind the scenes is calling out to the `securedrop-admin` CLI to do updates, and the logic relies on sensible return codes being returned by the CLI. On the 0.7.0 tag a `return 1` does make `securedrop-admin` eventually exit non-zero.

**Comment by redshiftzero** [comment]
Also now that we have integration tests, we should have a regression test that covers this case for the future

**Comment by kushaldas** [comment]
@redshiftzero this should fix this.

```
diff --git a/admin/securedrop_admin/__init__.py b/admin/securedrop_admin/__init__.py
index 597114bd..017b0a3a 100755
--- a/admin/securedrop_admin/__init__.py
+++ b/admin/securedrop_admin/__init__.py
@@ -807,9 +807,10 @@ def main(argv):
         except Exception as e:
             raise SystemExit(
                 'ERROR (run with -v for more): {msg}'.format(msg=e))
-        else:
-            sys.exit(EXIT_SUCCESS)
-
+    if return_code == 0:
+        sys.exit(EXIT_SUCCESS)
+    else:
+        sys.exit(EXIT_SUBPROCESS_ERROR)
 
 if __name__ == "__main__":
     main(sys.argv[1:])

```

**Comment by kushaldas** [comment]
To test, add `return 1` to the update function in the first line. And then run `./securedrop-admin update` and that should have 1 as exit code.

**Comment by redshiftzero** [comment]
Ah okay so this works, the only issue is that since `securedrop-admin sdconfig` doesn't actually provide a return code (just checked and the return code is `None`), it'll exit non-zero with the logic here (cool news: this was caught by the new integration tests). Adding a commit to fix that
