### ISSUE TITLE
"Admin only" warning may get flashed twice

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3605]
## Description

Reporting this here while documenting TODOs (#724).

From `securedrop/journalist_app/decorators.py`:

```python
def admin_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if logged_in() and g.user.is_admin:
            return func(*args, **kwargs)
        # TODO: sometimes this gets flashed 2x (Chrome only?)
        flash(gettext("Only administrators can access this page."),
              "notification")
        return redirect(url_for('main.index'))
    return wrapper
```

## Steps to Reproduce

Unsure.

## Expected Behavior

Flashed messages appear once.

## Actual Behavior

Flashed messages may appear twice.

**Comment by redshiftzero** [comment]
Looks like this is from the early era of SecureDrop where Tor Browser wasn't enforced, so this one is good to close.
