### ISSUE TITLE
[functional testing] Extract tor details from staging to instance_information.json

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3621]
The current tbb branches add a set of tools for using config data in json format in order to run tests. Lets extract this data from staging and dump into a compatible json file.

Epic: #3659

**Comment by msheiny** [comment]
Ummmmm @kushaldas i dont want to pull a PR yet ... but you are happy to cherry-pick from my branch at `GenFuncTestConfig`. 

I realize the recent git restrictions are also annoying. I'd be happy to target PRs against branches on your remote if it'll help the back and forth here.

**Comment by conorsch** [comment]
In yesterday's standup, @kushaldas mentioned that @msheiny had prepared changes to satisfy this ticket, but those changes are not included in any open PRs (e.g. #3628). Moving this to backlog until we sort out where that work is, or otherwise reimplement it.

**Comment by eloquence** [comment]
Resolved via #3705.
