### ISSUE TITLE
Update tor stable package to 0.3.3.9

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3625]
## Description

I like tor... we have tor.. let's update and test tor 0.3.3.8 now that its stable. [Release notes here](https://gitweb.torproject.org/tor.git/tree/ChangeLog?id=99f9816efa08ab83f90a307ea41844d693488fde)

## User Research Evidence

Users have been clamoring for more Tor!! See this user's feedback:

> Oh Tor.. I guess its okay
> -- Some random person
## User Stories

As a tor package, I love updates

**Comment by emkll** [comment]
tor 0.3.3.9 has been uploaded to apt-test. Everything seems to be working fine in tests so far.

**Comment by redshiftzero** [comment]
Packages QAed as part of 0.9.0 release, new Tor packages are live
