### ISSUE TITLE
docs: Journalist 2FA reset clarifications

### ISSUE THREAD

**Issue by pierwill** [freedomofpress/securedrop#3626]
Looking at the journalist 2FA reset docs [here](https://docs.securedrop.org/en/release-0.8/journalist.html#reset-passphrase-or-two-factor-authentication-token) after reading [this forum post](https://forum.securedrop.club/t/reset-two-factor-authentications-scary/914), I think we can be more specific about the cases:

- Case 1: journalist wants to change passphrase
- Case 2: journalist wants to change 2FA token (When would one want to change the token? Would changing the 2FA *device* be its own case?)
- Case 3: journalist has forgotten passphrase
- Case 2: journalist has lost 2FA device

Which cases require special intervention by an admin, and which do not?

With these use cases in mind, what other clarifications would improve these docs?

I can update the docs once we have a handle on this.

**Comment by b-meson** [comment]
@pierwill I also have an open PR here that you may want to look at https://github.com/freedomofpress/securedrop/pull/3388. I haven't had a minute to revisit it. 

Will, your four cases look correct. 

There are two ways to rotate a passphrase, in the admin user interface and in the CLI. I (believe) you can _only_ reset the 2FA using the admin interface in the webapp but I haven't attempted to do so.

**Comment by pierwill** [comment]
Thanks b-meson. I'll take a look—

**Comment by eloquence** [comment]
@pierwill The changes in https://github.com/freedomofpress/securedrop/pull/5301 where finally merged a few weeks ago; if you see room for additional improvement, please don't hesitate to file a `securedrop-docs` issue. Thanks!
