### ISSUE TITLE
Document libvirt vagrant-mutate use

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#3630]
## Description

We support libvirt for running full VMs on Linux, but the docs are incomplete. @dachary wrote a great guide here: https://blog.dachary.org/2017/08/15/howto-vagrant-libvirt-provider-on-debian-gnulinux-stretch9/ but new contributors will have difficulty finding that at first.

During SD Engineering meeting today, @kushaldas highlighted for particular attention in the libvirt setup process the need to use `vagrant-mutate`, since the Bento boxes we use in Vagrant do not ship libvirt images. An alternative approach, suggested by @msheiny, is that we host the libvirt images, to make first-time setup easier for contributors.

## User Research Evidence

Observing new contributors trying to get up and running with SecureDrop VMs often requires a follow-up linking to @dachary's blog post above. Any developer should reasonably expect to find the necessary steps to create a dev/testing env locally in the project documentation itself. 

## User Stories

As a developer, I want to trust the project documentation to describe the sufficient and necessary steps for development setup. 

As a maintainer, I want to encourage folks to read through the docs. I _don't_ want to mention tips in conversation about the state of the docs to clarify issues new contributors are likely to encounter.

**Comment by kushaldas** [comment]
>An alternative approach, suggested by @msheiny, is that we host the libvirt images, to make first-time setup easier for contributors.

I would love this.

**Comment by zenmonkeykstop** [comment]
1st-timer here: converting the box to libvirt locally isn't a big deal IMO - is there any other advantage to hosting the preconverted boxes?

**Comment by conorsch** [comment]
> converting the box to libvirt locally isn't a big deal IMO - is there any other advantage to hosting the preconverted boxes?

The major advantage is indeed reducing developer friction, particularly for new contributors, and I agree that's a trade-off that might not be worth the maintenance burden. Would prefer documentation of the workflow in the near-term, so that devs can get started without needing to ping existing contributors and maintainers on the undocumented steps (well, @dachary documented them well :wink:). 

@zenmonkeykstop Could you prepare a PR porting the necessary material to the dev docs? Some credit to @dachary in the commit message would not be unwelcome. :slightly_smiling_face:

**Comment by zenmonkeykstop** [comment]
Will do
