### ISSUE TITLE
The "Development Guide" link in SecureDrop's security policy on Bugcrowd returns a 404.

### ISSUE THREAD

**Issue by EdOverflow** [freedomofpress/securedrop#3631]
The _Development Guide_ link on https://bugcrowd.com/freedomofpress points to https://docs.securedrop.org/en/latest/development/getting_started.html which returns a 404.

![image](https://user-images.githubusercontent.com/18099289/42650829-c96ace5c-860d-11e8-9a1e-003025ccce71.png)

The link should point to https://docs.securedrop.org/en/latest/development/setup_development.html.

**Comment by conorsch** [comment]
Great catch, @EdOverflow, thanks for bringing to our attention! Will fix and report back.

**Comment by conorsch** [comment]
Fixed: https://bugcrowd.com/freedomofpress

**Comment by conorsch** [comment]
Also added a redirect to catch any other instances in the wild.

**Comment by heartsucker** [comment]
Marking this as closed since the link works now :)
