### ISSUE TITLE
[functional testing] Remove TBB install logic from app-test role

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3678]
## Description

A task in the app-test role is referencing an undefined variable `tbb_dir`

## Steps to Reproduce

1. check out `tbb-0.9.0` or a branch based on it
2. `make build-debs`
3. `vagrant up /staging/`

## Expected Behavior

staging VMs are provisioned without issue

## Actual Behavior

```
TASK [app-test : disable mprotect on firefox and the firefox plugin container] ***
fatal: [app-staging]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'tbb_dir' is undefined\n\nThe error appears to have been in '/Users/redshiftzero/Documents/Github/securedrop/install_files/ansible-base/roles/app-test/tasks/disable_mprotect_ff_plugin_container.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: disable mprotect on firefox and the firefox plugin container\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'tbb_dir' is undefined"}
```

## Comments

Note that bugs like this aren't getting caught due to the fact that the CI jobs that the staging CI job is reliant on are failing

Epic: #3659

**Comment by conorsch** [comment]
Yes, I've seen this one locally, as well. 

> Note that bugs like this aren't getting caught due to the fact that the CI jobs that the staging CI job is reliant on are failing

Tracked in #3661.

**Comment by kushaldas** [comment]
As we are planing to use a separate container to test the staging instance, can we just remove this tbb related ansible file all together?

**Comment by conorsch** [comment]
@kushaldas I agree: there's no reason for the TBB logic to be in Ansible at all anymore. Let's snip that out.
