### ISSUE TITLE
API call for post_reply returns different kinds of values for 400

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3684]
## Description

The [post_reply](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/journalist_app/api.py#L208) call has 3 different ways to return `Error 400`, but the first two are returning `string`, but, the last return is returning a `JSON` object.

```
return jsonify(
    {'message': 'You must encrypt replies client side'}), 400
```

This makes the API call inconsistent, please return `JSON` object in all 3 `Error 400` cases

## Steps to Reproduce

Please specify your environment if that is necessary to reproduce the bug (if in
doubt, include it).

## Expected Behavior

All `Error 400` paths inside of a single API call should return same kind of output.

## Actual Behavior

Two of them are returning strings, and only one is returning `JSON` data.

**Comment by redshiftzero** [comment]
Hm, these should be getting caught by the custom error handler we have (to generate a JSON response), and these should be under test too. Can you provide full STR for the unexpected cases you are seeing?

**Comment by kushaldas** [comment]
It seems this is only my confusion. The API returns proper error `JSON` data. Closing the tickets.
