### ISSUE TITLE
[functional testing] functional tests fail at setup when run locally

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#3696]
## Description
Functional tests break when run locally due to incorrect test user credentials.

## Steps to Reproduce

From the `tbb-0.9.0` branch:
```
make build-debs
cd securedrop
./bin/dev-shell ./bin/run-test tests/functional
```
## Expected Behavior
All tests pass.

## Actual Behavior
Tests fail during setup.

## Comments
The setup() function in `securedrop/tests/functional/functional_test.py` probably needs to be updated to set the password according to the new model introduced by the recent passlib change.

**Comment by kushaldas** [comment]
@zenmonkeykstop Please test https://github.com/freedomofpress/securedrop/pull/3692 PR. That should also take care of this.

**Comment by redshiftzero** [comment]
This is no longer an issue when running tests locally, so closing
