### ISSUE TITLE
Textboxes for admin and journalist passphrase fields should be even longer

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#3711]
## Description

In SecureDrop trainings, admins and journalists are asked to create diceware passphrases, which can vary in length depending on which words entropy delivers and how many words they use. Currently, the passphrase field for the admin and journalist interfaces are long, but not quite long enough for most users' passphrases. See discussion in #2288 for the rationale behind wanting passphrase textbox fields to be as long 

## User Research Evidence

This design recommendation is informed by direct observation of SecureDrop users.

**Comment by kushaldas** [comment]
This is a valid request. I would also love to reduce the size of the OTP box to a smaller one than the huge
password and username box. 

@freedomofpress/securedrop-ux Please tell what do you think about this?

**Comment by SaptakS** [comment]
I think we can safely assume that usernames will be shorter compared to passphrases. So how about we have username and OTP(65% - 35%) in one row and passphrase(100%) in next row? The only trouble I have in this idea is generally I feel in UX, OTP is the last field that someone fills in. But UI wise might make sense.

**Comment by huertanix** [comment]
I would advise against shuffling the order of form fields into an unfamiliar layout, and keeping the three rows in place with the username and 2FA code fields 1/3rd the width of the password field. This is the layout and sizing I recommend:

![sd journalist workstation login](https://user-images.githubusercontent.com/72914/44932179-5e7cb000-ad32-11e8-9a89-7b6a791bd92e.png)

**Comment by abhn** [comment]
Yes, all fields that huge was a bit awkward, especially the 2fa. Are we good on this, or should we wait? If we're good, I can revise my PR according to the layout @huertanix posted.
