### ISSUE TITLE
Indicate cause of login failures for admin and journalist logins

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#3712]
## Description

Currently after a login failure, there's no indication available to say whether this was due to a bad passphrase or 2FA-related failure so the journalist will guess what the cause is, leading to more login failures. When an admin or journalist tries to log in and fails, the error should instead indicate whether the login failure was due to a bad passphrase or due to a 2FA-related issue, or both.

## User Research Evidence

This design recommendation is informed by direct observation of SecureDrop users trying to log in.

**Comment by ninavizz** [comment]
I sought to do this in the Workstation wireframes, and was told we could not do this because it created a vulnerability. @emkll ?? (if we can't do this, can we close the issue?)

**Comment by huertanix** [comment]
@emkll Also curious about this particular security concern.

**Comment by eloquence** [comment]
@huertanix Our consistent approach for both SecureDrop Client and SecureDrop Core has been to not indicate the precise reason for a login failure, to ensure that any malicious user cannot use this to test passphrases or 2FA codes. We're unlikely to want to revise that, so closing this issue for now, but we may want to tweak the error messaging to be more helpful (it's a bit better in the SecureDrop Client, I think).
