### ISSUE TITLE
Add a "show passphrase" option for admin and journalist login pages.

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#3713]
## Description

During trainings, journalists may accidentally misstype or misspell their passphrase when trying to log in, but don't currently have a means of verifying what they typed so they can make a correction. Much like the Tails persistence passphrase field in the Tails greeter, the SecureDrop journalist interface login page should include a checkbox to show the passphrase if they want to see it.

## User Research Evidence

This design recommendation is informed by direct observation of SecureDrop users trying to log in.

## User Stories

As a journalist or admin, I would like to know if I miss-typed my very long passphrase and correct it without having to re-type the whole thing.

**Comment by abhn** [comment]
Has anyone taken up this and/or #3711, #3712? If not, shall I work on this?

**Comment by abhn** [comment]
Thank you @kushaldas, and thanks for clarifying about separate PRs, haha.

**Comment by abhn** [comment]
I needed some pointers on how to display the show password button. Currently, I've implemented it as a simple checkbox (https://imgur.com/tjvu2nYl.png). Is this intuitive enough?

Another option is to use an SVG as the checkbox's label, and hide the checkbox itself. In that case, we'll need an SVG (I can hunt something relevant from the free license ones).

Any help appreciated.

**Comment by huertanix** [comment]
Hi @abhn,

Design-wise, let's change this to having it below the field; The field will be longer pending the change in #3711. Let's also add a form label to it so people know what the checkbox is for like this:

[Password]
[ ] Show password

On the checkbox itself, let's stick to native form elements where possible. SVGs have a hard time working in the recommended security settings in Tor Browser and in general it's good to use native elements for accessibility reasons.

**Comment by abhn** [comment]
Understood, thanks @huertanix

**Comment by abhn** [comment]
@huertanix I believe the PR is ready for review. Thanks

**Comment by ninavizz** [comment]
Adding this to the Journalist Workstation's Alpha, per convo w/ @eloquence earlier today. Will attach screenshots of the pattern in Google and write a Gherkin description tomorrow, for Nicholas.
