### ISSUE TITLE
Link to advice re: VPC ID

### ISSUE THREAD

**Issue by pierwill** [freedomofpress/securedrop#3716]
Where it currently says the topic is out-of-scope, the [Testing: CI](https://github.com/freedomofpress/securedrop/blob/develop/docs/development/testing_continuous_integration.rst) doc could use an external link to somewhere offering advice in the following section:

```
Setup Environment Parameters
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[...]

You will be prompted for the values of the required environment variables. There
are some defaults set that you may want to change. You will need to determine
the value of your VPC ID to use which is outside the scope of this guide.
```

**Comment by redshiftzero** [comment]
we moved to our CI to GCE, so this is no longer an issue
