### ISSUE TITLE
[functional testing] Add VNC server to functional test runner container

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#3718]
## Description

It is very difficult currently to debug why functional tests fail using the new tor browser selenium logic. The upstream selenium team offers docker containers packed with firefox/chrome that include a VNC server for visual view of what the browser is doing. This would be insanely useful for us during development.

## User Research Evidence

Doesn't affect end-users, only developers.

## User Stories

As a developer, it would aid in my troubleshooting to be able to visually see the Tor Browser tests running while they are running.

Epic: #3659

**Comment by redshiftzero** [comment]
resolved by #3817
