### ISSUE TITLE
Sunset the screensaver

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#3722]
## Description

During SecureDrop trainings, journalists will be surprised and worried that the screen they have come back to is now blank and wonder if something broke. Although the screensaver may add some security from shoulder-surfing, Tails OS (and Qubes?) already have screensavers enabled by default, so this feature is no longer needed and should be removed.

## User Research Evidence

This design recommendation is informed by direct observation of SecureDrop users in newsroom implementations. Side note: Generally speaking, people are familiarized with screensavers through their operating system, but not through websites, making this a fairly alien concept to basically everyone.

**Comment by mdrose** [comment]
After searching the code and testing the interfaces, the screensaver seems to only be present on the Source interface, not the Journalist interface. Was this already removed without closing this issue, or is removing it from the Source interface also desired? Unless I'm missing something?

**Comment by huertanix** [comment]
@mdrose I think that the screensaver should be removed on the source interface as well. We have no visibility on how sources use SecureDrop in the wild by design, but we can safely assume a website screensaver is just as alien to them as it is to journalists.
