### ISSUE TITLE
SecureDrop backups from previous versions don't work if database migration has occurred

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3732]
## Description

Backup restore (https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/restore/files/restore.py) script does not apply database migrations, and as such breaks the application upon backup restore. Manual workaround that appears to have no side-effects is to run `sudo dpkg-reconfigure securedrop-app-code` on the app server.

## Steps to Reproduce

1. Install SecureDrop 0.8.0
2. `securedrop-admin backup`
3. Upgrade to 0.9.0 (or higher)
4. `securedrop-admin restore`
5. Observe source and journalist interface return error 500

## Expected Behavior

The application should be operational.

## Actual Behavior

The source and journalist interfaces return error 500s.

## Comments

Running `sudo dpkg-reconfigure securedrop-app-code` calls the postinst script which will apply migration. Based on my testing, this seems to work reliably.

**Comment by heartsucker** [comment]
Using `dpkg-reconfigure` is the best choice because it means we keep the upgrade/migration logic in one place.
