### ISSUE TITLE
Tooltip missing on read replies icon in single source page on journalist interface

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#3734]
## Description

Read replies are downloadable in 0.9.0 from the single source page as another document type with a checkmark icon. The other document type icons have a tooltip on mouseover that describes their type, but the checkmark icon doesn't.

## Steps to Reproduce
In a 0.9.0 install:

- As a source, submit a message and remember your code phrase
- As a journalist, reply to the message
- As a source, delete the reply
- As a journalist, view the single source page and mouse over the checkmark icon for the reply document

## Expected Behavior
A tooltip is displayed indicating what the icon means

## Actual Behavior
Unlike the other icons in the document listing, nothing is displayed.

**Comment by redshiftzero** [comment]
Just noticed while looking at this that some tooltips are not localized. Let's fix this tooltip in 0.9.0 and then add the localization in a followup PR, which we may or may not include in 0.9.0 (cc @kushaldas since that will mean string changes)

**Comment by redshiftzero** [comment]
closed by #3735 #3738 

PR #3736 is up for localization followup
