### ISSUE TITLE
qa_loader.py creates records referencing pre-existing sources and journalists

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#3739]
## Description

`/var/www/securedrop/qa_loader.py` is used during testing to create large amounts of random test data. If there are pre-existing journalists and sources in the database it may create random replies and submissions for them, confusing testing.

## Steps to Reproduce

- Install 0.8.0
- Create admin account via CLI on app server
- As source, submit message and record source codephrase
- As admin, reply to message
- Log in to app server and run

```
sudo su 
cd /var/www/securedrop
./qa_loader.py --multiplier=1
```
- Upgrade to 0.9.0~rc1
- As previous source, check for replies
 
## Expected Behavior
Source sees original reply from journalist

## Actual Behavior
Source sees reply from journalist preceded by blank replies

## Comments
Screenshot attached. This is probably a low-priority bug, but it would make testing easier if it were fixed.

![screenshot from 2018-08-24 23-40-36](https://user-images.githubusercontent.com/2782952/44612989-807aad80-a7db-11e8-97b8-57a4fd67abc2.png)

**Comment by redshiftzero** [comment]
The simple fix here is in QA to:

0. Create admin users
1. Run the qa loader
2. Submit document as source 

Submitting the document as a source after running the QA loader sidesteps this issue - let's do that from now on.

**Comment by heartsucker** [comment]
I can fix this. We just need to keep track of the sources/docs/etc that we create in lists and then use those in the following steps.

Also, it hasn't happened yet, but there's another bug where if you create a source then delete one the loader will crap out because it uses `range`s to iterate over `id`s.
