### ISSUE TITLE
SecureDrop updater does not automatically appear in Tails 3.9~rc1

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3749]
## Description

After an upgrade to tails 3.9~rc1, the SecureDrop updater GUI does not appear on screen after a reboot when an update is required.
## Steps to Reproduce

Update Tails device or vm to 3.9~rc1
git checkout `0.7.0` any other non-release branch/tag that is not 0.8.0

## Expected Behavior

The SecureDrop Updater GUI should appear on screen
## Actual Behavior

The SecureDrop Updater GUI does not appear on screen

## Comments

I've tried both clean install and update

**Comment by kushaldas** [comment]
I will try to reproduce it now.

**Comment by kushaldas** [comment]
## Environment Tails3.9~rc1

After setting up a new Tails device, make sure that you enable Additional software installation in the `Persistence volume` 

## ./securedrop-admin setup  step

While doing the `./securedrop-admin setup` step, after the installation of all of the Debian packages, Tails will ask the following question (as in the screenshot). Make sure you click on the `Install Every Time`. 

![tails_install_packages](https://user-images.githubusercontent.com/272303/44788004-792a1a00-abb6-11e8-8309-b44b18587373.png)


## Move to an older release and reboot

```
git checkout 0.7.0
sudo poweroff
```

And restart the box, after enabling the persistence volume and adding one administrative password, the AutoUpdater GUI will show up. 

@emkll Please verify the same steps and tell if you see something different.

**Comment by redshiftzero** [comment]
Does this just need a docs update? @emkll @kushaldas

**Comment by emkll** [comment]
Packages installed in the tails workstation are as follows: `python-virtualenv, python-yaml, python-pip, ccontrol, virtualenv, libffi-dev, libssl-dev, libpython2.7-dev`, and appear to be only used to setup the virtualenv. 

In Tails < 3.9, the behavior was consistent with `Install Only Once`. `Install Every Time` might speed up `./securedrop-admin setup`, but be otherwise be functionally identical, provided the workstation has internet access. I propose we update the docs and recommend `Install Only Once`, to minimize changes.

**Comment by redshiftzero** [comment]
Prior to closing, can you confirm @emkll that the initial report was due to some other issue?

**Comment by emkll** [comment]
Just tested this again twice, and both times the updater appears. Since I cannot reproduce, and based on reports in this ticket, I will close.

Note that as a result of discussion in this ticket , #3757 / #3759 were opened to clarify  `securedrop-admin setup` behavior in Tails 3.9, as Tails 3.9 introduces apt persistence and a new notification appears at the top of the screen.
