### ISSUE TITLE
Incorrect security message displayed on source interface index page in Tails 3.9~rc1

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#3788]
## Description

In Tails 3.9~rc1 (with Tor Browser 8.0a9) and with the Tor Browser security slider set to "standard," a ribbon message is displayed saying "it is recommended to install the Tor Browser..." - it should say "it is  recommended to move the security slider..." .

## Steps to Reproduce

  - Install 0.9.0~rc4 or upgrade from 0.8.0 to 0.9.0~rc4
  - In Tails 3.9rc1, visit the source interface index page with the Tor Browser security slider set to "standard"

## Expected Behavior
A ribbon message is displayed recommending that the security slider be set to "safest"

## Actual Behavior
A ribbon message is displayed recommending that Tor Browser be used to visit the site instead.

**Comment by redshiftzero** [comment]
This is in prod since Tor Browser 8 just got released. Since we're doing a release today it will be fixed on instances within 24 hours.
