### ISSUE TITLE
Document procedures for participating in pre-release QA

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3792]
## Description

We need documentation on how to participate in QA, both for:

1. Upgrade tests
2. Fresh installs

@kushaldas had created a blog post here: https://kushaldas.in/posts/setting-up-securedrop-0-5rc2-in-vms-for-qa.html with some instructions on how to go about this. 

There's also this playbook for upgrade testing: https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d

**Comment by redshiftzero** [comment]
As part of this, we should make sure to run through (and document) testing fresh installs, as there was confusion during the 0.9.0 release about Tor package QA - the following change was made:

```
3) update install_tor.yml to change deb definition in "Setup Tor apt repo" task to include [arch=amd64] qualifier
```

**Comment by zenmonkeykstop** [comment]
For a HW fresh install, I updated defaults in install_files/ansible-base on the admin workstation before running `securedrop-admin install`, as follows:

1) override defaults for apt in `roles/defaults/main.yml`, pointing to apt-test and test key
2) override defaults for tor-apt in `group_vars/all/securedrop`, pointing to apt-test and test key
3) update `roles/tor-hidden-services/tasks/install_tor.yml` to change deb definition in "Setup Tor apt repo" task to include [arch=amd64] qualifier

**Comment by eloquence** [comment]
See also the potentially confusing QA loader behavior Kevin identified in #3739; let's ensure we document usage in pre-release QA as part of this effort.

**Comment by eloquence** [comment]
We've committed to iterative improvements to the QA process for the 10/4-10/17 sprint; Jen, Kev and I will scope a bit more tomorrow. Realistically, we have a few hours tomorrow and on Tuesday 10/9 (QA/feature freeze kicks off EOD) to nail down the QA and release plan for 0.10.0.

**Comment by eloquence** [comment]
Related specifically to this ticket, for the 0.10.0 QA period, @zenmonkeykstop will take some more detailed personal notes regarding the exact steps for performing various tests. This can then feed into formally reviewed documentation for testers post-0.10.0.

We've agreed on some other iterative improvements for the test plan, which will be reflected in the release ticket (#3849) and an associated wiki page.

**Comment by redshiftzero** [comment]
[moving to 0.12.0 milestone]

**Comment by eloquence** [comment]
We won't be able to spend too many cycles on this but let's at least vet existing internal docs during QA as part of the 7/8-7/22 sprint.

**Comment by rocodes** [comment]
The existing QA docs can be found at https://github.com/freedomofpress/securedrop/wiki/QA-Procedures, feedback is welcome.

**Comment by eloquence** [comment]
^ @zenmonkeykstop has committed to take another spin through this during/after remaining QA for 1.5.0.

**Comment by eloquence** [comment]
Ro has fleshed out the docs and Kushal and Kev did a first pass review. Remaining to-dos for the 8/6-8/20 sprint:
- @zenmonkeykstop  will pull Conor's QA playbook (currently a Gist) into the repo and add docs for it
- @kushaldas will incorporate some additional detail from his blog into the wiki page.

After that we should be in a good place to resolve this issue :-)

**Comment by eloquence** [comment]
(These docs currently live in our wiki, so I'm leaving this in the SD Core repo and tagging it "wiki" for now.)

**Comment by eloquence** [comment]
Closing as the procedures live happily on the wiki and have continued to be reviewed and tweaked with subsequent releases: https://github.com/freedomofpress/securedrop/wiki/QA-Procedures
