### ISSUE TITLE
Firefox (Quantum) incorrectly detected as Tor in source interface

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3793]
## Description

By means of a small JavaScript check, the source interface shows a warning when accessing it over an insecure browser, or when using Tor with JavaScript enabled. The user agent detection for this warning was [recently updated](https://github.com/freedomofpress/securedrop/pull/3789) given the UA change in Tor Browser 8.0.0.

Unfortunately per a report from @harrislapiroff we are now incorrectly classifying Firefox Quantum as Tor, suppressing the warning. This is unlikely to impact production users as they would commonly not be able to load .onion URLs; however, we should still attempt to correct the detection, or, if this proves difficult, perhaps re-consider whether we want to limit the warning to cases that can be unambiguously detected (e.g., JavaScript use, mobile UA that can't possibly be TBB).

**Comment by harrislapiroff** [comment]
Here's a proposed non-invasive Tor Browser check:

```js
// This user agent string matches Tor Browser 8 or Firefox Quantum (on desktop)
const TBB_UA_REGEX = /Mozilla\/5\.0 \((Windows NT 6\.1|X11; Linux x86_64|Macintosh; Intel Mac OS X 10\.13|Windows NT 6\.1; Win64; x64); rv:[0-9]{2}\.0\) Gecko\/20100101 Firefox\/([0-9]{2})\.0/


const is_likely_tor = function () {
  return (
    // Has Tor/FF UA string
    window.navigator.userAgent.match(TBB_UA_REGEX) &&
    // Tor Browser always reports a GMT timezone
    new Date().getTimezoneOffset() == 0 &&
    // Tor Browser always reports device dimensions being the same
    // as window dimensions -- this is *very* unlikely to be true in any
    // other desktop browser, given window chrome and toolbars
    window.screen.width == window.innerWidth &&
    window.screen.height == window.innerHeight
  )
}
```

The only false positive I can imagine is if someone using Firefox Quantum in a GMT timezeone somehow puts it in a "kiosk mode" (which I am not sure is possible).

**Comment by redshiftzero** [comment]
In PR #3817 we hit a functional test failure when using Firefox due to this issue (we have tests in that branch for both the source warnings when using Tor Browser and Firefox, so we can detect breakage like this). We xfailed that test (`TestSourceInterfaceBannerWarnings.test_warning_appears_if_tor_browser_not_in_use`), so when this issue is resolved, we should be sure to remove the xfail.

**Comment by eloquence** [comment]
Realistically won't make it onto 0.10.0, so re-milestoned (we should still clean up this logic soon).

**Comment by legoktm** [comment]
This was fixed a while back, using vanilla Firefox correctly shows the banner to use Tor Browser, and using Tor Browser does not display that banner.
