### ISSUE TITLE
Upgrade Tor on instances to 0.3.4.9

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3813]
## Description

We should upgrade running instances to the latest (0.3.4.9) in SecureDrop 0.11.0: https://blog.torproject.org/new-release-tor-0349

**Comment by emkll** [comment]
Tor 0.3.4.8 has been uploaded to apt-test for testing.

**Comment by redshiftzero** [comment]
seeing some tor-related CI failures, needs investigation: https://circleci.com/gh/freedomofpress/securedrop/18638

**Comment by redshiftzero** [comment]
I've seen two of these pointer deference issues, let's defer this update until the next cycle

**Comment by redshiftzero** [comment]
(now latest Tor is 0.3.4.9, updated ticket)

**Comment by emkll** [comment]
Tor 0.3.4.9 has been uploaded to apt-test for testing. Will be provisioning staging VMs to see if the memory management errors observed with 0.3.4.8 have been addressed.

**Comment by eloquence** [comment]
Went out as part of 0.11.0, closing.
