### ISSUE TITLE
Build 0.9.1 VM images for upgrade testing

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#3816]
## Description

Last week we released SecureDrop 0.9.1, so we're currently developing 0.10.0~rc1, but the upgrade testing scenario still uses 0.8.0 images for upgrade testing. Let's bump those box versions using the `make vagrant-package` target.

## User Stories

As a developer, I want to ensure that changes will not break upgrades, so tooling that checks such cases should be current with planned upgrades in the wild, i.e. 0.9.1 -> 0.10.0.

**Comment by msheiny** [comment]
Thanks for making this issue :) I'm on it ! Got a stable connection
