### ISSUE TITLE
tails 3.9 persistent storage not maintaining the transfer device's keys

### ISSUE THREAD

**Issue by robzim** [freedomofpress/securedrop#3823]
Hi, when installing from 0.91 and tails 3.9 we are losing the transfer device keys in persistent storage.  we have to use tails 3.6, create the persistent storage, register the transfer device, then upgrade to tails 3.9 in order to maintain the persistent storage keys.  Thanks, Rob Zimmelman NBC News, rob.zimmelman@nbcuni.com

**Comment by eloquence** [comment]
Sorry for the very late response. Unfortunately password persistence for LUKS-encrypted devices was removed in Tails 3.9, and is unlikely to come back. See backstory in #4434 and https://gitlab.tails.boum.org/tails/tails/-/issues/16718.
