### ISSUE TITLE
Bulking downloading folder structure

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#383]
I've noticed that in practice, it's really helpful if each message/document is in it's own folder. The reason is because in Tails, you double-click a .gpg file to decrypt it, and it creates the new file in the same folder. If it's a doc, then you right-click on the .zip to extract it to get the original file that was uploaded. Sometimes (if the source is savvy and follows the journalist key instructions) this is another .gpg file with a different name, and you double-click on that to decrypt it. And sometimes, it decrypts into a .zip or .tar.gz or something that the source sent, so you extract that. Etc, etc.

Basically, each message generates at least 2 files, sometimes 3 (if they post a gpg-encrypted message in the box). And each doc generates at least 3 files (.zip.gpg, .zip, and whatever is extracted from the .zip), sometimes way more. It gets really disorganized to have all of the files just sitting there in the same folder.

(Also, sometimes a source tries to upload the same document twice because they weren't sure if it worked the first time. If the two .zip.gpg files are in the same folder, you end up extracting the zip files over each other when the contents have the same filename.)

So anyway, I propose that the bulk download feature (and any future bulk download features, such as #372) shouldn't just put all the messages/docs into a zip file, but rather should build a directory structure like this:

```
| source_codename
|--| year-month-date
|--|--| doc_number
|--|--|--| document.gpg
```

So for example, if the source codename is "Ottoman mate" and they uploaded a message and then a document on May 22, the directory structure would be:

```
ottoman-mate
ottoman-mate/2014-05-22
ottoman-mate/2014-05-22/1
ottoman-mate/2014-05-22/1/1-ottoman_mate-msg.gpg
ottoman-mate/2014-05-22/2
ottoman-mate/2014-05-22/2/2-ottoman_mate-doc.zip.gpg
```

Make sense? I don't think the directory structure needs to be exactly like this, as long as it's organized sequentially and each message/doc is in it's own folder. (And the dates are super useful, especially if there's weeks of back-and-forth between journalist and source, to look back -- but the date could just be the date of last activity.)

**Comment by ajvb** [comment]
@fowlslegs and I discussed this in person and decided this was a good way to organize the folder structure without having to make the changes to the db to save timestamps on each submission (which would be needed for the original structure) and could/would leak information as discussed in #822 

Structure:
```
| source_codename
|--| <doc_number>_<Source.last_updated>
|--|--| document.gpg
```
Example:
```
ottoman-mate
ottoman-mate/1_2014-05-22/
ottoman-mate/1_2014-05-22/1-ottoman_mate-msg.gpg
ottoman-mate/2_2014-05-22/
ottoman-mate/2_2014-05-22/2-ottoman_mate-doc.zip.gpg
```

**Comment by fowlslegs** [comment]
Status update... Have been on vacation the last couple weeks, and have a lot to catch up on. Will probably not get to this until next week.
