### ISSUE TITLE
Passphrase information inconsistent on docs

### ISSUE THREAD

**Issue by aleprovencio** [freedomofpress/securedrop#3834]
Hello,
[here](https://docs.securedrop.org/en/stable/tails_guide.html) it's stated that it should not be necessary to set a master keepassx passphrase, while [here](https://docs.securedrop.org/en/stable/passphrases.html) says the opposite.

**Comment by conorsch** [comment]
Thanks for reporting, @aleprovencio . For context, the latter doc states:

> A master passphrase for the KeePassX password manager

Twice, in two separate sections. Those should indeed be revised for clarity.

**Comment by ninavizz** [comment]
Has this been fixed yet? :/

**Comment by eloquence** [comment]
The outdated Tails guide was removed a while ago, so this inconsistency is no longer present. See #4673
