### ISSUE TITLE
Convert functional tests to use pytest/fixtures

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3836]
## Description

Using pytest fixtures creates a single source for how we initialize the objects that tests rely on. This is generally more maintainable than having each test function/class/module initialize its resources how it sees fit.

Plus, once we move to having the functional tests run against external servers (using TB or otherwise), this would be a single place we could have a switch for altering the tests.

However, this is somewhat non-trivial if we want to ever add `pytest-xdist`. Pytest fixtures can be scoped in different ways, and xdist will parallelize load in a way that guarantees all free functions in a module go to the same worker or all functions in a class go to the same worker. We want to avoid having multiple webdrivers in existence at the same time (memory constraints), and we want to avoid having to recreate too many webdrivers as well as their boot time (on my low/mid-spec laptop) is roughly 2 seconds.

If we convert to the functional tests and ignore xdist support and slow tests, this is very easy. If we want all the bells and whistles, we have to think a little harder.

### Minimum Criteria

We need to continue using the pattern of one `app` per function because this guarantees a clean start for every test.

## User Stories

As a dev, I want to make changes to tests in one place when I update app code, and not be digging around in different places.

**Comment by heartsucker** [comment]
Related: #2755

**Comment by nabla-c0d3** [comment]
This issue can now be closed. All functional tests now use fixtures 🎉. 

There a few different fixtures available (named sd_servers_xxx) for starting the journalist & source apps; they should be used depending on whether the test needs the app's data to be reset, or must be in a specific state, etc.
