### ISSUE TITLE
Password field is longer than username/OTP token on login

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3856]
(not really a bug per se but...)

## Description

The password field is significantly longer than the other fields. We should make them equal for prettiness reasons.

![screenshot_2018-10-09_14-15-14](https://user-images.githubusercontent.com/3998464/46668819-de1d5a80-cbcd-11e8-91b7-bac2a68e8818.png)

## Steps to Reproduce

Boot the dev container on develop.

**Comment by hoyla** [comment]
My tuppence: given that the field widths currently give the user a reasonable expectation of the length of content they'll be entering into those fields, I think it's arguable the current are helpful. And I reckon utility trumps prettiness. But I don't pretend to be an authority.

**Comment by huertanix** [comment]
The design decision to make passphrase fields longer was informed by user interactions in the wild. Check out #3711 for the discussion around this.

**Comment by heartsucker** [comment]
Right, but I meant the others should be equally long because it seems like that's more standard for forms (e.g., bootstrap defaults).

**Comment by redshiftzero** [comment]
Since this change to the current form field lengths was based on UX feedback as @huertanix points out, let's leave it as is?

**Comment by heartsucker** [comment]
Ok fair enough. Closing.
