### ISSUE TITLE
Add documentation covering common manual QA tasks

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#3905]
## Description

The SecureDrop release process includes a manual testing phase, with test plans written by the designated release manager for each new version. Some parts of the test plan require a high level of familiarity with the application and environment, which makes it harder to encourage community involvement in testing. 

Supplementing the test plans with documentation describing how to perform QA tests that are common across test plans would make testing easier and more accessible to the wider community.

**Comment by redshiftzero** [comment]
hey is this a dupe of #3792?

**Comment by zenmonkeykstop** [comment]
It totally is - nuking it and referencing #3792 from now on.
