### ISSUE TITLE
Support range requests (RFC 7233) on journalist interface

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3907]
## Description

The journalist interface should support range requests so user agents can continue downloads that failed part way through. We have the most control over this on the journalist workstation, so we would see the most benefit there.

### Current behavior

```http
HTTP/1.0 200 OK
Cache-Control: public, max-age=43200
Content-Disposition: attachment; filename=1-barren_unfamiliarity-msg.gpg
Content-Length: 604
Content-Type: application/pgp-encrypted
Date: Fri, 26 Oct 2018 08:44:49 GMT
Etag: "sha256:25aef0be2cb6900a88a2590b2ee3637117eb51a733a105ae692e212623450f7f"
Expires: Fri, 26 Oct 2018 20:44:49 GMT
Last-Modified: Fri, 26 Oct 2018 08:42:46 GMT
Server: Werkzeug/0.14.1 Python/2.7.6
Set-Cookie: js=eyJleHBpcmVzIjp7IiBkIjoiRnJpLCAyNiBPY3QgMjAxOCAxMDo0NDo0OSBHTVQifX0.DrRlgQ.17vemUmgcvLR2QvisGT0TOiZfyU; HttpOnly; Path=/
Vary: Cookie
```

### Proposed Behavior

```http
HTTP/1.0 200 OK
Cache-Control: public, max-age=43200
Content-Disposition: attachment; filename=1-barren_unfamiliarity-msg.gpg
Content-Length: 604
Content-Type: application/pgp-encrypted
Date: Fri, 26 Oct 2018 08:44:49 GMT
Accept-Ranges: bytes
Etag: "sha256:25aef0be2cb6900a88a2590b2ee3637117eb51a733a105ae692e212623450f7f"
Last-Modified: Fri, 26 Oct 2018 08:42:46 GMT
Server: Werkzeug/0.14.1 Python/2.7.6
Vary: Authorization
```

## User Stories

As a journalist downloading large documents on a flaky Tor connection, I want downloads to pickup where they left off.

**Comment by redshiftzero** [comment]
note that we would also need to make some non-trivial changes to the [securedrop-proxy](https://github.com/freedomofpress/securedrop-proxy) to use this - right now for file downloads we wait for the entire encrypted file to download and then `qvm-move` it into the SVS
