### ISSUE TITLE
Allow source <-> journalist communcation on a document-by-document basis

### ISSUE THREAD

**Issue by Hainish** [freedomofpress/securedrop#391]

**Comment by eloquence** [comment]
We discussed this in our old issue review meeting yesterday and I also briefly brought it to the attention of @huertanix today. The original report was under-specified and hence not actionable as is; we will continue to investigate source/journalist workflow issues, but closing this issue for now.

**Comment by Hainish** [comment]
This related to early SecureDrop conversations on allowing discussion threads linked to specific documents. Not sure if it's relevant anymore.

On February 21, 2018 6:02:46 PM PST, Erik Moeller <notifications@github.com> wrote:
>We discussed this in our old issue review meeting yesterday and I also
>briefly brought it to the attention of @huertanix today. The original
>report was under-specified and hence not actionable as is; we will
>continue to investigate source/journalist workflow issues, but closing
>this issue for now.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/freedomofpress/securedrop/issues/391#issuecomment-367542493

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
