### ISSUE TITLE
Include `filesystem_id` in API response for Source

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3910]
## Description

Right now we don't include the `filesystem_id` in the API response for a `Source` on the grounds that it would be leaking information. However, this is embedded in the key itself.

In one terminal window:

```
cd securedrop && make dev
```

In another:

```
$ http localhost:8081/api/v1/sources | jq -r .sources[0].key.public | gpg2 --homedir /tmp/gpg --import
gpg: WARNING: unsafe permissions on homedir '/tmp/gpg'
gpg: key 0EF5F5E567465EBF: public key "Autogenerated Key <RRLQAEXBQ3D4D3EHDF4TZVDCWJWG5G74X75F5I25MJLARW6P5LROB4D3RTXAEIDRYNTWI76NVT3BQIPAPSX2YAV4TTU5DH6GJHI3XJA=>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

As you can see, the `filesystem_id` is present as part of the name.

It may make sense for us to explicitly put that in the API response to help with manipulating GPG keyrings in the future.

**Comment by heartsucker** [comment]
Actually just gonna go a whole 'nother way with this. We should probably just use a source's UUID as a their name for the key.

**Comment by redshiftzero** [comment]
Closing in favor of #4695
