### ISSUE TITLE
Update i18n docs to account for Weblate / GitLab infrastructure migration

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3929]
## Description

This must be done prior to updating the strings for the 0.11.0 release:

- Point to [our GitHub translations repo](https://github.com/freedomofpress/securedrop-i18n) in: [i18n_tool.py](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/i18n_tool.py)
- Update soon-to-be-404ing link in the README here: https://github.com/freedomofpress/securedrop#acknowledgments
- Update i18n docs: https://github.com/freedomofpress/securedrop/blob/2455e4e50d83075fb9ce5a6945882410c3612d8d/docs/development/i18n.rst, which still refers to the GitLab workflow and .club URLs

**Comment by kushaldas** [comment]
Uh, missed that this was closed :( Thank you @eloquence :)
