### ISSUE TITLE
[xenial] Verify Trusty backup -> Xenial recovery story

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3960]
We should ensure that a SecureDrop backup completed on 14.04 can successfully be recovered on 16.04. Whether we ask admins to perform this step manually, or whether we automate it, it may be a required part of the Xenial migration and will certainly be highly recommended.

If clean upgrades to Xenial are not yet implemented one should complete this ticket by following these steps instead:

1. Create a backup on 14.04 server
2. Create fresh install on 16.04 and then attempt to run the restore

Part of #3204, may result in follow-up issues.

**Comment by zenmonkeykstop** [comment]
This failed for me while reviewing PR #4080 for `3961-separate-subdir-per-distro-for-deb-pkg-builds`on prod VMs

- did a clean 14.04 install
- took a backup
- did a fresh install on 16.04
- ran `./securedrop-admin restore <filename here>`
- backup completed successfully

After backup, `ssh app` fails, as /var/lib/tor/services is overwritten. Copying `var/lib/tor/services/ssh/hostname` from the tarball to `install_files/ansible-base/app-ssh-aths` and rerunning `./securedrop-admin tailsconfig` didn't restore access, and now ssh to app or mon fails immediately.

**Comment by zenmonkeykstop** [comment]
D'oh, didn't add HidServAuth, working fine with that addition.
