### ISSUE TITLE
localization: explain how to handle string changes merged between feature and string freeze

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3971]
## Description

Our current process for regular releases (which can update strings) is:
1. Two weeks before release, feature freeze is declared and a release branch is created.
2. One week before release, string freeze is declared and translations are reviewed for the final release.

The current docs have a [note for string freeze day](https://docs.securedrop.org/en/latest/development/i18n.html#one-week-before-the-release-string-freeze) to "Verify develop and the release branch have the same source strings". This is for the situation where a string change has been merged into `develop` _after_ the release branch was created. In this scenario, in most cases we don't want to include that change in the release - for example, if the string change was part of a larger code change that we should not incorporate after feature freeze. 

However, the current documentation doesn't explain what to do in this scenario. We should improve the localization manager docs by adding an explanation here (and testing it). Specifically, what we should do is update the messages to be translated on the `securedrop-i18n` repo based on the `release/0.x.y` branch instead of updating from `develop`. This can be the default step in the documentation. 

## User Stories

As a SecureDrop localization manager, I want clear documentation on how to update the strings so that I do not make a mistake.

**Comment by eloquence** [comment]
Feature and string freeze are now on the same day, closing.
