### ISSUE TITLE
On the Admin Workstation,  N SecureDrop updater processes are started if N network interfaces are enabled in Tails

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#3999]
## Description

If a Tails Admin Workstation has more than one network interface, the SecureDrop network manager hook that checks for updates will run for each active NIC. (For example, if a workstation has both Ethernet and Wifi enabled.)

This is confusing to end users and may result in multiple update processes clobbering each other's changes.

## Steps to Reproduce

On an Admin Workstation:
- revert to an earlier SecureDrop version:
```
cd ~/Persistent/securedrop
git checkout 0.10.0
```
- enable multiple network connections (eg Ethernet and Wifi) and wait for their Tor connections to come up

## Expected Behavior
A single instance of the Securedrop Updater is started.

## Actual Behavior
Multiple instances of the SecureDrop Updater are started.

**Comment by kushaldas** [comment]
https://tendo.readthedocs.io/en/latest/ can help us to solve this one with minimal code change. @redshiftzero @emkll any comments?

**Comment by redshiftzero** [comment]
Last commit is 6 months ago, only 79 stars on GitHub - how commonly used is this dependency? Note that we use [this method](https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/app.py#L113) to prevent duplicate instances of the securedrop-client, what do you think about using a similar approach here?

**Comment by kushaldas** [comment]
>Last commit is 6 months ago, only 79 stars on GitHub - how commonly used is this dependency? Note that we use this method to prevent duplicate instances of the securedrop-client, what do you think about using a similar approach here?

I was going to comment about too, we just simply use the same function here.

**Comment by eloquence** [comment]
I've added this to the 0.12.2 milestone as it's IMO a good candidate for the point release, given the inherent "n+1" delay in any graphical updater fixes.
