### ISSUE TITLE
Broken packages block updates due to cron-apt run order

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#4003]
## Description

The nightly `cron-apt` operations to install updates consist of three discrete actions, executed in the following order:

1. update apt lists for whitelisted repos
2. remove unwanted distro-maintained kernels (leaving only SD-specific hardened kernels)
3. install any new package versions available in whitelisted repos

If any packages fail to install, _all_ future updates will fail to install. 

## Steps to Reproduce

At a high level, steps to reproduce are:

1. Install a "broken" package (one that errors out at e.g. the `postinst` stage)
2. Attempt to upgrade to a newer, fixed version of same package via cron-apt
3. Observe failure to upgrade

More specifically, a practical scenario can be created with:

1. Set up `upgrade` scenario VMs based on 0.9.1. 
2. Edit `/etc/hosts` and duplicate the `mon` IP line a few times.
3. Run `cron-apt -i -s` to install debs at version 0.10.0 or newer.
4. Observe failure.
5. Build patched/fixed debs for e.g. 0.12.0~rc1 and copy to local apt server (in `upgrade` scenario)
6. Run `cron-apt -i -s` on the host with a broken package
7. Observe that the newer 0.12.0~rc1 is _not_ installed, and the system is still in a broken state.

## Expected Behavior
Updates to broken packages are applied.

## Actual Behavior
Updates are never installed if a package is in a broken state.b

## Comments

If we flip steps 2 & 3 in the cron-apt flow, i.e. install updates immediately after updating the lists, we should sidestep this problem.

**Comment by ageis** [comment]
There is the possibility to MAILON="error" in the cron-apt config so you can shoot off an e-mail if there's a bad exit status. unattended-upgrades has the option `Unattended-Upgrade::AutoFixInterruptedDpkg "true";` which reruns dpkg hooks in an attempt to fix unclean state. At a recent gig I implemented both cron-apt and unattended-upgrades together, but here I've felt for a long while that a transition to unattended-upgrades as the more elegant/configurable/supported solution may be apt.
