### ISSUE TITLE
[xenial] Investigate/fix apt sources under xenial when upgrading 

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4017]
## Description

When performing a do-release-upgrade to Xenial, apt-freedom.press are commented out from `/etc/apt/sources.list.d/` (the interactive upgrade script states at the beginning of the upgrade: `Third-party sources disabled`). However, FPF apt repo(s) remain in `/etc/apt/security.list`. Furthermore, security.list contains trusty as the channel name for all sources, including upstream (likely because cron-apt config is distinct from apt config), which suggests that unattended security updates via cron-apt might not work.

We should ensure that:
- cron-apt is correctly pulling in package upgrades (both upstream and fpf-provided) via security.list
- apt.freedom.press is in `/etc/apt/sources.list.d/` to ensure we can provide optional packages to be installed by admins if necessary

**Comment by eloquence** [comment]
Will be resolved via docs, see #4057.
