### ISSUE TITLE
Use py.test or similar

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#404]
Looks like it can help us reduce boilerplate and provide some other nice features: http://pytest.org/latest/

**Comment by ThomasWaldmann** [comment]
securedrop/manage.py test invokes py.test, so should this issue be closed?

**Comment by garrettr** [comment]
Yes, I think we can close this issue. We don't yet fully take advantage of all of the py.test features that I'd like to, but I will file more specific follow-up issues for those issues as they come up.
