### ISSUE TITLE
Debugging my install

### ISSUE THREAD

**Issue by humanitystruth** [freedomofpress/securedrop#4043]
![image1](https://user-images.githubusercontent.com/37747653/51340848-e7c42300-1a44-11e9-948f-7d8a4a971cad.jpeg)

I'm not entirely sure where to even begin on this issue, but I've been racking my brain on this install. Any ideas? 

Thanks in advance!

**Comment by redshiftzero** [comment]
Hey @humanitystruth - can you show the error message and/or the task that failed (should be in red)? 

Please do not include any sensitive information, like passwords or onion URLs in your response

**Comment by humanitystruth** [comment]
Here you go. I appreciate the help and sorry for not including this originally.

![img_5357](https://user-images.githubusercontent.com/37747653/51356651-5213ac80-1ab3-11e9-8dee-fcf39f2327bb.JPG)

**Comment by heartsucker** [comment]
The principle error here is that the `securedrop-keyring` package cannot be authenticated. I checked the key's expiration (`fpf-signing-key.pub`) and verified that it expires in October of this year.

@humanitystruth Can you let us know what version of SecureDrop you're using? If it's not 0.11.0, Can you give us the outputs of the following commands?

```
git status
git rev-parse HEAD
```

Additionally, this may be caused by an `apt update` failing because other keys on the system are out of date. Can you check what happens if you run the following from the admin workstation Tails?

```
ssh app
# (this next command happens in the ssh shell on the app server)
sudo apt-get update
```

I suspect that second command will fail.

**Comment by humanitystruth** [comment]
Okay. So here's the scoop. You we're right. I was on an old version of tails as well as securedrop. (0.7.0). I updated both tails and securedrop from 0.7.0 thru to 0.11.0 as described in the walkthrus. I also updated app server via -> sudo apt-get update.

Now I am getting a new error after updating everything:

![img_5360](https://user-images.githubusercontent.com/37747653/51408910-11e51600-1b15-11e9-88ca-39ce84529fcc.JPG)

**Comment by heartsucker** [comment]
Is this a new install or an old one? As in, have you successfully installed SecureDrop before and are you attempting to update it now? Or was this a new install using an old USB with an old checked out version of SecureDrop?

**Comment by humanitystruth** [comment]
It's a brand new install on an old USB. I had to pause my project for 9 months or so. Now I am on tals 3.11 and SecureDrop .0.11.0.

Thanks for your help on this!

**Comment by heartsucker** [comment]
Yo I'll try to get to this later, but it's Sunday night and I'm on my way to a concert.

**Comment by humanitystruth** [comment]
Fair enough sir!

**Comment by heartsucker** [comment]
Also while we're at it, what Tails version are you on?

**Comment by humanitystruth** [comment]
Okay: I apologize for the delay. I have confirmed both installed successfully and I am at the end of "Install SecureDrop Servers", where ./securedrop-admin install gets 1 fail, in regards to ETHS(just like last image) :(
Also: I am on tails 3.11.

**Comment by humanitystruth** [comment]
Not sure why this is only attaching the filepath, either..

**Comment by humanitystruth** [comment]
![img_5363](https://user-images.githubusercontent.com/37747653/51880516-7606a600-236f-11e9-96f6-a12af556c575.JPG)

**Comment by heartsucker** [comment]
Do you have TLS certs for your onion address? Because most installs don't since they required extended verification. I think this may be a misconfiguration on your end.

**Comment by humanitystruth** [comment]
I dont have a ev ssl certificate. I was hoping my ucc ssl certificate would work? 
how do I fix this? should I rerun sdconfig, tailsconfig or modify a specific file?

Thanks again for your help heartsucker

**Comment by eloquence** [comment]
Closing as stale; @humanitystruth, if you still need installation help, you may want to contact us directly via `securedrop@freedom.press`.
