### ISSUE TITLE
Flaky container timeouts when building deb packages

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#4051]
## Description

The `make build-debs` target occasionally emits errors on build, related to the `gather_facts` step run by Ansible after container creation.

## Steps to Reproduce

Run `make build-debs` five times. You'll likely get a failure at least once. If you don't, I want to know!

## Expected Behavior

`make build-debs` completes reliably without error. (Not counting the test failure notifying about unapplied apt updates). 

## Actual Behavior

`make build-debs` emits an error:

```
    PLAY [Build SecureDrop application Debian package from local repository.] ******
    
    TASK [Gathering Facts] *********************************************************
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
    fatal: [trusty-sd-app]: FAILED! => {"changed": false, "cmd": "/sbin/udevadm info --query property --name /dev/mapper/Tyr--vg-root", "msg": "Timer expired after 10 seconds", "rc": 257}                                                                                                                                                                     
    ok: [trusty-sd-config]
    ok: [trusty-sd-generic-ossec-agent]
    ok: [trusty-sd-sec-update]
    ok: [trusty-sd-generic-ossec-server]
    changed: [trusty-sd-generic-ossec-server] => (item=/tmp/build/ossec-server)
    ok: [trusty-sd-generic-ossec-server] => (item=/tmp/build)
```

## Comments
It's not reliable _which_ container fails, so it feels rather like a race condition. It may be heavy load that contributes to the timeout, but even with no other applications running, I can generate the error. Have tested both Debian Stretch and Qubes for build host, and the problem exists on both.

Seems to be related to the Ansible version upgrade (#3945), where this problem was first reported. We may be able to bump the gather_facts timeout to accommodate. Removing build parallelism (by excising the `strategy: free` param in the build playbook) reduces the frequency of the failure, but is not a perfect solution.

**Comment by heartsucker** [comment]
I can't reproduce this, and I've never seen this error before (and I do a medium amount of deb building). I successfully completed this step like 8 times just now so idk works for me :man_shrugging:

Env:

```
$ git rev-parse HEAD
b725c81ab6755b02c90c698d35f4427bf1b30788
$ docker --version
Docker version 17.05.0-ce, build 89658be
$ uname -a
Linux pythagoras 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```

And this is using a venv created from the `develop-requirements.txt` file, so those dependencies are all locked.

**Comment by kushaldas** [comment]
```
$ git rev-parse HEAD
b725c81ab6755b02c90c698d35f4427bf1b30788
$ docker --version
Docker version 17.05.0-ce, build 89658be
```

I also can not reproduce this one.  No issues with the containers.
