### ISSUE TITLE
[xenial] Add base OS info to metadata endpoint

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4059]
## Description

Part of #3204. In order to have better visibility into which SecureDrop instances are actively updating to from Ubuntu Trusty to Ubuntu Xenial (and actively engage with admins as needed), it makes sense to expose this info via the existing metadata endpoint.

To avoid breaking existing uses, this should be done in a new `server_os` variable.

From a security perspective, this does not give an attacker key information -- for now, both releases receive security updates; once 14.04 has reached EOL, it will also no longer receive SecureDrop package updates, which will be reflected in its already exposed SecureDrop version.

# User Stories

As a SecureDrop administrator, I'd like to be actively alerted by the support team when I have to perform critical security updates, so that I can act on them with appropriate priority.

As a SecureDrop support team member, I'd like to know whether an instance is following recommended upgrade procedures, so I can increase the urgency of outreach efforts if required.

**Comment by nightwarrior-xxx** [comment]
@eloquence Can I have a look at it ?

**Comment by eloquence** [comment]
@nightwarrior-xxx By all means! We're in a crunch over the next couple of weeks to get all the must-do functionality in #3204 in; if you have time over the next few days, your help would be much appreciated. :)

**Comment by heartsucker** [comment]
@nightwarrior-xxx you commented on this last night but have since deleted your comment. Are you going to work on this or should someone else?

**Comment by nightwarrior-xxx** [comment]
@heartsucker Yes,I would love to work.I thought to ask you on gitter first before taking up this issue

**Comment by heartsucker** [comment]
Yeah then it's all yours

**Comment by nightwarrior-xxx** [comment]
@zenmonkeykstop  [Just to clear confusion] I have to import platform and store linux_distribution  in a variable called ```server_os``` in the file ```securedrop/admin/securedrop_admin/init.py```

**Comment by heartsucker** [comment]
You don't have to add a variable to that file. You can just add it under the route in `source_app/api.py`.
