### ISSUE TITLE
Documentation about the API may have been incorrect leading to incorrect code

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#4064]
## Description

The initial implementation of the API expected a header of the form:

```http
Authorization: $token $value
```

This was listed in the docs as

```http
Authorization: Token $value
```

And in the code it was initially checked by this bit of code:

https://github.com/freedomofpress/securedrop/blob/b725c81ab6755b02c90c698d35f4427bf1b30788/securedrop/journalist_app/api.py#L39-L40

When we merged PR https://github.com/freedomofpress/securedrop/pull/4054, the code was updated to include an explicit check for the presence of the token `Token` in the header's value. The code is now this:

https://github.com/freedomofpress/securedrop/blob/b662cd136ee6c497dd0ebc044411bcea33e29cc8/securedrop/journalist_app/api.py#L39-L43

Because of this explicit check, we have an issue in the client where we cannot authenticated with the server because the client uses the token `token` (note the lowercase `t`) in the auth header. See https://github.com/freedomofpress/securedrop-client/issues/232

## Steps to Reproduce

- Checkout `develop` in this repo (5bbd3fa4a)
- Checkout `master` in the client repo (`0154d77`)
- Authenticate to the server
- Attempt another action that requires an API call

## Expected Behavior

The API call succeeds.

## Actual Behavior

The server returns 403 Forbidden.

## Comments

The fix is decide on either the use of the token `Token` *or* `token` in the auth header and standardize it between the server (including docs) and SDK.

**Comment by redshiftzero** [comment]
Let's resolve this over in the SDK, closing here
