### ISSUE TITLE
Remove ads on our readthedocs instance

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#4065]
## Description

This is in reference to ads on docs.securedrop.org

Ads make my heart hurt. They could also giving away additional metadata that unveils whom is visiting our documentation pages. Let's eventually try and self host RTD to work-around this issue but in the meantime I suggest we scope out payment plans to remove ads on hosted RTD.

## User Research Evidence

The ads aren't visually intrusive but I'm sure it would be universal for all our users to remove ads both aesthetically and from a metadata perspective.

## User Stories

As a securedrop documentation page, I don't want a stinkin' ad on me

## Next Steps

Technically the cheapest plan to remove ads is $5/month. This is geared towards individuals and not organizations such as FPF. I think it would be best to reach out to their sales/support staff to see if this would be acceptable. I really like RTD and I don't want to short-change them from revenue BUT i also don't want us to throw a ton of money at this problem if it's more cost effective to self-host.

**Comment by redshiftzero** [comment]
In the medium-term I advocate we pay RTD a bit to remove the ads (so that we don't need to self host more SecureDrop-related services right now)

**Comment by msheiny** [comment]
I have signed us up for the gold subscription at $5/mo
