### ISSUE TITLE
CI staging with rebase task can silently fail

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4066]
## Description

For example, in https://circleci.com/gh/freedomofpress/securedrop/21323 , the full ci run does not occur. The gce-start script does not exit successfully, and the rest of the run (namely the tests) are not run, and it is not reported as a CI failure. For example:

```
make[1]: Entering directory `/home/circleci/sd'
./devops/gce-nested/gce-runner.sh
ssh: connect to host <snip> port 22: Connection timed out

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
make[1]: *** [ci-run] Error 255
```

## Expected Behavior
CI should fail when provisioning of CI instance fails

## Actual Behavior

CI passes
## Comments

Suggestions to fix, any other relevant information.

**Comment by emkll** [comment]
Another example of a run that should fail but doesn't: https://circleci.com/gh/freedomofpress/securedrop/21471

**Comment by conorsch** [comment]
The failure is masked because the call to the failing function is wrapped in a bash if statement. To observe the behavior locally, apply this patch:

```
diff --git a/Makefile b/Makefile
index cd497579..d0ed592b 100644
--- a/Makefile
+++ b/Makefile
@@ -21,6 +21,22 @@ ci-run: ## Provisions GCE host for testing staging environment.
 ci-run-xenial: ## Provisions GCE host for testing staging environment.
        ./devops/gce-nested/gce-runner.sh xenial
 
+.PHONY: debug-ci-nested
+debug-ci-nested: ## Debug errors not propagating
+       @if [[ "${CIRCLE_BRANCH}" != docs-* ]]; then \
+               true; \
+               echo "true"; \
+               false; \
+               echo "false"; \
+       fi
+
+.PHONY: debug-ci-inline
+debug-ci-inline: ## Debug errors not propagating
+       true
+       echo "true"
+       false
+       echo "false"
+
 .PHONY: ci-go
 ci-go: ## Creates, provisions, tests, and destroys GCE host for testing staging environment.
        @if [[ "${CIRCLE_BRANCH}" != docs-* ]]; then \
```

Then run the targets in succession:

```
$ make debug-ci-nested
true
false
$ echo $?
0
$ make debug-ci-inline
true
echo "true"
true
false
Makefile:35: recipe for target 'debug-ci-inline' failed
make: *** [debug-ci-inline] Error 1
$ echo $?
2
```

Simply wrapping the call with a script containing `set -e` should resolve. We already have Circle CI re-running the destroy step explicitly to avoid long-running test instances.
