### ISSUE TITLE
Rename `Terminology` to `Glossary` in the docs

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#4083]
## Description

This is the expected term, and we should make a reference to the glossary early in each of the respective sections like

- Source Guide
- Journalist Guide
- Admin Guide
- Install SecureDrop

## User Research Evidence

While a UX team was looking at the docs, they asked "why isn't there a glossary" since they couldn't find it.

**Comment by bumbleblue** [comment]
I would want to add that a glossary/terminology section would also make terminology across website and documentation more consistent. Once you decide on the words to use, there can be a sprint to find&replace some of the confusing terms 🙂

**Comment by bumbleblue** [comment]
Example: What's a `SD workstation`? vs. a `journalist interface`? what constitutes `secure viewing`?

**Comment by ninavizz** [comment]
^ I love the idea of a documentation sprint; we're currently doing lots of mini/adhoc efforts, and currently @zenmonkeykstop and (I think?) @huertanix are co-leading the first major overhaul of the Source guide. This is a great bit for them to consider (poke, poke!—renaming "terminology" to "glossary;" goal being prioritizing clarity and resonance among a winder user group, than linguistic precision that can limit cognitive resonance).

There is an open issue in the sd-ux repo to unite nomenclature across the entire product, as informed by findings from the Workstation project. That said: it's critically important this does NOT fall off the priorities radar... and I appreciate this issue, so much, for reinforcing that urgency. Thank you, Eileen!!

P.S.: @bumbleblue if you ever feel inspired to attend a crit at 17:00UTC we'd love to have your voice and thoughts! https://github.com/freedomofpress/securedrop-ux/wiki/Meetings

**Comment by huertanix** [comment]
@ninavizz I'm down for a doc sprint!

**Comment by ninavizz** [comment]
Pokey pokey @eloquence you mentioned in standup today you'd be doing some work in RTD? 😸

**Comment by lbeaufort** [comment]
Hi there! I'd like to work on this issue.
