### ISSUE TITLE
[0.12.0] [xenial] Create test plans and QA matrix

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4105]
In preparation for SecureDrop 0.12.0 and as part of Xenial support (#3204), we will need to prepare the following documents:

- [ ] a 0.12.0 test plan for instances upgrading from 0.11.1, similar to the [0.11.0 test plan](https://github.com/freedomofpress/securedrop/wiki/0.11.0-Test-Plan)
- [ ] a standard release QA matrix, similar to the [0.11.0 release QA matrix](https://docs.google.com/spreadsheets/d/1c5DmnXVKXhkkcfjDKs0IlGsYCMnRl3TqdAC9RDBaW04/edit#gid=0)
- [ ] a test plan and QA matrix specifically for a freshly installed version of SecureDrop 0.12.0 on Ubuntu 16.04 per the revised documentation (#4103)
- [ ] a test plan and QA matrix specifically for a SecureDrop 0.12.0 installation upgraded from Ubuntu 14.04 to Ubuntu 16.04 per the upgrade docs (#4057)

We do *not* need to test installation of SecureDrop 0.12.0 on Trusty, as this option will not be supported.

Part of #3204 and the 0.12.0 release epic.

**Comment by zenmonkeykstop** [comment]
There will probably be 2 upgrade scenarios to test here:

- testing Xenial after an upgrade in place.
- testing Xenial after a backup-install-restore upgrade.

**Comment by heartsucker** [comment]
See the [wiki post](https://github.com/freedomofpress/securedrop/wiki/0.12.0-Test-plan) for the current test plan.

**Comment by heartsucker** [comment]
@eloquence I think this ticket is covered by the release ticket, wiki entry, and QA spreadsheet. I recommend we close this.

**Comment by redshiftzero** [comment]
We can close this and move on to other tasks - each scenario above is written out in row 2 of the (single) QA matrix. Users should add their QA reports as new columns in the QA matrix, along with a report on the ticket itself.
