### ISSUE TITLE
Update text in "New Identity" post-logout message to reflect updated Tor Browser UI

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4131]
## Description

**The current text reads:** 
`"Important! Thank you for exiting your session! Please select "New Identity" from the green onion button in the Tor browser to clear all history of your SecureDrop usage from this device.`

Unfortunately, the above text was composed when the UI for the Tor Browser's toolbar had a messy/ugly icon in it that was green, and some other messy icons. The UI has since been updated, and there is now a crisp, easily discoverable onion icon in the toolbar. (hooray Linda, Antonela, and Tor team!)

**Pls to update text to instead, read:**
`"Important! Thank you for exiting your session! Please select "New Identity" from the onion button in the Tor browser's toolbar to clear all history of your SecureDrop usage from this device.`

Differences: Omit the word "green," make the word "browser" possessive, and add the word "toolbar" as shown.

## Steps to Reproduce

Log into SecureDrop. Log out. See text in purple banner.

**Comment by ninavizz** [comment]
Because there IS a cute green onion now in the URL bar, this is probably especially important—since you cannot create a new identity from the current green onion.

![image](https://user-images.githubusercontent.com/8262612/52824825-172f7500-306f-11e9-87f7-c0c2f456697d.png)

/cc @eloquence could this also get squeezed into this latest release—mostly since the most urgent part is removing the word "green" (the possessive "button's" and 'toolbar' can be added/re-translated in a future release).

**Comment by eloquence** [comment]
Thanks for flagging; it's indeed a trivial string change and seems fine to roll into 0.12.0 since no QA is required. If @redshiftzero has no objections I'll prepare a quick PR for it.
