### ISSUE TITLE
Eliminate mention of Demo Instance on sd.org

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4132]
Yo @eloquence, just making official in an Issue. :)

Seen...
- On the Overview Page: https://securedrop.org/overview/
- In the Footer across the whole sd.org site

**Comment by eloquence** [comment]
Thanks for flagging @ninavizz; this is now removed. We're still hoping to eventually restore the demo instance in some form, but it may be a while.

**Comment by ninavizz** [comment]
Sweet! Yes, the UX Gal™ pipes-up in support of a demo instance coming to life again. Just... well, reality, and—yay, no dead links! :)
