### ISSUE TITLE
Remove NoScript workaround instructions from Source Interface

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4160]
In #4153, we introduced instructions to the Source Interface for working around a NoScript/Firefox issue which causes some uploads to fail. The upstream NoScript issue (closed as a Firefox issue is being pinpointed as the root cause) is https://github.com/hackademix/noscript/issues/64; the best candidate for the underlying Firefox issue appears to be: https://bugzilla.mozilla.org/show_bug.cgi?id=1506562

These instructions are cumbersome and the upstream issue will hopefully be resolved ASAP. We'll need to continue to monitor upstream and remove the instructions once a fix has landed in the latest releases of Tor Browser Bundle & Tails.

**Comment by eloquence** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1532530 for additional follow-up.

**Comment by ninavizz** [comment]
Is this Issue more of a "to do" for once the issue has been fixed on the Mozilla/NS end?

**Comment by eloquence** [comment]
Yes, exactly. Hence the "blocked" label, which I'll remove once the upstream issue is fixed and the fix can be expected to reach most Tor browser users by the time of the next SecureDrop release milestone.

**Comment by eloquence** [comment]
See tbb-dev thread [Firefox/NoScript bug with major downstream effects](https://lists.torproject.org/pipermail/tbb-dev/2019-March/thread.html#970) for discussion with Tor browser developers, as well.

**Comment by eloquence** [comment]
Upstream Tor browser issue proposing to change the default, & discussion: https://trac.torproject.org/projects/tor/ticket/29733

**Comment by eloquence** [comment]
The NoScript fix is included in Tor 8.0.8 (released March 21) so we should be able to revert the warning potentially for 0.12.2, pending QA:

https://blog.torproject.org/new-release-tor-browser-808
