### ISSUE TITLE
[docs] instruct localization manager to push to remote repo prior to locking

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4165]
## Description

To avoid running into [merge conflicts](https://docs.weblate.org/en/weblate-3.4/faq.html#how-to-fix-merge-conflicts-in-translations) on Weblate (as we did for 0.12.0) which need to be resolved via manual conflict resolution or by discarding changes, we should ensure that the localization manager guide instructs the manager to:

1. Commit
2. Push
3. and _then_ Lock translations

such that any changes to the local repository are pushed to the remote. This is the action that is suggested in the FAQ linked above to prevent [merge conflicts](https://docs.weblate.org/en/weblate-3.4/faq.html#how-to-fix-merge-conflicts-in-translations).

**Comment by kushaldas** [comment]
@jasonbraganza you may want to do this one tonight.
