### ISSUE TITLE
Tor packages not upgraded immediately during Xenial upgrade

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4206]
During QA of 0.12.0, @zenmonkeykstop observed that Tor was not updated immediately after upgrading (following the upgrade-in-place procedure) from Trusty to Xenial. Instead of the Xenial 0.3.5.x series (#4031), the Trusty 0.3.4.x series package was used until the next `cron-apt` run.

As a precaution and to ensure the upgrade logic behaves fully as we expect it to, we should ensure that the Tor package is updated immediately after an in-place upgrade.

**Comment by eloquence** [comment]
This won't make it into 0.12.1 so moving back into near-term backlog and off milestone, but it's still a candidate for a follow-up point release if warranted; keeping it open.

**Comment by redshiftzero** [comment]
All instances that are going to upgrade have done so, otherwise people can install fresh on the latest release on Xenial. Closing this since it was upgrade only
