### ISSUE TITLE
Add "« Back to submission page" link to NoScript docs

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4208]
The `why-journalist-key` page in the Source Interface has a helpful "« Back to submission page" link at the bottom, the `disable-noscript-xss` page does not. We should have the link on both pages (or make other consistent UX changes to both pages), especially given that otherwise there's only a prominent "LOG OUT" link, and users may be disinclined to click the "Back" button in connection with forms.

# User Story

As a source, I want to know how I get back to the submission screen after learning about fun technical workarounds, so that I can successfully continue my submission.

**Comment by ninavizz** [comment]
Rats, good catch!
