### ISSUE TITLE
Add automatic tests for malicious / buggy translated strings

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#4209]
## Description

Test for:
- translated HTML tags match original
- translated format strings match original

## User Research Evidence

This is an extremely tedious process during the release, and because it is so tedious, it is a source of errors.

**Comment by eloquence** [comment]
This is now done via Weblate checks, which seems to be the appropriate level at which to manage translation integrity. We can file separate issues for specific improvements to these checks. Closing this old issue.
