### ISSUE TITLE
Investigate running test_infra tests against production HW

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#4216]
## Description

Currently, QA testing involves a "basic server testing" phase that duplicates some checks already present in the test_infra tests while missing a whole bunch of others. It would be useful to be able to automate this testing phase and do it in more detail using the test_infra suite. Failing that, a script that could be run from the Admin Workstation to do basic server testing would be a useful thing.

## User Stories

As a SecureDrop Tester, I want to be able to automatically run basic server tests against production servers.

**Comment by eloquence** [comment]
Tentatively adding to 1.4.0 milestone per today's sprint retrospective; please don't hesitate to nominate other issues on the QA automation front that should be higher priority or also added.
