### ISSUE TITLE
During 14.04->16.04 upgrade, tmux is unable to re-attach

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4221]
An organization performing a Xenial upgrade reported that they were unable to re-attach to the Application Server after the `sshd` restart. They attributed this to the fact that tmux itself was upgraded before then. They were able to manually re-attach by finding the old process ID via `pgrep` and re-attaching via `/proc/$pid/exe`. 

They did not experience the same issue upgrading the Monitor Server.

We should attempt to understand the root cause and, if warranted, add an update to the documentation to help users work around this issue.

**Comment by rmol** [comment]
I've reproduced this. Happened exactly as described -- only on the app server, where attaching via the old executable under /proc worked. I've got a fix -- basically incorporating their workaround by adding to /etc/profile.d/bashrc_securedrop_additions an attempt to attach via the /proc copy of the old executable if attaching fails but a session is found -- but want to go through another test cycle or two to validate it.

**Comment by eloquence** [comment]
OK, thanks for the repro. This seems like a good candidate for the point release, so tentatively added to the milestone. That said, if we're certain this will impact prod upgrades, we should update the docs with the workaround before then.

**Comment by kushaldas** [comment]
Is this over `tor` or direct `ssh` also? Asking because I never had this trouble in direct `ssh` connections.

**Comment by rmol** [comment]
The problem did not occur with direct SSH connections to the servers.
