### ISSUE TITLE
[docs] Update language for "Source" to be more user-centric

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4241]
## Description

Whistleblowers and everyday folks looking to securely share information with an organization, are unlikely to identify themselves as a "Source." The word itself is industry nomenclature w/in journalism, and speaks more to relational semantics vs natural human mental-models of behavior. 

It's highly important for non-technical users unaccustomed to reading developer documentation to immediately see themselves user tasks described in the docs. Without an immediately identifiable path, users are more likely to disengage and to "wing it," vs taking the initiative to push themselves to learn something they likely don't even understand to follow known formats.

## User Research Evidence

UX best practices. 

@bumbleblue had previously flagged difficulties getting her head around the product (as a Source) via a host of issues, including how the experience is reflected in the docs. A first step and small piece towards improving the experience for Sources, seems to be calling them something more human and natural sounding than "Sources." 

## User Stories

I have documents I'd like to share with the New York Times, that could put my family in danger should my employer or government interests be able to trace this "leak" back to me. It would for certain be career-ending for me, should the leak be traced back to me and I could experience jail time. The "SecureDrop" tool feels like the safest route for me to go, and I want to learn more about how to use it so that I can ensure my anonymity. I only see things written about the tool for engineers and journalists, though—no product overviews or other things that seem to speak to my needs.

**Comment by ninavizz** [comment]
Hey hey! I know this is unlikely to be a simple/easy-peezy thing... but it feels important. 

@huertanix @zenmonkeykstop @eloquence @redshiftzero I know we want to do a holistic review of the Source experience, and of the Source guide—but this feels like a low-hanging fruit item that would need to be included in such efforts, anyway, while also delivering a high value if done sooner rather than later. Hence, identifying this as a starting-point item. 

Thoughts, feelings? Happy to coordinate/facilitate a design workshop in an uncoming sprint that could involve many folks, and be conducted via remote tooling.

**Comment by ninavizz** [comment]
...ok, OCD got the best of me and I had to indulge in a first pass. 
Yeah, this also means splitting RTD into two distinct guides, now: the "User Guide" and the "Installation Guide"

Please forgive the lack of fonts parity to RTD. Goal with below: speak more directly/clearly to non-technical users, and remove content that will alienate and confuse them while more clearly and enticingly guiding them to what is relevant to them. 

Hierarchy matters more at times, than the content itself. Hence, moving "Passphrase Best Practices" to the top, and creating an opportunity to also educate Sources about GPG that would cross-link to the article in the Journalist Guide. 

![image](https://user-images.githubusercontent.com/8262612/53912380-b069ff80-400d-11e9-8542-801bcd0222f3.png)

**Comment by eloquence** [comment]
Thanks @ninavizz! Lots to discuss here. My take:

- Changing the term "source" in the source guide itself: relatively straightforward as long as we can agree on the terminology.

- Changing the term "source" elsewhere in the docs: IMO unnecessary and confusing (since target audience are journalists/admins); *Source Interface* is a core term we shouldn't change.

- Making the table of contents a bit more friendly (cherry-picking some ideas from the above): relatively straightforward.

- Major reorganization: requires us to think carefully how changes will impact current audiences, and may require changes to the docs build pipeline. Not trivial, should be deferred.

I would add that there's no reason to believe that sources discover or read the source guide; it's not linked from most landing pages nor from securedrop.org. Anchoring it more clearly on securedrop.org may be another low-hanging fruit improvement.

See also #490 for some previous discussion for a stand-alone "best practices" guide.

**Comment by ninavizz** [comment]
Quick responses...
- First bullet: Yay!
- Second bullet: Agreed, agreed, oui oui agreed!
- Third Bullet: Coolio!

Fourth bullet & final point: So... if nothing points to the "Source Guide" to provide guidance to Sources, why does it exist in the docs?

I was motivated to pick this back up, after seeing @bumbleblue's recent points made to @heartsucker offering thoughts on how to make the Source experience more usable. Reading your comments however, was a good reminder that there not being an agreed-to "Source Experience" or even "Source Personas," all of this is very hard to evaluate w/o all of us diving into subjectivetopia and personal opinions. Would be nice to start scratching at resolve around the two broader things, but I'd still like to identify low-hanging fruit to make the experience more usable to sources. 

I'll ping @bumbleblue to see if she could come to a UX meeting in the future, and maybe we could all discuss together with some context around where she and Ame were coming at their suggestions from? At a minimum, I'd love to hear them communicate what their expectation of the Source journey is.

Back to the 4th bullet, tho: I do feel it could be helpful and offer some transparency to Sources, into how Journalists and Admins are guided to use SecureDrop. My primary concern with the current RTD setup, is that deep-geekery (installation, localization, and anything targeted to users who at a minimum know Linux and command-line things) and _basic_ user guides are bunched into the same "Guide" artifact, which risks imposing a significant imposter-syndrome burden onto a non-technical user visiting the Guide thinking they just need to learn something basic. 

Is the goal of the Guide to communicate to developers and project contributors, how Journalists and Sources are expected to use SD?

**Comment by ninavizz** [comment]
In the [07 March 2019 UX call](https://github.com/freedomofpress/securedrop-ux/wiki/UX-meeting-20190307) this issue was discussed. Speculated motivations and deeper insights from @bumbleblue's cognitive walkthrough with @heartsucker were discussed, and this issue's goals were punted into #4259. Seeking to close and archive this, however, to open a new/clean issue.
