### ISSUE TITLE
SSH Error: data could not be sent to remote host

### ISSUE THREAD

**Issue by tuanzicc** [freedomofpress/securedrop#4270]

**Comment by emkll** [comment]
Hello, 
your `ssh_users` is set do SD in your configuration file, whereas your terminal session logs in with the `securedrop` username. Try updating your site specific with `ssh_users: securedrop` 

Furthermore, I would recommend you rotate your smtp credentials as they are clearly visible on your screenshot.

**Comment by emkll** [comment]
Hi @tuanzicc , I hope the above guidance was helpful. I am closing this issue as we use GitHub exclusively for development and bug tracking, and not for support purposes. If you encounter any issues, feel free to open a thread on https://forum.securedrop.org
