### ISSUE TITLE
Port TBB functional testing support from `tbb-0.9.0` to `develop`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4290]
Once improvements that can be untangled and cleanly ported to existing functional tests have been merged into `develop` (see #4289, #4287 and #4286), let's port the remainder of the `tbb-0.9.0` branch as appropriate, and get tests passing.

**Comment by redshiftzero** [comment]
See @heartsucker's feedback here #4029 which should be addressed in this merge
