### ISSUE TITLE
SecureDrop instances using 2014 Mac Minis should restart when power restored after an outage

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#4299]
## Description

Currently, Mac Minis must be manually restarted after a power outage. (There is a register setting to allow for an automatic restart, but it requires that the correct PCI device be identified and that a `setpci` command is run on startup (as the setting doesn't persist across reboots).)

## User Research Evidence

Feature requested by current user

## User Stories

As a SecureDrop admin, I would like my Mini-based instance to be available after a power outage without manual intervention.

**Comment by kushaldas** [comment]
I also noticed this thing. It will be a nice thing to have.

**Comment by emkll** [comment]
I have also observed the same behavior on a NUC5CPYH

**Comment by legoktm** [comment]
Mac Mini support was dropped in 2.3.0 (c.f. https://github.com/freedomofpress/securedrop-docs/pull/312, https://securedrop.org/news/securedrop-2_2_0-released/)
