### ISSUE TITLE
Linting container failing in CI

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#4301]
## Description
The `lint` CI checks are failing, due to apt errors reported from the Debian Jessie repos.

## Steps to Reproduce

1. Observe CI failing here: https://circleci.com/gh/freedomofpress/securedrop/24949
2. Run `docker run -it gcr.io/google-containers/python:2.7.11-slim apt-get update` locally and observe same failure.

## Expected Behavior
Apt lists are fetched without error, container build proceeds, linter runs.

## Actual Behavior
Apt lists fail during fetch, container built halts, linter does not run, CI fails.

## Comments
While this may be a transient error, Debian Jessie was marked EOL last year, so we should immediately move the container to a Stretch-based image to ensure continued updates.

**Comment by cji** [comment]
https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

The packages still exist at archive.debian.org if an interim fix would be useful.

**Comment by cji** [comment]
Now that I see that it's being pulled from a jessie based image, scratch the above. :) The easiest solution might be to just switch to `python:2.7.16-slim-stretch` from Docker Hub, which is just a minor version bump in Python but on a stretch based image.
