### ISSUE TITLE
ossec test notifications do not generate ossec alerts

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4339]
## Description

Errors in Apache logs no longer trigger an ossec alert / email notification.

## Steps to Reproduce

1. Navigate to a Journalist Interface on a SecureDrop instance that has email notifications set up
2. Click on Admin, and navigate to Instance Config
3. Click on "Send Test OSSEC Alert"
4. Observe no emails are sent to the admin mailbox

## Expected Behavior

Email should be sent shortly after the button is clicked.

## Comments

Test ossec notification relies on triggering an app error, that is caught by apache logs and then sent to ossec.

Default rule is set to 0, which mean it won't appear in alerts.log (requires level 1) or in emails (requires level 7)

https://github.com/ossec/ossec-hids/blob/master/etc/rules/apache_rules.xml#L173

**Comment by redshiftzero** [comment]
More [extensive testing](https://github.com/freedomofpress/securedrop/blob/develop/molecule/testinfra/staging/mon/test_ossec_ruleset.py) of OSSEC rules could help us catch issues like this (relevant: #2134 #2137)
