### ISSUE TITLE
Lack of 2fa for document interface

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#435]
We have already added TOTP to the document interface via the gauth apache module and we had planned on adding basic auth to provide the second factor (password something they know). People were concerned that basic auth would introduce usability issues for the journalist because it would be yet another password that the journalist would need to know. But after talking with @iSec the security gains out weigh the usability issues.

**Comment by garrettr** [comment]
When I implemented the authentication for journalists in the web application in #522, I added a password in addition to a TOTP (or HOTP)-based two factor code to authenticate each individual journalist. This was the short term solution proposed by iSec in their report, and resolves the issue.
