### ISSUE TITLE
Create securedrop-app-code Debian package with Python 3 dependencies

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4355]
Now that we have basic Python 3 compatibility (#997, resolved through #4239), we need to ensure that all the `securedrop-app-code` dependencies transition to Python 3 as well. The plan of record is to use `dh-virtualenv` to ship these dependencies in the package itself, instead of depending on the system Python libraries. 

This will allow us to use consistent dependency management processes for SecureDrop Workstation and SecureDrop core, and will get us closer to resolving #3407.

**Comment by eloquence** [comment]
For the 4/17-5/1 sprint, Kushal will prepare at least a draft PR for broader team input, which will not use FPF's PyPI mirror yet.

**Comment by redshiftzero** [comment]
hey @kushaldas what is the status of this?

**Comment by redshiftzero** [comment]
can you push up whatever wip you have when you get a chance @kushaldas ?

**Comment by kushaldas** [comment]
I did not manage to work on this enough during that sprint, but, I have other WIP work on my backup system (a `make clean` removed from my laptop during the last trip). I will push it here with details of things needs to be done.

**Comment by redshiftzero** [comment]
please push up whatever wip you have locally so @rmol can check it out since y'all will be working together next sprint to get the combined `mod_wsgi` changes and this issue merged together.

**Comment by kushaldas** [comment]
I pushed https://github.com/freedomofpress/securedrop/pull/4555 to show the changes I made for a debian python3 package using `dh-virtualenv`
