### ISSUE TITLE
securedrop/docs/passphrases.rst

### ISSUE THREAD

**Issue by iqlinuxadmin** [freedomofpress/securedrop#4360]
## Description

Although this page:
securedrop/docs/passphrases.rst
says the admin will need "A master passphrase for the KeePassX password manager"

this page: https://docs.securedrop.org/en/release-0.11.1/set_up_admin_tails.html
says "TIP: If you would like to add a master password, navigate to Database and Change master key. Note that since each KeePassX database is stored on the encrypted persistent volume, this additional passphrase is not necessary."
## Comments

This is a bit confusing- in one place it says the master is needed, in another it says it's not.

**Comment by zenmonkeykstop** [comment]
Thanks @iqlinuxadmin - I've put in a wee pull request which hopefully clarifies this section of the docs a bit.
