### ISSUE TITLE
[docs] Workstation backup procedure results in a unusable backup due to directory ownership issues

### ISSUE THREAD

**Issue by rysiekpl** [freedomofpress/securedrop#4396]
## Description
[Backup the Workstations](https://docs.securedrop.org/en/release-0.12.2/backup_workstations.html) section of the documentation lays out a procedure that ends up creating a backup with ownership of all files set to `root`, rendering it unusable.

## Steps to Reproduce

1. follow the "Backup the Workstations" procedure to back up a workstation
2. create a new Tails thumbdrive with persistent storage
3. copy the files back from the backup onto persistent storage
4. boot Tails from the new thumbdrive and unlock persistent storage in the Tails Greeter

## Expected Behavior

Redeployed workstation is fully usable.

## Actual Behavior

Redeployed workstation is unusable, since ownership information has been lost -- replaced entirely by `root` user owning all files and directories.

## Comments

Related to: #4397

**Comment by rysiekpl** [comment]
One idea would be to use `rsync` instead of Nautilus. People who deploy SecureDrop can probably be trusted with CLI tools like `rsync`, which (if used correctly) would ensure proper permissions, etc.

**Comment by eloquence** [comment]
As far as we know, the permission issue occurs if the files were not fully written to the storage device. In the revised instructions (#4402) we now include a `&& sync` operation to reduce the risk that the storage device is disconnected before the write operation is complete. Please let us know if you encounter the issue with these revised instructions; we have not seen in it in our own testing. Closing this issue for now.
