### ISSUE TITLE
[docs] Add Admin Offboarding Checklist

### ISSUE THREAD

**Issue by olivemartini** [freedomofpress/securedrop#4398]
## Description

Add language in docs to advise orgs how to prepare for Admin turnover — how to handle Admin credential rotation, hardware handoff, etc.

## User Research Evidence

Offboarding and transferring Admin duties takes time from the news organization, the new Admin, and our support team. We should prepare documentation as a solution to this issue, and to encourage better administration of SD instances.

**Comment by eloquence** [comment]
Thanks for filing this earlier this year, @olivemartini! This is definitely on our radar and we plan to take it on in the next 4-8 weeks.

**Comment by olivemartini** [comment]
Very cool! I thought I'd have the bandwidth to take this issue myself when I first filed it, but that was clearly not the case. Do let me know if I can assist in some way. It'd be helpful to give recommendations for at least these two scenarios: 1. amicable Admin exit and 2. bad news (there's definitely a better phrase here) Admin exit.

Or, focus on scenario 1, and adding at the end: if things have gone south with the exiting Admin, here are extra steps you might take. @zenmonkeykstop has a really clear and concise answer for this, iirc!
