### ISSUE TITLE
Add type annotations to securedrop app code

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4399]
In the securedrop application code we use [typing](https://pypi.org/project/typing/) and [mypy](https://mypy.readthedocs.io/en/latest/) and have annotations only in a few files. We should have individual PRs that:

- Add type hints to the codebase one file at a time (since small diffs easier to review)
- Enforce 100% annotation in those files in CI (done via this makefile target: https://github.com/freedomofpress/securedrop/blob/develop/Makefile#L37)

Please comment here what file you are taking to avoid duplication of work

See also: #2795

**Comment by redshiftzero** [comment]
@rmol discovered this problem when reviewing #4408:

> We have a bigger problem with derivations of sqlalchemy.Model, as they effectively resolve to Any and thus aren't really checked. We talked to the mypy developers yesterday and have an idea for fixing this, but we'll tackle that in a later PR. It shouldn't hold this one up.

The idea mentioned there was:

```
# SqlAlchemy's Model is typed Any, so mypy won't check model classes
# unless we make them more specific.
if typing.TYPE_CHECKING:
    class BaseModel:
        def query(self, *args, **kwargs):
            pass
else:
    BaseModel = db.Model
```

**Comment by pierwill** [comment]
👋 Volunteering to help with this!

**Comment by pierwill** [comment]
Currently working on [source_app/utils.py](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/source_app/utils.py).

**Comment by nabla-c0d3** [comment]
FYI after all my current PRs are merged, I will make a final PR to enforce/require type annotations across the whole repo.

**Comment by nabla-c0d3** [comment]
This issue can now be closed: typing annotations are enforced across all files outside of the test suite.
