### ISSUE TITLE
404 in docs for Tails install guide

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4403]
The link https://tails.boum.org/doc/first_steps/installation/index.en.html/ in  https://docs.securedrop.org/en/release-0.12.2/tails_guide.html is no longer live, so we'll need to revise this section a bit & remove the dead link.

**Comment by Dalek-Sec** [comment]
I made a subjective judgement how to fix this in PR #4409

**Comment by redshiftzero** [comment]
closed by #4409 (although will need backport into 0.12.2)
