### ISSUE TITLE
Check documentation links as part of docs linting

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4410]
## Description

Sphinx [linkcheck](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder) allows the verification of links with the `requests` library to ensure that the links are still valid and active. It might be useful to run this regularly or as part of CI to catch dead or broken links.
## User Stories
As a user, clicking on a link and getting a 404 can be a a frustrating experience.

**Comment by pierwill** [comment]
Great idea! I'll take a look into this—

**Comment by redshiftzero** [comment]
possibly, how long does this take to run on the current docs?

**Comment by pierwill** [comment]
Not sure. Haven't been able to check with my current environment problems (#4472).

Will try to test this using a previous docker image.

**Comment by pierwill** [comment]
Time to run sphinx's linkcheck feature is at least a few minutes. I'm at 5 minutes right now on an iffy connection, 70% done.

Any objections to making this its own make target, `make docs-linkcheck`? Would be useful for those regularly working on docs as a whole.

**Comment by redshiftzero** [comment]
yeah making it a separate target from `docs-lint` is a good call given the time to run :+1:
