### ISSUE TITLE
Keep two different versions of requirements.txt file for Python2 and Python3

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#4415]
## Description

`pip-compile` creates different output for `requirements.txt` for Python2 and in Python3. Which in turn creates problems in installing those dependencies in the different versions. 

## Probable solution

Have two different requirements files for Python2 and Python3, for both dev and tests.

**Comment by rmol** [comment]
@kushaldas Unaware of this ticket, I went down a different path trying to address this, and [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) seemed to work. At least they let me keep Python 2 requirements in the file without breaking Python 3 usage, e.g. `enum34` and `ipaddress`. 

Are there other problems they don't cover, or might that be a solution?

**Comment by kushaldas** [comment]
@rmol I will have to re-research tomorrow morning.

**Comment by rmol** [comment]
@kushaldas I'd still be interested to hear your thoughts about environment markers, but after further investigation it looks like separate requirements files will be easier.
