### ISSUE TITLE
Source Interface message to flagged sources is inaccurate

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4420]
As a result of issue #1524 / PR #1558, the message shown to sources that have been [flagged for reply](https://docs.securedrop.org/en/release-0.12.2/journalist.html#flag-for-reply) was updated, from this:

> A journalist has been waiting for you to log in again so SecureDrop can generate a crypto key for you. Now that you have logged in, they are able to write you a reply. Check back later for replies.

To this:

> **Whew, it’s you! Now, the embarrassing part...**
> Our servers experienced an unusual surge of new activity, when you last visited. This could have been human activity, an automated attack, or just some random blip. To err on the side of caution, we put a hold on sending all documents from that day through to our journalists.
>
> Now that we know you’re really a human, though, we’ll get your previous submission into the
> hands of a journalist straight away. We’re sorry for the delay. Please do check back again
> in a week or so.

This revised language is inaccurate. In particular, this part: "To err on the side of caution, we put a hold on sending all documents from that day through to our journalists. Now that we know you’re really a human, though, we’ll get your previous submission into the hands of a journalist straight away."

Flagging is a process used to manually select sources for keypair generation upon login in the case of entropy depletion. This only impacts the ability of news organizations to reply to sources. It does not impact their ability to review documents or messages from any source, nor the source's ability to send more. Indeed, reviewing documents or messages is the method by which news organizations can validate _which_ sources to flag for reply.

I would recommend rewording other parts of this message as well, but at minimum, this part needs to be updated, so that sources don't get an inaccurate impression _when_ a news organization was able to first see their message or document. I will propose alternative wording in a comment.

**Comment by eloquence** [comment]
Proposed alternative wording:

> **Sorry that we have not responded yet!**
>
> Our SecureDrop recently experienced a surge of activity. We were able to download your submission, but for security reasons, the creation of a two-way communication channel was delayed until now. Please check back again later for a reply.

The rationale for the above wording is to keep it simple and focus on the part that's important to the source: they got my message/document and will get back to me.

**Comment by heartsucker** [comment]
> was delayed until now.

This seems to leave the source hanging. Do they need to take action. I think it should additionally say.

> By logging back in, the final steps have been automatically completed. You can now receive messages.

Because also "Please check back later" makes it sounds like maybe later they need to do something else. I mean, whatever it is, I feel like it should definitely say "No really you don't have to do anything else, everything is done."

**Comment by ninavizz** [comment]
@heartsucker I feel the (judo-move!) addition of "the creation of a two-way communication channel was delayed until now" accomplishes need you identified & seek to solve in the sentence you proposed.

Honestly, the text I recommended 2 years ago was WAY too long—and Erik's suggested text comes right-up against the limit of how long UI text should be (tho I'm a tad hurt Mr Formal wants to remove `Whew` ...hmmph!). ;)

When anyone sees a block of text that's more than 1-2 lines, it begins to morph into a "wall" that discourages engagement.

**Comment by eloquence** [comment]
Yeah, I agree that we need to be very careful with length, _especially_ for a one-time flash message like this one. That said, I do like the reassuring power of a sentence like "You can now receive messages", which may be worth adding 5 words to our word budget. :)

**Comment by ninavizz** [comment]
I see a perfect compromise coming together... huzzah! See, much more fun than one person doing all the writing (and ohey, higher quality output, too!) Thank you both @heartsucker and @eloquence 

Also, I love the concept of a "word budget." Heehee. 

Final nits: 
- Conjunctions are advised in UI/message copywriting, to make the cognitive-intake more of a quick-burst than a "hmmm..." moment requiring focus. As such, `have not` I recommend to change to `haven't`. Curious how such things work in the L10n/translations process. 
- I also killed "that," as it's not totally necessary—and the salutation reads more quickly, w/o it.
- I re-arranged the second sentence so it reads a little more smoothly wrt informing users about what happened, why it happened, and what that means for them. Addressing those points in that order is usually a good formula to follow, for UI messaging.
- The user did not enter a password to re-visit the Source UI; as such, it's an assumption I'd like to examine in future user testing, that the concept of "Logging In" will mis-match the Source's mental model of their follow-up visit, whereas "Check In" or "Checking In" makes more sense to me (I also recommended it as a button text update, in unrelated Source UI stuff).

> Sorry we haven't responded yet!
> 
> Our SecureDrop recently experienced a surge of activity. We were able to download your submission, but the creation of a two-way communication channel was delayed for security reasons. By checking in again, you've triggered the final step to complete that channel and are now able to receive messages. Please check back again later for a reply.

Ok, now it's almost as long as the current message. :/

What do you guys think of the above, taking into consideration all of our contribs?

**Comment by eloquence** [comment]
One last proposed rev for brevity:

>  Sorry we haven't responded yet!
> 
> Our SecureDrop recently experienced a surge of activity. For security reasons, the creation of a two-way communication channel was delayed until you checked in again. Please rest assured that we were able to download your submission, and check back again later for a reply.

**Comment by ninavizz** [comment]
Aww, I love that! "Please rest assured" is just so lovely. And, agreed—it reads far more smoothly. 
Thank you, again. 

Yeah, eventually adding a link to direct the user to an `.onion` Source Guide that can explain why this happens, would be nice. It's a bit of a WTF pill to swallow, but I think we've whipped this peanut-butter to be as silky smoove as it could possibly be. 

I say ship it! <3
