### ISSUE TITLE
"Journalist key" in source interface is not (typically) a journalist key

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4421]
The *Source Interface* refers to "the journalist's public key", both through the `/journalist-key` and `/why-journalist-key` route names, and in the page heading on the `/why-journalist-key` page, "Why download the journalist's public key?"

This is very misleading wording, as most SecureDrops are operated by news organizations employing more than one journalist. This key is in fact the SecureDrop Submission Key for this installation, the _exact same_ key that messages/files will be encrypted to upon submission. (See #4413 for terminology standardization.)

Offering technical users the option to pre-encrypt is essentially a workaround until we establish a reasonable method for automatic client-side encryption (see #92).

To avoid messing up people's mental model of how SecureDrop works, we should rename this route, especially given that we do refer to managing individual journalist keys in parts of the documentation (for completely different reasons: to securely export files from the *Secure Viewing Station*).

**Comment by eloquence** [comment]
@DrGFreeman Are you potentially interested in helping with this, as well?

**Comment by DrGFreeman** [comment]
@eloquence, sure, I can get on it shortly.

So my understanding is that only the routes need renaming as the Source Interface now refers to the key as "our public key" (on `/lookup` and "the team's public key" on `/why-journalist-key`.
