### ISSUE TITLE
Guidance in docs re: remembering Transfer Device passphrase is outdated

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4434]
The [setup docs for the Transfer Device](https://docs.securedrop.org/en/release-0.12.2/set_up_transfer_device.html) instruct the administrator to use the "Remember Password" feature on each workstation, so they don't have to enter it by hand or store it in their password manager.

Unfortunately, persisting GNOME keyring data was [removed](https://redmine.tails.boum.org/code/issues/15275) in Tails 3.9. Keys persisted before then continue to work, but on any workstation set up since then, these instructions won't work.

The "Remember password" checkbox still appears; it just won't actually remember the passphrase after the Tails session is complete.

There's an upstream issue, https://redmine.tails.boum.org/code/issues/16718 , to consider reinstating that functionality; for now, we should update the docs in line with current behavior.

**Comment by eloquence** [comment]
Should we ask folks to store this passphrase on each workstation that might need to mount the Transfer Device, including the SVS? Note that we currently don't recommend setting up KeePassX on the *SVS*, as far as I can tell.

**Comment by olivemartini** [comment]
Good point, @eloquence. The Journalist still must access the KeePassX database on the Journalist Workstation and transcribe the passphrase to mount the persistent volume on the SVS. If we don't want to disrupt existing workflows/documentation, I think it is sufficient to expect the same behavior (passphrase transcription from the Journalist Workstation) to get the passphrase to mount the Transfer Device on the SVS. It could be clunky, so I'm open to other opinions, however!

**Comment by zenmonkeykstop** [comment]
I think there's an argument for adding a KeePassX db on the SVS at least for this passphrase. It's probably better that journalists don't either bring the JW or write down that passphrase every time they use the SVS. If an org was following perfect workflow as recommended, they wouldn't bring in extraneous hardware to the SVS room.

**Comment by eloquence** [comment]
Upstream [notes](https://redmine.tails.boum.org/code/issues/16718) that it can be manually configured by adding this to `persistence.conf`:

```
/home/amnesia/.gnome2/keyrings  source=gnome-keyrings
```

Between asking folks to set up yet another password manager vs. the admin manually adding this during setup, manually adding it during setup -- if it does work as expected -- might be the better choice. Thoughts? Sounds like upstream may restore the feature, but that will take a while.

**Comment by zenmonkeykstop** [comment]
Can we fix this in `tailsconfig` by adding the line there?

**Comment by eloquence** [comment]
Upstream has decided not to reinstate the old behavior, as they feel that it's difficult to communicate to the user in a reasonable way what passwords would/wouldn't persist when persistence is enabled for the GNOME keyring.

It should be noted that our current guidance for the *Transfer Device* is impractical, even with the recent changes to the [Journalist Guide](https://docs.securedrop.org/en/latest/journalist.html). We recommend encrypting the *Transfer Device* with LUKS encryption, which won't work on non-Linux operating systems. 

IMO we should do some more testing with VeraCrypt first (#4620). Do VeraCrypt passwords get persisted into the GNOME keyring? If so, finding the most elegant to enforce that persistence across workstations would be the next step.

**Comment by eloquence** [comment]
Per https://github.com/freedomofpress/securedrop/issues/4620#issuecomment-515215032, we may well keep using LUKS at least for the *Journalist Workstation→SVS* part of the workflow.

It seems really error-prone to try to get admins to consistently enable GNOME keyring persistence for all workstations, and ensure that that characteristic is preserved throughout a SecureDrop instance's lifetime. If it is not, it could lead to sudden lack of access to the device in question.

Compare the requirement to [enforce filename preservation during gzip de-compression](https://docs.securedrop.org/en/release-0.14.0/set_up_svs.html#ensure-filenames-are-preserved) in Tails, which anecdata suggests is not being consistently implemented by news organizations.

It seems to me that we have two realistic options:

- Ensure that passwords for the transfer device (and, potentially, a separate export device) are stored on each workstation that reads or writes to that specific device. (This would require also setting up a password manager on the journalist's everyday workstation.)

- Ensure that passwords for the transfer device (and, potentially, a separate export device) are stored in a mobile password manager used by people managing the system.

Of these options, I find the second one to be the better recommendation. It works well for small orgs (which likely only have 1-2 users checking SecureDrop) and large ones (which likely already have standards around password distribution and management they can follow). We can point to the training team's excellent guide for [choosing a password manager](https://freedom.press/training/blog/choosing-password-manager/), and we'll likely be able to use a similar procedure for the SecureDrop Workstation's Export Device.
