### ISSUE TITLE
Strip unnecessary CSS from source interface

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4450]
The CSS served via the *Source Interface* currently includes the full [Font Awesome Free 5.0.6](https://fontawesome.com/) styling. As the name suggests, Font Awesome is an icon font; the purpose of the CSS styles is to enable you to render its glyphs using syntax like `<i class="fas fa-camera"></i>`. However, the font is not actually used on the *Source Interface* (because it conflicts with Tor browser's behavior in the "Safest" security setting). Instead, we serve up static images rendered from the few glyphs that we use as icons.

The Font Awesome CSS is therefore likely wholly unnecessary. The issue here is to:
- Verify whether any part of the Font Awesome CSS is required for current *Source Interface* styling
- Strip the stylesheet as appropriate.

**Comment by eloquence** [comment]
(Thanks to @ninavizz for reporting this issue.)

**Comment by drewmassey** [comment]
So if we look at this:
```
$ grep -i 'fa-' securedrop/source_templates/*
``` 

we get this:
```
securedrop/source_templates/generate.html:    <img class="icon off-hover" src="{{ url_for('static', filename='i/font-awesome/fa-arrow-circle-o-right-white.png') }}" width="17px" height="17px">
securedrop/source_templates/generate.html:    <img class="icon on-hover" src="{{ url_for('static', filename='i/font-awesome/fa-arrow-circle-o-right-blue.png') }}" width="17px" height="17px">
securedrop/source_templates/locales.html:    <img class="icon menu__trigger-icon" src="/static/i/font-awesome/fa-globe-black.png" width="18px" height="16px">
securedrop/source_templates/login.html:    <img class="icon off-hover" src="{{ url_for('static', filename='i/font-awesome/fa-arrow-circle-o-right-white.png') }}" width="18px" height="18px">
securedrop/source_templates/login.html:    <img class="icon on-hover" src="{{ url_for('static', filename='i/font-awesome/fa-arrow-circle-o-right-blue.png') }}" width="18px" height="18px">
```

And so there are no raw calls to `<i class="fa-..."></i>` in the HTML code (unless it lurks elsewhere). Hence this issue could be resolved by taking the following steps:

- Removing references to font-awesome in `_base.sass`
- Deleting `securedrop/sass/libraries/_font-awesome-iconography.sass`

Does this make sense to you @eloquence ?
