### ISSUE TITLE
Dim the source interface when idle

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#447]
On some dark markets, they now have a security feature where if you're idle or change focus for a certain amount of time, the page totally dims itself, so if you walk away from the computer and leave it up then no one walking by can see what you were looking at. This seems like a great idea that we should implement for SecureDrop, and the best part is that it requires no JavaScript but is all done with CSS. For example, the code below will hide the page after 1 minute. Let me know what you think and I can submit a pull request!

```
<style type="text/css">
@keyframes fadein { from { opacity: 0; } to { opacity: 1; } }
@-webkit-keyframes fadein { from { opacity: 0; } to { opacity: 1; } } 
@keyframes fadeout { 0% { opacity: 1; } 98% { opacity: 1; } 100% { opacity: 0; } }
@-webkit-keyframes fadeout { 0% { opacity: 1; } 98% { opacity: 1; } 100% { opacity: 0; } } 
html {
        animation: fadeout 60s;
        -webkit-animation: fadeout 60s;
        opacity: 0;
}
html:hover {
        animation: none;
        -webkit-animation: none;
        opacity: 1;
}
</style>
```

**Comment by garrettr** [comment]
Again this is interesting idea, but I concerned it would negatively impact usability for sources. Even @ageis admits it confused him the first time he encountered it. Perhaps the best course of action would be to merge it for 0.4, and let it bake for a while to see if we like it? This also seems like the kind of feature that would be good to evaluate with a user study.
