### ISSUE TITLE
Sphinx-autobuild missing in Docker container

### ISSUE THREAD

**Issue by pierwill** [freedomofpress/securedrop#4472]
## Description

Problems running docs locally under Docker.

## Steps to Reproduce

1. `cd securedrop/`
2. `bin/dev-shell bash`
3. `cd ..`
4. `make docs`

## Expected Behavior

Run the docs server.

## Actual Behavior

fails with
```Makefile:12: *** The 'sphinx-build' command was not found.```

## More info

I've attempted to solve with `pip install -r securedrop/requirements/develop-requirements.txt`, but the same error appears.

Attempting to install the dependency singly also fails:

```
$ pip install sphinx-autobuild
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```

**Comment by eloquence** [comment]
This is no longer relevant with the standalone docs repository which does not rely on Docker, see the README for quickstart instructions: https://github.com/freedomofpress/securedrop-docs
