### ISSUE TITLE
Only run lint, deb-tests CI jobs on builder image updates

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4484]
## Description

We kick off a lot of unnecessary CI jobs for builder image update PRs:

https://circleci.com/workflow-run/08e02775-390d-4644-8524-f8af71793100

We only should keep the lint and deb-tests jobs around

**Comment by emkll** [comment]
I think in this case it might make sense to keep the staging-with-rebase job: While the builder tests do have some unit testing around expected files, staging-with-rebase will ensure those packages are installable on the target os. What do you think @redshiftzero ?

**Comment by redshiftzero** [comment]
good point, let's keep the staging job
