### ISSUE TITLE
Update favicon: color!

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4502]
## Design Epic 
Design updates to the Source UI (w/in the existing experience) are being explored in [UX-repo issue #42](https://github.com/freedomofpress/securedrop-ux/issues/42). Within these updates, a new color palette is being used. The goal of the color updates are make the product reflect the SecureDrop brand, as it's presented on the website. They also make the product snazzier.

**This issue has been drafted to implement the below in a PR after #4500 has been completed**
 
## This Issue
- [x] Update SecureDrop favicon that ships with the product. `sd_favicon-2019.png` is [here](https://drive.google.com/open?id=1ycflbtla_9ZU0ErKBv-pqEUThfCcKl4w)

**Comment by eloquence** [comment]
![Screenshot from 2019-07-19 14-54-23](https://user-images.githubusercontent.com/213636/61567722-74bc5900-aa35-11e9-8544-b5c4db8373b6.png)

New favicon on light/dark background by comparison (active/inactive tab). I think the edge looks a bit frayed on a darker background.

**Comment by ninavizz** [comment]
New colors + PNG artifacts documented: freedomofpress/securedrop-ux#65
