### ISSUE TITLE
Migrate virtualenv on Tails Workstations py2 -> py3

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#4516]
## Description

The virtualenv on Admin & Journalist Workstations is currently based on Python 2. As we port the script logic to Python 3 (#3489), we'll also need a plan to migrate the virtualenv. 

See the logic in the `envsetup` def: https://github.com/freedomofpress/securedrop/blob/97d603d136a24bae9756f8b55a7efe16b0fdec16/admin/bootstrap.py#L127-L128 Simply changing the `VENV_DIR` to `.venv3` may be sufficient for first-time installs, but we'll have to test the upgrade story carefully. 

## User Research Evidence

None. We must perform this change to ensure that software used for managing SecureDrop is up to date, and receiving security fixes.

## User Stories

As an Admin, I want the tools required for managing SecureDrop to retain upstream security support. 

As an Admin, I want upgrades to be as smooth as possible, with a minimum of manual steps to be perform on multiple workstatoins.

**Comment by legoktm** [comment]
This was done in 30940ab01f636574b482eb04d96525f1fcf30a7b.
