### ISSUE TITLE
Use Python 3 in development environment

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#4519]
## Description

We should transition our development environment to Python 3. We're preparing to switch the source and journalist production servers to Python 3 with 0.15.0, and aligning development and production will reduce the likelihood of discovering problems only during deployment.

See also #4292.

**Comment by redshiftzero** [comment]
Part of this ticket will be if investigating if https://github.com/freedomofpress/securedrop/issues/4415 can be closed (i.e. can we get away with shared py2/3 requirements files)
