### ISSUE TITLE
Screenshots in source guide are out of date

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4529]
The screenshots in the [source guide](https://docs.securedrop.org/en/release-0.13.0/source.html) are out of date (0.8.0rc1), which is leading to some inaccuracies:

- The "Tor browser" instructions will be updated as part of 0.14.0 (#4494), but the screenshots still reflect the old instructions, including an old screenshot of the security slider

- The "Flagged for reply" language was updated due to inaccuracies (#4420), but the language here is still the old language

There are smaller issues, such as the icon mismatch for submission (icon was updated in #2508).

Let's update these screenshots consistent with the current state of `develop`, ideally in time for 0.14.0 so we can push out updated Tor instructions both in docs and code at the same time.

**Comment by ninavizz** [comment]
Note: if #4500, #4501, #4502, and #4503 go into 0.14.0, those will dramatically change the Source UI. So—this issue should only then be tackled, with resolution around the 4 aforementioned styling thingys being in or out of 0.14.0.

**Comment by ninavizz** [comment]
Discussed the above comment on Slack, and it's safe to say that the above tickets will _not_ be making it into 0.14.0.

That said, I also just created #4535, which would be terrific to get into 0.14.0 (and the updated screenshots), if possible.
