### ISSUE TITLE
Update "Upload" icon in Source UI

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4535]
## Description

Per #2508 and #1536, the upload icons were changed; first, to a datastore icon, and later to a cloud icon. The design rationale to add the datastore icon was to avoid use of cloud semiotics in the icon, which can scare users. The datastore icon confused users, however, so another cloud icon replaced it.

This issue is to replace the latest cloud icon with a more common upload icon that both speaks to the needs flagged in #1536, while also considering the user feedback that the (admittedly obscure) datastore icon was unclear.

## User Needs Evidence

See above

## Implementation

The attached files were created from the PNGs currently used in the Source UI. Same size, same placement of the art, same whitespace—so ideally, only the filenames would need to be changed in the code. 
- [Big arrow PNG](https://drive.google.com/open?id=1dXGEFu6QTx0yUowGKBVNAnHE_VzDBEyu)
- [Blue arrow PNG](https://drive.google.com/open?id=1ppo8iibYk6lu_KnzCLUD8Qo-0Vmz6Qmd)
- [White arrow PNG](https://drive.google.com/open?id=1exp_FQDC_XBgP1lz_ikEpQIq-tQV-6NY)

**Comment by ninavizz** [comment]
^ Happy to discuss in forthcoming UX meeting; wanted to get issue in GH for now, however.

**Comment by ninavizz** [comment]
Discussed in UX meeting. Agreed to action items:
- Both icons to be replaced
- @eloquence said he'd do as an off-sprint PR
- Do this, before updating screenshots (kind of a **_duh_**, but `shrugs`)

**Comment by ninavizz** [comment]
Updated files, based on first rev by Erik revealing sizing weirdness (and wanting to tweek the grey/blu on the Submit page logo):
- [Small Blue](https://drive.google.com/open?id=1ZUhHGM76XPh8P_L18Gjf1MY8gFECLNFl)
- [Small White](https://drive.google.com/open?id=1w2xVKs5nnPijbZK-zvLUymAlkxAaLLsx)
- [Big Pewter](https://drive.google.com/open?id=1QhbZ8osjdAjRG5rAphUtaCZjA-Lr4tAG)

**Comment by eloquence** [comment]
We've poked at this today and are pretty happy with the final version (comment above) of the small icons, but the large one doesn't scale well in Firefox to the 80x80 size it's rendered at (it's nice to use higher res versions to enable zooming on high DPI displays without an 8-bit style appearance). Nina will investigate further.
