### ISSUE TITLE
Consider removing or archiving outdated upgrade documentation

### ISSUE THREAD

**Issue by edenemmanuel** [freedomofpress/securedrop#4547]
## Description

We should consider removing or archiving outdated SecureDrop and Tails upgrade documentation. While it is useful to have these docs available for posterity sake, it clutters up the TOC (and thus the sidebar) of the documentation, which can be overwhelming for new admins/potential admins. As an example, see the screenshot appended to this ticket.

We have precedent for doing this in #1750.

## Motive

Why the removal or archival? If an admin is using an older version of SecureDrop (esp. really old versions), they should not be encouraged to upgrade over several releases to the latest version. Rather, they should backup what they need (if any) and do a full reinstall.

Similarly with Tails drives, it is unrealistic to expect an admin or a journalist to upgrade to the latest version of Tails from the 1.x series. They would similarly be advised to backup and reinstall the latest version as appropriate.

## Potential fix

I would aim for complete removal, since one could view older versions of the documentation by selecting what version they'd like to view from the documentation itself. (We have precedent for this, as mentioned earlier.)

If that's undesirable, then I would advocate creating a separate TOC section entitled "Outdated Documentation" or something similar and moving these pages down there. It would keep the relevant bits of documentation clean.

If we decide to remove or archive the documentation, we should set a policy for how many upgrade documents would be appropriate to keep in the "current documentation". My initial stab at a policy would be to keep the last three releases.

This policy could be enshrined in the documentation guidelines.

## User Stories

As an admin or a journalist, I might be overwhelmed by the sheer number of articles available, particularly in the sidebar.

As an admin of a severely outdated instance, I might consider the availability of upgrade documentation to mean there is implicit support for upgrading from very old versions, rather than the much more appropriate "upgrade" method: to perform a backup and reinstall.

## Screenshot

![Screenshot 2019-06-22 at 16 22 29](https://user-images.githubusercontent.com/8506155/59969774-72381380-950a-11e9-97fb-e8d5e7bc52e3.png)

**Comment by edenemmanuel** [comment]
I would be happy to prepare a PR for this, as directed, if there's support for this ticket.

**Comment by KwadroNaut** [comment]
Regarding the text, where you would advise people to backup and reinstall, it would be nice to point out that people can still read the old instructions. Readthedocs even has a convenient interface for this:
https://docs.securedrop.org/en/latest/
![1](https://user-images.githubusercontent.com/99527/59974577-13c47100-95ae-11e9-8c96-1403291911c0.png)
![2](https://user-images.githubusercontent.com/99527/59974578-13c47100-95ae-11e9-97bb-9e6a57014fe1.png)
Rationale: it happens where you need to find out *what* to backup from an older usb-backup, or you might be 2 minor versions behind and need to double check what has changed or why there were several hotfixes after each other.

**Comment by edenemmanuel** [comment]
Correct! Worth considering mentioning the RTD feature, which would be the way to look at old documentation.

There are [several](https://docs.securedrop.org/en/release-0.13.1/upgrade/xenial_backup_install_restore.html#step-1-back-up-your-instance) [places](https://docs.securedrop.org/en/release-0.13.1/backup_workstations.html] in the documentation regarding backing up the Workstations and backing up instances.

If there is action required from admins due to changes/bugfixes in a new release, the release notes have historically provided them, and they've been incorporated into the documentation.

**Comment by eloquence** [comment]
Thanks @edenemmanuel! If others have no objections, I think it would make sense to remove all upgrade docs up to (but _not_ including) https://docs.securedrop.org/en/release-0.13.1/upgrade/xenial_after_april_30.html ; end of Trusty support is a logical cutoff.

**Comment by eloquence** [comment]
We're on board with the removal of the older upgrade guides as described in my previous comment.

@edenemmanuel Do you have time to work on this in the next few days? If not I can take a stab at it early next week. 

This is bumping up a bit in urgency as these docs often include the `gpg --recv-key` command for fetching the release key, and we're updating those invocations for 0.14.0 to specify a keyserver explicitly. These invocations come up a lot in the older guides, and rather than updating them, we can just remove the outdated guides altogether as you suggest.

**Comment by edenemmanuel** [comment]
I can tackle that for sure @eloquence.
