### ISSUE TITLE
Incorrect (but compatible) width/height attributes in image markup

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4549]
## Description

Many of the `<img>` tags in SecureDrop's templates look like this:

```html
<img class="icon" src="some-image.png" width="20px" height="14px">
```

To the CSS-trained eye, this may look perfectly correct, and indeed it is rendered without problems as most rendering engines will happily ignore anything after the integer. However, this is technically not valid HTML, and https://validator.w3.org/ will report it as an error ("Bad value 14px for attribute height on element img: Expected a digit but saw p instead."). 

For `width` and `height` attributes, the value should be a non-negative integer without a unit (as pixels are always the unit). To avoid surprises, let's use valid markup throughout.

**Comment by nightwarrior-xxx** [comment]
@eloquence So we have to remove the ```px``` and use something like ```%``` ?

**Comment by eloquence** [comment]
No, the syntactically correct way to specify the `width` or `height` attribute inside an `<img>` tag is without any unit as the unit is implicit, e.g., `<img src="some-image.png" width="100">`.

**Comment by nightwarrior-xxx** [comment]
We have to do it for every image which has ```width``` and ```height``` in ```px``` . I am confused where we have to change it.
