### ISSUE TITLE
Tails Guide instructs users to use `develop` version of the codebase, without verification

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4566]
The Tails guide here:

https://docs.securedrop.org/en/release-0.13.1/tails_guide.html

includes instructions for setting up the `securedrop` repo on a Tails workstation. However, it does not include the download of the release key, the checkout of a specific tag, or the signature verification.

I've not tested if the graphical updater will succeed under these conditions to switch the user to a signed tag on the next update, but if they do not update, they'll be stuck on the ` develop` version of this codebase, which could cause issues attempting to use the `tailsconfig` command.

This may fail for other reasons: the guide does not include instructions for copying the required hidden service definitions to ensure that the `tailsconfig` command can use them.

This guide is also very unclear as to who its target audience is (admins provisioning Tails sticks? journalists?). We should carefully examine whether it should be consolidated with other existing guides. If not, to avoid such inconsistencies, let's consider using re-usable text blocks for instructions that must be repeated.

**Comment by redshiftzero** [comment]
I think we should at least remove the git clone section for 0.14.0 and link out to https://docs.securedrop.org/en/release-0.13.1/set_up_admin_tails.html#download-the-securedrop-repository (this is what the primary Journalist provisioning docs in https://docs.securedrop.org/en/release-0.13.1/onboarding.html do)
