### ISSUE TITLE
securedrop-admin logs command should clean up logs from admin workstation and server after task completion

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4593]
## Description

When running `./securedrop-admin logs`, the unencrypted log tarball is stored in the user's home directory, root owned with a+r permissions. Both encrypted and non-encrypted log tarballs are also stored in install_files/ansible-base.

The `./securedrop-admin logs` command should clean up the unencrypted tarballs from both the admin workstation as well as both app and mon servers' home directories.

## User Stories

As an administrator, I do not want old logs to use up space nor to be available in the clear to a non-privileged user

**Comment by zenmonkeykstop** [comment]
Related if we wanted to delete files securely without relying on shell commands: https://github.com/ansible/ansible/issues/20958
