### ISSUE TITLE
potential test flake in _source_proceeds_to_login

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4614]
## Description

I'm not actually sure if [this](https://circleci.com/gh/freedomofpress/securedrop/30888) is even a flake since it's blocking most PRs into `develop`, may be a consistent failure:

```
    def _source_proceeds_to_login(self):
        self.safe_send_keys_by_id("login-with-existing-codename", self.source_name)
        self.safe_click_by_id("login")
    
        # Check that we've logged in
        assert self._is_logged_in()
    
        replies = self.driver.find_elements_by_id("replies")
>       assert len(replies) == 1
E       AssertionError
```

**Comment by rmol** [comment]
It is oddly consistent the last couple of days. That code checking `#replies` is from 2017. The element it's looking for is in the template HTML, not added by JS or anything, and I don't see anything else that could appear with that ID. The `self._is_logged_in()` check above waits for another element (`div#logout`) to be present in the DOM, so by the time we're looking for `#replies` it should definitely be present. So I don't _think_ it's the recent changes to `safe_click_by_id` (and as of yet, the lack of restoring `el.location_once_scrolled_into_view` that fixed a flake Kushal ran into yesterday) causing navigation to fail during login -- if `#logout` is present, a page has been loaded after login, with the user in the session, so `#replies` should be there as well.

The only thing I could think of is that my recent removal of Selenium's implicit waits is causing a problem with the time taken by the `find_elements_by_id` call, but I would think we'd get a `TimeoutException` in that case. And the same test is on its 217th successful run on my machine right now. 

We definitely should purge `find_elements_by_id` from our tests. It has to crawl the DOM, so it's much slower than the singular `find_element_by_id` or, if you really do want to assert that only one element has the ID, using `find_elements_by_css_selector("#id")` and counting the results. But I don't think it's why this is failing.
