### ISSUE TITLE
Split securedrop into separate repositories?

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#462]
SecureDrop is a set of different software that runs on different machines. Some software gets run on the app software, and different software gets run on the monitor server. The source and journalist interfaces also run their own software (though they share many of the same internal python modules).

With #415, we're also adding securedrop-client, [securedrop-airgap](https://github.com/micahflee/securedrop-airgap), and a shared module between them, securedrop-updates (maybe it should python-securedrop-updates).

Should these all start out as separate repositories, and should we split the current freedomofpress/securedrop into separate repos as well?

Or should we continue to stick with just one big repo with all of it (how we've been doing it)?

**Comment by garrettr** [comment]
FWIW, we've split the OSSEC and grsec packages that we maintain into separate repositories (they were originally tracked in `install_files`): https://github.com/freedomofpress/ossec and https://github.com/freedomofpress/grsec

**Comment by dachary** [comment]
Years after this issue was open there seems to be an agreement on how how the repositories are set. Feel free to re-open if you feel differently.
