### ISSUE TITLE
Fetch-tor-debs ci target is failing

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4626]
## Description

Non-dev builds for Tor 0.3.5.x series Xenial builds are longer mirrored on the torproject apt mirror [1], and causes CI to fail
https://circleci.com/gh/freedomofpress/securedrop/31282

Tor apt mirrors currently serve `tor_0.4.0.5-2~xenial+1_amd64.deb`.

We should wait as 3.5 is an LTS series, which will received 2 more years of updates over the 4.0 series.

[1] : https://deb.torproject.org/torproject.org/pool/main/t/tor/
[2] : https://trac.torproject.org/projects/tor/wiki/org/teams/NetworkTeam/CoreTorReleases

**Comment by mmahut** [comment]
Hit the same issue today, changing it to 0.4.1 as a workaround.

**Comment by redshiftzero** [comment]
Reopening since we moved it to weekly but it stills fails

**Comment by redshiftzero** [comment]
this target is now passing: https://circleci.com/gh/freedomofpress/securedrop/31919
