### ISSUE TITLE
[v3 onion migration] add detailed documentation for administrators

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4632]
We should add a page in our documentation that describes the v3 migration steps and our recommendations: use v3 only for new installs on 1.0.0, otherwise enable v3 alongside v2 and disable v2 once all journalist/admins users are migrated over to v3 and your landing page has had the v3 onion URL only for $some_reasonable_amount_of_time. 

This ticket should not be done until the other tasks in #2951 are completed. 

Here's some expected content of the docs:

### How admin users will need to upgrade

First, you’ll need to upgrade your servers and then your admin workstations.

1. Run `securedrop-admin sdconfig` and set new v3 variable to True
2. Run `securedrop-admin` install.
3. This will create new `aths*.private_auth` files and an `app-ths-source-v3` file in `install_files/ansible-base`.
4. Re-run `securedrop-admin tailsconfig`. 
5. Copy the ths files to other admin workstations, and run `securedrop-admin tailsconfig` there.

Next, you’ll need to update your landing page and coordinate with journalists to ensure their workstations are updated. If you use HTTPS, before updating your landing page you should acquire a new certificate with your v3 details.

### How journalist users will need to upgrade

You’ll need to get update Tor onion service files from your admin. Run `securedrop-admin tailsconfig`. 

### How source users will need to upgrade

They will use the v3 onion on the landing page.

**Comment by redshiftzero** [comment]
@rmol pointed out there are a lot of places to update here:

* backup/restore guide (and we have yet to test backup/restore on v3)
* multiple places in the installation guide
* the development docs (when it comes to staging)

in addition we _also_ need a topic guide explaining the update process. The person implementing this can take each task in a separate PR (I recommend beginning with the upgrade topic guide) such that it's a smaller task.

**Comment by zenmonkeykstop** [comment]
D'oh, I missed that comment about separate PRs. Can split if required but right now it's all in one big one with the exception of backup/restore because not sure how that's gonna work.
