### ISSUE TITLE
In journalist interface, create comprehensive filters when JS is enabled

### ISSUE THREAD

**Issue by Hainish** [freedomofpress/securedrop#464]
We currently allow javascript use in the journalist interface, while gracefully degrading when js is disabled.  For journalists that have JS enabled, we should create a comprehensive filter bar above the list of sources.  This expands out the filter box we have currently for source names.  We can add extra criteria: {starred, unstarred}, {has unread docs, doesn't}.

This is also useful for the list of submissions.  We can filter by {read, unread}, {starred, unstarred}, {msgs, docs}

**Comment by redshiftzero** [comment]
This was implemented back in #465, so closing.

**Comment by redshiftzero** [comment]
Whoops, just kidding. Looks like it didn't get merged! Reopening this and tagging with Reading Room

**Comment by eloquence** [comment]
We discussed this issue in our old issue review yesterday, and I also brought it up with @huertanix from the newsroom team today. We don't see that this part of the UI currently needs work, but of course we'll continue to look for usability and workflow improvements. Closing this issue for now.

**Comment by dachary** [comment]
@Hainish feel free to re-open at any time if you still think this important ;-)
