### ISSUE TITLE
CI failure: On updating packages for staging-rebase

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#4640]
## Description

https://circleci.com/gh/freedomofpress/securedrop/31408?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## Steps to Reproduce

All PRs are right now failing on the same.

## Expected Behavior

The staging-rebase CI job should pass.

## Actual Behavior

```
    TASK [common : Check whether tor will be upgraded.] ****************************
    ok: [app-staging]
    ok: [mon-staging]
    
    TASK [common : Hold tor package to prevent upgrade breaking SSH connection.] ***
    
    TASK [common : Perform safe upgrade to ensure all the packages are updated.] ***
make: *** [ci-go] Terminated
Warning: Permanently added '35.230.107.161' (ECDSA) to the list of known hosts.

scp: /home/sdci/securedrop-source/junit/*xml: No such file or directory
Too long with no output (exceeded 20m0s)
```

**Comment by kushaldas** [comment]
I could not reproduce it locally, wondering anything to do with Google Cloud.

**Comment by emkll** [comment]
Updating the timeout to 30m does not resolve: https://github.com/freedomofpress/securedrop/pull/4636/commits/75c1e843c275aa2fdc9469662d9eba6379a1b015

Based on local testing, the upgrade process takes ~10 minutes or so

**Comment by conorsch** [comment]
See also #4637, which indicates we don't want to upgrade the base box without further testing. I consider this issue blocked by resolution of #4637.

**Comment by eloquence** [comment]
This has been resolved for a while, see recent `staging-test-with-rebase` runs, e.g.:
https://circleci.com/gh/freedomofpress/securedrop/31642?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
