### ISSUE TITLE
[docs] Strengthen printer usage recommendations throughout 

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4646]
The [latest version of the Journalist Guide](https://docs.securedrop.org/en/latest/journalist.html#encrypting-and-moving-documents-to-your-everyday-workstation) addresses many issues with previous versions (e.g., it makes malware risks more explicit), but it still is fundamentally structured on the assumption that we want journalists to move files off the SVS in electronic form.

We should much more clearly highlight printing as preferred method to get documents off the SVS. Compared with all other methods, it has the strongest overall security properties (especially because it virtually eliminates malware risks). It is obviously not a fit for all use cases, but for documents that can be managed in print form, we want to encourage news organizations to consider it wherever possible.

We should also strongly encourage purchase of a non-WiFi-enabled, Tails-compatible printer in the [pre-install hardware checklist](https://docs.securedrop.org/en/latest/checklists/pre_install_hardware.html), and strengthen other references (e.g., right now we only say that "it is often useful" to have a printer).

**Comment by ninavizz** [comment]
(cough) a BLACK AND WHITE LASER, un-networked printer, too. 

http://seeingyellow.com/
