### ISSUE TITLE
virtualenv needs to be activated before adding users via manage.py 

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4656]
## Description

The documentation to add users needs to be updated after the recent change to use a virtualenv

## Steps to Reproduce

Follow instructions in https://docs.securedrop.org/en/latest/create_admin_account.html to create an account

## Expected Behavior

User account is made

## Actual Behavior

Python dependencies cannot be found

## Comments

We can instruct the user to activate the virtualenv first (`source /opt/venvs/securedrop-app-code/bin/activate`)

**Comment by zenmonkeykstop** [comment]
Should the venv activation maybe be wrapped in a script or added in the `www-data` user's `.profile`? ( Not sure they have one apart from system default).

**Comment by conorsch** [comment]
Wrapper script is a fine idea here, it can handle:

1. sourcing the venv
2. managing user (e.g. `su`ing to www-data)
3. passing args to `manage.py`

Of course we'd still need to update the docs to map. Makes sense to call the script `securedrop-admin`, although we already have such as script in the Tails environment, and potentially in a Qubes Workstation environment (#51), as well.

**Comment by kushaldas** [comment]
The best way is to point the executable to the  inside of virtualenv. This is what happens by using entrypoints in `setup.py`.

**Comment by rmol** [comment]
To use an entry point, wouldn't we need what's now in `/var/www/securedrop` installed in `site-packages` under `/opt/venvs/securedrop-app-code`, so that `manage.py` is on `sys.path`?

**Comment by kushaldas** [comment]
We can just add some sys.path entries for that. Have to verify the change though.

**Comment by rmol** [comment]
I've tested that the changes from #4713 (options 1+3 above) do solve the problem; having the virtualenv python in the shebang line of manage.py makes it work. 

I think getting entry points working deserves a separate post-1.0.0 ticket.

**Comment by redshiftzero** [comment]
@rmol tested this, so closing
