### ISSUE TITLE
Google Authenticator PAM module hasn't been updated, we should change this to pam_oath

### ISSUE THREAD

**Issue by Hainish** [freedomofpress/securedrop#466]
The Google Authenticator PAM module has been cited as a security risk by the audit.  We should start using pam_oath from the OATH Toolkit.

**Comment by garrettr** [comment]
Clarification: the vulnerability was in `google-authenticator-apache-module`, not in the PAM module. We do not know of any current vulnerabilities in the PAM module.

We ultimately implemented two-factor authentication in the Document Interface in #522 to replace the apache module. We still use the PAM module to add two-factor authentication for SSH.
