### ISSUE TITLE
testinfra: facilitate running a single test or single file of tests 

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4674]
## Description

As a developer it's nice to be able to run a single test or single file of tests. It would be great to enable this for our testinfra test suite which is used for testing our staging environment: https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html#running-the-config-tests

**Comment by conorsch** [comment]
Two possible methods:

1. edit the `verifier` block in `molecule.yml` for a given scenario to include `k: <name_of_test_to_run>`
2. set `PYTEST_ADDOPTS="-k <name_of_test_to_run"` on the verifier invocation

The latter seems most straightforward, since it doesn't involve a diff.
