### ISSUE TITLE
Ensure torrc munging in postinst does not conflict with changes introduced for v3 onion services

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4676]
## Description

As part of #2951 , we should ensure that some postinst changes for torrc config do not affect the migration. We could also remove those postinst changes as they should no longer be necessary for any SecureDrop instance running the latest version of tor we are mirroring (0.3.5.9)

https://github.com/freedomofpress/securedrop/blob/9af7898c69caa8f265ee12a122c3ea2921ceff98/install_files/securedrop-config/DEBIAN/postinst#L56-62

**Comment by conorsch** [comment]
> We could also remove those postinst changes as they should no longer be necessary for any SecureDrop instance running the latest version

That'd certainly be my preference, to remove the postinst torrc munging logic altogether. In the future, we should be careful to assign such logic with dpkg version restrictions in the configure blocks.
