### ISSUE TITLE
Document SecureDrop package dependencies

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#468]
We should create a document that lists SecureDrop dependencies and explains what the packages are and how we are using them. This is useful to have even though the deb packages install dependencies automatically. @ageis suggested we make this list a part of a readme.md or dependencies.md.

**Comment by conorsch** [comment]
This is mostly resolved by our Ansible setup, which handles package installation and configuration of the various services, such as Tor and Apache. The associated task lists are liberally commented, at least in the develop branch, for those interested in exploring the choices made for configuring the deployment. 

Down the road we may rethink how SecureDrop is deployed, but the present documentation, as well as copious GitHub issues, are sufficient for those interested in exploring the architecture. 

> document should also explain how one can debug each component (e.g. AppArmor, where to find the log file(s), and so on)

Specifically, see:

* [OSSEC alerts | Troubleshooting](https://docs.securedrop.org/en/stable/ossec_alerts.html#troubleshooting)
* [Useful logs](https://docs.securedrop.org/en/stable/logging.html)
* [Generating AppArmor profiles for Tor and Apache](https://docs.securedrop.org/en/stable/development/apparmor_profiles.html)
* [SecureDrop apt repository docs](https://docs.securedrop.org/en/stable/development/apt_repo.html)

We _could_ be more explicit in terms of the Python dependencies for the application code, but most of those includes are self-explanatory, or in the process of being refined (e.g. #1306, #1379).
