### ISSUE TITLE
last_updated timestamp should be updated when a reply is sent

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4682]
The `last_updated` timestamp for a source is currently only updated when the source performs an action (upload a file or message). It should also be updated when a journalist performs an action (sends a reply) to follow the common conversational pattern where any activity by either party "bumps" the conversation to the top (sources [are sorted](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/journalist_app/main.py#L67) by `last_updated` in the Journalist Interface). This is also relevant to the SecureDrop Client, where we want to show the timestamp of the most recent activity for a source in the conversation view.

**Comment by eloquence** [comment]
I've flagged this "needs discussion" as we want to tread a bit carefully here. Do we lose something important if we alter this behavior? May journalists _specifically_ be interested to know the last activity from a source, and want this timestamp to be preserved regardless of their own interactions with the source? Will it be confusing in the *Journalist Interface* if replying to a source bumps it to the top?

My intuition is that bumping the timestamp for all actions is the more intuitive behavior (it's a bit mysterious in the UI right now what the timestamp represents), but it may be a good idea to at least do some informal outreach before altering this behavior.

**Comment by redshiftzero** [comment]
we should add another field because the `last_updated` field is used by the journalist notifications (to determine if any sources have submitted in the last 24 hours), updating this when journalist send replies will cause spurious alerts indicating that SecureDrop should be checked.

**Comment by eloquence** [comment]
Thanks, that makes sense, and gives us the ability to decouple client and Journalist Interface behavior. Closing this issue and re-filing for clarity.
