### ISSUE TITLE
[docs] the workstation backup docs' instructions for mounting persistent volumes are not valid for Tails 3.15

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#4684]
## Description

The documentation at https://docs.securedrop.org/en/stable/backup_workstations.html#preparing-the-backup-device instructs the user to mount the PV to be backed up via Nautilus. Currently, if you attempt to mount a Tails PV via Nautilus it unlocks the encrypted volume but fails to mount it with an `Operation cancelled` message.  The volume can still be mounted via the `Disks` utility. 

## Steps to Reproduce

in Tails 3.15 or greater,
- Insert another Tails stick with a persistent volume and click the volume's entry in Nautlius' left-hand panel
- enter the volume's passphrase and click `Unlock`

## Expected Behavior
 The volume is unlocked and available in Nautilus.

## Actual Behavior
An `Operation cancelled` error is displayed and the volume's entry is no longer listed in Nautilus.

## Comments
This is most likely an upstream Tails issue, but one workaround that is worth adding to the docs is to use the `Disks` utility to mount the volume. If you open `Disks` and click on the USB device's listing, you can see that the LUKS volume has been unlocked, just not mounted. Selecting the unlocked volume (the volume displayed *under* the encrypted volume) and clicking the play button mounts the volume and displays it in Nautilus with the correct name.

**Comment by rocodes** [comment]
Sure, can do

**Comment by rocodes** [comment]
See https://redmine.tails.boum.org/code/issues/16789 -- good news, fix committed :)

**Comment by rocodes** [comment]
Happy to report this does appear to be fixed by 3.16.

**Comment by nebelsprachen** [comment]
@eloquence I think this issue can be closed? Does any work remain for it?

**Comment by emkll** [comment]
Thanks @joaedwar and @rocodes , this can be closed!
