### ISSUE TITLE
We should run pip-compile with --allow-unsafe

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#4686]
## Description

Recent versions of `pip-tools` [add warnings when compiling requirements with `--generate-hashes` could result in uninstallable output](https://github.com/jazzband/pip-tools/pull/814). In our requirements files, we're getting these about `setuptools`, which `pip-tools` considers "unsafe" and refuses to hash. This means that we might not be able to update requirements in a virtualenv containing a version of `setuptools` too old to satisfy a requirement's new dependencies. Development virtualenvs can just be rebuilt, but this could break admin virtualenvs in the field.

We can persuade `pip-tools` to hash `setuptools` by adding the `--allow-unsafe` option wherever we invoke `pip-compile --generate-hashes`. This should allow trouble-free pip updates, and seems to be [safe according to at least one pypa developer](https://github.com/pypa/pip/issues/6459), though `pip-tools` [decided to be conservative and stop at the warnings](https://github.com/jazzband/pip-tools/issues/806).

**Comment by emkll** [comment]
Progress was made towards this issue in #4890. A [review](https://github.com/freedomofpress/securedrop/pull/4890#issuecomment-540175740) noted that it was incomplete: We should pin setuptools in https://github.com/freedomofpress/securedrop/blob/f746182fb625cf2e1f43bf1be419ef9428c12266/admin/requirements.txt#L165

Until then, the Admin virtualenv will use the pip-provided setuptools

**Comment by emkll** [comment]
closed via https://github.com/freedomofpress/securedrop/pull/5159
