### ISSUE TITLE
Include a style guide for contributors

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#47]
We should have consistent coding styles.

**Comment by garrettr** [comment]
This is still an issue. We've had several pull requests come through recently that have fixed a number of PEP8 violations, which has helped. I think we should re-orient this issue to not only recommend a consistent coding style, but to enforce it. Therefore, the requirements for this issue should be:

- [ ] Make coding style adherence a requirement for contribution, and document the requirement in our contribution guidelines (`docs/develop.md`).
- [ ] Enforce this requirement via our CI pipeline. For example, Let's Encrypt checks code style as part of their [Travis automated tests](https://github.com/letsencrypt/lets-encrypt-preview/blob/master/.travis.yml#L20).
