### ISSUE TITLE
Document how to patch kernel with grsecurity

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#470]
The very basic [SecureDrop](https://github.com/freedomofpress/securedrop) guide mentions the need for Ubuntu servers with grsec kernel patches installed, but the [Ubuntu configuration guide](https://github.com/freedomofpress/securedrop/blob/develop/docs/ubuntu_config.md) says those instructions are outside the scope of the guide. Our documentation should ideally explain all the steps that we take to install SecureDrop, including installing grsec kernel patches.

**Comment by garrettr** [comment]
The latest version of this documentation is actually in the Github wiki for the new (separate) grsec repo: https://github.com/freedomofpress/grsec/wiki/Build-Instructions. We might want to consider moving those docs back into that repo (but that issue should be filed against that repo, not here).

**Comment by garrettr** [comment]
I added an issue to move the instructions back to `build.md` in https://github.com/freedomofpress/grsec/issues/1.
