### ISSUE TITLE
restore script needs updating to python 3

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4731]
## Description

`securedrop/install_files/ansible-base/roles/restore/files/restore.py` needs updating to python 3

**Comment by rmol** [comment]
There are other shebang lines that should be updated, among them of course `backup.py`. They could all be changed to use `/opt/venvs/securedrop-app-code`, which would ensure the virtualenv never has to be activated in production to avoid confusing failures, but that would pose a problem for developers invoking them while using custom virtualenvs. I think making production use less involved should take priority; if devs need to run things without using the Makefile targets or the dev container, they can specify their python on the command line.
