### ISSUE TITLE
Add grsec-patched kernel to FPF package repository

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#474]
To ensure that deployed instances are always using the latest stable kernel and grsecurity, we should keep an up-to-date version in our package repository that can be installed with unattended-upgrades. The grsecurity mailing list seems to be dead, so we will want to keep an eye out for changes to the download page (this can easily be scripted). This grsec-patched kernel should remain optional to install until we have tested it on more hardware configurations.

**Comment by garrettr** [comment]
The grsecurity kernel is included in the [FPF package repository](apt.freedom.press) as of the 0.3 release. The documentation for building this kernel is in the now-separate [grsec repo](https://github.com/freedomofpress/grsec) and the process for updating the package repository for new releases of the grsecurity kernel is documented in our [release procedures](https://securedrop.hackpad.com/SecureDrop-Release-Procedures-3HpUYU2Hnwf).
