### ISSUE TITLE
[1.0.0] New SecureDrop logo is not present on source and journalist interfaces on install 

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4753]
## Description

A short summary of the issue.

## Steps to Reproduce

- Install SecureDrop on 1.0.0-rc2
- Observe old logo is used on both the source and journalist interface

## Expected Behavior

The new logo should be used

## Actual Behavior

![old-logo](https://user-images.githubusercontent.com/15223328/64367809-ea30b880-cfe6-11e9-96d3-a6013e01b403.png)
![old-logo-JI](https://user-images.githubusercontent.com/15223328/64367810-eac94f00-cfe6-11e9-9d09-3ccfbd969881.png)

## Comments

The logo is marked as a conffile, which also means it probably won't change for orgs that use the default logo in an upgrade scenario: https://github.com/freedomofpress/securedrop/blob/develop/install_files/securedrop-app-code/debian/conffiles#L1

**Comment by emkll** [comment]
Good catch, seems likely that it was left by accident during at build-time.

**Comment by rmol** [comment]
Yep. It's included in `.rsync_filter`: `include static/i/**`. We'll want to exclude it.

The logo is copied out of the way then restored in `preinst`/`postinst`, so if that's what's in place during the upgrade, it will be kept.
