### ISSUE TITLE
Spinning up staging env per docs highly likely to fail due to builder image updates

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4764]
The docs [currently state](https://docs.securedrop.org/en/stable/development/virtual_environments.html) that you should create the debs for your staging environment using `make build-debs`. That command will fail if the builder image hash needs to be updated due to security updates, which is highly likely to be the case. 

If that is the intended behavior for `make build-debs`, we should either recommend the use of `make build-debs-notest` or provide other instructions that help developers avoid this situation when setting up a staging environment.

**Comment by zenmonkeykstop** [comment]
The command fails, but after the debs are created, so you can still proceed. But it's definitely not a good look.
