### ISSUE TITLE
Tails 4 desktop shortcuts not showing up

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4771]
## Description

After tailsconfig on Tails 4 beta, .desktop files are not working on the Desktop

## Steps to Reproduce

1. Install the Tails 4 beta: https://tails.boum.org/news/test_4.0-beta2/
2. Set up persistence
3. Clone the SecureDrop repo, install SD (or copy over your keys/creds/`site-specific`)
4. From `~/Persistent/securedrop`, run `./securedrop-admin tailsconfig`

## Expected Behavior

Desktop shortcuts appear on desktop to the source and journalist interfaces, when clicked they open Tor Browser

## Actual Behavior

Desktop shortcuts appear, but they open in Text Editor when clicked

## Comments

Needs investigation, note we had a similar issue back when we updated to Tails 3.3: #2586

Related to #4669

**Comment by zenmonkeykstop** [comment]
Some notes: the situation has changed a little in Gnome 3.3 (buster) vs 3.2 (stretch). Desktop icons are disabled by default and reenabled via an extension: 
https://gitlab.gnome.org/World/ShellExtensions/desktop-icons

setting `metadata::trusted` via `gio` directly isn't working for me, but there is a right-click menu item **Allow Launching** that makes an icon launchable. The code behind it is here:

https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/blob/master/fileItem.js#L528

probably the best bet is to replicate any new functionality there  in `securedrop_init.py` along with what's already being set for Tails 3.*.
