### ISSUE TITLE
Playbook stalls when switching from SSH-over-Tor to SSH-over-LAN.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#4779]
## Description

During the 1.0.0-rc2 QA case:
```
- [ ] Now disable SSH over Tor, rerun `securedrop-admin install` and `./securedrop-admin tailsconfig`:
```
The install playbook stalls on the task "Force a reboot conditionally, when tor_over_ssh status changed".  The reboot happens, but afterward the servers are still accessible over Tor and not via Direct IP.

## Steps to Reproduce

- installed a v2 production system
- enabled v2+v3 via a second `./securedrop-admin install`
- disabled ssh-over-tor via `sdconfig` and a third `install`

## Expected Behavior
`install` completes successfully and servers are available via direct IP after `tailsconfig` has run.

## Actual Behavior
- `install` stalls at task mentioned above.
- if admin runs `install` a second time, SSH-over-Tor is also disabled, locking them out of the servers (because the listen address for sshd changes and the ssh/sshv3 hidden services are not added in `sshd_config` and `torrc` respectively.)

**Comment by emkll** [comment]
I believe this is fixed in https://github.com/freedomofpress/securedrop/pull/4794, due  the changes to the reboot task
