### ISSUE TITLE
supervisor is using python 2

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4783]
## Description

Python 2 is used by supervisor on 1.0.0-rc2 installs

You can see this by running `ps aux | grep supervisor` or `ps aux | grep python` (I discovered this during exploratory testing where I moved the python 2 interpreter `mv /usr/bin/python /usr/bin/pythontemp` before running the QA checklist to see if any functionality broke due to dependency on Python 2)

## Steps to Reproduce

Install on 1.0.0-rc2

## Expected Behavior

Python 2 is not required for any SecureDrop functionality

## Actual Behavior

Python 2 is used by supervisor

## Comments

Here's my initial investigation of this: 
* there is a supervisor release on PyPI that supports Python 3:  https://github.com/Supervisor/supervisor/issues/1060#issuecomment-480438643
* but we install from apt (supervisor is a dependency of the securedrop-app-code deb) and the supervisor package in xenial https://packages.ubuntu.com/xenial/admin/supervisor is running on an old version that is python 2 only

**Comment by redshiftzero** [comment]
OK so after discussion async @kushaldas is going to discuss this with a colleague tomorrow. If we don't get clarity after that (to understand what the policy is with Xenial LTS packages that currently require python 2) we'll file upstream.

In my view any dependency we are using in production SecureDrop instances that currently _requires_ the use of Python 2 we need to do one of the following for:

* Verify that upstream will be updating to a version requiring Python 3 instead of Python 2 well in advance of the Python 2 EOL
* Package it ourselves, or see if we can install using e.g. pip instead of apt
* See if we can remove the requirement for the tool

**Comment by eloquence** [comment]
Per chat w/ @redshiftzero removing from 1.0.0 milestone (we won't resolve this by next week and it's not a release blocker), but the above follow-up should be done at a high priority.

**Comment by rmol** [comment]
The `supervisor` package is in the `universe` section, so I'd guess that Ubuntu won't be replacing it with a Python 3 version.

It would not be difficult to install it in our virtualenv. We could start it with a `@reboot` cron job under `www-data`, so losing systemd oversight shouldn't be a problem: worst case it would be restarted with the daily reboot.

I suppose we could just run the rq worker and requeuer programs the same way; it's nice to have supervisor controlling them, but it should be possible to remove it altogether.

**Comment by eloquence** [comment]
Plan of record:
- @rmol to complete systemd investigation & post update here
- @redshiftzero to check in upstream re: Python 3 EOL plans

**Comment by redshiftzero** [comment]
upstream ticket: https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1844802

**Comment by redshiftzero** [comment]
Let's just go ahead with the change in #4855 since the upstream maintainer has not responded

**Comment by redshiftzero** [comment]
supervisor 4 package now exists: https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1844802, now just determining which ubuntu releases it will be in
