### ISSUE TITLE
Restoring from a v2 backup on an instance with v3 enabled breaks v3 onion services

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#4786]
## Description

When a v2 backup is used to restore an instance that has v3 services enabled (either v3 only or v2+v3), the v3 onion services are no longer enabled on the app server. 

## Steps to Reproduce

on prod vms or hardware:

- install a v2-only instance
- take a backup
- use `sdconfig` and `install` to enable v3
- restore from the v2backup 

## Expected Behavior
- data is restored, v3 services are still accessible

## Actual Behavior
- restore hangs when tor is restarted on the server, v3 services are no longer configured on the app server

## Comments
The backup tarball includes /etc/tor/torrc, which contains the onion service definitions. When it overwrites the v3 torrc, it breaks the services.

One approach to address this might be to break the onion service definitions out into files that are included in `torrc` via  %include. For example,a structure like:
```
/etc/tor/torrc.d/
                    10-v2-definitions.conf
                    20-v3-definitions.conf
```
and a line like:
```
%include /etc/tor/torrc.d
```
in the `torrc` proper.

Restoring from a v2 tarball would overwrite `/etc/tor/torrc.d/10-v2-definitions.conf` but shouldn't affect other files in the same directory.

**Comment by eloquence** [comment]
Noting for the record: For 1.0.0, we've agreed that graceful and non-destructive failure is acceptable in this scenario. (Graceful: ideally include suggested remediation steps the admin can take, e.g., revert back to v2 before restoring backup; non-destructive: fail early before any modifications to the system state.)
