### ISSUE TITLE
 ssh-over-tor and v2/v3 service migration test scenarios

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#4804]
## Overview
This is a tracking issue for manual tests for onion service migration scenarios for Securedrop 1.0.0, including potential changes to the SSH-over-Tor setting.

In each scenario below, install to prod VMs or HW with the settings listed, then update settings via `./securedrop-admin sdconfig`, `./securedrop-admin install`, and `./securedrop-admin tailsconfig`.

The scenario passes if the Source and Journalist desktop shortcuts work and use the appropriate service URL, and `ssh app` and `ssh mon` also work with the expected values in `~/.ssh/config/`.

Do not attempt all scenarios! Pick a couple and claim them with a comment below, then check them off if they pass, or flag it in your comment if they don't. Scenarios are listed roughly in order of relative probability. Most live instances likely use the default SSH-over-Tor option, and switching SSH options after an install is unlikely. Individual cases are chained together to reduce the number of scenarios while keeping the effort required for each manageable.

### Scenario 1 (@kushaldas):
- [x] Install (ssh-over-tor, v2) and update to (ssh-over-tor, v2+v3)
  - [x] verify shortcuts and ssh
- [x] Next, update to (ssh-over-tor, v3)
  - [x] verify shortcuts and ssh

### Scenario 2 (@kushaldas):
- [x] Install (ssh-over-tor, v2) and update to (ssh-over-tor, v3)
  - [x] verify shortcuts and ssh
- [x] Next, update to (ssh-over-tor, v2+v3)
  - [x] verify shortcuts and ssh

### Scenario 3 (@emkll):
- [x] Install (ssh-over-lan, v2) and update to (ssh-over-lan, v2+v3)
  - [x] verify shortcuts and ssh
- [x] Next, update to (ssh-over-lan, v3)
  - [x] verify shortcuts and ssh

### Scenario 4 (@emkll):
- [x] Install (ssh-over-lan, v2) and update to (ssh-over-lan, v3)
  - [x] verify shortcuts and ssh
- [x] Next, update to (ssh-over-lan, v2+v3)
  - [x] verify shortcuts and ssh

### Scenario 5 (@conorsch):
- [x] Install (ssh-over-tor, v2) and update to (ssh-over-lan, v2)
  - [x] verify shortcuts and ssh
- [x] Next, update to (ssh-over-tor, v2)
  - [x] verify shortcuts and ssh

### Scenario 6 (@emkll ):
- [x] Install (ssh-over-tor, v2+v3) and update to (ssh-over-lan, v2+v3)
  - [x] verify shortcuts and ssh
- [ ] Next, update to (ssh-over-tor, v2+v3)
  - [ ] verify shortcuts and ssh

### Scenario 7 (@zenmonkeykstop):
- [x] Install (ssh-over-tor, v3) and update to (ssh-over-lan, v3)
  - [x] verify shortcuts and ssh
- [x] Next, update to (ssh-over-tor, v3) **Failed initially with `fatal:failed to fork` error on app from `aptitude safe-upgrade` during "Performing safe update.." task. No obvious resource hogs, install completed after app was rebooted.**
  - [x] verify shortcuts and ssh

### Scenario 8 (@emkll ):
- [x] Install (ssh-over-tor, v3) and update to (ssh-over-lan, v2+v3)
  - [x] verify shortcuts and ssh
- [x] Next,  update to (ssh-over-tor, v3)
  - [x] verify shortcuts and ssh

### Scenario 9 (@emkll ):
- [x] Install (ssh-over-tor, v2+v3) and update to (ssh-over-lan, v3)
  - [x] verify shortcuts and ssh

### Scenario 10 (@zenmonkeykstop ): 
- [x] Install (ssh-over-tor, v2) and update to (ssh-over-lan, v2+v3)
  - [x] verify shortcuts and ssh
- [x] Next, update to (ssh-over-tor, v3) **Failed initially with fatal:failed to fork error on app from aptitude safe-upgrade during "Performing safe update.." task. No obvious resource hogs, install completed after app was rebooted.**
  - [x] verify shortcuts and ssh

### Scenario 11 (@conorsch):
- [x] Install (ssh-over-tor, v2) and update to (ssh-over-lan, v3)
  - [x] verify shortcuts and ssh

### Scenario 12 (@rocodes):
- [x] Install (ssh-over-lan, v2) and update to (ssh-over-tor, v2+v3)
  - [x] verify shortcuts and ssh

### Scenario 13 (@rocodes):
- [x] Install (ssh-over-lan, v2) and update to (ssh-over-tor, v3)
  - [x] verify shortcuts and ssh

**Comment by conorsch** [comment]
Scenario 5 complete (updated above), no problems, moving on to scenario 11.

**Comment by zenmonkeykstop** [comment]
Ye are scenario-demolishing machines! @kushaldas I can take #10, haven't done my share yet.

**Comment by conorsch** [comment]
Scenario 11 complete, no problems. Thanks for preparing the wonderfully clear test plan, @zenmonkeykstop!

**Comment by rocodes** [comment]
**Scenario 13** pass, no problems. Thank you @zenmonkeykstop !

**Comment by zenmonkeykstop** [comment]
**Scenario 7** done. Ran into reproducible issue on second upgrade, but it wasn't related to the ssh-over-tor toggle, looked more like memory constrains on the VMs

**Comment by zenmonkeykstop** [comment]
**Scenario 10** done. Same issue on second upgrade.

**Comment by zenmonkeykstop** [comment]
Resolving - release is done, thanks all for your efforts!
