### ISSUE TITLE
Forensic analysis of TBB post SD-leak

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#481]
I did a [forensic analysis of the Tor Browser Bundle (PDF)](https://research.torproject.org/techreports/tbb-forensic-analysis-2013-06-28.pdf) last year, but never tested a scenario in which a user uploads documents to a site. It would be good to redo the analysis with this specific scenario in mind.

**Comment by eloquence** [comment]
We discussed this issue in our old issue review today. Our current policy is that auditing Tor Browser Bundle is beyond the scope of SecureDrop development, though of course we are keeping an eye on Tor's security practices. Closing this issue.
