### ISSUE TITLE
Create temporary .onion sites to upload documents to

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#482]
In some cases, it could make sense to set up a temporary .onion for a source to upload documents to as opposed to uploading directly to the more permanent site. The idea is that the .onion site would disappear as soon as documents have been uploaded. At some point, we might want to discuss whether implementing this functionality in SecureDrop makes sense.

**Comment by flamsmark** [comment]
I don't understand the advantage conferred by this.

**Comment by eloquence** [comment]
We discussed this issue in our old issue review today. We're not currently anticipating that we'll ever support throwaway .onion links directly in SecureDrop. Sources that are interested in this may wish to consider using OnionShare for the actual file upload, which also avoids size limitations of SecureDrop. We may make more explicit reference to OnionShare in the future in SecureDrop pages / docs. Closing this issue.
