### ISSUE TITLE
Update SecureDrop grsec kernels to 4.14

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4843]
## Description

grsecurity will be ending 4.4 series support at the end of this year. We should therefore move to the 4.14 kernel series for SecureDrop, which will provide further hardware support, and benefit from upstream security improvements. grsecurity will be supporting 4.14 through 2021.

**Comment by eloquence** [comment]
Given the hardware testing required, we decided against squeezing this into 1.1.0, but we'll likely need to do a point release soon after -- we don't want to cut it too close for the EOL date.

**Comment by eloquence** [comment]
During the 10/23-11/6 sprint, we've agreed to:
- Create a new 4.14 config and test it locally
- Upload new test kernels to our apt test repository
- Test the kernels on all supported hardware (Dell PowerEdge R620, HP Proliant DL385 G7, 2014 Mac Mini, Intel NUC 5CPYH, Intel NUC 7i5BNH)
- Report and prioritize issues

Dell/HP testing is blocked on shipment of the testing hardware to an undisclosed location.
