### ISSUE TITLE
Extend testinfra to run a subset of tests against production

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#4846]
## Description

Currently release QA involves manually running a series of server-side tests to verify their configurations (Pax flags, apparmor, iptables etc). It would reduce QA time and the risk of errors if those tests were run automatically. The testinfra tests used in staging could be extended for this purpose.

## User Research Evidence

Discussed with @redshiftzero, some preliminary research done a few sprints back.

## User Stories
As a SecureDrop tester, I want to be able to easily verify the configuration of production systems.

**Comment by redshiftzero** [comment]
definitely agree, but duplicate of #4216?

**Comment by zenmonkeykstop** [comment]
Yup, I couldn't find the previous ticket, will nuke this one.
