### ISSUE TITLE
Move to Tor 0.4.1.x stable series

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4848]
## Description

In #4658, we moved to Tor's 0.4.0.x release series, moving on the stable instead of LTS releases. Recall that Tor maintains the stable debian packages and we just publish their packages on our apt server for distribution to SecureDrop instances.

The Tor 0.4.0.x series will [EOL in Feb 2020](https://trac.torproject.org/projects/tor/wiki/org/teams/NetworkTeam/CoreTorReleases#Listofreleases), so we should migrate onto 0.4.1.x now that stable releases in that series are available. Most recently [0.4.1.6 was released](https://blog.torproject.org/new-release-tor-0416), so in 1.1.0 or 1.2.0 we should move instances to at least that version (packages are wip by tor packagers at the time of this writing but will be done in time for 1.1.0).

The implementor of this ticket should verify that the version of the release they are updating us to is the most recent in the 0.4.1.x series.

**Comment by emkll** [comment]
As of 1.0.0, we tracking the 0.4.1.x series #4728 . I propose we update to 0.4.1.6 for 1.1.0 to close out this ticket.
