### ISSUE TITLE
investigate using I2P as an additional layer of protection and/or an alternate option to Tor.

### ISSUE THREAD

**Issue by aoighost** [freedomofpress/securedrop#485]
Tor has some flaws involving the architecture of the network where the fastest nodes are always given priority. It has recently come out that the US Government has been funding fast Tor nodes. There is the possibility that Tor may not be enough to protect those using securedrop. I would like to suggest investigating I2P as a possible additional layer, or alternate implementation, as both a safety and a fallback in event Tor becomes compromised.

**Comment by redshiftzero** [comment]
I definitely see the motivation here, however Tor has received _significantly_ more vetting and research, and supporting both Tor and I2P is a significant burden for us that I don't think is worthwhile for any security benefit (through defense in depth) we might get. We are happy to re-evaluate at a later date, but I'm going to close this for now.
