### ISSUE TITLE
Graphical updater "is already running" dialog during late stages of the update process

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4878]
## Description

The graphical updater briefly shows an "is already running" dialog during the last stages of the process. The dialog can be dismissed and has no negative consequences.

Tested on Tails 3.16.

## Steps to Reproduce

Perform a full graphical update using the graphical updater, with the Tails admin password set.

## Expected Behavior

The graphical update completes without any unusual messages.

## Actual Behavior

An "already running" dialog briefly appears towards the end of the process.

**Comment by zenmonkeykstop** [comment]
This happens because the network hook is now always triggered by tailsconfig, rather than only on a change in the network hook script (consequence of v3 services.)

If it's a problem, probably the easiest thing to do would be to have the second copy of securedropupdater just exit silently.
