### ISSUE TITLE
Update docs for Tails 4

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4893]
We want to 
- review all references in the documentation for accuracy against Tails 4/SecureDrop 1.1.0
- prioritize and update the highest priority issues (e.g., incorrect instructions or screenshots that are confusing) for 1.1.0.

This includes but is not limited to Tails references in the following sections:
- [Journalist Guide](https://docs.securedrop.org/en/release-1.0.0/journalist.html) - a lot of very specific Tails guidance here, e.g., regarding use of VeraCrypt
- [Printer setup docs](https://docs.securedrop.org/en/release-1.0.0/tails_printing_guide.html)
- [Install docs](https://docs.securedrop.org/en/release-1.0.0/install.html) ("Additional software" prompt)
- [SVS setup docs](https://docs.securedrop.org/en/release-1.0.0/set_up_svs.html)
- [Submission Key generation](https://docs.securedrop.org/en/release-1.0.0/generate_submission_key.html)
- [Network firewall setup](https://docs.securedrop.org/en/release-1.0.0/network_firewall.html) (e.g., "unsafe browser" use, network config on the AWS)

We should also sanity check:

- [Backup docs](https://docs.securedrop.org/en/release-1.0.0/backup_workstations.html)
- [Update docs](https://docs.securedrop.org/en/release-1.0.0/update_tails_usbs.html)
- [YubiKey docs](https://docs.securedrop.org/en/release-1.0.0/yubikey_setup.html)

**Comment by eloquence** [comment]
#4937 updates the printer and SVS docs, and I've verified that the VeraCrypt docs still work. #4942 at least partially updates several other docs, including the Submission Key generation, the network firewall instructions, and the journalist guide. @rocodes, can you confirm if any additional work or due diligence remains to be done on the following?

> Submission Key generation
> Network firewall setup (e.g., "unsafe browser" use, network config on the Admin Workstation)
> Backup docs
> Update docs
> YubiKey docs

**Comment by rocodes** [comment]
Submission key generation: I have screenshots with (slightly) updated UI, although current docs are not incorrect. Yubikey and Update docs I'd still like to review.
