### ISSUE TITLE
Clarify SecureDrop branch naming in dev docs

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#4951]
## Description

Contributors have been tripped up by `develop` being our primary branch, instead of the more common `master`. In our [Setting Up the Development Environment](https://docs.securedrop.org/en/latest/development/setup_development.html) document, we should be clearer that we work on `develop`. It is the default in the freshly cloned working copy, but git command habits or aliases from experience with other projects could result in an inadvertent switch to `master`, causing breakage and confusion.

## User Research Evidence

https://forum.securedrop.org/t/docker-error-in-make-dev-unable-to-find-image-pull-access-denied/1263

**Comment by zenmonkeykstop** [comment]
Let's go one step further, and update master to contain only a README with the single line "THIS IS NOT A PLACE OF HONOUR" and then lock it.

**Comment by eloquence** [comment]
This was clarified via https://github.com/freedomofpress/securedrop-docs/pull/20. It's also worth noting that since this issue was filed, the `master` branch in `securedrop` has been deleted, reducing the risk of confusion.
