### ISSUE TITLE
Update UI/docs consistent with "New Identity" behavior change in Tor Browser 9.0

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4952]
The "New Identity" behavior has changed once again in Tor Browser 9.0. There's now a dedicated button for it:
![New identity button](https://blog.torproject.org/sites/default/files/inline-images/toolbar%20update.png)

So we have to update these instructions:

> Thank you for exiting your session! Please select "New Identity" from the onion button in the Tor browser's toolbar to clear all history of your SecureDrop usage from this device.

And also the relevant portion in the [source guide](https://docs.securedrop.org/en/release-1.1.0/source.html).

**Comment by ninavizz** [comment]
For this upcoming release, let's just update the text and the icon as follows:

>   **Sweep Activity** Click the  “New Identity” `<x>` button in your Tor Browser’s toolbar before you continue. 

Icon art `<x>`, here: —tbd—

For the following release, we should update all flash messaging in the Source UI per discussion in 31 Oct UX meeting. Discussion about those changes should happen in #4967

**Comment by eloquence** [comment]
I would propose the following iteration of your wording:

> **Clear Your Browser Activity:** Click the "New Identity" `<x>` button in your Tor Browser's toolbar before you do anything else.

Reasoning:

1) While I understand the motivation to use "Sweep" to connect the language to the icon, given that this language is not used anywhere else in Tor Browser, I think we should default to a more commonly used (and easier to translate) verb. As far as I can tell, similar functionality is typically called "Clear <x>" in applications, e.g. "Clear browser history". If the Tor team is planning to use "Sweep" then that would change my view.

2) I would go with the longer "Clear Your Browser Activity" to make it obvious that it is a request to the user do something.

3) "Before you continue" is a bit confusing IMO, because this message is shown after logout. "Continue what? I just logged out!"

**Comment by ninavizz** [comment]
1. Tor team doesn't know; Nina:Antonella pow-wow, forthcoming.

2. The possessive introduces a cognitive distraction, but "Clear Browser Activity" is direct and concise. Thank you for the suggestion! :)

3. Ok, touché... so: the user just logged-out, but now we want them to "do this." Why? I don't disagree with your broader flag here, but I don't feel we have an adequate answer between either of us.

Could we code into the SUI a trigger to have it automagically do the "New Identity" thing, or would that require a forbidden script.

**Comment by ninavizz** [comment]
@eloquence ...how do you feel about `moving on`? It acknowledges the user's decision to leave SD, while more clearly framing the ask imho, but I have no idea how it'll translate (or if I'm the only one who likes it in English)...

![image](https://user-images.githubusercontent.com/8262612/68171424-8f550800-ff28-11e9-8775-22219e383b64.png)

**Comment by eloquence** [comment]
"Moving on" is more idiomatic; we'd need to rely on documentation for translators to ensure consistent translation across languages. In terms of how it feels in English, I have a _weak_ preference for "before you do anything else" in the original proposal, primarily because I feel it leaves no ambiguity: it doesn't matter whether your next action is to
- continue browsing in Tor
- close the browser window
- leave the Internet cafe you're in
- switch to another application on the same computer
- etc.

In contrast, less specific phrases like "moving on" or "continue" seem to leave more room for interpretation. Move on where or to what? Continue to do what?

**Comment by rocodes** [comment]
What about "Clear Browser Activity: (Now | Next | before doing anything else), click the "New Identity" <broom> Button in your Tor Browser Toolbar."

**Comment by zenmonkeykstop** [comment]
@ninavizz, what would you think about having a dedicated **Logged Out** screen as opposed to a flash message on the homepage? ILike, the flow would be:

- user clicks **Log Out**
- user is logged out and sent to screen where sole message/action is "you're not done, click that broom", with no links back to homepage (except for default logo one)
- user presumably clicks broom.

**Comment by ninavizz** [comment]
I'd LOVE that... for many reasons, namely everything y'all say above—AND THE opportunity to remind sources to return to check for replies or to re-submit under the same codename.

**Comment by zenmonkeykstop** [comment]
Also a good place for some generic opsec reminders (cover yr tracks, don't tweet at the org you just leaked to, etc).

**Comment by ninavizz** [comment]
I've never liked the semiotics in "Ohey, I logged out—but now there's an urgent-y alert?!"

If it's a whole new page, the urgent-y text doesn't look like an erroneous action against the last page, whereas the current semiotics allude to that. The re-wording @ro proposed that @eloquence and I have been stuck on, largely revolves around that.

**Comment by eloquence** [comment]
Yes, I like the "whole new page" proposal, if we can keep the design super simple. If the only action we want the user to take is to click one button, then having that be the only message on the screen makes sense.

**Comment by ninavizz** [comment]
I'd like to propose an elegant design with a VERY explicit/clear hierarchy that prioritizes:
1. Sweep ask
2. Check back soon ask
3. (whitespace)
4. (elegant minimalism)
5. OpSec tips for next steps

**Comment by eloquence** [comment]
Sounds good from my end. If 5. turns into a rabbit hole we can implement a simpler version for now. Standard disclaimer: elegance objectives may not be fully achievable. :P

**Comment by zenmonkeykstop** [comment]
Golden ratio whitespace: :white_check_mark:

**Comment by rocodes** [comment]
Quick followup q:

If a user's session expires, currently they are redirected to the main Source Interface page. That behaviour will remain the same even if we have a new 'post-logout' page that instructs the user to create a new Tor identity, correct?  (As in, expired sessions should _not_ also redirect to the 'a new broom sweeps clean' page?)

**Comment by eloquence** [comment]
@rocodes I agree we don't want to alter the behavior of session expiry. The user may want to log in again, and we don't want to make that impossible by parking them in front of a dead end page.

However, in both cases, we want to provide clearer instructions which button to click, since the text "New Identity" only appears on hover. So it is important that we incorporate the broom icon into both messages (the flashed message that is displayed on session expiry, and the logout screen). To resolve this issue, we'll also want to make this clearer in the docs.

This won't make it into 1.2.1 so there's no huge rush on it. Let's work with Nina when she is back to finalize the design and language for both cases as part of #5116.

**Comment by eloquence** [comment]
@rocodes Bumping this back on your radar; we'll want to get this resolved before the QA period for SD 1.3.0, which will most likely kick off around April 15. We'll get back into sprint mode next week, will formally pull into that one.

**Comment by ninavizz** [comment]
Final decisions on design and verbiage of both pages, here: https://github.com/freedomofpress/securedrop-ux/issues/94#issuecomment-589456323
