### ISSUE TITLE
use Tor Browser driver for source-logout_flashed_message.png

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4961]
## Description

Our [automated screenshot taking code](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html?#updating-screenshots) currently doesn't properly take the screenshot `source-logout_flashed_message.png` (ref: #4958). It is used in the source guide for explaining:

> The final step to clearing your session is to restart Tor Browser for
optimal security.

A flashed message is shown for users when they logout while using Tor Browser. We want that flashed message to appear in the screenshot taken using the automated screenshots, but it doesn't currently since we use a Firefox driver for the screenshot. If we use the Tor Browser driver for this screenshot, then the flashed message should appear.

**Comment by DrGFreeman** [comment]
Hi @redshiftzero, I can take this one if that's OK.  I'm not very familiar with selenium but that will be a good opportunity to learn and, having just worked on the automated screenshot taking code, I know where to start.

**Comment by DrGFreeman** [comment]
I noticed that the screenshots `source-index.png` and `source-session_timeout.png` shows a banner "It is recommended to user the Tor Browser to access SecureDrop: ..." when using the Firefox driver for the screenshot. Should these screenshot also be taken using the Torbrowser driver? If so, I can include these additional changes in the PR I am preparing.

**Comment by redshiftzero** [comment]
ah so `source-index.png` should be switched to Tor Browser, `source-session_timeout.png` we're not currently using in the documentation so we can leave it as is for now

**Comment by DrGFreeman** [comment]
OK thanks @redshiftzero. I'll leave the `source-session-timeout.png` screenshot as-is for now. I tried taking that screenshot with the Tor Browser driver but it shows the banner about Tor security settings not high enough... That would have to be cropped-out anyways.

**Comment by DrGFreeman** [comment]
> I tried taking that screenshot with the Tor Browser driver but it shows the banner about Tor security settings not high enough... That would have to be cropped-out anyways.

I managed to adjust the security settings of the `torbrowser_driver` so that the banner does not display. I have therefore included `source-session_timeout.png` in #4975 so it can be used as-is if the need comes.
