### ISSUE TITLE
make dev stuck at the beginning on Debian Buster

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#4972]
## Description

`make dev` is stuck at the beginning without much helpful text. 

```
$ git log -1
commit 39fbc68a69c9d92c94de6431de1d30149dcc8280 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 486853c64 98838d91e
Author: redshiftzero <jen@freedom.press>
Date:   Tue Nov 5 10:33:27 2019 -0500

    Merge pull request #4968 from freedomofpress/docs-client-setup
    
    Link client developement documentation to the securedrop-client repository

```

## Steps to Reproduce

```
make dev
```

## Expected Behavior

The docker  development environment is supposed to start.

## Actual Behavior

![Command output](https://user-images.githubusercontent.com/272303/68288996-66a94b80-00ab-11ea-8623-e5a0b2a80edb.gif)

**Comment by kushaldas** [comment]
I think some previous commit removed the output messages from the docker build command here.

**Comment by kushaldas** [comment]
Finally got the following error.

```
███ Starting development server...
The command '/bin/sh -c gpg --import /opt/tor_project_public.pub &&     wget  https://www.torproject.org/dist/torbrowser/${TBB_VERSION}/tor-browser-linux64-${TBB_VERSION}_en-US.tar.xz &&     wget https://www.torproject.org/dist/torbrowser/${TBB_VERSION}/tor-browser-linux64-${TBB_VERSION}_en-US.tar.xz.asc &&     gpg --verify tor-browser-linux64-${TBB_VERSION}_en-US.tar.xz.asc tor-browser-linux64-${TBB_VERSION}_en-US.tar.xz &&     tar -xvJf tor-browser-linux64-${TBB_VERSION}_en-US.tar.xz &&     mkdir -p /root/.local/tbb && mv tor-browser_en-US /root/.local/tbb &&    paxctl -cm /root/.local/tbb/tor-browser_en-US/Browser/firefox.real &&     paxctl -cm /root/.local/tbb/tor-browser_en-US/Browser/libnspr4.so &&     paxctl -cm /root/.local/tbb/tor-browser_en-US/Browser/plugin-container' returned a non-zero code: 8
make: *** [Makefile:183: dev] Error 8

```

**Comment by kushaldas** [comment]
I am guessing due to upgraded Tor browser, trying with latest version string.

**Comment by kushaldas** [comment]
```
███ Starting development server...
setsid: failed to execute supervisord: No such file or directory

```

**Comment by redshiftzero** [comment]
with latest Tor Browser from your PR in #4973 do you still hit `supervisord: No such file or directory`?

**Comment by kushaldas** [comment]
> with latest Tor Browser from your PR in #4973 do you still hit `supervisord: No such file or directory`?

Yes, though I finally got the app running in the container (along with that error).

**Comment by redshiftzero** [comment]
what was the problem? or is the app running without supervisor?

**Comment by kushaldas** [comment]
> what was the problem? or is the app running without supervisor?

I think it just did a rebuild of the docker image, and without any output, so I thought nothing is happening, I got the proper messages in my Unoon tool when it showed processes from inside of the container connecting to the network.

**Comment by redshiftzero** [comment]
ah okay, there are two problems we should address (we should address them because we'll have a lot of new people working on SD on saturday due to aaron swartz day):

1. make dev doesn't produce build output by default, leading the contributor to be confused as to if things are happening or if the dev env is stalled
2. we need to investigate the `supervisord: No such file or directory` error
