### ISSUE TITLE
Metadata route tests failing

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#4981]
## Description

After updating my dev env to the latest develop, `make test` has 2 failing tests:
```
tests/test_source.py::test_metadata_route FAILED
tests/functional/test_source_metadata.py::TestInstanceMetadata::test_instance_metadata FAILED
```

## Steps to Reproduce

1. Be in the Docker development environment
2. `make test`

## Expected Behavior

All tests should pass. 

## Actual Behavior

I think this is the root cause of the failure for both tests:
```
    @view.route('/metadata')
    def metadata():
        meta = {
            'gpg_fpr': config.JOURNALIST_KEY,
            'sd_version': version.__version__,
            'server_os': platform.linux_distribution()[1],
>           'supported_languages': config.SUPPORTED_LOCALES
        }
E       AttributeError: 'SDConfig' object has no attribute 'SUPPORTED_LOCALES'

source_app/api.py:18: AttributeError
```

**Comment by redshiftzero** [comment]
hmm do you have an old `config.py` sitting around? if so can you delete it and rerun `make dev`?

**Comment by garrettr** [comment]
Haha, yep, that was it! Thanks, @redshiftzero.
