### ISSUE TITLE
Analyze impact of multiple Intel vulnerabilities

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#4992]
## Description

This ticket is to track the [various vulnerabilities disclosed by Intel on 2019-11-12](https://blogs.intel.com/technology/2019/11/ipas-november-2019-intel-platform-update-ipu/) and analyze their impact to SecureDrop.

**Comment by redshiftzero** [comment]
we scraped the vulnerability data from the various advisories released on 2019-11-12 ([link to the code](https://github.com/redshiftzero/intel-vulns/blob/master/scrape.py) to download all vulnerabilities from a particular day from intel security center in a structured format in case it's useful for anyone else), analysis is ongoing here: 

https://docs.google.com/spreadsheets/d/1iHD_tqfER6qtp6gUwtaWSzlHUxL0AQIgmg2hCCIvj2k/edit

an advisory for securedrop admins will be posted soon

**Comment by eloquence** [comment]
Advisory was posted earlier this week:
https://securedrop.org/news/advisory-november-2019-intel-vulnerabilities/

Is the analysis complete? It looks like the spreadsheet lists mitigations for all lines that are not struck through.

**Comment by redshiftzero** [comment]
oh yep we can close this - the current to do is to keep track of upstream's mitigations and update the advisory when needed
