### ISSUE TITLE
Rename "test.sh" and "tests"

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#500]
I know I'm nitpicking, but we really should come up with a better naming scheme than "tests" and "test.sh". If these files are specifically for use with vagrant, rename them to "vagrant-test.sh" and "vagrant-tests" or something similar.

**Comment by garrettr** [comment]
Disagree, there's nothing inherently wrong with these names. Although I have some planned test improvements for 0.4 that will probably change the test layout (and may get rid of `test.sh`).
