### ISSUE TITLE
address lgtm code analysis alerts in develop branch

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#5007]
## Description

As of #4849 we have lgtm code analysis incorporated into CI to give guidance for pending diffs. Right now it's optional (i.e. it won't fail CI). It would be nice to fix all the lgtm code issues in the `develop` branch which you can see here:

https://lgtm.com/projects/g/freedomofpress/securedrop

PRs fixing these issues would ideally come via single PRs addressing one area of the codebase (e.g. addressing all alerts in `admin/`).

**Comment by DrGFreeman** [comment]
For information, I was reading about how LGTM works and especially looking for how to waive/suppress alerts on specific lines of code (similar to `# noqa: <code>` used with linting). I found the answer [here](https://lgtm.com/help/lgtm/alert-suppression#python) and am sharing it in case it might help others.

This will be required in cases like [this one](https://lgtm.com/projects/g/freedomofpress/securedrop/snapshot/a03859bb48b2f137cb5bed67c2a3d342c01c0aed/files/install_files/ansible-base/roles/build-ossec-deb-pkg/library/ossec_urls.py?sort=name&dir=ASC&mode=heatmap#x2b306c8fba143414:1) where the import is require despite not being used.

**Comment by DrGFreeman** [comment]
Some of the LGTM alerts duplicate linting alerts that have been explicitly suppressed. [This file](https://lgtm.com/projects/g/freedomofpress/securedrop/latest/files/install_files/ansible-base/roles/build-ossec-deb-pkg/library/ossec_urls.py?sort=name&dir=ASC&mode=heatmap) is an example where the LGTM alerts report issues where `# noqa: <code>` has been added.

In such cases, and when there is no obvious reason for the `# noqa` flag, should efforts be made to correct the issue reported by the alert and the `# noqa` flag removed?
