### ISSUE TITLE
add functional test coverage for making the file submissions disallowable on the admin interface

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#5008]
## Description

In #4879 we had a contribution enabling an instance to turn off file submissions - instead the instance would accept only messages. This ticket is for adding Selenium-based functional test coverage for this feature in the admin interface. The test would ideally have the following steps:

1. Admin disables file submissions.
2. Source users visits. We confirm that they cannot submit files, only messages.
3. Source submits a message.
4. Admin re-enables file submissions.
5. Source visits again and submits a file successfully.

A good starting point would be looking at similar tests here: https://github.com/freedomofpress/securedrop/blob/develop/securedrop/tests/functional/test_admin_interface.py

**Comment by DrGFreeman** [comment]
I can take this one. Getting familiar with the functional tests by now :wink:.

**Comment by redshiftzero** [comment]
excellent, feel free to take this one @DrGFreeman 😃
