### ISSUE TITLE
Incorrect label IDs in admin UI

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5013]
On the `/admin/add` user screen, labels are defined for the checkboxes "Is Admin" and "Is using a YubiKey [HOTP] ". However, the [`for` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Attributes) is named incorrectly (using underscores instead of hyphens as in the input IDs). This results in especially annoying behavior: the mouse pointer changes over the label, but clicking it has no effect.   This should be a two-line fix + testing.

**Comment by DrGFreeman** [comment]
Checking all the checkboxes with labels, I found [one other](https://github.com/freedomofpress/securedrop/blob/90bd863b6c7a20cdf2b7803dbfe0921c60e0b0fc/securedrop/journalist_templates/edit_account.html#L24-L25) with similar mismatch between checkbox `id` and label `for` value.

I will submit a PR shortly with the three corrections.
