### ISSUE TITLE
No deletion log on journalctl

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5032]
## Description

`1.2.0-rc1`

After a journalist deleted a file/message, there is no deletion log in the `journalctl` output.

## Steps to Reproduce

Submit a few messages and files to the server.

In the app server:

```
journalctl -u securedrop_rqworker -f
```

Then delete as many messages/collections via the web UI.

## Expected Behavior

Deletion logs mentioned in the journalctl

## Actual Behavior

No such screenshot.

## Comments

The actual files are getting deleted.

**Comment by zenmonkeykstop** [comment]
Deletion logs are in the securedrop_shredder logs IIRC.

**Comment by redshiftzero** [comment]
yep @zenmonkeykstop is correct, so closing this, reopen if you find that the deletion events are not present in the shredder logs @kushaldas (I confirm that they are present for me on 1.2.0-rc1)
