### ISSUE TITLE
securedrop-monitor does not confirm GPG fingerprint for OSSEC emails

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#506]
When installing securedrop-app and entering the GPG public key for the SecureDrop application, I was asked to confirm the key's fingerprint. I expected the same thing to happen when installing securedrop-monitor and entering the GPG public key that is tied to OSSEC emails, but it seems the installation process takes the public key and moves on without asking me to confirm the fingerprint.

**Comment by garrettr** [comment]
You also need to specify the OSSEC key fingerprint, `ossec_gpg_fpr`, in `{staging,prod}-specific.yml`, so this issue is resolved now.
