### ISSUE TITLE
Update tor to 0.4.2.x series

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#5070]
## Description

First stable tor release in 0.4.2.x series is out:
https://blog.torproject.org/new-release-0425-also-0417-0406-and-0359

We have some time to upgrade since we're running on 0.4.1.6 which doesn't EOL until [May](https://trac.torproject.org/projects/tor/wiki/org/teams/NetworkTeam/CoreTorReleases#Listofreleases), but we should do this upgrade in the next regular SecureDrop release (1.3.0).

**Comment by emkll** [comment]
CI is now failing, as 4.1.x debs are no longer served from Tor's apt server: https://circleci.com/gh/freedomofpress/securedrop/38230
