### ISSUE TITLE
Keeping settings when upgrading the Tor Browser

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#508]
The SecureDrop installation guide talks about setting up the Tor Browser with a HidServAuth value to enable the journalist to visit the Document Interface. This section should also cover how the journalist can upgrade the Tor Browser in the future without losing those settings (alternatively, warn the journalist that these settings will need to be reapplied when upgrading).

**Comment by garrettr** [comment]
I consider this to be resolved as part of #514 and the automatic ATHS setup we've created for journalists and admins (and are currently improving in #925, #955, etc.)
