### ISSUE TITLE
Rename Qubes staging standalone VM due to conflict with workstation VM

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5097]
## Description

Initially reported by @zenmonkeykstop 

We have introduced changes in https://github.com/freedomofpress/securedrop-workstation/pull/407 that rename `sd-svs` to `sd-app`. As a result, the Qubes staging environment instructions will no longer work if the SecureDrop workstation is provisioned on the host.

## Expected Behavior
Qubes VMs should have a unique name
## Actual Behavior

`sd-app` refers to both the AppVM that is running the SecureDrop Client, as well as the SecureDrop Application server for the qubes-staging scenario.

## Comments

We should update the qubes-staging docs to rename the sd-app to another name (e.g. sd-app-staging)

**Comment by eloquence** [comment]
I'd recommend:
- `sd-staging-app` and `sd-staging-mon` for the staging VMs
- `sd-staging-app-base` and `sd-staging-mon-base` for their templates
- `sd-staging-base` for the base template.

Not normally a fan of multiple hyphens but for development I think it's OK to break that convention. The reason to avoid starting with `sd-app` is to reduce developer confusion/frustration when navigating menus etc.

**Comment by zenmonkeykstop** [comment]
Yikes, I'd already redone this as `sd-appserver`, `-sd-monserver`, but tbh the `sd-staging` prefix makes more sense. Will fix it up and submit a PR
