### ISSUE TITLE
Tor browser link invalid in /tor2web-warning page

### ISSUE THREAD

**Issue by DrGFreeman** [freedomofpress/securedrop#5105]
## Description

The URL of the link to Tor browser in `/tor2web-warning` is invalid.

![image](https://user-images.githubusercontent.com/22901938/73129038-911eec80-3fa8-11ea-894d-bda49ed5554a.png)

## Steps to Reproduce

In the Source Interface, access `/tor2web-warning` and click on the "Tor browser" link.

## Expected Behavior

Browser opens the Tor browser web page.

## Actual Behavior

Application returns "Page not Found".

## Comments

Link is missing "https://".

**Comment by DrGFreeman** [comment]
The `/use-tor` page in the Source Interface has the link to the Tor browser page in plain text for the source to copy/paste, as well as the gettor@torproject.org address, whereas `/tor2web-warning` has a direct link to the Tor browser page.

Should `/tor2web-warning` link to `/use-tor` instead?

**Comment by zenmonkeykstop** [comment]
I can't speak for @redshiftzero or @eloquence, but the one worry that I'd have is that if someone uses tor2web to visit an SD instance and *then* downloads Tor Browser in the same browsing session, that's a good amount of correlating evidence for an adversary observing their network traffic. The language on the `use-tor` page might not make sense in that scenario.

**Comment by DrGFreeman** [comment]
> but the one worry that I'd have is that if someone uses tor2web to visit an SD instance and _then_ downloads Tor Browser in the same browsing session, that's a good amount of correlating evidence for an adversary observing their network traffic.

So I understand that, even if the link is corrected, having a direct link to https://www.torproject.org/projects/torbrowser (which redirects to https://www.torproject.org/download/) isn't good either?

**Comment by legoktm** [comment]
We fixed this in 35f1a948d34e2c6768839e22c05f05260b5d0c00.
