### ISSUE TITLE
Moving to python3-venv to create the virtual environment for SecureDrop

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5134]
## Description

In future we should move to using `python3-venv` module to create the virtual environment for the application (in debian package). This will help us to use more standardized way to use the related upstream tools.

Once such attempt was made https://github.com/freedomofpress/securedrop/pull/5110, but, it requires more work and finding out a better solution to have the exact versions we need for the dependencies. 

## User Stories

IAs a Python developer, I would love to stay as close as possible to the upstream virtual environment.

**Comment by emkll** [comment]
Closing, this has been resolved in https://github.com/freedomofpress/securedrop/pull/5484
