### ISSUE TITLE
journalist login with long passphrase causes internal server error

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5145]
## Description

When logging in to the journalist interface, entering a passphrase that's too long raises `models.InvalidPasswordLength`, which is not caught properly, so ends up handled at line 97 of `/var/www/securedrop/journalist_app/__init__.py`, in `_handle_http_exception`, where `AttributeError: 'InvalidPasswordLength' object has no attribute 'code'` results in the plain Apache Internal Server Error page being delivered to the visitor.

## Steps to Reproduce

This can be reproduced with the dev server.
- `make dev`
- visit the journalist interface at http://localhost:8081
- try to log in with a passphrase longer than 128 characters

## Expected Behavior

The server should return a flashed error indicating the login failed.

## Actual Behavior

The improperly handled exception lands the visitor at a dead-end Internal Server Error page.

**Comment by prateekj117** [comment]
@rmol Will look into this.

**Comment by prateekj117** [comment]
@rmol Wrapping the `raise InvalidPasswordLength(password)` in a `try-catch` block like:
```
try:
    raise InvalidPasswordLength(passphrase)
except InvalidPasswordLength as error:
    str(error)
````
would work I think.
