### ISSUE TITLE
Differnet versions of pytest mentioned in different requirements files

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5179]
## Description

`develop-requirements.txt` has  `pytest==3.2.0`
`test-requirements.txt` has  `pytest==3.10` 

## Expected Behavior

Both the files should have the same version mentioned.

## Actual Behavior

We have different versions mentioned.

**Comment by emkll** [comment]
closed via https://github.com/freedomofpress/securedrop/pull/5585
