### ISSUE TITLE
Add option to run development environment with hidden services

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5189]
We have determined that it would be useful for dev agility to be able to launch Source Interface / Journalist Interface hidden services using the Docker-based development environment (e.g., via a `make dev-tor` target). 

## Motivation

This would make it easier to quickly test server-side changes e.g. for the SecureDrop Workstation project, in cases where testing with a high fidelity server-side staging environment is not required. It would also make it easier for new developers to get started on our projects.

## Out of scope for this issue
- SSH onion services
- Other staging/dev differences

**Comment by eloquence** [comment]
I'm guessing that for simplicity's sake we'd just want to support v3 in the dev env.

**Comment by eloquence** [comment]
Cross-ref related SDK change to use such an environment with the SecureDrop Client outside Qubes:

https://github.com/freedomofpress/securedrop-sdk/pull/15

**Comment by legoktm** [comment]
This was implemented in 6d444f50e1f149a721ba384759176b9910b034e2 / #6167.
