### ISSUE TITLE
make staging provisioning timeout at final reboot step

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5193]
## Description

While reviewing https://github.com/freedomofpress/securedrop/pull/5192, observed some issues in local staging environment at the final reboot task

## Steps to Reproduce
In libvirt staging environment, `make staging`
## Expected Behavior
Vms should be rebooted and staging environment should be provisioned

## Actual Behavior
```
TASK [Reboot if required due to security updates.] *****************************
    fatal: [mon-staging]: FAILED! => {"changed": false, "elapsed": 664, "msg": "Timed out waiting for last boot time check (timeout=600)", "rebooted": true}
    fatal: [app-staging]: FAILED! => {"changed": false, "elapsed": 665, "msg": "Timed out waiting for last boot time check (timeout=600)", "rebooted": true}
```

## Comments

Perhaps related to #4364 ?

**Comment by emkll** [comment]
Removing the `~/.ansible` folder on my dev machine, and running make clean did appear to resolve the issue (and may explain why we don't see this error in staging environment)

**Comment by conorsch** [comment]
Have not encountered this particular issue, but I've mostly been using the Qubes staging env, not the libvirt one. Given that clearing out `~/.ansible/` (likely just `~/.ansible/cp/` would suffice), probably worth resurrecting #4366.

**Comment by emkll** [comment]
Looks like it may also be happening in CI:
https://circleci.com/gh/freedomofpress/securedrop/39711

**Comment by eloquence** [comment]
Another CI flake here, and this is a long-running job, so definitely something we should poke at soon to reduce developer pain levels

https://app.circleci.com/pipelines/github/freedomofpress/securedrop/250/workflows/6c919263-d5dd-46a2-9412-7849e4d47e7a/jobs/40924/steps

**Comment by eloquence** [comment]
Closing given changes in #5504 and #4366 and no recent CI failures, please reopen if you see it again.
