### ISSUE TITLE
securedropadmin-setup failing with exit status 1.

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#5221]
Description:

Trying to run securedrop-admin setup in Kali Linux 5.5.0 (based on Debian), the command exits with a status 1.

Steps to Reproduce:
 ./securedrop-admin setup.

Expected Behaviour:
Should install successfully.

Actual Behaviour:
 ```
error: command \'x86_64-linux-gnu-gcc\' failed with exit status 1\n       
              ERROR: Command errored out with exit status 1: 
/home/amnesia/Persistent/securedrop/admin/.venv3/bin/python -u -c \'import sys, setuptools, tokenize; 
sys.argv[0] = \'"\'"\'/tmp/pip-install-7at8bfjs/cffi/setup.py\'"\'"\';
 __file__=\'"\'"\'/tmp/pip-install-7at8bfjs/cffi/setup.py\'"\'"\';
f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);
code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');
f.close();
exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-r0iknnz1/install-record.txt --single-version-externally-managed --compile --install-headers /home/amnesia/Persistent/securedrop/admin/.venv3/include/site/python3.8/cffi 
Check the logs for full command output.\n'
ERROR: Failed to install pip dependencies. Check network connection and try again.
 ```

Comments:
I am not sure about what went wrong.
cloned the project
using v 1.2.2

**Comment by zenmonkeykstop** [comment]
Hi @poseidonlb - the `securedrop-admin` script is intended to be run under Tails only, so it's not tested under Kali Linux. Our best guess would be that python development requirements aren't available - try adding those with `sudo apt-get install python3-dev`. But again, note that the script as it stands is not written with Kali Linux in mind.

**Comment by poseidonlb** [comment]
hello @zenmonkeykstop . understood. I am gonna work on making it work and share the solution here. any other ideas would also be welcome. Thank you!

**Comment by legoktm** [comment]
Closing per above and lack of follow-up.
