### ISSUE TITLE
Yubikey personalization GUI has changed [low priority] [HOTP]

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop#5229]
## Description

The Yubikey personalization GUI has changed and the configuration options for HOTP are slightly different (for reference in https://docs.securedrop.org/en/release-1.2.2/yubikey_setup.html#download-and-launch-the-yubikey-personalization-tool). There is no "Hide secret" checkbox; instead there is a Generate button beside the secret key field. Filing to follow up on after QA/at some lower-priority time. 

## Steps to Reproduce
on Tails, install the `yubikey-personalization-gui` package, launch the gui and navigate to OATH-HOTP tab. compare with https://docs.securedrop.org/en/release-1.2.2/yubikey_setup.html#download-and-launch-the-yubikey-personalization-tool

## Expected Behavior
docs match software 

## Actual Behavior
docs are out of date

## Comments
Can be assigned to me to fix

**Comment by eloquence** [comment]
@rocodes has offered to take a stab at this during the 5/20-6/3 sprint, but lower priority than our other commitments, especially release QA.
