### ISSUE TITLE
modify circle ci configuration on master to only run docs related jobs

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#5264]
## Description

Since we currently are using master branch only for the purpose of building documentation, we should modify the jobs that are run on that branch to only those that are relevant for documentation purposes, which is the lint job only, as it runs the docs linting. We may even want to restrict further and only run the docs linting on master.

**Comment by prateekj117** [comment]
@redshiftzero I would like to work on this.

**Comment by zenmonkeykstop** [comment]
Do we want to run said jobs against master, or against PRs into master? (or both?)

**Comment by prateekj117** [comment]
@zenmonkeykstop Seems to me it meant both `Pull Request` and `Push` event, so I did the changes according to that. Let me know if any change is required in #5266 PR.
