### ISSUE TITLE
OSSEC test alert does not send, gpg "Permission denied" error in procmail log

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5265]
Environment: long-running production instance just updated to 1.3.0 (not manually rebooted yet)

I see OSSEC alerts flowing, but sending a test alert via the Journalist Interface ("Instance Config" section) does not work for me. I see the following error in `/var/log/procmail.log` on the monitor server:

```
procmail: Assigning "LASTFOLDER=/var/ossec/send_encrypted_alarm.sh ossec"
procmail: Notified comsat: "ossec@:/var/ossec/send_encrypted_alarm.sh ossec"
From ossec@freedom.press  Wed May 13 19:34:21 2020
 Subject: OSSEC Notification - mon - Alert level 7
  Folder: /var/ossec/send_encrypted_alarm.sh ossec                          817
procmail: Executing "/var/ossec/send_encrypted_alarm.sh,ossec"
gpg: gpg: NOTE: trustdb not writable
NOTE: trustdb not writable
gpg: can't create `/var/ossec/.gnupg/random_seed': Permission denied
gpg: NOTE: trustdb not writable
```

Note: I don't know if this is a recent regression or a longstanding issue with my instance.

**Comment by eloquence** [comment]
It looks like the issue went away after the nightly reboot. Now I can send test alerts that look as follows:

```
OSSEC HIDS Notification.
2020 May 14 13:24:09

Received From: (app) 10.20.2.2->/var/log/apache2/journalist-error.log
Rule: 400700 fired (level 7) -> "Apache application error."
Portion of the log(s):

[Thu May 14 13:24:08.370774 2020] [wsgi:error] [pid 3799:tid 117507186415360] [remote 127.0.0.1:53834] ERROR:flask.app:This is a test OSSEC alert



 --END OF NOTIFICATION
```

Assuming that's the expected format, closing.

**Comment by eloquence** [comment]
Even though the above email sent (and was encrypted), I still see a gpg "Permission denied" error in the procmail log for the same email. Reopening until we can confirm that it's either a problem with my instance or an expected error that's safe to ignore.

**Comment by eloquence** [comment]
From the looks of it so far, not high priority, but a good learning issue for @rocodes and myself to poke at in the 5/20-6/3 sprint.

**Comment by rocodes** [comment]
Can repro, am currently investigating!

**Comment by rocodes** [comment]
### More than anyone probably wanted to know about this
STR: triggered a test alert in the journalist interface, examined mon server (@1.3.0).

```
lovelace@mon:~$ sudo tail /var/log/procmail.log                                      
[...]
procmail: Assigning "LASTFOLDER=/var/ossec/send_encrypted_alarm.sh ossec"
procmail: Executing "/var/ossec/send_encrypted_alarm.sh,ossec"
procmail: Notified comsat: "ossec@:/var/ossec/send_encrypted_alarm.sh ossec"
From ossec@freedom.press  Tue Jun  2 15:22:16 2020
 Subject: OSSEC Notification - (app) 10.20.2.2 - Alert level 7
  Folder: /var/ossec/send_encrypted_alarm.sh ossec                          906
gpg: NOTE: trustdb not writable
gpg: can't create `/var/ossec/.gnupg/random_seed': Permission denied
lovelace@mon: sudo ls -la /var/ossec/.gnupg
total 24
drwx------  2 ossec ossec 4096 May  6 15:28 .
dr-xr-x--- 14 root  ossec 4096 May  6 16:34 ..
-r-xr-x---  1 root  ossec 5046 May  6 15:27 pubring.gpg
-r-xr-x---  1 root  ossec    0 May  6 15:27 pubring.gpg~
-r-xr-x---  1 root  ossec  600 May  6 16:34 random_seed
-r-xr-x---  1 root  ossec    0 May  6 15:27 secring.gpg
-r-xr-x---  1 root  ossec 1200 May  6 15:27 trustdb.gpg
```
The `/var/ossec/.gnupg` folder on the mon server has 550 permissions. Writing to the file `/var/ossec/.gnupg/random_seed` therefore fails.


#### Whence?
- In the postinst script for the mon server, there's a default chmod -R 550 for the $OSSEC_HOME dir. (The `.gnupg` directory is then set to 700, but this is not a recursive action): 
https://github.com/freedomofpress/securedrop/blob/f6bbe6c196fa4f2e9fb3890b087618fd46d3ffb4/install_files/ossec-server/DEBIAN/postinst#L79

- The `configure_server` sets perms for the contents of `/var/ossec/.gnupg` to 600. 
https://github.com/freedomofpress/securedrop/blob/f6bbe6c196fa4f2e9fb3890b087618fd46d3ffb4/install_files/ansible-base/roles/ossec/tasks/configure_server.yml#L49

- _A_ difference is expected, but say "only the ossec user should have read/write permissions", when no one ends up with write permissions.  
: https://github.com/freedomofpress/securedrop/blob/1c2a437bb563248a4015d1f86386be449a2beb93/molecule/testinfra/staging/mon/test_ossec_server.py#L47

#### Is this serious?
From a _cursory_ look, it does not look serious. For example, it is possible to pass a `--no-random-seed-file` option if using gnupg on a read-only filesystem. 

From the gnupg manpage (https://gnupg.org/documentation/manpage.html):
"GnuPG uses a file to store it's internal random pool over invocations. This makes random generation faster; however, sometimes write operations are not desired [...]". 

#### What do? 
Either the permissions could be changed to 600 from 550, or if the intention is to use gnupg in read-only mode after the install, we could suppress this warning (eg by looking at --no-random-seed-file and other gnupg options).

**Comment by conorsch** [comment]
Great write-up, @rocodes! 

> Either the permissions could be changed to 600 from 550

That sounds like the right approach, largely we're talking about the longstanding #1756 here.

**Comment by rocodes** [comment]
lightning response, thanks @conorsch. EOD for me but I'll pick this up again tomorrow

**Comment by conorsch** [comment]
> the permissions could be changed to 600 from 550, or if the intention is to use gnupg in read-only mode after the install

Definitely agree we should clean up the permissions. Noting that on the gnupg dir for OSSEC, we actually want 700, not 600—but definitely not 550! I suggest making the change in two places:

* removing the perms-futzing logic for that dir from the playbook, basically excising these tasks https://github.com/freedomofpress/securedrop/blob/f6bbe6c196fa4f2e9fb3890b087618fd46d3ffb4/install_files/ansible-base/roles/ossec/tasks/configure_server.yml#L23-L59
* updating the `postinst` for the `securedrop-ossec-server` package to chmod 700 the gnupg dir, which matches what the postinst for `ossec-server` is already doing

With that approach, we'll rely on the deb package logic to enforce state on servers during upgrade. In order to test the approach working well, we should use the "upgrade" scenario, to confirm that a server with bad 550 perms gets switched to 700 perms without any use of Ansible.

**Comment by eloquence** [comment]
So far I've tested manually setting the permissions as you do here in postinst, and that permission configuration seems to make `gpg` happy -- I no longer see the `trustdb` errors. :tada: Now attempting to build a staging env as well.
