### ISSUE TITLE
GCE staging CI tests are failing to run

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#5293]
## Description

The staging-test-with-rebase CI job is failing due to a missing container image. 

## Steps to Reproduce
Open a PR that runs all test jobs, observe CircleCI fail. 

## Expected Behavior
The `staging-test-with-rebase` job starts successfully, then completes successfully. 

## Actual Behavior
The `staging-test-with-rebase` job fails to start, complaining that it cannot find a container image:

```
#!/bin/bash -eo pipefail
BRANCH_MATCH=$(devops/scripts/match-ci-branch.sh "^(i18n|docs)")
if [[ $BRANCH_MATCH =~ ^found ]]; then echo "Skipping: ${BRANCH_MATCH}"; exit 0; fi
make ci-go
 Creating GCE host for testing staging environment...
Error: No such container: gcloud_tool
make: *** [ci-go] Error 1

Exited with code exit status 2
CircleCI received exit code 2
```

## Comments
Example failed job: https://app.circleci.com/pipelines/github/freedomofpress/securedrop/250/workflows/171478a3-7b5a-4e35-b0b6-c9bb3b76f19f/jobs/40916/steps

**Comment by conorsch** [comment]
Rerunning with SSH, raised verbosity, seeing:

```
++ grep -q gcloud_tool
++ docker run --rm --env=CLOUDSDK_COMPUTE_ZONE=us-west1-c --volume /tmp/gce-nested/gce.pub:/gce.pub --volume /home/circleci/sd/.gce.creds:/gce-svc-acct.json --name gcloud_tool -d quay.io/freedomofpress/gcloud-sdk:222.0.0-1 background
++ sleep 3
++ docker exec -i gcloud_tool /usr/bin/gcloud --project securedrop-ci compute images list '--filter=family:fpf-securedrop AND name ~ ^ci-nested-virt-stretch' '--sort-by=~Name' --limit=1 '--format=value(Name)'
Error: No such container: gcloud_tool
+ ci_image=
make: *** [ci-go] Error 1
```

So the backgrounded tooling container is failing, and the backgrounding means the error wasn't raised. 

```
circleci@default-52a6c378-4297-434c-b5cc-f9629d1aa3a6:~/sd$ docker run --rm --env=CLOUDSDK_COMPUTE_ZONE=us-west1-c --volume /tmp/gce-nested/gce.pub:/gce.pub --volume /home/circleci/sd/.gce.creds:/gce-svc-acct.json --name gcloud_tool quay.io/freedomofpress/gcloud-sdk:222.0.0-1 
ERROR: (gcloud.auth.activate-service-account) There was a problem refreshing your current auth tokens: invalid_grant: Invalid JWT Signature.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
```

indicates we may have breakage on the service account credentials.

**Comment by maeve-fpf** [comment]
I believe I caused this when trying to remove the old keys for the instance culler; sorry! I've generated another key and am rerunning the build now...

**Comment by conorsch** [comment]
@maeve-fpf If there are new credentials for the GCP service account, we'll also need to update the GOOGLE_CREDENTIALS env var for this repo's CircleCI settings, see relevant config in https://github.com/freedomofpress/securedrop/blob/develop/devops/gce-nested/ci-env.sh#L33-L51

**Comment by conorsch** [comment]
Changes made out of band appear to have resolved, job https://app.circleci.com/pipelines/github/freedomofpress/securedrop/250/workflows/21bc7256-ff33-4c21-a12b-e69a43ec9683/jobs/40921/steps has proceeded past the prior failure point.

**Comment by maeve-fpf** [comment]
Looks like that build eventually failed due to a timeout, after `TASK [common : Check whether tor will be upgraded.]`. I don't know enough to comment on the failure but it sounds unrelated.

**Comment by conorsch** [comment]
Agreed unrelated, bounced CI in #5292 again. Will file a separate issue to update the dependencies inside the CI test box, since that'll help reduce running time.

**Comment by conorsch** [comment]
Confirming passing test run in https://app.circleci.com/pipelines/github/freedomofpress/securedrop/250/workflows/1e8eb2d5-c44f-4e1d-97a1-31cc4d77c405/jobs/40922/steps
