### ISSUE TITLE
Add deprecation notice for v2 services

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5302]
Due to the significantly improved security and anonymity properties of v3 onion services, we are aiming to transition all SecureDrop instances to v3 by a certain date, likely no later than the next server OS upgrade (i.e. by April 30, 2021). In order to facilitate that transition, we should:
- determine the final date for removal of v2 support
- add a deprecation notice with that date to the Journalist Interface
- potentially, add a deprecation notice in other contexts (e.g., in the graphical updater, or on every playbook run).

This issue is intended to track relevant code changes, and potential design work for notices displayed to journalists/admins.

**Comment by conorsch** [comment]
Tor has announced their timeline for transitioning v2 -> v3:

<blockquote>

  1) September 15th, 2020
     0.4.4.x: Tor will start warning onion service operators and clients that v2 is deprecated and will be obsolete in version 0.4.6

  2) July 15th, 2021
     0.4.6.x: Tor will no longer support v2 and will be removed from the code base.

  3) October 15th, 2021
     We will release new stable versions for all supported series that will disable v2.
</blockquote>

See details here https://lists.torproject.org/pipermail/tor-dev/2020-June/014365.html Targeting the OS migration described in #4768 keeps us just ahead of that timeline.

**Comment by conorsch** [comment]
Nothing is set in stone yet, but there's discussion upstream about warning users of Tor Browser when they connect to v2 Onions as early as September 2020, see https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40001 So we may want to generate some support messaging that gives existing Admins some advanced notice on the migration, ahead of the OS transition in 2021.

**Comment by ninavizz** [comment]
Yuppitiee doo... commenting to get this on my radar.

**Comment by eloquence** [comment]
We discussed the scope of this work during sprint planning. For now, we are limiting ourselves to the Journalist Interface (i.e. the graphical updater is out of bounds). @creviera will take point on the implementation, and @ninavizz will advise on UX.

The old warning that we implemented for the Ubuntu 14.04->Ubuntu 16.04 upgrade can be seen in the PR comment here:
https://github.com/freedomofpress/securedrop/pull/4055#pullrequestreview-195116461

Here is some proposed language as a starting point for discussion:

> Update Required: Your SecureDrop servers are still running v2 Onion Services. In February 2021, v2 Onion Services will be disabled, and your SecureDrop servers may become unreachable.  [Learn more]

@ninavizz @creviera @emkll and others, thoughts on language and design?

The implication here is:
- We would release SecureDrop 2.0.0 in February 2021, consistent with our timeline for Xenial last year
- That release would _fully remove/disable_ v2 support (justifying the version bump), while retaining time-limited support for Ubuntu 16.04 until its EOL

**Comment by eloquence** [comment]
Also @creviera for cross-reference, here is the commit that was part of SD 1.0.0 (the first version to support v3) which ensured that we create `/var/lib/securedrop/source_{v2,v3}_url` as part of a playbook run. That means if these files don't exist, v3 is definitely not enabled: ccb2b27a683146237ce402e5b6fd3620adbf21d6

**Comment by eloquence** [comment]
Proposed language tweak per @emkll feedback yesterday:
> Update Required: Your SecureDrop servers are still running v2 Onion Services, which are being phased out for security reasons. In February 2021, v2 Onion Services will be disabled, and your SecureDrop servers may become unreachable. [Learn more]

The proposed addition here is the phrase "which are being phased out for security reasons".
