### ISSUE TITLE
Issues with reinstalling monitor-server with v3-onion

### ISSUE THREAD

**Issue by davralin** [freedomofpress/securedrop#5311]
## Description

Mon-server suffered a hardware-crash, reinstallation was not possible due to inventory-dynamic finding `mon-ssh-auth.private` and then overriding the local_ip for monitor-server.
Deleting `mon-ssh-auth.private` will fail the `validate`-role, because `v3_ssh_auth_file_count` would not be equal to 0 or 2.

A workaround is deleting `mon-ssh-auth.private`, and edit [this](https://github.com/freedomofpress/securedrop/blob/develop/install_files/ansible-base/roles/validate/tasks/validate_tails_environment.yml#L65), so that it checks for 0 or 1 while doing the initial installation.

## Steps to Reproduce

1. I read the [following](https://docs.securedrop.org/en/master/backup_and_restore.html) and note the part about Monitor-server requiring a full reinstall from scratch.
2. Reinstalled ubuntu using the same configuration from previously.
3. Ran `securedrop-admin install`.

## Expected Behavior

Reinstalled monitor-server

## Actual Behavior

It will fail to contact the monitor-server, debugging will confirm that it is trying to contact it via the onion-address.
`inventory-dynamic` will enumerate the auth-file, and will send an inventory that points to the onion-address.
Removing the auth-file will provide an inventory with the defined local IP, but that will fail the validate-role from `securedrop-admin install`.

## Comments

Please note that I am using a slightly different network-setup, so I'm not using the suggested IP's from the installation.

I think it would be smart to have an actuall document that states how a restore of the mon-server is done.

For the fix, my first thought would be to duplicate the file-count-check, and have the documentation set an ansible-variable when you need to re-install the mon-server - then use that variable as a when-clause for the file-count-check.

The documentation would then have to include information to delete mon-ssh-auth.private.

Also note, this was what I did to fix this issue, as I didn't have much time onsite (I'm the technician for this organization, but I'm not normally onsite) - so please alert me if the actions I did somehow increase the risks for us.

**Comment by rocodes** [comment]
Hi @davralin, thank you for getting in touch and reporting this. Request for better docs on mon server recovery/reinstallation absolutely noted. If you'd like, in the meantime we can also correspond in more detail on the Support Portal: https://support.freedom.press/

**Comment by davralin** [comment]
> Request for better docs on mon server recovery/reinstallation absolutely noted.

I'm not sure if there's **THAT** much more documentation that is needed to be honest, I'm guessing it's as easy as nobody tested monitor-reinstalls with V3-onions.

Perhaps a whole page would be great, but in reality I think there's enough with a paragraph.

I mean, my solution would require one setting, and then the `./securedrop-admin install` would work just fine.

> If you'd like, in the meantime we can also correspond in more detail on the Support Portal: https://support.freedom.press/

I'm not sure I'd like that, since my organisation doesn't support you financially - I don't think it's fair (to you) to address this more officially.
If it's needed, for more detailed "non-public" talks, please insist, and I'll do that. :-)

**Comment by eloquence** [comment]
Thanks again @davralin for filing, and sorry for letting this sit for a while. BTW, no financial support required for a support portal account, it just means that we won't be able to give you priority support -- but I would still recommend [requesting an account](https://support.freedom.press/account/register) so you receive all official announcements by email, and so that you _can_ reach us via a private issue tracker when needed.

Tracking this issue as a docs issue for now: https://github.com/freedomofpress/securedrop-docs/issues/81

**Comment by davralin** [comment]
I probably won't be handling this anymore internally, but I will pass that info along to my replacement.

If needed, feel free to ping me for specifics or anything, I don't mind answering, even though I wont be able to test any fixes.
