### ISSUE TITLE
Rename `master` branch to `docs` or another name

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5321]
The branch name `master` is misleading in our case, as we only use it to identify the current stable version of the documentation; the term `master` also has dark societal connotations, depending on how it's interpreted. We should rename this branch to `docs` or something else. 

This change needs to be carefully staged, because we'll need to update https://docs.securedrop.org redirects in infra and the RTD configuration.

**Comment by eloquence** [comment]
Note that the branch name is displayed on https://docs.securedrop.org/ and in the URL; there may be an argument for a name that speaks a bit more clearly to the fact that this is the stable version of the docs.

**Comment by creviera** [comment]
we could name it `stable` to indicate that it tracks stable releases of securedrop

**Comment by ninavizz** [comment]
How about `primary`, assuming a hierarchical connotation is also needed by consumers of the semiotic of a name? A complete schema should also be considered, not just one part of a dark social pattern.

**Comment by zenmonkeykstop** [comment]
+1 for `stable` - `primary` isn't as descriptive. There might be a bit of a problem with RTD with the use of `stable` though, as it automatically generates a `stable` version based on the latest semver tag for a given project. Would be worth investigating tho.

**Comment by eloquence** [comment]
I did some preliminary testing in a test repo with RTD set up.
- I can set up a `stable` branch, have it selectable in RTD, and configure it to trigger builds when changes are pushed to it.
- At least in my configuration, pushes of semver branches or tags are ignored. (I have only explicitly activated the `stable` branch.)
- The RTD docs seem to suggest that this kind of configuration is explicitly supported:

>  If you want a custom `stable` version, create either a tag or branch in your project with that name.

[source](https://docs.readthedocs.io/en/stable/versions.html)

**Comment by eloquence** [comment]
`master` has been deleted, and docs are now built from the `stable` branch. Closing. (We still have #5326 to ensure the process for updating docs during/after releases is fully documented.)
