### ISSUE TITLE
Create troubleshooting.md with common issues

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#533]
I'm sure there are a few common issues that pop up during the installation process. We should collect them in troubleshooting.md and include solutions.

**Comment by conorsch** [comment]
The combination of the [OSSEC Troubleshooting section](https://docs.securedrop.org/en/stable/ossec_alerts.html#troubleshooting) and the [Test the Installation steps](https://docs.securedrop.org/en/stable/test_the_installation.html) should be sufficient here.

**Comment by redshiftzero** [comment]
I'm going to close this until there are more specific additions that should be made to the docs
