### ISSUE TITLE
Install command fails on admin workstation if v2 services enabled, v3 services disabled.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5334]
## Description

If the `site-specific` file on an Admin Workstation has `v2_onion_services: true` and `v3_onion_services: false

## Steps to Reproduce

using an admin workstation USB:
- ensure that the workstation code has been upgraded to 1.4.0
- run `./securedrop-admin sdconfig` and set v2 services on, v3 services off
- run `./securedrop-admin install`

## Expected Behavior

- Install playbook is run, prompting user for server-side admin password

## Actual Behavior

- command fails with error `ERROR: Since you disabled v2 onion services, you must enable v3 onion services`

## Comments

This issue is 1.4.0-specific, 1.3.0-tagged version works correctly.

**Comment by rmol** [comment]
I can reproduce this. Investigating...
