### ISSUE TITLE
Narrow branch target for staging-test-with-rebase, nightly runs

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5336]
`staging-test-with-rebase` often takes >30 minutes or flakes out entirely, which significantly slows down normal development. Unless we can very significantly speed it up, we should consider:
- making it nightly and reinstating a build manager role for a given release cycle who is on duty to monitor/escalate that these aren't failing during dev
- continuing to running it on all `release/` branch PRs, since those really should always pass

**Comment by eloquence** [comment]
Deferring this for now per sprint planning, we'll see how the job performs with an updated base image. May revisit mid-sprint if too many PRs get stalled by repeated CI fails again. If we do implement this, we agreed it would be great to add Slack alerting for nightly job fails, to raise visibility.

**Comment by eloquence** [comment]
Example of recent failure, after 48m: https://app.circleci.com/pipelines/github/freedomofpress/securedrop/524/workflows/0a304b9b-e1a6-4db2-a1ed-de26425b5967/jobs/42275/steps

**Comment by eloquence** [comment]
I'm seeing #5401 a lot lately, often requiring multiple kicks to resolve.

**Comment by cfm** [comment]
This change is drafted in #6063.  @zenmonkeykstop, did you have any additional alerting in mind for failures of the nightly workflow?  I don't think I have access to that configuration (pending freedomofpress/infrastructure#3225).

**Comment by cfm** [comment]
For this sprint, after #6063, @zenmonkeykstop will monitor nightly `staging-test-with-rebase` runs and evaluate whether additional alerting will be worthwhile.
