### ISSUE TITLE
Update SecureDrop kernel to 4.14.186 or later

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5359]
Consistent with the workstation kernel updates tracked in https://github.com/freedomofpress/securedrop-workstation/issues/546, we should update the grsecurity kernel for SecureDrop 1.5.0 as well.

**Comment by conorsch** [comment]
Today I built new a new kernel based on 4.14.188, but haven't tested it in VMs yet. I'll move forward with those sanity-checks tomorrow, then proceed with a PR to include in apt-test repos.

**Comment by rmol** [comment]
Fixed by #5365. Closing.
