### ISSUE TITLE
Docs build fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5384]
As reported here https://github.com/freedomofpress/securedrop/pull/5371#issuecomment-659318974 `make docs` targets (which depend on a virtualenv) currently fail on Ubuntu 20.04 due to incompatibilities with the pinned version of the requirements. Given that we can expect an increasing number of developers to be on 20.04 (especially after the August 6 point release which will trigger `do-release-upgrade` notifications), we should aim to resolve.

**Comment by gonzalo-bulnes** [comment]
> Are you able to get the docs-build to work if you update [cffi and ruamel.yaml] locally?

Short answer is yes for `make docs-lint` (that builds the docs); but I'm not positive on `make docs-linkcheck` yet. (I think so, because [it runs without warnings or errors until it stops](https://github.com/freedomofpress/securedrop/pull/5387).)

**Comment by gonzalo-bulnes** [comment]
Note: this may be relevant to https://github.com/freedomofpress/securedrop/issues/4768.
