### ISSUE TITLE
[1.5.0] [QA] v2 onion services files are not removed during v3 migration, so deprecation warning still shows 

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop#5400]
## Description

During QA, I experienced the following: When migrating to v3 onion services, v2 onion services (`ths`) files were not removed from `install_files/ansible_base` on the Admin workstation, and the `/var/lib/securedrop/source_v2_url` file was still present on the app server (though the v2 url was no longer working).  This means that the v2 deprecation warning, which checks for the presence of the latter file, will still be shown despite v2 onion services being disabled.

See https://github.com/freedomofpress/securedrop/pull/5366/files#diff-4c2318c651fa1f217d6b6ed48e77e201R176 

## Steps to Reproduce

1. Clean install 1.5.0-rc2 with v2+v3 onion services enabled. Confirm presence of deprecation warning. 
2. `sdconfig` to disable v2.
3. `install`, `tailsconfig`
4. Observe deprecation warning and aforementioned files.

## Expected Behavior

No warning is shown

## Actual Behavior

Deprecation warning still present

**Comment by sssoleileraaa** [comment]
Good find! What if we add logic in the install script to delete the `source_v2_url` file if the config removes v2 rather than disables it? Or, we could move the file, if it exists, to a documented location somewhere.

**Comment by zenmonkeykstop** [comment]
Yep, I can't remember off the top of my head how Ansible creates this file but there should be a check in the appropriate role to enforce its existence or absence based on `site-specific`.

**Comment by rmol** [comment]
https://github.com/freedomofpress/securedrop/blob/d2c5bef5dd54171511416d1bac641046f17e5e6f/install_files/ansible-base/roles/app/tasks/copy_tor_url_info_to_app_dir.yml#L18
