### ISSUE TITLE
Document potential "some index files failed to download" error on Ubuntu 12.04.5

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#541]
I've been installing SecureDrop on VM's this week, and ran into some unexpected problems with the latest release of Ubuntu 12.04 (precise). We've been using 12.04.4, but 12.04.5 was [released](http://fridge.ubuntu.com/2014/08/08/ubuntu-12-04-5-lts-released/) on 8/8 and is now the recommended version to install.

In ubuntu_config.md, we _say_ the servers require 12.04.4, but the link goes to Ubuntu's 12.04 release page and the links at the top default to 12.04.5. In the [install guide](https://github.com/freedomofpress/securedrop/blob/develop/docs/install.md#before-you-begin), we specify 12.04.5. As a docs nit, this should be the same across all of our documentation.

More importantly, I've been having issues with apt on 12.04.5. STR:
1. Install 12.04.5, following the instructions in ubuntu_config.md
2. After rebooting, `apt-get update` per the instructions in ubuntu_config.md.

Expected: update works without issues

Actual: Several update files fail to download, with a "Hash Sum Mismatch" error. This leave apt in an inconsistent and broken state - for example, try `apt-get install build-essential` after the bad update.

In the ubuntu freenode channel, I was directed to run a [fixpackage](https://dl.dropboxusercontent.com/u/8850924/fixpackage) script to resolve these issues. This did indeed fix the problem. However, I think it's ridiculous that apt would be in a broken state immediately after a fresh install, and I'm worried that this will cause problems for new deployments.

I'm going to continue examining 12.04.5 to see if I can understand what is causing the problem. We should either specify and provide links to 12.04.4, which works without problems, or provide documentation for using the fixpackage script on 12.04.5 if users encounter this issue.

**Comment by dino74** [comment]
Just in case you were wondering what is causing the problem on 12.04.5 server 
https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1430648
