### ISSUE TITLE
Generating desktop icon templates with i18n_tool.py generates review noise

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5426]
## Description

When compiling the desktop icon templates for 1.5.0, `i18n_tool.py` produced [output](https://github.com/freedomofpress/securedrop/commit/706424c3a) that only differed in the sorting of the `Name` lines. There's no `--sort-output` argument to `msgfmt` as there is for `xgettext`, but we could open up the generated template and sort those lines ourselves. This could save the localization managers the time it takes to examine the diff, only to find nothing should have changed.

**Comment by kushaldas** [comment]
My point would be to open up the `.j2` file after the `msgfmt` call, and then sort properly. I will wait for @zenmonkeykstop's comment on this.
