### ISSUE TITLE
Update removed `platform.linux_distribution` funtion call in Python 3.8

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5433]
## Description

We are using [platform.linux_distribution](https://github.com/freedomofpress/securedrop/blob/4c73102ca9151a86a08396de40163b48a5a21768/securedrop/source_app/api.py#L20) function in our metadata endpoint. But, this function was deprecated from Python3.5 and totally removed from Python 3.8. 

## Solution

We can directly read the `/etc/lsb-release` and `/etc/os-release` file as required.

**Comment by kushaldas** [comment]
#4768 is dependent on this.

**Comment by DrGFreeman** [comment]
@kushaldas and @eloquence, I can take care of this if it's OK with you.

**Comment by eloquence** [comment]
That would be awesome, thanks @DrGFreeman :)
