### ISSUE TITLE
Periodically send email notifications to journalists

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#544]
Some deployers have requested email alerts for when they receive submissions, or for other similar events. The current recommendation is to periodically check the Journalist Interface manually, which is cumbersome.

Such a feature would have to be carefully designed to avoid leaking information about submissions. For example, it's easy to see how sending an email immediately for every submission leaks useful information to adversaries that could be used to identify sources.

An alternative approach would be to send an alert at a regular interval, say every day or week, with a digest of events that occurred. This email should also be padded to avoid leaking information about the number of type of events that occurred in the interval.

Finally, any such email should be encrypted to a key provided by the journalist who wants to receive these notifications.

**Comment by stevepimen** [comment]
Setup a trigger in DB would be more "deep-root" ;) solution that would complain with any security requirements.

**Comment by garrettr** [comment]
@stevepimen DB triggers are a bad idea in general, and especially in this context. We do not want to have a signal (such as sending email) that leaks timing information about the behavior of sources. A DB trigger on recording a new submission in the database obviously fails to achieve this security goal.

**Comment by eloquence** [comment]
Submission email notifications are described in #1195 and being implemented (as a simple yes/no notification) in #2803. Other types of notifications should be filed as separate issues, ideally tightly scoped. Closing this one.
