### ISSUE TITLE
Create symlink for the mod_wsgi.so in Python 3.8

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5445]
In Python 3.8 on Ubuntu `Focal` when the mod_wsgi configuration gets generated, it points to 

```
/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.so
```

But, the real shared library path is 

```
/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/mod_wsgi/server/mod_wsgi-py38.cpython-38-x86_64-linux-gnu.so
```

We should make sure that Apache/mod_wsgi should be able to find the correct shared library and load it.

This is part of the #4768 EPIC

**Comment by conorsch** [comment]
See further details in #5443. Turns out a symlink is not required, so closing.
