### ISSUE TITLE
Optionally include file attachments when generating server data with `make dev`

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop#5451]
## Description

To support https://github.com/freedomofpress/securedrop-client/issues/1140 and make setting up dev servers more configurable in a scriptable way, I propose that we support adding document attachments when we run `make dev` in a predictable way that can be used in our functional tests. 

For our first iteration, the simplest thing to do would be to add a `hello.txt` attachment with the contents of `hello`, or something similar to this, across all sources in the data generated by the `create_dev_data.py` script. If we add a new argument called `NUM_DOCS` then we could default to 0 or 1 for each source, and eventually add support to randomize configuration data if we don't want all sources to have files and we want contents to vary (for uses outside of functional tests). For now, it would be a huge improvement just to be able to add a doc at `make dev` time.

**Comment by eloquence** [comment]
+1, I've often wanted this when testing the client.
