### ISSUE TITLE
Improve logic for generate_unique_codename

### ISSUE THREAD

**Issue by prateekj117** [freedomofpress/securedrop#5455]
It's always better and more protected to use while with conditional instead of using `while True`. I came across this while working on #2043 and realized that `generate_unique_codename` actually uses an infinite loop. 

https://github.com/freedomofpress/securedrop/blob/96debdc98be53bafac89b5ddaea761a0f71894fa/securedrop/source_app/utils.py#L40-L46

I took a different approach and used the while with conditional pattern in `display_id`.  If for some reason, the `if` condition gets changed in code and it's not visible in the review that we have an infinite loop depending on that if conditional, we might end up with an infinite loop in the code.

Proposed  solution:
Use the similar logic pattern as in #5381

**Comment by prateekj117** [comment]
@eloquence @rmol @kushaldas Need your view on this.

**Comment by eloquence** [comment]
@prateekj117 I agree with your reasoning. I defer to our maintainers but I think we'd likely accept a PR to this effect.
