### ISSUE TITLE
Support disabling v2 deprecation warning in development environment

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5456]
The Docker dev env currently displays the deprecation warning added in #5366:

> Update Required: Your SecureDrop servers are still running v2 onion services ..

That means it's also in the generated screenshots. This may be fine for purposes such as Weblate (where it's useful to always see where a deprecation warning is shown), but it's not desirable for documentation, for user test environments, and for screenshot generation for other purposes. I suggest we add an environment variable to suppress the warning, or go the alternative route of turning it off by default.

**Comment by prateekj117** [comment]
@eloquence I will take a look into it. Is the desired behavior to introduce the environment variable and show warning accordingly, or to remove it altogether?

**Comment by eloquence** [comment]
Thanks Prateek! :) I'd suggest turning it off by default and enabling it via environment variable, since all new installs will have v3. Please note that this is only for the Docker-based development environment, the behavior in staging/production should not change.

**Comment by prateekj117** [comment]
@eloquence Cool.

**Comment by eloquence** [comment]
Since we'll likely replace the warning with a Focal EOL warning for 1.8.0 (#5688), this issue has outlived its usefulness. We can consider dev env behavior in the context of #5688.
