### ISSUE TITLE
`make build-debs` is failing on develop

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5471]
## Description

The package build for `xenial` is now failing on `develop`.

## Steps to Reproduce

- [ ] `make build-debs`

## Expected Behavior

All packages should be built properly.

## Actual Behavior

`securedrop-app-code` is failing to build with steps related to python packages installation (most probably pip).

[randomerror.txt](https://github.com/freedomofpress/securedrop/files/5150781/randomerror.txt)

Note: In the `focal_pacakge_bulid` branch `make build-debs-focal` is working. 

## Comments

Suggestions to fix, any other relevant information.

**Comment by emkll** [comment]
Looks like the following diff resolves for me locally (h/t @chigby @SaptakS)

We should understand _why_ this regression occurred. While we pin setuptools in `dev-requirements.txt`, is this specific version of setuptools not used with dh_virtualenv?
```
diff --git a/install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/tasks/main.yml b/install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/tasks/main.yml
index c34bb8542..268b0c87f 100644
--- a/install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/tasks/main.yml
+++ b/install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/tasks/main.yml
@@ -106,6 +106,7 @@
     chdir: "{{ securedrop_app_code_deb_dir }}"
   environment:
     DH_VIRTUALENV_INSTALL_ROOT: "/opt/venvs"
+    SETUPTOOLS_USE_DISTUTILS: "stdlib"
 
 - name: Find newly built Debian package
   find:
```

**Comment by rmol** [comment]
I think [this comment](https://github.com/pypa/setuptools/issues/2350#issuecomment-683512526) explains it well enough.

As far as I've been able to find, only in `dh-virtualenv` 1.0 or later can you specify the version of `setuptools` you want it to use, with the [DH_UPGRADE_SETUPTOOLS](https://dh-virtualenv.readthedocs.io/en/1.2.1/usage.html#envvar-DH_UPGRADE_SETUPTOOLS) environment variable.

Getting a recent version of `dh-virtualenv` to install on Xenial is probably going to take some time, if it's possible at all.

Looks to me like the expedient fix is `SETUPTOOLS_USE_DISTUTILS`.
