### ISSUE TITLE
Upgrade Tor to 0.4.4 series

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5500]
First stable tor release in 0.4.4.x series is out [1] which contains major performance and security fixes. SecureDrop using the 0.4.3.x series which will be end-of-life on February 15th 2021, however we should consider doing it for the next SecureDrop release (1.6.0). The debs are also available on tor's apt mirror [2]

[1] https://blog.torproject.org/node/1921
[2] https://deb.torproject.org/torproject.org/pool/main/t/tor/

**Comment by conorsch** [comment]
Not closing this because the package is only on apt-test. As part of 1.6.0, we'll promote to prod, assuming no problems discovered in QA.

**Comment by emkll** [comment]
Tor 0.4.4.5 has been upgraded as part of the 1.6.0 release (see #5501 )
