### ISSUE TITLE
Make sure that all non-grsec kernels are purged duing install on Focal

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5508]
## Description

This is blocked on  #5507. We have to make sure that no non-grsec kernel is installed on the Focal system.

## Steps to Reproduce

- [ ] `molecule converge -s libvirt-staging-focal`

## Expected Behavior

The command should finish properly.
 
## Actual Behavior

The step for purging all non-grsec kernels will fail as it booted into `5.4.x` series kernel (default in Focal).

## Comments

Suggestions to fix, any other relevant information.

**Comment by conorsch** [comment]
> This is blocked on #5507.

Not so sure... the tasks I'm seeing failing during installation are #5495 and then the assertions that all kernels were removed. At least in libvirt VMs, I'm running a grsec kernel as expected, and removing the other automatically installed kernels is possible if I update the patterns. Haven't tested on hardware (nor on Qubes, in which the staging VMs are created directly from the Ubuntu ISOs), but #5507 can track that follow-up.
