### ISSUE TITLE
Add virtualbox-staging-focal molecule scenario

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5511]
## Description

Just like `libvirt-staging-focal`, we need a `Virtualbox` target `virtualbox-staging-focal` to provide staging support on non-Linux platforms

**Comment by eloquence** [comment]
Given the maintenance burden, let's discuss as a team whether we still want to support this architecture for the staging environment going forward.

**Comment by eloquence** [comment]
We agreed as part of the 4/15 sprint that we're removing VirtualBox support, so this issue is no longer relevant. Closing; see #5904.
