### ISSUE TITLE
make staging-focal starts a Xenial-based environment

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5523]
## Steps to Reproduce

- run `make staging-focal`
## Expected Behavior

- An Ubuntu Focal environment should be created via the `libvirt-staging-focal` scenario.
## Actual Behavior
- An Ubuntu Xenial environment is be created via the `libvirt-staging-xenial` scenario (due to it being the default scenario)

## Comments

It appears the `securedrop_platform_suffic` variable is not passed to `select-staging-env` [1] when invoking it from `create-staging-env` [2]

[1] https://github.com/freedomofpress/securedrop/blob/5bd908f17595183bd3099cbe41087f520750425a/devops/scripts/select-staging-env#L16

[2] https://github.com/freedomofpress/securedrop/blob/5bd908f17595183bd3099cbe41087f520750425a/devops/scripts/create-staging-env#L18

**Comment by conorsch** [comment]
Whoops. I've still been using `molecule converge -s libvirt-staging-focal`, haven't even trained myself to use the new target yet. You're right, it definitely doesn't work as described!
