### ISSUE TITLE
Add CI job to run Securedrop application tests on Focal using Python3.8

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5524]
## Description

We need a new CI job to run the SecureDrop application tests on a `Focal` container to run against Python3.8.
This will help us to identify any problem on Python3.8

Steps would be:

- [ ] Add a new Dockerfile for Focal and SecureDrop environment
- [ ] Add a `make dev-focal` target to run the app code in the Focal dev container
- [ ] Add `make test-focal` target
- [ ] Add a separate CI job for `make test-focal`

**Comment by eloquence** [comment]
To get early visibility of breakage, we've agreed to pull this into the current sprint as a stretch goal, _except_ for the CI job, which should wait until after 1.6.0.
