### ISSUE TITLE
Consider using an if statement

### ISSUE THREAD

**Issue by pnijhara** [freedomofpress/securedrop#5548]
*This is a good first issue for new contributors to take on, if you have any questions, please ask on the task or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!*

In file `admin/securedrop_admin/__init__.py`, line 518 (https://github.com/freedomofpress/securedrop/blob/develop/admin/securedrop_admin/__init__.py#L518), we can use an `if` statement.

Current code:
```python
517        if type(default) is bool:
518            default = default and 'yes' or 'no'
```

Updated code:
```python
 517        if type(default) is bool:
 518            default = 'yes' if default else 'no'
```

Reason:
 Using `[condition] and [on_true] or [on_false]` may give wrong results when `on_true` has a false boolean value. Though I am not sure about it. However, the `if` expression is more readable and straight forward.

PS
Went through the codebase and found this one, thus opened the issue and not for the sake of the T-shirt!

**Comment by legoktm** [comment]
Note that the code has moved down to https://github.com/freedomofpress/securedrop/blob/develop/admin/securedrop_admin/__init__.py#L569

I agree that the code as you've proposed is cleaner and easier to logically read.

**Comment by SethAngell** [comment]
I'll hop on this if it's still available!
