### ISSUE TITLE
Enable black and isort for this repo

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5551]
We've been trialing `black` and `isort` for auto-formatting Python code in other SecureDrop repos, and are generally happy with the combination. An example configuration can be found here:

https://github.com/freedomofpress/securedrop-client/blob/main/pyproject.toml
https://github.com/freedomofpress/securedrop-client/blob/main/Makefile

We'll want to use the same setup for SecureDrop Core, with the same settings. As with previous migrations (e.g., https://github.com/freedomofpress/securedrop-client/pull/1115), we'll use `.git-blame-ignore-revs` to ensure that original attribution of modified lines is preserved in `git blame` output.

**Comment by eloquence** [comment]
@nabla-c0d3 Perhaps you'd be interested in collaborating with us on this, after the type annotation stuff is merged (will probably still take us a couple of weeks to get through; thanks for all your work on it so far)?

**Comment by eloquence** [comment]
We're aiming to work on this late in the 10/15-10/29 sprint, or early in the following one.

**Comment by eloquence** [comment]
(@rmol is still focused on churning through the PR backlog to make this a bit easier, so bumped back to backlog for now.)

**Comment by eloquence** [comment]
(Doesn't need to be coupled to the next release, removing from milestone for now.)

**Comment by zenmonkeykstop** [comment]
Optimistically adding this to the 2.4.0 milestone, would like to land upcoming large changes first if possible though.

**Comment by legoktm** [comment]
As part of this it would be nice if we could remove the useless `# -*- coding: utf-8 -*-` lines and enforce a newline at the end of every file.
