### ISSUE TITLE
Docs link to architecture diagrams is broken

### ISSUE THREAD

**Issue by DrGFreeman** [freedomofpress/securedrop#5568]
## Description

The link to architecture diagrams in https://docs.securedrop.org/en/latest/development/tips_and_tricks.html#architecture-diagrams is broken.

## Steps to Reproduce

1. Open https://docs.securedrop.org/en/latest/development/tips_and_tricks.html#architecture-diagrams.
1. Click the link to architecture diagrams in the first paragraph (url: https://github.com/freedomofpress/securedrop/tree/develop/docs/diagrams) 

## Expected Behavior

A page opens with architecture diagrams.

## Actual Behavior

Error 404

**Comment by sssoleileraaa** [comment]
ah, looks like we have a few things to iron out in the new securedrop-docs repo. good catch. the link works for our `latest` version of documentation but not for `stable`. will look into fixing tomorrow.

**Comment by sssoleileraaa** [comment]
also https://docs.securedrop.org/en/latest/_images/securedrop-database.png should be replaced by this image: https://github.com/freedomofpress/securedrop-docs/blob/main/docs/diagrams/securedrop-database.png

**Comment by eloquence** [comment]
These changes have just landed in the `main` branch of the docs repo via https://github.com/freedomofpress/securedrop-docs/pull/22, so they're indeed live in the `latest` version only for now. To build a new `stable` version, we can push a `1.6.0-1` tag tomorrow.

**Comment by eloquence** [comment]
Fixed in `stable` now as well: https://docs.securedrop.org/en/stable/development/tips_and_tricks.html#architecture-diagrams
