### ISSUE TITLE
JUI Web UI nits

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#5576]
## Just some Nina Nits
_Possibly to squeeze-into the forthcoming deletion flow work. Because I'm me, I had to._

- [ ] Capitalize the "F" in "Filter by codename"
- [ ] Replace the fontawesome icons with PNGs, for more graceful degradation. See tofu, below.

![image](https://user-images.githubusercontent.com/8262612/95945158-b48c0080-0d9e-11eb-9b43-bde156bfb0be.png)

**Comment by DrGFreeman** [comment]
Hi @ninavizz, the replacement of Font Awesome icons with PNGs is covered in #5546. I proposed to take care of #5546. I could also include the capitalization of the "F" in "Filter by codename" in the same PR.

**Comment by ninavizz** [comment]
@DrGFreeman I would personally love that, thank you so much Dr G! :)
