### ISSUE TITLE
Investigate replacement of `pyotp` with equivalent functionality in `cryptography`

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5613]
## Description

The `cryptography` package contains support for [HOTP/TOTP](https://cryptography.io/en/latest/hazmat/primitives/twofactor.html). We should see if it can do everything we use `pyotp` for. Those two packages are excellent and maintained, but our update protocol is laborious enough that we should eliminate any dependencies we can.

*Edited by @eloquence to reflect removal of `scrypt` dependency, 2021-09-28*

**Comment by evilaliv3** [comment]
@rmol : Actually i come to this evaluation myself within @GlobaLeaks and i just made this change.

Here you can find the code i used to reimplement TOTP by means of python-cryptography: https://github.com/globaleaks/GlobaLeaks/commit/64750f40e7d8b49739cb184fd0e4f7b662c8d0ea

**Comment by rmol** [comment]
Hey, thanks @evilaliv3! That should save us some time. :slightly_smiling_face:

**Comment by nabla-c0d3** [comment]
The dependency to `scrypt` was removed in #5694.

**Comment by eloquence** [comment]
Thanks, retitled accordingly!

**Comment by nabla-c0d3** [comment]
PR at https://github.com/freedomofpress/securedrop/pull/6679 is ready

**Comment by nabla-c0d3** [comment]
PR https://github.com/freedomofpress/securedrop/pull/6679 was merged so this issue can be closed 👍
