### ISSUE TITLE
Resetting journalist password more than once can raise IntegrityError

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5617]
## Description

If a journalist's password is reset twice in quick succession, the second attempt to revoke the two-factor token will trigger an exception:
```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: revoked_tokens.token
[SQL: INSERT INTO revoked_tokens (journalist_id, token) VALUES (?, ?)]
```

## Steps to Reproduce

- Run `make dev`
- Log in as `dellsberg`.
- Log in as `journalist`, visit http://localhost:8081/admin/ and edit the `dellsberg` account. 
- Reset the password once, then again. You should see the `IntegrityError`.

## Expected Behavior

That you could reset the password as many times as you like.

## Actual Behavior

You cannot reset the password as many times as you like.

**Comment by eloquence** [comment]
Was able to reproduce immediately by following the STR.
