### ISSUE TITLE
Restore CodeCov.io functionality to this repo

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5620]
## Description

It looks like Codecov has stopped updating[1] the coverage information when Python2 support was removed in #4859 . We should either: 

1. Restore coverage reports or
2. Remove the badge on the README of this repo. 

[1] https://codecov.io/gh/freedomofpress/securedrop

**Comment by eloquence** [comment]
(At sprint planning today there was broad support for re-enabling this and @zenmonkeykstop offered to investigate. Retitled accordingly.)

**Comment by eloquence** [comment]
@zenmonkeykstop With #5632 and #5657 merged, is there more work left to do to close this issue?

**Comment by zenmonkeykstop** [comment]
It's good to close.
