### ISSUE TITLE
Update Tor to 0.4.4.6

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5624]
## Description

A new version of the stable series was release, which backports bugfixes and also contains a security fix, see https://blog.torproject.org/node/1952

Upstream issue discussing the fix can be found in https://gitlab.torproject.org/tpo/core/tor/-/issues/40080

**Comment by eloquence** [comment]
What's left to consider this issue resolved, and is it really "in development"?

**Comment by emkll** [comment]
The packages are now on live apt-test, but they will be only released to apt.freedom.press with the release of SecureDrop 1.7.0

**Comment by rmol** [comment]
The packages are now in production on apt.freedom.press.
