### ISSUE TITLE
Dual distro support broke "securedrop-admin verify"

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5659]
## Description

When adding support for Focal to the configuration tests in #5529, a check of the `MOLECULE_SCENARIO_NAME` environment variable broke `securedrop-admin verify`, where it's not set.

## Steps to Reproduce

On an admin workstation:
- Run `securedrop-admin setup -t`
- Run `securedrop-admin verify`

## Expected Behavior

That the configuration tests would run.

## Actual Behavior

You get an error [here](https://github.com/freedomofpress/securedrop/blob/76d133a7e5962f8d904e507d93e6a61575358eeb/molecule/testinfra/conftest.py#L31) saying `'NoneType' object has no attribute 'endswith'`. 

## Comments

Should probably check if it's `None` or just add `""` as the default in the `os.environ.get` call.

**Comment by eloquence** [comment]
(Added to 1.7.0 milestone, seems like we want a fix in place before QA begins.)
