### ISSUE TITLE
Make it easier to delete all source data without preventing source login

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5675]
In #5358 we made it clearer that deleting a source account will prevent that source from logging in. Depending on a news organization's workflow, it may be desirable to delete all data associated with a source, while still accepting future submissions from that source.

Currently, this is only possible on the page for an individual source (go to source's page in Journalist Interface -> Select all -> Delete).

We should consider offering an action on the index page (where all sources are listed) to wipe all source data for the selected source(s), but to preserve the source account(s). This would make it possible to wipe multiple sources at once, without preventing all those sources from sending additional information.

The UI will need to clearly distinguish the two behaviors (deleting source accounts vs. only deleting source data).

# User Story

As a journalist, I want to be able to quickly move stuff off the server, without preventing sources from sending more stuff.

**Comment by prateekj117** [comment]
@eloquence Sounds good. I can start looking into this.

**Comment by eloquence** [comment]
Hi @prateekj117, thanks for offering to poke at this issue. We're pretty far along with some user research in support of this work and this may not be the easiest project to collaborate on. If you're looking for a good frontend issue related to deletion, #4649 may be a better pick.

**Comment by prateekj117** [comment]
@eloquence Sure !!!

**Comment by nabla-c0d3** [comment]
@eloquence Is there a use case for not allowing the source accounts to login forever?

I don't know the news organizations' workflow very well, but it could be simpler to just support one logic,: preserving the source accounts around forever, while deleting their associated data when a journalist "deletes" them. Having two kinds of source deletion could add complexity/confusion.

**Comment by eloquence** [comment]
> @eloquence Is there a use case for not allowing the source accounts to login forever?

Yes, to protect source anonymity, an organization may want to erase all trace of communications with a source from the server once the information has been dealt with. (Great question - we share your goal of keeping things as simple as possible!)

**Comment by eloquence** [comment]
Closing as duplicate of #5766, which has more details from recent team discussions.
