### ISSUE TITLE
Some automated screenshots are cropped incorrectly

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5693]
The automated screenshots generated using the functional tests are generally cropped well now, but there are a couple of screenshots that are now cropped incorrectly, possibly due to the page layout change resulting from the organization name feature added in #5629.

<details>
<summary>
Click to expand
</summary>

The OSSEC alert screenshot:
![journalist-admin_ossec_alert_button](https://user-images.githubusercontent.com/213636/104061963-6a07fd80-51ae-11eb-8400-feb46b761b5d.png)

The logo change screenshot:
![journalist-admin_changes_logo_image](https://user-images.githubusercontent.com/213636/104061988-72f8cf00-51ae-11eb-807c-5f0e8f4363ec.png)
</details>

**Comment by eloquence** [comment]
@DrGFreeman Since you worked on the cropping in #4561, any interest in poking at this?

**Comment by DrGFreeman** [comment]
> @DrGFreeman Since you worked on the cropping in #4561, any interest in poking at this?

@eloquence, Sure, I'll have a look.

The cropping I implemented only crops the bottom. Here the cropping occurs at the top on long pages so I believe the size used by the Selenium driver may not be high enough to capture the whole page.

P.S. Sorry for the late reply, I must have missed the GitHub notification and just found this while browsing through the issues.
