### ISSUE TITLE
"securedrop-admin sdconfig" locale selection should prompt with a sorted list

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5698]
## Description

Right now `securedrop-admin sdconfig` vomits a long unsorted list of locale codes at the admin, so making sure the instance is going to wind up with all the locales they need to support is more difficult than it needs to be.

The minimum fix would be returning a sorted list from `SiteConfig.Locales.get_translations`, which would be easier to scan. We could get fancy and use `prompt_toolkit` checkboxes, but at that point we should probably consider tackling #3325.

See also #4248.

**Comment by legoktm** [comment]
@cfm fixed this in https://github.com/freedomofpress/securedrop/commit/fe1f7ee364af131ad1ae402fc18b65fba7896396
