### ISSUE TITLE
Update tor version to improve v3 Onion reliability

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#5699]
## Description

The Tor Project is working on a fix to improve the reliability of v3 Onion Services. See details here: https://gitlab.torproject.org/tpo/core/tor/-/issues/40237

As of this writing, there are no new packages available, but we're monitoring closely and will aim to provide updates via the upcoming 1.7.0 release (#5689) at the latest. When packages are available, we'll place them on apt-test to run CI and QA against them. If no problems are found, we proceed with release to prod.

Let's pay close attention to where updates are required: we may want to mention client (i.e. Tor Browser) upgrades as part of release messaging.

**Comment by eloquence** [comment]
We are continuing to monitor the situation; see latest (January 28) post to the network-health mailing list here that describes a more recent service outage across v3 onion services:
https://lists.torproject.org/pipermail/network-health/2021-January/000662.html

**Comment by eloquence** [comment]
Released as part of 1.8.0.
