### ISSUE TITLE
Cryptography warning message generating unactionable OSSEC alert

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5714]
## Description

With 1.7.0-rc2, OSSEC alerts containing `/var/www/securedrop/secure_tempfile.py:10: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.` are generated on application startup. These will be generated until the move to Focal, so it might be worth suppressing the OSSEC email.

## Steps to Reproduce
Install 1.7.0-rc2, review OSSEC alerts

## Expected Behavior
OSSEC alerts should be actionable and not too noisy

## Actual Behavior
As above.

**Comment by eloquence** [comment]
Given that this warning will go away w/ the Focal migration, we've agreed that we'll just respond to any questions about it on an as-needed basis.
