### ISSUE TITLE
system clock error expected to always happen?

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop#5730]
## Description

We have a check that ensures the system clock is set properly: https://github.com/freedomofpress/securedrop/blob/eb8d03e66b4b2628b78eb4d8a532e2932728d137/install_files/ansible-base/roles/common/tasks/post_ubuntu_install_checks.yml#L37 yet I think we expect it to fail every time because the ntp socket will be in use. In the comment above test, we say to ignore the errors for this task. Then it says: `However, if the command fails for some other reason, we want to fail the task, so we inspect the error output.` Does this mean that we should always check the error output to see if it's an error other than "the NTP socket is in use"? If this is true, then perhaps we should allow the test to succeed if the NTP socket is in use and only fail for unexpected reasons. Otherwise, we could improve what we have now by explaining in the error output that an NTP socket in use error is expected.

**Comment by conorsch** [comment]
It's the `ignore_errors: yes` that causes the scary red warnings to be printed to the screen during the run. We can instead use `failed_when:` with the logic in the subsequent task:

https://github.com/freedomofpress/securedrop/blob/eb8d03e66b4b2628b78eb4d8a532e2932728d137/install_files/ansible-base/roles/common/tasks/post_ubuntu_install_checks.yml#L49

Then the task will always show green/happy, unless the command exits non-zero with a different string, in which case it'll fail hard and stop the playbook, which is what we want.
