### ISSUE TITLE
Remove support for v2 Onion Services

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5731]
## Description

Tor Onion Services V2 support will be disabled in clients on October 15th 2021 [1]
In https://github.com/freedomofpress/securedrop/issues/2951, we introduced support for v3 onion services, and #4768 , we on restricting the use of Onion Services to v3-only

This ticket is to track the removal of all onion service v2 functionality alongside the transition to Ubuntu 20.04.

[1] https://blog.torproject.org/v2-deprecation-timeline

**Comment by sssoleileraaa** [comment]
we should probably remove outdated tor2web logic as part of this effort as it no longer seems to be maintained. @redshiftzero pays closer attention to the ongoings in torland, mind providing feedback here?

**Comment by redshiftzero** [comment]
Since there isn't v3 support in tor2web and it hasn't had commits in a couple years (I also couldn't find any working relays), I think it's fine to remove... if Tor2Web sees a big resurgence of use you could add it back if/when that happens
