### ISSUE TITLE
Misplaced "No Collections Selected" error on JI

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#5754]
## Description

When I fail to select any Sources from the All Sources page of the JI, and click "Delete," I am immediately taken to the "Delete Confirmation" overlay, indicating a deletion is about to happen. When I click "Delete," I am then told that nothing was selected. That is a bit bait-and-switch.

## Steps to Reproduce

1. Log into JI
2. Click "Delete" on All Sources page
3. Click "Delete" on overlay
4. Observe error bubble

## Expected Behavior

Upon clicking "Delete" from the All Sources page, without any objects selected, I should get the warning and not the overlay. Only the overlay, if objects are selected. If that would require JS, I'm ok with limiting this fix to the JS-only version.

## Actual Behavior

I get the error bubble after confirming a delete action in the overlay against 0 objects. A little confusing today; a lot more confusing when _Safe Delete_ is pushed.

<img width="830" alt="Screen Shot 2021-01-26 at 4 28 14 PM" src="https://user-images.githubusercontent.com/8262612/105925391-e5620f80-5ff4-11eb-9202-6d8062a2aa6c.png">
<img width="948" alt="Screen Shot 2021-01-26 at 4 32 29 PM" src="https://user-images.githubusercontent.com/8262612/105925396-e8f59680-5ff4-11eb-9f9c-95f6c06723d6.png">

**Comment by ninavizz** [comment]
/cc #5675 and @zenmonkeykstop to potentially include this into Safe Delete work. TL;DR, it'll look wacky to show `0 Sources are selected. What would you like to delete?`

## w/o this issue resolved
<img width="915" alt="Screen Shot 2021-01-26 at 5 05 19 PM" src="https://user-images.githubusercontent.com/8262612/105927409-c8c7d680-5ff8-11eb-8cc4-b5f4118fba4d.png">

## Modal shd only show when items are selected
<img width="915" alt="Screen Shot 2021-01-26 at 5 03 08 PM" src="https://user-images.githubusercontent.com/8262612/105927212-68389980-5ff8-11eb-9bdb-a0f0e8db3146.png">

**Comment by ninavizz** [comment]
Addenda: If this is tackled with the Safe Delete updates, because we're seeking to eliminate use of the word "Collections" and the current error message follows a ux anti-pattern (telling the user what they did wrong vs telling the user what they need to do, in addition to what they did wrong).

## Updated Error Text Recc
`<b>Nothing Selected</b> Please select one or more source accounts for deletion.`

(yup, w/o a period at the end of the first statement)

**Comment by zenmonkeykstop** [comment]
Addressable for the JS-enabled case.

**Comment by eloquence** [comment]
This was resolved via #5770 when JavaScript is enabled. We'll likely have to live with it for the no-JS experience.
