### ISSUE TITLE
Python/pip issues running securedrop-admin in Docker container

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5764]
## Steps to reproduce
1. Enter dev shell via `./securedrop/bin/dev-shell`
2. Attempt to satisfy `securedrop-admin` requirements via steps in https://docs.securedrop.org/en/stable/development/admin_development.html

## Expected behavior

Requirements are installed successfully and I can run `securedrop-admin` in the development shell.

## Actual behavior

I encountered two issues:
- I was unable to run `pip` itself in the `virtualenv`, which failed with a `SyntaxError` on `sys.stderr.write(f"ERROR: {exc}")` as described [here](https://stackoverflow.com/questions/65896334/python-pip-broken-wiith-sys-stderr-writeferror-exc)
  - I resolved this by manually installing pip in the virtualenv using https://bootstrap.pypa.io/3.5/get-pip.py
- When attempting to actually install the dependencies, I then encountered this issue with `setuptools` on Python 3.5: https://github.com/pypa/setuptools/issues/2541
  - I resolved this by downgrading `setuptools`

**Comment by eloquence** [comment]
Questions:
- What steps should we recommend in the docs?
- Are any changes necessary to improve the developer story, or to avoid spillage of these types of issues into production contexts?

**Comment by emkll** [comment]
Does this error also occur when using the admin dev shell container? https://github.com/freedomofpress/securedrop/blob/8cf9bc37cd68f0db3dee4fef7c279f299184c6fa/admin/bin/dev-shell

**Comment by eloquence** [comment]
It does not, thanks: I did not realize we had two different `dev-shell`s! I'll make a small docs PR to clarify.

(One thing that's still a bit confusing is that the `admin/bin/dev-shell` command is completely silent for several minutes while the image is being built, due to the use of output redirection.)
