### ISSUE TITLE
If a source's store directory is missing, subsequent submission attempts will fail with a FileNotFoundError exception

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5787]
## Description

As per title.

## Steps to Reproduce

(in dev)
- log in to the SI and submit.
- in a shell on the dev docker container (`docker exec -it securedrop-dev-0 bash`) find and delete the source's directory under `/var/lib/securedrop/store/` 
- submit from the SI again as the same source 

## Expected Behavior
Either:
- submission succeeds and directory is recreated,
Or:
- Submission fails with an informative error

## Actual Behavior
uncaught FileNotFoundError and a stack trace (in dev)

Suggestions to fix, any other relevant information.

**Comment by eloquence** [comment]
> submission succeeds and directory is recreated,
> Or:
> Submission fails with an informative error

All things considered, I would suggest going with the first option: recreate the directory.

1) This is not a state that should arise during normal operation, but
2) Admins may accidentally or intentionally wipe the `store` directory to clean out files and messages;
3) This approximates a "file and messages" deletion operation through the UI;
4) Locking out individual sources or large numbers of them can cause significant opsec issues in its own right as they recreate accounts and passphrases.

That said, it may be good to at least log an error or OSSEC alert in this case. Thoughts from others?

**Comment by prateekj117** [comment]
@eloquence Sounds good. Can I take this up?

**Comment by prateekj117** [comment]
@zenmonkeykstop @rmol @kushaldas May I take this up?

**Comment by eloquence** [comment]
@prateekj117 It would be great if you could take a first stab at this, for sure!
