### ISSUE TITLE
Apparmor denial for ntpd on Focal

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5795]
## Description

`ntpd` throws grsec denial message.

## Steps to Reproduce

- [ ] Install focal on hardware (I hope the same will show up in vm too)
- [ ] check `/var/log/syslog`

## Expected Behavior

- no grsec error from ntpd

## Actual Behavior

```

Feb 17 03:43:33 app systemd[1]: Starting Network Time Service... Feb 17 03:43:33 app kernel: [  202.428911] audit: type=1400 audit(1613533413.416:46): apparmor="DENIED" operation="open" profile="/usr/sbin/ntpd" name="/snap/bin/" pid=3303 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 Feb 17 03:43:33 app ntpd[3303]: ntpd 4.2.8p12@1.3728-o (1): Starting Feb 17 03:43:33 app ntpd[3303]: Command line: /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 112:117 Feb 17 03:43:33 app ntpd[3306]: proto: precision = 0.175 usec (-22)
--
```

## Comments

Suggestions to fix, any other relevant information.

**Comment by conorsch** [comment]
At standup today, @rmol mentioned he'd seen this one, too. Since we're adding ntp to Focal, conceivable we can just stop doing that, and let systemd-timesyncd do its thing.
