### ISSUE TITLE
`deb-tests-focal` in CI is failing with: ERROR: Unable to contact the Docker daemon

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop#5799]
Looks like PRs are blocked due to an issue with CI and Docker for Focal. Here are the two PRs I'm looking at that are failing:

* https://github.com/freedomofpress/securedrop/pull/5789
* https://github.com/freedomofpress/securedrop/pull/5798

This is the error:

`ERROR: Unable to contact the Docker daemon. Please refer to https://docs.docker.com/config/daemon/ for managing the daemon`

Xenial works fine - it's just failing during `make ci-deb-tests-focal`. This is the setup for the test in `.circleci/config.yml`:

```yml
  deb-tests-focal:
    docker:
      - image: cimg/python:3.7
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - run: sudo apt-get update && sudo apt-get install -y make virtualenv enchant jq python3-dev build-essential rsync
      - checkout
      - setup_remote_docker
      - run:
          name: Test Debian package build on Focal
          command: |
            make ci-deb-tests-focal
```

Which looks a lot like the test run for xenial, which is passing:
```yml
  deb-tests:
    docker:
      - image: cimg/python:3.7
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - run: sudo apt-get update && sudo apt-get install -y make virtualenv enchant jq python3-dev build-essential rsync
      - checkout
      - setup_remote_docker
      - run:
          name: Test Debian package build
          command: |
            BRANCH_MATCH=$(devops/scripts/match-ci-branch.sh "^update-builder")
            if ! [[ $BRANCH_MATCH =~ ^found ]]; then echo "Skipping: ${BRANCH_MATCH}"; exit 0; fi
            make ci-deb-tests
```

When following the troubleshooting instructions linked to in the error message above, I run into this issue:

```
> sudo dockerd
...
WARN[2021-02-17T22:28:28.123237715Z] Running iptables --wait -t nat -L -n failed with message: `iptables v1.8.4 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.`, error: exit status 3 
INFO[2021-02-17T22:28:28.141310086Z] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2021-02-17T22:28:28.141546051Z] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2021-02-17T22:28:28.141564293Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.4 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
```

**Comment by conorsch** [comment]
Thanks for failing, @creviera. No sign of any problems on https://status.circleci.com/ right now. At a glance, this looks like a CircleCI problem, and not anything to do with recent changes we've made. 

Here's an example of the failure: https://app.circleci.com/pipelines/github/freedomofpress/securedrop/1906/workflows/341b6a13-0e58-488d-a95c-969dc2e877d2/jobs/50615

**Comment by kushaldas** [comment]
I pushed a commit https://github.com/freedomofpress/securedrop/pull/5793/commits/cc9b2a64378f586e7fef38d4bf17cdce592f74fb to the https://github.com/freedomofpress/securedrop/pull/5793 once CI passes, and the PR is merged. We have to rebase all other open PRs.

**Comment by kushaldas** [comment]
Here is an independent PR https://github.com/freedomofpress/securedrop/pull/5801 maybe we can merge this first and then all the other PRs can be rebased.
