### ISSUE TITLE
Update Tor to 0.4.5.6

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5802]
## Description

A new version of the stable series was released[1], contains bugfixes and improvements to V3 onion service reliability [2] (Tor 0.4.4.7 Debian packages for xenial and focal were never released on Tor Project's apt mirror)

[1] https://blog.torproject.org/node/2000
[2] https://gitlab.torproject.org/tpo/core/tor/-/issues/40237

**Comment by emkll** [comment]
The packages are now being served by apt-test, and should be released to existing instances as part of SecureDrop release 1.8.0

**Comment by eloquence** [comment]
Released as part of 1.8.0.
