### ISSUE TITLE
ipv6 not completely disabled on Focal

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5807]
## Description

We disable ipv6 on Xenial via [sysctl](https://github.com/freedomofpress/securedrop/blob/33f94c913dab88fa24cee023eb0c8abe7553b4f7/install_files/ansible-base/roles/common/defaults/main.yml#L41).

On Focal, this isn't enough, as netplan assigns a link-local v6 address to an interface by default, which results in ipv6 not being disabled for that interface (check, for example, `cat /proc/sys/net/ipv6/conf/eno1/disable_ipv6`). See the `netplan` [man page](https://manpages.ubuntu.com/manpages/eoan/en/man5/netplan.5.html).

## Steps to Reproduce

Build a Focal instance. Check whether ipv6 is disabled for the default interface with `cat /proc/sys/net/ipv6/conf/eno1/disable_ipv6`.

## Expected Behavior

That with our array of sysctl options, we'd have managed to disable ipv6 for any and all interfaces.

## Actual Behavior

That netplan knows better.

## Comments

I've tested two solutions. Adjusting the netplan configuration for all configured interfaces to include `link-local: []` works, but adding `ipv6.disable=1` to the grub kernel command line is the simpler option and definitively disables ipv6 everywhere. I've run into problems with that in my Qubes staging environment, though, and need to test it as part of the install on hardware, as opposed to adding it in manually after the fact.

**Comment by conorsch** [comment]
Thanks for reporting, @rmol. I'll take a look at this today. I address that the grub command line approach is going to be the most solid. Will test on Qubes staging first, and see if I can reproduce any of the trouble you mentioned. Let's make sure we add tests to ensure that the VMs don't have ipv6 addresses on any interface, as well:

```
sdadmin@app-staging:~$ sudo ip -4 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 10.137.0.50/24 brd 10.137.0.255 scope global eth0
       valid_lft forever preferred_lft forever
sdadmin@app-staging:~$ sudo ip -6 addr
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::216:3eff:fe5e:6c00/64 scope link 
       valid_lft forever preferred_lft forever
```
