### ISSUE TITLE
Crash logs present in /var/crash 

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5815]
## Description

Initially reported by @kushaldas during 1.8.0 QA
> Why is there a /var/crash/_usr_bin_lscpu.1000.crash file on both the servers?

`/var/crash` contains kernel crash dumps [1] and should be investigated.

## Steps to Reproduce
On app or mon, `ls /var/crash`
## Expected Behavior

- `/var/crash/` should not contain any files
## Actual Behavior

`/var/crash/_usr_bin_lscpu.1000.crash` is present on `app` and `mon`
## Comments

I could not reproduce this in VMs, but we should track and see if others can reproduce.

[1] https://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html#VARCRASHSYSTEMCRASHDUMPS

**Comment by conorsch** [comment]
As with #5280, could this behavior be related to the spectre/meltdown checker? During QA period, let's keep an eye on that directory, and note particularly if crash reports appear after the meltdown checks, or even after paxtest.

**Comment by eloquence** [comment]
No additional reports since QA (I also don't see it on my prod instance), as noted above, likely the result of security tests during QA.
