### ISSUE TITLE
What is perl doing here?

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5820]
## Description

On a Xenial box with 1.8.0rc1, I can see this following `grsec denial` errors. 

```
Feb 25 08:23:26 app-prod kernel: [  361.202196] grsec: From 10.0.1.53: denied write to CPU MSR by /usr/bin/perl[perl:2898] uid/euid:0/0 gid/egid:0/0, parent /
bin/dash[sh:2748] uid/euid:0/0 gid/egid:0/0
Feb 25 08:23:26 app-prod kernel: [  361.249944] grsec: From 10.0.1.53: denied write to CPU MSR by /usr/bin/perl[perl:2931] uid/euid:0/0 gid/egid:0/0, parent /
bin/dash[sh:2748] uid/euid:0/0 gid/egid:0/0

```

**Comment by emkll** [comment]
Thanks for opening @kushaldas. Do the timestamp coincide with running the spectre/meltdown checking script? A previous (related) issue opened on this topic: https://github.com/freedomofpress/securedrop/issues/5040

**Comment by conorsch** [comment]
To @emkll's point, sure looks like https://github.com/speed47/spectre-meltdown-checker/blob/08e30e156dab6d32a549aab83486920b4ad65970/spectre-meltdown-checker.sh#L2366

**Comment by kushaldas** [comment]
Thank you for the replies, I think I can close this now.
