### ISSUE TITLE
Grammatical error in flash message after deleting source account

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5822]
## Description

After deleting a source account, we flash "Success! The account and data for the source {} has been deleted." 

Perhaps "The account and data for the source {} _have_ been deleted."

([Suggested](https://weblate.securedrop.org/translate/securedrop/securedrop/en/?checksum=b359855176c2dea2) by @ekcnl)

**Comment by eloquence** [comment]
*have* is indeed correct, will fix.
