### ISSUE TITLE
1.8.0 translation feedback: warning when deleting a source

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5823]
## Description

AO [suggested](https://weblate.securedrop.org/translate/securedrop/securedrop/en/?checksum=683531028fe964b4) that we change:
```
The source will not be able to log in with their codename again.
```
to
```
The source will no longer be able to log in with their codename.
```

**Comment by eloquence** [comment]
Both versions seem fine to me but the second one does read a little bit more smoothly, will make the change if no concerns.
