### ISSUE TITLE
1.8.0 translation feedback: Focal upgrade warning

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5824]
## Description

AO [suggested](https://weblate.securedrop.org/translate/securedrop/securedrop/en/?checksum=c775f74150ac3872) changing `A manual update is urgently required to remain safe.` to `A manual upgrade is urgently required to remain safe.` in:

```
<strong>Critical Security:</strong>&nbsp;&nbsp;The operating system used by your SecureDrop servers 
will reach its end-of-life on April 30, 2021. A manual update is urgently required to remain safe. 
Please contact your adminstrator. <a href="//securedrop.org/xenial-eol" rel="noreferrer">Learn More</a>
```

as well as [here](https://weblate.securedrop.org/translate/securedrop/securedrop/en/?checksum=60e0284e103e2c51):
```
<strong>Critical Security:</strong>&nbsp;&nbsp;The operating system used by your SecureDrop servers 
has reached its end-of-life. A manual update is required to re-enable the Source Interface and remain safe. 
Please contact your administrator. <a href="//securedrop.org/xenial-eol" rel="noreferrer">Learn More</a>
```

There's also a typo in the first string: "adminstrator" needs another "i".

**Comment by eloquence** [comment]
:+1: to  update->upgrade and typo fix (good catch!)
