### ISSUE TITLE
1.8.0 translation feedback: say replies are saved, not stored

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#5828]
## Description

From [AO](https://weblate.securedrop.org/translate/securedrop/securedrop/en/?checksum=a6f950dfa57047f3): "Your reply has been saved." might be better than "Your reply has been stored."

**Comment by eloquence** [comment]
Fun fact - that language goes back to the AaronSw days of SecureDrop (8b1b3580137a57c76f27a9c90101926255da2b5b). I agree "has been saved" is a bit more friendly. I don't see that string having changed in the last development cycle though, am I missing something? If not I would be inclined to wait with this change until after 1.8.0.

**Comment by rmol** [comment]
The language has not changed, but the construction of the flash message did, which resulted in the message being broken up into two, which now need to be translated separately. If we're going to change "stored" to "saved", it would save work to do it now.

**Comment by eloquence** [comment]
Discussed a bit more with @ninavizz. We don't think a single word change would make this message significantly more user-friendly, and would like to suggest revising it fully for a future release. The problem that `stored` and `saved` share is that they only speak to the technical completion of an operation, and don't clearly relate to the journalist's intent (talking to a source). In fact, `saved` is often associated with saving drafts (e.g., in email apps) that then later have to be sent. As jargon-y as it is, `stored` at least is not typically used in this fashion.

That said, the message should definitely be improved. A message that more explicitly speaks to the journalist's intent (e.g., "Success! The source will be able to read your reply next time they log in" or something to that effect) would  perhaps work better. We can discuss that a bit more here.

Even though the structure of the message has changed for 1.8.0, the word `stored` has previous translations, so for now, I would suggest just retaining those translations.

**Comment by zenmonkeykstop** [comment]
"posted" is also an option - implies that it has yet to be  "delivered."
