### ISSUE TITLE
Screenshot utility script should be removed from  packages

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5832]
## Description

The file `securedrop/upload-screenshots.py` used for updating Weblate resources is being added into the `securedrop-app-code` package. 

It's not directly accessible and is blocked by apparmor, but should be excluded from the package build anyway for hygiene reasons.

**Comment by conorsch** [comment]
Sounds good, that's what we have https://github.com/freedomofpress/securedrop/blob/70b31deed05053853d41b3041532e0a1fff6b320/securedrop/.rsync-filter for.

**Comment by eloquence** [comment]
(I'm interested in poking at this before 2.0.0, but given other commitments, kicking back to near-term backlog for now.)
