### ISSUE TITLE
Exclude SSH tor config from server restores

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5833]
## Description

 SSH onion service configurations should not be restored from backups:

- in the scenario where you're restoring onto a server with the same tor config as the backup, it doesn't do anything
- in the scenario where you're restoring over a fresh install, it breaks a working ssh config, currently requiring manual intervention to fix
 
A migration without restoring ssh configs would look like:
- install fresh (using old `tor_v3_keys.json` if safe and available)
- restore - old data  and ji/si onion addresses now in place, fresh install SSH config preserved 
- run install - old ji/si auth keys overwritten with new ones (only required if old `tor_v3_keys.json` not used in install
- run tailsconfig - ji/si tails-side configs updated

## User Research Evidence

Anecdotal based on experience testing migration flows in 1.8.0-rc1

## User Stories

As an admin, I want to be able to perform a restore or migration with minimal manual steps and without the risk of breaking SSH access and needing to fix it in person.

**Comment by conorsch** [comment]
Migration would be a heck of a lot simpler if we were to stop restoring SSH services, and just stick with what's new. The only downside would be that organizations with multiple administrators, each using their own Admin Workstation USB stick, would need to synchronize the new service info out of band. In all other circumstances, it's a lot simpler and more straightforward to reuse the new v3-only services created on the new host.

**Comment by zenmonkeykstop** [comment]
For orgs doing the Focal migration over the next month or two who are not already on v3, they'll need to do that oob sync regardless.

**Comment by zenmonkeykstop** [comment]
I'm gonna defer this to 1.9.0 unless there are objections. Sorting out the migration process took longer than expected, and it only saves a couple of steps in that process. It would save more if the client-side Tor config files were rebuilt as part of the process (as opposed to being manually copied into place) but that's a bit much to take on during the QA period.

**Comment by eloquence** [comment]
(Added `needs/docs` because the backup/migration guide will need to be updated.)
