### ISSUE TITLE
(Focal) Failure enabling systemd-timesyncd: "service is masked"

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop#5840]
## Description

Installing SecureDrop 1.8.0-rc1 on Focal on hardware (NUC7s), I'm consistently encountering an error during the `Ensure systemd-timesyncd service is enabled` task:

`Unable to enable service systemd-timesyncd: Failed to enable unit: Unit file /etc/systemd/system/systemd-timesyncd.service is masked.` 

## Steps to Reproduce

- Install Focal on hardware
- Fresh clone of SD repo, (reuse tor_v3_keys.json)
- Checkout 1.8.0-rc1 and modify `install-fpf-repo/...main.yml` to use apt-test repo and apt-test key as per QA procedures 
- Complete pre-install steps then install from scratch using `./securedrop-admin --force install`.

## Expected Behavior
1.8.0-rc1 installed on servers

## Actual Behavior
On both app and mon:
`Unable to enable service systemd-timesyncd: Failed to enable unit: Unit file /etc/systemd/system/systemd-timesyncd.service is masked.`

**Comment by zenmonkeykstop** [comment]
FWIW I did not observe this during my most recent install, and the service is up and running on my boxen.

**Comment by rmol** [comment]
I am so far unable to reproduce the error; my test run had no problem with `Ensure systemd-timesyncd service is enabled`.

**Comment by conorsch** [comment]
I haven't seen this, either. However, it might be worthwhile explicitly setting `masked: no` on the relevant task: https://github.com/freedomofpress/securedrop/pull/5806/files#diff-ae5be923cdf2cac58831b9ea69297001a39085628927b7c6a55e4a994f41803fR76-R81

**Comment by rocodes** [comment]
I'm going to reinstall Focal and see if even I can repro. (My reference to "consistently" was on repeated `install` attempts, but I'll try wiping now)

**Comment by rocodes** [comment]
I wiped and reinstalled Focal and 1.8.0-rc1 did not reproduce my original issue. Maintainers feel free to close if you wish.

**Comment by rmol** [comment]
@conorsch I added #5842 to unmask the service. Don't think it's strictly necessary, but wouldn't hurt either, other than the extra review and testing time.
