### ISSUE TITLE
The Application Server submissions checker runs 60 times a day instead of once.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5847]
## Description

The crontab entry for the script checking for new submissions (for use in journalist alerts) (with a reboot time of 4am) looks like:

```
* 3 * * * /var/www/securedrop/manage.py were-there-submissions-today
```
This will kick off the script every minute from 3am to 4am. If the intent is to trigger it once, it should be more like

```
* 3 0 * * /var/www/securedrop/manage.py were-there-submissions-today
```

## Steps to Reproduce
Check /var/log/syslog on a production system.

## Expected Behavior
There's one log line at 3am for the script.

## Actual Behavior
There's are multiple log lines from 3am  to reboot for the script.

## Comments
The ansible task setting it up needs a "minutes" value, which should just be 0

(This does not look like an issue introduced in 1.8.0. The code in question hasn't been touched since May 2018.)

**Comment by eloquence** [comment]
Since it's not a regression, added to near-term backlog for now.

**Comment by prateekj117** [comment]
@eloquence I can take a look at this.

**Comment by prateekj117** [comment]
@rmol Seems straightforward. Can I take this one up?

**Comment by zenmonkeykstop** [comment]
Hi @prateekj117 - it is straightforward! Verifying that it works correctly (and having a good test plan) is probably the only bit to worry about. Please feel free to pick it up.

**Comment by prateekj117** [comment]
@zenmonkeykstop If it's desired to kick-off only once at 3:00 AM daily, then the correct crontab entry should look something like:
```
0 3 * * * /var/www/securedrop/manage.py were-there-submissions-today
```
instead of the one given in the issue description.
