### ISSUE TITLE
Focal: securedrop-app-code package held back by unattended-upgrades 

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5849]
## Description

securedrop-app-code is not upgraded by unattended-upgrades due to a conffile conflct:

`/var/log/unattended-upgrades/unattended-upgrades.log` states 
```
package has been backlisted due to conffile promts: [securedrop-app-code]
```
manual upgrade confirms
`/var/www/securedrop/static/i/logo.png` is set as a conffile, which means the package will  not override what is served by the package

## Steps to Reproduce

Please specify your environment if that is necessary to reproduce the bug (if in
doubt, include it).

## Expected Behavior

securedrop-app-code should be upgraded
## Actual Behavior

securedrop-app-code is not upgraded

## Comments

We should add to the unattended-upgrades config:

```
Dpkg::Options "force-confdef";
Dpkg::Options "force-confold";
```

**Comment by zenmonkeykstop** [comment]
Reopening as per discussion, options should be formatted like:

```


Dpkg::Options  {
    "--force-confdef";
    "--force-confold";
};
```
