### ISSUE TITLE
Upgrade scenario is broken

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#5883]
## Description

The `upgrade` scenario, used for testing in-place upgrades on Xenial, is no longer behaving well. First reported in https://github.com/freedomofpress/securedrop/pull/5870#issuecomment-804508509

## Steps to Reproduce
1. Check out latest `develop` branch
2. Run `echo 1.7.1 > molecule/shared/stable.ver` to use an existing box (1.8.0 boxes are unmerged, in #5870)
2. Run `make upgrade-start`

## Expected Behavior
Scenario prep is completed, process exits 0, three (3) VMs are configured and ready for upgrade: app, mon, & apt.

## Actual Behavior

Scenario prep hangs while creating the app server. If you run `virt-manager`, you can see that `upgrade_apt` was created fine (directly from the upstream Bento box), box 

## Comments

Suggestions to fix, any other relevant information.

**Comment by conorsch** [comment]
See test reports in https://github.com/freedomofpress/securedrop/pull/5870#issuecomment-807606795. I'm able to run through the process on `develop` and the machines create successfully for me. I do see a syntax problem related to Ansible logic, which should be addressed in the latest changes in #5870.

@rmol please try the test plan above and document your results here.

**Comment by rmol** [comment]
I checked out develop, modified `stable.ver`, built debs, and tried `make upgrade-start`. This was on Debian 10, Vagrant 2.2.14, libvirt.

The process has failed for me repeatedly, but not in the ways reported in #5870. There's no server hang, and it doesn't appear that the video driver is the problem.

**Comment by conorsch** [comment]
See https://github.com/freedomofpress/securedrop/pull/5870#issuecomment-809821917 In a nutshell, let's prioritize #5512 rather than continue trying to support the xenial upgrade logic.
