### ISSUE TITLE
Update cryptography dependency

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5898]
The `cryptography` library is currently pinned at version 3.2.1, because [3.3 dropped Python 3.5 support](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#33---2020-12-08), which is the version of Python included with Ubuntu 16.04.

After the full removal of Xenial support (#5725), we should be in a good position to update the `cryptography` library as part of the SecureDrop 2.0.0 release. We can consider:
- [version 3.3.2](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#332---2021-02-07), which as of this writing is the last release with security fixes, and which was released prior to the inclusion of Rust code
- the latest stable version at the time of release, which will introduce the Rust build requirement.

**Comment by eloquence** [comment]
With #5911 merged, this should now be unblocked.

**Comment by kushaldas** [comment]
For the 2.0.0 release, I suggest to move to the `3.3.2` as we can easily build it from the sources, and then in the next release we can change the build process to use the prebuilt wheels from our workflow/git repository.
