### ISSUE TITLE
Remove virtualbox support from VM scenarios

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#5904]
## Description
Our Molecule-based VM scenarios for developing server config support both libvirt & virtualbox. Some, such as the `upgrade` scenario, only support libvirt. We originally added virtualbox support for macos support, but that was before we had a containerized dev env for developing app code, that works well on all platforms.

At sprint planning yesterday, a quick straw poll showed that none of the team members are using Virtualbox. Let's remove it from the config and the docs. Doing so will reduce the amount of code we're maintaining for testing, and slightly reduce the amount of code we need to address as part of removing Xenial codepaths.

**Comment by eloquence** [comment]
Noting that we may provide macOS support for running SecureDrop VMs in future, depending on developer initerest, in which case we should evaluate again what the options are, which may include libvirt (which is cross-platform, but KVM is Linux-specific) or a cloud-based solution. However, we do not have the bandwidth to maintain three (!) different approaches for managing VMs (libvirt, Qubes, VirtualBox).

**Comment by conorsch** [comment]
Started on these changes in #5922. As mentioned there, we'll need a separate docs PR, which I don't have in draft state. Worth pointing out that #5911 removed a few Virtualbox scenarios already, and #5883 will handle the rest.
