### ISSUE TITLE
Consider disabling codecov.io

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5910]
CodeCov.io was only recently re-enabled for this repo (#5632/#5657). While it has added some value in terms of standardizing coverage checks and tracking change over time, we may be able to achieve the core functionality we care about (pass/fail checks tied to coverage metrics) with the existing `coverage` module, without the use of an external service. Let's consider if codecov.io really adds enough value to justify continued use.

**Comment by zenmonkeykstop** [comment]
This needs revisiting, the codecov bash uploader has been sunsetted so we would need to switch to their binary one anyway.

**Comment by zenmonkeykstop** [comment]
Opting to switch to the binary uploader for now - rather than using the CircleCI orb, which exposes all CircleCI  env vars to the uploader, a limited set of vars have been carried over into the test container.
