### ISSUE TITLE
Incorrect service addresses in Source Interface metadata endpoint after data-only backup

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5912]
## Description

After performing a data-only backup, the source interface `/metadata` endpoint will use the onion service address from the 
backup instead of the instance's actual address. If the backup was v2-only or v2+v3, the v2 address will also be listed even if v2 services are disabled.

## Steps to Reproduce

- create a v3 instance
- do a data-only restore from a backup with different service addresses.
- observe the `/metadata` endpoint

## Expected Behavior
Only the instance's actual SI interface(s) listed

## Actual Behavior
Interface(s) from the backup  listed.

## Comments

Suggestions to fix, any other relevant information.

**Comment by eloquence** [comment]
Closing per discussion at sprint planning today since `v2_source_url` was already removed from the metadata endpoint in #5926.
