### ISSUE TITLE
Upgrade Ansible to latest stable

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#5914]
## Description
The Admin Workstation currently runs Ansible v2.9.7. Soon enough, we'll need to bump to the already released 2.10.x series. That's a difficult jump, and violates expectations about semver. 

## Example output for complicated upgrade
See the following failure message about a naive upgrade from 2.9.7 -> 2.10.7

<details>
<summary>
pip error output
</summary>

```
$ ansible --version
ansible 2.9.7
  config file = /home/user/securedrop/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.virtualenvs/sd/lib/python3.7/site-packages/ansible
  executable location = /home/user/.virtualenvs/sd/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
[user@sd-dev:~/securedrop] [sd] develop+* 6h15m51s ± 
 $ pip install 'ansible>2.10,<2.11' 
Collecting ansible<2.11,>2.10
  Downloading https://files.pythonhosted.org/packages/ba/22/7b58a8ba8e43159dc5cb32d97dd50e2b70b016585dbb188e9f2b61dac1e2/ansible-2.10.7.tar.gz (29.9MB)
     |████████████████████████████████| 29.9MB 561kB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/user/.virtualenvs/sd/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-312we13s/ansible/setup.py'"'"'; __file__='"'"'/tmp/pip-install-312we13s/ansible/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-312we13s/ansible/pip-egg-info
         cwd: /tmp/pip-install-312we13s/ansible/
    Complete output (31 lines):
    
    
                ### ERROR ###
    
                Upgrading directly from ansible-2.9 or less to ansible-2.10 or greater with pip is
                known to cause problems.  Please uninstall the old version found at:
    
                /home/user/.virtualenvs/sd/lib/python3.7/site-packages/ansible/__init__.py
    
                and install the new version:
    
                    pip uninstall ansible
                    pip install ansible
    
                If you have a broken installation, perhaps because ansible-base was installed before
                ansible was upgraded, try this to resolve it:
    
                    pip install --force-reinstall ansible ansible-base
    
                If ansible is installed in a different location than you will be installing it now
                (for example, if the old version is installed by a system package manager to
                /usr/lib/python3.8/site-packages/ansible but you are installing the new version into
                ~/.local/lib/python3.8/site-packages/ansible with `pip install --user ansible`)
                or you want to install anyways and cleanup any breakage afterwards, then you may set
                the ANSIBLE_SKIP_CONFLICT_CHECK environment variable to ignore this check:
    
                    ANSIBLE_SKIP_CONFLICT_CHECK=1 pip install --user ansible
    
                ### END ERROR ###
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
</details>

The import bit:

<blockquote>
Upgrading directly from ansible-2.9 or less to ansible-2.10 or greater with pip is known to cause problems.  Please uninstall the old version found at: /home/user/.virtualenvs/sd/lib/python3.7/site-packages/ansible/__init__.py and install the new version:
    
pip uninstall ansible
pip install ansible
</blockquote>

That change will require special handling of the upgrade logic in the Admin Workstation, to avoid breakage. 

## Misc

Looks like the Ansible project is [switching to semver](https://docs.ansible.com/ansible/latest/roadmap/COLLECTIONS_3_0.html#release-schedule), presumably due to feedback regarding the breakaging changes in 2.10:

> Ansible is switching from its traditional versioning scheme to semantic versioning starting with this release. So this version is 3.0.0 instead of 2.11.0.

**Comment by zenmonkeykstop** [comment]
Looks like pip install --upgrade from 2.9.* to later versions works, so the updater may not need major changes

**Comment by sssoleileraaa** [comment]
[Backlog pruning, 5/15] This would help us reduce our overall safety list ignores and is something we would do as part of maintenance mode anyway. Strategy would be to start upgrading now on a feature branch and release 2.60 whether or not it's pulled in by the end of the 8-week cycle. If we have to, we will pick the work back up in a following cycle or once we are in maintenance mode.

**Comment by rocodes** [comment]
[as discussed in planning] commenting to remind us to allow more review time than normal, for larger diff review

**Comment by zenmonkeykstop** [comment]
Spoke too soon on the upgrade front, updating from 2.9 to 2.13 (6.* by the semver change) is still going to require some special handling in the SD updater. 

Simply running `./securedrop-admin setup` against an existing install does not add both required packages (ansible-core, ansible), so this case would need to be detected and the existing ansible package uninstalled first. This is probably gonna make this upgrade a 2-parter: first release to add code in GUI updater to handle this case, second release to actually do the upgrade.

Good news is, while there are a lot of deprecation warnings (~300 or so just for the include module), at least the simpler playbooks are pretty much functional!

**Comment by zenmonkeykstop** [comment]
Looks like the least painful way to do this is, in bootstrap.py:

- before updating deps, identify starting ansible version
- if starting version was 2.9.*:
  - remove ansible
  - run pip install -U command

Since this is a bootstrap.py change, and the GUI updater order of operations is: update source; run setup; run tailsconfig, I think this can be done as a single release? (It doesn't change the GUI updater code).

**Comment by zenmonkeykstop** [comment]
Bumping to 2.7.0 - if we need to upgrade in a point release we can but this is a good scope reduction otherwise.

**Comment by zenmonkeykstop** [comment]
Flipped to RfR - note that this does not upgrade all the way to latest but does get us over the 2.9->2.10 hump. Probably the simplest way to avoid dependency shenanigans would be to move to latest with the next Tails Debian bump (incoming later this year iirc).
