### ISSUE TITLE
Add API endpoint for batch deletion of files and messages associated with a source

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5959]
As part of implementing Safe Deletion for the SecureDrop Client (https://github.com/freedomofpress/securedrop-client/issues/1202), we've identified the need for a new endpoint that batch-deletes files and messages associated with a source, to improve roundtrip performance of "Files and Messages" deletion.

**Comment by eloquence** [comment]
@zenmonkeykstop has offered to take point on this, starting with developing a spec for discussion.

**Comment by prateekj117** [comment]
@eloquence @zenmonkeykstop Let me know if I could work on this issue.

**Comment by prateekj117** [comment]
@eloquence Let me know if I can take this up.

**Comment by eloquence** [comment]
This was resolved via #5963.
