### ISSUE TITLE
[2.0.0-rc2] Failure during tailsconfig when provisioning Journalist USB: ~/Persistent/.securedrop/torrc_additions does not exist

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop#5997]
## Description

During QA (rc2), when attempting to verify #5965, I encountered an error running `tailsconfig`. 

## Steps to Reproduce

- New Tails 4.19 USB, persistence enabled
- clone SD repo
- copy in `app-journalist.auth_private` and `app-sourcev3-ths`
- verify tag + check out 2.0.0-rc2  
- `./securedrop-admin setup`, `./securedrop-admin tailsconfig`

## Expected Behavior
`tailsconfig` completes successfully

## Actual Behavior
(A complete log is attached: [tailsconfig.txt](https://github.com/freedomofpress/securedrop/files/6666074/tailsconfig.txt))
```
TASK [tails-config : Confirm Tor service info was found.] ******************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [tails-config : Append ClientOnionAuthDir directive to torrc additions] ***********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Destination /home/amnesia/Persistent/.securedrop/torrc_additions does not exist !", "rc": 257}

NO MORE HOSTS LEFT *********************************************************************

NO MORE HOSTS LEFT *********************************************************************

PLAY RECAP *****************************************************************************
localhost                  : ok=18   changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

ERROR (run with -v for more): Command '['/home/amnesia/Persistent/securedrop/install_files/ansible-base/securedrop-tails.yml', '--ask-become-pass', '-i', '/dev/null']' returned non-zero exit status 2.

```

## Comments
The `~/Persistent/.securedrop` directory is present, but `torrc_additions` is not.

**Comment by zenmonkeykstop** [comment]
This is a bug in the workstation provisioning code - previously `torrc_additions` was created by the task handing v2 authenticated services (even if those services did not exist) and then updated with the v3 config. the former task was removed, so on new workstation provisionings, nothing creates that file.
