### ISSUE TITLE
all-caps button labels are misread by screen-readers

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6003]
## Description

For example:  A button labeled `ADD USER` will be announced by a screen-reader as an initialism to be spelled out: "A.D.D. user".

https://github.com/freedomofpress/securedrop/blob/012d30e8baeb8ffa7c10a56f4b43c464abf87cf7/securedrop/journalist_templates/admin.html#L6-L9

## Steps to Reproduce

For this example:

1. Navigate to the Admin Interface of the Journalist Interface.
2. Activate a screen-reader.

## Expected Behavior

The button visually labeled `ADD USER` is announced as "add user".

## Actual Behavior

The button visually labeled `ADD USER` is announced as "A.D.D. user".

## Comments

Labels capitalized explicitly in #1538 can be reverted to title case (pending #5821) and then styled with the `text-transform` property.

**Comment by eloquence** [comment]
Note there are i18n arguments against `text-transform`, see https://github.com/freedomofpress/securedrop/issues/1587#issuecomment-694969536

**Comment by cfm** [comment]
After further research:

1. Per https://github.com/freedomofpress/securedrop/issues/1587#issuecomment-694969536: the localization argument against `text-transform` stands.  (Thanks for referring me, @eloquence.)
2. Where testing demonstrates that screen-readers may misread a *specific* label in all caps, [we can override it with `aria-label`](https://webaim.org/discussion/mail_thread?thread=8674#post1), at the cost of adding an extra string to translate.  For example:
```html
 <button type="submit" id="add-user" aria-label="{{ gettext('Add User') }}"> 
   {{ gettext('ADD USER') }} 
 </button> 
```
3. In general, however, and in the absence of a specific misreading, [we should avoid micromanaging the accessibility tree](https://stackoverflow.com/a/53825307).

I'll close this general tracking issue and address specific instances as I encounter them in the course of #5986 and #5987.
