### ISSUE TITLE
Use CircleCI's built-in branch filtering feature throughout

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#6024]
CircleCI supports [branch filters with regular expressions](https://circleci.com/docs/2.0/configuration-reference/#jobfilters). We're currently using the script [`match-ci-branch.sh`](https://github.com/freedomofpress/securedrop/blob/develop/devops/scripts/match-ci-branch.sh) for our branch filter logic.

We should evaluate if there are still reasons to use this script, and if not, replace it with CircleCI's built-in functionality, for performance and maintainability reasons.

**Comment by prateekj117** [comment]
@eloquence Sounds good. I can take this up. I see most jobs right now are using both the `match-ci-branch` script alongside Circle CI branch filters. But some have skipped Circle CI branch filters and only using the script. I will make a PR for the same.

**Comment by eloquence** [comment]
@prateekj117 Do you still want to work on this?

**Comment by prateekj117** [comment]
@eloquence For sure !!! Will do it this weekend.
