### ISSUE TITLE
Remove Tails automatic-decompression flag if no longer needed

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#6042]
This code in `securedrop_init.py`
https://github.com/freedomofpress/securedrop/blob/1a2494d2b27129708e0da6b4278a7e888746daaf/install_files/ansible-base/roles/tails-config/files/securedrop_init.py#L100-L102
may no longer be needed; we removed the instructions for changing this setting on the SVS in https://github.com/freedomofpress/securedrop-docs/commit/bb1e33bb132efc9cff977852c719b4b5ba06b9ec as it was no longer necessary in Tails 4. Tails 4 is now enforced as the required environment, so let's remove this code if it's no longer needed.

**Comment by zenmonkeykstop** [comment]
this is resolved in https://github.com/freedomofpress/securedrop/pull/6079.
