### ISSUE TITLE
need idempotent db initialization

### ISSUE THREAD

**Issue by david415** [freedomofpress/securedrop#605]
We need some sort of idempotent initialization for the database so that we don't initialize it if we don't have to. I suggest making db.init_db() be idempotent or give us some sort of API call that tells us wether or not to call db.init_db()...

**Comment by garrettr** [comment]
@dolanjs Do you think this is still an issue? I think we've pretty much agreed that `db.init_db` is functionally idempotent (calling it on an already-initialized db does nothing), although Ansible doesn't know that (and will still show it as "changed" in the playbook run output, even if it's not).

**Comment by dolanjs** [comment]
@garrettr we made the ansible task that runs db.init_db  idempotent. So while db.init_db is not idempotent ansible will not run it if the db already exists. So think we can close this issue.

```
- stat: path="{{ securedrop_data }}/db.sqlite"
register: db

- name: initialize sqlite db
shell: "su -s /bin/bash -c \"PYTHONPATH={{ securedrop_code }} python -c 'import db; db.init_db()'\" {{ securedrop_user }}"
when: not db.stat.exists
```

**Comment by garrettr** [comment]
@dolanjs :+1:
