### ISSUE TITLE
invalid `datetime` attributes

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6057]
## Description

In `securedrop/source_templates/lookup.html`, `time` elements have invalid `datetime` attributes giving too many digits for fractional seconds.

## Steps to Reproduce

Validate the HTML of the Source Interface's `/lookup` view.

## Expected Behavior

The page validates.

## Actual Behavior

The page fails validation with errors like:

> Bad value `2021-07-13 22:47:04.564322` for attribute `datetime` on element `time`: A fraction of a second must be one, two, or three digits

## Comments

Should be simple to fix with a truncating Jinja filter.

**Comment by anorthall** [comment]
I have fixed this in #6058, however I used strftime() instead of the Jinja truncate feature, as you cannot truncate the datetime instance without first converting it to a string.

**Comment by zenmonkeykstop** [comment]
Thanks to @cfm for finding this and @anorthall for picking it up! Will add a comment on the PR.
