### ISSUE TITLE
Improve SecureDrop backups

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#606]
We have two categories of DR backup:
One-time-backup: tor certs, app gpg keypair (pub and airgapped private), config.py, ssh 2fa secret values

Periodic-backups: app gpg keyring, db and /store directory

The initial install will make a backups of the One-time-backups at the end of the installation and encrypt them using the applications public key.

It would be nice if the document interface had a way to perform the periodic-backups. All of the files needed for periodic backups are owned by the application user so that shouldn't be an issue.

**Comment by garrettr** [comment]
The one-time-backup use case discussed in the top comment has been implemented in #766 and #829. Implementing periodic backups is a bit harder, and is something we should consider for a future release.

**Comment by flamsmark** [comment]
Storing something on the admin workstation is a form of backup, but it's not disaster recovery. A disaster recovery plan should allow for returning to regular-enough operations even if every piece of regular infrastructure is out of service. If the admin is in the same building as the SVS, app, and monitor servers when the fire starts, the backup created by this system will not be available for recovery.

**Comment by eloquence** [comment]
Closing in favor of up-to-date issues tracking specific improvements, e.g., #5148.
