### ISSUE TITLE
Upgrade to tor >=0.4.5.10

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#6061]
## Description

Tor v0.4.5.10 will be released on 2021-08-16, and fixes a security vulnerability. Details here: https://lists.torproject.org/pipermail/tor-packagers/2021-August/000127.html

As of https://github.com/freedomofpress/securedrop/pull/6059 we intend to move to 0.4.5.9, although that's not released to prod or staging yet. I recommend we go straight to .10 and ship to prod after we've tested.

## User Stories
As a user of SecureDrop, I want to trust that the Tor anonymous connections are fully patched.

**Comment by zenmonkeykstop** [comment]
seconded. will close the 0.4.5.9 one for now.

**Comment by conorsch** [comment]
Voila: https://blog.torproject.org/node/2062

**Comment by eloquence** [comment]
This was done and we have not observed any issues, closing.
