### ISSUE TITLE
`rel_datetime_format` under-localizes absolute timestamps

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6073]
## Description

`time` elements get their `title`s from the `rel_datetime_format` filter, which has a default date format:

https://github.com/freedomofpress/securedrop/blob/012d30e8baeb8ffa7c10a56f4b43c464abf87cf7/securedrop/template_filters.py#L11-L14

This initial `fmt` value constrains the localization that Babel is able to perform.

## Steps to Reproduce

For example:

1. Enter the Source Interface for a source with replies in the German locale, e.g.:  http://127.0.0.1:8080/lookup?from_login=1&l=de_DE
2. Inspect a `time[title]` attribute:

```sh-session
> $('time').title
"Aug. 23, 2021 09:23 PM"
```

3. Compare to a timestamp localized without an explicit format:

```python
>>> import babel
>>> from babel.dates import *
>>> babel.dates.format_datetime(datetime.now(), locale='de_DE')
'23.08.2021, 22:17:06'
```

## Expected Behavior

Locale preferences are respected for order of date elements, 12-hour v. 24-hour time, &c.

## Actual Behavior

Locale preferences are overridden by the default `fmt`.

## Comments

`fmt` could default to (e.g.) [`long`, which Babel will localize as appropriate](http://babel.pocoo.org/en/latest/dates.html).  If we're attached to this default `fmt` for `en_US`, we could preserve it there and use `long` for other locales.

**Comment by anorthall** [comment]
I will work on this, if that's okay.

**Comment by anorthall** [comment]
@cfm There really doesn't seem to be any sensible way to do it other than to use `long` as you said. 

So, a simple `if` statement to check if the locale is `en_US` (or potentially GB, Australia - will look) in `rel_datetime_format()` and use `long` if not is all that is required here? Just making sure I understand the issue!

**Comment by cfm** [comment]
That sounds right, @anorthall.  My own ideal, frankly, would be to just use `long` everywhere and not bother with a special case for `en_*`, but I'll have to defer to @zenmonkeykstop on whether there's a compelling reason to preserve the current custom format.
