### ISSUE TITLE
Staging environment fails on multiple provision runs, at local deb pkgs for kernel

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#6076]
## Description

@kushaldas shared this error message:

<blockquote>
    fatal: [mon-staging]: FAILED! => {"changed": true, "cmd": ["apt-get", "install", "-y", "-f", "/root/securedrop-grsec-5.4.136+focal-amd64.deb"], "delta": "0:00:00.376052", "end": "2021-08-25 09:09:47.196142", "msg": "non-zero return code", "rc": 100, "start": "2021-08-25 09:09:46.820090", "stderr": "E: Unable to correct problems, you have held broken packages.", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n securedrop-grsec : Depends: linux-image-5.4.136-grsec-securedrop but it is not installable", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " securedrop-grsec : Depends: linux-image-5.4.136-grsec-securedrop but it is not installable"]}
    fatal: [app-staging]: FAILED! => {"changed": true, "cmd": ["apt-get", "install", "-y", "-f", "/root/securedrop-grsec-5.4.136+focal-amd64.deb"], "delta": "0:00:00.418120", "end": "2021-08-25 09:09:47.227002", "msg": "non-zero return code", "rc": 100, "start": "2021-08-25 09:09:46.808882", "stderr": "E: Unable to correct problems, you have held broken packages.", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n securedrop-grsec : Depends: linux-image-5.4.136-grsec-securedrop but it is not installable", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " securedrop-grsec : Depends: linux-image-5.4.136-grsec-securedrop but it is not installable"]}
</blockquote>

That's familiar enough to me, so I'd like to try to reproduce it. 

## Steps to Reproduce
1. Run `make staging` with fresh debs to build a staging environment.
2. Don't change anything, just re-run `make staging`

Do you see the error?

## Expected Behavior
Multiple provisioning runs complete successfully. 

## Actual Behavior
Subsequent runs fail, due to incomplete apt logic around manually instaling local deb pkgs. 

## Comments

Problem seems to be related specifically to the kernel tasks, which use subtly different logic from the other debs.

**Comment by eloquence** [comment]
I get a very similar error. First run is fine, subsequent run failed with the errors below.

- [Full logs from first run](https://gist.github.com/eloquence/6be5aaa69c0967715e8dfa8fa4c4b314)
- [Full logs from subsequent run](https://gist.github.com/eloquence/23ef58fd091f5b01c55a6e19b00eca35)

>    fatal: [mon-staging]: FAILED! => {"changed": true, "cmd": ["apt-get", "install", "-y", "-f", "/root/securedrop-grsec-5.4.136+focal-amd64.deb"], "delta": "0:00:00.915124", "end": "2021-08-27 04:25:19.772736", "msg": "non-zero return code", "rc": 100, "start": "2021-08-27 04:25:18.857612", "stderr": "E: Packages were downgraded and -y was used without --allow-downgrades.", "stderr_lines": ["E: Packages were downgraded and -y was used without --allow-downgrades."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following held packages will be changed:\n  securedrop-grsec\nThe following packages will be DOWNGRADED:\n  securedrop-grsec\n0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following held packages will be changed:", "  securedrop-grsec", "The following packages will be DOWNGRADED:", "  securedrop-grsec", "0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded."]}
>
>    fatal: [app-staging]: FAILED! => {"changed": true, "cmd": ["apt-get", "install", "-y", "-f", "/root/securedrop-grsec-5.4.136+focal-amd64.deb"], "delta": "0:00:00.991674", "end": "2021-08-27 04:25:19.746687", "msg": "non-zero return code", "rc": 100, "start": "2021-08-27 04:25:18.755013", "stderr": "E: Packages were downgraded and -y was used without --allow-downgrades.", "stderr_lines": ["E: Packages were downgraded and -y was used without --allow-downgrades."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following held packages will be changed:\n  securedrop-grsec\nThe following packages will be DOWNGRADED:\n  securedrop-grsec\n0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following held packages will be changed:", "  securedrop-grsec", "The following packages will be DOWNGRADED:", "  securedrop-grsec", "0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded."]}
 ```

**Comment by conorsch** [comment]
Encountered this while rebuilding a staging environment today. Will submit a quick fix shortly.
