### ISSUE TITLE
Rendering discrepancies on web interfaces between latest (2.0.2) and current develop branch

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6080]
Issue collecting rendering changes coming from the a11y refactor that probably need to be tweaked:

- [x] #6081
- [x] #6082
- [x] #6083
- [x] #6084
- [x] #6093

(if you see something else please add it above!)

**Comment by cfm** [comment]
Draft pull request #6096 can serve as the accumulator for these fixes, so that we can easily review and merge the full set, including for any further discrepancies we may notice, in one fell swoop.
