### ISSUE TITLE
SI "Yes, delete all replies" button is now 3 lines of text instead of 2, increasing overall height

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6083]

**Comment by cfm** [comment]
I'm not able reproduce this discrepancy.  I see—

```
YES, DELETE ALL
REPLIES
```

—at reasonable viewport sizes on both 2.0.2 and current `develop`.  What I've proposed in 88d8a1b8b1553d55ad1e5f1c6eb4f556325d00e6 gives a little more leeway to *keep* this button to two lines, however, and at my default Tor Browser viewport actually gets both buttons to be one-line.
