### ISSUE TITLE
Journalist Interface All Sources page is missing gray border on  right panel, padding between left and right panels

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6084]

**Comment by cfm** [comment]
Note that 6d4602da288b398dea3680dfb9faba67cf11e85a does not remove the extra `border-top` on the `footer`, carried over from the Source Interface.  (In general, I'm still hoping to reduce discrepancies *between* the two interfaces, without introducing too much drift or entropy into either one across releases. :-)
