### ISSUE TITLE
Expired signing key in ansible causing installation failure

### ISSUE THREAD

**Issue by jgillum** [freedomofpress/securedrop#6089]
SecureDrop's installer appears to fail because of the expired signing key `fpf-signing-key.pub` in `/install_files/ansible-base/roles/install-fpf-repo/files/`. 

Commenting out this expired key in `main.yml` and leaving only the 2021 key seems to still make the apt-cache update fail, and thus the installer fail, too.

**Comment by eloquence** [comment]
Thanks for the report @jgillum and sorry for the inconvenience. 
- Prior to running the installer, can you confirm that `git status` in `~/Persistent/securedrop` on your Admin Workstation shows `HEAD detached at 2.0.2`?
- Are you able to share the relevant portion of the Ansible output (taking care to redact any sensitive details)? 
 
For confidential communications, please don't hesitate to [request an account](https://support.freedom.press/account/register) on our support portal.

**Comment by jgillum** [comment]
Thanks so much! Yes, it's 2.0.2; I just confirmed. 

Here's the tail of the ansible output:

```
TASK [Check if install has been done before] ***********************************
ok: [app -> xxxxx]
ok: [mon -> xxxxxx]

TASK [install-fpf-repo : Install SecureDrop apt repo GPG signing key.] *********
ok: [app] => (item=fpf-signing-key.pub)
ok: [mon] => (item=fpf-signing-key.pub)
ok: [mon] => (item=fpf-signing-key-2021.pub)
ok: [app] => (item=fpf-signing-key-2021.pub)

TASK [install-fpf-repo : Setup FPF apt repo.] **********************************
fatal: [app]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
fatal: [mon]: FAILED! => {"changed": false, "msg": "apt cache update failed"}

NO MORE HOSTS LEFT *************************************************************

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
app                        : ok=9    changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0   
localhost                  : ok=11   changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
mon                        : ok=9    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   

ERROR (run with -v for more): Command '['/home/amnesia/Persistent/securedrop/install_files/ansible-base/securedrop-prod.yml', '--ask-become-pass']' returned non-zero exit status 2.
amnesia@amnesia:~/Persistent/securedrop$ 
```

**Comment by eloquence** [comment]
Thanks @jgillum, very helpful. Was there anything in the output that relates to key expiry, or another reason that you suspect that this is the cause of the apt cache update failure? (The output indicates that the correct (up-to-date) signing key is being installed successfully, alongside the historical one.) If you SSH into the server or log into it locally, do you get error output if you run `sudo apt update`?

**Comment by jgillum** [comment]
I wondered the same thing, but weirdly, `apt update` pulls the latest repository with no issue.

**Comment by eloquence** [comment]
@jgillum Can you try increasing the Ansible verbosity, like so, to see if you can get more useful log details (you'll also likely see more sensitive info in the output)?

`ANSIBLE_VERBOSITY=3 ./securedrop-admin install`

**Comment by jgillum** [comment]
Turns out this whole time I was using Ubuntu 21 by mistake, and the apt repositories weren't correct. Thanks! Works now.

**Comment by jgillum** [comment]
Turns out this whole time I was using Ubuntu 21 by mistake, and the apt repositories weren't correct. Thanks! Works now.
