### ISSUE TITLE
[QA] "securedrop-admin verify" does not support force arg

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#6128]
## Description
Running `./securedrop-admin verify` on `release/2.1.0` fails, because there's no prod-signed tag on that commit. 

## Steps to Reproduce
1. Check out `release/2.1.0` in Tails, configured VMs
2. Run `./securedrop-admin verify`, observe error message and friendly recommendation to try the "--force" flag
3. Run `./securedrop-admin --force verify` as recommended, observe error message about flag not being understood

## Expected Behavior

`./securedrop-admin --force verify` skips tag verification logic, just like `./securedrop-admin --force install` does.

## Actual Behavior

`./securedrop-admin --force verify` does not recognize the `--force` flag at all.

**Comment by zenmonkeykstop** [comment]
IMO `verify` shouldn't do the version check at all - it doesn't run any playbook that can change the workstation or server state, so it doesn't matter which version you're on locally (altho the onus is then on the user to make sure they're using the version they expect).
