### ISSUE TITLE
HTTPS-enabled instance may still have 128-bit keys after upgrade

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6132]
## Description

In https://github.com/freedomofpress/securedrop/issues/6103#issuecomment-938341940, I found that an HTTPS-enabled instance upgraded to v2.1.0~rc1 may still use 128-bit keys rather than the 256-bit keys intended by #5988.

## Steps to Reproduce

> (HTTPS-only) On the Source Interface index page, verify via the Tor Browser Security Tab that the connection is encrypted not only as an Onion Service but also vi TLS 1.3 with 256-bit keys

## Expected Behavior

After rerunning `make self-signed-https-certs && ./securedrop-admin install`, Tor Browser "Page Info" says (my emphasis):

> Connection Encrypted (Onion Service, TLS_AES_256GCM_SHA384, **256 bit keys,** TLS 1.3)

## Actual Behavior

Tor Browser "Page Info" says (my emphasis):

> Connection Encrypted (Onion Service, TLS_AES_128GCM_SHA256, **128 bit keys,** TLS 1.3)

## Comments

This suggests that an explicit `make self-signed-https-certs && ./securedrop-admin install` is necessary for #5988 to go into effect on upgrading an existing SecureDrop installation.

**Comment by conorsch** [comment]
@cfm Are you saying that the test plan for 2.1.0 should permit 128-bit keys? Or are you saying that on upgrade to 2.1.0, prod instances using HTTPS on the Source Interface may break?

**Comment by zenmonkeykstop** [comment]
As part of #5988, the Apache SSLCipherSuite directive is now not being set on fresh installs and is being removed on upgrades - it might be necessary to set it if we really want to force the expected key length. Mind you, IANACryptographer, but 128-bit AES seems good enough?

**Comment by zenmonkeykstop** [comment]
I think the test plan (ie me) is at issue here - I got 256-bit keys while working through the case the first time, so I put that in as an expectation. I don't think there's a valid reason to expect that the negotiation would always work out that way. Gonna update the plan, and I think we can close this unless there are any objections.

**Comment by cfm** [comment]
We've decided out of band that today I'll brush up on TLS 1.3 in order to confirm the conclusion in https://github.com/freedomofpress/securedrop/issues/6132#issuecomment-939361795.

**Comment by cfm** [comment]
My research bears out your conclusion, @zenmonkeykstop, in https://github.com/freedomofpress/securedrop/issues/6132#issuecomment-939361795:

> I think the test plan (ie me) is at issue here - I got 256-bit keys while working through the case the first time, so I put that in as an expectation. I don't think there's a valid reason to expect that the negotiation would always work out that way. Gonna update the plan, and I think we can close this unless there are any objections.

Per [RFC 8446](https://www.rfc-editor.org/rfc/rfc8446#section-9.1)—

> A TLS-compliant application MUST implement the TLS_AES_128_GCM_SHA256
> cipher suite and SHOULD implement the TLS_AES_256_GCM_SHA384
> and TLS_CHACHA20_POLY1305_SHA256 cipher suites (see
> Appendix B.4).

—so both the 128-bit and the 256-bit session keys we've observed are valid.

For what it's worth, Qualys [discriminates](https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide#cipher-strength) on the basis of session-key length in rating TLS endpoints, but Mozilla [recommends](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) all three cipher suites equally.
