### ISSUE TITLE
old signing key `22245C81E3BAEB4138B36061310F561200F4AD77` is not removed during upgrade

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6133]
## Description

In https://github.com/freedomofpress/securedrop/issues/6103#issuecomment-938341940, I found that the old signing key `2224 5C81 E3BA EB41 38B3 6061 310F 5612 00F4 AD77` was still present after upgrade to v2.1.0~rc1, alongside the new signing key `2359 E653 8C06 13E6 5295 5E6C 188E DD3B 7B22 E6A3`.  @zenmonkeykstop has [informally corroborated](https://freedomofpress.slack.com/archives/C123KPJ1X/p1633663499050100).

## Steps to Reproduce

> verify that the old signing key with fingerprint `22245C81E3BAEB4138B36061310F561200F4AD77` is not present on the application or monitor servers, e.g. by running the command `for s in app mon; do ssh $s sudo apt-key list; done` from the Admin workstation

## Expected Behavior

```sh-session
amnesia@amnesia:~/Persistent/securedrop$ git branch --points-at HEAD
* release/2.1.0
amnesia@amnesia:~/Persistent/securedrop$ for s in app mon; do ssh $s sudo apt-key list | grep -b2 -a1 "2224"; done
```

## Actual Behavior

```sh-session
amnesia@amnesia:~/Persistent/securedrop$ git branch --points-at HEAD
* release/2.1.0
amnesia@amnesia:~/Persistent/securedrop$ for s in app mon; do ssh $s sudo apt-key list | grep -b2 -a1 "2224"; done
Warning: apt-key output should not be parsed (stdout is not a terminal)
587-pub   rsa4096 2016-10-20 [SC] [expired: 2021-06-30]
639:      2224 5C81 E3BA EB41 38B3  6061 310F 5612 00F4 AD77
696-uid           [ expired] SecureDrop Release Signing Key
Warning: apt-key output should not be parsed (stdout is not a terminal)
587-pub   rsa4096 2016-10-20 [SC] [expired: 2021-06-30]
639:      2224 5C81 E3BA EB41 38B3  6061 310F 5612 00F4 AD77
696-uid           [ expired] SecureDrop Release Signing Key
```

**Comment by conorsch** [comment]
Observed this during QA as well. Looks like we're still installing the old key via Ansible: https://github.com/freedomofpress/securedrop/blob/21a162ddb6879dea996fd8a352c53e67550aedd5/install_files/ansible-base/roles/install-fpf-repo/defaults/main.yml#L22-L23

That explains why I saw it during my clean install scenario. For @cfm's upgrade scenario, though, I wouldn't expect the Ansible logic to cause the key to be there. More investigation required for root cause, but we can still remove that Ansible line immediately.

**Comment by conorsch** [comment]
Discussed during sync today, and both @cfm and I ran the `./securedrop-admin install` action, which suggests the Ansible oversight above is at fault. I'll investigate and submit a PR.

**Comment by conorsch** [comment]
After manually removing key, `./securedrop-admin install` indeed restores it. Will try next with that Ansible var edited, and confirm it doesn't get re-added.
