### ISSUE TITLE
Question: Secure Drop is unavailable multiple time per day

### ISSUE THREAD

**Issue by elfranne** [freedomofpress/securedrop#6135]
## Description

We have a Secure Drop installation that does not responds multiple time per day. I use curl to request the public onion:
`curl --socks5-hostname 127.0.0.1:9050 redacted.onion -s -o /dev/null -w "%{http_code}\n"`
That results in a `exited with 7`.

For example today it has not responded 4 times, ranging from 10 to 20 minutes each time. (I am excluding the daily reboot)
Is this a normal behavior ? Or is it expected for the Tor network to "fail" so often ?

**Comment by zenmonkeykstop** [comment]
The only expected time for the installation not to respond is during the  reboot, but Tor can be flaky. It would be worthwhile to review the system logs for any Tor-related errors - also, if you can check the Journalist Interfaceand the SSH onion services if available, that could help narrow it down.

For security reasons we don't tend to discuss issues with specific instances in Github, but if you'd like some help troubleshooting, please feel free to register an account at https://support.freedom.press/

**Comment by eloquence** [comment]
Hi @elfranne , having not heard back from you, I'm closing this issue - but please don't hesitate to get in touch via the support portal above, or via securedrop@freedom.press.
