### ISSUE TITLE
Display forgotten codename in one click rather than two

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop#6155]
## Description

When you click on the "Forgot your codename?" link, the "Remember your codename is" popup appears without showing the codename. Then you have to click on a "Show" link to see the codename. See:

![Peek 2021-10-26 23-50](https://user-images.githubusercontent.com/4522213/139014692-da71f72f-b4f8-478e-ae2a-c0cd8d78553a.gif)

I think we should combine this two click operation into a one-click operation so that the codename is displayed when the user clicks on the "Forgot your codename?" link.

## User Research Evidence

None

**Comment by eloquence** [comment]
I agree this interaction is pretty wonky. Note that @ninavizz is currently [exploring](https://github.com/freedomofpress/securedrop-ux/wiki/Prototypes-Archive#source-ui-new-user-experience-2021) design solutions for an "inverted flow" in which the codename (now renamed passphrase) is shown at the end of the submission process, not at the beginning.

In that case, the entire "Forgot your codename" pattern would likely not be necessary. If we end up keeping it, I agree we should find ways to make the interaction less cumbersome.

**Comment by eaon** [comment]
The order of these elements in the UI has changed, so this link does not exist anymore, instead I think the current design also implicitly resolves the issue that @creviera pointed out:

![image](https://user-images.githubusercontent.com/201369/200058276-5be83071-dd19-4dbd-9fbb-e06475221a21.png)

If someone has forgotten to note down their codename/passphrase, it's just one click away and the functionality is visible in the view-port :smile:
