### ISSUE TITLE
NUC11 hardware: network device unsupported by SecureDrop custom kernel

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop#6170]
## Description

On a NUC11i5PAK, the network connectivity is lost during installation after the first reboot.

## Steps to Reproduce

I am following the documentation instructions and the issue appeared when running `./securedrop-admin install` from the Admin workstation. However, I believe that booting the NUC11 using the `5.4.136-grsec-securedrop` kernel may be enough to reproduce the issue.

## Expected Behavior

After the servers reboot, the installation script resumes normally. Even if it that wasn't the case, I'd expect to be able to connect to both servers via: `ssh sdadmin@10.20.2.2` and `ssh sdadmin@10.20.3.2`.

## Actual Behavior

There is no route to either `app` or `mon`.
When logging into the servers directly (physical access) this is what I see:

```sh
sudo lshw -class network
# prints that the network device is UNCLAIMED
```

The (wired) network device of the NUC11i5PAK is: `Ethernet controller [...] Intel CorporationDevice [8086:15f3] (rev 03)`, which seems to be supported via the `igc` kernel module. (I might be wrong about his, or there might be other ways.)
That module seems to be missing from the hardened kernel that SecureDrop uses:

```sh
modinfo igc
# modinfo: ERROR: Module alias igc not found.
```

Finally, for reference, by default Ubuntu 20.04 allows to use the network device as `enp0s25`. (Which is why the installation script behaves as expected until the servers are rebooted with the custom kernel.)

## Comments

Using the SecureDrop [kernel-builder](https://github.com/freedomofpress/kernel-builder) to get a build based on the 5.10 release might be a good starting point.

**Comment by gonzalo-bulnes** [comment]
@zenmonkeykstop @eloquence @conorsch Please let me know if I missed anything that would be useful documenting in this issue!

**Comment by zenmonkeykstop** [comment]
Looks like grsec's 5.15 series might actually be the way to go. the 5.10 patch  is EOL in Q1 2022.

**Comment by conorsch** [comment]
> the 5.10 patch is EOL in Q1 2022.

Agreed, that's what https://grsecurity.net/download/ says. However, the EOL dates there are substantially different from what's on https://www.kernel.org/category/releases.html :

| EOL dates        | 5.10     | 5.15 |
|--------------|-----------|------------|
| grsec | 2022Q1      | 2024Q4        |
| kernel.org    |2026Q4  | 2023Q4       |

If what we want is long-term support for hardware, tracking the 5.10 series seems like the biggest win for us. The discrepancy is great enough that I suspect the grsec page is perhaps out of date. I suggest we reach out to spender and and ask for clarification.

**Comment by conorsch** [comment]
The kind folks at grsecurity strongly recommended we target 5.15, as @zenmonkeykstop rightly proposed. We'll continue to test patches and revise the build process, if necessary, in https://github.com/freedomofpress/kernel-builder/pull/18

**Comment by gonzalo-bulnes** [comment]
:point_up: I installed the [5.15.18](https://github.com/freedomofpress/securedrop/pull/6242) kernel above on a fresh Ubuntu 20.04.3 installation:
- The `enp2s0` network device is not `UNCLAIMED` anymore :heavy_check_mark: 
- `sudo modinfo igc` does print information of the module :heavy_check_mark:
