### ISSUE TITLE
Change use of word "document" across SI and JI, to "file"

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#6173]
## Description

In confirmation messaging in the Source UI, on the "All Sources" page of the JI, and maybe on the individual Source page in the JI, the word "document" is shown. In the H2 and Body copy of the SI, we have already changed the word to "File," and I believe in the SDW Client have also made the update. 

The file-name format including the word "doc" for files in the `.gz` filename, I'm not too worried about. it's more in the SI confirmation messaging and possible error messaging, as well as in the JI, that it feels nitpicky and out of place. 

## User Research Evidence
![image](https://user-images.githubusercontent.com/8262612/142579763-a0725fe3-5c30-4fa8-ba28-5b9bb5ab8305.png)

## User Stories

As a Source submitting an image, there is a cognitive disconnect when I get a confirmation message thanking me for my document. As a journalist, it is adding cognitive friction to see "doc" when I know they're "files."

**Comment by huertanix** [comment]
A quick addendum to this: Having to clarify that "doc" in the filename doesn't mean it's a Microsoft Word document file but any kind of file (image, video, etc) is something I go out of my way to explain in SecureDrop training sessions to avoid confused trainees.
