### ISSUE TITLE
Implement CSP Frame Ancestors policy

### ISSUE THREAD

**Issue by evilaliv3** [freedomofpress/securedrop#6178]
I would like to propose to improve of the current CSP policy by adding the ```frame-ancestors``` directive.

In specific i would like to propose to set the directive to the value ```frame-ancestors: none```

I would like to precise that this addition would not add any value on top of our current usage of the ```X-Frame-Options``` header and actually would just represent an overhead in the communication but would suggest anyhow its addition in relation to browser up-to-date standard compliance

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

**Comment by zenmonkeykstop** [comment]
LGTM, folding into a new PR as per https://github.com/freedomofpress/securedrop/pull/6183#issuecomment-979365288

**Comment by zenmonkeykstop** [comment]
Closed by #6187
