### ISSUE TITLE
Deprecate usage of X-Download-Options header

### ISSUE THREAD

**Issue by evilaliv3** [freedomofpress/securedrop#6180]
With this ticket I would like to propose the deprecation of the usage of the ```X-Download-Options``` header that was actually supported only by IE and introduced in IE8 to fix their own broken download implementation.

Any up to date browser, including IE and Edge now does safely implement the noopen policy on file download while using the standard header ```Content-Disposition: attachment```: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

Considering that we do not target any IE browser (expecially IE 8 o IE9) we could safely remove the header that represents just an overhead.

This ticket follows the same evaluation applied to the GlobaLeaks project: https://github.com/globaleaks/GlobaLeaks/commit/8c1af7fd753c204c2c7828174c3d9e0823173bdb

**Comment by zenmonkeykstop** [comment]
`Content-disposition: attachment` is indeed being set as expected. This will be folded into a new PR along with other header changes, as per https://github.com/freedomofpress/securedrop/pull/6183#issuecomment-979365288

**Comment by zenmonkeykstop** [comment]
Closed by #6187
