### ISSUE TITLE
Deprecate usage of X-XSS-Protection header

### ISSUE THREAD

**Issue by evilaliv3** [freedomofpress/securedrop#6182]
With this ticket I would like to propose the deprecation of the usage of the ```X-XSS-Protection``` header that is actually supported only by IE and Safari: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

The same protection is no implemented by our current implementation of the CSP policy that disables inline JavaScript.

Considering that we do not target any IE or Safari browser browser (and expecially that IE is dead and replaced by Edge featuring a Chome engine) we could safely remove the header that represents just an overhead.

This ticket follows the same evaluation applied to the GlobaLeaks project: https://github.com/globaleaks/GlobaLeaks/commit/2c83b156b83b47487385d047474d63302a31539d

**Comment by zenmonkeykstop** [comment]
Closed by #6187
