### ISSUE TITLE
Remove securedrop-keyring package from securedrop repo.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6199]
## Description

The same signing key is used for Debian and Ubuntu packages, and the logic for building it is duplicated (with minor differences in layout) in this repo and in the https://github.com/freedomofpress/securedrop-debian-packaging repo.

To reduce build complexity (and because this package is rarely updated), it could be removed from the securedrop repo, adding `focal` a a target dist in https://github.com/freedomofpress/securedrop-debian-packaging instead.

## User Research Evidence
none

## User Stories
As a developer, I want the build to only include necessary artifacts.

**Comment by legoktm** [comment]
The workstation and server versions of this package are identical except for minor metadata things:
```
$ debdiff securedrop-keyring_0.1.5+2.3.2+focal_amd64.deb securedrop-keyring_0.1.5+buster_all.deb
[The following lists of changes regard files as different if they have
different names, permissions or owners.]

Files in second .deb but not in first
-------------------------------------
-rw-r--r--  root/root   /usr/share/doc/securedrop-keyring/changelog.gz
-rw-r--r--  root/root   /usr/share/doc/securedrop-keyring/copyright
-rw-r--r--  root/root   DEBIAN/conffiles
-rw-r--r--  root/root   DEBIAN/md5sums
-rwxr-xr-x  root/root   DEBIAN/postinst

Control files: lines which differ (wdiff format)
------------------------------------------------
Architecture: [-amd64-] {+all+}
Homepage: [-https://securedrop.org-] {+https://github.com/freedomofpress/securedrop-debian-packaging+}
{+Installed-Size: 23+}
[-Source: securedrop-]
Version: [-0.1.5+2.3.2+focal-] {+0.1.5+buster+}
```

It's a super duper trivial package, it just installs one file, so we can just build one deb and copy it across all 3 buster/bullseye/focal components.

**Comment by legoktm** [comment]
The goal here to de-duplicate the nearly-but-not-quite identical securedrop-keyring packages across server and SDW is good, but it seems more likely that SDW will move to bookworm first and start shipping the signing key in sources.list files so we'll still need the keyring package only for the server (since a move to jammy+ seems farther out)...so it should just stay here for the time being.
