### ISSUE TITLE
Ubuntu Groovy packages are no longer available for `builder-focal`

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6205]
## Description

`builder-focal` installs `dh-virtualenv` explicitly from Ubuntu Groovy, whose packages are no longer available at archive.ubuntu.com.  

https://github.com/freedomofpress/securedrop/blob/41d5414ff753c19fe467359220a0889228f0e3b1/molecule/builder-focal/Dockerfile#L37-L40

```sh-session
cfm@ozymandias ~ % curl -s http://archive.ubuntu.com/ubuntu/dists/ | grep "groovy" | wc -l
       0
cfm@ozymandias ~ % curl -s https://web.archive.org/web/20211130221857/http://archive.ubuntu.com/ubuntu/dists/ | grep "groovy" | wc -l
       5
```

`staging-test-with-rebase`, along anything else that uses the `builder-focal` Molecule scenario, will fail until this is resolved.

## Steps to Reproduce

https://app.circleci.com/pipelines/github/freedomofpress/securedrop/3386/workflows/cec934c8-66d5-416e-b529-5f7131796184/jobs/58508

## Expected Behavior

`staging-test-with-rebase` passes.

## Actual Behavior

`staging-test-with-rebase` fails with:

```
    TASK [Update apt-cache for our security checker] *******************************
fatal: [focal-sd-sec-update]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'http://archive.ubuntu.com/ubuntu groovy Release' does not have a Release file."}
```

## Comments

[There's still no `dh-virtualenv` available for Focal](https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=dh-virtualenv), so we'll have to kick (pin) this package down the road (to another non-LTS release).

**Comment by eloquence** [comment]
Thanks for the report @cfm, I've tried to address this in #6206. AIUI a maintainer with quay.io access will need to push the new build container to test it.
