### ISSUE TITLE
SI: Re-Style Passphrase Widget

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#6213]
_This is a child-issue to the epic #6211_ 

## Problem
Today's "Passphrase Widget" is problematic for many reasons, summarized across many touchpoints & reports:
- Lock semiotic confusing
- Refresh functionality opportunity for user error
- Colors outdated
- A11y unfriendly hide/show control

## Solution
_New to Figma? So are all of us! [Learn about SecureDrop on Figma.](https://github.com/freedomofpress/securedrop-ux/wiki/Using-Figma)_
- [ ] Create new hide/show control [per Figma](https://www.figma.com/file/rHT1RE7zpNttqIGdZpPkhQ/SI_FlowInversion-deux?node-id=572%3A4727)
- [ ] Implement re-designed passphrase widget that does the following:
- Kill `Remember your codename is:` string
- Kill padlock icon 
- Kill refresh control (Erik did already in PR #6195)
- Kill hide/show control _placed inside widget itself_.
- Resize rectangular container
- Place 28x28 weeble icon colored `grimace blue`. Mimic padding/positioning [within Figma](https://www.figma.com/file/rHT1RE7zpNttqIGdZpPkhQ/SI_FlowInversion-deux?node-id=572%3A4727).
- Container has 1px #FFFFFF outline & #FAFCFF fill
- Give dropshadow [per Figma](https://www.figma.com/file/rHT1RE7zpNttqIGdZpPkhQ/SI_FlowInversion-deux?node-id=572%3A4727)
- Place 7 irregularly wide #D0D3EB rectangles inside container for "Hidden" view. Rectangles imply redaction, do not need to dynamically resize to actual words. [See Figma](https://www.figma.com/file/rHT1RE7zpNttqIGdZpPkhQ/SI_FlowInversion-deux?node-id=572%3A4727) for sizing/padding/etc.
- Connect new A11y friendly hide/show control
- Typography: mmh... color `grimace blue` and make bold? May need to tweek size. Courier non-standard font, so probably want to stick with monospaced font. 

<img width="833" alt="Screen Shot 2022-01-04 at 6 55 00 PM" src="https://user-images.githubusercontent.com/8262612/148154518-a9b70add-ddc3-497f-b097-48f4b8ea7286.png">
<img width="199" alt="Screen Shot 2022-01-04 at 1 05 02 PM" src="https://user-images.githubusercontent.com/8262612/148154538-02d78ec4-e074-42a5-a75c-f3f4e81fe28a.png">
oops... above screenshot grabbed, before `:focus` state added to hide/show control. 😸

**Comment by eaon** [comment]
Fixed in #6315
