### ISSUE TITLE
Update Tor version to 0.4.6.9

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6218]
A new stable Tor version is available - the version used by securedrop should be updated accordingly.

Steps involved are as follows:

- [x] - update [securedrop fetch-tor-debs scenario](https://github.com/freedomofpress/securedrop/blob/c5d7766d886b6bf3c9fdc297e4bb21b960e58447/molecule/fetch-tor-packages/playbook.yml#L15) to pull 0.4.6.9 - See https://github.com/freedomofpress/securedrop/pull/6227
- [x] - in a clean build VM, download 0.4.6.9 packages using above scenario and add them to the apt-test repo via a PR into https://github.com/freedomofpress/securedrop-dev-packages-lfs - See https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/127
- [x] - verify basic Tor functionality using packages from apt-test in a staging or prod (VMs are fine) environment.
- [ ] - add the same 0.4.6.9 Tor packages to apt repo via a [PR into https://github.com/freedomofpress/securedrop-debian-packages-lfs/](https://github.com/freedomofpress/securedrop-debian-packages-lfs/pull/68)

**Comment by conorsch** [comment]
> in a clean build VM

For those using Qubes, see https://github.com/freedomofpress/securedrop-debian-packaging/wiki/FAQ#how-do-i-create-a-local-environment-suitable-for-building-packages. You'll need docker on top of the python dependencies to run the fetch tor debs logic.

**Comment by zenmonkeykstop** [comment]
Sadly not closed until the Tor packages are in prod...

**Comment by zenmonkeykstop** [comment]
I have installed the 0.4.6.9 packages on an otherwise prod instance. Tor behaviour seems unremarkable, SSH and JI auth services are available, as is the SI. Will review logs after an overnight reboot.

**Comment by zenmonkeykstop** [comment]
Packages are stable, will issue a PR into prod momentarily.

**Comment by conorsch** [comment]
Packages are live in prod, available here: https://apt.freedom.press/pool/main/t/tor/
