### ISSUE TITLE
[meta] Mastodon account for this project

### ISSUE THREAD

**Issue by linux-lukas** [freedomofpress/securedrop#6221]
Could a Mastodon account be worthwhile for the project?

A Mastodon account for the project would have several advantages: 

1. you would no longer have to rely on Twitter as a communication channel.
2. you can tap into new target groups => more people would become aware of your project and thus possibly also find potential supporters for your project.

**Comment by eloquence** [comment]
We have one: 
https://fosstodon.org/@securedrop

**Comment by conorsch** [comment]
@Lukas2112 Boy, do I have good news for you: https://fosstodon.org/@securedrop :smiley:

**Comment by linux-lukas** [comment]
Brilliant! This should definitely be added to the Prototype Fund page! :) 🥳 🎉 🥳 🎉 🥳 🎉
