### ISSUE TITLE
Switch from itsdangerous to another JWT library

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#6224]
## Description

An upcoming release of `itsdangerous`, 2.1, will drop support for JSON Web Signatures. The project maintainers recommend switching to `authlib` instead. Encountered the deprecation notice while performing a [diff review](https://github.com/freedomofpress/securedrop-debian-packaging/wiki/itsdangerous-0.24-to-2.0.1). See this [relevant GitHub issue](https://github.com/pallets/itsdangerous/issues/257) with maintainer comments.

**Comment by legoktm** [comment]
I'm still looking around, but authlib seems very heavy for our pretty minimal needs. I think something smaller that just does JWT/JWS might be a better fit? E.g. https://github.com/jpadilla/pyjwt

Via tokei, authlib is 17K Python LOC, while pyjwt is 1.6K (just the library, excluding tests).

**Comment by legoktm** [comment]
I reviewed the libraries listed at <https://jwt.io/libraries?language=Python>:

* pyjwt: Clean and straightforward API, code looked to be implemented correctly. No red flags in [past security issues](https://security-tracker.debian.org/tracker/source-package/pyjwt).
* python-jose: fork of pyjwt without clear justification, didn't seem to be any significant improvement
* jwcrypto: Not a fan [of the API](https://jwcrypto.readthedocs.io/en/latest/jwt.html#examples), seems harder to use than pyjwt
* authlib: contains a bunch of auth-related things, really overkill for what we need.

I'll push a PR to use pyjwt in a few minutes.
