### ISSUE TITLE
Consider using reprepro's update functionality instead of fetch-tor-packages

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6233]
## Description

We mirror the tor and tor-geoip packages from Tor's apt repo in to the one run by FPF to make sure new Tor versions don't accidentally break SecureDrops. Currently this is done with a custom fetch-tor-packages script, which requires you configure a container/VM with Tor's sources and uses SecureApt to download them, and runs some basic tests.

reprepro, which we use to build our apt repo, has this mirroring functionality built in: https://manpages.debian.org/bullseye/reprepro/reprepro.1.en.html#conf/updates (look at [Wikimedia's config for an example](https://gerrit.wikimedia.org/r/plugins/gitiles/operations/puppet/+/2dfe83dc68dcee6c92bae798d6a59acffbb567c3/modules/aptrepo/files/updates)).

I think it might reduce complexity to use reprepro's functionality instead of having our own script that does it. This also seems like something CI could prepare for apt-test and just have maintainers verify that checksums match and any other manual testing.

**Comment by zenmonkeykstop** [comment]
This makes a lot of sense to me:
- updating the test repo manually is kindof mindless and annoying so automating it would be good
- historically Tor updates were coupled with SD releases, but there is no reason for that, so just grabbing new stable versions when available and putting them up reduces lag between versions on our side and reduces release effort

Note that a manual signing operation is still required for the prod repos, so it can't be automated all the way through as it stands, but even getting said functionality into apt-test would be a nice win.

**Comment by legoktm** [comment]
I posted the reprepro config at https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/128. For CI I wasn't sure if we should be adding a CircleCI pipeline to the securedrop-dev-packages-lfs repo itself or in securedrop-debian-packaging, which is where the workstation auto-build CI lives.

**Comment by legoktm** [comment]
For prod, we could have CI push the tor update to a branch, leaving it for a human maintainer to test, verify checksums against deb.torproject.org and then sign. Or maybe it's easy enough to copy the debs over from the dev repo (and then test, verify, etc.) that having CI push to a branch doesn't add that much value.

**Comment by legoktm** [comment]
https://github.com/freedomofpress/securedrop-dev-packages-lfs/commit/d34805ee912af2bf17684ca8b79b84ab611492a3 ta-da!

At https://github.com/freedomofpress/securedrop-debian-packaging/pull/287#issuecomment-1068365009 I wrote:
> Ideally we'd create a pull request with the same Tor debs to securedrop-debian-packages-lfs which would trigger notifications for human review, however AFAICT that requires having a Github OAuth token, which I didn't see the jobs having (or at least I didn't see it explicitly being passed, maybe it's implicit??). If we don't have the OAuth token we can push to a new branch, but that would trigger the same level of notification in Slack, so I don't think it as a big win. In any case, I was leaving that part for a future PR once we confirmed this worked.

The securedrop-debian-packages-lfs repository is private (as an extra hardening measure I assume, not for obscurity), so we would be giving CI access to push to non-main branches (via SSH key), plus an OAuth token to create a PR. Do we want to open that up?

My current feeling is that given that maintainers would need to pull down the PR to sign the release file, it's not a significant amount of extra work to ask them to first copy the debs over from the securedrop-dev-packages-lfs repository.

**Comment by legoktm** [comment]
The last step for this (I think) is to get the docs PR merged: https://github.com/freedomofpress/securedrop-docs/pull/320.
