### ISSUE TITLE
Delete confirmation screenshots are garbled

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6248]
## Description

All the journalist-delete* variant screenshots have a garbled confirmation screen.

## Steps to Reproduce

Run `LOCALES=en_US make translation-test`

## Expected Behavior

Pulled from weblate (2.1.0):
![journalist-delete_all_confirmation_vTw1MQ5](https://user-images.githubusercontent.com/81392/152445463-4454b2f9-84f7-4362-b064-0a8096b9271c.png)

## Actual Behavior

![journalist-delete_all](https://user-images.githubusercontent.com/81392/152445314-0718c2c9-594d-4c92-ae19-ec7ae2ec9f48.png)
![journalist-delete_all_confirmation](https://user-images.githubusercontent.com/81392/152445317-88f80925-2e3a-4f30-9e8f-5598827e7794.png)
![journalist-delete_none](https://user-images.githubusercontent.com/81392/152445318-e35fc6e0-045e-4b39-ba70-1dcd3d58d0f6.png)
![journalist-delete_one](https://user-images.githubusercontent.com/81392/152445319-db675b8a-7795-482c-9094-7090724b102d.png)
![journalist-delete_one_confirmation](https://user-images.githubusercontent.com/81392/152445321-84960487-0756-4ffd-8642-c48d0a6f2b22.png)

**Comment by zenmonkeykstop** [comment]
:grimacing: that looks like an unintended consequence of recent CSS updates.

**Comment by legoktm** [comment]
Briefly discussed with @conorsch, for now we're just going to use the old 2.1.0 non-garbled screenshots. All of the other ones look fine though.

**Comment by legoktm** [comment]
I bisected this to, unsurprisingly, 5daebb694a581c9885d95459a5c87a57fbb68acc. I'm going to try to bisect the unsquashed branch to see if that helps to narrow it down.

**Comment by legoktm** [comment]
d22c9f8218b745f80b526b10f5328b956481caed adjusted how it looks:
![journalist-col_no_document_weird_04a2bd3e4e0a75](https://user-images.githubusercontent.com/81392/152462674-9c4717ca-ec88-46f7-a04b-78ee8ff435b5.png)

And then d48f18837c6d86fafd0b45139fce2d10819a89d4 is what made it all garbled.

**Comment by legoktm** [comment]
When I bump the Firefox version in the dev container to the current version, 91.5.0esr, which Tor Browser 11.0.4 is based on, then the screenshots come out fine. So this might just be a now-fixed browser bug...

**Comment by legoktm** [comment]
Yeah, all the screenshots look good now. I'll grab an old TB version to see how broken it is, maybe we need to include that explicitly as something journalists need to do (and I'd hope everyone is already using the latest TB...)

**Comment by legoktm** [comment]
I grabbed an old copy of Tor Browser 10.5 (based off of 78.15.0esr) from https://archive.torproject.org/tor-package-archive/torbrowser/10.5.10/ and the deletion confirmation window is entirely broken, as the screenshots indicate:
![Screenshot_2022-02-04_15-35-56](https://user-images.githubusercontent.com/81392/152617237-a0ba684c-be5c-4f8b-9f9e-78c823a2abb3.png)

I would think that using Tor Browser 10.x today is a security issue so no one should be using it, so hopefully this isn't a real problem that we need to worry about aside from updating the container.
