### ISSUE TITLE
Journalist API datetime format has changed, breaking client login.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6255]
## Description

See freedomofpress/securedrop-sdk#171 - the datetime format being returned by the Journalist API includes timezone info as a result of the Flask 2.0 update - previously it dd not, and the SecureDrop Client expects naive datetimes with no timezones.

## Steps to Reproduce

Attempt to use the client with a server running 2.2.0-rc1 or latest develop

## Expected Behavior

Client works as normal

## Actual Behavior

Client crashes with error in linked issue above

## Comments

A simple fix would be to force the datetime format to not include timezones in the API. There's a larger issue here of how to handle tz-aware datetimes in the client, but that might be too much to take on during the client process, it seems better to preserve the existing behaviour.

Looks like there are two potential areas to consider: the API token expiry datetime (which is probably causing the issue above), and the source last_updated field (which is used in the client). The first is a change in securedrop/journalist_app/api.py, the second is a change in models.py, in Source.to_json(). I don't think there are any other affected areas.

**Comment by gonzalo-bulnes** [comment]
> SecureDrop Client expects naive datetimes with no timezones.

I think this isn't totally accurate, rather, the format output by the server became recently invalid (`+00:00` and `Z` are redundant), which broke the Client expectations. This is still an effective workaround, and I described what I think is a good next step in https://github.com/freedomofpress/securedrop/issues/6257
