### ISSUE TITLE
./securedrop-admin setup -> E: Unable to locate package ccontrol

### ISSUE THREAD

**Issue by tchwpkgorg** [freedomofpress/securedrop#6268]
I'm trying to install SecureDrop. Unfortunately, it fails right at the beginning:

```
$ ./securedrop-admin setup
INFO: Installing SecureDrop Admin dependencies
INFO: You'll be prompted for the temporary Tails admin password, which was set on Tails login screen
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ccontrol
ERROR: Failed to install apt dependencies. Check network connection and try again.
```

I'm trying to install it on Ubuntu 20.04. Ubuntu does not have a "ccontrol" package.

**Comment by eloquence** [comment]
Hi @tchwpkgorg , the `./securedrop-admin setup` command must be run from the Admin Workstation, which runs the Tails live USB  operating system, not Ubuntu. Are you following the installation guide from the beginning, starting with https://docs.securedrop.org/en/stable/overview.html ?

**Comment by eloquence** [comment]
Hi @tchwpkgorg, I'm closing this issue per the above comment, let us know if you run into issues when running the command from Tails.
