### ISSUE TITLE
[2.2.0-rc2] Kernel panic with 5.5.18 kernel on Mac Mini

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#6271]
I installed the updated kernel on my Mac Minis, which were already running Ubuntu 20.04 and an old SecureDrop release (~1.8.0) with a 5.4.97 kernel.

On reboot, the kernel panicked with the following error output:

![20220215_114414](https://user-images.githubusercontent.com/213636/154152881-f22b9c33-a5b3-42ea-8912-014cc6e81ad8.jpg)

On both Mac Minis, I was subsequently unable to boot the machine at all. Even after a full power-cycle, the display was never initialized after the initial boot-up chime.

With assistance from @zenmonkeykstop, I was able to perform a PRAM reset by holding down Alt+Windows Key+P+R at the time of the initial chime. After that, the display initializes. But I now have to do this on each boot.

**Comment by eloquence** [comment]
If I bypass the initial boot problem and enter GRUB by holding down [Escape], adding the `nomodeset` kernel option as suggested by Kev resolves the issue (but the initial boot problem remains). I made the change permanent in the GRUB config; the behavior is the same (system now boots successfully after PRAM reset).

**Comment by zenmonkeykstop** [comment]
I replicated the kernel panic by installing securedrop-grsec on a stock ubuntu 20.04.3 install, but did not get the display issues. With `nomodeset`, system boots to console as expected for me, with no PRAM reset required. `paxtest` and speculative execution tests are same as with other hardware.
