### ISSUE TITLE
Untranslated strings in "remember codename" widget

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop#6287]
## Description

![image](https://user-images.githubusercontent.com/201369/154710374-e80efae0-a978-4c61-bbda-607cbf816fb9.png)

![image](https://user-images.githubusercontent.com/201369/154710484-020473ee-0e9b-4bab-84c7-c311f0411a92.png)

"Show" and "Hide" are injected via CSS, therefore never translated.

## Comments

Fixed easily by adding data attributes on the element and referencing those with CSS's `attr()` function

**Comment by cfm** [comment]
Another good catch, @eaon.  Thank you!

**Comment by cfm** [comment]
Another good catch, @eaon.  Thank you!  This might also be a more-elegant way to provide the strings currently stored in [`js-strings.html`](https://github.com/freedomofpress/securedrop/blob/ecd6b2b2309715ccbedc1b8b75c1daaa71ad1961/securedrop/journalist_templates/js-strings.html).
