### ISSUE TITLE
Update new "Get Codename" page in line with design recommendations

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#6311]
As part of the Source Interface design improvements (see #6210), we have broad consensus around language changes to the "codename" pages which could be made regardless of whether or not we ultimately fully reverse the password generation flow. This is ["E1" in Figma](https://www.figma.com/file/rHT1RE7zpNttqIGdZpPkhQ/SI_FlowInversion-deux?node-id=915%3A5608):
![Screenshot from 2022-02-28 16-50-53](https://user-images.githubusercontent.com/213636/156083829-9e10ef5e-5032-4f35-a931-c84a984e4352.png)

The wording changes, which were collaboratively workshopped at a couple of UX meetings, in summary:
- reduce text on the page to the essentials, clearly summarized
- avoid the potentially confusing phrase "using this codename will be the only way we have to communicate with you"
- change button to "Continue" instead of "Submit Documents" (avoid a button label that refers to a task that actually happens on the _next_ step)

This does _not_ change the word "codename" to "passphrase" yet, because a) that change needs to be carefully rolled out, given that the term has been used from the very beginning, b) we'll want to user-test the term "passphrase" before fully committing to that change, so we don't have to potentially change it twice.

The styling changes to the codename widget are the same as already implemented in @eaon's branch for #6211. The show/hide widget is also the same as implemented there (but the default state on this page would be "show", not "hide").

**Comment by eloquence** [comment]
(Retitled issue since the language updates have landed now.)

**Comment by eaon** [comment]
Fixed in #6315
