### ISSUE TITLE
question

### ISSUE THREAD

**Issue by P0cas** [freedomofpress/securedrop#6317]
```
Created journalist (username=journalist, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=True)
Created journalist (username=dellsberg, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Created journalist (username=clarkkent, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
```
Hey how to do login? I used as above account, but not working. and how to get a Two-factor code?

**Comment by eaon** [comment]
Hi there! The two-factor code secret is included in the excerpt you shared: `otp_secret=JHCOGO7VCER3EJ4L`, and if you have a look at [SecureDrop's documentation](https://docs.securedrop.org/en/stable/development/setup_development.html#using-the-docker-environment) you'll also find a QR code version and instructions how to generate a code from Python.

Good luck!

**Comment by P0cas** [comment]
Thanks for reply!
