### ISSUE TITLE
SI Tor Browser security level instructions are outdated

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop#6319]
## Description

When visiting the source interface with Tor Browser while JavaScript is enabled, a warning is displayed that includes a dialog with instructions of how to change it to "Safest". This dialog still references old language not used by recent versions of Tor Browser.

## Expected Behavior

The dialog showing up to date language to properly guide sources

## Actual Behavior

![2 2 0-tb-warning-dialog-open](https://user-images.githubusercontent.com/201369/157085523-9fcf6343-8f65-4de7-9bb7-f5d53f11789b.png)

![2 2 0-tb-warning-dialog-open-guard-dialog-open](https://user-images.githubusercontent.com/201369/157085541-7b9c38d4-1e01-4adb-8fbb-37e276e80ba3.png)

## Comments

When **Change** is selected, the TB opens up a new tab and shows the Security Level section of the browser preferences. I think we should probably indicate that the change happens in a new context. Maybe something along the lines of:

2. Select **Change** to open Security Level preferences
3. Select **Safest** and close preferences

**Comment by eloquence** [comment]
I would say:

> 2. Click **Change** to open Security Level preferences
> 3. Select **Safest** and close the preferences tab

Otherwise SGTM. ("Click" instead of "Select" because there is no selection of multiple options here.)
