### ISSUE TITLE
Update grsec kernel to 5.15.26

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6323]
## Description

A new 5.15 grsec patch is available including recent security fixes. We should update to it.

Steps involved:

- [x] Build updated grsec kernel and file a PR to add it to the apt-test repo
- [x] #6324
- [x] Create a 2.2.1 hotfix release containing only the kernel bump
- [x] Cut a 2.2.1-rc1 tag and a packages pr to add them to the apt-test repo
- [x] test the hotfix and kernel update
- [x] Cut a 2.2.1 release and push it to the production repo
- [x] cleanup

**Comment by legoktm** [comment]
2.2.1 was successfully released, closing.
