### ISSUE TITLE
Codename check triggers KeyError after subsequent login

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#6339]
# Steps to reproduce

1. Enable the new "Prevent sources from submitting their codename as an initial message" setting
2. Create a new source and submit message, note down the codename
3. Log out and log back in as that source
4. Submit another message

# Expected behavior

Message submitted

# Actual behavior

KeyError: 'new_user_codename'

**Comment by zenmonkeykstop** [comment]
Makes sense in retrospect, as that value is no longer in the session on the return visit. Fix inbound
