### ISSUE TITLE
Next schema change will fail test_schema_unchanged_after_up_then_downgrade because of instance_config weirdness

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6352]
## Description

The next schema change will fail the `test_schema_unchanged_after_up_then_downgrade` test because of something wrong with the `instance_config` table:

```
E               AssertionError: Schema for ('table', 'instance_config', 'instance_config') did not match:
E               Left:
E               CREATE TABLE "instance_config" (
E               	version INTEGER NOT NULL, 
E               	valid_until DATETIME NOT NULL, 
E               	allow_document_uploads BOOLEAN, 
E               	organization_name VARCHAR(255), 
E               	initial_message_min_len INTEGER DEFAULT '0' NOT NULL, 
E               	reject_message_with_codename BOOLEAN DEFAULT '0' NOT NULL, 
E               	PRIMARY KEY (version), 
E               	CHECK (allow_document_uploads IN (0, 1)), 
E               	CHECK (reject_message_with_codename IN (0, 1)), 
E               	CHECK (reject_message_with_codename IN (0, 1)), 
E               	UNIQUE (valid_until)
E               )
E               Right:
E               CREATE TABLE "instance_config" (
E               	version INTEGER NOT NULL, 
E               	valid_until DATETIME NOT NULL, 
E               	allow_document_uploads BOOLEAN, 
E               	organization_name VARCHAR(255), 
E               	initial_message_min_len INTEGER DEFAULT '0' NOT NULL, 
E               	reject_message_with_codename BOOLEAN DEFAULT '0' NOT NULL, 
E               	PRIMARY KEY (version), 
E               	CHECK (allow_document_uploads IN (0, 1)), 
E               	CHECK (reject_message_with_codename IN (0, 1)), 
E               	CHECK (reject_message_with_codename IN (0, 1)), 
E               	UNIQUE (valid_until)
E               )

tests/test_alembic.py:63: AssertionError
```

You will notice that both of those schemas are identical.

## Steps to Reproduce

Create an entirely no-op migration, like https://gist.github.com/legoktm/c0384c339e1485c350bbc6d1b6b2da6b

## Expected Behavior

Tests pass

## Actual Behavior

See failure above.

## Comments

I ran into this while working on https://github.com/freedomofpress/securedrop/pull/6350. @zenmonkeykstop since you touched this part in https://github.com/freedomofpress/securedrop/commit/fb36b50afbfe96d988af0c19de16d424fff2e6b1#diff-1d479d01d55da852b7ea6c4f260fe28e83b88438446013fa093754299d063461, do you have any initial ideas what the problem might be? Otherwise I'll start poking at it.

**Comment by zenmonkeykstop** [comment]
Updated that test to deal with duplicate CHECK constraints, but that's only being applied on the alembic-generated schema IIRC. If the duplicate CHECK is also now on the model-generated schema, it would also need to have the same deduping applied (or we could just drop the deduping on the alembic side - it should no longer be necessary if the CHECKS are the same in both).

**Comment by legoktm** [comment]
Yeah, the failure is because we're not deduping the right side.

But the test passes just fine with the deduping removed on both `develop` and with a dummy schema change, so I think we're better off just removing the deduping. Will submit a PR shortly.
