### ISSUE TITLE
Organization name gets escaped twice

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop#6357]
## Description

When configuring an instance's name as (for example) "Hello & World", the `&` shows up as `&amp;` wherever the organization name is used, because it is escaped when it is being set and again when it is being displayed. 

## Comments

As far as I can tell, the organization name is the only user provided input that is escaped before it is set - oversight or intentional?

**Comment by zenmonkeykstop** [comment]
Probably more overzealousness!
