### ISSUE TITLE
include accesssibility and localization in test plans/matrices

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6388]
## Description

We should consider explicitly including accessibility and localization in QA test plans and matrices.  This is a tracking issue until these documents are created for the v2.4.0 release.

Assistive tech could be treated as a dimension of testing just like server hardware, with one tester assigned to step through the test plan in a screen-reader.

Localization testing could be done on a volunteer basis, with one or more folks volunteering to step through the usual test plan in the language of their choice.  (The goal here is not to test the translations themselves but rather how SecureDrop behaves in a non-default locale.)

## User Stories

As a developer, I want more (and more-routine) familiarity with how different users—of different locales and abilities—experience the software I work on.

**Comment by cfm** [comment]
Deferring to v2.5.0—happily, because v2.4.0's test plan in #6440 includes explicit accessibility testing!

**Comment by cfm** [comment]
@zenmonkeykstop, I've taken the liberty of proposing in v2.5.0's QA matrix two top-level parameter rows:

* **Assistive tech:**  For each release, at least one person should step through (at least) acceptance testing using a [screen-reader](https://github.com/freedomofpress/securedrop/wiki/Accessibility) or other assistive tech.
    * I think we can skip this for v2.5.0, since it has no user-facing changes.  But the row will carry forward to the next QA matrix.  :-)
* **Locale:**  For each release, at least one person (one of the Localization Managers?) should step through all of their assigned QA in a non-`en_US` locale.
    * This I think we *should* do for v2.5.0, since it costs virtually zero marginal effort to ease into this practice while the stakes are low!  (CC: @eaon)

**Comment by zenmonkeykstop** [comment]
Both of these seem like reasonable additions, thanks @cfm.

**Comment by cfm** [comment]
These additions have already proven their worth in this QA cycle.  I'll close this ticket and defer to future Release Managers to tweak QA assignments on these dimensions as we do on platform and Tails version.
