### ISSUE TITLE
"Tor Browser" link in tor2web warning is broken

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6393]
## Description

The "Tor Browser" link in the tor2web warning is broken because it does not specify a protocol, so the browser treats it as a relative link.

## Steps to Reproduce

* Visit `/tor2web-warning` in the SI
* Hover over or click on the "Tor Browser" link, it should send you to a non-existent `/www.torproject.org/projects/torbrowser.html` on the SI's domain.

## Expected Behavior

* Link takes you to Tor Project website.

## Comments

Fix should be as simple as adding "https://" in front.

**Comment by zenmonkeykstop** [comment]
Given that this link is gonna be on a tor2web-proxied page potentially with analytics, maybe we shouldn't even have it.

**Comment by legoktm** [comment]
I do think we need a way to direct them into the Tor network.

Maybe we include it as a plaintext link, like we do the onion address, so basic click tracking analytics hopefully wouldn't pick it up (but maybe fancy clipboard tracking would??).

**Comment by legoktm** [comment]
![Screenshot 2022-04-11 at 18-18-55 SecureDrop Protecting Journalists and Sources](https://user-images.githubusercontent.com/81392/162842717-1d9e174d-1513-4f9a-8f8c-d3c550f6f0d3.png)

Or alternatively:

![Screenshot 2022-04-11 at 18-23-26 SecureDrop Protecting Journalists and Sources](https://user-images.githubusercontent.com/81392/162843197-78727015-4350-44b8-b434-6f3ba570f3af.png)

**Comment by legoktm** [comment]
@tina-ux if you have any suggestions here. For background, this is the warning we show when we detect that users are using a "Tor2Web" proxy to access the Source Interface, which deanonymizes them and often these proxies have trackers like Google Analytics, etc. So we want to make sure if they haven't already, download Tor Browser, and then provide them with the correct Onion URL.

**Comment by zenmonkeykstop** [comment]
There are existing strings describing how to get Tor Browser (including the email option? is that still a thing?) in  `source_templates/use-tor-browser.html` - it might make sense to reuse them (either cutting and pasting or adding an include to both templates) so as to reduce translation overhead.

**Comment by eaon** [comment]
In #6430 I went with the first option @legoktm suggested.

Regarding options other than the download link for Tor Browser, I'm rather skeptical of including those here, but am open to further discussion in a context where we talk about how we communicate with (to?) sources. (This is me making the assumption that more text/instruction isn't always helpful)
