### ISSUE TITLE
runtime `i18n` configuration manipulates global state

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6420]
I guess we already do this for LOCALES, but I think continuing the pattern should be accompanied by a TODO that manipulating/relying on global state is not desirable.

_Originally posted by @legoktm in https://github.com/freedomofpress/securedrop/pull/6406#discussion_r863080227_

**Comment by legoktm** [comment]
(This is not a good first issue yet, I will add some more detail on what the plan is to fix this before it's ready for others to take on)
