### ISSUE TITLE
Update flake8/pyflakes so it understands new mypy comments

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6427]
*This is a good first issue for new contributors to take on, if you have any questions, please ask on the task or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!*

The old version of flake8/pyflakes doesn't understand advanced mypy type comments like `# type: ignore[override]`. This was fixed in https://github.com/PyCQA/pyflakes/pull/455 (pyflakes 2.2.0 I believe).

```
securedrop/store.py:32:    from tempfile import _TemporaryFileWrapper  # type: ignore # noqa: F401
securedrop/journalist_app/sessions.py:125:    def save_session(  # type: ignore[override] # noqa
```

(the second instance is from the unmerged sessions PR)

**Comment by rocodes** [comment]
(This will be resolved by https://github.com/freedomofpress/securedrop/pull/6885)

**Comment by legoktm** [comment]
Indeed, we've dropped flake8/pyflakes entirely with ruff now.
