### ISSUE TITLE
Update grsecurity-patched kernels for retbleed patches

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6496]
## Description

https://comsec.ethz.ch/research/microarch/retbleed/ - once patches are released for stable kernels, we will need to build and release them (currently still needs a SecureDrop release).

A grsecurity patch is now available against thr 5.15.57 kernel, steps to release are as follows:
- [x] Build updated grsec kernel and file a PR to add it to the apt-test repo (https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/172)
- [x] Bump the kernel version in the securedrop repo (https://github.com/freedomofpress/securedrop/pull/6506)
- [x] Create a 2.4.2 hotfix release containing only the kernel bump
- [x] Cut a 2.4.2-rc1 tag and a packages pr to add them to the apt-test repo
- [x] test the hotfix and kernel update
- [x] Cut a 2.4.2 release and push it to the production repo
- [ ] cleanup

Workstation ticket: https://github.com/freedomofpress/securedrop-workstation/issues/809

**Comment by legoktm** [comment]
5.15.57 dropped today with the retbleed patches: https://lwn.net/Articles/902317/

**Comment by zenmonkeykstop** [comment]
Now also available in grsec patches as of 28/07.

**Comment by legoktm** [comment]
2.4.2 was released with an updated kernel.
