### ISSUE TITLE
Create a developers.securedrop.org Sphinx docs site for developer docs

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#6520]
Currently we have developer documentation split out in a few places:
- https://docs.securedrop.org/, as its own section below the end user documentation
- Various GitHub wikis
- Various GitHub READMEs (e.g. https://github.com/freedomofpress/securedrop-workstation/blob/main/README.md) 
- FPF-internal resources

To make developer docs more discoverable and consistent, I would propose the following delineation:
- `developers.securedrop.org` as a Sphinx doc (docs.securedrop.org style) site for all canonical developer documentation across SD Server and SD Workstation
- `docs.securedrop.org` and `workstation.securedrop.org` are reserved purely for journalist/admin documentation
- wikis are used primarily for unstructured tips, meeting notes, proposals, and ad hoc documentation; procedural documentation (e.g., QA guidelines) is gradually moved to `developers.securedrop.org`
- READMEs are primarily used as overviews and "Quick start guides"; detailed guidelines, threat model information, etc. are gradually moved to `developers.securedrop.org`

This would be a fair bit of continuous cleanup work, but we could start iteratively by simply moving the entire existing "Developer Documentation" section of https://docs.securedrop.org/ to `developers.securedrop.org` and keep going from there following these principles.

**Comment by gonzalo-bulnes** [comment]
I'm up for that. :hand:

**Comment by eloquence** [comment]
[`securedrop-dev-docs`](https://github.com/freedomofpress/securedrop-dev-docs/) now exists as an experimental repo. It's based off `securedrop-docs` so we preserve a full history (at the cost of a larger repo size). I've opened a draft PR that does the initial split (i.e. removal of all non-developer docs from that repo). I would appreciate comments on that approach before I mark the PR ready for review:

https://github.com/freedomofpress/securedrop-dev-docs/pull/1

**Comment by gonzalo-bulnes** [comment]
Thanks for moving this forward @eloquence!

The approach makes sense to me, including the starting point from securedrop-docs. If both repos have their initial conmits in common, it will be straightforward to merge them back if later on we decide to, for example, maintain de developer docs from a long-lived branch on this repo instead of a separate repo. (Not that I think that's likely to happen, but it can be done and it makes the decision to split easier.)

I'll flag the PR to review it when you mark it as ready for review. 🔖

**Comment by eloquence** [comment]
Thank you, Gonzalo! On a side note, IMO this split also would make it easier to potentially integrate https://workstation.securedrop.org/ into https://docs.securedrop.org down the road, rather than treating it as its own discrete product documentation -- but that's a separate discussion, and I think closely tied to general availability of the SecureDrop Workstation.

**Comment by eloquence** [comment]
@maeve-fpf The staging site at https://staging-dev-docs.securedrop.org/ looks great to me, so in principle I think we're ready to promote this to prod `developers.securedrop.org`. I say "in principle" because I'm not sure builds are fully working yet; #2 was merged earlier today and I don't see it reflected in the live build (I've not attempted a Cloudflare cache purge yet).

**Comment by maeve-fpf** [comment]
I will check this out when renaming the host from `dev.` to `developers.`, but I'm pretty sure it's because builds will try to modify tags in `main` by default, and the branch isn't merge this. I can override this with an env var in the Codefresh pipeline, so I will do that when going through some additional testing tomorrow.

**Comment by eloquence** [comment]
https://github.com/freedomofpress/securedrop-workstation/pull/828 is the README counterpart to https://github.com/freedomofpress/securedrop-dev-docs/pull/2 and removes the subsequently redundant parts from the README. I'll promote it to ready once the new docs site is live.

If that approach seems reasonable, my next target to merge-and-simplifiy would be the unwieldy https://github.com/freedomofpress/securedrop-debian-packaging/ README.

**Comment by eloquence** [comment]
Here are the next steps as I understand them:
- The following PRs can be approved in draft form by anyone, in any order:
  - https://github.com/freedomofpress/securedrop-dev-docs/pull/6
  - https://github.com/freedomofpress/securedrop/pull/6556
  - https://github.com/freedomofpress/securedrop-docs/pull/387
- Once all three PRs are approved, I can merge them and update https://securedrop.org/faq/about-securedrop/ and https://securedrop.org/contribute/ to point to the new site

Let me know if I'm missing any other key places to update (there are no references in https://workstation.securedrop.org/ or https://support-docs.securedrop.org/).

**Comment by eloquence** [comment]
Per feedback from Kev I've moved the docs into the parent directory in https://github.com/freedomofpress/securedrop-dev-docs/pull/7. This is now ready for review, and if that looks good, the three PRs above will unfortunately need to be re-reviewed due to the updated URLs (thanks for the first round @legoktm).

**Comment by eloquence** [comment]
Alright, this is _mostly_ completed and all the above changes have been applied. Still need to update documentation guidelines in https://developers.securedrop.org/en/latest/documentation_guidelines.html - once that's done, I think we can close this issue.

**Comment by eloquence** [comment]
That last bit was addressed in https://github.com/freedomofpress/securedrop-dev-docs/pull/15, and we also added redirects in https://github.com/freedomofpress/securedrop-docs/pull/393. So this can be closed, with any further dev docs changes tracked as separate issues.
