### ISSUE TITLE
KeePassXC entry for "App Server SSH Onion URL" has wrong description

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6523]
## Expected behavior
* "App Server SSH Onion URL" has a description (or none) that matches what it's for.

## Actual behavior
* It has the same description as the app/mon user passphrases.

**Comment by nathandyer** [comment]
This is stored in the `tails_files/securedrop-keepassx.kdbx` database in the SecureDrop repository. Because this isn't directly related to anything in the SecureDrop Docs repo, I'm going to transfer this over to the SecureDrop repo, and file a PR for an updated KeePassXC database.
