### ISSUE TITLE
Use gpgv for signature verification in dev Dockerfile

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6526]
## Description

https://github.com/freedomofpress/securedrop/blob/develop/securedrop/dockerfiles/focal/python3/Dockerfile

In the dev Dockerfile, we download a few things and then verify their signatures using `gpg --verify`. We should use `gpgv` instead, it's lighter and built to just do one thing, verification. We can also have it verify signatures against just the key we want with `--keyring` instead of having to grep the gpg output for the key that did the verification.

https://github.com/freedomofpress/kernel-builder/commit/782f04a8691773918f58e94a84ccfc52433f1c26 is an example of how I converted from gpg to gpgv in another repository.

**Comment by noumxn** [comment]
hi @legoktm, I would love to volunteer and work on this issue. If this issue hasn't been assigned yet, and if its okay with you, could you please assign this to me?
Thank you!

**Comment by legoktm** [comment]
@noumxn: done, let me know if you need any assistance or have questions here or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!
