### ISSUE TITLE
Remove usage of lsb_release

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6527]
## Description

lsb_release is mostly obsolete these days, instead we should read from `/etc/os-release`.

It's still used in https://github.com/freedomofpress/securedrop/blob/develop/securedrop/server_os.py, as well as:
```
user@dev ~/g/f/securedrop> ack lsb_release --ignore-dir=.venv
admin/bootstrap.py
67:        id = subprocess.check_output("lsb_release --id --short", shell=True).decode("utf-8").strip()
88:            dist = subprocess.check_output("lsb_release --codename --short", shell=True).strip()

securedrop/server_os.py
10:        ["/usr/bin/lsb_release", "--release", "--short"],

install_files/ansible-base/roles/tails-config/files/securedrop_init.py
127:cmd = ["lsb_release", "--id", "--short"]

install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/files/usr.sbin.apache2
101:  /usr/bin/lsb_release rix,

install_files/ansible-base/inventory-dynamic
131:    Returns output of `lsb_release --id --short`, to check
134:    cmd = ["lsb_release", "--id", "--short"]

install_files/securedrop-app-code/debian/rules
5:SECUREDROP_BUILD_PLATFORM=$(shell lsb_release -sc)
```

* https://0pointer.de/blog/projects/os-release (announcement, addresses "why not lsb_release")
* https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by jameelkaisar** [comment]
Should we use grep/awk to read `VERSION_ID` from `/etc/os-release`?

```
$ /usr/bin/lsb_release --release --short
20.04
$ cat /etc/os-release | grep VERSION_ID | cut -d \" -f 2
20.04
$ awk -F\" '$1=="VERSION_ID=" { print $2 ;}' /etc/os-release
20.04
```

**Comment by legoktm** [comment]
So in Python code I think we can just do the string parsing in Python itself.

For shell scripting I tend to like `source /etc/os-release` and then use them as environment variables. But if that's not possible, or not a good idea because of potential name conflicts, then yeah, some grep/cut/awk oneliner is fine.

**Comment by legoktm** [comment]
Noting for posterity that I commented in the Tails bug tracker about shipping a standards-compliant `/etc/os-release` file: https://gitlab.tails.boum.org/tails/tails/-/issues/12372#note_194944
