### ISSUE TITLE
LGTM.com shutting down in December 2022

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6542]
## Description

LGTM.com, which we use for some Python and JavaScript checks, is shutting down at the end of the year: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

Their recommendation is to move to "GitHub code scanning".

**Comment by legoktm** [comment]
I tagged this with needs discussion because my personal opinion is that the checks were not useful and if we just dropped them that would be fine. I think other people liked them though? In which case we need to find a replacement.

**Comment by eloquence** [comment]
https://github.com/freedomofpress/securedrop/pull/6537#issuecomment-1239541960 is an example of an LGTM report which I think is somewhat useful. It looks like GitHub's code scanning feature is also based on CodeQL and intended to fully replace LGTM. I defer to @zenmonkeykstop and our security engineers, but I would recommend that we switch over to GitHub's code scanning feature in repos that use LGTM and then re-evaluate after a while whether to expand usage or discontinue it.

**Comment by legoktm** [comment]
> [#6537 (comment)](https://github.com/freedomofpress/securedrop/pull/6537#issuecomment-1239541960) is an example of an LGTM report which I think is somewhat useful.

All of those are already pylint checks:
* Unused import: https://pylint.pycqa.org/en/latest/user_guide/messages/warning/unused-import.html
* Non-callable called: https://pylint.pycqa.org/en/latest/user_guide/messages/error/not-callable.html
* Unreachable code: https://pylint.pycqa.org/en/latest/user_guide/messages/warning/unreachable.html

The only reason that `make app-lint` doesn't fail on that PR right now is we currently only run pylint over `securedrop/` and the newly added files are in a separate directory. I assume that'll be fixed before it lands.

**Comment by eloquence** [comment]
That's fair; it does look like GitHub's CodeQL support is fairly configurable and there may be a narrower subset of checks that usefully complements the ones we already have. [Here's](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/#python-built-in-support) an overview of the built-in checks.

**Comment by legoktm** [comment]
From https://github.com/freedomofpress/securedrop/pull/6551#pullrequestreview-1127047557:
> Surprisingly this is the first case I've encountered of LGTM actually pointing out a real issue, I wonder if pylint is not running on our scripts (will file a separate task for that).

**Comment by eloquence** [comment]
Closing per https://github.com/freedomofpress/securedrop/pull/6688#issuecomment-1412360606
