### ISSUE TITLE
Fix yamllint warnings, enable strict mode

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6575]
*This is a good first issue for new contributors to take on, if you have any questions, please ask on the task or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!*

## Description

We currently have some yamllint warnings:

```
$ make yamllint
███ Linting YAML files...
./.circleci/config.yml
  78:221    warning  line too long (293 > 220 characters)  (line-length)
  256:221   warning  line too long (222 > 220 characters)  (line-length)
  262:221   warning  line too long (224 > 220 characters)  (line-length)

./install_files/ansible-base/roles/validate/tasks/validate_tails_environment.yml
  81:4      warning  wrong indentation: expected 4 but found 3  (indentation)

./install_files/ansible-base/roles/restore/tasks/perform_restore.yml
  112:9     warning  too many spaces after hyphen  (hyphens)

./install_files/ansible-base/group_vars/securedrop_application_server.yml
  12:5      warning  too many spaces after hyphen  (hyphens)
```

These should be fixed. Then we can enable `--strict` mode (in `devops/scripts/yaml-lint.sh`) so that any future warnings will cause CI to fail.

**Comment by IlyesSemlali** [comment]
Hi ! 

I'd like to work on this, can you assign it to me ?

**Comment by zenmonkeykstop** [comment]
Absolutely, have at it.

**Comment by legoktm** [comment]
@IlyesSemlali how's it going so far? Is there anything you need help with?

**Comment by IlyesSemlali** [comment]
Hi, sorry I haven't been able to check that yet, I'll be working on it tonight
