### ISSUE TITLE
Run flake8 against alembic migrations

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6576]
*This is a good first issue for new contributors to take on, if you have any questions, please ask on the task or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!*

## Description

In `.flake8` we currently exclude `securedrop/alembic/versions`. We should be running flake8 against those files by removing the exclusion and fixing any new flake8 errors.

**Comment by rahulXs** [comment]
Hi, I would to work on it. Could you please assign it to me? Thanks!
