### ISSUE TITLE
Upgrade to flask 2.0.3

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6577]
*This is a good first issue for new contributors to take on, if you have any questions, please ask on the task or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!*

## Description

We currently have some type checking disabled because of a bug in flask 2.0.2 that was fixed in 2.0.3. We don't want to upgrade to 2.1.0+ yet since that's a much bigger step.

```
    # TODO: enable type checking once upstream Flask fix is available. See:
    # https://github.com/pallets/flask/issues/4295
    @app.errorhandler(CSRFError)  # type: ignore
    def handle_csrf_error(e: CSRFError) -> "Response":
```

## How to fix

You'll want to update the dependency in `securedrop-app-code-requirements.in`, probably `Flask>=2.0.3,<2.1.0`, run `make update-python3-requirements` to build the new `securedrop-app-code-requirements.txt`.

Then disable the mypy overrides (and ensure mypy passes) and test basic submission functionality using the dev container.

Note that for dependency updates we require a "[diff review](https://github.com/freedomofpress/securedrop/wiki/Dependency-specification-and-update-policies)" to be done. This will be done by a SecureDrop maintainer after you submit a PR.

**Comment by rsk2** [comment]
Hi @legoktm, can I work on this?

**Comment by zenmonkeykstop** [comment]
> Hi @legoktm, can I work on this?

Feel free! let us know if you have any questions.

**Comment by rsk2** [comment]
@zenmonkeykstop , @legoktm I referred [this document](https://developers.securedrop.org/en/latest/setup_development.html) but I am not entirely sure how to setup the development environment since I am using windows. Can you please guide me?

**Comment by legoktm** [comment]
Unfortunately we don't have a lot of guidance for using Windows, do you have the Windows Subsystem for Linux (WSL) set up? You'll also need to install Docker.

**Comment by rsk2** [comment]
Sorry, I can't help with this issue.

**Comment by rohitsm** [comment]
Hi @legoktm! Could I work on this issue?

**Comment by legoktm** [comment]
Go for it! Let us know if you have any questions

**Comment by rohitsm** [comment]
@legoktm - Could you pls help to clarify the following questions? 

**Q1.**
> _...disable the mypy overrides (and ensure mypy passes)...._

I disabled the `mypy` overrides and ran `mypy` on the repo. I manually inspected the output and verified that no failures seen that were related to type checking on the `handle_csrf_error()` methods. Would this be sufficient or are there any other executions?

**Q2:**
> _... test basic submission functionality using the dev container..._

Are there specific functionality that needs to be checked additionally? I followed the documentation listed here: https://developers.securedrop.org/en/latest/testing_application_tests.html and was able to verify that all the functional and page layout tests passed successfully.

**Comment by legoktm** [comment]
1. Nope, that's it. CI verifies mypy too, so it's all good.
2. Usually I manually submit a message and then log into the Journalist Interface and verify it shows up. If the tests pass (and they did in CI too), then that's more comprehensive then any manual testing.

**Comment by rohitsm** [comment]
Thanks @legoktm. I ran the tests and they all passed. I have marked the above PR as ready for review.
