### ISSUE TITLE
after installation, Apache tries to compile initialized `config.py`

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6600]
## Description

After #6591, the Ansible task [`initialize_securedrop_app`](https://github.com/freedomofpress/securedrop/blob/012d30e8baeb8ffa7c10a56f4b43c464abf87cf7/install_files/ansible-base/roles/app/tasks/initialize_securedrop_app.yml) yields an AppArmor denial, since it copies `config.py.example` to `config.py` *after* the `postinst` `refresh_bytecode()` routine is executed during installation of `securedrop-app-code`.

## Steps to Reproduce

https://circleci.com/gh/freedomofpress/securedrop/64880

## Expected Behavior

`test_aa_no_denies_in_syslog[ansible://app-staging]` passes.

## Actual Behavior

`test_aa_no_denies_in_syslog[ansible://app-staging]` fails.

## Comments

Although the `postinst` script should be idempotent enough to call safely with `dpkg-reconfigure`, @zenmonkeykstop suggests it may be simpler to recompile the Python bytecode directly after copying `config.py.example` to `config.py` in `initialize_securedrop_app`.

**Comment by zenmonkeykstop** [comment]
Looks like pre-compiling the populated `config.py` doesn't help, Apache still tries to build it beforehand when starting the source and journalist WSGI processes from the postinst, so there will still be  apparmor denies triggered. One option would be to add a postinst check for the config.py file, and only restart apache from it if the file exists:
- for the install case, this means that installing securedrop-app-code will not restart apache, so the provisioning scripts will be responsible for doing so once config.py is updated
- for the upgrade case, apache will be restarted.

If this doesn't help, I think we need to revert the apparmor pycache change for now in support of unblocking the release.

**Comment by legoktm** [comment]
My inclination would be to revert the apparmor `__pycache__` change for now, so we get some benefit from precompiling, but will still see some on-the-fly generation, which is not great but given that it's the status quo it seems fine for this release.

**Comment by zenmonkeykstop** [comment]
Yup, that's what I'm doing as I type - rolling it back  it for the `/var/www/securedrop/`  pycache directories at least. A PR will be forthcoming, followed by backport, followed by RC2.
