### ISSUE TITLE
Update ubuntu_config.md with steps for network configuration

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#662]
I am hoping @garrettr can update this issue with more information, but the short version is that we need to update ubuntu_config.md with steps for network configuration. Instead of allowing DHCP to autoconfigure, users should cancel while it's doing that, choose "Configure network manually", and then enter reasonable values (e.g. 192.168.1.50 for app and 192.168.1.51 for mon).

**Comment by dolanjs** [comment]
Think this issue was resolved and can be closed. In the current ubuntu_config.md we have the #configure-the-network-manually section which covers this with the updated values.

**Comment by ageis** [comment]
Agreed on closure, but for the sake of argument, I like using Google's nameservers. Theoretically if you controlled the corporate nameserver plus Debian's signing key, you could serve compromised packages, right?

**Comment by conorsch** [comment]
Previous comments already indicate that this issue has been resolved, so closing.

The [official docs now include](https://docs.securedrop.org/en/stable/servers.html#configure-the-network-manually) explicit language about manually specifying the IPv4 addresses during OS installation: 

> The Ubuntu installer will try to autoconfigure networking for the server you are setting up; however, SecureDrop 0.3 requires manual network configuration. You can hit **Cancel** at any point during network autoconfiguration to be given the choice to *Configure the network manually*.

> If network autoconfiguration completes before you can do this, the next window will ask for your hostname. To get back to the choice of configuring the network manually, **Cancel** the step that asks you to set a hostname and choose the manu option that says **Configure the network manually** instead.

Similar examples are provided in the [Network Firewall setup docs](https://docs.securedrop.org/en/stable/network_firewall.html#nic-configuration), as well.
