### ISSUE TITLE
Add a background TOTP generator to the dev environment

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6621]
## Description

The JI requires 2FA using TOTP or HOTP, this adds a little bit of extra complexity for devs when working in the dev environment in particular. Since the TOTP secrets for default accounts are known, it should be possible to add a job that periodically outputs the token values for journalist accounts to Docker's stdout, saving devs the hassle of using oathtool or an authentication app when working on the JI.

## User Research Evidence
n/a - suggested as a hackathon prep idea

## User Stories
As a dev, I don't want to have to manage TOTP secrets for accounts in the dev environment in the same was as I would "real" ones.

**Comment by eaon** [comment]
I wonder if we should add this to the cheat sheet or maybe the `Makefile`? Interleaving access log / core reload with 2FA codes every 30 seconds sounds unnecessarily noisy to me.

I have an alias piping `oathtool` output to `wl-copy` / `xclip`, maybe that's good to share?

**Comment by zenmonkeykstop** [comment]
That sounds like a worthwhile approach!
