### ISSUE TITLE
Translation-related errors in output when running `make dev`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#6628]
Haven't tried to prune Docker files yet, so might be specific to my env (this is on latest `develop`). Seeing errors like this:

```
WARNING: Start of line didn't match any expected keyword.
WARNING: Problem on line 1258: '| msgid "Must be at least {num} character long."'
WARNING: Start of line didn't match any expected keyword.
WARNING: Problem on line 1259: '| msgid_plural "Must be at least {num} characters long."'
compiling catalog /home/erik/Code/securedrop/securedrop/translations/fr_FR/LC_MESSAGES/messages.po to /home/erik/Code/securedrop/securedrop/translations/fr_FR/LC_MESSAGES/messages.mo
```

**Comment by zenmonkeykstop** [comment]
Connfirmed on `develop`. Can repro after running `docker system prune --all`.

**Comment by zenmonkeykstop** [comment]
Not an issue on `release/2.5.0`, so probably related to the `sh` dependency removal in `i18n_tool.py`.

**Comment by legoktm** [comment]
Yep :( bisected to 21ebdc8d9a04f228d7fb0643a3e81745cc17db90. Debugging now...

**Comment by legoktm** [comment]
The warnings have always been there, the old code just suppressed them instead of letting them print. I'll restore that behavior in a few minutes.

The warnings itself are because of https://github.com/python-babel/babel/issues/566 and seem harmless.
