### ISSUE TITLE
Add support for Intel NUC 12s

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop#6662]
## Description

Intel NUC 11s are coming up on the 'end of sale' date for many retailers, and NUC 12s are now widely available. We should test and officially support these newer NUCs.

## Steps to Verify and Add Support for NUC12s
- [x] Acquire a [NUC12WSKi5](https://simplynuc.com/product/nuc12wski5-full/)
- [x] Verify that Focal server installation works, system boots with ~default kernel~ without error (HWE needed)
- [x] Install latest SD grsec kernel, verify system boots with new kernel without error
- [x] Update documentation references and add NUC12 to the list of recommended/tested hardware
- [x] Update QA matrix to include NUC12
- [x] Verify that [BIOS update instructions](https://docs.securedrop.org/en/stable/update_bios.html) are applicable to NUC12

**Comment by nathandyer** [comment]
Just to give an update here, I have acquired a NUC12WSKi5, and began testing this afternoon. 

So far things have not gone smoothly. I'm still trying to troubleshoot, but I'm going to leave a comment here to explain some of my findings so far:

* Out of the box, the ability to boot from USB is disabled. I had to manually enable it in the BIOS by pressing F2, then going to **Boot** -> **Boot Priority** -> **USB**, then ticking the check box and pressing F10 to  save and Exit
* I created an Ubuntu 20.04.5 Server USB disk using the standard method, verifying the checksum to ensure integrity. After doing this and trying to boot by using the F10 Boot Menu, the disk is not recognized as a boot source.
* I tried again with Ubuntu 20.04.5 Desktop on the same USB stick, with the same results (not visible in the boot menu).
* I then tried the USB stick in each of the four USB ports (same results, not presented with boot option).
* I downloaded and flashed Ubuntu 22.04.5 onto the same USB stick, and found that it was detected immediately. After booting, WiFi and Ethernet are both completely functional. 
* I then tried booting a Tails disk I had handy, and found that it booted correctly. Ethernet was detected, but not WiFi (I suspect it was due to the older kernel)
* Going back to testing 20.04.5, I tried disabling SecureBoot, which did not make a difference. I also tried to enable legacy boot, but UEFI is the only supported option and can't be turned off in the BIOS.
* I'm going to pick up another USB disk to try 20.04.5 on that, but the USB drive I have worked with 22.04, so I don't expect the new USB disk to make a difference.

TL;DR: Although Ubuntu 22.04 works just fine, it appears that Ubuntu 20.04.5 (on the same USB disk) is not detected or bootable, despite it being listed as a supported OS on the Intel website. I'm sure I'm overlooking something, so I will try again with a new USB drive tomorrow. If there are other suggestions for things to try, please feel free to send them my way.

**Comment by nathandyer** [comment]
Good news! I was able to get Ubuntu Server 20.04.5 to boot successfully! 

To do so, I had to:
1. Download [the most recent BIOS update](https://www.intel.com/content/www/us/en/download/739909/bios-update-wsadl357.html?wapkw=nuc12wski5)
2. Press F9 in the BIOS to restore optimized defaults (before doing this step, the behavior was the same as before, even with the newer BIOS version)

It's worth noting that USB support was enabled by default on the latest BIOS update after restoring default options, so it's not necessary to call that step out.

I confirmed it would boot whether or not Secure Boot was enabled, and that setting it to boot USB first made no difference in its ability to boot.

On boot, everything appears normal on screen. The built-in network adapter does not seem to be detected, most likely because of the 5.4 kernel. I will continue testing from here, but at least it's booting to 20.04 now!

**Comment by legoktm** [comment]
You could try the Ubuntu HWE kernels? https://ubuntu.com/kernel/lifecycle

Those should come with 5.15, which is what our grsec kernels are also based on.

**Comment by zenmonkeykstop** [comment]
Yup to HWE, even better if we can use it during the install process (I think that's an option in installer's Grub?), otherwise we have to use ethernet adaptors temporarily.

**Comment by nathandyer** [comment]
Good news all around! Using the HWE kernel worked great, and all the hardware seems to be totally operational (including the ethernet). There is an option on boot in GRUB for "Boot and Install with HWE Kernel." I also swapped the SSD from my existing SD install, which has our grsec kernel (5.15), and confirmed everything was operational and working as expected there on this newer hardware.

Will move forward with adding to the documentation, and modifying the QA matrix.

**Comment by legoktm** [comment]
Wheeee. Can you run the the paxtest/spectre-meltdown-checker tests listed on https://developers.securedrop.org/en/latest/kernel.html ? Just to verify we aren't missing any mitigations needed for the newer hardware.

(p.s. if you want to review https://github.com/freedomofpress/securedrop-dev-docs/pull/28 ;-))

**Comment by nathandyer** [comment]
@legoktm Sure thing, will do both! :)

**Comment by nathandyer** [comment]
Happy to report that all results for the `spectre-meltdown-checker` come back as "not vulnerable" on the grsec kernel, and the results of `paxtest` match the results from the NUC11. I think we're OK to proceed with listing the NUC12 as supported.

**Comment by legoktm** [comment]
\o/ Adding NUC 12 to the matrix on #6697 then :)

**Comment by legoktm** [comment]
@nathandyer anything else left to do here or is this complete?

**Comment by nathandyer** [comment]
@legoktm Nope, this is all done! Going to go ahead and close.
