### ISSUE TITLE
December 2022 Linux kernel update

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6697]
We need to do another Linux kernel update. Should be done with coordination in https://github.com/freedomofpress/securedrop-workstation/issues/847.

## Checklist
* [x] Source tarball saved internally
* [ ] Uploaded to apt-test.freedom.press
* [ ] Tested on recommended hardware (see below)
* [ ] Uploaded to apt.freedom.press and released

## Testing matrix
[Instructions on testing procedure](https://developers.securedrop.org/en/latest/kernel.html)

* [x] NUC12 - @nathandyer 
* [x] NUC11 - @legoktm
* [x] NUC10  - @legoktm
* [x] NUC8  
* [ ] NUC7

**Comment by legoktm** [comment]
Targetting 5.15.81, which came out on Friday.

**Comment by nathandyer** [comment]
Happy to report that all is well on the NUC 12. 5.15.81 boots correctly, SecureDrop still functions, and the `paxtest` and `meltdown-checker` results are identical to the previous kernel.

**Comment by zenmonkeykstop** [comment]
NUC8 is also good.
