### ISSUE TITLE
Add pyupgrade to our toolchain

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6699]
## Description

pyupgrade is a tool that automatically rewrites code to use modern syntax. https://github.com/asottile/pyupgrade has a detailed list with examples.

This would be similar to black/isort, in which we'd have a command like `make pyupgrade` that applies all the changes, and then another like `make pyupgrade-check` which verifies there are no unapplied changes. Note that black should always run after pyupgrade changes things.

## User Stories

* As a developer, I want to automatically update Python code to modern patterns/syntax so I don't have to do it manually

**Comment by phershbe** [comment]
@legoktm I can work on this if you'd like. I'm relatively new and don't have professional experience yet but I do open source sometimes and I've worked with `make` and `black` before, for example. Let me know!

**Comment by legoktm** [comment]
Hi @phershbe, thanks for your interest! I want to get input from other team members before we move ahead with this, that will probably take (or not) a week if you don't mind waiting, or I can suggest another task for you to work on now!

**Comment by phershbe** [comment]
@legoktm Yeah, of course, I'm not on any kind of timeline, I'm simply here to help and to practice. Thank you for offering another task ... I'm kind of intimated by a lot of stuff, any other easy tasks off the top of your head? I was looking at https://github.com/freedomofpress/securedrop/issues/6641.

**Comment by legoktm** [comment]
@phershbe: yep, that is (I think!) relatively straightforward (parsing the flask version out of requirements.txt). I'd also suggest #2484 (some code deletion), and #6515 (porting some regex checks to Python/flask).
