### ISSUE TITLE
Create support for theming

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#67]
The securedrop instance that the New Yorker uses is called StrongBox, and other orgs will want their own custom branding too. Right now there's no way to brand your own securedrop without hacking core code, which we should discourage.

This doesn't need to be in 0.1.

**Comment by flamsmark** [comment]
This doesn't seem closed. As a SecureDrop admin, I can only customize a very small number of things on the landing page. I would like to be able to customize many more.
