### ISSUE TITLE
OSSEC sending daily login reports, even if a user hasn't logged in

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop#6748]
## Description

Ever since the 2.5.1 release, OSSEC sends a daily email showing either one or two logins on the app server. After investigation, it appears that this is happening as a result of changes made in [this commit](https://github.com/freedomofpress/securedrop/commit/411946a2f4336e1e18ac88259a9c07ae268df09f) which changes it so that OSSEC checks run as as the `www-data` user.

Because it now sends out these false alarms, the daily login report is less useful as a monitoring tool.

## Steps to Reproduce

This behavior happens automatically once per day, as long as the server is running and OSSEC alerts are set up correctly.

You can see where this happens by inspecting `/var/log/auth.log`. A line will appear, containing:

```
USER=www-data ; COMMAND=/opt/venvs/securedrop-app-code/bin/python3 /var/www/securedrop/manage.py check-disconnected-[db|fs]-submissions
```

followed by:

```
session opened for user www-data by (uid=0)
```

## Expected Behavior

A daily login report is only sent in the event of an actual login by an end-user.

**Comment by legoktm** [comment]
It would be worth checking to see if https://github.com/freedomofpress/securedrop/issues/6705 fixes this, I don't remember if systemd timers trigger the same pam line about a session being opened. Of course the simpler fix would be to adjust the OSSEC rule.

**Comment by zenmonkeykstop** [comment]
It probably would - `sudo` is the culprit here.
