### ISSUE TITLE
building packages should automatically save build log

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6774]
> I do think that if we want to keep publishing build logs long-term it should be automated, e.g. `make build-debs` should also spit out a properly named build log that can be directly committed.

_Originally posted by @legoktm in https://github.com/freedomofpress/securedrop-dev-docs/pull/40#discussion_r1136113719_

* [x] #6787
* [x] freedomofpress/securedrop-client#1789

**Comment by cfm** [comment]
The DX working group discussed the following options today:
1. documenting the use of the `script` command to capture the entire `sd-dvm` build session;
2. wrapping `script` in a do-nothing script; and
3. actually scripting this use of something like `script -c make build-debs`.

(Enough `script` scripting?)  I'll time-box a first pass on this during an extra workday I'll have floating around next week, perhaps even pairing with @legoktm in person.  :-)

**Comment by legoktm** [comment]
I tried using `script` today, overall it was straightforward, the only problem is that it very literally captured all output, including escape sequences and progress things. This means tools like `less` consider it as containing binary:
```
$ less workstation.log 
"workstation.log" may be a binary file.  See it anyway?
``` 
And I can't even upload it as a gist to show you:
```
$ gh gist create workstation.log 
failed to collect files for posting: failed to upload workstation.log: binary file not supported
```

I manually copied + pasted for https://gist.github.com/legoktm/0b589ecb8852727546f998b4c7902dc5 but presumably that lost some binary information?

Compare with the manually copy-paste-out-of-terminal logs: https://github.com/freedomofpress/build-logs/commit/08b5f09f4871253876e92a12f671d00e9df58fe1

**Comment by cfm** [comment]
I find some of the non-custom suggestions in <https://unix.stackexchange.com/questions/14684/removing-control-chars-including-console-codes-colours-from-script-output> reasonable.  But I would understand if we decided this is more trouble than it's worth.

**Comment by cfm** [comment]
@legoktm, running with `TERM=dumb` seems much cleaner, e.g.:

```patch
--- a/Makefile
+++ b/Makefile
@@ -354,7 +354,8 @@ endif
 .PHONY: build-debs
 build-debs: ## Build and test SecureDrop Debian packages
        @echo "Building SecureDrop Debian packages..."
-       @$(SDROOT)/builder/build-debs.sh
+       @export TERM=dumb
+       @script -c $(SDROOT)/builder/build-debs.sh
        @echo
 
 .PHONY: build-debs-notest
```

Then:

```sh-session
user@sd-dev:~/securedrop$ file typescript
typescript: ASCII text, with very long lines, with CRLF, CR, LF line terminators
```

Good enough, do you think?

**Comment by legoktm** [comment]
That is perfect :D

**Comment by cfm** [comment]
I've fleshed this out in #6787 with some templating that we should be able to adapt for `securedrop-builder` if we like it.

**Comment by cfm** [comment]
Closing this here now that we have freedomofpress/securedrop-client#1789.
