### ISSUE TITLE
CircleCI Slack orb fails from forks, causing workflows to error out

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6777]
## Description

After #6739, when CircleCI runs on a branch from a fork, the new Slack orb errors out without `$SLACK_ACCESS_TOKEN`.

## Steps to Reproduce

1. Fork `freedomofpress/securedrop`.
2. Clone your fork and check out a new branch.
3. Commit something on your branch, even if it's just `git commit --allow-empty`.
4. Push your branch to your fork.
5. Open a pull request from your branch into `freedomofpress/securedrop`.

## Expected Behavior

CircleCI runs and passes ~, and the Slack orb posts a notification to `#securedrop-notifications`~.

## Actual Behavior

In each CircleCI job, step `Slack - Sending Notification` errors out and the job fails:

```
In order to use the Slack Orb (v4 +), an OAuth token must be present via the SLACK_ACCESS_TOKEN environment variable.
Follow the setup guide available in the wiki: https://github.com/CircleCI-Public/slack-orb/wiki/Setup

Exited with code exit status 1

CircleCI received exit code 1
```

* Example from a non-maintainer contributor: https://app.circleci.com/pipelines/github/freedomofpress/securedrop/5633/workflows/5e6342a8-914e-4f7b-ad5a-e7e1476b587b/jobs/68126
* Example from a maintainer (yours truly): https://app.circleci.com/pipelines/github/freedomofpress/securedrop/5637/workflows/e9c890de-b5d8-4672-9608-921dc58f2237/jobs/68139

## Comments

#6739 comes from freedomofpress/infrastructure#3225, but we should probably hold off on trying to fix this until we've decided freedomofpress/securedrop-engineering#24.

**Comment by zenmonkeykstop** [comment]
Do we want notifications from forks? That could get noisy.

**Comment by cfm** [comment]
Ah, good point, @zenmonkeykstop.  I've updated the "Expected Behavior"
section: the goal is that CircleCI *passes*, whether or not there's a
notification to Slack.

CircleCI support confirmed this diagnosis for @nabla-c0d3 in
<https://github.com/freedomofpress/securedrop/pull/6764#issuecomment-1497124923>.
