### ISSUE TITLE
development server no longer hot-reloads on file changes

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6784]
## Description

After #6563, `make dev` no longer hot-reloads on file changes, because the immutable `SDConfig` doesn't carry the `env` attribute from `config.py`.  (This regression was last encountered in #5594.)

## Steps to Reproduce

Same as #5594.

## Expected Behavior

Same as #5594.

## Actual Behavior

Same as #5594.

## Comments

The fix in <https://github.com/freedomofpress/securedrop/issues/6669#issuecomment-1526129678> is trivial, but I want to take a moment to see if there's an easy way to test for this regression (fool me once, fool me twice, etc.).

**Comment by uncleSlayer** [comment]
Can I work on this?

**Comment by cfm** [comment]
On Wed, May 10, 2023 at 08:55:40AM -0700, Siddhant Ota wrote:
> Can I work on this?

Sure; thanks your interest!  You'll find the basic fix in
<https://github.com/freedomofpress/securedrop/issues/6669#issuecomment-1526129678>.
The goal here is to find out if we can add a test that checks that "env"
is passed through as expected.  Let us know if you have any questions.

**Comment by uncleSlayer** [comment]
Thanks, I'm new to open source but I'll give me best. I'll let you know if I need anything.

**Comment by uncleSlayer** [comment]
I have applied the patch you mentioned in #6669 and reload works in my machine. But I don't know how to write tests (I don't understand how it is implemented in this repo to be specific). Can you point me to some resources where I can learn? Thanks

**Comment by uncleSlayer** [comment]
> On Wed, May 10, 2023 at 08:55:40AM -0700, Siddhant Ota wrote: Can I work on this?
> Sure; thanks your interest! You'll find the basic fix in <[#6669 (comment)](https://github.com/freedomofpress/securedrop/issues/6669#issuecomment-1526129678)>. The goal here is to find out if we can add a test that checks that "env" is passed through as expected. Let us know if you have any questions.

I have applied the patch you mentioned in https://github.com/freedomofpress/securedrop/issues/6669 and reload works in my machine. But I don't know how to write tests (I don't understand how it is implemented in this repo to be specific). Can you point me to some resources where I can learn? Thanks

**Comment by cfm** [comment]
@uncleSlayer, I'm sorry I left you hanging here.  What we want is a test in [`test_config.py`](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/tests/test_config.py) that checks that the configuration includes the `env` attribute added by the patch to `sdconfig.py`.

Don't feel any pressure to come back to this after so long!  I'll follow up in a week to close this out if we don't hear back from you.
