### ISSUE TITLE
schedule regular run of `remove-pending-sources`

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6788]
## Description

Add a ~cron job~ `systemd` timer for `manage.py remove-pending-sources`.

- [ ] Decide on interval: nightly? weekly?
- [ ] Decide on value (or change default) of `--keep-most-recent`

**Depends on:**
- #6785
- #6705
    - #6780

**Comment by sssoleileraaa** [comment]
[Backlog pruning, 5/15] Confirmed dependency on #6705 and @legoktm mentioned that cleaning the sources table could be helpful once we get to working on the Sequoia migration.

**Comment by cfm** [comment]
Since #6780 installs cleanly, I'll optimistically start implementing this on that precedent, with the goal of having a pull request ready to file as soon as #6780 is merged.
