### ISSUE TITLE
Release securedrop-grsec 5.15.89-2

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6789]
This is the first step in fixing #6762. As described there, we need to push out a version of the securedrop-grsec metapackage that depends on both the current and previous kernel versions before the 2.6.0 release.

Because this is a one-time operation, I've pushed the necessary changes to a separate kernel-builder branch: https://github.com/freedomofpress/kernel-builder/tree/server-hack-6762 - specifically https://github.com/freedomofpress/kernel-builder/commit/79847811a0a4c227442ef234fa6c610e5be01f14. The package is fully reproducible and has been independently rebuild/verified by another SD maintainer.

## Test plan
* [x] Diffoscope with the [current package](https://apt.freedom.press/pool/main/l/linux-upstream/securedrop-grsec_5.15.89-grsec-securedrop-1_amd64.deb), the full diff should be the version number and dependency list:
```
--- securedrop-grsec_5.15.89-grsec-securedrop-1_amd64.deb
+++ securedrop-grsec_5.15.89-grsec-securedrop-2_amd64.deb
├── control.tar.xz
│ ├── control.tar
│ │ ├── file list
│ │ │ @@ -1,3 +1,3 @@
│ │ │  drwxr-xr-x   0 root         (0) root         (0)        0 2011-06-29 20:23:37.000000 ./
│ │ │ --rw-r--r--   0 root         (0) root         (0)      543 2011-06-29 20:23:37.000000 ./control
│ │ │ +-rw-r--r--   0 root         (0) root         (0)      581 2011-06-29 20:23:37.000000 ./control
│ │ │  -rwxr-xr-x   0 root         (0) root         (0)     2029 2011-06-29 20:23:37.000000 ./postinst
│ │ ├── ./control
│ │ │ @@ -1,13 +1,13 @@
│ │ │  Package: securedrop-grsec
│ │ │  Source: linux-upstream
│ │ │ -Version: 5.15.89-grsec-securedrop-1
│ │ │ +Version: 5.15.89-grsec-securedrop-2
│ │ │  Architecture: amd64
│ │ │  Maintainer: SecureDrop Team <securedrop@freedom.press>
│ │ │  Installed-Size: 15
│ │ │ -Depends: linux-image-5.15.89-grsec-securedrop, intel-microcode, paxctld
│ │ │ +Depends: linux-image-5.15.89-grsec-securedrop, linux-image-5.15.81-grsec-securedrop, intel-microcode, paxctld
│ │ │  Section: admin
│ │ │  Priority: optional
│ │ │  Homepage: https://securedrop.org/
│ │ │  Description: Metapackage providing a grsecurity-patched Linux kernel for use
│ │ │   with SecureDrop. Depends on the most recently built patched kernel maintained
│ │ │   by FPF. Package also includes sysctl and PaX flags calls for GRUB.
```
* [ ] Install the package with `sudo unattended-upgrades --debug` (or wait 24h for it to happen automatically), verify that all linux-image- packages are set as auto-installed (run `sudo apt-mark auto 'linux*-securedrop'`), run `sudo apt autoremove`, verify that the 5.15.89 and 5.15.81 packages are not up for removal (you don't actually need to remove them)

## Checklist
* [x] Release to apt-test: https://github.com/freedomofpress/securedrop-apt-test/pull/195
* [ ] Release to apt-prod

**Comment by legoktm** [comment]
(Re-opened since we need to land on apt-prod too :))

Tested on apt-test, installed with unattended-upgrades, force set `apt-mark auto` then:

```
sdadmin@mon:~$ sudo apt autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  linux-image-5.15.26-grsec-securedrop linux-image-5.15.57-grsec-securedrop
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 643 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```

* [x] verify that the 5.15.89 and 5.15.81 packages are not up for removal

**Comment by zenmonkeykstop** [comment]
Stepped through the upgrade on a prod VM:
- [x] unattended-upgrades works, no errors
- [x] 5.15.81-grsec-securedrop was installed.
- [x] post-upgrade, still running 6.15.89-grsec-securedrop
- [x] both are marked as auto and are not `autoremove`d

LGTM for the prod release next available window.
