### ISSUE TITLE
request review by Sequoia team

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6801]
For us to have confidence in our adoption of Sequoia, we should request a code review from the Sequoia team, to confirm that our approach is sound, API usage is correct and stable, etc.

For completeness, this should take place after the implementation of:
* #6799 
* #6800 
* #6802

**Comment by legoktm** [comment]
I sent an [email](https://lists.sequoia-pgp.org/hyperkitty/list/devel@lists.sequoia-pgp.org/thread/DUGVGBDCFI72LDIUZO6AXRPQGZA6YWGB/) to the Sequoia dev mailing list yesterday asking for the review and it's in progress!
