### ISSUE TITLE
Verify that new Focal securedrop-keyring package contains the updated 2024-expiry key.

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop#6805]
The securedrop-keyring package is built and released with the other SecureDrop server packages. As part of server release testing, the key should be checked to verify that it has been updated and that `apt` operations work without errors.

**Comment by zenmonkeykstop** [comment]
This probably does *not* need to be blocked by the release itself on sober reflection - checking the package built via `make build-debs` on current develop should do it.

**Comment by zenmonkeykstop** [comment]
Built and unpacked the securedrop-keyring package from `develop`, confirmed that the expiry date is `2024-07-08`.
