### ISSUE TITLE
Dependency alerts are configured using RustSec/cargo audit

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6815]
We should get notifications for security issues in Rust dependencies using the https://rustsec.org/ database and their cargo-audit tool.

Presumably this should be done using the same infrastructure/setup that our current Python alerts use.

**Comment by zenmonkeykstop** [comment]
Added a Makefile target and some CI bits for a minimal version of this - I'd hold off on anything more substantial until we see how https://github.com/aquasecurity/trivy or similar shakes out.
