### ISSUE TITLE
consider moving `staging-test-with-rebase` to bare-metal hosts

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6838]
## Description

@legoktm has pointed out that with a few tweaks <https://github.com/cfm/terraform-metal-securedrop-staging> could be used to run `staging-test-with-rebase` either (a) on VMs on bare-metal hosts or (b) directly on bare-metal hosts, rather than via nested virtualization as we currently do.

## Pros

- Simpler CI
- `staging-test-with-rebase` more faithful to hardware environments

## Cons

- More-expensive CI

**Comment by legoktm** [comment]
I'd be interested to know whether we expect this to be faster (bare metal!) or slower (provisioning takes longer or constrained by e.g. Tor)

The other part that was appealing about this is that it supported the Tails environment, which would be nice to also have end-to-end testing for.

**Comment by cfm** [comment]
`staging-test-with-rebase` likes to take ~43 minutes at Google Cloud.

At Equinix Metal:

* 2 minutes for provisioning:
    ```sh-session
    user@sd-dev:~/terraform-metal-securedrop-staging$ time terraform apply -auto-approve
    [...]
    Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

    Outputs:
    ip_address = "139.178.94.47"

    real    1m46.064s
    user    0m0.402s
    sys    0m0.082s
    ```
* 22 minutes for `make staging`:
    ```sh-session
    Jun 08 18:37:59 sd-staging systemd[1]: Starting Initial cloud-init job (metadata service crawler)...
    [...]
    Jun 08 18:59:32 sd-staging cloud-init[1286]:     PLAY RECAP *********************************************************************
    Jun 08 18:59:32 sd-staging cloud-init[1286]:     app-staging                : ok=156  changed=92   unreachable=0    failed=0    skipped=36   rescued=0    ignored=0
    Jun 08 18:59:32 sd-staging cloud-init[1286]:     localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
    Jun 08 18:59:32 sd-staging cloud-init[1286]:     mon-staging                : ok=136  changed=80   unreachable=0    failed=0    skipped=29   rescued=0    ignored=0
    ```
* < 1 minute for `make testinfra`:
    ```sh-session
    root@sd-staging:~/securedrop# make testinfra
    [...]
        ====== 477 passed, 13 skipped, 3 xfailed, 1 xpassed, 3 warnings in 48.65s ======
    ```

So potentially almost 50% time savings.

*But*—not to oversell it—this is all we're doing to set up Tails:

https://github.com/cfm/terraform-metal-securedrop-staging/blob/4daac60acbda4da20b5019b04d6153d6587307fd/user_data.sh#L80-L96

I haven't dared try to automate anything *inside* Tails.
