### ISSUE TITLE
Update cryptography to 41.0.0

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6856]
Cryptography is throwing safety alerts, best to update it.

**Comment by legoktm** [comment]
https://github.com/advisories/GHSA-5cpq-8wj7-hf2v is the issue in question.

> pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.5-40.0.2 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://www.openssl.org/news/secadv/20230530.txt.
>
> If you are building cryptography source ("sdist") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.

So this only affects dev environments and not prod instances since we build cryptography ourselves and don't statically link against OpenSSL.
