### ISSUE TITLE
[2.6.0] Journalist Interface: Redis raises `NameError: name 'hasattr' is not defined`

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6866]
## Description

On the Application Server, `/var/log/apache2/journalist-error.log` shows:

```
Exception ignored in: <function Redis.__del__ at 0x7632d5ee5dc0>
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/redis/client.py", line 1216, in __del__
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/redis/client.py", line 1222, in close
NameError: name 'hasattr' is not defined
Exception ignored in: <function Redis.__del__ at 0x7632d5eeadc0>
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/redis/client.py", line 1216, in __del__
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/redis/client.py", line 1222, in close
NameError: name 'hasattr' is not defined
```

The application itself is not obviously broken.

## Steps to Reproduce

On the Application Server:

- Install `securedrop-app-code` `2.6.0-rc2`
- `systemctl restart apache2`

## Expected Behavior

No errors.

## Actual Behavior

As above.

## Comments

Things to investigate:

- [x] What codepath is getting us here?
    * https://github.com/freedomofpress/securedrop/issues/6866#issuecomment-1599794640
- [x] Why haven't I been getting these level-2 OSSEC alerts (when I have been getting other OSSEC alerts from this instance as usual)?
    * Hypothesis: swallowed in post-installation alert storm, until...
    * https://github.com/freedomofpress/securedrop/issues/6866#issuecomment-1601142791

**Comment by cfm** [comment]
First appeared on this Application Server on Thursday after upgrading to `2.6.0-rc1`:

```
root@mon:/var/ossec/logs/alerts/2023/Jun# zgrep -B2 "NameError" *                                                                                     
ossec-alerts-16.log.gz-2023 Jun 16 00:00:15 (app) 10.20.2.2->/var/log/apache2/journalist-error.log                                                    
ossec-alerts-16.log.gz-Rule: 1002 (level 2) -> 'Unknown problem somewhere in the system.'                                                             
ossec-alerts-16.log.gz:NameError: name 'hasattr' is not defined 
[...]
```

**Comment by cfm** [comment]
Hypothesis:  After #6783, this is a red herring caused by (a) [cleaning up Redis connections](https://github.com/redis/redis-py/blob/2bb7f102f6b6724f5d5d9f2cdb187226ab5d2167/redis/client.py#L1226-L1234) (b) [during mod_wsgi teardown](https://stackoverflow.com/a/44940341).

**Comment by legoktm** [comment]
Agreed that it seems like a red herring based on b). `hasattr` is a built-in that will always be present.

**Comment by zenmonkeykstop** [comment]
Haven't managed to repro this during an upgrade from 2.5.2 to 2.6.0-rc2 on VMs/

**Comment by legoktm** [comment]
@cfm noted this was producing OSSEC alerts that should be suppressed, which I can confirm:

```


OSSEC HIDS Notification.
2023 Jun 21 03:07:41

Received From: (app) 10.20.2.2->/var/log/apache2/journalist-error.log
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

NameError: name 'hasattr' is not defined



 --END OF NOTIFICATION
```

**Comment by cfm** [comment]
...so, while the `NameError` itself is a red herring, I'll prepare a `local_rules.xml` addition to suppress the OSSEC alert it generates.
