### ISSUE TITLE
`i18n` branches and/or repository should run full CI workflow

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6876]
## Description

In #6873 ([specifically](https://app.circleci.com/pipelines/github/freedomofpress/securedrop/5958/workflows/3b8714d7-6108-4ada-9ac7-a52718a2e239/jobs/69875/tests)), we discovered the possibility of rare but obstructive partitions between the tooling that pushes to `securedrop-i18n` and the tests that run in `securedrop`.  From the smallest to the largest possible solution to this problem:

1. `securedrop@i18n-*` branches should run the full CI workflow _in addition to_ the translation test suite.
2. The `securedrop-i18n` repository itself should run full CI, including the translation test suite.
3. After freedomofpress/securedrop-engineering#30, pull requests from Weblate into `securedrop` will run the full CI workflow like any other.

## User Stories

As a maintainer, I want as few surprises as possible, especially on release day.

**Comment by legoktm** [comment]
I think we should adopt 1) as a general policy - any commit slated to be merged into develop or a release branch must pass the full CI suite. I'm not really a fan of having special branch names trigger special jobs, ideally all tests should run always - are the translation tests too slow to run for every PR?

And of course we should do 3) too. :)
