### ISSUE TITLE
evaluate Polish (`pl`) for language support

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6880]
## Description

[Polish (`pl`)](https://weblate.securedrop.org/projects/securedrop/securedrop/pl/#information) reached 100% translation coverage for v2.6.0 but has only 1% review coverage.  If it maintains and reaches 100% translation and review coverage, respectively, for v2.7.0, we can grant support for it per the [policy on supported languages](https://developers.securedrop.org/en/latest/supported_languages.html).

**Comment by huertanix** [comment]
Related Q: If I know Polish speakers/readers who would be down to volunteer for review, should I point them to Localization Lab?

**Comment by cfm** [comment]
@huertanix, yes: Localization Lab is the primary point of contact for both translators and [reviewers](https://developers.securedrop.org/en/latest/translations.html#how-to-become-a-reviewer).  Thank you!

**Comment by cfm** [comment]
Polish still has only 1% review coverage as of `2.7.0-rc3`, so it is not eligible for support in v2.7.  We can reopen this ticket if and when it becomes eligible.
