### ISSUE TITLE
July 2023 Linux kernel update

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6887]
Being done with coordination in https://github.com/freedomofpress/securedrop-workstation/issues/907.

## Checklist
* [x] Source tarball saved internally
* [x] Uploaded to apt-test.freedom.press
* [ ] Tested on recommended hardware (see below)
* [ ] Uploaded to apt.freedom.press and released

## Testing matrix
[Instructions on testing procedure](https://developers.securedrop.org/en/latest/kernel.html)

To update to the new kernel, please use `sudo apt-get update && sudo unattended-upgrades -d` (not `sudo apt-get upgrade`) OR wait 24h for the automatic update to happen.

* [x] NUC12 :  
* [x] NUC11:
* [x] NUC10:
* [ ] NUC8:
* [x] NUC7:

**Comment by nathandyer** [comment]
Testing on NUC12:
- [x] `uname -r`: `5.15.120-1-grsec-securedrop`
- [x] `sudo paxtest blackhat`: Consistent results before and after kernel upgrade. "Return to function (memcpy)" is listed vulnerable (before and after), all others are not vulnerable/denied resources.
- [x] `spectre-meltdown-checker`: `Not vulnerable` across the board

Looks great to me!
