### ISSUE TITLE
revise all internationalization- and localization-related documentation for continuous localization

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6916]
- [x] ~Revisit `.mo` compilation; reconcile team decision with `securedrop-client`~ → Assume `.mo` compilation will from Weblate to `make compile-translations`
- [x] Revisit pre-commit hook; reconcile team decision with `securedrop-client` → freedomofpress/securedrop-client#1673

**Comment by zenmonkeykstop** [comment]
Blocked on final implementation of continuous l10n workflow.
