### ISSUE TITLE
streamline functions currently provided by `i18n_tool.py`

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6917]
- [x] Adapt `securedrop-client`'s `make extract-strings` target
    - Can this be generalized in `securedrop-tooling`?
    - Does this let us combine the `securedrop/{securedrop,desktop}` Weblate components?  (This might violate the "No side effects" constraint.)
- [x] Enforce in CI (`make check-strings`)
    - Can this be generalized in `securedrop-tooling`?
- Per <https://github.com/freedomofpress/securedrop-engineering/pull/30#issuecomment-1633171470>:
    - [x] Reimplement "Compile `.po` catalogs → `.mo` machine objects" as `make compile-translations`
- ~`make update-docs` → https://github.com/freedomofpress/securedrop-docs/blob/main/docs/includes/l10n.txt~
    - Counterpoint: https://github.com/freedomofpress/securedrop/issues/6917#issuecomment-1689091116 
    - freedomofpress/securedrop-docs#503
- ~~freedomofpress/securedrop-client#1280~~
    - Counterpoint: https://github.com/freedomofpress/securedrop/issues/6917#issuecomment-1690762840

**Comment by cfm** [comment]
The `{check,extract}-strings` targets are available in `6917-c10s-l10n` as of 63be596914b09a75acf3d58955c9b44bd8dc7c4b, which is failing CI in `lint` as intended.  Remaining `i18n_tool.py` invocations to replace next week:

```sh-session
(.venv) user@sd-dev:~/securedrop$ grep -R "i18n_tool.py" * | grep -Ev "^changelog.md:"
Makefile:	@echo "SUPPORTED_LOCALES = $$(if test -f /opt/venvs/securedrop-app-code/bin/python3; then ./securedrop/i18n_tool.py list-locales --python; else DOCKER_BUILD_VERBOSE=false $(DEVSHELL) ./i18n_tool.py list-locales --python; fi)" | sed 's/\r//' >> securedrop/config.py
Makefile:	@$(DEVSHELL) $(SDROOT)/securedrop/i18n_tool.py list-translators
Makefile:	@$(DEVSHELL) $(SDROOT)/securedrop/i18n_tool.py list-translators --all
securedrop/debian/translations.sh:/tmp/securedrop-app-code-i18n-ve/bin/python3 ./i18n_tool.py --verbose translate-messages --compile
securedrop/bin/translation-test:./i18n_tool.py translate-messages --compile
securedrop/bin/translation-test:SUPPORTED_LOCALES=$(./i18n_tool.py list-locales)
securedrop/bin/generate-docs-screenshots:./i18n_tool.py translate-messages --compile
securedrop/bin/dev-deps:    ./i18n_tool.py translate-messages --compile
```

**Comment by cfm** [comment]
<https://github.com/freedomofpress/securedrop/issues/6917#issue-1850462680>:

> * [ ]  `make update-docs` → https://github.com/freedomofpress/securedrop-docs/blob/main/docs/includes/l10n.txt

This has always had a bit of smell to me.  I think it's the only place outside of packaging where we let a Make target in one repository read or write a file in another.  Even though there's a `--docs-repo-dir`, I've only ever been able to use (e.g.) `/home/user/securedrop/securedrop-docs` to get Docker to play nicely with permissions and Git roots.

Since our goal here is to automate as much of this process as possible, rather than reimplement this particular step literally, I propose to do one of the following instead, from least to most effort:

1. Replace the [`include` directive in `install.rst`](https://github.com/freedomofpress/securedrop-docs/blob/0588a478d9f425edea9bf29968b7af2bc31f884e/docs/admin/installation/install.rst?plain=1#L37-L43) with a link to [`i18n.json`](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/i18n.json).
2. Add a Make target that writes `i18n.json` to either `i18n.md` or `i18n.rst` in this repository.  Then replace the `include` directive in `install.rst` with a link to that file, which GitHub will render.  Enforce this in CI, as `make check-strings` enforces `make extract-strings`.
3. Add a Make target in `securedrop-docs` that fetches `i18n.json` and writes it to the `l10n.txt` expected by the `include` directive in `install.rst`.  Use this in CI.

**Comment by legoktm** [comment]
You have some stuff checked off in the above list, am I correct in assuming that's just a personal list you're using, i.e. those things haven't been fixed in `develop` yet nor a PR?

**Comment by cfm** [comment]
Yes, exactly, @legoktm: this checklist tracks the work in progress in `i18n-6917-c10s-l10n`.

**Comment by cfm** [comment]
<https://github.com/freedomofpress/securedrop/issues/6917#issue-1850462680>:

> * [ ]  [replicate `i18n_tool.py list-translators` in continuous-localization workflow securedrop-client#1280](https://github.com/freedomofpress/securedrop-client/issues/1280)

Hot take: we shouldn't do this either.  I've proposed this in <https://github.com/freedomofpress/securedrop-client/issues/1280#issuecomment-1690749088> and presumptively documented it in freedomofpress/securedrop-dev-docs@f91a4d30b5436c2fad653e4666dc2e38b328d337.

**Comment by cfm** [comment]
Barring any objections to the reductions of scope I've proposed in <https://github.com/freedomofpress/securedrop/issues/6917#issuecomment-1689091116> and <https://github.com/freedomofpress/securedrop/issues/6917#issuecomment-1690762840>, here's what's left here:
1. [x] <https://github.com/freedomofpress/securedrop/blob/96ef2ef85ddb5b2bdb69453014ce8b5745ae6532/.circleci/config.yml#L225> invokes `i18n_tool.py` and needs to use `make supported-locales` instead, which means I need to factor out <https://github.com/freedomofpress/securedrop/blob/38655dec9c51f90206ea7aebdb751a2d1012fd7d/securedrop/bin/translation-test#L20> to take a separator.
2. [x] There are also some tests (_outside_ of the now-gone `test_i18n_tool.py`) that rely on `i18n_tool.py` and will need to use either `pybabel` or precompiled test fixtures instead.
3. [x] As we relearned in #6712, the `securedrop/desktop` component is indeed unavoidable, because the Tails environment doesn't have `gettext`, `pybabel`, &c. available.  Based on my findings just now in <https://github.com/freedomofpress/securedrop-client/issues/1507#issuecomment-1692381661>, we *can* have Weblate generate `.mo` files for this component and verify them in CI, without needing to keep tooling around to update them manually.
4. That will get us to the point of having a draft pull request, which we'll need to test (prior to formal review) in `securedrop-i18n-sandbox` against `weblate-sandbox` per #6232.
