### ISSUE TITLE
support Debian bookworm-based Tails

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6942]
## Description

Tails 6.0 will be based on Debian bookworm: https://gitlab.tails.boum.org/groups/tails/-/milestones/118 - when this happens it'll also include a switch to Python 3.11 and a new GNOME version, so we'll need to add code to rebuild the virtualenv and make sure our dependencies are all compatible or update them and test the extension stuff.

And then handle support docs + comms.

**Comment by legoktm** [comment]
@zenmonkeykstop notes that we could do testing with vanilla bookworm and set up CI (against `debian:bookworm`) ahead of time.

**Comment by zenmonkeykstop** [comment]
This was completed with #7121
