### ISSUE TITLE
October kernel update

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6966]
## Checklist
* [x] Source tarball saved internally ([instructions](https://wiki.freedom.press/wiki/Responding_to_source_requests_for_SecureDrop_kernels#How_to_upload_SecureDrop_kernel_tarballs))
* [x] Logs and build info uploaded to `build-logs`
* [x] server and workstation kernels uploaded to `apt-test.freedom.press` - see https://github.com/freedomofpress/securedrop-apt-test/pull/204
* [x] Tested on recommended hardware (see below)
* [x] Uploaded to `apt.freedom.press` and released

## Testing matrix
[Instructions on testing procedure](https://developers.securedrop.org/en/latest/kernel.html)
Make sure you're using the latest version of the spectre-meltdown-checker.

### Server: 
To update to the new kernel, please use `sudo apt-get update && sudo unattended-upgrades -d` (not `sudo apt-get upgrade`) OR wait 24h for the automatic update to happen.

### Workstation:
To update to the new kernel, run updater on a staging build.

### H/W testing:

* [x] VMs: @zenmonkeykstop 
* [x] NUC12: @nathandyer 
* [x] NUC11: @legoktm
* [x] NUC10: @legoktm
* [x] NUC8: @zenmonkeykstop 
* [ ] ~NUC7:~
* [x] Workstation: @zenmonkeykstop

**Comment by zenmonkeykstop** [comment]
Currently blocked on failing kernel builds, see https://github.com/freedomofpress/kernel-builder/issues/40

**Comment by zenmonkeykstop** [comment]
Unblocked again by new grsecurity patch. Ready for apt-test and hardware testing.

**Comment by legoktm** [comment]
NUC11 is ✔️ , NUC10 is also good, just noting that I ran into the same checker false positive as last time: https://github.com/freedomofpress/securedrop/issues/6938#issuecomment-1716625204.

**Comment by nathandyer** [comment]
NUC12 is also  ✔️

* [x] `uname -r`: 5.15.135-1-grsec-securedrop
* [x] `sudo paxtest blackhat` output OK
* [x] `spectre-meltdown-checker` output OK
* [x] Basic smoke tests
