### ISSUE TITLE
Consider using CertParser instead of Cert::from_str

### ISSUE THREAD

**Issue by nwalfield** [freedomofpress/securedrop#6986]
https://github.com/freedomofpress/securedrop/blob/8d00ba5d9d3835a22a09bcd3a338b65aee697e7d/redwood/src/lib.rs#L103-L105

`Cert::from_str` is a wrapper around [`Cert::from_bytes`](https://docs.sequoia-pgp.org/sequoia_openpgp/parse/trait.Parse.html#method.from_bytes), which returns the first certificate and silently ignores anything else.  If this function should fail if handed a keyring, then you should instead use [`CertParser`](https://docs.sequoia-pgp.org/sequoia_openpgp/cert/struct.CertParser.html).

**Comment by nwalfield** [comment]
The same applies [here](https://github.com/freedomofpress/securedrop/blob/develop/redwood/src/lib.rs#L151):

https://github.com/freedomofpress/securedrop/blob/8d00ba5d9d3835a22a09bcd3a338b65aee697e7d/redwood/src/lib.rs#L151

**Comment by legoktm** [comment]
@nwalfield in my testing `Cert::from_str` fails on keyrings (which, correct, we do want to fail):

I ran `/usr/bin/gpg --export --armor freedom.press > fpf.asc`, then used `sq inspect` to verify its an OpenPGP keyring with multiple keys ([see output](https://gist.github.com/legoktm/1bb18a7e9b815fe42d5fab60496bdba2)). Then when I use `Cert::from_str()` against that I get "Malformed Cert: Additional packets found, is this a keyring?".

Am I missing something?

**Comment by nwalfield** [comment]
You're right.  The documentation was misleading.  I've [improve it](https://gitlab.com/sequoia-pgp/sequoia/-/merge_requests/1566).
