### ISSUE TITLE
Consider using File::create_new

### ISSUE THREAD

**Issue by nwalfield** [freedomofpress/securedrop#6989]
As is, the following code will truncate an existing file.  I can't tell if this is reasonable, but you may consider using [`File::create_new`](https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.create_new) instead, which throws an error if the file already exists.

https://github.com/freedomofpress/securedrop/blob/8d00ba5d9d3835a22a09bcd3a338b65aee697e7d/redwood/src/lib.rs#L160

**Comment by legoktm** [comment]
Unfortunately `File::create_new` is unstable, but we can do it directly with OpenOptions.

**Comment by nwalfield** [comment]
> Unfortunately `File::create_new` is unstable, but we can do it directly with OpenOptions.

Good point.  I now remember encountering the same problem, and using `OpenOptions` instead.
