### ISSUE TITLE
`update_version.sh` should update `.pot` files too

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#7020]
## Description

Our `messages.pot` files have a `Project-Id-Version` header that is not updated by `update_version.sh`.  (E.g.: #7018.)  Options:

1. ***Don't* version them.**  Have `make extract-strings` `sed` `Project-Version-Id` out of these files, as we do for `POT-Creation-Date` for reproducibility.
2. **Let `update_version.sh` update them directly** as it does other files, via `sed`.
3. **Have `update_version.sh` call `make extract-strings`** to propagate the new version, perhaps erroring out if `make check-strings` indicates that they're not otherwise current.  (We don't want to include actual string changes with the version change.)
    * This requires that the virtual environment be active.
4. **Have `update_version.sh` tell the user** to run `make extract-strings` and amend the commit if necessary.

## How will this impact [SecureDrop users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?

No user impact.

## How would this affect SecureDrop's [threat model](https://docs.securedrop.org/en/stable/threat_model/threat_model.html)?

No security implications.

## User Stories
As a release manager, I don't want to have to remember to run `make extract-strings` after `update_version.sh`.

**Comment by legoktm** [comment]
Is the version useful for anything in these files? If not, No. 1 seems like the best option.
