### ISSUE TITLE
SecureDrop 2.7.0 - Enable SSH over TOR -> no - Not working anymore

### ISSUE THREAD

**Issue by raphael-nis** [freedomofpress/securedrop#7075]
## Description

Installation fails with set option "Enable SSH over TOR = no"

## Steps to Reproduce

Try to install securedrop 2.7.0 with set sdconfig parameter "Enable SSH over TOR = no"

## Actual Behavior

Error Message:
Task [restrict-direct-access] : Copy IPv4 iptables rules
fatal: [app]: FAILED! msg: “Destination directory /etc/iptables does not exist”
fatal: [mon]: FAILED! msg: “Destination directory /etc/iptables does not exist”

## Comments

We need a working workaround for this bug.

**Comment by nathandyer** [comment]
Hello @raphael-nis,

I'm sorry you're running into this issue during installation! I posted a reply to your support request on the SecureDrop forum, which [you can find here.](https://forum.securedrop.org/t/securedrop-2-7-0-restrict-direct-access-copy-ipv4-iptables-rules-failed/1558)

Please take a look there, and if you're still running into these errors, let us know and we can assist through our [support portal](https://support.freedom.press/account/register).

Thank you!
