### ISSUE TITLE
February 2024 Linux kernel update

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#7113]
Being done with coordination in https://github.com/freedomofpress/securedrop-workstation/issues/950.

## Checklist
* [x] Source tarball saved internally
* [x] Uploaded to apt-test.freedom.press
* [x] Tested on recommended hardware (see below)
* [ ] Uploaded to apt.freedom.press and released

## Testing matrix
[Instructions on testing procedure](https://developers.securedrop.org/en/latest/kernel.html)

To update to the new kernel, please use `sudo apt-get update && sudo unattended-upgrades -d` (not `sudo apt-get upgrade`) OR wait 24h for the automatic update to happen.

* [x] NUC13
* [x] NUC12:
* [x] NUC11:
* [x] NUC10:
* [x] NUC8:
* [ ] NUC7:

**Comment by zenmonkeykstop** [comment]
Tested on Nuc8 and Nuc13 (soon to be added to reccos) as part of 2.8.0 QA. No problems so far.

**Comment by legoktm** [comment]
✔️  on NUC10 and NUC11.

**Comment by legoktm** [comment]
Pushed to production
