### ISSUE TITLE
make dev-tor: persist onion addresses

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop#7115]
## Description

`make dev-tor` spins up the servers in containers with onion addresses. However, these are non-persistent, meaning that each time they are ran, a new address will be generated. For Workstation development, having stable onion addresses is key. Otherwise one would need to reprovision the workstation every time they change.

Ensuring that `make dev-tor` makes the secrets persistent, would help development.

## How will this impact [SecureDrop users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?
No impact. Dev quality of life impact only.

## How would this affect SecureDrop's [threat model](https://docs.securedrop.org/en/stable/threat_model/threat_model.html)?
Does not. Dev-facing.

## User Stories

As an SDW developer, I want to spin up SD servers with persistent onion addresses quickly without provisioning physical machines of VMs with the servers.

**Comment by zenmonkeykstop** [comment]
Two :+1: from me, would definitely reduce barrier to entry for SDW development.
