### ISSUE TITLE
 Update the release pubkey to version with expiry date of 2027-07-08

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#7162]
(Cloned from freedomofpress/securedrop#6794 )

The securedrop release key expiry needs to be bumped before 2024-07-07. In order to reduce maintenance burden (and punt on a policy change to update the release key with new major versions instead), the key expiry will be set for T+3 years.

The pubkey is used in the following areas:

- verifying apt repo Release signatures (via the usual Ubuntu and Debian apt tools in servers and the Qubes Debian sd-* VMs)
- verifying git tags for Tails code updates (via gpg and git in the CLI and GUI updaters)
- verifying RPM package signatures (via dnf on Qubes dom0 and sys-firewall VMs)
- verifying updates to the HTTPSEverywhere onion names channel (in Tor Browser)

Note that:
- no HTTPSEverywhere logic needs to change, as the PEM-format key used there doesn't include an expiry date 
- packages or Release files should not need to be re-signed, as the private key is not being rotated.
- external documentation updates should not be necessary as the key fingerprint doesn't change and documentation referencing the pubkey doesn't mention the expiry date.
- Qubes 4.1 EOL is July 30 and non-hotfix SDW development against  4.1 has ended. One option to reduce overhead would be to skip updating the key for the 4.1 version  of SDW and require that pilot participants update to 4.2 once available. If some users remain on 4.1 and an urgent fix is required, this would mean that the fix could only be applied by moving to 4.2. 
 
Proposed tasks to update the pubkey for the areas above are summarized below:

# To complete (ASAP / before 2024-07-07) 

## server
- [x] Generate new pubkey with updated 2027 expiry date and distribute to maintainers for verification
- [x] freedomofpress/securedrop#7164
- [x] Verify that the new package contains the updated key
- [x] #7168

## workstation (4.2/bookworm)
- [x] freedomofpress/securedrop-client#2035
- [x] freedomofpress/securedrop-workstation#1045
- [ ] release bookworm securedrop-keyring package (initial 4.2 prod release should include new key)
- [ ] release securedrop-workstation-dom0-config 1.0.0 (initial 4.2 prod release should include new key)

## workstation (4.1/bullseye) - optional?
- [x] release bullseye securedrop-keyring package as hotfix against 0.10.1
- [x] release securedrop-workstation-dom0-config as hotfix against 0.11.0
- [x] explicitly skip 4.1 base template update (no new 4.1 installs supported past 2024 key expiry)

# misc
- [x] Update on keys.openpgp.org
- [x] Update on securedrop.org

**Comment by legoktm** [comment]
This was done in https://securedrop.org/news/securedrop-2_9_0-released/.
