### ISSUE TITLE
Make dev-tor fails: tor tries to change ulimit which is not permited

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop#7174]
## Description

`make dev-tor` is failing for me on develop (as of 59be919d) due to ulimit issues:

```
Setting up Tor...
HiddenServiceDir /var/lib/tor/services/source/
HiddenServicePort 80 127.0.0.1:8080
HiddenServiceDir /var/lib/tor/services/journalist/
HiddenServicePort 80 127.0.0.1:8081
/etc/init.d/tor: line 140: ulimit: open files: cannot modify limit: Operation not permitted
```

## Steps to Reproduce

```
git clone https://github.com/freedomofpress/securedrop/
make dev-tor
```

## Expected Behavior

`make dev-tor` to start the servers without issues.

## Actual Behavior

fails with the message

```
Setting up Tor...
HiddenServiceDir /var/lib/tor/services/source/
HiddenServicePort 80 127.0.0.1:8080
HiddenServiceDir /var/lib/tor/services/journalist/
HiddenServicePort 80 127.0.0.1:8081
/etc/init.d/tor: line 140: ulimit: open files: cannot modify limit: Operation not permitted
 * Starting tor daemon...                                                                                                                                                          [ OK ] 
-----BEGIN PRIVATE KEY-----
XXXXXXXXXXXXXXXXXXXXXXX
-----END PRIVATE KEY-----
tee: /var/lib/tor/services/journalist/authorized_clients/client.auth: No such file or directory
descriptor:x25519:XXXXXXXXXXXXXXXXXXXXXXX
make: *** [Makefile:256: dev-tor] Error 1
```

## Comments

Suggestions to fix, any other relevant information.

**Comment by legoktm** [comment]
I don't think anything has changed on the tor package side (the Ubuntu focal package hasn't changed since 2020), so this must be something on the host side. How are you invoking it? Bookworm in Qubes?

**Comment by zenmonkeykstop** [comment]
- debian-11 based VM: can't repro 
- debian-12-xfce based VM: can't repro

Weirdly enough, first two attempts to run `ulimit -n <N>` in the container succeed, but after running `ulimit -a` for the first time, all other `ulimit -n` attempts fail with the given error.

**Comment by deeplow** [comment]
Oh, never mind. My bad. I was actually on fedora 40 :/, not using my main device and I though this sd-dev qube was debian... I'll close this one as it doesn't really matter for us and that must be the problem. Sorry about that.
