### ISSUE TITLE
Allow organizations to add a custom reply template

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#718]
We should add support for custom reply templates to the Document Interface. A journalist can for example send an initial reply to a source before even looking at the documents telling the source the documents have been received.

**Comment by redshiftzero** [comment]
Seems like this would be nice as two features: 
1) Administrators / the "point person" can add a SD-wide default response that appears in all journalists accounts as a template reply. 
2) Individual journalists can add their own reply template(s) that will only appear in their accounts.

**Comment by eloquence** [comment]
We are still interested in this; however, it appears that tlsdate is unmaintained (last commit 2015). We'd want to use a maintained fork or another option. Adding to "Some Day" milestone until we have an agreed upon implementation strategy, and retitling.

**Comment by eloquence** [comment]
We discussed this issue in our old issue review yesterday and I also brought it to the attention of @huertanix today. While we will want to continue to improve source/journalist interaction, custom reply templates as specified here are not something that's been raised as important by newsrooms so far, and so we're not currently intending to implement this feature. Closing for now.

**Comment by dachary** [comment]
@runasand feel free to re-open at any time if you still think this is important ;-)
