### ISSUE TITLE
Nightly CircleCI staging-test-with-rebase jobs are failing

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#7195]
@mig5 tracked down the underlying issue to reliance on a Docker feature that has been deprecated. As a quick fix we can re-enable it. Long-term we should update the job to work with the latest version of the `gcloud-sdk` image. Longer-term we could move this job elsewhere altogether - either to another platform with support for nested virtualization or to a bare metal provider ala https://github.com/cfm/terraform-metal-securedrop-staging

**Comment by zenmonkeykstop** [comment]
With the docker fix in place, nightlies are still failing due to an apparmor deny:

```
Jun 28 18:59:44 app-staging kernel: [  306.920508] audit: type=1400 audit(1719601184.466:63): apparmor="DENIED" opera...pro_esm_cache//dpkg" name="/var/lib/dpkg/arch" pid=64033 comm="dpkg" requested_mask="r" denied_mask="r" fsuid=0 ouid=0'
```

Looks like this is an upstream known issue: https://github.com/canonical/ubuntu-pro-client/issues/3137- the fix was backported to Focal and made available over the weekend!

**Comment by legoktm** [comment]
We didn't fix this long-term yet, which https://github.com/freedomofpress/securedrop/pull/7215 will do.
