### ISSUE TITLE
`securedrop-admin update` returns indistinguishable error messages for distinct error conditions

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#7200]
## Description

`securedrop-admin update` returns the same error message `Signature verification failed.` for multiple distinct error conditions.  It's therefore necessary to step through the logic of the `update()` function to identify the cause of the error.

https://github.com/freedomofpress/securedrop/blob/f5ca29b6a279cc7d681ab6d7f08c98cedce2c8bd/admin/securedrop_admin/__init__.py#L1078-L1095

## Steps to Reproduce

Discovered in the course of #7168.

## Expected Behavior

Error messages either (a) are self-explanatory or (b) can be traced to a unique point in the code.

## Actual Behavior

Neither.

## Comments

It would be interesting to run a search for duplicated logging and exception strings across the codebase and see if this is a problem elsewhere.

**Comment by xavierlwr** [comment]
interested, will look into this

**Comment by rudradeep22** [comment]
If no one is working on this, can I take this up?

**Comment by legoktm** [comment]
Hey @rudradeep22, you're welcome to. If you have any questions or need help feel free to join our [Matrix room](https://gitter.im/freedomofpress/securedrop).
