### ISSUE TITLE
Offer alternatives to diceware for source codename

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#721]
This may help with memorability, especially for non-native-english speakers. Some alternative "dictionaries":
- diceware-like dictionary in other languages
- emoji
- 4 or 5 wikipedia article titles

**Comment by garrettr** [comment]
Can't tell if the emoji suggestion is serious... :shipit:

**Comment by flamsmark** [comment]
Emoji are rather difficult to type.

**Comment by redshiftzero** [comment]
Closing this in favor of #999.
