### ISSUE TITLE
Test with Tor Browser 14 / Firefox 128 ESR

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#7229]
## Description

Tor Browser 14 is currently going through alpha testing right now: https://blog.torproject.org/new-alpha-release-tor-browser-140a1/

This brings in Firefox ESR 128 (from 115), we should test that basic SI and JI functionality works correctly.

Previously: https://github.com/freedomofpress/securedrop/issues/6956.

**Comment by nathandyer** [comment]
Spent a while this afternoon thoroughly testing Tor Browser 14 (14.0a5) with both the Source and Journalist Interfaces of my personal SD instance. The short version is, everything is working perfectly and appears no different than with the current stable release of Tor Browser. Specifically, I tested:

## Source Interface
- [x] Generating a new code name with the "Get Started" button
- [x] Sending a message
- [x] Sending a document
- [x] Viewing a Journalist reply
- [x] Deleting a Journalist reply
- [x] Logging out
- [x] Logging back in with existing code name

## Journalist Interface
- [x] Logging in with username, passphrase, and 2FA token
- [x] Viewing a submission
- [x] Downloading messages and documents
- [x] Sending a reply
- [x] Starring/unstarring submissions
- [x] Selecting and downloading a submission
- [x] Selecting and downloading unread submissions

Going to tentatively mark this as done, but happy to test any additional items I might have missed

**Comment by legoktm** [comment]
Yay! The only other thing I can think of testing is short onion names.

**Comment by nathandyer** [comment]
Good idea! I confirmed that the SD HTTPS-everywhere-ruleset is still present in `about:rulesets`, and I was able to load a well-known public SecureDrop instance using their Short Onion Name.

**Comment by legoktm** [comment]
Note that our CI needed some updates for TB14 (74ff170d45b13c02b22c5bf838e6c8c1d22c5dc5), but that's all taken care of now.
