### ISSUE TITLE
release SecureDrop 2.10.1

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#7239]
This is a tracking issue for the release of [SecureDrop 2.10.1](https://github.com/freedomofpress/securedrop/milestone/87), which will be a translations-only point release on top of [v2.10.0](https://github.com/freedomofpress/securedrop/milestone/86).

Tentatively scheduled as follows:

**Pre-release announcement:** TK
**Release date:** October ~17~ 22

**Release manager:** @cfm
**Deputy release manager:** @zenmonkeykstop 
~~**Localization manager:**~~
**Communications manager:** @nathandyer

## Test plan

Because this is a translations-only release, QA will be limited to:
- [x] CI passes on the release branch.
- [x] Diffoscope of (a) packages built from the release branch versus (b) v2.10.0 packages shows only the expected changes in translation files.

## Final release
- [x] Push signed tag 
- [x] Build final Debian packages (and preserve build log)
- [x] Diffoscope of (a) final packages versus (b) v2.10.0 packages shows only the expected changes in translation files, version strings, and timestamps.
- [x] Commit package build log to https://github.com/freedomofpress/build-logs
- [x] Pre-Flight: Test that install and upgrade from 2.10.0 to 2.10.1 works w/ prod repo debs (apt-qa.freedom.press polls the `release` branch in the LFS repo for the debs)
- [x] Pre-Flight: Test updater logic in Tails (apt-qa tracks the `release` branch in the LFS repo)
- [x] Flip apt QA server to prod status (merge to `main` in the LFS repo)
- [x] Merge Docs branch changes to ``main`` and verify new docs build in securedrop-docs repo
    - freedomofpress/securedrop-docs#605
- [x] Prepare release messaging

## Post release
- [x] Create GitHub release object 
- [x] Once release object is created, update versions in `securedrop-docs` and Wagtail
- [x] Verify new docs show up on https://docs.securedrop.org
- [x] Publish announcements
- [x] Merge changelog back to `develop`
- [x] Update roadmap wiki page: https://github.com/freedomofpress/securedrop/wiki/Development-Roadmap

**Comment by cfm** [comment]
Based on discussion today with @zenmonkeykstop, the release plan above assumes that we are comfortable doing "diffoscope-only" QA of a translations-only point release prior to preflight testing.  @freedomofpress/securedrop-maintainers, please do let me know if you feel differently.

**Comment by cfm** [comment]
Deferred to next week to allow more time for review of new translations.

**Comment by cfm** [comment]
We plan to fininsh preflight QA of freedomofpress/securedrop-apt-prod#148 tomorrow for a ~Monday~ Tuesday release.

**Comment by zenmonkeykstop** [comment]
- [x] Upgrade preflight:
  - [x] upgrade completed successfully, SI and JI on 2.10.1
  - [x] can upload files and messages in SI and download/decrypt from JI
  - [x] can reply from JI and read from SI
  - [x] spot-check of LTR and RTL languages shows no issues.

**Comment by cfm** [comment]
- [x] Preflight clean installation
    - [x] Installed successfully
    - [x] Source and Journalist Interfaces show v2.10.1
    - [x] Can submit
    - [x] Can reply
    - [x] Locales spot-checked
