### ISSUE TITLE
Upgrade geckodriver

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#7255]
The pagelayout tests are emitting warnings like:
```
WARNING The geckodriver version (0.33.0) detected in PATH at /usr/bin/geckodriver might not be
compatible with the detected firefox version (115.3.1); currently, geckodriver 0.35.0 is recommended
for firefox 115.*, so it is advised to delete the driver in PATH and retry
```

**Comment by andrewasche** [comment]
Hi I'm trying to see if I can reproduce this message, but I'm not finding it running `make test`
Let me know if I should try something else

**Comment by legoktm** [comment]
I believe pytest only shows it if the test fails, maybe adding "assert False" to the end of one of the functional tests would work. (I can figure out more specific reproduction steps on Monday if needed.)

**Comment by andrewasche** [comment]
Thank you I was able to reproduce this error by adding debugging output  with `make test -d` I will try to work on a change
