### ISSUE TITLE
Document setting up pfSense firewall with SecureDrop rules

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#732]
We have a [set of rules](https://github.com/freedomofpress/securedrop/blob/develop/install_files/network_firewall/rules) for the pfSense firewall that [we recommend](https://github.com/freedomofpress/securedrop/blob/develop/docs/hardware.md), but no guide that talks about actually setting up the firewall with said rules. The Netgate APU2 [installation guide (PDF)](http://support.netgate.com/index.php?/Knowledgebase/Article/GetAttachment/19/1134) may help with this as well.

**Comment by Taipo** [comment]
Just a note that these APU2 and APU4 units are out of stock. pFSense are recommending http://store.pfsense.org/SG2440/ as the current replacement.

**Comment by conorsch** [comment]
@Taipo thanks for pointing this out! I've opened a new issue, #1072, for updating the docs.
