### ISSUE TITLE
backup regression regarding the redis password

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#7328]
## Description

I haven't verified it yet, but there's probably a regression in the backup/restore prodecure now that we set a redis password. The password is set in config.py, which we backup, but we don't backup the redis.conf, so when it is restored, that same password won't be re-added to the redis config (a different one will be randomly generated).

We're also not backing up the new rq_config.py file.

**Comment by zenmonkeykstop** [comment]
We could probably regenerate it, I don't think we need to persist any redis state between backups.

**Comment by legoktm** [comment]
Ack, that's probably better. Since we already run `dpkg-reconfigure securedrop-app-code`, I think we should delete the redis password out of config.py (if set), out of redis.conf (if set), and then delete rq_config.py (if it exists) and then let it be regenerated by the postinst script.

I'll think about edge cases a bit more but tentatively tagging with the 2.11.0 milestone.

**Comment by legoktm** [comment]
I'm planning to tackle this after #7331 lands because that one moves the script around.
