### ISSUE TITLE
Create https://securedrop.org/focal-eol redirect

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#7371]
## Description

The JI now links to https://securedrop.org/focal-eol - create it as a redirect in wagtail to https://docs.securedrop.org/en/stable/admin/maintenance/noble_migration_prep.html once https://github.com/freedomofpress/securedrop-docs/pull/612 lands.

**Comment by nathandyer** [comment]
Once https://github.com/freedomofpress/securedrop-docs/pull/612 is ready, I'll tag a stable docs release, and then set up the redirect in Wagtail

**Comment by nathandyer** [comment]
https://securedrop.org/focal-eol is now redirecting as requested :)
