### ISSUE TITLE
Infer server time securely (ntpsec or other options)

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#738]
***NOTE: This issue is very old; see most recent comments [below](https://github.com/freedomofpress/securedrop/issues/738#issuecomment-513269078) - @eloquence, 2020-09-08***

Currently, the SecureDrop servers use the default Ubuntu behavior for time synchronization. This is:
- ntpdate is installed
- ntpdate is run on boot to update the server's time
- ntpd is _not_ installed

Therefore, the server's time is updated over NTP on every boot. This is not ideal for a few reasons:
1. Since these are long-running servers, the time is not updated between reboots and so may drift enough to cause problems. Since we now use TOTP (without any compensation for clock skew) for the journalist logins in the document interface, even a few seconds of drift has a noticeable impact and leads to improperly failed logins.
2. NTP is generally a poor choice for a security-sensitive application because:
   1. It is a UDP-based protocol, and so it cannot be proxied over Tor. This provides a signal for adversaries interested in locating the hidden service. Note that this is not a major problem in our threat model, as we expect the location of the servers is fairly easy to determine due to our deployment recommendations. However, it is still undesirable.
   2. It is not authenticated, so an adversary can manipulate the time information received by the server and attempt to perform all kinds of interesting attacks.

So, we need to keep the time accurate and do so in a security-conscious manner. The best choice here seems to be to use [tlsdate](https://github.com/ioerror/tlsdate/). It is easy to setup, provides a daemon, and is widely used (e.g. is default time updater on Chromebooks). It uses TCP, so it can be proxied over Tor, and it uses TLS, so it provides an (imperfect but substantial) level of protection from network attackers.

In order to use tlsdate, we need to:
- [x] Confirm which version we should use. The [version in the Ubuntu trusty repository](http://packages.ubuntu.com/trusty/net/tlsdate) (0.5) appears to be significantly behind the latest release (0.12). Can we use 0.5, or should we use 0.12?
  - [ ] If we need to use 0.12, how should we install it? Options include:
    - get the maintainer to update the super-old version in the trusty repos
    - package it ourselves and provide it in the FPF repo
- [ ] Test that installing tlsdate means that ntpdate (which is insecure by comparison) is no longer used at all. We need to make Ubuntu use tlsdate instead of ntpdate to update the time on boot. There are a variety of possible strategies here:
  - [ ] Does tlsdate handle this for us as part of its postinst?
  - [ ] If not, can we edit the boot-time time updater script to use tlsdate?
    - [ ] Test this - it's possible that weird things could happen depending on when in the boot order this happens.
  - [ ] If that doesn't work, can we just disable ntpdate and let the system fall back to the tlsdate daemon?
    - [ ] How to disable ntpdate? `apt-get purge` it?

**Comment by garrettr** [comment]
OpenBSD team is using one of tlsdate's techniques to provide authenticated "constraints" for the time set by ntpd: http://marc.info/?l=openbsd-tech&m=142356166731390&w=2. It is an interesting alternative approach.

**Comment by garrettr** [comment]
More reasons why NTP is problematic: http://arstechnica.com/security/2015/10/new-attacks-on-network-time-protocol-can-defeat-https-and-create-chaos/

**Comment by fowlslegs** [comment]
So @Whonix seems to have done a lot of homework on this issue. There are a number of interesting notes and ideas [here](https://www.whonix.org/wiki/Dev/TimeSync).

**Comment by garrettr** [comment]
Note that this change needs to be made carefully, and with some thought given to monitoring the reliability and consistency of whatever NTP replacement we choose. SecureDrop optionally (in practice, often) uses TOTP in various places as a second authentication factor, and as TOTP is time-based it is very sensitive to clock problems, and can cause authentication for journalists and admins (see background in #736) to break, which is a major availability problem. A quick skim of [tlsdate's issues](https://github.com/ioerror/tlsdate/issues), e.g. https://github.com/ioerror/tlsdate/issues/173, shows that this kind of problem is unfortunately common, and is often out of the tlsdate's maintainers control.

**Comment by ioerror** [comment]
On 11/4/15, Garrett Robinson <notifications@github.com> wrote:
> Note that this change needs to be made carefully, and with some thought
> given to monitoring the reliability and consistency of whatever NTP
> replacement we choose. SecureDrop optionally (in practice, often) uses TOTP
> in various places as a second authentication factor, and as TOTP is
> time-based it is very sensitive to clock problems, and can cause
> authentication for journalists and admins (see background in #736) to break,
> which is a major availability problem. A quick skim of [tlsdate's
> issues](https://github.com/ioerror/tlsdate/issues), e.g.
> https://github.com/ioerror/tlsdate/issues/173, shows that this kind of
> problem is unfortunately common, and is often out of the tlsdate's
> maintainers control.
>

You just have to run an accurate clock on the remote server. This is
why we use the Google service as millions of ChromeOS users use it.

**Comment by torrancew** [comment]
Apologies for chiming in on such an old thread, but as the poster of the mentioned TLSdate issue, I can second that that bug relates to a single server that provided the issue, which just so happened to be the debian package's default value. In the case of that bug, the default config was in use on 2 personal workstation. Conversely, we also deployed tlsdate to several hundred servers with a more carefully architected hierarchy, and a more carefully chosen external authority, and had absolutely no issues. (This was also a TOTP environment).

**Comment by garrettr** [comment]
@ioerror @torrancew Thanks for chiming in with your feedback and personal experiences using tlsdate. When I wrote my comment in November, my main thought was that, had we already been using tlsdate, which would've been installed from the Debian/Ubuntu packages, then https://github.com/ioerror/tlsdate/issues/173 would have created serious availability problems for SecureDrop users due to our use of TOTP for authentication.

However, I am glad to hear that this was a localized problem, and my characterization of this type problem as "common" in https://github.com/freedomofpress/securedrop/issues/738#issuecomment-153838096 appears to have been unfair. We are refocusing our attention as an organization on SecureDrop in Q2 2016, and I expect switching away from ntp to tlsdate will be included in one of the next major releases (0.4 or 0.5).

**Comment by eloquence** [comment]
We are still interested in this; however, it appears that tlsdate is unmaintained (last commit 2015). We'd want to use a maintained fork or another option. Adding to "Some Day" milestone until we have an agreed upon implementation strategy, and retitling.

**Comment by ageis** [comment]
Yeah, I would say the situation has evolved since 2014, and I would suggest https://www.ntpsec.org/. It's based on the reference implementation that we all love and know to be vulnerable, but secure and hardened.

I recommend time.cloudflare.com too, as anycast technology means your NTP client will talk to the geographically nearest PoP.

On NTPsec, here are some of the benefits; quoting from https://www.ntpsec.org/accomplishments.html:

- We have extracted the NTP codebase from BitKeeper
- We have significantly hardened the code against buffer overruns
- We have implemented Network Time Security
- We have removed about a hundred seventy five thousand lines of obsolete code
- We have improved the accuracy of time stepping with real hardware by x10
- Our ntpd can run in a fully autonomous mode using local clocks only
- We have implemented a simpler refclock configuration syntax
- We have added a statistics-file visualizer to help diagnose problems
- We have applied Coverity scanning and fixed bugs where they were revealed
- We have fixed all compiler warnings
- We have increased the visibility of potential defects to static analyzers
- We have moved the build to waf
- We have updated and reorganized the documentation
- We have reduced the set of languages used in the suite to C and Python
- We have added an improved reporting tool for time service operators
- We have collected on the gains from Pythonizing all our scripting by adding ntpmon, an administrator’s tool 
- We have earned trust in the InfoSec research community
- We have achieved measurable gains in security

The other popular ntp alternative is [chrony](https://chrony.tuxfamily.org/), which is definitely better than ntpd. See https://chrony.tuxfamily.org/comparison.html, especially the security section.

**Comment by ageis** [comment]
The key feature is Network Time Security, which is basically TLS for ntp. It's a [brand new IETF spec](https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp-19) which I'm not aware of other pools/servers that are using it besides Cloudflare.

**Comment by eloquence** [comment]
Are there other security risks associated with our use of  ntpdate beyond the risk of denial of service type attacks? This would likely influence the priority of replacing ntpdate with alternatives like ntpsec.

**Comment by ageis** [comment]
Not particularly... anything warranting a CVE will have already been covered by the distribution's security updates. Take a look [at MITRE](https://www.cvedetails.com/vulnerability-list.php?vendor_id=2153&product_id=&version_id=&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&month=0&cweid=0&order=1&trc=88&sha=c61e5eda4bb989460ea442ed3188781a4266eaa8) for an overview of vulnerabilities.

**Comment by legoktm** [comment]
Starting with Debian Bookworm the `ntp` package will now be ntpsec, I assume Ubuntu will follow along. The thread starting with https://lists.debian.org/msgid-search/454d0e14-7448-5cef-ad68-cbdff7467edd@debian.org has some more discussion/details.

My personal preference would be to use systemd-timesyncd though.

**Comment by zenmonkeykstop** [comment]
timesyncd is already in use on  SD servers as per https://github.com/freedomofpress/securedrop/pull/5806 so we can probably close this.

**Comment by legoktm** [comment]
Perfect! (I feel like I should've already known that...)
