### ISSUE TITLE
Verify contents of prod-specific.yml before installing SecureDrop

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#749]
When installing SecureDrop, the admin is asked to fill out _prod-specific.yml_ before running an _ansible-playbook_ command which installs the software and configures/hardens the servers. As part of the installation process, the _ansible-playbook_ command should verify the contents of _prod-specific.yml_ before continuing. 

That is, we need to make sure the information we require for the install is present in the file, and we also need to make sure the information that is present is accurate. The installation process does not seem to complain about the fact that the IP address I entered for the Monitor Server is "192.168.1.522".

**Comment by fowlslegs** [comment]
@conorsch Think this one should stick in the 0.4 milestone?

**Comment by conorsch** [comment]
@fowlslegs Yes, thanks for nudge. Will step through the related issues here and evaluate the same.

**Comment by conorsch** [comment]
#1348 has good targets for validation, but as described in https://github.com/freedomofpress/securedrop/pull/1348#issuecomment-240519667 and https://github.com/freedomofpress/securedrop/issues/1340#issuecomment-237020725, we'd do well to use Ansible's `assert` module to perform these checks, rather than a custom script.

**Comment by conorsch** [comment]
Preparing a PR to resolve, waiting for review and merge of #1762. All the logic is present in the `validate-all-prod-vars` feature branch right now, but I'd like to cherry-pick some of @heartsucker's work in #1259 to strengthen the GPG validation.

**Comment by conorsch** [comment]
Given feedback from first-time Admins, a common problem during installation is not enabling required persistence options, e.g. SSH keys. We should try to validate that the persistence options are indeed enabled during setup time, otherwise hard-to-debug problems come up, e.g. loss of SSH keys.
