### ISSUE TITLE
Users should download the FPF signing key from our website

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#771]
As discussed in #742, I think users should download the Freedom of the Press Foundation Master Signing Key from our website and not from a keyserver. We updated install.md to download the key from a keyserver because the new site has not yet been launched. As soon as the site is launched, we should make the key available there and update install.md again.

**Comment by garrettr** [comment]
The key is available on the [Freedom of Press Foundation website](https://freedom.press/sites/default/files/fpf.asc) and the new [SecureDrop website](https://securedrop.org/sites/default/files/fpf.asc). The link is advertised prominently on the footer on both sites.
