### ISSUE TITLE
OSSEC now supports authd client authentication

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#818]
OSSEC now supports "Optional Client Authentication" for the authd dameon. [1] The authd process is used to initially create and distribute the pre shared secret key used for the ossec server agent communication. Currently this is an unauthenticated process that is done only during the initial installation and if needed while re-ip'ing an existing install. Otherwise the process is not enabled.

Enabling the authd client authentication would require generating and distributing a signed client/CA certs to the agent/server with ansible during the initial install.

[1] http://ossec-docs.readthedocs.org/en/latest/programs/ossec-authd.html

**Comment by garrettr** [comment]
@dolanjs Can you describe a little more of the benefit that would be realized with client authenticator for the authd daemon? IIRC we only run this program once during the installation process, so the risk of compromise at that point is fairly minimal. It also seems to incur some significant administrative overhead, in the form of generating, distributing, and maintaining a CA/CA certs.

**Comment by dolanjs** [comment]
@garrettr I don't really see what we would gain from this either. The ossec agent/server authd connection does not leave the SD environment and it would cause a significant setup/maintenance overhead. For those reasons think we can not implement this and close the issue.
