### ISSUE TITLE
referrer solution

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#819]
from talking to Mike West, I learned that the HTTP referrer meta tag can be used to clear referrer for all subresources and navigations: https://wiki.whatwg.org/wiki/Meta_referrer. (its proposed replacement, the CSP referrer header, is nowhere near supported in Firefox ESR)

this makes #516 unnecessary.

**Comment by garrettr** [comment]
When we return to this issue, we should also consider https://twitter.com/frgx/status/650289616587767808

> you also want to kill the opener property. Rel=noreferrer ftw; or just have a redirect page

**Comment by diracdeltas** [comment]
My TBB referer patch was merged in TBB 5.0.4 so I think this can be closed
