### ISSUE TITLE
Rounded timestamps

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#822]
Currently, the exact timestamps of submissions and replies are stored on the SecureDrop. We normalize submission timestamps (#301) for each source, so all submissions appear to have the same timestamp as the most recent submission (both in the database and on the filesystem). The ordering of the submissions is maintained naturally due to the auto-incrementing primary key in the database.

While this destroys the metadata of the prior history of submissions, it is precisely accurate for the latest submission and also for all undeleted replies (which could theoretically be used to infer some general timing information about prior submissions).

Another approach to consider would be to obfuscate _all_ timings by rounding. One specific adversary to consider is a passive network attacker near the source who monitors Tor flows (say their local network administrator or ISP). If they also had access to the document interface or database, then they would be able to precisely correlate the flows they observed with the timing of submissions.

We could mitigate this by rounding the times that we record to the nearest minute, hour, or day. The ordering must be preserved or the conversation will be impossible to follow, but there seems to be a reasonable tradeoff of the usability of following the conversation with mitigating potential metadata correlation attacks.

If we implemented this, we might be able to revert #301 (which is unintuitive). Or we could consider increasingly rounding the timestamps over time, so a recent submission may be rounded to an hour, an older submission may be rounded to the day, and an even older one may be rounded to the week or month. (This is just thinking out loud - I advocate implementing the simplest version of this first, and carefully considering the tradeoffs of implementing something like this due to the significantly increased complexity).

We would need to add UI information to the source and document interfaces to help users understand that the timestamps are rounded, and why.

Thanks to Roger Dingledine for suggesting this.

**Comment by aliclark** [comment]
+1 sounds like a good idea

Further steps beyond this might be to:
a) remove all time info from the UI and instead use a "*new*" binary flag. Timing info can be really useful for an attacker, eg. to guess the source's timezone or occupation

b) the SecureDrop instance could hold back submissions and comments to some rounding time. For example, it might only show new entries at 9.30AM, 1.30PM and 5PM local time (but the sysadmin could create special cases). This especially applies to comments - having an interactive conversation could be a really bad idea (questions could still be bulk-asked and bulk-answered with reasonable timeliness).

**Comment by garrettr** [comment]
@aliclark Those are both good ideas!

a) I think it would be possible to create a UI that dispenses with timestamps, and just uses ordering + "new", although we would definitely need to prototype this and do some user testing to make sure it doesn't confuse people, or throw away information that journalists might want.

b) Also a good idea. I have been thinking that it would be good to send journalists emails when they receive submissions. Of course, we should not just send emails as soon as submissions are received as that would leak timing metadata. A better idea would be to send a daily or n-daily (interval could be choosable by users) digest email about the activity on the system. This would fit well with what you propose here.

**Comment by aliclark** [comment]
Thanks Garret, it's good to see you're open to these ideas. A non-batched approach in the worst case could only hide timing info up to however often the system is being checked, and a batched one up to however long before batching becomes a usability issue. I guess this range might be somewhere between an hour and 1-2 days depending on the organization.

On the other hand, the current rounding beyond that could still be helpful for retroactive analysis, if files aren't being deleted from the drop system, but zip contents would also need to have times touched at creation to provide protection.

I could have a go at the original issue solution soon, which seems possible by supplying "-t MMDDhhmm" to touch, perhaps rounding down to the nearest 1, 2 or 3 hours.
Cheers

**Comment by mdrose** [comment]
This is considerably more difficult than I expected. utime, and by extension, touch, only sets the atime and mtime timestamps on files, leaving the ctime with an accurate timestamp. This makes rounding impossible through this method. The only way I can seem to change the ctime is by changing the system clock, unless I'm missing something?

**Comment by fowlslegs** [comment]
Leaving this issue in 0.4 because there is a pending PR https://github.com/freedomofpress/securedrop/pull/834.

**Comment by conorsch** [comment]
In order to focus on reconciling develop and master branches in the 0.4 release, removing this from the milestone. We're still interested in adding it, but we'll need to document the UX change, since Journalists won't be able to rely on the precision of the most recently submitted timestamps any longer.

**Comment by heartsucker** [comment]
Hey guys. I was assigned to review #834, but it seems like the effort should be saved until after we do a more thorough analysis of what we want this feature to do. I think this feature really make the most sense if we fully truncate the timestamp columns in the tables as well as obfuscate the filesystem metadata.

I think the solution we need to take is to only use a date (without time) for everything about sources and communications, and we need to obfuscate filesystem metadata. I think we need to scrap #834 and implement a feature that:

1. Only writes dates
2. Truncates old datetimes
3. Scrubs FS metadata
4. Updates the UI to match the new timestamp format

Thoughts?

**Comment by redshiftzero** [comment]
This is certainly an interesting idea, but I don't think the security benefit here justifies the technical effort and additional complexity this introduces. 

Any attack involving a compromise of the SecureDrop application server has much more serious implications than being able to read the timestamps on the files, primarily the attacker being able to read the plaintext of all submissions, messages and replies after the point of compromise. A compromise of just the journalist interface would provide timing information (and not the plaintext of submissions), but would require the attacker to circumvent several other security protections - they'd need compromised journalist credentials or a critical web app vulnerability along with the ATHS token for the journalist interface. Generally, to make use of the timestamps at all, they'd also need the ability after making a critical attack against SecureDrop to associate the timing information with Tor activity on their local network, else the timestamps do not provide any interesting information. 

The PR in #834 is a good one from an earlier era of SecureDrop, but I agree with @heartsucker that we should scrap it (also worth noting a lot of the underlying code has changed now) given the above. Let's close it, and re-evaluate what would be need to done to resist forensics down the road once [higher priority issues](https://github.com/freedomofpress/securedrop/issues?q=is%3Aissue+is%3Aopen+label%3AP-high) have been addressed. Until then we can leave this issue open and unimplemented. I've placed it on the [Someday](https://github.com/freedomofpress/securedrop/milestone/31) milestone.

**Comment by eloquence** [comment]
Closing per https://github.com/freedomofpress/securedrop/issues/822#issuecomment-333052295 , feel free to reopen if you want to make a strong security argument that would outweigh the concerns about complexity and maintenance effort (and potentially reduced usability).
