### ISSUE TITLE
capture non standard straffic

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#832]
To improve incident response and forensics for suspicious activity we could implement [sysdig](http://sysdig.org) on the servers and configure sysdig to capture non-standard outbound traffic and some other the other [examples](http://www.sysdig.org/wiki/sysdig-examples/) listed.

**Comment by ageis** [comment]
Note that sysdig entails a privileged kernel module. This is a pretty interesting and possibly worthwhile idea; part of me wonders why James didn't reckon the standard userspace tools like conntrack and iptables logging would suffice.

**Comment by conorsch** [comment]
We're interested in improving the monitoring story over all, even considering alternatives to OSSEC in https://github.com/freedomofpress/securedrop/issues/1123. At present, we're unlikely to add sysdig or other tooling without a deep rethinking about the role monitoring serves, and how Admins wish to interact with it.
