### ISSUE TITLE
Follow-up on meta refresh to clear referer

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#841]
We reverted the use of a custom redirect page that use meta refresh in #453 because it did not appear to work in production. In re-examining this issue now, I do not believe we resolved it properly. There is never an answer as to why the issue happens in production but does not happen in development. Now that we have a much better system for testing production and production-like environments (Vagrant + Ansible), it should be possible to debug this properly.

Tagging for 0.3 because the usability of copy-pasting links sucks.

**Comment by fowlslegs** [comment]
Not worth time debugging this because it's not necessary anymore since Yan's patch got upstreamed in TB.
