### ISSUE TITLE
Harden SSHD Configs

### ISSUE THREAD

**Issue by Hainish** [freedomofpress/securedrop#857]
We now know that the NSA can decrypt SSH at least some of the time.  OpenSSH permits certain ciphers that are questionable, including unsafe NIST curves, SHA1 dependent suites, and theoretically factorable (< 2048 bit) DH negotiations.

https://stribika.github.io/2015/01/04/secure-secure-shell.html provides SSHD configs which preclude the possibility of connecting with crypto considered unsafe.  We should follow these guidelines for any SSH service we connect to, for instance, the monitor server.

**Comment by ageis** [comment]
I have a commit to implement the recommended key exchange algorithms (shown below) on the sshd_config for the app and mon server. I don't really see much point or benefit to touching the ssh_config in the app/mon roles, but maybe I'm wrong? Not only are you not supposed to be shelling to other systems from the SD environment (I think), but insisting on these settings globally would also limit the servers that you can successfully negotiate with.

Client configuration on the admin workstation and whatnot is left to them, so we could simply put a link to this post in our setup guide.

```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
```

**Comment by garrettr** [comment]
> Client configuration on the admin workstation and whatnot is left to them

I don't think we have to limit the client configuration if we harden the server configuration. The only concern is clients who can't negotiate any of the hardened set of `KexAlgorithms`.
