### ISSUE TITLE
When ossec_gpg_fpr is invalid, OSSEC sends empty emails

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#858]
**STR**
1. Fill out the OSSEC information in `staging-specific.yml`, following the instructions in `docs/ossec_alerts.md`.
2. Mess up the value of `ossec_gpg_fpr`. In my case, I accidentally deleted a character of the fingerprint while manually removing whitespace (which is present by default in the output of `gpg --with-fingerprint`).
3. `vagrant up /staging$/
4. Note that the OSSEC emails you receive contain correct-seeming subject lines, but the emails themselves are empty.

At a minimum, this should trigger errors on the installed system. From a cursory examination, I did not see any errors from encrypting the emails in `/var/ossec/logs/ossec.log` or `/var/log/mail.log`. Even better, we should prevent the install from happening if this kind of error is apparent in the configuration.

**Comment by ageis** [comment]
This is because of the custom script we're using send_encrypted_alarm.sh which consists simply of the one-liner:
```
/usr/bin/formail -I "" | /usr/bin/gpg --homedir /var/ossec/.gnupg --trust-model always -ear "{{ ossec_gpg_fpr }}" | /usr/bin/mail -s "$SUBJECT" {{ ossec_alert_email }}
```
At some point earlier I had questioned this approach of using procmail and piping things and suggested that we should consider using a Postfix content filter such as gpg-mailgate instead (https://code.google.com/p/gpg-mailgate/) In any event, without testing I am not sure how that would affect or change this specific issue. 

We can start by making sure the gpg command exits successfully and without errors in the send_encrypted_alarm script, and sending something to the log if it doesn't.

**Comment by runasand** [comment]
Seems related to #749, which is currently tagged as an enhancement with a 0.4 milestone.

**Comment by garrettr** [comment]
I agree with @runasand that the best way to resolve this issue is via validating data before the install even begins.

Additionally, we might consider adding a check to `send_encrypted_alarms.sh` to make sure the GPG key is available. In that case, you might run in to a chicken-and-egg scenario where you want ossec to send an alert about the issue, but the issue is about sending email so it can't send an email about not being able to send email (xzibit.jpg). I think logging something explicit out to syslog would be better than nothing though.

**Comment by conorsch** [comment]
Definitely agree that we need to validate the GPG fingerprint prior to using it in templates. We can do that via various `assert` checks as described in #749 and elsewhere. Doing so will help prevent known-bad vars from landing on the Monitor Server in the first place.

Additionally we should ensure that the `send_encrypted_alarm.sh` script is more resilient to failure, e.g. with `set -e` and `set -o pipefail`. Seems sensible that if the encryption command fails, we should still try to send mail, with a default string such as:

> Failed to encrypt OSSEC alert; investigate the mailing configuration on the Monitor Server.

Could also insert explicit reference to contacting SD support, but we can tackle those copy-level edits during review of a solution.
