### ISSUE TITLE
Server hard drive freespace scrubbing

### ISSUE THREAD

**Issue by Taipo** [freedomofpress/securedrop#88]
Worst case scenarios are a journalistic organisation facing a direct raid by an adversary in a country that does not have laws protecting the rights of journalists/sources.

This goes beyond having apache logging disabled and secure file destruction

It is important that the source and journalist servers have their free space scrubbed regularly to remove not just the deleted file content but also the meta data history to prevent a nation state adversary from rebuilding an activity, where proof of the activity itself could be enough to begin incriminations against a journalist.

If that is an accepted premise, how well can a solid state drive have its free space scrubbed, or individual secure file erasing? 
http://www.usenix.org/events/fast11/tech/full_papers/Wei.pdf

**Comment by garrettr** [comment]
I think this is less of a concern due to the implementation of the anti-forensic measures in #862, but we might still consider implementing it for some additional defense in depth.

**Comment by redshiftzero** [comment]
Since swap is disabled (#1626), we use `srm` when deleting documents (#131), and we never write plaintext to disk in the first place (#862), I'm closing this issue. Feel free to comment if you disagree.
