### ISSUE TITLE
Automatically enforce PEP8 for Python code

### ISSUE THREAD

**Issue by ThomasWaldmann** [freedomofpress/securedrop#886]
there are some pep8 issues in the code - would you like to have them cleaned up?

If so, I'ld also suggest to use pytest-pep8, so no new issues will be introduced in future.

**Comment by ThomasWaldmann** [comment]
see PR #890

**Comment by garrettr** [comment]
The pep8 issues in the current code were fixed in #890. I'm changing the title of this issue to make it about auto-enforcing pep8 in the future.

**Comment by ajvb** [comment]
PEP8 issue currently exist. Is this something we want to get rid of? I personally think the 80 character line limit is lame, but if it is the desire of the project, I'm all about it.

I have had great success with https://pypi.python.org/pypi/autopep8 in the past, I could help create a pre-commit git hook we stick in the repo and we could use Code Climate or similar for style enforcement on PR's?

**Comment by ajvb** [comment]
Also, I'd be happy to run it throughout the application and test code and create a PR.

**Comment by redshiftzero** [comment]
Yep! automatic PEP8 checking via autopep8 would be great. If you want to take that on it would be really helpful :+1:. We still need to define what else constitutes good style for this project (relevant: #47), once we do that we can add additional automated style checks.

**Comment by ajvb** [comment]
Would be my pleasure. I'm conferencing this week and most of next so probably will be a little bit till I can complete it. On a side note, how do you guys feel about adding something like http://codeclimate.com/ with the github integration so every users PR's must follow pep8? There are other options, but I've had good success with CodeClimate and it is free for OSS.

**Comment by fowlslegs** [comment]
I was looking into it last week actually. PEP8 checking would be useful, and Radon just looks like fun to play with. I would be open to trying it, considering it is free for open-source projects.

**Comment by ajvb** [comment]
@fowlslegs Ok awesome :D

Fixed current PEP8 related issues in #1471 and added pep8 pre-commit hook

**Comment by ThomasWaldmann** [comment]
BTW, in my projects, I have pep8 checking active (via pytest-pep8), but I don't enforce the 80chars limit, but set a limit of e.g. 120 chars.

80 has more bad effects imho than it does good - and we don't have vt80 terminals any more.

**Comment by fowlslegs** [comment]
As an alternative to code climate, we could just run `pep8` in Travis. Does CodeClimate provide any benefit that would help contributor's identify and fix PEP8 errors faster?

**Comment by ThomasWaldmann** [comment]
I had a look at codeclimate a while ago. While it looks pretty at first, I had the impression that it doesn't give much practically useful information. I did not actually try it longer term though, so take that with a grain of salt.

**Comment by ajvb** [comment]
I do think that CodeClimate provides a nicer interface than simply running `pep8` in Travis and it includes Radon, but I think running `pep8` in Travis may be better as it is easier to set "global rules".

>80 has more bad effects imho than it does good - and we don't have vt80 terminals any more.

I completely agree with this, and it would be easier to set a different line length requirement through running `pep8` in Travis.

**Comment by fowlslegs** [comment]
I'm not dead set on keeping it at 79* either, however, 120 is too long for me to have two files open in vertical-split panes on my laptop. 100 might be a good.

> easier to set a different line length requirement through running pep8 in Travis

Really? I would hope this would be easy to do either way.

**Comment by fowlslegs** [comment]
Asked a friend in order to collect a little more anecdata: for her monitor + font size, 99 chars will fit in a split pane.

**Comment by fowlslegs** [comment]
Leaving this in 0.4 for now because there is a pending PR, although rebasing will be terrible considering how much develop has changed.

**Comment by fowlslegs** [comment]
Testing story here is relevant https://github.com/freedomofpress/securedrop/pull/1894#issue-239207662.
