### ISSUE TITLE
Automate running google-authenticator for each admin in Ansible

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#895]
This is related to issue #826 and cutting down on manual processes needed for the admin to get set up. We could create a new Ansible task that runs google-authenticator on the App & Mon Server on behalf of each admin user and captures the output and writes it to a file in /install_files/ansible-base, which would then contain their QR code, secret key, verification and emergency codes. (Note from a security standpoint, this necessarily entails that admins might get access to each other's codes, which I think we can probably allow)

@garrettr considered the problem in terms of three priorities:

1) using google-authenticator's command line arguments
2) writing ~/.google_authenticator based on what the utility *would* output (not ideal in case anything changes in the future) reportedly @dolanjs tried this before
3) piping "y" to STDIN to run google-authenticator interactively (super buggy and inadvisable) 

Our current documentation recommends answering "yes" to everything in terms of the rate limiting and window size. Based on that I determined the following command would suffice to achieve the same result:

`google-authenticator -f -t -d -r 3 -R 30 -w 17`

In case you don't want to use sudo_user for some reason then you could just use -s arg to write ~/.google_authenticator to another non-standard location and later move it into $HOME.

Not a high priority but I am willing to work on it.

**Comment by dolanjs** [comment]
@ageis to clarify this would mean the person who runs the ansible playbook would have all of the provisioned OS admin secret values on their Tails workstation. Granted the person who runs the ansible-playbook also has root access on the servers, so if they wanted to, they could retrieve all the values anyway.

**Comment by conorsch** [comment]
Superseded by #1283, in which we discuss whether recommending 2FA for Admins is a good idea at all.

**Comment by memelet** [comment]
So this 2FA is being considered only for tty logins? What about ssh logins? Is there another issue for that?

**Comment by garrettr** [comment]
@memelet See #826 and #1283.
