### ISSUE TITLE
Automatically run "SecureDrop Init" after boot

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#896]
`tails_files/install.sh` creates a "SecureDrop Init" launcher for the journalist workstation. Double-clicking this launcher adds the HidServAuth values for the Document Interface to the system torrc and reloads Tor.

There is no reason to require this to be manually run, and forgetting to do this is a common cause of support complaints. We should instead use the [Tails dotfile persistence](https://tails.boum.org/doc/first_steps/persistence/configure/index.en.html#index13h2) to auto-run "SecureDrop init" at boot.

The only reason we haven't done this yet is because we haven't had a chance to test this. This needs to be tested thoroughly with Tails to make sure it reloads Tor correctly and at the right time for the changes to be persisted for the entire Tails session.

**Comment by ageis** [comment]
Turns out that xsessionrc is not really the "right time" and can result in stuff like #985 on slow computers because of timing differences. A better solution is a NetworkManager hook which is now part of the #955 PR.

**Comment by ageis** [comment]
There is a second reason not to use .xsessionrc. Turns out that Tails is using it to export a few environment variables, which I didn't notice until now probably since I had overwritten the file and didn't check what was in it before. =/

**Comment by conorsch** [comment]
Resolved via #1018, which implemented Network Manager hooks for setting up the Tor config upon logging into Tails with persistence activated. Additional testing to be performed in #1299, prior to 0.3.7.
