### ISSUE TITLE
Copy'ing the tails_files .securedrop folder doesn't work

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#897]
Since all of the journalist use the same ATHS it would be nice if once the first Journalist was created the .securedrop folder can just be copied to the other journalists' Tails USB. 

Tails sets a restrictive default umask which I think is changing the permissions that are required for SecureDrop init to work.

**Comment by eloquence** [comment]
Closing in favor of #5297, which discusses improvements to the Journalist Workstation provisioning story in the context of the current architecture.
