### ISSUE TITLE
Automatically install persistent packages on Tails

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#898]
If you enable [APT persistence](https://tails.boum.org/doc/first_steps/persistence/configure/index.en.html#index8h2) on Tails, the packages will be stored but they *will not* be automatically installed on reboot. Auto-installation can be achieved by [editing live-additional-software.conf](https://tails.boum.org/doc/first_steps/persistence/configure/index.en.html#index14h2).

We should auto-install Ansible on the Admin Workstation by default.

**Comment by ageis** [comment]
This is covered in pull request #922.

**Comment by garrettr** [comment]
These changes were merged and modified over a long series of PR's to develop, see #1182 for the initial merge. The Tails install script was overhauled and improved in #1309 and merged into release/0.3.7 to address various Tails-related issues in [0.3.7](https://github.com/freedomofpress/securedrop/milestone/12). The overhauled scripts will be merged back into develop as part of #1313. Marking this as resolved.
