### ISSUE TITLE
Automatically set up SSH aliases on Admin Workstation

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#899]
After Ansible is finished, the only way to access the servers is by SSH'ing to an ATHS. We can make this easier by setting up entries for "app" and "mon" in `~/.ssh/config` using Tails' [dotfile persistence](https://tails.boum.org/doc/first_steps/persistence/configure/index.en.html#index13h2).

**Comment by ageis** [comment]
This is covered in pull request #922.

**Comment by conorsch** [comment]
Resolved via #1182.
