### ISSUE TITLE
Use a bigger wordlist

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#902]
It seems Diceware is nowhere near the length of the biggest english wordlists. For instance, this one seems quite reasonable and has 109,582 words: http://www-01.sil.org/linguistics/wordlists/english/wordlist/wordsEn.txt.

The securedrop passphrases are ~90 bits by default, IIRC. Using that list, it would be 5-6 words instead of 7-8.

**Comment by diracdeltas** [comment]
That wordlist above is from http://www-01.sil.org/linguistics/wordlists/english/. The license is unclear but seems permissive ("public brand software").

**Comment by garrettr** [comment]
@diracdeltas There's a trade-off between usability and wordlist length. The longer the list, the more unfamiliar words (which are difficult to remember). I think our current wordlist could be improved in the following ways:

- [ ] lengthen it, taking care not to add overly long, unfamiliar, or offensive words
- [ ] remove any unusual or awkward entries in the list

For example, I think the single letter and number entries in the current wordlist are a little awkward in the context of a passphrase that is mostly words.

**Comment by diracdeltas** [comment]
FWIW I've played around with the wordlist above and found that randomly-chosen phrases were as memorable if not more memorable than diceware phrases of the same length.

**Comment by redshiftzero** [comment]
Closing this since we recently adopted EFF's carefully researched wordlist in #1452 which addresses the concerns with hard to memorize, offensive, or awkward entries. If a longer list is produced by the community then we will use it, else we should work with what we have imho.
