### ISSUE TITLE
Consider setting kernel.grsecurity.deny_new_usb

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#917]
[Docs](http://en.wikibooks.org/wiki/Grsecurity/Appendix/Grsecurity_and_PaX_Configuration_Options#Deny_new_USB_connections_after_toggle).

Setting this on the app/monitor servers could add another layer of difficulty for adversaries who might attempt a physical compromise. On the other hand, it could also complicate backup/recovery efforts. For example, backups would have to travel over Tor (which might take a very long time if there are a lot of large files submitted).

**Comment by garrettr** [comment]
We should consider using some of grsecurity's other [physical protections](http://en.wikibooks.org/wiki/Grsecurity/Appendix/Grsecurity_and_PaX_Configuration_Options#Physical_Protections) as well. We can either re-purpose this issue for "consider all grsecurity physical protections", or we can file new issues for each protection as the need arises.

**Comment by redshiftzero** [comment]
Given that it's not uncommon for admins to console into their SecureDrop servers to look at logs (and sometimes transfer these logs onto USB drives for analysis) if they experience network issues, I don't think we could apply this grsecurity option without introducing significant complication to an already quite complicated troubleshooting process. Closing for now, and we can reopen at a later date if the situation changes.

**Comment by msheiny** [comment]
This issue was discussed during an internal security audit as a candidate for re-opening. ping @conorsch who is highlighted in my notes

From discussion:
> Admins will not be permanently blocked from using USB, they’ll just need to plug in USB devices and then reboot (likely hard reset). Depends on securedrop-config package (due in 0.5.1) handling sysctl values.

**Comment by ageis** [comment]
For whoever next stumbles on this issue, and if you're thinking of deny_usb, I strongly suggest or would point out the potential import of many other grsec sysctl settings, many of which are less impacting of usability. The only ones conclusively addressed by your environment are rwxmap_logging and grsec_lock. https://gist.github.com/ageis/5875289fd85d7e2d30e1

**Comment by conorsch** [comment]
We're not going to implement this any time soon. As mentioned above (https://github.com/freedomofpress/securedrop/issues/917#issuecomment-351101158), physical access to a SecureDrop server is a problematic situation in itself, and denying insertion of new USB devices doesn't provide any meaningful protection. Even if we did restrict new insertions, an attacker would simply have to insert and then wait for the nightly server reboot for the device to be recognized. 

If we ever remove the mandated nightly reboots, then we can reconsider.
