### ISSUE TITLE
Bookmark the interfaces in Tails

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#923]
In investigating the possibilities of Tails's dotfiles persistence, I determined that it should be possible to place bookmarks for the Document and Source interface in a submenu of the main Applications menu.

Practically, this involves putting launchers in `~/.local/share/applications` a definition for the menu in `~/.config/menus`, and potentially a "directory" definition in `~/.local/share/desktop-directories`. Alternatively, we could just place these bookmarks on the desktop.

**Comment by ageis** [comment]
Technically completed with Desktop shortcuts in pull request #922. The Desktop is certainly more visible than other menus. Unfortunately in my investigation/testing I couldn't get the Applications sub-menus I wanted to be created by using the same conventions (mentioned in the previous comment) that would create them on Debian.

**Comment by ageis** [comment]
Just wanted to add, it will only be possible for us to automate Tor Browser bookmark creation (rather than Desktop launchers) if we can make insertions to Firefox's "places.sqlite", a SQLite3 database. That's somewhat non-trivial, but it could be done with a Python script and the pysqlite bindings. I'd be willing to work on it since I could personally use some more familiarity with Python.

**Comment by ageis** [comment]
Found some useful example code: https://raw.githubusercontent.com/kralo/uni-ms-linux-custom/master/add-firefox-bookmarks.py

**Comment by ageis** [comment]
So I've found that it will not be possible for us to have our own sub menu under the Applications main menu, since Tails does not follow the Gnome/XDG directories spec and amnesia can't write to /etc/xdg/menus. However, we have the next best thing. The launchers can go under Applications>Internet by including the Network category in the .desktop files and copying them persistently to .local/share/applications. This is implemented and working in my latest commit in #955.

**Comment by conorsch** [comment]
SecureDrop 0.3.7 included an overhaul of the Tails setup script (#1318), and desktop icons are now installed by default for the Source and Document Interfaces on both the Admin and Journalist Workstations. These desktop icons persist through reboots on both platforms, so the original intent of this issue has been achieved. Closing.

**Comment by ageis** [comment]
@conorsch It's funny that you just closed this, cause I was in the midst of working on a little Python script that makes Firefox bookmark insertions. =P

**Comment by conorsch** [comment]
@ageis synchronicity! :metal:
