### ISSUE TITLE
No directions for the long term storage tails usb

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#934]
The install doc mentions the long term offline storage tails usb but not how to set it up or what it use for. (The long term storage tails usb is another airgapped Tails usb that also has a copy of the application's private gpg key and instance backup).

**Comment by flamsmark** [comment]
I don't remember reading about this at all in the install instructions.

**Comment by conorsch** [comment]
Tracking improvements to docs in:

* #606
* #1127 
* #1128 
* #1446
