### ISSUE TITLE
Document tails upgrade process for airgapped SVS

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#937]
We should create a separate document for how to upgrade the airgapped tails usb since it is different than for networked tails USBs.

**Comment by redshiftzero** [comment]
This exists here: https://docs.securedrop.org/en/stable/upgrade_to_tails_2x.html. Closing.

**Comment by fowlslegs** [comment]
https://www.wired.com/2015/11/securedrop-leak-tool-produces-a-massive-trove-of-prison-docs/
