### ISSUE TITLE
reboot_into_grsec is not idempotent

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#938]
It will reboot during the playbook even if grsec is already installed and running. Need to register a variable to check if reboot is required (see cron_apt.yml).

**Comment by garrettr** [comment]
@dolanjs Should we nominate this for 0.3.2? Doesn't seem like it would affect existing installs, but will make re-provisioning less annoying.

**Comment by conorsch** [comment]
Resolved by #939.
