### ISSUE TITLE
apparmor profile should support ssl

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#949]
The apparmor profile currently will not allow orgs to enable ssl for their source/document interface. If the org locally modifies the profile then during the next update to securedrop-app-code will override those changes. We should add support for ssl apache modules and access to read the certs in the apparmor profile so it doesn't interfere with any sites that are using SSL

**Comment by dolanjs** [comment]
Adding this should work for most orgs using ssl:
```
<   /etc/apache2/mods-available/ssl.conf r,
<   /etc/apache2/mods-available/ssl.load r,
<   /etc/apache2/mods-available/socache_shmcb.load r,
85d81
<   /run/lock/apache2/ssl-cache.* rw,
123d118
<   /var/lib/ssl/* r,
```

**Comment by dolanjs** [comment]
the ssl module also requires the setenvif module which will need to be allowed in the apparmor profile.

**Comment by garrettr** [comment]
@dolanjs Should we nominate this for 0.3.2 or let it wait for 0.4?

**Comment by dolanjs** [comment]
@garrettr This needs to happen for 0.3.2 or it will break the the existing installs that use SSL on their source interface, since the apparmor profile is included as part of the securedrop-app-code deb package.

**Comment by dolanjs** [comment]
After testing was found that `k` needs to be added to this line for setting a lock 
```
/run/lock/apache2/ssl-cache.* rwk,
```
