### ISSUE TITLE
Google step up verification breaks OSSEC alerts

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#950]
Google and other smtp relays often (and sometimes randomly) require step up verification for accounts which will break the ossec alerts until the admin manually intervenes. It would be nice to not require 3rd party smtp relays for the orgs who don't run their own smtp relays or somehow else avoid OSSEC alerts from being marked as spam.

**Comment by dolanjs** [comment]
To avoid the step up verification issues with google as the smtp relay
 * Don't use tor when creating the account
 * Enable 2 step verification for the account
 * Use an app specific password for sasl config

These points are already described here: https://github.com/freedomofpress/securedrop/blob/develop/docs/ossec_alerts.md#using-gmail-for-ossec-alerts

**Comment by fowlslegs** [comment]
Resolved by 14f2df0d1.

**Comment by fowlslegs** [comment]
Woops, `git blame` isn't the best sometimes. That was just us moving from `.md` to `.rst`. The issue does seem to be resolved as updated instructions with these considerations in mind are now present.
