### ISSUE TITLE
Provide visual notification for testing environments

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#963]
We often temporarily stand up SecureDrop instances for the purpose of demoing or testing. We don't advertise these instances to the public, so we don't expect people to mistake them for legitimate SecureDrop instances - you would have to use a deep web search engine, or be running some kind of interesting hidden service survey, to find them. However, it appears that sometimes people get [confused](https://twitter.com/dolanjs/status/581993449454329857).

I propose that we add a configuration option to the Ansible playbooks to trigger marking an instance as a test instance. The instance should prominently display a warning explaining that it is a test instance and that it should not be used to submit confidential information.

We could make this configuration option on by default for the staging environment, which should eliminate this problem in the future.

**Comment by conorsch** [comment]
We can add a custom default logo with a **TEST** watermark on it and push that out to the staging environments. Once we have custom text support (#774) we can extend the visual notification of testing instances there, as well.

Related: #911

**Comment by conorsch** [comment]
@harlo made a fine alternative logo with a **TEST** watermark that should be reused for this task, once the playbooks have been modified to support the logo. Probably the cleanest implementation is overriding a default var in the dev and staging playbooks. That way, nothing needs to be changed in the prod info, and all environments will have the intended logo.

**Comment by garrettr** [comment]
We should address this, but I think there are more important issues to address for 0.4.

**Comment by redshiftzero** [comment]
Closing since notification of a test environment was done through the new custom notification feature merged in #1399 in 6c18088672784b78c9af10cf8993a8535a0370f0
