### ISSUE TITLE
Apt upgrade via Ansible could break SSH over Tor sessions

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#964]
There is a small edge case around the cron-apt tasks in the ansible playbook for existing installs that could stop the tor service and lock everyone out of the system until the servers are manually rebooted.

For existing installs subsequent ansible-playbook runs use ssh over a tor sessions. If there is an update to the tor package when the ansible playbook is ran again the cron-apt tasks will attempt to install them. The pre-install script for the tor package will stop tor which will also kill the ssh over tor session that ansible is using. This will leave tor stopped on the server until it is manually rebooted.

**Comment by conorsch** [comment]
There are two relevant packages here:

* `tor`
* `deb.torproject.org-keyring`

If `tor` is upgraded, the automatic service restart will break the SSH connection and leave the machine inaccessible over SSH. The nightly server reboots will restore connectivity, but that still means there's up to a 24-hour window where the machines are inaccessible, unless the Admin can physically reboot.

As a precaution, we can mark the `tor` package with `hold` prior to the apt upgrade, then release the hold immediately after upgrading. Doing so will ensure that updates to `tor` are installed only via `cron-apt`, and not interactively during Ansible playbook runs. 

The hold/release strategy would prevent existing installations from being locked out during a routine playbook run, but would also have the undesirable side-effect that fresh installations would have an outdated version of tor until the first nightly reboot. If we can flag or detect a first-time installation, then we can intelligently hold/release the package as necessary.
