### ISSUE TITLE
Sign OSSEC alerts

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#966]
Currently the OSSEC alerts are encrypted to the admin but are not signed. This should be a relatively straight forward to do. Ansible can generate a gpg key without a passphrase and then the send_encrypted_alarms.sh script can be modified to also sign all the emails it sends.

**Comment by garrettr** [comment]
The goal of signing the emails would be to prevent someone from sending spoofed OSSEC alerts to the admin. Are there any other benefits?

**Comment by garrettr** [comment]
This could still be useful, but I think there are more important issues to focus on for 0.4.

**Comment by fowlslegs** [comment]
> The goal of signing the emails would be to prevent someone from sending spoofed OSSEC alerts to the admin.

Sending spoofed OSSEC alerts in combination with intercepting and dropping authentic OSSEC ones is one way to essentially completely defeat the monitoring system without compromising the monitor server. Of course, even with signatures important messages could still be intercepted and dropped, which is almost equivalently bad. The subject line itself is enough to determine which message(s) you'd need to block to hide your tracks if you're a powerful adversary who has (i) compromised the app server and (ii) can intercept email, but (iii) cannot compromise the monitor server which has a much smaller attack surface than the app server.

This problem could be solved by integrating a hash chain mechanism into the future admin client. Each message m<sub>n</sub> is accompanied by a hash h(m<sub>n</sub> || m<sub>n-1</sub>) and both parts are signed. This way, notifications cannot be censored without detection. Further, we'd ditch GPG for a more modern encrypted communication protocol in such a setting that would provide full-content encryption (as well as many other desirable properties).

**Comment by eloquence** [comment]
> Of course, even with signatures important messages could still be intercepted and dropped, which is almost equivalently bad. 

That I think is the crucial point here. Plus, having admins pay attention to encrypted OSSEC alerts is difficult enough as it is without adding the complexity of managing another keypair. Per discussion with @conorsch we're unlikely to implement in this form, but feel free to reopen if you want to make a strong counterargument.
