### ISSUE TITLE
Document interface no longer flags new submissions as unread

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#969]
According to one of the current installations, the document interface no longer flags which submissions are new. They say the behavior appears to have changed when they auto-updated to 0.3.1.

**Comment by pemulis** [comment]
I've also seen this issue.

**Comment by garrettr** [comment]
@pemulis Thanks, I was able to reproduce it yesterday as well but was then derailed dealing with 0.3.2. Will work on it more today and tomorrow.

**Comment by garrettr** [comment]
Accidentally pushed this to develop. The commit is good, but we need to add tests to prevent this regression from recurring in the future.

**Comment by garrettr** [comment]
Added tests in #987.
