### ISSUE TITLE
Convert SecureDrop visualization diagram to an open format

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#976]
Follow-up to #975. Ideally any and all diagrams would have the following properties:

1. Open format
2. Version-controllable (e.g. XML, not a binary format)
3. Easily editable by potential contributors, ideally with open-source software. [draw.io][1] is also a nice solution that we have been using for some other things.

[1]: http://draw.io/

**Comment by mark-in** [comment]
This issue seems to be resolved by #1211.

**Comment by conorsch** [comment]
@ghost Yup, that SVG you contributed certainly does the trick. Thanks!
